### ISSUE TITLE
Conflict with angular models and bug with ngModel

### ISSUE THREAD

**Issue by Deadly0** [jagi/meteor-astronomy#102]
User document:
![bugfa](https://cloud.githubusercontent.com/assets/4887213/10007530/b884733e-60ce-11e5-96b4-8a51317819a0.png)

1. `username` field was modefied by `ngModel` Angular directive, but Astronomy sees no changes (`_modifiers` filed is empty) and `save()` doesn't work.

2. Conflict with Angular-Meteor model. Both have `save` method and it's impossible to call both.

**Comment by jagi** [comment]
1. You can read in the [documentation](http://astronomy.meteor.com/#set) that you have always use the `set` method to set values. So if you set values directly, Astronomy will not know what to update.

2. It means that you can't use both. The only thing you could do is hooking somehow into the process of setting values on Angular model and update Astronomy mode accordingly. You would have to store an Astronomy class instance in some property in the Angular model.

```js
var angularModel = {
  _astronomy: new AstronomyClass()
};

/* ... */

// On setting a value in Angular
angularModel._astronomy.set(fieldName, fieldValue);
```

I don't like Angular and I'm not gonna support it officially. However, as I wrote you can make some workarounds. IMHO Angular is messy and not intuitive :)

**Comment by Deadly0** [comment]
@jagi I found other big problems with angular. Astronomy doesn't work on client with angular at all. Is it possible to disable automatic injection of astonomy class on client, but keep working on server in methods? I know about `{transform: null}`, but it doesn't work with angular on client. Need an config option like `Astro.config.injectOnClient = false`. Thank you!

**Comment by jagi** [comment]
You can just define classes only on the server by putting them in the `server` directory or in the if statement:

```js
if (Meteor.isServer) {
  Post = Astro.Class({ /* ... */ });
}
```
