### ISSUE TITLE
Is the wiki being replaced?

### ISSUE THREAD

**Issue by kahmali** [jagi/meteor-astronomy#103]
It appears most of the wiki has been removed. Do you intend to move the documentation elsewhere? Sorry if I missed an announcement somewhere. 

**EDIT: I was specifically looking for the documentation for the Validators module**

**Comment by VladShcherbin** [comment]
@kahmali maybe [this one](http://astronomy.meteor.com/)

**Comment by kahmali** [comment]
Thanks so much @VladShcherbin! Just what I was looking for. Looks much better in this format. Keep up the great work @jagi!

**Comment by jagi** [comment]
I'm moving everything under one website with a documentation. I'm preparing for 1.0.0 release. It should appear next week. The new documentation is for 1.0.0 version so I encourage you to move on to it. Here https://github.com/jagi/meteor-astronomy/issues/97 you can find more info how to move.

Thanks @VladShcherbin for fast reply :-).
