### ISSUE TITLE
Modules Wiki page is missing

### ISSUE THREAD

**Issue by waxhell** [jagi/meteor-astronomy#105]
The readme.md refers to the Modules wiki for more details on modules, however that page is missing:

https://github.com/jagi/meteor-astronomy/wiki/Modules

**Comment by frabrunelle** [comment]
@waxhell: The Modules documentation has been moved here: http://astronomy.meteor.com/#modules

See #103.

**Comment by jagi** [comment]
Yes exactly :). Maybe I removed documentation too early and didn't inform about it. However in a few days I will be releasing 1.0.0.
