### ISSUE TITLE
Allow the old way of nesting fields in astronomy@1.0.0

### ISSUE THREAD

**Issue by parhelium** [jagi/meteor-astronomy#106]
```
SiteConfigShop = new Astro.Class( {
    name: 'SiteConfigShop',
    fields: {
        'type'                        : t( 'string', 'catalog-pl' ),
        'pages'                       : t( 'number', 20 ),
        'products'                    : t( 'array', [] ),
        'products.$'                  : t( 'string'),
        'language'                          : t( 'array', 'pl' ),
        'languages'                        : t( 'array',  SSS.consts.LANGUAGES ),
        'prices'                               : t( 'object'),
        'prices.percentages'          : t( 'object'),
        'prices.percentages.a'        : t( 'number', 0),
        'prices.percentages.b'        : t( 'number', 0),
        'prices.percentages.c'        : t( 'number', 80),
        'prices.currency'                 : t( 'string', 'pln'),
        'prices.exchangeRate'        : t( 'number', 1),

    }
} )
```

@jagi  I really want to be able to define schema as above. Is it possible to have also old way of defining nested fields ?
Creating new Astro.Class for each nested object simply doesn't make sense here - especially from readability perspective...

For me it will be great to use nested fields in old way and new way in the same time.

**Comment by jagi** [comment]
Hmm as you write about it I think that it would be a good idea to allow the old way. Right now it's not possible but should be quite easy to implement. I will parse the old way of defining fields and create a new schema automatically.

Remember that you can always define nested class inline:

```js
SiteConfigShop = new Astro.Class({
  name: 'SiteConfigShop',
  fields: {
    'type'               : t( 'string', 'catalog-pl' ),
    'pages'              : t( 'number', 20 ),
    'products'           : t( 'array', [] ),
    'products.$'         : t( 'string'),
    'language'           : t( 'array', 'pl' ),
    'languages'          : t( 'array',  SSS.consts.LANGUAGES ),
    'prices' : {
      type: 'object',
      nested: {
        name: 'Prices',
        fields: {
          'percentages' : {
            name: 'Percentages',
            fields: {
              'a'        : t( 'number', 0 ),
              'b'        : t( 'number', 0 ),
              'c'        : t( 'number', 80 ),
            }
          },
          'currency'     : t( 'string', 'pln'),
          'exchangeRate' : t( 'number', 1 )
        }
      }
    }
  }
});
```

However it's not as clear as the old approach.

**Comment by parhelium** [comment]
It is all about having clear schema, so the old way is prefered. Thank you for your hard work !

**Comment by jagi** [comment]
Yes I agree that it's a lot more clear. However internally I had to change the way it works to make internals more clear and less error prune. So I just have to allow the old way and parse schema to mach the new way :)

No problem :). This feature should appear tomorrow if everything will go according to my plan :)

**Comment by parhelium** [comment]
@jagi I keep finger crossed !

**Comment by jagi** [comment]
Done. It will appear in the rc-6. However it should be taken in mind that each field in the form of `field.nestedField` or `field.$.nestedField` will have to go through additional parser so it may increase load time. I'm planning to introduce a feature of building schema during the application build. However, I think that it will appear in 2.0 version of Astronomy because it may be hard to implement it for the current version.
