### ISSUE TITLE
Validators wiki is gone

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#107]
Hi,
I just started a new project and giving astronomy a go for the first time.
I added the validators package and had a quick look at the validators wiki. Looked promising.
However, the day after the whole wiki was gone, and still is.
Where did it go?

Thanks!

**Comment by shadowRR** [comment]
Since @jagi has updated to the actual testing version of the new Astronomy (V.1.0.0), the documentation has moved to this page for the validators : http://astronomy.meteor.com/#validators.

Careful though, some of the functions on this doc are only available with the new version.

**Comment by jazzdragon** [comment]
Awesome thanks!
It would be great to update the atmosphere and github links.

**Comment by jazzdragon** [comment]
https://github.com/jagi/meteor-astronomy-validators/pull/29

**Comment by jagi** [comment]
Yes, sorry I should do it right away. I will update all links today or tomorrow.
