### ISSUE TITLE
Question regarding Meteor.userId() in Astronomy events

### ISSUE THREAD

**Issue by cjsauer** [jagi/meteor-astronomy#108]
I started this question here https://github.com/jagi/meteor-astronomy/issues/72#issuecomment-142810655

@jagi, your recommendation doesn't seem to work. I moved the `Doc.save()` call into a Meteor method, but I still get the same error that I must call `Meteor.userId()` in a method. Do I need to do this?

```javascript
Meteor.methods({
  '/doc/new': function(doc) {
    doc.set('userId', Meteor.userId());
    doc.save();
  }
});
```

It won't let me call it inside the `beforeInsert` event, which is where I'd really like it to live. It makes the most sense from a design perspective. 

I'd like to do this:

```javascript
Meteor.methods({
  '/doc/new': function(doc) {
    doc.save();
  }
});

// ...
// Inside Astronomy definition
  events: {
    'beforeInsert': function(e) {
      this.set('userId', Meteor.userId());
    }
  },
// ...
```

**Comment by jagi** [comment]
Can you create a reproduction repository?

**Comment by jagi** [comment]
I've made an example for you showing that it works https://github.com/jagi/astro-user
