### ISSUE TITLE
Methods on collections

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#109]
Hi,
I was wondering if there is a way to have methods that would be applied on whole collections. Pseudo code:

Posts = new Mongo.Collection('posts')
Post = Astronomy.Class({
  fields: ['title', 'content'],
  methods: {
    getOnlyTitles: function(){
      return this.title
    }
  }
})

Then do something like:
titles = Posts.find().fetch().getOnlyTitles()
// titles === ['title 1', 'title 2'...]

Thanks!

**Comment by jagi** [comment]
Notice that you are trying to execute the `getOnlyTitles()` method on an array of documents. You would have to extend the `Array` prototype to do that which is a bad idea. You can create something else, something like collection helper.

```js
Posts.getOnlyTitles = function(selector) {
  selector = selector || {};
  var titles = [];

  this.find(selector, {
    fields: {title: 1}
  }).forEach(function(doc) {
    titles.push(doc.title);
  });

  return titles;
};
```
