### ISSUE TITLE
Autopublish causes exceptions serverside with RC.6

### ISSUE THREAD

**Issue by shwaydogg** [jagi/meteor-astronomy#110]
I setup the RC packages below and then when I turn autopublish with meteor toys, constellation or the autopublish package itself and connect on the client there's a never ending flow on the serverside of the following exception:

`Got exception while polling query: Error: EJSON.parse argument should be a string`

package changes:
```
-jagi:astronomy@0.12.1
-jagi:astronomy-relations@0.1.2
-jagi:astronomy-simple-validators@0.6.0
-jagi:astronomy-validators@0.10.10
+jagi:astronomy@1.0.0-rc.6
+jagi:astronomy-simple-validators@1.0.0-rc.2
+jagi:astronomy-slug-behavior@1.0.0-rc.2
+jagi:astronomy-softremove-behavior@1.0.0-rc.1
+jagi:astronomy-timestamp-behavior@1.0.0-rc.1
+jagi:astronomy-validators@1.0.0-rc.4
```

**Comment by jagi** [comment]
Please create a reproduction repository. I don't know what can be a reason for this error without having the sample project.
