### ISSUE TITLE
Update on nested class with 'Direct Collection Access'

### ISSUE THREAD

**Issue by shadowRR** [jagi/meteor-astronomy#111]
Hey @jagi,

I was wondering how to use you're direct access methods when trying to update fields on a nested class ? Short example :
```
AstroClassToUpdate.update({
       'item._id': _idToUpdate
   }, {
          $set: {
                'item.$.price': priceValue,
                'item.$.quantity': quantityValue
      }
}, {multi : true});
```
Now if i executed the same query directly to mongo, it works as expected. I'm guessing it's not working with the update direct collection access method because of how nested class are handled ?

**Comment by jagi** [comment]
Usage of the "direct collection access" is limited and yes your code will not work. Probably I will be working on it in the future and I will try to add support for more features. However, right now it has to work that way.

**Comment by shadowRR** [comment]
Ok thanks ;)
