### ISSUE TITLE
Integration with AutoForms?

### ISSUE THREAD

**Issue by derwaldgeist** [jagi/meteor-astronomy#112]
Thanks to @serkandurusoy I finally found this amazing package - after spending a couple of days trying to implement my own ODM mapping mechanisms as I was dearly missing something like that. Big thumbs up, in fact I would expect something like Astronomy being part of the core Meteor framework.

One question came to my mind, and I think you mentioned somewhere that you're already working at it: an integration with @aldeed's autoform package. For me, this is the missing link to replace SimpleSchema completely in my app (although I really liked it - it was better than having no validation at all).

**Comment by serkandurusoy** [comment]
@derwaldgeist you can follow the progress on forms over at issue #14 but one thing's for sure that, *autoform integration* is not in the early roadmap. Perhaps in the future. Instead, an astronomy-native forms implementation is in the works.

In the meantime, you can check out https://github.com/usefulio/forms/ for a new form-kid-on-the-block which looks very promising.

**Comment by derwaldgeist** [comment]
Thanks for the quick reply! I don't mind if it's an autoform integration or a home-grown solution. Did not find #14, so I am closing this dup now.

**Comment by jagi** [comment]
Hi, I don't have plans to make integration with Aldeed's autoforms. I will be creating my own forms package. I hope I will be working closely with Useful.io to make it the best choice for production. There are a few very important:

- Auto forms generation - It won't be auto generating form fields. In fact it's almost impossible to cover all possible use cases. I have experience with frameworks auto generating forms and it was almost impossible to fit my needs if it was something more complicated than a regular form.
- Tools and helpers - Instead I want to focus on giving tools that will make it easier to create forms. Like in Useful.io's forms package it will be auto binding a model with a form. And also giving some tools that will help set input's attributes.

If it goes about model package being a part of Meteor platform. There was a discussion about it [here](https://forums.meteor.com/t/please-give-meteor-core-a-build-in-orm-support-object-relational-mapping/10302/22)
