### ISSUE TITLE
Call to set() on nested array field does not work within model methods

### ISSUE THREAD

**Issue by cjsauer** [jagi/meteor-astronomy#114]
Take the code given below as an example:

```javascript
UserProfile = Astronomy.createClass({
  name: 'UserProfile',
  /* No collection attribute */
  fields: {
    someArray: {
      type: 'array',
      nested: 'string',
      default() {
        return [];
      }
    },

    someString: 'string'
  }
});

User = Astronomy.createClass({
  name: 'User',
  // Use the built-in Accounts' user collection
  collection: Meteor.users,
  fields: {
    username: 'string',
    emails: 'array',
    createdAt: 'date',
    services: 'object',
    profile: {
      type: 'object',
      nested: 'UserProfile',
      default() {
        return {};
      }
    }
  },

  methods: {
    someMethod() {
      console.log(this.profile.get('someString'));
      console.log(this.profile.get('someArray'));
      this.profile.set('someString', 'TEST');
      this.profile.set('someArray', ['Not Empty']);
      this.save();
      console.log(this.profile.get('someString'));
      console.log(this.profile.get('someArray'));
      return this;
    }
  }
});
```

I've observed that `this.profile.get('someArray')` is NOT printing the correct value of `['Not Empty']` after saving. Although `this.profile.get('someString')` *is* being set, so it seems to only be affecting array types in nested fields.

The workaround is to use: 

```javascript
this.profile.someArray = ['Not Empty']

**Comment by jagi** [comment]
Can you create a reproduction repository? It will be easier for me to check it out.

**Comment by jagi** [comment]
Please create a reproduction repository as it's done for Meteor https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by cjsauer** [comment]
Sorry for the delay: 
https://github.com/cjsauer/astronomy-issue-114

**Comment by jagi** [comment]
Ok I will take a look at it tomorrow

**Comment by jagi** [comment]
Ok situation looks like follows. Instead splicing array you should use the `pull` method to remove element from the array. However, when fixing your code I've noticed a bug in Astronomy that I have to fix. I will publish a fix (probably today). So after that you will be able to use the `pull` method properly.

**Comment by jagi** [comment]
Ok you can use the 1.1.0 version of Astronomy and the `pull` method. It will work.
