### ISSUE TITLE
How to remove specific string from an array?

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#116]
Let's say I have a collection called Uploads:

```
Uploads = Astro.Class({
  name: 'Upload',
  collection: Uploads,
  fields: {
    tags: {
      type: 'array',
      default() { return [] }
    }
  }
});
```

And I want to locate a specific upload and remove a specific tag, either by its index or its name (either is fine). What's the proper way to do this in Astronomy 1.0? I can't use `pop` because the tag might be in the middle of the array. The only way I can think of is this:

    Uploads.update(uploadId, {$pull: {tags: tagName}});

I was just wondering if there was some way to do it on a single item via Astro's class:

```
u = Uploads.find(uploadId);
u.pull('tags', tagName); // I know pull() doesn't exist
u.save();
```

**Comment by jagi** [comment]
Hi, Astronomy does not implement all methods of MongoDB yet. But it will in the future. It isn't hard to implement every possible method from MongoDB. Right now the best way to do it is:

```js
var u = Uploads.findOne(uploadId);
u.set('tags', _.without(u.tags, tagName);
u.save();
```

I know that it saves again entire array into database and it can be not so fast. Of course you can also use your solution. As long as it's data removal it does not need to check any constraints.

I will add the `pull` method to the features to implement.

**Comment by ffxsam** [comment]
Sounds good. Thanks, Astronomy is amazing!

**Comment by jagi** [comment]
Thanks :)

**Comment by jagi** [comment]
The `pull` method was added in the 1.0.2 version.  You can test it out. It isn't documented yet but will  be.

```js
var doc = Docs.findOne();
doc.pull('tags', tagToPull);
doc.save();
```

**Comment by darko-mijic** [comment]
Please add this to documentation.

**Comment by jagi** [comment]
Yes I have it in plans. I have a lot things to do, so I've left it for later. I will update it today :)
