### ISSUE TITLE
Data bound to type / Influence on EJSON-ification

### ISSUE THREAD

**Issue by derwaldgeist** [jagi/meteor-astronomy#117]
First of all: let me thank you for this amazing package! It solves many of the problems I've been trying to solve myself with a home-grown implementation, but this package is so much better.

There are two things, however, I am missing compared to my own implementation of such a model framework, but could be easily extended in Astrononomy:

1. I would like to store meta-data with the type itself, i.e. data that is bound to the type instead of its instances. I am using this to store information like the templates that render this specific type in a certain context. This might be a case for a an extension / a behaviour. I will do this now by extending the constructor of the classes (as I did with my own framework), but I think it would be better to have a way of defining custom type-specific meta-data when defining the type itself.

2. Having more influence on the EJSON-ification of the type. For instance, EJSON allows to define your own method for deciding whether two instances of a type are equal (```equals()```). Maybe this could be done via an event hook?

Another idea for improvement: I think the current syntax of set() and get() is a bit confusing, since they are not really doing the same thing and the user has to make sure that set() is in fact used to set values, whereas for a normal get it is better to use the dot syntax, since get() delivers raw documents. Maybe it would be a better idea to use ES6 getters and setters for all properties and store the actual values in a shadow property map? This would allow the user to set values using dot syntax as well, so getting and setting would behave just the same.

But that's all kind of "nitpicking". The package itself ist great, I will now move my home-grown implementation to this new way of handling models.

**Comment by jagi** [comment]
Hi, thanks :)

1. Of course as you said you can just add some properties to the class, however it could be made possible by an extension/module. It's rather not good idea to make behavior for that. It should make use of the `initDefinition` and `initClass` events and extend a class with some static properties. In the class schema you could define it the following way:

```js
User = Astro.Class({
  /* ... */,
  statics: {
    staticProperty: 'value',
    staticMethod: function() {}
  }
});
```

```js
Astro.eventManager.on('initClass', function() {
  var Class = this;
  var schemaDefinitions = Class.definitions;
  _.each(schemaDefinitions, function(schemaDefinition) {
    _.extend(Class, schemaDefinition.statics);
  });
});
```

It's quite simple module that could land in the core package. If you want to contribute any PR would be welcome :).

2. If you want to provide a custom `equals()` method then you can just provide it in the class definition.

```js
User = Astro.Class({
  /* ... */
  methods: {
    equals: function(doc) {
      return true; // Always equal
    }
  }
});

EJSON.equals(doc1, doc2); // true
```

3. Yes it may be a little bit confusing at the beginning. Before the version 1.0.0 the `get()` method was returning NON plain value. And it worked exactly as you said (using the ES6 getters and setters) but it caused more problems than benefits. Moreover creating a polyfill for setters/getters is impossible, so it didn't work in older browsers, so I've decided to never use setters/getters until the browsers support will be good enough.
However, when you remember that you always have to set values using built in functions like `set`, `push`, `inc` etc. and you can get values just by direct access then you will get accustomed to it :).
I have some ideas for improvements in this area but they would break backward compatibility with Astronomy 1.0 so these improvements will appear in Astronomy 2.0 :) but can predict any date :P

**Comment by derwaldgeist** [comment]
Thanks for these explanations!

**Comment by jagi** [comment]
No problem :)

**Comment by dalcib** [comment]
Meteor 1.2 uses Babel to compile ES6 code like getters and setters to ES5 for old browsers. 
So I think we don't need to get stuck to it. 
Direct access to properties is the number one feature that I would like to see in Astronomy.

**Comment by jagi** [comment]
@dalcib no Babel does not transpile getters and setters. It's not possible to transpile this feature.
You can access properties directly right now if you read them. However you have to use `set`, `push`, `inc` etc. methods to manipulate data. I have some ideas to replace it but as I said in future versions :)

**Comment by dalcib** [comment]
Ok @jagi. Thank's.
