### ISSUE TITLE
optional: true and Validators.required() not working as expected

### ISSUE THREAD

**Issue by derwaldgeist** [jagi/meteor-astronomy#118]
I expected that any field that is *not* marked with
```optional: true```
has to be defined when instantiating an object.

But I have no problems to create the object and even save it to Mongo, if a non-optional field value is missing. In Mongo, the field is there, but it is set to ```null```.

Even if I add
```
validator: Validators.required()
```
to the field, I do not get an error if the field is missing. And also ```validate()``` does not report an error. Is this behavior intended? I've added both the core and the validator packages to my app.

**Comment by jagi** [comment]
The problem with the `required` validator is more complex. When Astronomy was in beta there was no `optional` option for a field. If a field value is `null` and a field is marked as `optional = true` then it won't be validated. If a field is `null` and a field is marked as `optional = false` then it will be validated and in such situation the `required` validator makes sense. So the `required` validator is only for non-optional fields. And why at all do we need this validator? It's just to display error message under a field "Field is required". That's it.

**Comment by derwaldgeist** [comment]
Ok, thanks for this info. But why am I able to instantiate (and even save) an object to the database, if a field that wasn't marked with ```optional: true``` is missing? I would expect that in this case both instantiation and save would fail. Maybe I'm biased, since I was using SimpleSchema until now and this was exactly the behaviour of this framework in this case. And I found this behaviour quite natural.

**Comment by jagi** [comment]
You know it's because some assumptions that I've made at the beginning and I didn't want to change that. I know it may not be as intuitive. I was thinking about some flag in the config that would make exactly what are you talking about, that would prevent saving a document if required fields are not filled. I will probably add it in next version.

**Comment by derwaldgeist** [comment]
OK, fine :+1:

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.
