### ISSUE TITLE
Trying to set a value of the "_modifiers" field that does not exist in the "Video" class

### ISSUE THREAD

**Issue by mplatts** [jagi/meteor-astronomy#119]
Any time I find a document it gives me these errors in the console:

<img width="652" alt="screen shot 2015-10-05 at 1 28 26 pm" src="https://cloud.githubusercontent.com/assets/184383/10272011/0e1b12e4-6b65-11e5-9de0-dc9735936db6.png">

```js
Videos = new Mongo.Collection('videos');

Video = Astro.Class({
  name: 'Video',
  collection: Videos,
  behaviors: {
    timestamp: {},
    slug: {
      fieldName: 'name',
      slugFieldName: 'slug',
      canUpdate: true,
      unique: true,
      separator: '-'
    }
  },
  methods: {},
  fields: {
    tagIds: {
      type: 'array',
      index: 1,
      "default": function() {
        return [];
      },
      validators: [Validators.array()]
    },
    name: {
      type: 'string',
      "default": '',
      validators: [Validators.required(), Validators.string(), Validators.maxLength(50), Validators.minLength(2)]
    },
    description: {
      type: 'string',
      validators: [Validators.string()]
    },
    imageUrl: {
      type: 'string',
      validators: [Validators.string()]
    },
    isPublished: {
      type: 'boolean',
      "default": false,
      validators: [Validators.boolean()]
    },
    publishedDate: {
      type: 'date',
      "default": function() {
        return new Date;
      },
      validators: [Validators.date()]
    },
    isDummyData: {
      type: 'boolean',
      "default": false,
      validators: [Validators.boolean()]
    }
  }
});
```

**Comment by jagi** [comment]
Hi, take a look at this section in documentation http://astronomy.jagi.io/#publications and this one http://astronomy.jagi.io/#warnings. It should solve your problem.

**Comment by mplatts** [comment]
Thanks, that fixed it except for the users collection, which still does it only when I refresh while signed in (as opposed to signing in, where it's fine). Will keep trying to fix

**Comment by jagi** [comment]
Ok let me know if you found solution for that. It's worth sharing with the community.

**Comment by JulianKingman** [comment]
Thanks, this was helpful. I'm curious, what effect does turning off transforms have, with regards to astronomy functionality?

**Comment by jagi** [comment]
@JulianKingman turning off transforms does not have huge effect on Astronomy functionality. Turning off transformation, only turns it off for the collection:

```js
Users.findOne(); // will return plain object with transformation turned off
```

However you can still do:

```js
User.findOne(); // will return instance of the astronomy class
```

In fact, if I would know about the problems I would turn off transformation for collections by default.
