### ISSUE TITLE
Not validating nested fields

### ISSUE THREAD

**Issue by matikucharski** [jagi/meteor-astronomy#121]
Hi.
I discovered problem with validating nested fields.
Here is meteorpad that describes my situation: http://meteorpad.com/pad/xzFTb3H55jSeF96tJ/Nested%20fields%20jag:astronomy%20validation

Generally speaking no fields that are in form of 'object.property' are validated.

During debugging I noticed that in `validate.js` file on line 20 you have `var fieldValidator = Class.getValidator(fieldName);` and it is always `undefined` for nested fields.
There is `fieldName==='language'` in my case but it would work if there would be `fieldName==='configuration.language'` or `Class` would be configuration object

**Comment by jagi** [comment]
It's not a correct way of defining validators:

```js
    validators: {
        'domains'                                   : v.object(),
        'domains.default'                           : v.string(),
        'domains.custom'                            : v.or( v.string(), v.null() ),
        'configuration'                             : v.object(),
        'configuration.type'                        : [v.string(), v.choice(['shop'])],
        'configuration.pages'                       : v.number(),
        'configuration.title'                       : v.string(),
        'configuration.language'                    : [v.required(), v.choice( ['pl', 'en', 'de'] )],
    },
```

There is no single line in a documentation that you can do so. You have to define a nested class to allow validation of nested fields http://astronomy.jagi.io/#nested-fields

You can define `parent.child` fields but it was done only for backward compatibility reason.

You can also do it in the following way:

```js
User = Astro.Class({
  /* ... */
  fields: {
    /* ... */
    'parent.child': {
      type: 'string',
      validator: Validator.minLength(3)
    }
  }
});
```

**Comment by matikucharski** [comment]
> You can define parent.child fields but it was done only for backward compatibility reason.

That's the reason I wrote it this way. I thought validation also will work with that. 
It looks like I need to rewrite my validators. Thanks anyway:)

**Comment by jagi** [comment]
No problem :)
