### ISSUE TITLE
Setting specific nested array element

### ISSUE THREAD

**Issue by darko-mijic** [jagi/meteor-astronomy#122]
I would like to be able to do something like this (data model is from your meteor-astronomy-examples):

``user.set("phones[0].name", "new name for phone");``

I know i can't manipulate array directly, without using .set() because then the _modifiers object will not updated.

Also i know i could use: 

``user.phones[0].set("name", "new name for phone");``

But that is not an elegant solution in context of the problem i would like to solve. I am extending your meteor-astronomy-examples project with reactivity and support for editing list of phones which are present in the model of your example but editing is not implemented.

Is there a plan to support syntax from first code block? Does it make sense to have something like that in your opinion?

Thanks :)

**Comment by jagi** [comment]
You can use:

```js
user.set('phones.0.name', 'new name for phone');
```

**Comment by JulianKingman** [comment]
I have a related question....

Last weekend I built an app at a hackathon using Astronomy, and I modeled my data kind of weirdly, where I had deeply nested data in each document (doc > array > objects > array > objects > strings/numbers). What ended up happening as a result is that I had to do some pretty hacky things with lodash to access the data I wanted, for example:

 var elmt = _.pluck(_.flatten(_.pluck(this.exercises, 'data')),'hr');

In retrospect, it occurs to me that with Astronomy's class system, I could have created a new nested class for 'data', and perhaps there would be a way to easily find and update nested arrays, sort of treating them like 'mini-collections'. Is there a way to do that with Astronomy?

**Comment by JulianKingman** [comment]
Oh, and if the obvious solution is to create an actual new collection, I'd point out that having a nested document reduces find requests and bypasses the need to add logic to relate different collections to each other.

**Comment by jagi** [comment]
@JulianKingman if I understand you correctly you are talking about nested classes what was described [here](http://astronomy.jagi.io/#nested-fields). You have to define schemas for nested fields. I didn't write what data you were looking for in a nested fields. But I assume that it's not something related with ORM/ODM system you are using. Event if you are using Astronomy you access fields the same way as it was plain JavaScript object.

```js
doc.arrayOfObject[0].array[1].stringField;
```
