### ISSUE TITLE
findOne doesn't return Astro obj

### ISSUE THREAD

**Issue by Kyezil** [jagi/meteor-astronomy#126]
I have been moving my current app from 0.12 to 1.0.0 but I don't know how to solve this error.
I have a simple Astro Class (Item) associated with a Mongo Collection (Items) but using `Items.findOne` doesn't return an instance of Item. I also tried `Item.findOne` (new from 1.0.0, I think) without success.

Here's my reproduction repository: https://github.com/Kyezil/astronomy-bug-startup
You need to run `meteor` twice because at first time nothing goes wrong (`new Item` is called).

Maybe I am doing something wrong as that used to work on 0.12 but it's driving me crazy.

**Comment by jagi** [comment]
You have to remove the `transform` option from the class schema and it will work

**Comment by Kyezil** [comment]
@jagi Thanks a lot. I thought `transform: true` was the option to set for the behaviour I wanted. So the error was due to the fact that `transform` is a function passed to the Collection (and true does nothing), am I wrong?

**Comment by jagi** [comment]
Yes it used to work that way but in 1.0 it has changed :-)
