### ISSUE TITLE
Cleaning data

### ISSUE THREAD

**Issue by camilosw** [jagi/meteor-astronomy#127]
One of the great features of Simple Schema is the data cleaning before validate and before insert or update https://github.com/aldeed/meteor-simple-schema#cleaning-data

Do you have plans to include a similar feature? I don't like to trim all my string fields manually.

**Comment by jagi** [comment]
Hi, what options would you like to see to be implemented in Astronomy? Real "data cleaning" should be rather a feature in the `forms` package than in ORM. I'm already preparing the `forms` package that will have the `clean` option.

Let's me describe how does it look in Astronomy:
- `filter`: Already works that way. There is no way of turning it off. It shouldn't be possible to change that behavior.
- `autoConvert`: Already works that way. There is no way of turning it off. It shouldn't be possible to change that behavior.
- `removeEmptyStrings`: Empty strings should be allowed. From what I've heard there were many problems with this feature.
- `trimStrings`: It's not a job for ORM but the `forms` package. Which should allow trimming white spaces before setting values on a document.
- `getAutoValues`: Default values are already implemented.
- `isModifier`: I think it's not applicable for Astronomy.
- `extendAutoValueContext`: Context of a function for a default value is always a document for which a default value is calculated.

**Comment by jcheroske** [comment]
Just wondering how the forms package is coming along. Are you going to release a React version?

**Comment by jagi** [comment]
Forms package was postponed to make Astronomy 2.0 first and later build stuff on it. There are several issues in 1.0 that can't be fixed and are already fixed in 2.0.

There is no need for React version as Astronomy is view independent.

There will be GraphQL version of Astronomy after official support for it in Meteor's Apollo project
