### ISSUE TITLE
extend and server only part of the class

### ISSUE THREAD

**Issue by martunta** [jagi/meteor-astronomy#128]
I wanted to use .extend function make part of Astronomy class secure, and to work only server side.

It does not seem to work fully. so far I have noticed two issues:
1) if I have field that is only defined server side, then in browser console there are warnings of type 
`Trying to set a value of the "secretField" field that does not exist in the "Falfsecret" class` warnings I could of course ignore, but it is not good that browser even knows that such field exists. It must be sent somehow to the client after all. Otherwise, serverside updates for this field work.

2) if I add a transform function via extend only in server side, it does not work. If I move it to client/server side class definition, it starts to work. 

My usecase is that I want to use Astronomy for simplicity, yet I want part of information only ever be available in server side. Each document that is retrieved from db, would have sensitive information cut and transformed, before document is sent to the client. 

Maybe there is some other ways how to achieve this to still be able to use Astronomy?

**Comment by jagi** [comment]
1) When you add some fields on the server and you publish them to the client then all fields are sent. You would have to define the `fields` option in the `find` method. It will solve a problem. However, as I think about it, it would be good to do it automatically. I can make use of the `Class.find()` and `Class.findOne()` methods and add the `fields` option automatically.

2) I will test it out. However, why do you need a different transform function on the server? It's because of the problem in the point number 1?

**Comment by martunta** [comment]
besically I want part of the class to be operated only on the server. There would be transform function that takes several sensitive fields and produce non-sensitive field from them. 
and opposite direction as well (though I am not sure how to do pre-insert or pre-update hook, yet.

In the documention .extend is mentioned in the context of having some stuff only on the server - if those fields are not actually only on the server, then what's the point of extend? what are the usecases you were thinking about when writing about server-only extends?

maybe I am wrong to us Astronomy this way at all? Maybe there is some other way how to do different server-only hooks, outside Astro classes?

**Comment by jagi** [comment]
The problem is not a class definition but publications. When you publish some documents even if they differ you have to make sure that you are not publishing them to the client. However I can automate that process.

You don't have to use a transform function for that. You can use event like `afterInit`. You can initialize compute values of some fields in this event.

**Comment by martunta** [comment]
how can I control publications within astronomy? I haven't thought about that part yet. And also where to do security checks.

I will try events like `afterInit` later tonight. That sounds good.

**Comment by jagi** [comment]
You don't control publications from the level of astronomy. You do it in Meteor using the `Meteor.publish()` method. There are many articles and tutorials about that.

**Comment by martunta** [comment]
I tried using event `afterInit` in server side `extend`. It was triggered, when I did server side `upsert`.
However, it seems that it is not triggered when I do `findOne` on client side. 

Also, in documentation there is `afterFind` event mentioned (but not documented), but it was also not triggered on client side `findOne`.

**Comment by jagi** [comment]
Your problem is more complicated than it seems to be. It's because how Meteor works. You can have extra fields on the server and publish only subset of these fields to the client. However, it doesn't work the other way. You can't have extra fields on the client.

Ok, I lied here a little bit. You can have extra fields but they should be computed from the already published fields. I don't know if you can publish not existing fields. In theory it should be possible to create such workaround but I haven't tested it.

Let's take a look at the example:

```js
Items = new Mongo.Collection('items');

Item = Astro.Class({
  name: 'Item',
  collection: Items,
  fields: {
    serverAndClient: 'string',
    computed: 'string'
  }
});

Meteor.methods({
  'add': function(doc) {
    doc.save();
  }
});

if (Meteor.isServer) {
  Item.extend({
    fields: {
      server: 'string',
    },
    events: {
      beforeSave: function() {
        this.set('computed', 'computed');
      }
    }
  });

  Meteor.publish('all', function() {
    return Items.find({}, {
      fields: {
        server: 0
      }
    });
  });
}

if (Meteor.isClient) {
  Meteor.startup(function() {
    Meteor.subscribe('all');
  });
}
```

As you can see, a field being `computed` has to be defined for both client and server. There is also the `server` only field. In the `beforeSave` method (on the server) you should compute a value of the `computed` field and save it into the database.

**Comment by martunta** [comment]
beforeSave I get, but how to do the same other way around? calculate value after reading `server` field from the database, then publish `computed` to the client, while keeping `server` field secret and only on server? 

I was thinking about maybe doing it within `Meteor.publish` function, as I couldn't get it to work with `afterInit` or `afterFind` events (as described in previous comment), but I have not yet figured out how to do it.

**Comment by jagi** [comment]
You just have to publish all fields except the server side fields. It's possible in the publish method as I made in the example above. Pasting it here, one more time.

```js
Meteor.publish('all', function() {
  return Items.find({}, {
    fields: {
      server: 0
    }
  });
});
```

It means that all fields will be published except the `server` field. I will try to do it automatically in future Astronomy releases.

**Comment by martunta** [comment]
yeah, not publishing secret field is simple. but how to do computed field, on server side, before returning data to client?

**Comment by martunta** [comment]
let me write a bit of pseudocode to ilustrate what I want to achieve:

client side:
```
Item = Astro.Class({
  name: 'Item',
  collection: Items,
  fields: {
    serverAndClient: 'string',
    computed: 'string'
  }
});
```

server side:
```
Item.extend({
    fields: {
      secret: 'string',
    }
  });

Item.transformAfterFind(doc) {
   doc.computed = encrypt(doc.secret); 
}
```

**Comment by jagi** [comment]
You have to compute a field value on a document save, on the server. It's not possible to compute this field on find.

**Comment by martunta** [comment]
Oh, I though that that's what the transform() function is for?

**Comment by jagi** [comment]
You can use the transform function to add extra fields but not in your case and only on the client. The `computed` field has to be computed from the `server` field. It's not send to the client, so the transform function won't be able to compute a value for the `computed` field. If you think that the transform function will be executed in the publication, then you are wrong. The `transform` function will be executed only on the client. In the publication you have to return a cursor which does not call the transform function. Only fetching a document executes the transform function.

Summing everything up. The only way to solve it is adding an extra server only field on the server. Add the `computed` field for both client and server. Compute a value of the `computed` field during the save operation on the server. Publish all fields except server only fields. That's it. May sound complicated but it's the only proper way I know.

**Comment by martunta** [comment]
Yeah. I think I will then have to save the computed field in db on save. Second option is to leave the field completely out of db model, and create it ad-hoc by calling server method. that of course discards all reactivity for particular field. 

anyway, thanks a lot for your help. Things are more clear now!

**Comment by jagi** [comment]
Yes. It's definitely better to choose the first option.

No problem :)

**Comment by martunta** [comment]
sorry for reopening this issue, but I have one more question. 

In your example you write 
```
Meteor.methods({
  'add': function(doc) {
    doc.save();
  }
});
```
I have tried it and it works well, when I do `Meteor.call('add',itemInstance);` from client side. But maybe it  would feel more natural to use, if it would be possibile to just call itemInstance.save() on the client and let Astronomy itself to figure out that there are server side only Class extension containing extra fields and event handlers, that need to be invoked as well? 

Currently just doing save() completely ignores all serverside class extension, which did not feel immediately obvious (for me that is)

**Comment by jagi** [comment]
To understand it you have to know how calling the `save` method on the client works in Meteor. In fact, it's calling the Meteor method. It takes the plain JavaScript object as an argument. I can't send Astronomy class. And on the server it does not know that it's Astronomy document.

The workaround for that is overriding the Mongo.Collection class. Which is not a good idea but I've decided that I will do it in Astronomy 2.0. I also hope that MDG will introduce collection hooks that would not force me to override the Collection class.

In addition, it's not good pattern to use the `save()` method directly. Many Meteor developers do not recommend using it. It's hard to secure your application using allow/deny rules. The methods approach is much better.
