### ISSUE TITLE
same logo as meteorionic

### ISSUE THREAD

**Issue by dstollie** [jagi/meteor-astronomy#13]
The icon in the logo of meteor astronomy really like like the icon of the logo of meteorionic. 

https://camo.githubusercontent.com/b4f32ff628fcfd0d3ebca06493ec86fdce3ff557/687474703a2f2f662e636c2e6c792f6974656d732f33393179343730383432305030483030316b31472f6d6574656f7269632e706e67

I wouldnt say its a big problem but I just to take note

**Comment by jagi** [comment]
To be honest I've never seen this logo before so I haven't been inspired by it. I don't think that it's a big problem as far as it's not commercial product. But thanks for informing.
