### ISSUE TITLE
Saving partial docs to the db

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#133]
When creating an instance of a class, it receives all the keys from the schema with a value of null.
So when saving to the db a document that doesn't have all the keys in the schema, it has all these fields with a value of null.
Is there a way to avoid that? even if I try to delete those keys before saving, I get them in the db.

On the same note, is there a way to unset fields on an update?

**Comment by jagi** [comment]
No you can't do that. If you want to unset some field you would have to use standard Mongo query. Astronomy is ORM/ODM and the data must be consistent. If you have some value in the schema it should also be present in the database.

**Comment by jazzdragon** [comment]
ok thanks

**Comment by jagi** [comment]
I've reminded myself right now that you can pass array of fields to the `save` method and save only these fields:

```js
doc.save(['fieldA', 'fieldB']);
```

However you would have to check which fields are `null` so I think it's not worth using in your situation.
