### ISSUE TITLE
afterInsert event on Meteor.users not working

### ISSUE THREAD

**Issue by ndarilek** [jagi/meteor-astronomy#134]
Using the suggested Meteor.users schema, I have the following on my server:

```
User.extend({
  fields: {
    services: "object"
  },
  events: {
    afterInsert: function(event) {
      console.log("Called", this)
    }
  }
})
```

I'm trying to add users to roles using alanning:roles, which unfortunately requires that the user exists, so `Accounts.onCreateUser` is out. Previously I had an after-insert collection-hook doing this, but I can't seem to get this bit of my app to run under Astronomy.

I also tried a string as the event name as featured in the docs, but that doesn't seem to have made a difference. What am I missing? The user isn't being created by `new User()` but I was still hoping that the events would fire regardless of how the data was inserted.

Thanks.

**Comment by jagi** [comment]
I need more code to help you. From this code I can't tell anything. The best would be a reproduction repository.

**Comment by ndarilek** [comment]
Sure:

https://github.com/ndarilek/meteor-astronomy-event-issue

Just start the app. It should, assuming my code is correct, set up an afterInsert event on the Meteor.users collection. I tried both `afterInsert` and `"afterInsert"`. It then checks for the presence of afterInsert, which returns false, and creates an account that doesn't trigger the event since the event doesn't appear to be set.

Thanks.

**Comment by jagi** [comment]
It can't be used that way. When you create Astronomy class it is not used by the `createUser` method. You would have to save a document by hand:

```js
var user = new User();
user.set({
  username: Random.id(),
  password: Random.id()
});
user.save();
```

If you would like to set some default values you can get use of the `onCreateUser` hook:

```js
Accounts.onCreateUser(function(options, user) {
  user = new User(user);
  return user.raw();
});
```

**Comment by ndarilek** [comment]
OK, so events only work if I use the Astronomy API directly? They won't 
work if, say, an admin interface package inserts into the collection on 
its own?

**Comment by jagi** [comment]
Yes exactly. It could work that way if there would be ability to hook into Collection event. I didn't want to do it the way how collection2 works. I hope that MDG will introduce collection events/hooks one day.

**Comment by ndarilek** [comment]
Fair enough. Thanks for the answer.
