### ISSUE TITLE
Astronomy is preventing ReactiveTable.publish from working

### ISSUE THREAD

**Issue by frabrunelle** [jagi/meteor-astronomy#135]
Hey Jagi!

I'm using the [reactive-table](https://github.com/aslagle/reactive-table) package and I was doing some tests to make `ReactiveTable.publish` work, which would allow [server-side pagination and filtering](https://github.com/aslagle/reactive-table#server-side-pagination-and-filtering-beta).

Although the instructions are really simple, I wasn't able to make it work. After a lot of debugging, I finally figured that the problem was somehow related to Astronomy.

I made a reproduction repo [here](https://github.com/frabrunelle/reactive-table-astronomy).

When you start this Meteor app (which contains the `astronomy` package), you will see that no data is displayed in the table.

And in the client-side console you can see the following error:

```
Uncaught MinimongoError: Duplicate _id 'null'
```

Also, if you add the `astronomy-validators` package, you get a different error:

```
Uncaught Error: Expected to find a document already present for removed
ReactiveTable subscription error: Error: Internal server error [500]
```

And for that error, in addition to the client-side console, there is also an error in the server-side console:
```
I20151015-19:00:14.727(-4)? Exception from sub reactive-table-rows id tApGzghLaafX6qDCr TypeError: Object [object Object] has no method 'all'
I20151015-19:00:14.727(-4)?     at packages/jagi_astronomy-validators/lib/module/ejson.js:9:1
I20151015-19:00:14.728(-4)?     at Object.Tracker.nonreactive (packages/tracker/tracker.js:589:1)
I20151015-19:00:14.728(-4)?     at Class.events.toJSONValue (packages/jagi_astronomy-validators/lib/module/ejson.js:7:1)
I20151015-19:00:14.728(-4)?     at packages/jagi_astronomy/lib/modules/core/events.js:51:1
I20151015-19:00:14.728(-4)?     at Array.every (native)
I20151015-19:00:14.728(-4)?     at Function._.every._.all (packages/underscore/underscore.js:219:1)
I20151015-19:00:14.728(-4)?     at Object._.extend.emit (packages/jagi_astronomy/lib/modules/core/events.js:49:1)
I20151015-19:00:14.728(-4)?     at Class.methods.toJSONValue (packages/jagi_astronomy/lib/modules/ejson/init_module.js:18:1)
I20151015-19:00:14.728(-4)?     at packages/ejson/ejson.js:168:1
I20151015-19:00:14.728(-4)?     at Object.Meteor._noYieldsAllowed (packages/meteor/fiber_helpers.js:11:1)
```

But when you comment out this piece of code:

```javascript
Row = Astro.Class({
  name: 'Row',
  collection: Rows,
  fields: {
    string: 'string',
    number: 'number'
  }
});
```
All the data is displayed correctly.

The problem might be due to the way to [Reactive Table](https://github.com/aslagle/reactive-table) package is coded but it might also be something with Astronomy. And since this only happens when I add Astronomy, I thought I would open the issue here.

I don't need to use `ReactiveTable.publish` for now since I am still developing my app and there is not a lot of data yet. But it would be nice if I could make use of it by the time I launch the app in a few weeks. I would appreciate any help to resolve this issue. Thank you very much!

If this proves out to be too complex to resolve, then I'll probably switch to using [tabular](https://github.com/aldeed/meteor-tabular), although it's not as easy to customize.

**Comment by jagi** [comment]
The reproduction repository is not a meteor project I can't run it. Please fix it and I will take a look at it.

**Comment by frabrunelle** [comment]
Sorry, the meteor project was in the `examples` folder. I fixed it just now. Can you take another look at it?

https://github.com/frabrunelle/reactive-table-astronomy

Thank you!

**Comment by jagi** [comment]
Ok I will take a look at it today in a few hours

**Comment by jagi** [comment]
The problem is that they treat documents coming from the collection as a plain JavaScript objects.

And Astronomy is using a transform function to wrap a plain JavaScript object with some extra functionalities. For now, a workaround for that would be:

```js
if (Meteor.isServer) {
  Row.extend({
    transform: function(doc) {
      return doc;
    }
  });
}
```

But because of that you lose transformation on the server. I see that such problems are very common and I have to figure out a solution. I'm thinking about ability to turn of transformation by passing `null` as it was in a beta version.

```js
Row = Astro.Class({
  /* ... */
  transform: null
});
```

and using the `Row.find()` method to get transformed documents. That would solve all problems that will ever happen. I think it's the best solution.

**Comment by frabrunelle** [comment]
Very nice! Thanks for implementing `transform: null`, it's great solution :smile: 

I'll open an issue on the `reactive-table` to ask if they could adopt the code to be compatible with Astronomy. That way it wouldn't be necessary to add `transform null`. But it's great to have a workaround for now :smile:

I'm also very much looking forward to seeing the Meteor guide about [Data loading and management](https://github.com/meteor/guide/blob/master/outlines.md#meteor-guide-data-loading-and-management), especially the following section:

> How to do pagination or infinite scroll so that you can load data incrementally as the user needs it

That way I could just do the pagination myself and display it in a [Bootstrap table](http://v4-alpha.getbootstrap.com/content/tables/). I just want to do it in such way that if I have thousands of records, they don't have to be loaded all at once and instead I can just show a couple (e.g. 20) at a time. The other features such as sorting by columns or filtering based on the content of the fields are nice to have, but I don't absolutely need them. And if I need search, I would implement it separately, probably by using a package such as [meteor-easysearch](https://github.com/matteodem/meteor-easy-search/), [search-source](https://github.com/meteorhacks/search-source) or [meteor-algolia](https://github.com/acemtp/meteor-algolia/).

I'll close this issue for now. Thank you very much for your help!

**Comment by jagi** [comment]
Ok good :)
