### ISSUE TITLE
Mini Mongo Server "Hooks"

### ISSUE THREAD

**Issue by mariorodriguespt** [jagi/meteor-astronomy#139]
I'm learning Astronomy and I'm trying to figure out how I can completely drop the collection-hooks package. I try to run either a Behavior or an Event only at server side but I was unable to do so. I was able to do so at client side but I usually have specific hooks for client and server.

I discovered that every works as expected if I run it on `meteor shell` or I if I can used `Methods`

My use case: I want to insert/update/remove on the client, I'm not a method for everything guy, and I would like to trigger Events or Behaviors ( I'm still trying to figure out the best approach ) to run some code.

Is this possible or is it on the roadmap?

**Comment by jagi** [comment]
The best way of using Astronomy is by taking advantage of using Meteor methods. It's a recommended way by many Meteor developers. Astronomy is not designed to work with allow/deny rules and direct collection access. Of course you can use it that way but I don't recommend it. If I know your use case better, than maybe I could advise you something.
