### ISSUE TITLE
Form model binding

### ISSUE THREAD

**Issue by niallobrien** [jagi/meteor-astronomy#14]
Any plans to add form model binding? Thanks, this looks like a great package, looking forward to playing with it.

**Comment by jagi** [comment]
Yes, I'm planning to create entire module not only for binding model with forms but also generating forms from model. It will be a big feature so it needs time. Right now, I'm preparing video tutorial. It will include information about using Astronomy with the forms. You can also check out this sample application https://github.com/jagi/meteor-astronomy-examples

I hope you will like this package :). Let me know if there are any other features to implement or problem you've encountered.

**Comment by niallobrien** [comment]
Awesome, I look forward to it.

**Comment by dovrosenberg** [comment]
I've gotten a decent start on connecting with forms, though haven't thought about automatically building the forms.

The approach I've taken is two-fold:
1) Register a form for submit handling (with template name and form name); it attaches a submit event handler that automatically copies the fields from the form to a Class object (assuming matching names for now), then validates and if it passes, saves it.  It calls optional user-defined functions before (ex. for attaching an existing _id for edits or perhaps for setting other fields that aren't on the form) and after (ex. for going to a new route, etc.). 

2) Register a form for error handling.  Haven't started this yet, but I think the approach is to check for each field whether there's a matching (by name/id) error span.  If there is, it will register onBlur events for those fields that will validate the field and update the error field text.

Happy to share the code, if it's helpful, though #1 was pretty straightforward, and I think #2 will be, as well.

**Comment by niallobrien** [comment]
Awesome, is this going to be a separate package?

**Comment by jagi** [comment]
@dovrosenberg I would be happy to see code and example use. I will start creating Form module for Astronomy soon so maybe we could cooperate in this matter. We could discuss details. I have some ideas about the forms implementation that comes from the usage of Doctrine library, but I don't want to discuss it here.

**Comment by niallobrien** [comment]
Are you guys part of the Meteor Club Slack channel?

**Comment by jagi** [comment]
No, what's that? :)

**Comment by ramijarrar** [comment]
Any updates on this?

**Comment by niallobrien** [comment]
@jagi https://www.patreon.com/meteorclub

**Comment by jagi** [comment]
It's in its early phase. Right now and for next two weeks I'm out of my country so not developing anything. I will be notifying about the progress when I'm back.

**Comment by niallobrien** [comment]
Any updates on this? Thanks.

**Comment by jagi** [comment]
Sorry for the late response. Still working on it. I will also have to implement module for binding model to the view. Together with forms module it will be complex toolset.

**Comment by ianserlin** [comment]
@jagi we are soon to release a public version of our internal forms package (most up-to-date branch is https://github.com/usefulio/forms/tree/README.md), and will probably add a simple extension to support astronomy validation, I'll keep you updated.

**Comment by jagi** [comment]
Good to hear. I will take a look at out in free time. In the new astronomy release there will be a lot of changes so you should take it into account.

**Comment by niallobrien** [comment]
When is the new release?

**Comment by jagi** [comment]
Right now Astronomy version is 1.0.0-rc.5. It should achieve 1.0.0 in the next week.

It won't introduce form model binding and forms package. I will be developing forms module after releasing 1.0.0.

As @ianserlin stated, they made the forms package that looks promising. I like its form - model binding feature. It's definitely something worth including in the forms package for Astronomy. I will have to work closely with developers on making the forms package the right way :)

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.
