### ISSUE TITLE
Security: Direct collection access

### ISSUE THREAD

**Issue by mariorodriguespt** [jagi/meteor-astronomy#140]
I was able to had whatever I wanted to a collection without Astronomy complaining about it when using native meteor methods. Direct collection access is a feature that, ideally, I only use at server side, it should be forbidden at client side.

I think Direct collection access defeats the purpose of declaring a schema, as a developer I should knowing exactly what I'm doing and it's nice to get an error when I have a typo that will make waste time debugging it.

It would be nice to have some clarification about the intended development approach to use Astronomy on the docs. As a user of `simple-schema` and `collection2`packages I was expecting this feature.

**Comment by jagi** [comment]
It's ORM/ODM and it's not intended to work with direct collection access. However, I've implemented partial support for this. If you prefer simple-schema, then just use it.

**Comment by jagi** [comment]
Direct collection access will be full featured in Astronomy 2.0 which will be available soon.
