### ISSUE TITLE
Can't save edits in nested object if it's an instance of a class

### ISSUE THREAD

**Issue by ianmartorell** [jagi/meteor-astronomy#141]
Let's say I have these models:

```coffeescript
@Things = new Mongo.Collection 'things'

@Thing = Astro.Class
  name: 'Thing'
  collection: Things
  fields:
    obj:
      type: 'object'
      default: -> {}

@NestedThing = Astro.Class
  name: 'Nested Thing'
  fields:
    name:
      type: 'string'
      default: -> ''
```

If I do this:
```coffeescript
thing = new Thing
id = thing.save()
thing.set 'obj.nested', new NestedThing
thing.set 'obj.nested.name', 'asd' # this won't be saved
nested = thing.get 'obj.nested' # we get this for later
thing.save()
thing = Things.findOne id
```
`thing` will now look like this:
```javascript
{ _modifiers: {},
  _original:
   { _id: 'u2XH65BuLa5LyMLSX',
     obj: { nested: [Object] } },
  _id: 'u2XH65BuLa5LyMLSX',
  obj:
   { nested:
      { _modifiers: {},
        _original: [Object],
        name: '',
        _isNew: true } },
  _isNew: false }
```
The `name` of the nested object doesn't get saved because the `_modifiers` are written to the nested object instead of `thing`. The `nested` variable we set earlier looks like this:
```javascript
{ _modifiers: { '$set': { name: 'asd' } },
  _original: { name: '' },
  name: 'asd',
  _isNew: true }
```

**Comment by jagi** [comment]
It does not work because of the limitations of MongoDB. You can not execute multiple operations on the same field also field and its nested field. You have to call the `save()` method between operations on the same field.

**Comment by ianmartorell** [comment]
Well, if you save after creating the nested field it doesn't work either:

```coffeescript
thing = new Thing
id = thing.save()
thing.set 'obj.nested', new NestedThing
thing.save() # Even if we save here, modifying the nested object won't work
thing.set 'obj.nested.name', 'asd' # this won't be saved
thing.save() # this returns 0
```

I still thing it happens because `_modifiers` gets written to the nested object instead of the parent, which is the one you call `save()` on.

**Comment by jagi** [comment]
Please create reproduction repository in pure JavaScript, so I will be able to test it.

**Comment by jagi** [comment]
I didn't write it in documentation but you have to execute the `save` method between every modification on the same field and its nested fields. So you should do:

```js
thing.set('obj.nested', new NestedThing());
thing.save();
thing.set('obj.nested.name', 'asd');
thing.save();
```

I will add this information to the documentation.

**Comment by ianmartorell** [comment]
What you just wrote in JavaScript is exactly the same code I wrote in CoffeeScript, and it doesn't work. I can create a reproduction repo tomorrow if you want.

**Comment by jagi** [comment]
Ok please create a reproduction

**Comment by ianmartorell** [comment]
I put up a very simple reproduction [here](https://github.com/ianmartorell/astronomy-nested). Just look at the console output.

**Comment by jagi** [comment]
The definition of the `obj` field is wrong. You forgot about the `nested` property.

```js
obj: {
  type: 'obj',
  nested: 'NestedThing'
}
```

Everything is in the documentation

**Comment by ianmartorell** [comment]
I thought the `nested` property was optional :/

**Comment by ianmartorell** [comment]
I thought the `nested` property was optional :/

**Comment by jagi** [comment]
It's optional if you are using plain JavaScript objects, however if you want to use nested classes then you have to provide it.
