### ISSUE TITLE
save() method callback, id parameter not an id

### ISSUE THREAD

**Issue by stevenjmarsh** [jagi/meteor-astronomy#144]
When calling the save method, and providing a callback, per the documentation, the callback is expecting  error and id parameters. The value I received for id was '1' (was expecting an id, I think this is some value other than id).

```
Template.journalEntryEdit.events({
    'submit form': function(e) {
        e.preventDefault();

        var entry = JournalEntries.findOne(this._id);
        entry.set({
            entryDate: $('#entry-datepicker').datepicker('getDate'),
            caption: $(e.target).find('[name=caption]').val()
        });

        entry.save(function (error, id) {
            // TODO: id doesn't seem correct here. a '1' was passed back, I think
            // maybe the number of some items saved? but was expecting an id.
            if (error) {
                alert('edit save error:' +  error.reason);
            } else {
                Router.go('journalEntryPage', {_id: id});
            }
        });
    }
});
```

**Comment by jagi** [comment]
It depends if it's a new document or already stored document. If it's a new document, then it will be ID, if it's updating already saved document then it will be number of records being updated. The same as in `insert` and `update` methods.

**Comment by stevenjmarsh** [comment]
Got it, thanks! And thanks for the quick follow up. I'll close this issue. Adding your above comment to the documentation would be helpful (or let me know if it is wiki based, and can be crowd supported). Thanks for your continued support of this package.

**Comment by jagi** [comment]
Here is a github repo https://github.com/jagi/meteor-astronomy-docs with a documentation. You can contribute if you wish :). Any contribution is welcome :)
