### ISSUE TITLE
Validation errors from nested classes disappear

### ISSUE THREAD

**Issue by JesperWe** [jagi/meteor-astronomy#146]
Using Meteor 1.2.0.2 and Atstronomy 1.1.2 + Validators 1.0.4

Class definition:

	UserProfile = Astro.Class( {
		name: 'UserProfile',
		fields: {
			name: 'string',
			address1: 'string',
			address2: 'string',
			zip: 'string',
			city: 'string',
			country: 'string',
			language: 'string'
		},
		validators: {
			'name': Validators.minLength(3)
		},

	} );

	Users = Astro.Class( {
		name: 'Users',
		collection: Meteor.users,
		fields: {
			username: 'string',
			profile: {
				type: 'object',
				nested: 'UserProfile'
			}
		}
	} );

...and the following save method:

	Meteor.methods( {
		'/user/save': function( user ) {
			if( user.validate( false ) ) {
				user.save();
				return user;
			}

			console.log( "Errors: " + JSON.stringify( user.getValidationErrors() ) );
			user.throwValidationException();
		}
	} );

...when saving an instance with profile.name.length < 3 user.validate() returns false as it should, but I get "Errors: {}" on the server console and an exception like this on the client: `{"error":"validation-error","reason":{},"message":"[object Object] [validation-error]","errorType":"Meteor.Error"}`

**Comment by JesperWe** [comment]
BTW, this is not the same as closed issues #121 or #124. The validation is happening, it's just the error message that is getting lost.

**Comment by jagi** [comment]
It's because the validation error is in the nested object `user.profile.getValidationErrors()`. I've already got an issue that it's a problem. I will try to figure out a way of accessing nested errors in more easy way.

**Comment by JesperWe** [comment]
I see. That is a bit awkward because they are only visible on the server.
And I can only .throwValidationException() for one object...

**Comment by jagi** [comment]
Yes, I have to fix it. I know about the problem. So stay tuned. A fix should appear soon.

**Comment by JesperWe** [comment]
Any news on this? Is it a "Fixed in v2" thing?
Any point in trying v2 at this time?

**Comment by jagi** [comment]
Hmmm strange I think that I've already fixed it but I'm not 100% sure. I don't have time right now to prepare reproduction repository. In v2 there is a little bit different approach to validation errors. They not get collected in the document. Instead they are thrown and it's developer's responsibility to collect them if needed. However, I will also prepare something similar like in 1.x where errors will be collected, but it will be separate module.
