### ISSUE TITLE
Unique() validator on a nested object field is not being applied

### ISSUE THREAD

**Issue by shwaydogg** [jagi/meteor-astronomy#147]
A non unique nested field [at least for a parent type "object" haven't tested array yet] will still pass validation when `Validators.unique()` is applied:

Test Example:
http://meteorad.com/pad/AATHfeTCerpyomdyz/Astronomy%20Nested%20Unique%20Value%20Example

Which is just the following in server code:

```
Tests = new Mongo.Collection('tests');

Test = Astro.Class({
  name: 'Test',
  collection: Tests,
  fields: {
    parentField: {type: 'object', nested: { name:'parentField', fields:{
      nestedField: {
        type: 'string',
        validator: [Validators.unique(),Validators.minLength(3)]
      }
    }}}
  }
});

var first = new Test({parentField:{nestedField:'123'}});
first.save();

var second = new Test({parentField:{nestedField:'123'}});

if(! second.validate()){
  console.log('SERVER: did not pass! :)');
  }else{
   console.log('SERVER: PASSED WHEN NOT UNIQUE! :('); 
}

var third = new Test({parentField:{nestedField:'12'}});

if(! second.validate()){
  console.log('SERVER: issue with validator setup');
  }else{
   console.log('SERVER: THIRD Failed, GOOD, validators are setup correctly.'); 
}
```

**Comment by jagi** [comment]
Unique validator does not work on the nested field. I will have to figure out some workaround for that.

**Comment by shwaydogg** [comment]
Is this now possible?

**Comment by lukejagodzinski** [comment]
"Now" you mean in 2.0? If so, then I have bad news. I removed the `unique` validator. It's to complex to keep track of all scenarios. If anyone wants some field to be unique, then consider using unique index or imprinting logic by yourself.

**Comment by shwaydogg** [comment]
Makes sense!
