### ISSUE TITLE
inc() doesn't exist

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#148]
Hi,
I'm trying to use inc() on a class instance, but I'm getting this error:
Uncaught TypeError: post.inc is not a function(…)

Any ideas?

**Comment by jagi** [comment]
Show more code. If it's saying that it does not exist then it means that document has to been transformed.

**Comment by jazzdragon** [comment]
(coffeeScript)

```coffeescript
TestCollection = new Mongo.Collection 'testCollection'
testClass = Astronomy.Class
  name: 'testClass'
  collection: TestCollection
  fields:
    testKey: 'testVal'

a = new testClass()
console.log a.inc
```

returns `undefined`.

**Comment by jagi** [comment]
Please don't use coffee script to present code in issues. The `testKey` field should be of `number` type.

**Comment by jazzdragon** [comment]
Sorry, that was a typo.
Anyway, it shows a doesn't have an `inc` method.
Again, in JS:

```javascript
TestCollection = new Mongo.Collection('testCollection')
TClass = Astronomy.Class({name: 'TClass', collection: TestCollection, fields: {testKey: 'number'}})
a = new TClass()
console.log(a.inc)
```

Also typed it in the console, same results.

**Comment by jagi** [comment]
It has. It works on my computer. What version of Astronomy are you using?

**Comment by jazzdragon** [comment]
jagi:astronomy@0.12.1
jagi:astronomy-validators@0.10.10
jagi:reactive-map@0.2.3

**Comment by jagi** [comment]
The `inc` method does not exist in Astronomy 0.12.1. You have to update.

**Comment by jazzdragon** [comment]
Gotcha. Thanks for your patient help!

**Comment by jagi** [comment]
No problem :)
