### ISSUE TITLE
_errors is not send back to client

### ISSUE THREAD

**Issue by parhelium** [jagi/meteor-astronomy#15]
`menu` is instance of `Astro.Class`.

Server side :

        if ( menu.validate() ) {
            menu.save();
        } else {
            console.log( menu._errors._getMigrationData() );
            return menu;
        }

Above `console.log` show that there is invalid field in `menu`.
`_errors : ReactiveDict` is not send through DDP , so client side can't see errors sent by server side.
There are some custom validators which should run on server ( unique ). So my goal is to validate on client side and then validate on server side. Eventually errors should be send back to client side.

**Comment by parhelium** [comment]
I noticed you have example of passing _errors in docs:
https://github.com/jagi/meteor-astronomy#ejson-ification

**Comment by parhelium** [comment]
Ufff... In the end I solved the problem.
Maybe it will  be useful for somebody. 

Just to recall, my goal was to validate Menu (Astro.Class) on server side and return eventual errors in nice way, so form will reactively show errors.


```
var onToJSONValue = function ( e ) {
    e.data.errors = this._errors.keys;
};

var onFromJSONValue = function ( e ) {
    this._errors.keys = e.data.errors;
    var hasErrors = _.some(this._errors.keys, function(undefined, fieldName) {
        return this._errors.get(fieldName);
    }, this);
    this._hasErrors.set(hasErrors);

};

Astro.on( 'tojsonvalue', onToJSONValue );
Astro.on( 'fromjsonvalue', onFromJSONValue );
```

Server side:

```
Meteor.methods( {
    'createMenu': function ( menu ) {
        if ( menu.validate() ) {
            menu.save();
        } else {
            return menu;
        }
    }
} )
```

Client side:

- `t.data.menu` , `t` is template, `menu` is Astro.Class

```
Meteor.call( 'createMenu', t.data.menu, function ( err, results ) {
        if ( err ) {
            // server side errors, or errors which should be shown in popup
            console.error( err )
        } else {
            var menu = results;
            if ( menu.hasValidationErrors() ) {
                _.keys(menu._errors.keys).forEach(function(key){
                    console.log(key, menu._errors.get(key))
                    t.data.menu._errors.set(key, menu._errors.get(key))
                })
                t.data.menu._hasErrors.set(menu._hasErrors.get());
            } else {
                // success
            }
        }
    } )
```

**Comment by jagi** [comment]
Yes `_errors` are not sent to the server through DDP (I've not implemented it yet). However it does not  cause any problem with validation. In fact you don't have to send errors back to the client to make it work. You can just validate on the client and validate on the serve simultaneously. However I will implement feature allowing EJSON-ification of `_errors`. Here is an example application showing how to deal with validation: https://github.com/jagi/meteor-astronomy-examples

I didn't implement EJSON-ification of `_errors` because I'm planning to replace `ReactiveDict` with `ReactiveMap` that I'm implementing right now.

**Comment by parhelium** [comment]
I'm already validating simultaneously and that works perfect.
However one of my validator :

```
Astro.createValidator( {
    name: 'unique',
    validate: function ( fieldName, value, collection ) {
        if ( !collection ) return false;

        if ( !(collection instanceof Mongo.Collection) ) {
            return false
        }
        // unique validator is used only during INSERT
        // if _id is present, then object is being updated NOT inserted.
        if ( this.get( '_id' ) ) {
            return true;
        }

        var query = {};
        query[fieldName] = value;
        if ( collection.findOne( query ) ) {
            return false
        }
        return true
    },
    onvalidationerror: function ( e ) {
        var fieldName = e.data.field;
        var fieldValue = e.data.value;
        var collection = e.data.options;
        if ( !(collection instanceof Mongo.Collection) ) {
            return 'Validator unique : Passed options is not Mongo.Collection. Cannot verify uniqueness.'
        }

        var query = {};
        query[fieldName] = fieldValue;
        if ( collection.findOne( query ) ) {
            return 'Field ' + fieldName + ' is not unique.'
        }

        return "Error!";
    }
} );

```

checks uniqueness of document. It needs access to all documents of collection and it doesn't make sense to subscribe all documents just for validation on client side...

**Comment by jagi** [comment]
@parhelium there are a few things worth mentioning here.
1. I've made an update to Validators module and now you can send errors through DDP protocol. Now it should be much easier to exchange errors between client and sever.
2. I've updated the example I mentioned about and now it returns to the client server validation errors: https://github.com/jagi/meteor-astronomy-examples/blob/master/methods.js
3. In your validator function you should rely on the third `collection` argument. To be honest I didn't even know that I'm passing it. It's just side effect of using underscore `_.each` method. Instead you should use `this.constructor.getCollection()` to take collection that given record belongs to.

I forgot about `unique` validator, I'm glad that you mentioned about it. If you don't mind I will add it to the list of standard validators included with Validators module.

The `unique` validator will only work properly on the sever. We can have situations that not all documents are published to the client. But I don't think it's a big problem. When doing validation on both client and sever, it will still return errors from the server that we can use.

**Comment by parhelium** [comment]
@jagi Thank you for updating package !
Feel free to add `unique` validator to list of standard validators included with Validators module.

I will test it tomorrow morning.

**Comment by jagi** [comment]
I've added also two more useful methods `throwValidationException` and `catchValidationException`. Thanks to them we can easily perform server validation and use thrown errors to display them in the form.

**client/server method:**
```js
Meteor.methods({
  '/user/save': function(user) {
    if (user.validate()) {
      user.save();
      return user;
    }

    user.throwValidationException();
  }
});
```

**template events:**
```js
Template.Form.events({
  'click [name=save]': function(e, tmpl) {
    var user = this;

    if (user.validate()) { // IMPORTANT! THIS VALIDATION CAN BE OMITED IF WE DON'T WANT TO PERFORM CLIENT SIDE VALIDATION
      Meteor.call('/user/save', user, function(err) {
        if (err) {
          user.catchValidationException(err);
        }
      });
    }
  }
});
```
