### ISSUE TITLE
Astronomy trying to save private keys

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#150]
Hi,
After updating my version of Astronomy, I get all these errors:

```
Trying to set a value of the "_modifiers" field that does not exist in the "Post" class
utils.js:5 Trying to set a value of the "_original" field that does not exist in the "Post" class
utils.js:5 Trying to set a value of the "_errors" field that does not exist in the "Post" class
utils.js:5 Trying to set a value of the "_isNew" field that does not exist in the "Post" class
```

I can suppress the errors like you suggested elsewhere when getting them from publications (although I'm not using any composite publications and still getting these errors), but when trying to save documents I sometimes get these errors that prevent the docs to be saved.

Thanks!

**Comment by jagi** [comment]
Take a look at [this](http://astronomy.jagi.io/#warnings) and [this](http://astronomy.jagi.io/#custom-transform) section in the documentation. There is an answer to your question.

**Comment by jazzdragon** [comment]
ok I see, so you suggest transforming the class to omit those private keys?
Why not doing it globally for all the astronomy class? looks like you would never want to actually save those to your db.

**Comment by jagi** [comment]
Oh sorry you wrote that you are not using publications. So show the code that causes this warning in the console.

**Comment by jazzdragon** [comment]
Thanks again for your help. I figured out my problem. I was trying to clone an instance like so:
```javascript
a = new testClass();
a.set(b.get());
```

So yeah, it was also trying to set the private keys as well. Solved it after I found `cloning` in the docs.

I think I found a bug though in the process. For some reason `set()` and `inc()` don't work after each other. Try this:

```javascript
A = Astronomy.Class({name: 'A', fields: {quantity: 'number'}});
a = new A();
a.set('quantity', 10);
console.log(a.quantity); // 10
a.inc('quantity', 1);
console.log(a.quantity); // 10

// alternatively:
A = Astronomy.Class({
  name: 'A',
  fields: {
    quantity: {
      type: 'number',
      default: function(){return 10}
    }
  }
});
a.inc('quantity', 1);
console.log(a.quantity); // 11
a.set('quantity', 10);
console.log(a.quantity); // 11
```

**Comment by jagi** [comment]
Ok  good to hear.

To achieve the same effect without the `copy()` method you would have to do:

```js
var doc = Docs.findOne();
var copy = new Doc();
copy.set(doc.raw());
``` 

As I wrote in other issues you have to call the `save` method between modifications of the same field, it's because of the limitations in MongoDB. I will add this information to the documentation soon.
