### ISSUE TITLE
Polymorphism

### ISSUE THREAD

**Issue by afsjunior** [jagi/meteor-astronomy#151]
Hi!

First I would like to congratulates "jagi" and all colaborators for the great job with this project!
I would like to make a question about polymorphism using Astronomy.

Consider these two classes:
```javascript
Game = Astro.Class({
	name: 'Game',
	typeField: 'className',
	fields: {
		result: 'string'
	},
	methods: {
		resultPrint: function() {
			return 'Game: ' + this.result;
		}
	}
});

BasketballGame = Game.inherit({
	name: 'BasketballGame',
	methods: {
		resultPrint: function() {
			return 'Basketball ' + super.resultPrint();
		}
	}
}); 
```
Is there a way to call the method resultPrint() of the class Game inside the class Basketball method like the example above expecting the result bellow?
```javascript
var basketball = new BasketballGame({ result: '38 x 41' });
basketball.resultPrint(); //returns the string 'Basketball Game: 38 x 41'   
```
Thanks!

**Comment by jagi** [comment]
Hi, thanks!

Yes it's possible to call parent method. However, as I'm not using ES2015 yet it's not the prettiest solution you can imagine :). It could look as follows:

```js
BasketballGame = Game.inherit({
    name: 'BasketballGame',
    methods: {
        resultPrint: function() {
            var Class = this.constructor;
            var resultPrint = Class.getParent().getMethod('resultPrint');
            return 'Basketball ' + resultPrint();
        }
    }
}); 
```

I'm planning to use ES2015, which would allow the use of the `super` keyword. However, it will be introduced in Astronomy 2.0

**Comment by afsjunior** [comment]
Thanks for your answer, jagi!

It will be really handy being able to use <code>super</code> keyword in the future.

With both approach, resultPrint() returned
```javascript
'Basketball Game: undefined'
```
I am using astronomy version 1.1.4 and for the second approach
```javascript
BasketballGame = Game.inherit({
    name: 'BasketballGame',
    methods: {
        resultPrint: function() {
            return 'Basketball ' + Game.prototype.resultPrint();
        }
    }
}); 
```
Thanks!

**Comment by jagi** [comment]
Oh sorry you have to call it in the context of the document.

```js
BasketballGame = Game.inherit({
    name: 'BasketballGame',
    methods: {
        resultPrint: function() {
            var Class = this.constructor;
            var resultPrint = Class.getParent().getMethod('resultPrint');
            return 'Basketball ' + resultPrint.apply(this, arguments);
        }
    }
}); 
```

or

```js
BasketballGame = Game.inherit({
    name: 'BasketballGame',
    methods: {
        resultPrint: function() {
            return 'Basketball ' + Game.prototype.fullName.apply(this, arguments);
        }
    }
}); 
```

**Comment by afsjunior** [comment]
Thanks for the update!
Both now worked fine.
Congrats once again.

**Comment by jagi** [comment]
Good to hear :)
