### ISSUE TITLE
cannot attach class to Meteor.users

### ISSUE THREAD

**Issue by zhaoyao91** [jagi/meteor-astronomy#153]
I get such an error according to the example

      Error: The "collection" property has to be an instance of the "Mongo.Collection" in the "User" class

**Comment by jagi** [comment]
Have you added account-base package?

**Comment by zhaoyao91** [comment]
I didn't add this package explicitly before, but I have accounts-password installed, which will install accounts-base according to the docs.
I've tried to install this package, and I test `Meteor.users instanceof Mongo.Collection`, sadly, it still return false.

**Comment by jagi** [comment]
So the problem is not with Astronomy. I don't know why you have this problem but maybe ask this question in the Meteor repository.

**Comment by zhaoyao91** [comment]
Thanks, I think this is indeed the matter of meteor. After some time( I don't know what happened during this time), I tried again and Meteor.users is again type of Mongo.Collection. Thanks for you great work, I am considering change to this package from collection2 in my current project.

**Comment by jagi** [comment]
Good to hear :)

**Comment by JulianKingman** [comment]
I had this issue after installing `mikowals:batch-insert`. The solution was to place it before the astronomy package in the packages file, I suspect the same might be true of other packages that modify collections..
