### ISSUE TITLE
Classes don't inherit methods

### ISSUE THREAD

**Issue by ianmartorell** [jagi/meteor-astronomy#154]
I've noticed that if I make a class inherit from another with `Class.inherit`, the child will have all the fields from the parent, but not its methods. I could provide a reproduction if necessary.

**Comment by jagi** [comment]
It should have all parent methods. Yes, create a reproduction.

**Comment by ianmartorell** [comment]
Well, I tried this in a barebones app and it's working fine... However, the objects in my project are definitely not inheriting the methods. I'm trying to figure out what I'm doing wrong, so closing this for now.

**Comment by jagi** [comment]
Ok
