### ISSUE TITLE
Attaching multiple events of the same type

### ISSUE THREAD

**Issue by ndarilek** [jagi/meteor-astronomy#155]
Not sure if I can do this, but I'd like:

server/tasks.js:
```
User.extend({
  events: {
  afterInsert: function() {
      // Task-specific code goes here
    }
  }
})
```

server/stripe.js
```
User.extend({
  events: {
  afterInsert: function() {
      // Create Stripe customer or account
    }
  }
})
```

It looks like there can only be a single handler per type. Am I wrong? A feature I miss from collection-hooks is the ability to set up event handlers in separate files, separated based on concerns. Perhaps there is another way to accomplish this in Astronomy? I could lump them all together, but I like the modularity of being able to drop server/stripe.js into other projects and, as long as I'm using Astronomy, get event integration for creating Stripe accounts on user events.

Thanks.

**Comment by jagi** [comment]
Yes, of course it's possible. You should check it before asking ;)

**Comment by ndarilek** [comment]
I did, actually, and it isn't working. Since I now know that it is 
possible, and that `extend` isn't overriding the keys, the problem must 
be in my own code and I'll investigate that further.

Sorry for the noise.

**Comment by jagi** [comment]
Ok. If you still can't make it work you can create a reproduction so maybe I well be able to help you.

**Comment by nicooprat** [comment]
If anyone is asking himself the same question, it's also working with the latest version of Astronomy (2.0.1).
