### ISSUE TITLE
Nested class as array - bug in saving

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#156]
Reproduction Repo: https://github.com/s7dhansh/meteor-astronomy-bug

Steps:
1. Have a nested array in an astro class
2. Instantiate the parent class
3. Save it
4. 'Set' the nested class
5. Push the nested class into parent class key
5. Save it again

It throws an error saying: `MongoError: Cannot update <nestedClass> and <nestedClass.0.nestedClassField> at the same time.`

**Comment by jagi** [comment]
Hmmm, yes it's seems to be a bug. However, for now you can change:

```js
var phone = new Phone();
phone.set({
  /* ... */
});
```

to

```js
var phone = new Phone({
  /* ... */
});
```

and it's gonna work. However, I will prepare a fix.

**Comment by jagi** [comment]
Ok I've fixed it but haven't published yet. I will do it today or tomorrow

**Comment by s7dhansh** [comment]
Thank you.
Yes, there are multiple workarounds. I used phone.raw() for now.

**Comment by marbemac** [comment]
Similar issue, with arrays. I have an array of nested classes. When I add a instance of the class to that array, and then edit/set a field in that class, and then save, I get the following error:

"Cannot update 'responses.0' and 'responses.0.codes' at the same time".

This is occurring on the latest release (1.2.0).

**Comment by jagi** [comment]
Yes it's a limitation of MongoDB that you can execute multiple operations on the same fields or nested fields of the field. I will have to create some workaround for this. We will see what I can do about it.

**Comment by marbemac** [comment]
It's a limitation that you can, or that you cannot?

Hmm - perhaps in cases like this, you could take the safer route and keep the parent-most update, removing the more specific nested updates?

**Comment by jagi** [comment]
"can't"

It's a little bit more complicated than that. I have to merge top level and nested changes.

**Comment by marbemac** [comment]
Any further thoughts on this? Is the best workaround right now to always set the entire array class (not the nested class property)?


```js
// this
rawObj = obj.responses[0].raw();
rawObj.codes = [200, 400];
obj.set('responses.0', rawObj)

// instead of this
obj.set('responses.0.codes', [200, 400])
```

**Comment by jagi** [comment]
@marbemac can you show your schema?

**Comment by marbemac** [comment]
Sure thing, abbreviated models below:

```js
SL.M.EndpointResponse = Astro.Class({
  name: 'EndpointResponse',
  fields: {
    mimeType: {
      type: 'string',
      default: 'application/json',
    },
    codes: {
      type: 'array',
      nested: 'number',
      default() {
        return [200];
      },
    },
  },
});
```

```js
SL.M.Endpoint = Astro.Class({
  name: 'Endpoint',
  collection: SL.C.Endpoints,
  transform: null,
  fields: {
    name: {
      type: 'string',
      default: '',
      validator: [
        Validators.maxLength(100),
      ],
    },

    responses: {
      type: 'array',
      nested: 'EndpointResponse',
      default() {
        return [];
      },
    },
  }
})
```

**Comment by marbemac** [comment]
I should mention that in the example I gave before, I first set the new response via:

```js
obj.set('responses.0', new SL.M.EndpointResponse());
obj.set('responses.0.codes', [200,500]);
obj.save(); // error
```

That is a very simplified example. In reality, those steps happen in disparate parts/components of my app. Otherwise I'd obviously do a simple:

```js
obj.set('responses.0', new SL.M.EndpointResponse({codes: [200, 500]}));
obj.save();
```

**Comment by jagi** [comment]
It's the same thing as in the main issue. It's just differs that you are setting document under specified index instead pushing. I will solve this problem. You have to wait a little bit. Stay tuned. I will inform you.

**Comment by marbemac** [comment]
Cool! Not trying to be pushy, was just curious. Thanks a lot.

**Comment by marbemac** [comment]
Any further luck on this one? We regularly run into random scenarios where our front-end is used in a particular new way, which results in an order of operations to the underlying model that triggers this bug. We're working around it as we find issues, but it's leading to messier code (and the odd 500 error as users uncover the bug). 

Again, don't want to be pushy! Just curious where this might fit into your roadmap. Thanks!

**Comment by jagi** [comment]
I'm testing new ways of working with nested data (that will appear in 2.0). I've already solved all issues but it can't be implemented in 1.x because it would be compatibility breaking. I don't know if I want to mess with it in 1.x, or I just should focus on 2.0 and propose you some fix for now.

I've tried to find some workaround for now but it seems that you have to execute the save() method between operations. It's hard to prepare an universal fix.

**Comment by marbemac** [comment]
We're running into this issue more and more, any idea on when a fix for this might be ready? (2.0 other otherwise?). Thanks!

**Comment by jagi** [comment]
I will try to publish Astronomy 2.0-rc.1 today. Of course it's still early version but it should be usable

**Comment by marbemac** [comment]
Awesome! Really looking forward to it. I know updating the documentation is a huge project, but in the meantime will you perhaps publish a simple list of major API / Philosophy changes for those that want to experiment with 2.0?

**Comment by marbemac** [comment]
Oh also, I guess this was implicit in my original question, but is this issue fixed in 2.0?

**Comment by jagi** [comment]
Yes it's fixed in 2.0. The best way to learn what changes I've made is taking a look at the example repository for v2 https://github.com/jagi/meteor-astronomy-examples/tree/v2

**Comment by marbemac** [comment]
Dude, the new nesting syntax looks so much nicer! Excited.

**Comment by jagi** [comment]
Glad that you like it. I'm making last fixes in validation and will publish a package in a few hours.

**Comment by jagi** [comment]
RC.1 published -> https://github.com/jagi/meteor-astronomy/issues/236
