### ISSUE TITLE
sets EJSON as nested object when updating existing parent

### ISSUE THREAD

**Issue by JayMc** [jagi/meteor-astronomy#157]
When I create a new Sale with nested Vendor. The entire vendor object is visible nested inside sale. but if I retrieve sale then set vendor it stores the EJSON and not the vendor object structure.
For updates can we cast another model to a nest field as we can when creating a new parent? 

Here is my 2 models (trimmed down)
```javascript
Sale = Astro.Class({
  name: 'Sales',
  collection: Sales,
  fields: {
  	vendor: {
  		type: 'object',
  		nested: 'Vendor',
  		default: function(){
  			return {}
  		}
  	}
});

Vendor = Astro.Class({
  name: 'Vendors',
  collection: Vendors,
  fields: {
    name: {
      type: 'string',
      validator: [
        Validators.minLength(3, 'Name too short'),
        Validators.maxLength(40)
      ]
    }
});
```

Example 1
Creating a new Sale with existing vendor works as expected. Stores vendor object.
```javascript
var vendor = Vendor.findOne('4YpnM3FXaksJ6EARx')
var sale = new Sale()
sale.set('vendor', vendor)
if(sale.validate()){
	sale.save()
}
```

Example 2
Updating an existing Sale with an existing vendor (ie changing the vendor) stores EJSON$type and EJSON$value
```javascript
var vendor = Vendor.findOne('4YpnM3FXaksJ6EARx')
var sale = Sale.findOne('ex5rhhauquFL8JtHj')
sale.set('vendor', vendor)
if(sale.validate()){
	sale.save()
}
```

I found that in example 2 I can only get the nested vendor details as an object if I create a new Sale `var sale = new Sale()`.

For updating existing Sales will I have to set each nested field individually like so?
```javascript
var vendor = Vendor.findOne('4YpnM3FXaksJ6EARx')
var sale = Sale.findOne('ex5rhhauquFL8JtHj')
sale.set('vendor._id', vendor._id)
sale.set('vendor.name', vendor.name)
..etc..
if(sale.validate()){
	sale.save()
}
```

**Comment by jagi** [comment]
You can't do it the way you did it. First of all you have to choose if you want to store a nested class in the separate collection or not. In your case you've decided to store Vendor documents in the separate collection. So you should only store ids of vendors in the Sale class.

You also have error in your example it lack of `}` in both classes definitions.

You probably want something like this:

```js
Sale = Astro.Class({
  name: 'Sale',
  collection: Sales,
  fields: {
    vendor: {
      type: 'object',
      nested: 'Vendor'
    }
  }
});

Vendor = Astro.Class({
  name: 'Vendor',
  fields: {
    name: {
      type: 'string',
      validator: [
        Validators.minLength(3, 'Name too short'),
        Validators.maxLength(40)
      ]
    }
  }
});
```

**Comment by JulianKingman** [comment]
I'm having the same issue, but my nested schema is in the same collection. I try to get around it by using .raw(), but it only works for one, the next one I add stress as ejson.

**Comment by jagi** [comment]
@JulianKingman show your schema. If it gets stored as a EJSON that means that the schema has not enought information to convert it into JSON format. The `raw()` method is executed on a nested data to retrieve JSON data, so it has to know what data resides in a nested field.

**Comment by JulianKingman** [comment]
Simplified:

````javascript
task = Astro.Class({
    name: 'task',
    collection: tasks,
    fields: {
        'name': 'string',
        'nextExIndex': {
            type: 'number',
            optional: true,
            default: function(){
                return 0;
            }
        },
        'workouts': {
            type: 'array',
            nested: 'workoutGroup',
            default: function () {
                return [];
            }
        }
    },
    events: {
        beforesave: function(){
            this.nextExIndex = this.nextExIndex + 1;
            Meteor.call('saveTask', this);
        }
    }
});

workoutGroup = new Astro.Class({
    name: 'workoutGroup',
    fields: {
        '_id': {
            type: 'string',
            optional: true
        },
        'sets': {
            type: 'string',
            optional: true
        },
        'exercises': {
            type: 'array',
            nested: 'exercise',
            default: function () {
                return [];
            }
        }
    }
});
exercise = new Astro.Class({
    name: 'exercise',
    fields: {
        '_id': {
            type: 'string',
            optional: true
        },
        'workoutId': {
            type: 'string',
            optional: true
        },
        'taskId': {
            type: 'string',
            optional: true
        },
        'notes': {
            type: 'string',
            optional: true
        }
    }
});
````

Then the methods to save/update:
````javascript
Meteor.methods({
 newExercise: function (workout, taskId, randId) {
        var task = tasks.findOne(taskId);
        //find the group
        var group = _.find(task.get('workouts'), {_id: workout._id});
        //add an execrise, original task is updated
        group.exercises.push(new exercise({
            _id: randId,
            workoutId: workout._id,
            taskId: workout.taskId,
            index: task.nextExIndex
        }));
        task.set('workouts', task.raw('workouts'));
        Meteor.call('saveTask',task);
    },
updateExercise: function (thisExercise, index, reps, sets, weight, name, notes) {
        var task = tasks.findOne(thisExercise.taskId);
        var group = _.find(task.get('workouts'), {_id: thisExercise.workoutId});
        var exercise = _.find(group.get('exercises'), {_id: thisExercise._id});
        exercise.set({name: name});
        task.set('workouts', task.raw('workouts'));
        Meteor.call('saveTask', task);
    }
});
````

**Comment by JulianKingman** [comment]
And one more thing, this shouldn't be necessary:
````javascript
task.set('workouts', task.raw('workouts'));
````
If I console.log the task, it shows up updated, but doesn't save.

**Comment by jagi** [comment]
But it's necessary now because when you set a new value it can't be the same reference. In the `task.workouts` field the array is stored. And when you tried to assign the same array to the field it does not see any difference. I'm working on new ways of dealing with data modifications in Astronomy 2.0. It should fix most of the users problems. For now it has to be done that way.

**Comment by JulianKingman** [comment]
I don't quite understand, but I look forward to v.2 :)
In any case, the real issue here is that it's saving as ejson, any idea why?
I just tried updating from 1.1.5 to 1.2.1, and now it gives me this error: ````Error: The nested class for [workouts] does not exist````

I realized there was an issue in my schema, where I was writing 'new Astro.Class', but removing the 'new' didn't fix it.

**Comment by jagi** [comment]
This error means that you haven't provided the `nested` property in a definition of the `workouts` field which should be a proper class name. Are you sure that the provided class name is correct?

**Comment by JulianKingman** [comment]
It's exactly as it's written above.
Could this have something to do with calling ````task.get('workouts')```` instead of ````task.get('workoutGroup')````? The actual field is workouts, should it match the class name?

**Comment by jagi** [comment]
Do you mean `tasks.get('workouts')` or `tasks.raw('workouts')`?
Please, do a few checks.

`task.raw('workouts')` - should return an array of plain JS objects like:
```js
[
  {'_id': 'some_id', 'sets': 'some_value', 'exercises': []}
]
```
Does it return such array?

You have to debug code and tell me exactly which line is throwing an error.

**Comment by JulianKingman** [comment]
I'm getting this error now when I try to add a workoutGroup:
````
Exception while simulating the effect of invoking 'newExerciseGroup' RangeError: Maximum call stack size exceeded(…) RangeError: Maximum call stack size exceeded
````

The method is pretty straightforward:
````javascript
newExerciseGroup: function (taskId, id) {
        var task = tasks.findOne(taskId);
        task.push({'workouts': new workoutGroup({_id: id})});
        Meteor.call('saveTask',task);
    }
````
I thought it wasn't liking the workoutGroup, but if I change that to a simplified json version, it doesn't like that either. I thought perhaps it didn't like sending the whole task to be saved, but changing it to just task.save() didn't help either... Something's not right here.

**Comment by jagi** [comment]
The order of defining class matters. It was always that way but in last version and make it even more strict because some performance improvements. So if you are using some class in the `nested` property it has to be already defined.

The `Maximum call stack size exceeded` error is cause by infinite loop. I see that you are calling another method inside the `newExerciseGroup`. It may be a problem.

**Comment by JulianKingman** [comment]
Oh... I see the issue... I had a 'beforechange' event calling that same method.

OK, well whatever combination of fixing the order of classes, debugging and updating I did, it now works properly and I'm not getting weird ````EJSON$value```` values in the database, so this is closed for me.

@JayMc, are you still having the issue?

**Comment by jagi** [comment]
OK good to here. I will close this issue for now.

**Comment by gatolgaj** [comment]
Hello ,
This Problem is Persisting for me in my Project. 
i have an Attribute Defined Like this 

```
   session: {
            type: 'array',
            default: function () {
                if (DEVELOPMENT) {
                    var sessionTime = Astro.getClass('sessionTime');
                    return [new sessionTime(), new sessionTime()];
                }
                else
                    return [];
            },
            nested: {
                name: 'sessionTime',
                fields: {
                    sessionId: {type: 'string'},
                    availableStartTime: {
                        type: 'string',
                        default: function () {
                            if (DEVELOPMENT) {
                                var array1 = ['08:00:00', '08:30:00', '09:00:00', '10:00:00', '11:00:00', '12:00:00'];
                                return array1[faker.random.number(5)];
                            }
                        }
                    }
                    ,
                    availableEndTime: {
                        type: 'string',
                        default: function () {
                            if (DEVELOPMENT) {
                                var array1 = ['13:00:00', '14:30:00', '15:00:00', '16:00:00', '18:30:00', '19:00:00'];
                                return array1[faker.random.number(5)];
                            }
                        }
                    }
                },
```

The `session` Attribute is inside another Attribute which is also an array. 
Now when i am updating the an already Existing Object by using the `.set()` method i find that the inner Array value is stored as `EJSON$value`

<img width="903" alt="screen shot 2016-04-22 at 8 32 17 pm" src="https://cloud.githubusercontent.com/assets/9367768/14745548/74d00092-08c9-11e6-8802-4367da385e9a.png">

Another Surprise is that when I retrieve the value back using `Class.findOne` it gives me back the result in correct format. 

Any Suggestions ? #157

**Comment by lukejagodzinski** [comment]
It's hard to tell without reproduction. And you should provide entire schema. Have you tried defining nested class outside of the `nested` property?

**Comment by alondahari** [comment]
I'm getting the same issue, in Astronomy 1.2.10
I have a triple nested class, like so (schemas are simplified):

``` javascript
_itemDiscount = Astronomy.Class({
  name: '_itemDiscount',
  fields: {
    name: 'string',
    discountAmount: 'number'
  }
})

_ItemInCart = Astronomy.Class({
  name: '_ItemInCart',
  fields: {
    itemDiscounts: {
      type: 'array',
      nested: '_itemDiscount',
      default: function(){ return [] }
    }
  }
})

Sales = new Mongo.Collection('sales')
Sale = Astronomy.Class({
  name: 'Sale',
  collection: Sales,
  fields: {
    itemsInCart: {
      type: 'array',
      nested: '_ItemInCart'
      default: function(){ return [] }
    }
  }
})
```

when pushing a discount to the item discounts, I get EJSON$type and EJSON$value in the database.
Thanks!
