### ISSUE TITLE
Defining fields

### ISSUE THREAD

**Issue by space-alien** [jagi/meteor-astronomy#158]
In the docs, there is a mix of:

```
fields: {
  phones: {
    ...
  }
}
```
and:
```
fields: {
  'phones': {
    ...
  }
}
```

Sometimes a field name is provided as a string literal. I assume this makes no practical difference?

**Comment by jagi** [comment]
Yes there is no difference. It's just how JS works.

**Comment by space-alien** [comment]
Thank you! That's what I thought. Let me know if you would like me to submit a PR to standardise the readme examples one way or the other. Personally, I prefer without the quotes, especially as that forces the use of valid JavaScript identifiers.

**Comment by jagi** [comment]
I don't think that there is a need for that. Developers know that it's possible to define it in both ways so they can choose the one preferred by them.
