### ISSUE TITLE
Is there any addToSet functionality in Astronomy?

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#159]
Let's say I want to ass multiple phones where Phone is a nested class.

```
Phone = Astro.Class({
  name: 'Phone'
  fields: {
    number: "string"
  }
})
```

I want to add an array of these nested classes, but no duplicates. Is there something like addToSet?
@jagi If not do you plan to add it ?
If you do, can you add an extra feature to that:
Normally addToSet checks the entire object to be duplicate. What if it took another argument and checked only those keys for duplicates. It would be quite awesome: 
`addToSet(obj, keysToCheckForDuplicate)`

**Comment by s7dhansh** [comment]
Something like this:

```
Array.prototype.isArray = true;
/**
 * @summary adds an object in the set maintining the uniqueness of one of the keys. eg. [{name: x}, {name: y}], with unique 'name'. If the key is same, then it will update the other values in the particualr object. eg. if Array is [{name: x}] and value is {name:x age: a}, Array will become [{name:x, age: a}]
 * @param {Object} value the item to be added
 * @param {String} key   unique key
 */
var extractKeys = function(o, keys){
  var ret = {};
  for (var i = 0; i < keys.length; i++) ret[keys[i]] = o[keys[i]];
  return ret;
};
Array.prototype.addToSet = function(value, keys){
  for (var i = 0; i < this.length; i++) {
    var left, right;
    if (!keys) {
      left = this[i]; right = value;
    }
    else {
      if (!keys.isArray) keys = [keys];
      left = extractKeys(this[i], keys);
      right = extractKeys(value, keys);
    }
    if (left === right) {
      for(var k in value) if(value.hasOwnProperty(k)){
        this[i][k] = value[k];
      }
      return;
    }
  }
  this.push(value);
};
```

**Comment by jagi** [comment]
I will probably introduce this method in the future versions

**Comment by jagi** [comment]
There will be no need to call the `addToSet` method in Astronomy 2.0. You will be able to just modify your document in every possible way and save it. There will be also full featured direct collection access.
