### ISSUE TITLE
Bubble up validation errors?

### ISSUE THREAD

**Issue by marbemac** [jagi/meteor-astronomy#161]
Consider the following:

```js 
if (model.validate()) {
    model.save();
} else {
    var errors = model.getValidationErrors();
    template.set('errors', errors);
}
```

If my root model is valid, but it has any nested schemas that fail, model.validate() will return false. However, model.getValidationErrors() will return an empty object since getValidationErrors only returns errors for the root schema. 

There seems to be an inconsistency here, where validate validates a model and all nested models, but getValidationErrors only returns the root model errors. In my case, I'm having to write custom validation functions for each model like so:

```js
methods: {
    customValidationErrors() {
      if (this.hasValidationErrors()) {
        return this.getValidationErrors();
      }

      if (this.request.hasValidationErrors()) {
        return this.request.getValidationErrors();
      }

      for (let r of this.responses) {
        if (r.hasValidationErrors()) {
          return r.getValidationErrors();
        }
      }
    },
}
```

This is a simple example, it gets more complex as you have more nested schemas. Is there a simple way to do this that I am missing? If not, might I suggest adding a getAllValidationErrors method to models, that returns the validation errors for the entire model (including nested schemas).

**Comment by jagi** [comment]
Do you have the newest version of the `jagi:astronomy-validators` package? Because it should work.

**Comment by marbemac** [comment]
Ah no I did not see the release from a couple of days ago. Working like a charm, nice job! Thanks for astronomy, just migrated over from simple schema + collection2 + collection hooks, and really enjoying it so far.

**Comment by jagi** [comment]
Glad to hear :) Enjoy :)
