### ISSUE TITLE
Saving is mandatory after pushing values to nested arrays and after every pop

### ISSUE THREAD

**Issue by darko-mijic** [jagi/meteor-astronomy#162]
If value is pushed to nested array using Astronomy's astroClassInstance.push() method it can not be removed before saving whole document.

Also, save must be called after every .pop().

For example:

```javascript
let contact = new Contact();
contact.push('phones', new Phone());
contact.pop('phones', 1); //Does not work and does not report an error
```

**Comment by darko-mijic** [comment]
Current workaround suggested by @jagi:

```javascript
var contact = Contacts.findOne();
var phones = EJSON.clone(contact.phones);
contact.phones.push(/* ... */);
contact.phones.pop(/* ... */);
contact.set('phones', phones);
contact.save();
```

**Comment by jagi** [comment]
Yes it must be saved. I will add information to the documentation when and why the `save()` method has to be called.

I'm already doing some research on improving Astronomy. I have a few ideas on how to avoid using `push`, `pull` etc. methods at all. It needs further investigation and it will appear in Astronomy 2.0. I have to prepare to it. For now it's how it works and it won't change a lot.

**Comment by darko-mijic** [comment]
This is my current workaround. I am using pop() directly on phones array ```doc.phones.pop()```, not ```doc.pop('phones')```.

And before saving I am doing this to remove top level modifiers and to add raw value for phones:

```javascript
delete doc._modifiers.$push.phones;
doc.set('phones', doc.raw().phones);
```

**Comment by laurentpayot** [comment]
I can't use `push` on an unsaved object array, because it doesn't get along well with `set`. So I'm using the following workaround (in <i>CoffeeScript</i>):
```coffeescript
if myItem._isNew
	rawList = (e.raw() for e in myItem.list)
	rawList.push(newElement.raw()) # normal JS array push, not Astronomy push
	myItem.set('list', rawList)
else
	myItem.push('list', newElement)
```

Hopefully this will be fixed in a future release...

**Comment by peXed** [comment]
Why was this issue closed? Is it fixed?
I still have problems saving documents with modified nested docs in nested docs (Root -> Nested Doc -> Nested Doc).

**Comment by jagi** [comment]
No it's was not fixed but it's one of the limitations of Astronomy 1.0. It's already fixed in 2.0. I can't implement it easily in 1.0. People will have to switch to 2.0 when it's released.

**Comment by peXed** [comment]
Oh, that was a fast reply. Thank you for the clarification!
You are doing an awesome job. Can't wait for 2.0 :+1:

**Comment by jagi** [comment]
:)
