### ISSUE TITLE
beforeFind event can't modify selector if only a string is used

### ISSUE THREAD

**Issue by gitamiller** [jagi/meteor-astronomy#164]
If you hook into the beforeFind event, you can't modify the selector if find is called with a string, like:
Model.findOne('abc');

In the beforeFind event, in code:
[meteor-astronomy/lib/modules/storage/init_class.js](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/storage/init_class.js#L233), line 233

```js
selector = selector || {};
```

Then when the event is called, on line 233
```js
    // Modify selector and options using the "beforeFind" event handlers.
    var event = new Astro.Event('beforeFind', {
      selector: selector,
      options: options
    });
```

If a string is used, javascript will copy the string and it's not a reference to the string that can be changed in the event handler like when you use a selector object;

This would also impact your softremove behavior as it won't work if you use FindOne with a string for an ID.

**Comment by jagi** [comment]
Yes in deed. I will fix it. I don't like the way Meteor does it. It changes the way MongoDB works. It's not possible to pass string as a selector in Mongo but in Meteor it's possible.

**Comment by gitamiller** [comment]
Thanks!
