### ISSUE TITLE
Can I get access to non-Astro objects server side?

### ISSUE THREAD

**Issue by JesperWe** [jagi/meteor-astronomy#165]
I am implementing https://github.com/meteorhacks/search-source on a collection of Astro objects as outlined below. The search result is sent to te client as a .fetch() array. As you can see in the code I am querying the Mongo.Collection (`Things.fetch()`), not the Astro.Class (`Thing.fetch()`). But I still get back all my objects as Astro objects. Search-source is not happy with this, and fails to send the objects to the client. If I pick only the `_original` from the array everything works, but that is of course very inefficient.

I would have thought that Mongo.Collection().find() shoudl return plain object, not Astro.Class instances...

Why is this happening? Is there any way I can get the "normal" objects from my collection without looping once more through all results?

	Things = new Mongo.Collection( 'things' );

	Thing = Astro.Class( {
		name: 'Thing',
		collection: Things,
		fields: {
			createdBy: {
				type: 'string',
				default: function() {
					return Meteor.userId() || null;
				}
			},
			language: {
				type: 'string',
				default: function() {
					return "en";
				}
			},
			title: 'string',
			description: 'string',
			...
		},
		indexes: {
			textsearch: {
				fields: {
					language: 1,
					title: 'text',
					description: 'text'
				},
				options: {
					weights: {
						title: 3
					}
				}
			}
		}
	} );

	if( Meteor.isServer ) {
		Meteor.publish( 'things', function() {
			return Things.find( {} );
		} );
		SearchSource.defineSource( 'thingsearcher', function( string, options ) {
			// format query object etc....
			return Things.find( query, dbOptions ).fetch();  // <<< Queries the Mongo.Collection!
		} );
	}

**Comment by jagi** [comment]
You can read about this in documentation [here](http://astronomy.jagi.io/fetching-documents), [here](http://astronomy.jagi.io/custom-transform) and [here](http://astronomy.jagi.io/publications)

**Comment by JesperWe** [comment]
Ha ha funny that the text in your first link was missing from the documentation when I was looking for it an hour ago :-) (It seems you re-organized the site...)

**Comment by jagi** [comment]
Yes it was missing and I've just noticed it :) (I've just deployed fixed version). There was a white space character at the file beginning what prevented displaying content (strange).
