### ISSUE TITLE
Class.find() returns documents from other classes

### ISSUE THREAD

**Issue by ianmartorell** [jagi/meteor-astronomy#167]
This is a feature request, because I haven't seen it in the documentation so I think it's not implemented.

When you have multiple classes in the same collection like this:
```
Items = new Mongo.Collection('items');

Parent = Astro.Class({
  name: 'Parent',
  collection: Items,
  typeField: 'type',
  fields: {
    parent: 'string'
  }
});

Child1 = Parent.inherit({
  name: 'Child1',
  fields: {
    child: 'string'
  }
});
Child2 = Parent.inherit({
  name: 'Child2',
  fields: {
    child: 'string'
  }
});
```
If you call `Child1.find()` I think it should only return documents where the `type` is `Child1`, but it returns all documents from the collection `Items`, even if they are different types.

**Comment by jagi** [comment]
Hmmm it may be a good idea, however it may break somebody's code...

**Comment by frabrunelle** [comment]
:+1: I would like this feature as well!

In fact, a few days ago I ran against this issue and I told myself that I would suggest it as a feature here. Thanks for opening this issue @ianmartorell :smile: 

I highly doubt it would break someone's code. Pretty much everyone would just have used Items.find() or Parent.find() I imagine.

**Comment by jagi** [comment]
Ok I've implemented this feature. It will appear with the next bugfix version.

**Comment by ianmartorell** [comment]
Great, thanks!

**Comment by ianmartorell** [comment]
Works well on 1.2.1
