### ISSUE TITLE
Question: How to trigger save from inside {{#each}} when nested field is updated?

### ISSUE THREAD

**Issue by JesperWe** [jagi/meteor-astronomy#168]
I have a rather complex class with some fields that are arrays of nested classes.
In my app I want to save to the DB every time an instance is modified.
I am using Blaze `{{#each}}` directives to render instances of the nested classes.

When there is a change in one of the fields of a nested instance inside the `{{#each}}`, I step into event handler in Blaze, but there I do not have access to my top level instance, since the data context (`this`) inside the `{{#each}}` is the nested instance.

This means that there is no `this.save()` method.

I also tried the `afterChange` event, but it is only triggered on the nested class, it doesn't bubble up to the class level above. And there doesn't seem to be any data available in the event handler in the nested instance to get hold of its parent.

Trying `afterChange` on the global level I get the event no matter where inside the hierarchy it occurs, but for events on a nested instance `event.target` is still the nested instance with no way to save or get hold of the parent.

I could of course use a global variable to signal the need for a save of the parent instance, but this seems very in-elegant to me. Is there any better solution?

**Comment by jagi** [comment]
I don't know if it's gonna help but check this out http://docs.meteor.com/#/full/template_parentdata

**Comment by JesperWe** [comment]
Mmm actually I use BlazeComponents so it does not work, but you gave me a new idea to try using the BlazeComponent tree traversal and get the data context from that, which worked.

Thanks.

As a side comment, I find the `afterChange` event a bit weird, since it fires even when i do a `.find()` (on all fields). Sure the field on the instance is changed from non-existent to something when it is created, but I find that event rather uninteresting....??

**Comment by jagi** [comment]
Hmmm it may be a bug. I will check it out. Closing for now this issue.
