### ISSUE TITLE
Suggestion: Collections still return plain js document(s)

### ISSUE THREAD

**Issue by zhaoyao91** [jagi/meteor-astronomy#169]
Great work, beautiful design, love it so much.
Through reading the documentation, I find that almost all functionalities are implemented as separate parts, only one thing, Collections now return a transformed doc(Astro class instance) by default. I think this is not so good. By **NOT** changing this with Collections, it can be a complete and clean extension  to old low level meteor-mongo mechanism, giving developers a clear line to choose which level they are working in, and, make it better compatible with other projects (especially for which is migrating)

**Comment by VladShcherbin** [comment]
Ha-ha, exactly the same thing I asked yesterday to be implemented. The clean way to choose, when to call model and when the collection. Plus non-breaking previous publications.

**Comment by jagi** [comment]
I've implemented mechanism to turn off transformation globally by setting `Astro.config.disableTransform = true;`. It will appear in the next published version of Astronomy. So I'm closing this for now :)

**Comment by VladShcherbin** [comment]
@jagi Awesome, thank you!
