### ISSUE TITLE
Default value for nested fields

### ISSUE THREAD

**Issue by parhelium** [jagi/meteor-astronomy#17]
I have a lot of nested documents and would like to manage them using Astronomy package.

```
A = Astro.Class( {
    name: 'A',
    collection: ACollection,
    fields: {
        name: {
            type: 'string',
            default: ''
        },
        displayName: {
            type: 'string',
            default: ''
        },
        notes: {
            type: 'string',
            default: null
        },
        links: {
            type: 'array',
            default: []
        },
        category: {
            type: 'string',
            default: ''
        },
        subObject: {
            type: 'boolean',
            default: false
        }
    }
)
```

Field `links` is array of objects.
Usually I'm using `js-schema` library : 
```
ASchema = schema({
    name : String,
    displayName : String,
    notes : String ,
    links : Array.of( {
        _id: String,
        amount: Number,
        unit: String,
        prepMethods: Array.of( String )
    }),
    category :  String,
    subObject : Boolean
})
```
However [`js-schema`](https://github.com/molnarg/js-schema/) doesn't allows me to specify default values for each field.
I would love to have [`js-schema`](https://github.com/molnarg/js-schema/) syntax together with your validators.

Something like that, would be brilliant : 

```
var t = function(type, default){
   var obj = {type:type, default : default};
   return  obj
}
A = Astro.Class( {
    name: 'A',
    collection: ACollection,
    fields: {
        name :               t('string', 'hello'),
        displayName :       t('string', 'displayname'),
        notes :               t('string', 'default notes') ,
        links : Astro.arrayOf( {
            _id:                t('string', 'default notes'),
           amount:               t('number', 0) ,
           unit:                t('string', 'default notes'),
           prepMethods:       Astro.arrayOf( t('string', 'default') )
       }),
       category :  t('string', 'default'),
       subObject : t('boolean', true)
    }
)
```

Let me know what do you think about it?

**Comment by jagi** [comment]
Yes it's the problem now. I was thinking about that, and how to resolve it.

First of all if it goes about nested validators I have solution for that, which probably I'm going to implement today.

If it goes about default values the problem is more complex. I assume that you don't want to pull out you array of links to different collection? I have to think about the solution and will let you know later today.

**Comment by parhelium** [comment]
I have semi-solved this problem now.
For nested fields definition I'm creating new `type`, so casting works fine.
However for validation purpose I use my old friend - `js-schema`, which have builtin validators and can validated nested object without any problem. The only drawback of `js-schema` is that I cannot define my own validators. 
## Example

```
var linksSchema = schema(
    Array.of( {
        _id: String,
        amount: Number,
        unit: String,
        prepMethods: Array.of( String )
    } )
);

Astro.createType( {
    name: 'links',
    cast: function ( value ) {
        if ( _.isArray( value ) ) {
            _.each( value, function ( obj ) {
                obj.amount = parseInt( obj.amount )
            } )
            return value;
        }
        return value;
    }
} );
```

For nested object I created validator `nested`, which takes as argument `js-schema` validator.
For now it works.

**Comment by jagi** [comment]
@parhelium I've made nested validators. New version is on the Atmosphere. You can read more about nested validators here: https://github.com/jagi/meteor-astronomy/wiki/Validators and if you use simple validators package here: https://github.com/jagi/meteor-astronomy/wiki/Simple-Validators

Nested field's default value is coming :)

**Comment by parhelium** [comment]
@jagi great !
I'm going to test this in the evening.

**Comment by parhelium** [comment]
@jagi, big thanks for this feature!
I have successfully update astronomy to version 0.10.4 in my project. It works so good, that I have removed js-schema... :+1:  

I noticed validation stops on first invalid field, that is perfect for most use cases.
However there is on use case where validation should not stop on first invalid field.

In my apps I try to keep structure of documents consistent all the time ( what a suprise ;-) ) so on every startup app is validating all documents in all collections. 
It may happen that doing some changes manually on db admin simply broke structure.

Let me know if sth like that could be easy to add.
Again, thanks for your hard work ! :)

**Comment by jagi** [comment]
Great to hear! :)

**Comment by jagi** [comment]
Now you can set default values of the nested fields. I'm going to update readme soon however you can now use following syntax.

```js
var Item = Astro.Class({
  name: 'Item',
  collection: Items,
  fields: {
    'object': {
      type: 'object',
      default: {}
    },
    'object.property': {
      type: 'string',
      default: 'some default string'
    },
    'array': {
      type: 'array',
      default: []
    },
    'array.$': {
      type: 'object',
      default: {}
    },
    'array.$.property': {
      type: 'number',
      default: 123
    }
  }
});
```

I hope you will like it. If something does not work as expected then let me know.

**Comment by parhelium** [comment]
Yupi ! Looks great. Will test tomorrow in the morning.

**Comment by JulianKingman** [comment]
This isn't working for me in the user collection... I'm trying to set the profile and profile.roles as defaults

**Comment by jagi** [comment]
Show your schema, so I will be able to help.

**Comment by JulianKingman** [comment]
```javascript
User = Astro.Class({
  name: 'User',
  collection: Meteor.users,
  fields: {
    emails: 'array',
    services: 'object',
    createdAt: 'date',
    username: 'string',
    profile: {
      type: 'object',
      default: {}
    },
    'profile.fragments': {
      type: 'array',
      default: []
    },
    'profile.role': {
      type: 'array',
      default: ['peon']
    }
  },
  relations: {
    lockedfragments: {
      type: 'many',
      class: 'Fragment',
      local: 'fragments',
      foreign: '_id'
    }
  },
  }
});
```

**Comment by jagi** [comment]
Ok, now I see what are you trying to achieve. Right now no achieve that you would need following schema:

```js
User = Astro.Class({
  name: 'User',
  collection: Meteor.users,
  fields: {
    emails: 'array',
    services: 'object',
    createdAt: 'date',
    username: 'string',
    profile: {
      type: 'object',
      default: {
        fragments: [],
        role: ['peon']
      }
    },
    'profile.fragments': {
      type: 'array'
    },
    'profile.role': {
      type: 'array'
    }
  }
});
```

Nested fields are not set to default value until trying to get given value or set given value with `null` or `undefined`. In the 0.13.0 version it will change. Your schema will look like follows:

```js
Profile = Astro.Class({
  name: 'Profile',
  fields: {
    fragments: {
      type: 'Array',
      default: []
    },
    role: {
      type: 'Array',
      default: ['peon']
    }
  }
});

User = Astro.Class({
  name: 'User',
  collection: Meteor.users,
  fields: {
    emails: 'Array',
    services: 'Object',
    createdAt: 'Date',
    username: 'String',
    profile: {
      type: 'Profile',
      default: {}
    }
  }
});
```

Thanks to that all the nested fields will be set by default and it will be much more readable. I'm also planning to introduce another way of defining nested fields.

```js
User = Astro.Class({
  name: 'User',
  collection: Users,
  fields: {
    emails: 'Array',
    services: 'Object',
    createdAt: 'Date',
    username: 'String',
    profile: Astro.Class({
      name: 'Profile',
      fields: {
        fragments: {
          type: 'Array',
          default: []
        },
        role: {
          type: 'Array',
          default: ['peon']
        }
      }
    })
  }
});
```

For now you achieve what you want, you have to use that I've posted above or wait for the next release.

**Comment by JulianKingman** [comment]
Thanks, thanks! So what you’re saying is that the default value won’t be set until I get the value… could I do something like this? (Doesn’t work as it is):

```javascript
  events: {
    afterinsert: function(){
      var fragments = this.get('profile.fragments');
      var role = this.get('profile.role');
      this.save();
    }
  }
```

I really like the 3rd way, it’s very ‘meteor’.


On August 13, 2015 at 4:38:39 AM, jagi (notifications@github.com) wrote:

Ok, now I see what are you trying to achieve. Right now no achieve that you would need following schema:

User = Astro.Class({
  name: 'User',
  collection: Meteor.users,
  fields: {
    emails: 'array',
    services: 'object',
    createdAt: 'date',
    username: 'string',
    profile: {
      type: 'object',
      default: {
        fragments: [],
        role: ['peon']
      }
    },
    'profile.fragments': {
      type: 'array'
    },
    'profile.role': {
      type: 'array'
    }
  }
});
Nested fields are not set to default value until trying to get given value or set given value with null or undefined. In the 0.13.0 version it will change. Your schema will look like follows:

Profile = Astro.Class({
  name: 'Profile',
  fields: {
    fragments: {
      type: 'Array',
      default: []
    },
    role: {
      type: 'Array',
      default: ['peon']
    }
  }
});

User = Astro.Class({
  name: 'User',
  collection: Meteor.users,
  fields: {
    emails: 'Array',
    services: 'Object',
    createdAt: 'Date',
    username: 'String',
    profile: {
      type: 'Profile',
      default: {}
    }
  }
});
Thanks to that all the nested fields will be set by default and it will be much more readable. I'm also planning to introduce another way of defining nested fields.

User = Astro.Class({
  name: 'User',
  collection: Users,
  fields: {
    emails: 'Array',
    services: 'Object',
    createdAt: 'Date',
    username: 'String',
    profile: Astro.Class({
      name: 'Profile',
      fields: {
        fragments: {
          type: 'Array',
          default: []
        },
        role: {
          type: 'Array',
          default: ['peon']
        }
      }
    })
  }
});
For now you achieve what you want, you have to use that I've posted above or wait for the next release.

**Comment by jagi** [comment]
I would not recommend doing it in this way:

```js
  events: {
    afterInsert: function(){
      var fragments = this.get('profile.fragments');
      var role = this.get('profile.role');
      this.save();
    }
  }
```

However if you really want to do it use `beforeInsert` event instead of `afterInsert`. Thanks to that it will make only one save. You also do have to store data in any variable.

```js
  events: {
    beforeInsert: function(){
      this.get('profile.fragments');
      this.get('profile.role');
    }
  }
```

However, as I said, I would avoid doing it that way.

**Comment by JulianKingman** [comment]
How would you recommend setting a default field for a user when they start up?

The issue with using beforeInsert is that it (I believe) depends on the Astronomy way of creating a document, and doesn't work with the user registration process which goes on behind the scenes.

**Comment by jagi** [comment]
It seems to be problematic. You would have to wait until I implement collection events.
