### ISSUE TITLE
suggestion: get old values in afterUpdate event

### ISSUE THREAD

**Issue by zhaoyao91** [jagi/meteor-astronomy#172]
I found that, we can only get the new updated doc in the afterUpdate event. sometimes we want to do something with both the old values and new values, such as, log the difference. I don't know how to deal with it by now.

**Comment by zhaoyao91** [comment]
great, I find that e.target._original keeps the old values. since this is a private fields, I am not sure if I could rely on them.

**Comment by jagi** [comment]
You can get the old values using `e.target.getModified(true)` and of course you can also access them using `e.target._original` but as you said it's a private property. However I'm not planning to mess with it so it's quite safe to work with it.
