### ISSUE TITLE
Release this as a regular npm module as well

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#173]
I really like what astronomy has to offer but i don't see a reason why you'd limit it with just meteor. I know we have mongoose, but this seems much better approach. Do you think it's a possibility for you to release an npm variant of this package?

**Comment by jagi** [comment]
Hmm it's interesting proposition. Some thing are Meteor specific like for example document transformation or document EJSON-ification. It's definitely not possible to easily create an npm module out of the current version. However I will consider this when creating Astronomy 2.0

**Comment by talha-asad** [comment]
You closed this issue, does it mean that 2.0 is going to get npm support?

**Comment by jagi** [comment]
Yes it's not going to be the npm package as it's to closely integrated with Meteor.
