### ISSUE TITLE
How to define several same behaviors?

### ISSUE THREAD

**Issue by zhaoyao91** [jagi/meteor-astronomy#175]
By now, I have to do it like:

      User.extend({behaviors: {resources: {fieldName: 'profile.avatars'}}});
      User.extend({behaviors: {resources: {fieldName: 'profile.posters'}}});

How can I define them in just one schema?

**Comment by jagi** [comment]
Unfortunately it's not possible now. But I know about this problem. I'm going to introduce **named behaviors** in the future, but there are more important things for now to implement.

**Comment by jagi** [comment]
Named behaviors will be available in Astronomy 2.0. Closing this issue for now. Version 2.0 will be available soon.
