### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MeKarina** [jagi/meteor-astronomy#178]
I just trying to use astronomy for my new app

1) Does default have the same function with autovalue in collection2? Or refer to defaultValue in collection2?

2) I don't get the reason you create getModfied(). This can be done by performing get(), is it? 

3) save() method is quite helpful but this would be great if you differentiate insert and update. I don't mean you to dump save() method. What I mean is to add the same function like save() but only performing insert or only performing update. This will helpful if your user need to build large app which need more flexibility. Yes we can use direct collection access, but I really love the way of set() and save() method

4) Is there example how to use Storage events and Modification events? This is essentially do the same work like `collection hooks`, is it?

thank You

**Comment by jagi** [comment]
1) I don't know how exactly autovalue in collection2 works but you have everything explained here: http://astronomy.jagi.io/default-values It just sets a default value of a field if none provided. It can set it on save or on document fetch

2) The `getModified()` method returns object of fields that had been modified, so there is a reason for having it. And it can also get an old value (before modification)

3) There's no point of introducing such methods. Give me an example and I can consider it.

4) Storage events are executed on document insert, update, remove so it's similar to how the `collection-hooks` works. However, the modification events are executed on document modifications even if they are not going to be persisted in a database.

**Comment by yudaprama** [comment]
1) If it aim to generate static value then it have similar function with `defaultValue` in `collection2`. If it aim to generate dynamic value then it have similar function with `autovalue` in `collection2`. Which one? Or both?

2) I see. Indeed a good feature!

thank You..

**Comment by MeKarina** [comment]
thank @jagi
