### ISSUE TITLE
self relation based in a variable

### ISSUE THREAD

**Issue by frankapimenta** [jagi/meteor-astronomy#18]
The wiki does not specify this situation I have.

How could one do a relation to self based on an array of ids?

User follows other User and maybe vice-versa?

class User would have an array "followersIds" with all of the ids of its followers.

User: _id, followersIds: [id2,id3,id4]; var user = new User(); user.followers

Thank you for your time

**Comment by jagi** [comment]
Sorry for a late response. It's not possible right now to create many to many relation. Relations module it's in its early version so it needs improvement. There will be some changes in API.

Right now to create many to many relation you would need to create it by hand. Store followers ids in array fields.

I will be working on improving relations soon. So I will let you know. Sorry for inconvenience.

**Comment by frankapimenta** [comment]
No worries :)
Ok. So I will create a getter in the class and use the array of ids to do this part.
BTW: Great Job :+1:

**Comment by jagi** [comment]
Ok good to hear :)

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.
