### ISSUE TITLE
How to (Can we) define events on nested object in array?

### ISSUE THREAD

**Issue by zhaoyao91** [jagi/meteor-astronomy#180]
I have simply my model as below: 
but this doesn't work.

        Items = new Mongo.Collection('items');
        
        Item = Astro.Class({
            name: 'Item',
            collection: Items,
            fields: {
                subItems: {
                    type: 'array',
                    nested: {
                        name: 'ItemSubItem',
                        fields: {
                            msg: 'string'
                        },
                        events: {
                            afterInsert(e){
                                console.log('create sub item~~')
                            },
                            afterUpdate(e){
                                console.log('update sub item ...')
                            },
                            afterRemove(e){
                                console.log('remove sub item !!!');
                            }
                        }
                    }
                }
            }
        });

**Comment by ianserlin** [comment]
It's an interesting question - I was just wondering how I can/should be able to apply a behavior like `timestamp` to a nested model.

**Comment by jagi** [comment]
Yes it does not work. Unfortunately something (nested classes) that was intended to solve many problems is causing many other problems. I've decided that I in 1.3 version I will bring back the old way of defining nested fields. It will solve all the problems with nested events, behaviors etc. Both ways of defining nested fields will work however it will be recommended to use the new (old) way from the 1.3 version.
