### ISSUE TITLE
Get accessor could return null on non-existing nested fields?

### ISSUE THREAD

**Issue by dbismut** [jagi/meteor-astronomy#183]
Hi - I've been finally able to play with Astrology, and I was wondering if the `get` accessor could return null on non-existing nested fields instead of throwing an error? `set` could similarly create non-existing nested fields and be able to set the value.

so if I have `foo = {a: {b: 1}}`, `foo.get('a.c')` would return `null`, and `foo.set('a.c', 2)` would result in `foo = {a: {b: 1, c: 2}}`.

**Comment by jagi** [comment]
The `get` method does not throw error if a nested field does not exist.

However, the `set` method won't create a non existing field if there is a nested class provided. Astronomy will want to keep a model correct with what was provided in the schema.

**Comment by dbismut** [comment]
You're right, sorry - I'm transitioning with Collection2 and reusing some code. Thanks for the clarification on `set`.
