### ISSUE TITLE
option to override immutable constraints in trusted code (server)

### ISSUE THREAD

**Issue by marbemac** [jagi/meteor-astronomy#186]
We have a billing model, with limits on it. For obvious reasons, we've marked those limits as immutable so that users cannot change them. However, we have a trusted server method that's called when a user updates their billing. From that trusted method, we'd like the ability to change the limits. However, we cannot right now because they're marked as immutable. To get around this, we are updating directly via the meteor collection. It'd be cool if there were an option to override immutability, available only on the server. Thoughts?

**Comment by jagi** [comment]
You can achieve that by not defining the immutable field on the class schema and later by extending the class. On the client you can extend the class with the immutable field, on the server you extend with the normal field.

**Comment by marbemac** [comment]
A typical update method for one of our models looks like this:

```js
Meteor.methods({
  '/endpoint/update'(model) {
    SL.H.ACL.canUser.update.resource(this.userId, model, true);
    model.protect();
    model.save();
  },
});
```

You'll notice that I've put in a "protect()" method that we call from all of these CRUD methods, to delete properties that we want to protect from the user updating. Ideally, we would use immutable for this. But SOME of those immutable properties need to be savable from other methods that only admins can call (our ACL system only lets users with admin rights call those special methods). So, when a model is saved in that method, we want to allow modification of those immutable fields.

I don't think the strategy you've described would help in this scenario, as it still leaves the "immutable" fields open on all server-side methods.

**Comment by jagi** [comment]
```js
var Post = Astro.Class({
  /* ... */
});

if (Meteor.isClient) {
  Post.extend({
    fields: {
      immutableField: {
        type: 'string',
        immutable: true
      }
    }
  });
}

if (Meteor.isServer) {
  Post.extend({
    fields: {
      immutableField: {
        type: 'string',
        immutable: false
      }
    }
  });
}
```

Does it what you understood from my reply?

If I understand you correctly you want this field to be (on the server) sometimes immutable and sometimes not. If it's what you want then you can't do it with the immutable property. You would have to do it by hand.
