### ISSUE TITLE
Velocity does not work well with Astronomy

### ISSUE THREAD

**Issue by zvictor** [jagi/meteor-astronomy#187]
# Problem

When trying to use Velocity & Astronomy together, it raises `Error: Custom EJSON type Astronomy is not defined`.

# Scenario

A minimal reproducible scenario can be found at https://github.com/zvictor/astronomy-EJSON-bug.
Velocity uses Meteor's `methods` and `calls` to transfer data.

# Debugging
1. In normal server/client & methods/calls operations everything works fine.
<img width="241" alt="screen shot 2015-11-12 at 12 01 21" src="https://cloud.githubusercontent.com/assets/181076/11116910/fc862d90-8935-11e5-9ef0-fb55160afc51.png">

2. While in Velocity, the server fetches the right data and fail right after, when trying to send it to the client (nodejs in this case).
![screen shot 2015-11-12 at 12 01 58](https://cloud.githubusercontent.com/assets/181076/11116912/00f7ef80-8936-11e5-9a2a-4c9fa715af26.png)

----

**Note**: It seems to be more a problem in Velocity than in Astronomy, but I couldn't find the Velocity's issue page to post it there. =/

**Comment by jagi** [comment]
It's probably a problem residing in both tools. One problem of many tools (like Velocity) is that they modify a document fetched from the collection. If it's changed to much, Astronomy/Meteor can have problems with dealing with data. What I would suggest is turning off transformation.

```js
Post = Astro.Class({
  name: 'Post',
  collection: Posts,
  transform: null,
  /* ... */
});
```

After that Velocity should work properly. But how to fetch Astronomy documents from the collection. You can still use the `Post` class for that:

```js
Post.findOne(); // Will return Astronomy document.
Posts.findOne(); // Will return simple JS object.
```

In future Astronomy releases I'm planning to turn off automatic transformation for collections.

**Comment by zvictor** [comment]
Is it a good idea to disable transformation? I like to have Astronomy doing that and I would prefer to keep it like it is now =)

What I am doing for now is executing `JSON.stringify/parse` on both sides of the calls used by Velocity. It works fine, although it's annoying.

**Comment by jagi** [comment]
You can still use transformation but disable them for collections by default. Thanks to that Velocity should work properly. Have you checked if does it work with Velocity?

**Comment by zvictor** [comment]
No, I haven't tried it yet but I think I will need to give it a try soon.

I have just found out that Velocity is no longer maintained by the same team and that issues are now supposed to be posted at  xolvio/chimp. We now have it posted there as well.

**Comment by jagi** [comment]
You know many packages dealing with data from collections assume that documents are plain javascript objects and they don't have any schema. That's why sometimes you need to turn off documents transformation.

I'm working on some improvements in data modification in Astronomy 2.0 and it may make developers lives easier. But I will tell more when I have working beta version.

**Comment by zvictor** [comment]
Problem solved, all what you need to run in order to have all your server calls automatically converted to raw format is:

`meteor add quadric:backdoor-raw`


more details at xolvio/chimp#152

Thanks!
