### ISSUE TITLE
Question about slug

### ISSUE THREAD

**Issue by MeKarina** [jagi/meteor-astronomy#188]
I've tried slug behavior as the docs. If input value `Me Karina`, it convert become `me-karina`. Does it possible to convert into `MeKarina` ?

thank you..

**Comment by jagi** [comment]
Right now you can't convert it from `Me Karina` to `MeKarina`. However, you can convert it to `mekarina` by setting the `separator` behavior option to `""` (empty string).

```js
behaviors: {
  slug: {
    separator: ''
  }
}
```

It's worth mentioning here that URL address should be treated as case insensitive. Of course, you can create addresses that are case sensitive but it's not recommended. If you are using slug for URLs that I would recommend making it lower case. If you are using it for something else and if you want to just remove all white spaces, then you should probably use the `replace` method on a string.

**Comment by MeKarina** [comment]
hi @jagi chek this: http://jsfiddle.net/Rkb57/

**Comment by jagi** [comment]
And what about this example?
