### ISSUE TITLE
toString() is being called on fields of type 'string' when validating/saving

### ISSUE THREAD

**Issue by cjsauer** [jagi/meteor-astronomy#189]
I'm not sure if this is expected behavior, but say I have a very simple collection: 

```JavaScript
Things = new Mongo.Collection('things');
Thing = Astro.Class({
  name: 'Thing',
  collection: Things,
  fields: {
    name: 'string'
  },
  simpleValidators: {
    name: 'required, string'
  }
});
```

And then say that I call:

```JavaScript
var thing = new Thing({name: {oops: 'this is not a string!'}});
if(thing.validate()) thing.save();
```

This is being validated and saved! If I look in the database, there is a document for Thing that looks like `{ name: '[Object object]' }`. This can not be expected behavior...

**Comment by jagi** [comment]
Yes, the problem here is more complex. In fact the `string` validator should be used with a field of the `null` type, where a value can be of any type. Astronomy makes sure that any value being set on a field is casted to the type defined for the field. So, it converts object to the string.

In future Astronomy releases, I plan to rethink validators. Such case as mentioned by you is more a job for a forms package, before any value is assign to the document. In fact, assigning non string value to the field of the string values should throw an error.

I'm open to discussion about this subject

**Comment by cjsauer** [comment]
Thanks for the quick response. I changed the field type to `'null'` and now my tests are passing, so that is a successful workaround. Sorry if this is a reposted issue; I searched around but couldn't find a similar report. 

I agree with you in that this shouldn't be the responsibility of Astronomy, but I don't know if it's even the responsibility of a forms package. I think it's up to the programmer. I am not a fan of having "magic" done on my behalf without my knowledge. I'd be much more comfortable calling `parseInt()` or `toString()` myself.

**Comment by jagi** [comment]
Yes, you are definitely right. This magic is not always good. That's why I think that it needs more discussion. It should probably throw error on setting wrong value and a developer should care about type by himself/herself. But many developers would not be happy with such change. So maybe there should be an intermediate solution. A field of the `string` type should correctly cast to string values like numbers but not objects. A field of the `boolean` type should cast any string to `true` and falsy values to `false`. Right now the `boolean` type parses the `"FALSE"` string to `false` which I think is a job for the forms package.

**Comment by VladShcherbin** [comment]
This thing with the types really sux. You need to specify twice, that this is the string and validation still does not show you an error.

I think, we should always have a types validation before the `.set` fires. This way, the validation will fail before the `.set` method and we won't need to specify the type twice (in fields and validators).

**Comment by VladShcherbin** [comment]
If the user does not want the validation and wants the transformation (any type to string for example), he can use astronomy w/o validators.

And we can add a simple check - if the astronomy validators package is installed, run the types validation before the `.set` method. But this way astronomy will need to set the validation errors even before we run the `validate` method.

**Comment by jagi** [comment]
It's more complex than that. When you think about it more deeply than you can came to conclusion that it should not allow setting a different value than one defined in the schema. Let's say we have a field of the `boolean` type. It should throw error when setting non boolean value. The schema can look as follows:

```js
var Post = Astro.Class({
  /* ... */
  fields: {
    title: 'string',
    isPublished: 'boolean',
    publishedAt: 'date',
    createdAt: 'date'
  }
});
```

How I see it is one more layer of abstraction between form and model. Let's say we have an input field for the field of the `boolean` type. The value from the input field can be a string. We collect values from the form that looks a follows:

```js
{
  title: 'Some title',
  isPublished: 'true',
  publishedAt: '2015-11-14',
  createdAt: '2015-11-15'
}
```

Now, this data should go through the process of converting values and validation. The layer between form and model can be called `validation`. The validation layer should be aware of the model and know what types does it expect for which fields. For example if it's not possible to convert the string value to boolean for the `isPublished` field than it should register an error that can be displayed in the form. If a date string can't be converted to a date object it should also register an error. However it's only validation of values coming from the form. It can check if a value is of the proper type if a string field is of the minimal or maximum length etc.

There should be an another layer of validation residing in a model that checks data integrity. For example if the publication date is after the creation date. It should also register an error that could be possible to display in the form. Such validation is not related with any particular field. Checking publication and creation date does checking on two fields, so a developer can choose where to display an error. As I said, it's a layer checking data integrity. It can also be called Post Validation (it's a term used in Doctrine framework for PHP).

What do you think about it? I think it needs rethinking everything from the ground up. It's needs a discussion.

**Comment by VladShcherbin** [comment]
Yes, it is a bit hard to validate. I do think that the creation date is the validation part, it is just a field and a user should be able to change it.

The whole problem is that we validate after we update the model. If we grab the values (from the form for example), then validate them and only then set to the model - it will be okay. 

We kinda have a model validation, but I will be actually happy to have a Validator's class, that can accept values and return errors, according to rules in it. This way, I'll create form rules and check them. It would be very flexible, reusable and nice way to even decouple validation from astronomy so we can use it everywhere. 

@jagi what do you think?

**Comment by VladShcherbin** [comment]
So, basically, what I mean is:

Model:
has fields, that can be used to inserted/updated/etc, can accept any value w/o validation. If the incoming input values come with fields, that are not in the model - cut them as they are not accepted. Model also have methods, behaviours, etc.

Validator:
can accept values and rules, can check the values against rules and return status + errors

So, when you submit a form, values are passed to Validator and if true, they are saved to database. This way, you can validate everything in your app, not only astronomy classes :+1:

**Comment by VladShcherbin** [comment]
So you have kinda:

```js
// Model
class Post extends BaseModel {
  constructor() {
    this.fields = [
      // fields, a model can have
      'title', 'slug', 'contents'
    ];

    this.indexes = {
      // indexes
    };

    this.behaviours = [
      // behaviours
    ];
  }

  // can have methods
  get allPosts() {
    // return all posts
  }
}

// Form validation
// values - values from the form
const rules = {
  title: 'required,string,minLength(3),maxLength(100),unique',
  slug: 'required,string,minLength(3),maxLength(100),unique',
  contents: 'required,string'
};

let values           = {'...'},
    validationResult = new Validator(values, rules);

if (validationResult) {
  new Post(values);
  
  // redirect somewhere
} else {
  // show errors
  validationResult.getErrors();
}
```

**Comment by jagi** [comment]
In my last post I've made a mistake. One you wrote about model is correct, so summing it up.

MODEL and VALIDATION
1. You can set any value on the model.
2. Any non existing field value will be cut out of the model
3. Validation should be performed on saving
  1. It should check if a value is of the proper type
  2. It should check any other field constraints like immutable etc.
  3. You can get validation errors and display them in the form
  4. Any other validators should be executed too

If it goes about the FORMS I see two possibilities:
1. User is responsible for converting forms values to the proper types
2. User can attach a model to the form and get automatic fields casting but he/she can also perform custom casting if a model can't handle it.

Right now, I don't know if I should decouple validation and model. I know many frameworks that keep them together.

**Comment by VladShcherbin** [comment]
@jagi fully agree on all the points above. The reason why I propose to decouple Validation is that this way we can have it everywhere and check almost everything (just like the `check` function). We can even use it not only in Meteor.

So I propose to create a validation, that can be used almost as core validation for everything in meteor. In forms saving method we can use it and be happy.

**Comment by VladShcherbin** [comment]
The only downside is that it requires a lot of rewriting and major breaking changes so it is v2 or ever v3.

**Comment by jagi** [comment]
Yes it sounds like a good idea. The only thing that bothers me is that the model still have to have type validation, which of course could use Validators package as a dependency. Yes it would appear in 2.0. It's not a lot of rewriting. Actually there will be more removing than creating a new code :)

**Comment by VladShcherbin** [comment]
Oh, that sounds great actually!

I think, we can have a weak validators dependency for models, if no validators - use underscore (if we need it in astronomy) or even typeof for such a small thing.

What do you think about using the es2015 classes? It has great support, syntax and opportunities. Babel will help older browsers. In fact, I think models is the perfect example of using js classes. Any chance to use it?

**Comment by jagi** [comment]
Yes weak dependency is a good idea.

I'm actually working on 2.0 and already using es2015 classes :). I haven't switched to it in all places yet but I'm planning to use it wherever it's possible.

**Comment by VladShcherbin** [comment]
@jagi the more you tell the news, the better they are!

2.0 will be definitely an awesome update for an already sweat pie for all of us. Huge thank you ;)

**Comment by jagi** [comment]
:) no problem

**Comment by soaresa** [comment]
Hello
For every class I use Validators I am setting beforeSave events to validate the object. If it's not valid I  throw Validation Exception and catch it on controller. I prefer this approach to guarantee consistence always. 
Right on!

**Comment by jagi** [comment]
@soaresa in Astronomy 2.0 it will validate a model on save operation by default and it will probably throw error. Right now you have to use the `validate()` method that returns `true` or `false`. However, when I move validation to the save method (calling the `validate()` method by hand will still be possible) I should inform a developer somehow about errors. I could return `true` or `false` from the `save()` method but I won't because I will also introduce chaining in 2.0, so it has to return itself.

```js
var id = Users.findOne().save()._id;
```

So the only way of getting know if there were any errors is throwing exception. I hope that it won't scare people :). There are many developers that don't like playing with try catch blocks :)

**Comment by cjsauer** [comment]
@jagi I agree with your direction on 2.0. Looking forward to further releases!

**Comment by soaresa** [comment]
@jagi, that will be great! I also agree with your direction.

Once your start validating before storage methods, you could provide a "friendly" way to save objects on server side. Like catching exceptions at server and putting errors back to the document at client side automatically. 

For now I have created an asynchronous class method ```Janus.save(object, callback(error, result))``` for client side to save my Astro objects at server side. It does the ```object.clearValidationErrors()``` at the beginning, evoques the ```Meteor.call()``` to save the object, it does the ```object.catchValidationException(error) ``` on meteor callback if a validation exception is thrown and at the end it executes the developer's callback.

But I am ready to throw it away if you come out with something better in Astronomy 2.0 :-) 

PS: Why Janus? https://en.wikipedia.org/wiki/Janus

**Comment by cjsauer** [comment]
@soaresa that's really clever. Hope it's ok that I steal this ;)

**Comment by soaresa** [comment]
Of course, @cjsauer. No problem at all...

**Comment by soaresa** [comment]
Hi @jagi.

With almost all operations using Astronomy objects I use an atomic method. In some cases now I am letting the client starts the object modifications and than I ask the server to save it because I am not using allow/deny rules at all. It looks like a behavior of a transaction system that needs the server to save everything.

I was never a fan of exposing the DB layer for the client but I do understand the pros for Meteor apps.

Thanks!

**Comment by jagi** [comment]
As I said before in Astronomy 2.0 there will be a choice. You will be able to use methods or allow/deny rules. Whatever you like. The current version of Astronomy 2.0 is already doing all that stuff and it works great. I'm adding more features and improving others. I think it will be a big change for everyone.
