### ISSUE TITLE
validator syntax - feature request

### ISSUE THREAD

**Issue by dovrosenberg** [jagi/meteor-astronomy#19]
Not sure if it's possible, since validators are a separate module, but I think it could be helpful to be able to specify single-field validators inside the fields object (as an option, in addition to the current syntax):  

    fields: {
        emailAddress: {
            type: 'string',
            validators: Validators.email
        }
    }   
For more lengthy object definitions it would make it simpler to be able to tell which fields have been validated and which haven't (particularly important during development to be able to make sure I haven't forgotten about one).

Just a thought.

**Comment by jagi** [comment]
Thanks for suggestion. It's definitely possible to do. It wouldn't be hard to create module for this without changing anything in the current code of the fields and validators modules. However, right now I want to focus on must have features, so let me postpone it for later :). But we will come back to it :)

**Comment by dovrosenberg** [comment]
Definitely low priority… if it bothers me too much, perhaps I’ll give a module a shot. ☺

The other approach would be if custom field types could be defined to automatically include validators.  Then I’d just define my field type as “email” or whatever and it would apply both the actual type (string) and the validator and be obvious when reading the schema what it all does

**Comment by jagi** [comment]
Good idea I would just modify this idea a little bit. We could define some validation groups. I don't know how API should look like but it could be something like this.

```js
fields: {
  email: {
    type: 'string',
    validateAs: 'email'
  }
}
```

So instead defining custom type, we add special `validateAs` keyword with the value of "validation group" / "validation context" (I don't know how to name it now). It could add a few validators like:
- required
- string
- email

Or something like this. Just a loose idea.

**Comment by jagi** [comment]
I came to conclusion that your idea is a "must have" :-). It will be possible to define validators just nezt to the fields. It's especially usefull when I introduce the nested fields definition. However both syntax will be valid.

**Comment by dovrosenberg** [comment]
Thanks.  I do like the validation group idea, too.  Particularly with the new nested syntax - I can see wanting to use the same set of 3-4 validators on many fields, so being able to apply as a group would be cleaner.

**Comment by jagi** [comment]
Ok, so I will implement both. However right now you can do it manually:

```js
var group = Validators.or([
  Validators.null(),
  Validators.and([
    Validators.string(),
    Validators.minLength(5)
  ])
]);
```

And you can use this group in as many places as you want.

```js
User = Astro.Class({
  name: 'User',
  collections: Users,
  fields: ['firstName', 'lastName'],
  validators: {
    firstName: group,
    lastName: group
  }
});
```

**Comment by dovrosenberg** [comment]
Excellent point.

**Comment by jagi** [comment]
Maybe I will add this example to the documentation under the section "reusing validators", because it can be handy for others.

**Comment by jagi** [comment]
Done in version 0.10.6. Now you can write:

```js
fields: {
    email: {
        type: 'string',
        validators: [
          Validators.required(),
          Validators.string(),
          Validators.email(),
        ]
    }
}  
```

**Comment by dovrosenberg** [comment]
Awesome.  Thanks!
