### ISSUE TITLE
getModified() return a Class instead of values

### ISSUE THREAD

**Issue by shadowRR** [jagi/meteor-astronomy#195]
Hey @jagi,

When i do a `getModified()` on a nested class (which is an array of objects), it doesn't return the raw values of each objects like i'm expecting, but instead, it return an array of class. And i can't really use the `raw()` method because i actually need the original values from my document

Ex: 
```
ParentClass = Astro.Class({
    name: 'parentclass',
    collection: ParentsClass,
    fields: {
        userId: {
            type: 'string',
            immutable: true
        },
        components: {
            type: 'array',
            nested: {
                name: 'ComponentsList',
                fields: {
                    'someField': {
                        type: 'string'
                    },
                    'someOtherField': {
                        type: 'string'
                    },
        }
    }
});
```
Saying that i've made change on the components array, by pushing an object in it.If i do a basic `getModified()`, i'll get a `components` field with a list of class and not just the values inside each of those.

Thanks

**Comment by jagi** [comment]
It's expected behavior. Maybe I could implement the `getRawModified()` method but you can do it by your self. You can always use the `raw()` method on each element of array. As I'm thinking about it now I think that there may be a need also for the `isModified(fieldName)` method. What do you think?

**Comment by shadowRR** [comment]
Well, since the point of `getModified()` was to obtain an object with all the values that have been modified, for me, it should return the same thing for all the nested fields. And i can't see why returning the class instead would be useful for ? (but it's maybe me...). Maybe we could have some options to ask to get either the class for nested class, or directly the object with the values like in the parent class ?

**Comment by jagi** [comment]
I don't understand the last paragraph you wrote.

**Comment by shadowRR** [comment]
Ok. What i meant was, having like a boolean options on the `getModified()` to say to the function to also get raw values for nested fields.

Right now, we can do :
`getModified(true)` to get the original values or,
`getModified(fieldName)` to get the modified value of a specific field or even,
`getModified(fieldName, true)` to have the original values of a specified field (not sure for this one).

We could add another one to be able to get the classes on nested fields if useful for some case, and by default get the direct values like in the parent class. I hope it's clearer now.

**Comment by jagi** [comment]
Oh I see. Tomorrow I will check what I can do about it and let you know.

**Comment by shadowRR** [comment]
Awesome, thanks ;).
