### ISSUE TITLE
.getModified() doesn't get transient fields that have been changed

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#196]
Hi,
I'm using the great transient fields feature to handle encryption in our app.
decrypted fields are transient, so they never get saved to the db, while encrypted fields are regular fields.
We encountered some unexpected behavior with the transient fields:
1. they are not included in .getModified() when they should. Is that on purpose?
2. for some reason, we couldn't figure out why, when a transient field is in a nested class, it loses it's value somehow on the way from the client to a meteor method.

Let me know if we're using transient fields in a way it wasn't designed for, and if you have any suggestions.
Thanks!

**Comment by jagi** [comment]
Yes I know about it. The problem with the `getModified()` method is that it uses quite different method to detect changes than it should. Each operation on a document registers modifier that caused a change and the `getModified()` method does not use it at all. If it goes about transient fields, modifications of them does not register any modifier but the `getModified()` method does not know about it. Fixing it would require rewriting entire method. I've already fixed it in 2.0 but it's now backward compatible. So sorry but there is no quick fix for it. You just have to wait for 2.0, which (I can promise) will be much more stable.

**Comment by jazzdragon** [comment]
ok, thanks.
When do you think you'll release 2.0?

**Comment by jagi** [comment]
I hope I will release it before Christmas :)

**Comment by soaresa** [comment]
Nice!

**Comment by talha-asad** [comment]
@jagi I am just wondering, do you expect the migration to be easy or is it going to be a bit of work?

Also i was wondering why are relations marked as experimental? any particular reason?

**Comment by jagi** [comment]
@talha-asad Migration shouldn't be very hard, however it can take a little bit of time depending on the project size. I will probably also create a package helping with migration, which would show which line should be updated, but we will see if I'm gonna have time for that.

If it goes about relations package. It is experimental in terms of API but it works. I want it to develop and change api a little bit in 2.0 and probably integrate it with the core package. I have a few ideas to make it easier to declare relations.
