### ISSUE TITLE
needsPlain doesn't seem to work

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#199]
Morning Jagi,
When creating a new type, needsPlain seems to not affect anything.
Even when I just return false from it, the plain method still runs.
Thanks!

**Comment by jagi** [comment]
The `needsPlain` method is executed when getting plain JavaScript values that are gonna be saved in a database. It's used in every method that modifies document `set()`, `push()` etc. In most cases you don't need to provide this function for types. In Astronomy it's used for converting astronomy documents into plain JavaScript values. Show me your type definition, so I will give you more information.
