### ISSUE TITLE
Use methods in events

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#200]
It would be cool if we could use methods inside of events. Is that possible? It would look like this:

````javascript
methods: {
    exampleEvent: function(){
        return Math.round(this.percent);
    },
events: {
    beforeInsert: {
        if(this.roundPercent){
            this.set(percent, this.exampleEvent());
        }
    }
}
````

OK, it's a weird example, but there are functions I find myself using multiple times in different events, and that I'd like to call from other places at other times, so it would be handy to be able to use the methods right inside the events.

**Comment by jagi** [comment]
It's actually works that way :) have you ever checked it? :) I'm closing this issue for now ;-)
