### ISSUE TITLE
Class methods synchronous on client?

### ISSUE THREAD

**Issue by purplecones** [jagi/meteor-astronomy#201]
I noticed that the methods I define on classes freeze my page while they are running. For example, I have a simple method on a User class that returns the total count of documents from another collection related to that user. The page freezes while that method is being executed.

Is there a way around this?

**Comment by jagi** [comment]
The problem is probably somewhere else. The count method from collection is very fast so it shouldn't block browser for a long time. It does not make a roundtrip to the server so the result should be instant. More over the count method is synchronous so it's not the fault of astronomy.

**Comment by jagi** [comment]
Show the code

**Comment by purplecones** [comment]
Here is a bare example of what I mean. The chart(amChart) freezes for a second while the list is being generated. The user list is a table of users, and for each user, methods are called to get the a total count of related documents to a different collection and sum of a specific field for all those documents.

![Image](http://g.recordit.co/yUDtw8891J.gif)

here are the two methods being called for each user:
```
    // returns the total amount user has invested
    getInvestmentsTotal() {
      return alasql(`SELECT SUM(investmentAmount) as investmentTotal FROM ? WHERE userId = '${this._id}'`, [Investments])[0].investmentTotal;
    },

    // returns the total amount user has invested
    getInvestmentsCount() {
      return alasql(`SELECT COUNT(*) as totalCount FROM ? WHERE userId = '${this._id}'`, [Investments])[0].totalCount;
    },
```
I'm using alasql but I was able to replicate this by using normal mongodb queries.

Here is the jsx code for the table rows
```
return (
          <tr key={index} onClick={this.goToUserDetails.bind(this, user._id)} style={{cursor: 'pointer'}}>
            <td>{user.profile.first_name}</td>
            <td>{user.profile.last_name}</td>
            <td>{user.emails[0].address}</td>
            <td>{format.num(user.getInvestmentsCount())}</td>
            <td>{format.$(user.getInvestmentsTotal())}</td>
          </tr>
        );
```

**Comment by jagi** [comment]
For me it looks like it's waiting for subscriptions to be ready. What are you using for managing subscriptions? Are you sure that all documents have been loaded from the server when displaying template?

I don't know how is the `alasql` method working internally but if it's loading document on the fly then it may need time to fetch documents from the server.

**Comment by purplecones** [comment]
I redesigned my React app structure so that there only top level component fetches all the required data instead of making additional mongodb queries in downstream components. Once top level component has received all data, the data is passed down as props down to all components.

**Comment by jagi** [comment]
Ok good
