### ISSUE TITLE
pulling then pushing the same value causing inconsistent state

### ISSUE THREAD

**Issue by saimeunt** [jagi/meteor-astronomy#202]
Given a document fetched from the database and having an array field property set to a single element value, pulling then pushing that same value results in erasing the value from the field.

Minimal reproduction :

```
Tests = new Mongo.Collection('tests');

Test = Astro.Class({
  name: 'Test',
  collection: Tests,
  fields: {
    array: {
      type: 'array',
      default() {
        return [];
      },
    },
  },
});

Meteor.startup(() => {
  Tests.remove({});
  //
  let test = new Test();
  test.push('array', 'value');
  test.save();
  test = Tests.findOne();
  // actual: ['value'], expected: ['value']
  console.log(test.get('array'));
  test.pull('array', 'value');
  test.push('array', 'value');
  // actual: [], expected: ['value']
  console.log(test.get('array'));
});
```

**Comment by jagi** [comment]
Yes I know about this problem. It's very hard to fix it in the current version. I'm currently working on 2.0 which won't have this problem. What you have to do right now is saving a document between operations, which may not be the best solution but it's for now the only that works.

**Comment by saimeunt** [comment]
OK, I already figured out another path to avoid this bug, keep up the good work for Astronomy@2.0 !

**Comment by jagi** [comment]
Ok good to hear. Thanks :)
