### ISSUE TITLE
Question on modelling objects with dynamic keys

### ISSUE THREAD

**Issue by JesperWe** [jagi/meteor-astronomy#208]
The actual question is at the end of this post, but first some context:
I am in the process of trying to improve the design of the data model for a rather complex data-set.
The current model uses nested array fields to model two levels of one-to-many relationships, like so:

	"model": {
		"_id": "EpZmP44ri9vskRG7v",
		"units": [
			{
				"_id" : "rck2SLcnxQCMjM3nu",
				"events" : [
					{
						"_id" : "T7qTSF3Gg8tCWxpGv",
						"model" : "EpZmP44ri9vskRG7v",
						"unit" : "rck2SLcnxQCMjM3nu",
						//...
					},
					//...more events
				]
			},
			//...more units
		]
	}

The problem with this is there is way too much looping around the arrays when I need to find a certain `Unit` or `Event` by `_id`.

Ideally I would like to use the ES6 `Map` datatype for Units/Events, but since that is not possible at the moment I want to try using objects with `_id` as key.
The example above would become:

	"model": {
		"_id": "EpZmP44ri9vskRG7v",
		"units": {
			"rck2SLcnxQCMjM3nu": {
				"events" : {
					"T7qTSF3Gg8tCWxpGv": {
						"model" : "EpZmP44ri9vskRG7v",
						"unit" : "rck2SLcnxQCMjM3nu",
						//...
					},
					//...more events
				}
			},
			//...more units
		}
	}

This way I can find Events straight away by `_id`.

My current Astronomy setup uses nested classes for `Unit` and `Event`, like so:

	Model = Astro.Class( {
		name: 'Model',
		collection: Models,
		fields: {
			_id: 'string',
			units: {
				type: 'array',
				nested: 'Unit',
				default: function() {
					return [];
				}
			},
			//...
		}
	} );

	Unit = Astro.Class( {
		name: 'Unit',
		fields: {
			_id: 'string',
			events: {
				type: 'array',
				nested: 'Event',
				default: function() {
					return [];
				}
			},
		},
		//...
	} );

This pattern does not work for my new data model, because I do not know the keys of the fields of the nested objects (The keys are `_id`'s).
My question: Is it possible to model my new structure in Astronomy? Specifically: If I have a field of type `'object'` where I don't know the keys beforehand, can I have  Astronomy instances as the values of the entries? My Astronomy `Event` class has a lot of intelligence in it, and I would like to work with Astronomy instances, not plain JS objects.

**Comment by jagi** [comment]
I don't understand your question. I don't see here one-to-many relation. Which class is one and which is many? One-to-many relation means that you are storing the `one` and `many` side in two different collections. In your description you are talking about three classes. The common MongoDB pattern for relations is storing array of ids or storing the `_id` of the `one` document in some field in the `many` document.

```js
post._id;
comment._id;
post.commentsIds = ['EpZmP44ri9vskRG7v', 'rck2SLcnxQCMjM3nu', 'rck2SLcnxQCMjM3nu'];
```

or

```js
post._id;
comment._id;
comment.postId;
post.getComments(); => Comments.find({postId: post._id});
```

**Comment by JesperWe** [comment]
OK, sorry about that, I will try to explain better:

Each `Model` has many `Units`.
Each `Unit` has many `Events`.

I want to store the entire structure as one Model document in a single collection (as outlined in the OP). Separating them (as the Posts and Comments in your example) makes publish/subscribe management too complex in this case (I have tens of thousands of Models, need to manage subscriptions very actively to avoid performance issues). So I have only one collection (`Models`). 

Right now, using arrays, Astronomy allows me to make a beautiful object model, with all the characteristics of the data modeled **in code** using validators and methods. But now, instead of an array, I want to use an object with the _id as key, to avoid looping in the arrays to find the right object. But still want use Astronomy to define the objects that are the values inside this object.

Another way to try to illustrate my desired object structure is with the objects classes annotated:

	Astro.class Model {
		units: {
			'<random.id>': Astro.class Unit {
				events: {
					'<random.id>': Astro.class Event {},
					'<random.id>': Astro.class Event {},
					'<random.id>': Astro.class Event {},
					...
				}
			},
			'<random.id>': Astro.class Unit {},
			'<random.id>': Astro.class Unit {},
			...
		}
	}

Obviously I can model this in Astronomy as just type: 'object' and manage the underlying object as any JS object, but I would prefer to work with Astronomy class instances for Units and Events. So I can do for example:

	var model = Model.find({_id: '...' });
	var unit = model.units[unitId];
	var event = unit.events[eventId];

...where unit and event are instances of my `Unit` and `Event` Astronomy classes.

**Comment by jagi** [comment]
Oh I see, now I understand. Hmm it's not possible in Astronomy 1.x. I've already received a few similar requests for such feature. I understand the reason and I think it may be a good idea to implement it in 2.0. However, as I think about it it would not be so simple to do.

So for now you have to do it by your self. However, if you want to cast nested object to astronomy class you can do it easily even if it's stored as a plain JavaScript object.

```js
var unit = new Unit(model[unitId]);
```

Of course it's not perfect workaround but it would work.

**Comment by minfawang** [comment]
Hi @jagi I encountered almost the same situation as mentioned above. Do you think the current implementation of 2.0 will relieve the issue somehow?

**Comment by jagi** [comment]
@minfawang it won't rather be possible to have dynamic keys. You have to use the `Object` type and you can put there whatever you want but you won't be able to put the nested classes. So you will have to manage data in it by yourself.
