### ISSUE TITLE
getting all validation errors

### ISSUE THREAD

**Issue by willoughby** [jagi/meteor-astronomy#209]
Calling getValidationErrors() gives me one validation error at a time if my model has multiple problems.

**Comment by shadowRR** [comment]
Are you using the `class.validate(false)` with the `false` options to tell the validation not to stop after the first error ?

**Comment by jagi** [comment]
@willoughby make sure that you did what @shadowRR wrote. There is probably a source of your problem.

**Comment by willoughby** [comment]
Thanks
