### ISSUE TITLE
Problem with collections using ObjectID

### ISSUE THREAD

**Issue by space-alien** [jagi/meteor-astronomy#210]
I'm experiencing an error when using Astronomy if a collection contains documents that have ObjectIds instead of simple string IDs:

`Exception in queued task: Error: transformed document can't have different _id`

I noticed this when inserting a document via the meteor mongo console (which would generate an ObjectId by default).

Is Astronomy compatible with ObjectIds?

**Comment by jagi** [comment]
Yes it seems like it does not work with ObjectIDs. The `_id` field is defined as string. So I will probably have to change it to no type as it can be sometimes ID and sometimes string. MDG decided to use strings instead ObjectIDs but I don't remember why. But maybe you shouldn't use ObjectIDs if you don't have to. However I will prepare fix for that and just change type of the `_id` field.

**Comment by jagi** [comment]
Fixed in 1.2.5
