### ISSUE TITLE
Generating Validation Errors Reveiw

### ISSUE THREAD

**Issue by shwaydogg** [jagi/meteor-astronomy#211]
Originally I thought I'd come across bugs with the "generating error messages" process, but upon writing the example code below, I realized the implementation was just different from what I expected.  The validation process has been separated from error message generation, as the code below makes clear.  From an API perspective I did not expect this, but there may be many valid reasons to do so.  

Foremost I think the docs could be updated to make some of this clearer, but I wanted to touch base before making a pull request in case any other changes make sense or my understanding is off.  In addition the example code and discussion could serve as interim publicly accessible resources before the docs are updated.

Possible Actions:

1. Clear up the docs, to describe the need for `validate(false)` to be invoked before you will get all validation errors from `getValidationErrors()` or helper methods. 

2.  `validate(false)` was originally `validateAll()` this seemed semantically clearer.  Perhaps it makes sense to provide an abstraction like `validateAll()` that calls `validate(false)` **?**

3. Have `getValidationErrors()` trigger all fields be validated before it generates error messges.  I'm not aware of a situation when you wouldn't want it to provide _all_ the validation errors. **?**

```
Contacts = new Mongo.Collection('contacts');
Contact = Astro.Class({
  name: 'Contact',
  collection: Contacts,
  fields: {
    first: {
      type: 'string',
      validator: Validators.minLength(3, 'The first name is too short!')
    },
    last: {
      type: 'string',
      validator: Validators.minLength(3, 'The last name is too short!')
    }
  }
});

c = new Contact();
c.set('first', 'g');
c.set('last', 'g');
console.log('errors:', c.getValidationErrors()); 
    //  ----> {}  

console.log('validate:', c.validate());
console.log('hasValidationErrors:', c.hasValidationErrors());
console.log('errors:', c.getValidationErrors());
  //  ----> {first: "The last name is too short!"}

console.log('validate:', c.validate(false));
console.log('errors:', c.getValidationErrors());
  //  ----> {first: "The first name is too short!", last: "The last name is too short!"}

/* The above output also correspond with what will be shown with the helper 
methods for "Displaying Error Messages":  http://astronomy.jagi.io/displaying-error-messages.   */
```

**Comment by jagi** [comment]
1. (3) Yes maybe I could clarify it in the docs that you have to call the `validate` method before getting errors. Of course I could execute validation on call of such methods like `getValidationErrors` or `getValidationError` but is it as hard to just call it? Moreover, there are several use cases when it's not necessary. One example is usage of such method in a template. It would execute validation for empty form which is not expected until you really want it to be called (field value change, save button clicked).

2. Yes probably it's more obvious what method does if it's names `validateAll` then `validate`. I will probably add this alias.

**Comment by shadowRR** [comment]
I'll agree with @jagi on the `getValidationErrors` request. I do have quite a few case where i don't want this one to trigger the validation for all fields.

**Comment by shwaydogg** [comment]
Thanks for the responses!  Sounds like we all agree add the `validateAll()` alias or similar and make usage clearer in docs :)  I'll take a crack at them when I get a chance.

**Comment by jagi** [comment]
Yep, I will bring the `validateAll` method back.
