### ISSUE TITLE
`format` method on custom types

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#213]
I think this will be very useful. The idea is to create a type that whenever retrieved from the DB it is processed by a method.
For example, if creating a 'price' type, it might look like this:
``` javascript
Astro.createType({
  name: 'price',
  constructor: function NumberField() {
    Astro.BaseField.apply(this, arguments);
  },
  needsCast: function(value) {
    return !_.isNumber(value);
  },
  cast: function(value) {
    return Number(value);
  }
  format: function(value) {
    return '$' + value.toFixed(2)
  }
});
```

So here I'd like prices to be numbers in the DB, but converted to formatted strings whenever I fetch them.

**Comment by jazzdragon** [comment]
Also, it would be very useful if there was a .getType() method on the keys of a class, so we can treat them differently.

**Comment by jagi** [comment]
This subject was already discussed. It's not a job for the model layer. It's a job for the view layer. Eventually you can add extra methods to the model like `getFormattedPrice` that would format the price. We can't store formatted a price in a document.

**Comment by jazzdragon** [comment]
ok, I guess that could be easier to achieve using something like `.getType()`.
Do you think that would make sense to implement?

**Comment by jagi** [comment]
Hmm could you provide some example? I don't quite understand what would the `getType()` method do.

**Comment by jazzdragon** [comment]
Yeah, so let's say I create a custom type, say `price`, and in the view layer I want to target all the fields in the instance with that type, I can do so with `instance[key].getType()`

**Comment by jagi** [comment]
Let me provide an example so you can confirm if I understand you correctly.

```js
var doc = Docs.findOne();
doc.price.getFormatted(); // doc.price is of the custom Price type
```

**Comment by jazzdragon** [comment]
No, let's say I have:
```javascript
var Item = new Astronomy.Class({
  name: 'item',
  fields: {
    name: 'string',
    description: 'string',
    price: 'price',
    priceAfterDiscount: 'price'
  }
})
```

Then, in my view, I would have:
```javascript
item = Items.findOne();
formattedItem = _.map(item, function(value, key, item){
  if(item[key].getType === 'price') {
    return formatPrice(value)
  }
  return value
})
```

**Comment by jagi** [comment]
Oh I see. You can do that right now.

```js
var item = Items.findOne();
var Class = item.constructor;
var formattedItem = _.map(item, function(value, key) {
  if (Class.getField(key).type === 'price') {
    return formatPrice(value);
  }
  return value;
});
```

However I don't think it's a good idea to create another copy of a document just to format prices. It won't be very efficient if you have many documents. It's just better to know what fields are of what type and use some helper or method.

**Comment by jazzdragon** [comment]
Perfect, thank you.
