### ISSUE TITLE
Possible bug in pull() method

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#216]
`pull` is not working for me in a particular instance. I have the following class:

```
Reels = new Mongo.Collection('reels');

Reel = Astro.Class({
  name: 'Reel',
  collection: Reels,
  fields: {
    name: 'string',
    tracks: {
      type: 'array',
      default() {
        return []
      }
    },
    artistId: 'string',
    password: 'string',
    createdAt: 'date'
  }
});
```

When I try this in the Meteor shell, (or in code) nothing happens:

```
r = Reels.findOne(userId); //successful
r.pull('tracks', {uid: 'aQTRzcj9gjinNDBMi'});
r.save();
```

Am I doing something wrong?

**Comment by jagi** [comment]
Probably the problem is that you are passing only id and you have to pass entire object that you want to pull.

**Comment by ffxsam** [comment]
You do? But I just want to pull based on a single field. The docs seem to indicate this is possible:

http://astronomy.jagi.io/pull

I'll just use the non-Astronomy way, which works:

    Reels.update(reelId, {$pull: {tracks: {uid: trackId}}});

**Comment by jagi** [comment]
It will be possible in Astronomy 2.0, right now it has to work the way it is :)

**Comment by ffxsam** [comment]
Ok. Thanks for all the hard work!

**Comment by jagi** [comment]
No problem :)
