### ISSUE TITLE
Question: does astronomy relations enforce reference integrity?

### ISSUE THREAD

**Issue by lsunsi** [jagi/meteor-astronomy#218]
Pretty self explanatory question.

Also, sorry for the questions, some parts of the doc are kind of incomplete.
Awesome package man.

**Comment by jagi** [comment]
What do you mean?

**Comment by lsunsi** [comment]
I mean, if I try to add some _id which isn't present in the related collection, will it work or will it throw an error?

**Comment by jagi** [comment]
It will work. It doesn't make such checks.

**Comment by lsunsi** [comment]
Great, thanks man!
