### ISSUE TITLE
Question: why does the schema creators use string instead of types?

### ISSUE THREAD

**Issue by lsunsi** [jagi/meteor-astronomy#219]
'string', 'array', 'object' and 'number' all have they javascript type counterparts.

It's not better or worse (actually it kind of looks better, maybe).
I'm just curious on why use strings, that's all.

**Comment by jagi** [comment]
To be honest I don't remember what was the reason to choose strings instead constructors. I was playing with both in beta version. You can have custom type which may not have constructor. Moreover there was also an idea to introduce build process using Meteor build process that would take JSON schema and create all classes during the build process. And as you may know you can't use references in JSON (only plain types). So I think the last one was the main reason.

**Comment by lsunsi** [comment]
Thanks for the answer man!
cool trivia
