### ISSUE TITLE
Version 1.2.7 breaks editabletext context=_original

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#223]
I had astronomy and editable text working nicely together (I would simply put context=_original as an option in editable text), but with the 1.2.7 update that breaks and I get a match error (explained here: https://github.com/JackAdams/meteor-editable-text/issues/43). Any idea why this broke with the last release?

**Comment by jagi** [comment]
You shouldn't access private properties of Astronomy. The `_original` property was one of the causes of performance problem. I've decided to remove it. But for backward compatibility it's computed on the fly when accessed. You would have to show me some example when it does not work. Maybe there is a better way then accessing the `_original` property.

**Comment by JulianKingman** [comment]
I see. The problem with editable text is that it expects a plain object, so I have to choose to use a plain object and sacrifice methods (via .get()), or not use editable text, neither of which I particularly like. I think I may know a way around it, and I'm working with Jack on that, but in the meantime, the _original property isn't working in the editable text template, for example ````{{> editableText collection=example field=title context=_original}}````, which I would guess would be because it becomes available after editable text has called for it.

**Comment by jagi** [comment]
Have you been trying to use `doc.raw()` instead of `doc._original`?

**Comment by JulianKingman** [comment]
I haven't been. How would that work in the context parameter? I still wouldn't have the methods, right?

**Comment by jagi** [comment]
The `doc.raw()` method returns pure data, without methods etc.
So the problem is that the `_original` property was changed to Astronomy object, right? So I've probably missed it. I will try to make a fix.

**Comment by jagi** [comment]
I've improved backward compatibility in 1.2.8. Please check it out and let me know if it works.

**Comment by JulianKingman** [comment]
Yep, that did it, thanks!
