### ISSUE TITLE
Version 1.27 Error TypeError: originalDoc is undefined

### ISSUE THREAD

**Issue by stoked74** [jagi/meteor-astronomy#224]
After upgrading to 1.2.7 I started to receive the error "originalDoc is undefined". It only appears to happen when using a new object instance. The first object inserts properly into the array, but the error appears when I try and add a second object to the array. The below code worked fine 1.2.6. 

The stack trace and code that's causing the error is below.

Code:

```javascript
e.preventDefault();

    var iProject = template.data.iProject;

    var empId = $(e.target).data("value");
    var empName = $(e.target).data("name");
    var roleId = $('#roleId-sel').val();

    var found = _.find(iProject.personnel, function(obj) {
      return obj.userId == empId && obj.roleId == roleId;
    });

    if (!found) {
      if (empId && roleId) {
        iProject.push('personnel', {
          'userId': empId,
          'name': empName,
          'roleId': roleId,
          'createdAt': new Date(),
          'createdBy': Meteor.userId()
        });

        // calling save here addresses a known bug in astronomy. 
        // https://github.com/jagi/meteor-astronomy/issues/202
        iProject.save();

        //update the div containing the assigned personnel
        template.assignedPersonnel.set(iProject.personnel);

      }

    }
```
Stacktrace:

12:02:47.200 TypeError: originalDoc is undefined
proto.getModified/<() jagi_astronomy.js:4079
_.forEach() underscore.js:157
proto.getModified() jagi_astronomy.js:4073
.methods.setModificationDate() jagi_astronomy-timestamp-behavior.js:99
events.beforeUpdate() jagi_astronomy-timestamp-behavior.js:45
.emit/<() jagi_astronomy.js:228
every() self-hosted:168
_.all() underscore.js:263
.emit() jagi_astronomy.js:226
classMethods.emitEvent() jagi_astronomy.js:1512
prototypeMethods.save() jagi_astronomy.js:924
["click #personnel-searchgroup .sunpro-personnel"]() project-edit.js:304
Template.prototype.events/eventMap2[k]</</<() blaze.js:3697
Template._withTemplateInstanceFunc() blaze.js:3671
Template.prototype.events/eventMap2[k]</<() blaze.js:3696
attached_eventMaps/</</</<() blaze.js:2557
Blaze._withCurrentView() blaze.js:2211
attached_eventMaps/</</<() blaze.js:2556
HandlerRec/this.delegatedHandler</<() blaze.js:833
jQuery.event.dispatch() jquery.js:4690
jQuery.event.add/elemData.handle() jquery.js:4359
1 jagi_astronomy.js:4079:9

**Comment by jagi** [comment]
Please try out Astronomy 1.2.8. If it's still not working then please create a reproduction repository.
