### ISSUE TITLE
Q: What is the best way to save createdBy and updatedBy fields in the documents

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#227]
One option is to set it during creation/modification manually. But is there a nice way where astronomy handles it on its own?

Meteor.userId can't be used as a default value, if I want to save from the client itself. It can not be used in publish functions and hence causes errors.
Can 'behaviors' be used? @jagi . Or any other solution?

**Comment by jagi** [comment]
I would do something like this. Should work.

```js
events: beforeInsert() {
  this.createdBy = Meteor.userId()
}
```

```js
Meteor.methods({
  'saveDoc': function(doc) {
    doc.save();
  }
});

Meteor.call('saveDoc', new Doc());
```

**Comment by s7dhansh** [comment]
Yes I saw that in one of the posts by you earlier. Which is why I asked if there was a way to do it 'from the client' i.e. while using normal collection.save() in the client itself. :)
I guess not, I will resort to this method then.

Thank you!

PS: Was wondering, is there any way to have this.userId as it is there in collection2/simple-schema, available to all schema definitions, always, irrespective of client/server/publish functions.

**Comment by jagi** [comment]
In Astronomy 2.0 you will be able to use `Meteor.userId()` without creating Meteor method. So it worth upgrading when it's ready :)

I haven't been planning to introduce such feature because `this` context may vary depending on the situation. And you may want to use your custom context in method, event or whatever. So it's just better to use Meteor.userId(). And if you want to call it from the client without Meteor method then you have to wait for Astronomy 2.0 :)

**Comment by nicooprat** [comment]
Also don't forget to add the `createdBy` field to the schema, like I just did :) As a side note, Astronomy could throw an error to say that we're trying to add a field that hasn't been defined in the schema...

**Comment by s7dhansh** [comment]
@nicooprat you can use my behavior now: https://github.com/settlin/meteor-astronomy-meta-behavior

**Comment by nicooprat** [comment]
@s7dhansh Perfect, thanks !

**Comment by nicooprat** [comment]
@jagi It would be great to have a place to list all the community behaviors! Maybe in the wiki?

**Comment by keremciu** [comment]
@nicooprat @s7dhansh 's behavior is so since. but if you'd like to use only createdBy and updatedBy fields you can my behavior https://github.com/keremciu/meteor-astronomy-userstamp-behavior

**Comment by lukejagodzinski** [comment]
@nicooprat yes I'm going to create such section in the documentation
