### ISSUE TITLE
How to sort by array length or document method?

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#228]
I have a method that returns the length of an array. It seems silly to create a separate field to store the value, how could I go about sorting the collection? It could look something like this:
````javascript
//option 1
collection.find({}, {$sort: {array.length: 1}});
//or
collection.find({}, {$sort: {documentMethod: 1}});

//option 2
collection.find({}).astroSort({documentMethod: 1});

//option 3
collection.find({}).sort(function(a,b){
    if(a.documentMethod < b.documentMethod){
      return 1;
   } else {
      return -1;
});
````
Any ideas?

**Comment by jagi** [comment]
I think it shouldn't be asked here as it's more Meteor/MongoDB related question. However I can say that it's probably not possible to do easily. In MongoDB you would have to use [aggregate](http://stackoverflow.com/questions/9040161/mongo-order-by-length-of-array) function which is not available in Meteor

```
findAndModify, aggregate functions, and map/reduce aren't supported.
```

In Useful.io we've experienced lately a problem of sorting and filtering using the related field (from the another collection). We've implemented a way of [computing relations on the fly](https://github.com/usefulio/meteor-astronomy-relations/blob/master/lib/module/define_relation.js). Maybe you could use that approach to compute the `size` property and sort by it. In my opinion it would be the best approach. Of course you could also use your custom sorting after fetching document.

**Comment by JulianKingman** [comment]
Thanks for the tip, I'll check out your solution for now and close this issue.

**Comment by jagi** [comment]
Ok no problem
