### ISSUE TITLE
Sorting on transient fields not working?

### ISSUE THREAD

**Issue by Broham** [jagi/meteor-astronomy#229]
I have a collection that I would like to setup case insensitive sorting on.  My first thought was to create a [transient field](http://astronomy.jagi.io/transient-fields) on the field that I wanted to sort by like so:

```
Document = Astro.Class
  name: 'Document'
  collection: Documents
  fields:
    title:
      type: 'string'
      validator: [
        Validators.required()
        Validators.minLength(5, 'The title must be at least 5 characters')
      ]
    lowerTitle: 
      type: 'string'
      transient: true
  events:
    afterInit: ->
      @set 'lowerTitle', @title.toLowerCase()
```

But when I query the collection and pass in a sort parameter the records are returned in the same (seemingly random) order every time.  

I am attempting to query the sorted records from my console like so: `Documents.find({},{sort: {lowerTitle: 1}}).fetch()` which returns the seemingly random results.  
If I query the non-transient field like so: `Documents.find({},{sort: {title: 1}}).fetch()` then it works fine

Does anyone have any idea why this would be happening?  Suggestions on how to get sorting working on the transient field?

**Comment by jagi** [comment]
As the name suggest the `transient` field is not stored in the collection so you can't sort by it. If you want to sort by a given field then just remove the `transient: true`.

**Comment by Broham** [comment]
@jagi - That's how I had it setup originally and the sorting still didn't work.  Is it possible to sort on a field that is set in the `afterInit` event even when it isn't marked `transient: true`?

**Comment by jagi** [comment]
Sorting only works on a fields/values that are saved in collection. You can't just change field's value without saving it and sort by this field.

Actually, you could do that but it's not standard behavior. It required modifying the way how MiniMongo stores data but it's to difficult to describe it here.

You're just doing something wrong if it goes about application logic.
