### ISSUE TITLE
Find by nested field resulting in weird behavior

### ISSUE THREAD

**Issue by lsunsi** [jagi/meteor-astronomy#230]
I'm having some weird behavior finding documents by a nested field in Mongo.
I took a screenshot to show what the weird behavior is.
![screen shot 2015-12-20 at 4 10 25 pm](https://cloud.githubusercontent.com/assets/6089867/11919249/56fe65e6-a734-11e5-89aa-113a519c73be.png)
The second find shows that the first one should find something, right?

**Comment by jagi** [comment]
It's not something related with Astronomy. However, after looking the output, yes it should return count 1 but you may have problem in some other place. If you think that it's something related with Astronomy then you have to create reproduction repository to allow me checking it out. Output is not enough.

**Comment by lsunsi** [comment]
@jagi Yeah, I thought it could be unrelated, but being honest if it isn't something related to astronomy I have no idea what it could be. Do you have some guess? That is some weird behavior

**Comment by jagi** [comment]
As I said, I can't tell anything from this output. You have to create reproduction repository https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by lsunsi** [comment]
@jagi  fair enough haha thanks man

**Comment by jagi** [comment]
I've tried creating a simple reproduction with one document you've mentioned and it worked. So problem has to be on your side. Maybe post your class schema here.

**Comment by lsunsi** [comment]
StudentProfile = Astro.Class({
     name: 'StudentProfile',
     fields: {
       name: {
         type: 'string',
         validator: Validators.UserName(),
       },
       cpf: {
         type: 'string',
         validator: Validators.CPF(),
       },
       enrollment: {
         type: 'string',
         validator: Validators.UserStudentEnrollment(),
        },
        school: {
         type: 'string',
         validator: Validators.Reference(),
       },
     },
      });

      User = Astro.Class({
        name: 'User',
        collection: Meteor.users,
        fields: {
          // meteor controlled fields
         emails: 'array',
          services: 'object',
          preferences: 'object',
          createdAt: 'string',
          profile: 'object',
   
       email: {
         type: 'string',
         validator: Validators.Email(),
       },
       roles: {
         type: 'array',
         validator: Validators.and([Validators.SomeOf(UserRoles.all('keys')), Validators.length(1)]),
       },
       adminProfile: {
         type: 'object',
         nested: 'AdminProfile',
         validator: Validators.UserProfiles('admin'),
         optional: true,
       },
       schoolProfile: {
         type: 'object',
         nested: 'SchoolProfile',
         validator: Validators.UserProfiles('school'),
       },
       teacherProfile: {
         type: 'object',
         nested: 'TeacherProfile',
         validator: Validators.UserProfiles('teacher'),
        },
        studentProfile: {
         type: 'object',
         nested: 'StudentProfile',
         validator: Validators.UserProfiles('student'),
       },
     },
     });

**Comment by lsunsi** [comment]
@jagi Thanks for the interest and help man! Just posted the class definition. The indentation might have turned out a little bad, but it's all githubs fault haha

**Comment by lsunsi** [comment]
and that's what a single 'student' document looks like, including the 'studentProfile.school' field.
and again, thanks for even taking a look @jagi. I'm sure you didn't need to
```
{ _modifiers: {},
  role: [Function],
  name: [Function],
  _errors: 
   { _values: {},
     _size: 0,
     _sizeDep: { _dependentsById: {} },
     _entriesDep: { _dependentsById: {} },
     _keysDep: { _dependentsById: {} },
     _valuesDep: { _dependentsById: {} },
     _keysDeps: {},
     _valuesDeps: {} },
  _id: 'LeiBSNyYdQZTSwufd',
  emails: 
   [ { address: 'felipe@aluno.com',
       verified: false } ],
  services: {},
  preferences: null,
  createdAt: 'Sun Dec 20 2015 15:42:39 GMT-0200 (BRST)',
  profile: null,
  email: 'felipe@aluno.com',
  roles: [ 'student' ],
  adminProfile: null,
  schoolProfile: null,
  teacherProfile: null,
  studentProfile: 
   { _modifiers: { '$set': [Object] },
     _errors: 
      { _values: {},
        _size: 0,
        _sizeDep: [Object],
        _entriesDep: [Object],
        _keysDep: [Object],
        _valuesDep: [Object],
        _keysDeps: {},
        _valuesDeps: {} },
     name: 'Felipe',
     cpf: '12312312323',
     enrollment: '123',
     school: 'MNFR3Dy4gXg89JBCx',
     _isNew: true },
  _isNew: false }
```

**Comment by jagi** [comment]
1. I see that you have some modifiers in the `studentProfile`: `_modifiers: { '$set': [Object] }`. Could you log what object is inside it?
2. And is this object what you get after `Meteor.users.findOne(/* ... */)`?
3. Are you fetching document on the client or server?
4. Are you sure that you are subscribed to all fields of the user if you make this find on the client?

**Comment by lsunsi** [comment]
``` 
_modifiers: 
   { '$set': 
      { name: 'Felipe',
        cpf: '12312312323',
        enrollment: '123',
        school: 'MNFR3Dy4gXg89JBCx' } }
```

1. See above.
2. Yeah, exactly.
3. I'm fetching on the server. When I had this problem I started using the shell to make the tests.
4. No subscriptions since I'm running on the server.

**Comment by jagi** [comment]
I've just replicated your example with data and it works. So you have some bug in your code.

**Comment by lsunsi** [comment]
@jagi yeah, I can't figure out what it is. anyway, thanks for trying to help man.

**Comment by lsunsi** [comment]
@jagi Quick updated: the problem was indeed with my code, but it wasn't easy to debug. I weird behavior was apparently being caused by me setting properties directly using Mongo.update instead of using the astronomy save API.

**Comment by jagi** [comment]
Ok I see. It's strange anyway but that's good that you solved it.

**Comment by lsunsi** [comment]
@jagi yeah agreed. thanks man. (: and sorry for the lots of questions I'm asking this past week. I'm just super excited about your package and trying to learn more and more haha
