### ISSUE TITLE
Validator on nested fields: how to check top-level document fields?

### ISSUE THREAD

**Issue by lsunsi** [jagi/meteor-astronomy#231]
That's a pretty simple one.
The context in a validator is the document the validator is in. That means in a nested class, the context is the nested document. What if I want to get a field from the top-level document?

For example, I have a profile field that has to be validated based on user roles. How can I achieve that?

**Comment by jagi** [comment]
Yes it's a problem right now. There is no easy way of accessing parent document from the validator. That's why I've totally redesigned validators in 2.0. You have to perform validation check on your own in your situation.
