### ISSUE TITLE
Can't use "_id" as a field name in a nested Class

### ISSUE THREAD

**Issue by matthieu60** [jagi/meteor-astronomy#232]
Reproduction repo : https://github.com/matthieu60/astro-bug

Steps:
1. Define a class with an array, the nested class containing a field named "_id"
2. Create an instance of it, fill the array with at least one element
3. Save
4. Modify, try to save again → error, save fails

The error is "Uncaught TypeError: Cannot read property 'findOne' of undefined" in Chrome.

**Comment by jagi** [comment]
Yes in deed there is a bug. I will fix it.

**Comment by jagi** [comment]
Fixed in 1.2.9

**Comment by matthieu60** [comment]
Thanks ! It works perfectly now
