### ISSUE TITLE
Astronomy and FS collection

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#237]
Is anyone using Astronomy with ```FS.collection``` collections?
I am interested in hearing experiences or a boilerplate code.

**Comment by jagi** [comment]
As Astronomy 1.0 does not support allow/deny rules it may not be a perfect idea to use Astronomy with FS.Collection collections, especially if it goes about validation. However if you only want to have some extra methods it should work without the problem. But I would also like hear some feedback from people that used it together.

**Comment by talha-asad** [comment]
So i was trying to model an FS collection in Astronomy and kept getting ```FSCampaignMediaCollection isn't an instance of Meteor.Collection```

This is what i was trying to do:

```js
FSCampaignMediaCollection = new FS.Collection("campaign_media", {
  stores: [
    new FS.Store.FileSystem("campaign_media")
  ]
});

FSCampaignMedia = Astro.Class({
  name: 'FSCampaignMedia',
  collection: FSCampaignMediaCollection,
  fields: {
    _id: 'string',
    original: 'date',
    owner: {
      type: 'array',
      default: function() { return []; }
    },
    uploadedAt: 'date',
    copies: {
      type: 'object',
      nested: {
        name: 'FSCampaignMediaCopies',
        fields: {
          campaign_media: {
            type: 'object',
            default: function() { return {}; }
          }
        }
      },
      default: function() { return {}; }
    }
  }
});
```

Is there a hacky way to get the original Meteor.Collection object from an FS collection object? Or maybe have astronomy recognize FS Collection object as it is pretty much the same as the original Meteor Collection object.

**Comment by jagi** [comment]
Hmm ok so FS Collection is probably using it's own transform function which may mean that it's not possible to use FS.Collection and Astronomy on the same collection. This should not be a problem with Astronomy 2.0 as it's not messing with the transform method on the collection but doing its own transformation. I will be writing more about it in documentation for Astronomy 2.0 (which does not exist yet)

**Comment by talha-asad** [comment]
Okay makes sense. Hoping you release it soon ;) :+1:

**Comment by jagi** [comment]
Closing this issue for now.
