### ISSUE TITLE
What do you use for generating your documentation?

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#238]

**Comment by jagi** [comment]
Hey, I'm not using any tool to generate documentation. In fact I should use some tool to document API. Right now it's more like description of the package.

**Comment by talha-asad** [comment]
I have some edits for the documentation:

http://astronomy.jagi.io/writing-behaviors
```We will discuss each property in details.``` -> ```We will discuss each property in detail.```

http://astronomy.jagi.io/custom-types
```However, in most cases you will have only to provide cast and plain methods``` -> ```However, in most cases you would only have to provide cast and plain methods```

**Comment by shadowRR** [comment]
@talha-asad you should directly make a pull request on the documentation repo ;)

**Comment by jagi** [comment]
Yep that would be better :)
