### ISSUE TITLE
Astronomy Schema and Capped Collection

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#239]
Is there a way to define a schema that creates a capped collection in mongo? I am unsure if this is even supported in the native meteor collections. However i think this is a great feature in mongodb which should be configurable in astronomy as well.

**Comment by jagi** [comment]
After looking thorugh the code of Meteor I think it's possible to create capped collection https://github.com/meteor/meteor/blob/master/packages/mongo/collection.js#L649 however you can only call it on the server. I don't think that it should be supported by Astronomy

**Comment by talha-asad** [comment]
Okay thanks for digging that up. Yes i agree no need to integrate it in astronomy.
