### ISSUE TITLE
Validation stops on first invalid field

### ISSUE THREAD

**Issue by parhelium** [jagi/meteor-astronomy#24]
I noticed validation stops on first invalid field, that is perfect for most use cases.
However there is one use case where validation should not stop on first invalid field.

In my apps I try to keep structure of documents consistent all the time ( what a suprise ;-) ) so on every startup app is **validating all documents in all collections**. 
It may happen that doing some changes manually on db admin simply broke structure.
It is better to see upfront how much db was damaged.

Let me know if sth like that could be easy to add.
Again, thanks for your hard work ! :)

**Comment by jagi** [comment]
Hmm I was talking about validation in Astronomy with the friend from the work like few days ago. He pointed out that sometimes it would be great to validate all fields of the object, not just stop after the first error :). It shouldn't be hard to implement. Probably I would have to introduce new method like `validateAll()`, what do you think?

**Comment by parhelium** [comment]
`validateAll` would be very useful for me. 
As I wrote I'm already using `js-schema` for doing that, so `for me` this is another must-have feature ;-)

**Comment by jagi** [comment]
Ok, no problem :). I will implement it soon, maybe tomorrow :)

**Comment by jagi** [comment]
Done in version 0.10.5 :)
