### ISSUE TITLE
Run without Meteor

### ISSUE THREAD

**Issue by samhatoum** [jagi/meteor-astronomy#240]
First of all, amazing package! Thank you for saving us weeks of work.

I'm using Astronomy in our [automated testing best practices](https://github.com/xolvio/automated-testing-best-practices) repository as it massively facilitates the Modeling by Example technique. 

I'm now looking at options of how to run tests at hyper speed, which means running them outside of the Meteor context. As a thought experiment, I'm wondering what it would take to allow this package to be run without Meteor at all, and instead of using Collections, to use an in-memory collection instead. This would really improve the testability.

What are your thoughts @jagi?

**Comment by jagi** [comment]
Hi, thanks!

There was already a person that proposed creating npm package out of Astronomy that could be run without Meteor. It was possible in 1.0 but right now Astronomy is much more integrated with Meteor than it used to be.

I've read your guides about testing and my test probably don't follow good practices you've mentioned :)

Of course I could create Astronomy tests that use Collection mocks etc. but you would probably want to have Astronomy working without Meteor right? How do you want to use it in tests?

**Comment by talha-asad** [comment]
I proposed creating an npm package out of Astronomy and i agree it seems to be closely integrated with Meteor environment. I think with Meteor 1.3 onwards this package could be made into an NPM package which binds with meteor if Meteor is defined, but this will probably be quite an effort. I am sure that @jagi you'll be credited well for your efforts though. 

For now the mock approach maybe good enough for testing, but i think getting 2.0 released first is definitely the way to go.

**Comment by samhatoum** [comment]
> but you would probably want to have Astronomy working without Meteor right? How do you want to use it in tests?

When I create a class using this syntax:
```
Post = Astro.Class({
  // ...
});
```
The model cannot be easily instantiated outside of Astronomy, which means I have to run the full Meteor context to be able to to unit test it. 

I would like to just include Astronomy in my tests, as an npm package, and then test all I like :)

**Comment by jagi** [comment]
Hmm but what's wrong with this syntax? It's not a matter of syntax. Astronomy is just heavily dependent on Meteor (MonogoDB, MiniMongo, Tracker, EJSON). I think I can't make it less dependent. How would you see it? Let's say we have `collection` property in the class definition. You can replace it with the mock of the Meteor Collection. That's one thing that can be done. However I don't think it's possible about Tracker or EJSON. It will be probably easier to accomplish with Meteor 1.3 release. And if they gonna make Meteor packages an NPM packages that would allow "extracting" Astronomy out of Meteor.

**Comment by samhatoum** [comment]
Yea, sounds like it would be a pain! I don't have a concrete answer so I'm just poking around some ideas with you below.

What I'm trying to do is model the domain through testing. The domain consists of domain objects (or entities), aggregate objects and services. ([DDD basically](https://en.wikipedia.org/wiki/Domain-driven_design))

I'd like to separate the domain modeling concerns from the infrastructure/persistence concerns.

Say I have 2 account holders that have an account, and I have a bank that provides a transfer operation. I would model this as follows: (low fidelity model that illustrates the point)

```javascript
class Account {
  constructor(options) {
    this.balance = account.balance;
  }
}

class AccountHolder {
  constructor(options) {
    this.account = new Account(options);
  }
}

class Bank {
  static transfer(fromAccountHolder, toAccountHolder, amount) {
    fromAccountHolder.account.balance -= amount;
    toAccountHolder.account.balance += amount;
  }
}
```

And to would test the domain and the domain only (without any persistence concerns), I would do this:

```javascript
it('transfers an amount from account A to the account B', function () {
  const accountHolderA = new AccountHolder({balance: 50});
  const accountHolderA = new AccountHolder({balance: 60});

  Bank.transfer(accountHolderA, accountHolderB, 10);

  expect(accountHolderA.balance).toBe(40);
  expect(accountHolderB.balance).toBe(70);
});
```

Notice that I can run these tests completely outside of Meteor, they are just classes and methods and they would run at lightning speed.

I currently can't do this with Astronomy (or maybe I can and I missed something?)

Perhaps something like this would work? 

```javascript
Account = Atronomize({
  class: Account, // Tell Astronomy which class to use rather than name
  fields: {
    balance: {
      type: 'number',
      default: 0
    }
  }
});

AccountHolders = Meteor.users;
Atronomize({
  class: AccountHolder, // Tell Astronomy which class to use rather than name
  collection: AccountHolders,
  fields: {
    account: {
      type: 'object',
      nested: 'Account',
      default: function () {
        return {};
      }
    }
  }
});
```

Then let's say I'd like to add persistence and validation to my domain entity objects, I would probably want to test that I have configured my persistence and validation correctly. Again, I would like to do this as unit tests outside of Meteor, so I'd possibly want something like this:

```javascript
it('should create an account with a balance of 0', function () {
  var accountHolder = new AccountHolder(); // This would be an Astronomized class
  expect(accountHolder.get('account').get('balance')).toBe(0);
});
```

and

```javascript
it('should write to the AccountHolder collection', function () {
  spyOn(AccountHolders, 'insert');
  var accountHolder = new AccountHolder({'account.balance': 10}); // This would be an Astronomized class
  accountHolder.save();
  expect(AccountHolders.insert).toHaveBeenCalled(); // We're only interested in the correct configuration, and we trust that Astronomy is doing it's job
});
```

I know some of the things I'm proposing might go against the design principles of Astronomy, and I'm intrigued to hear your thoughts about the above.

Thanks for your time!

**Comment by jagi** [comment]
I had conversation about testing and Astronomy with @cwohlman and now I better understand the problem. However, there is no simple solution for that problem. We have to wait until Meteor 1.3 release and then I can make some changes if it goes about dependencies. However, even if they move to npm packages, Astronomy integrations with Meteor is so strong that the only way of solving this problem may be creating mocks for Collections and Meteor methods.

**Comment by ianserlin** [comment]
Astronomy doesn't deal much with reactivity except for the `Class.find/update/upsert/remove` methods. The solution to this would be to refactor out the implementation of those methods and the part of `save` that does touch the database into separate packages.

You might end up with something like:

`astronomy-base`: what @samhatoum is asking for
`astronomy-mongo`: all the code that interacts with `Collections` and the implementation and calling of the `save` method.

Together, they would make `jagi:astronomy`.

It is possible by placing hooks in certain places, and it would make Astronomy's internal tests easier.

Where that fits into the priorities is up to jagi.

**Comment by jagi** [comment]
@ianserlin I was thinking about it when MDG announced that they will integrate GraphQL. And yes you're right. The only places when Astronomy 2.0 is deeply integrated with Meteor is save and validation process. And I agree with the solution. However, I think it's to early to take these steps. When support for GraphQL will be ready then I will split meteor into two packages. It's not big deal for current and future Astronomy 2.0 users, as it would be release as let say Astronomy 2.1 which would be backward compatible and it would just include two package that you've mentioned. Because I think that MongoDB version should still be the main one. When I will see working implementation of reactive GraphQL I will think where to split Astronomy. Because right now it quite hard to tell.

**Comment by ianserlin** [comment]
Makes a lot of sense.

**Comment by jagi** [comment]
I'm closing this issue for now. I will think about creating NPM module in the future. But for now it's too tightly integrated with Meteor. I really want to make it less dependant but have to wait for Meteor 1.3 and for more information about GraphQL support.

**Comment by jargot** [comment]
Any update on this @jagi ?

I would love to use Astronomy in my project but I'm not quite ready to throw out unit-testing just yet :)
In any case, many thanks for your work :+1:

**Comment by lukejagodzinski** [comment]
As I'm getting more and more familiar with GraphQL, Relay etc. then I see less and less room for such tools like Astronomy. In fact GraphQL + Relay + React stack is not MVC, so as Astronomy is a model layer, then it would probably not fit into it. I want to focus more on GraphQL as it's great. If there is any tool in the future that would help with developing GraphQL/Apollo apps it would be rather some GraphQL wrapper.

**Comment by iamrobreynolds** [comment]
Are you suggesting that we can/should be defining our schemas totally using GraphQL inside Meteor apps? I would love this to be the case so as not be duplicating coding efforts.

**Comment by lukejagodzinski** [comment]
I'm not quite familiar with Apollo yet but from what I know the workflow of defining schemas with it will be the same as in pure GraphQL. So Astronomy would be just a wrapper for GraphQL schemas which I think is pointless.
