### ISSUE TITLE
Transient fields suggestion

### ISSUE THREAD

**Issue by khaledkbadr** [jagi/meteor-astronomy#243]
In the transient fields documentation, you guarded the `birthDate` field before setting the age field. Can you make that the `afterinit` is dependent on fields like `this.birthDate` and only run when the fields are satisfied rather than guarding explicitly every time.

```javascript
events: {
    afterInit: function() {
      var birthDate = this.birthDate;
      if (birthDate) {
        var diff = Date.now() - birthDate.getTime();
        this.set('age', Math.abs((new Date(diff)).getUTCFullYear() - 1970));
      }
    }
```

**Comment by jagi** [comment]
What do you mean by saying "guarded"?

**Comment by khaledkbadr** [comment]
you're checking if birthDate is set, then set the age property.
My suggestion is to make the event dependant on `this.birthDate`, and do the checking in the API.

**Comment by jagi** [comment]
Ok now I know what you mean. You never know what is the proper value of the `this.birthDate`. In this example it's a date and I should actually check if it's a date `if (_.isDate(birthDate)) {`. There may be a situation where `null` is proper value to compute another field's value. You never know.

How would you like it to look like?

**Comment by jagi** [comment]
I'm closing this issue for now. I will reopen it if necessary.
