### ISSUE TITLE
Can I trust getModified() on an Astronomy object that has been sent to a server method from the client?

### ISSUE THREAD

**Issue by Vincentjonssonqi** [jagi/meteor-astronomy#244]
Hello and thanks for writing a great package! 
I am building a security module for this package. I was  writing an update method that would take an instance of an astronomy class as input and evaluate its ACL property to see if the operation on the object is allowed by the user requesting it. Because The ACL for the object is a field in the object itself and the whole thing is going to the client I need some strategy for evaluating (on the server) if the ACL property has been compromised since last saved. So directly I am thinking I can just run getModified() on the object in the update method and if the ACL property has changed since the last save I will know. But then I started to think that maybe it is possible for somebody to modify the underlying data in the object on which the getModified() function evaluates the state on. Hence the title "can I trust getModified()" on an object sent to the server (assuming the client is compromised)?

**Comment by jagi** [comment]
You should never trust the client :) I think it's a main principle of every client-server application. And you can't also trust the `getModified()` method if a document was modified on the client. You should always check if a new field's value is allowed to be set by a given user.

**Comment by Vincentjonssonqi** [comment]
Thank you for the answer, I had the same feeling so solved it by making the update method accept a values object and a objectId, then authorizing the request using the last saved instance of the objects ACL that I fetched from mongo. :)
```javascript
'comment/update':function(commentId,values) {
    //do an initial check to ensure that the values sent to the function are the expected types
    check(commentId,String);
    check(values,Object);
    //variable declaration
    var acl,
        comment = Comment.findOne({_id:commentId});
    //if the comment in question was not found
    if (!comment) throw new Meteor.Error('403', 'Not a valid commentId');
    //There is no need to check ACL for clearnece if the Class does not imoplement ACLs.
    if (Comment.getSecurityConfig().implementsACL) acl = comment.get('ACL');
    //Now we to authorize the request be calling Class.authorizeRequest() wich will evaluate the request against the CLP and possibly an ACL too.
    if (!Comment.autorizeRequest(this.userId,'update',acl)) throw new Meteor.Error('404', 'Not authorized to update the object');
    //Set the values that the update requested
    comment.set(values);
    //See if the comment object passes the validators
    if (!comment.validate()) throw new Meteor.Error('403', 'Not a valid comment');
    //save the comment
    try{
      comment.save();
      return comment;
    }catch (err){
      throw new Meteor.Error('400', err);
    }
  },
```
