### ISSUE TITLE
Can nested documents have behaviors?

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#245]
I have a nested document in my Astro Class. Can i use the timestamp behavior on it? If no, is there a workaround this?

If yes, does it work with array of nested objects as well?

**Comment by jagi** [comment]
Right now behaviors does not work on the nested fields. You have to implement it by your self from the top level document. I will be working on implementing it in Astronomy 2.0 but it may be hard to do.

**Comment by talha-asad** [comment]
Okay thanks for the info.
