### ISSUE TITLE
Why is this failing, bug?

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#247]
```js

Audiences = new Mongo.Collection('audience');

Audience = Astro.Class({
  name: 'Audience',
  collection: Audiences,
  fields: {
    _id: 'string',
    targets: {
      type: 'array',
      nested: 'object',
      default: function() { return []; }
    }
  }
});
```

The error i get on server shell is also not very useful as it fails to tell me which file and on what line the error actually is:
```
W20160105-12:16:05.449(5)? (STDERR) TypeError: Cannot read property 'nested' of undefined
W20160105-12:16:05.450(5)? (STDERR)     at new ObjectField (packages/jagi_astronomy/lib/modules/fields/types/object_field.js:8:1)
W20160105-12:16:05.450(5)? (STDERR)     at new ArrayField (packages/jagi_astronomy/lib/modules/fields/types/array_field.js:12:1)
W20160105-12:16:05.450(5)? (STDERR)     at packages/jagi_astronomy/lib/modules/fields/init_definition.js:181:1
W20160105-12:16:05.450(5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20160105-12:16:05.450(5)? (STDERR)     at Function.onInitDefinitionFields (packages/jagi_astronomy/lib/modules/fields/init_definition.js:177:1)
W20160105-12:16:05.450(5)? (STDERR)     at packages/jagi_astronomy/lib/modules/core/classes.js:27:1
W20160105-12:16:05.450(5)? (STDERR)     at packages/jagi_astronomy/lib/modules/core/events.js:68:1
W20160105-12:16:05.450(5)? (STDERR)     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
W20160105-12:16:05.451(5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20160105-12:16:05.451(5)? (STDERR)     at Object._.extend.each (packages/jagi_astronomy/lib/modules/core/events.js:64:1)
```

I am not sure if this is a bug, but i think the error trace should definitely be a bit more pointing. Right now the file that has this code isn't even being mentioned anywhere, so it kind of makes the developer go through each model and see if he made an error.

I know you're busy releasing 2.0 but if we can get the error traces fixed in 2.0 and leave them as is in 1.0 i think that would work with most people as well.

**Comment by jagi** [comment]
Remove `nested: 'object',`, you have to provide here plain type like `string`, `number` or class name. And that's why in Astronomy 2.0 I've changed the way nested fields are defined. Right now it's confusing.

**Comment by talha-asad** [comment]
Will Astronomy 2.0 have better error messages than the ones we get right now in 1.0?

**Comment by jagi** [comment]
Yes it will. However it's not possible to show exact error message for all possible situations. It will definitely be better than in 1.0
