### ISSUE TITLE
Better way to update document without ID selector

### ISSUE THREAD

**Issue by NaderIkladious** [jagi/meteor-astronomy#248]
Hello, 

When updating a document that you don't have it's ID and when it's simulated on the client it throw an error

```javascript
var commentId = 1;
var post = { _id: 2};

Comment.update({
        _id: {$ne: commentId},
        postId: post._id,
        pinned: true,
      }, { $set: {pinned: false} }, {multi: true});
```

What would be the best way to update documents directly without having their ids.

Error in console
```
Exception while simulating the effect of invoking 'Comment.togglePin' 
errorClass {error: 403, reason: "Not permitted. Untrusted code may only update documents by ID.", details: undefined, message: "Not permitted. Untrusted code may only update documents by ID. [403]", errorType: "Meteor.Error"}
```

Thanks :)

**Comment by jagi** [comment]
It's not a problem with Astronomy. It's how Meteor works. In principle it's not allowed to updated and remove documents on the client by anything but ID.

**Comment by NaderIkladious** [comment]
Oh Thank.
