### ISSUE TITLE
Client side indexes?

### ISSUE THREAD

**Issue by ayalpani** [jagi/meteor-astronomy#249]
Hi jagi, 

do I assume rightly, that an index I define with astronomy (http://astronomy.jagi.io/indexes) only uses/implements server side mongo indexes? Or does astronomy also maintain client side indexes?

Thanks, ayalpani

**Comment by jagi** [comment]
Hi, there is no index feature in MiniMongo and that's what is used on the client in Meteor and Astronomy. Astronomy is not changing here anything. So yes indexes are only implemented on server. MDG decided not to implement indexes on the client as user is mostly subscribed to small amount of documents and sorting/filtering/searching is quite fast for small sets.

**Comment by ayalpani** [comment]
Hi jagi, this was expected. So I need to create my own custom indexes, as my use case demands so - I need to support thousands of nested sets in the client. And thank you for astronomy, I just started using it today and it's really great :)

**Comment by jagi** [comment]
You may try extending MiniMongo and publishing a package. It would be great to have one.

I'm currently developing Astronomy 2.0 and it will be much better than 1.0 :)
