### ISSUE TITLE
remove syntax

### ISSUE THREAD

**Issue by dovrosenberg** [jagi/meteor-astronomy#25]
Not a big deal at all, but it might be helpful to have a way to remove a document given just an _id.  Because removes are often done in a meteor method, it can be more efficient to call the method with just an _id and not have to pass a full copy of the object back to the server.  Similarly for cases where all I have is an _id (perhaps from a related record) and haven't yet pulled the whole document.

If I do Posts.remove(id), then any Astronomy beforeremove/afterremove events don't get called.  So I've been doing `(new Post({_id:id})).remove()`, which seems a bit clunky.  Is there a better way?

**Comment by jagi** [comment]
If I understand you correctly you would like to minimise the amount of data that is sent over DDP from the client to the server when calling remove method, right?

When sending documents over wire using DDP, the entire object gets EJSON-ified. And I wouldn't mess with that. Of course there are situations (like remove) when you don't need entire object. Id is just enough. What I would suggest is something like this:

```js
// Client/server (or only server).
Meteor.methods({
  'remove': function(id) {
    var post = Posts.findOne(id);
    post.remove();
  }
});

// Client
Meteor.call('remove', post._id);
```

**Comment by dovrosenberg** [comment]
Yes.  It just seemed that pulling the whole document (FindOne) from the database in order to remove it isn’t very efficient.

**Comment by jagi** [comment]
Yes indeed, when you have a lot of traffic then sending only id or the whole object can make a difference. So it's good to have a choice. In fact you could even simplify this:

```js
// Client/server (or only server).
Meteor.methods({
  'remove': function(id) {
    Posts.remove(id);
  }
});

// Client
Meteor.call('remove', post._id);
```

However if you want to soft delete record you should do as follows:

// Client/server (or only server).
Meteor.methods({
  'remove': function(id) {
    var post = Posts.findOne(id);
    post.softRemove();
  }
});

// Client
Meteor.call('remove', post._id);

**Comment by dovrosenberg** [comment]
Not just softRemove, but if you have any delete events on the class, you have to use post.remove().  In those cases, while it's ugly, I'm thinking this would be the fastest:

    // Client/server (or only server).
    Meteor.methods({
      'remove': function(id) {
        (new Post({_id:id})).remove();
      }
    });

    // Client
    Meteor.call('remove', post._id);

**Comment by dandv** [comment]
A `Class.removeById(id)` method would be more explicit and faster if it could just remove the document specified by the id and run the `before` and `after` handlers, but not fetch the document from the DB.

However, it seems from the docs that `before` and `after` storage event callbacks receive the document in `this`, so `beforeremove will have fetch it from the DB anyway, which renders @dovrosenberg's point moot.

@jagi, is that accurate? Do `beforeremove` and `afterremove` set `this` to the object? Perhaps this should be documented in the README. There's an example at [Storage events](https://github.com/jagi/meteor-astronomy#storage-events) but not explicit documentation of their parameters or `this`.

**Comment by jagi** [comment]
Yes, you are right the `beforeremove` and `afterremove` events are called in the context of a document. To follow this principle in the `Class.removeById(id)` function we would still have to get the document from the database.
