### ISSUE TITLE
Inc does not work with set

### ISSUE THREAD

**Issue by samhatoum** [jagi/meteor-astronomy#253]
I have this class:

```javascript
Account = Astro.Class({
  name: 'Account',
  fields: {
    balance: {
      type: 'number',
      default: 0
    }
  }
});

AccountHolders = Meteor.users;
AccountHolder = Astro.Class({
  name: 'AccountHolder',
  collection: AccountHolders,
  fields: {
    name: 'string',
    username: 'string',
    password: 'string',
    emails: 'array',
    services: 'object',
    createdAt: 'date',
    account: {
      type: 'object',
      nested: 'Account',
      default: function () {
        return {};
      }
    }
  }
});
```

And this code:
```javascript
const accountHolderA = new AccountHolder();
console.log('1 -', accountHolderA.get('account.balance'));
accountHolderA.set({'account.balance': 50});
console.log('2 -', accountHolderA.get('account.balance'));
accountHolderA.inc('account.balance', 10);
console.log('3 -', accountHolderA.get('account.balance'));
accountHolderA.set('account.balance', accountHolderA.get('account.balance') + 10);
console.log('4 -', accountHolderA.get('account.balance'));
```

The output is this:
```
1 - 0
2 - 50
3 - 50
4 - 60
```

Expected output:
The output is this:
```
1 - 0
2 - 50
3 - 60
4 - 70
```

It seems that calling `inc` after `set` does not work. Is this expected behaviour?

**Comment by jagi** [comment]
Yes it's limitation of the 1.0 version of Astronomy. I've fixed it in 2.0. It's all about deep integration of Astronomy with MongoDB that allows only one operation on a given field. I'm registering all modifiers that had been executed and later try to run them when save is called.

Right now you have to execute save between operation of different type on the same field. You CAN execute many `set` (`inc` etc.) operations on the same field. But you can't execute on the same field operations of different type.
