### ISSUE TITLE
Collection Integrity

### ISSUE THREAD

**Issue by ayalpani** [jagi/meteor-astronomy#254]
Hi jagi,

I am wondering if there is already a solution or a pattern to use onboard, to check the overall integrity of a astronomy managed collection.

Basically, I am implementing hierarchical doc trees with this parent-references pattern: https://docs.mongodb.org/manual/tutorial/model-tree-structures-with-parent-references/

In addition, every doc keeps a reference to its predecessor with a "previous" field. A tree can be represented by these entries:

```javascript
{ _id: ObjectId('a'), title: 'root', parentId: null, previousId: null }
{ _id: ObjectId('b'), title: 'first child', parentId: ObjectId('a'), previousId: null }
{ _id: ObjectId('c'), title: 'second child', parentId: ObjectId('a'), previousId: ObjectId('b') }
{ _id: ObjectId('d'), title: 'third child', parentId: ObjectId('a'), previousId: ObjectId('c') }
```

This results in a tree structured like this:

```
root
  first child
  second child
  third child
```

Now I need a way to describe integrity rules, like:

`It is not allowed to have multiple docs with the same parentId and the same previousId (unless all but one of them were softRemove'd)`

Any proposal how to implement integrity rules, spanning a whole collection? Or at least a central spot to hook into document creation/update (taking into account softRemove behaviour)?

Thanks a lot! ayalpani

**Comment by jagi** [comment]
I think the best place for that is the `beforeSave` event and throw `Meteor.Error` if the condition is not met

**Comment by ayalpani** [comment]
Thanks, I will try that
