### ISSUE TITLE
Direct collection access callback

### ISSUE THREAD

**Issue by MeKarina** [jagi/meteor-astronomy#256]
helloo,, is there callback for direct collection access..??

```
Class.update({selector}, {modifier}, function(err, id) {
  if (err) {
    // do something
  } else{
    // do something
});
```

and getting this error...
```
Uncaught TypeError: doc._executeModifier is not a function
(anonymous function) @ init_class.js:134
(anonymous function) @ minimongo.js:173
_.each._.forEach @ underscore.js:105
LocalCollection.Cursor.forEach @ minimongo.js:167
classMethods.update @ init_class.js:132
Template.xxx.events.click #xxx @ xxx.js:53
(anonymous function) @ template.js:483
Template._withTemplateInstanceFunc @ template.js:457
(anonymous function) @ template.js:482
(anonymous function) @ view.js:884
Blaze._withCurrentView @ view.js:538
(anonymous function) @ view.js:883
(anonymous function) @ events.js:47
jQuery.event.dispatch @ jquery.js:4665
elemData.handle @ jquery.js:4333
```

thank You,,,

**Comment by jagi** [comment]
Have you solved your problem?

**Comment by MeKarina** [comment]
not yet... =((

**Comment by jagi** [comment]
And yes there is a callback:

```js
Post.update(s._id, {$set: {title: 'TEST'}}, function() {
  console.log(arguments);
});
```

If you show more code then I will be able to help

**Comment by MeKarina** [comment]
helloo,, @jagi 

i just find out that error above appear when i turn off transform,,, it's not about callback..

when i turn on transform,, error disappear,,, however update couldn't be saved without any error...

```
Class.update({selector}, {$addToSet: {key: value}})
```

only work when i use Collection...

```
Collection.update({selector}, {$addToSet: {key: value}})
```

thank Youu...

**Comment by jagi** [comment]
Oh I see. Yes Direct collection access is limited in 1.0 however it will be full featured in Astronomy 2.0. I will release 2.0.0.rc1 version until the end of this week or on the beginning of the next one. So you can switch to it. Of couse it won't be production ready package but you still can use it.

For now, for that particular case (`$addToSet` modifier) I would not recommend using direct collection access from Astronomy.

**Comment by MeKarina** [comment]
better wait then,,, and congratzz for the v2... =))

**Comment by jagi** [comment]
Thanks :) so just follow [this issue](https://github.com/jagi/meteor-astronomy/issues/236) to be informed about the release :)
