### ISSUE TITLE
BeforeRemove event

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#257]
I want to remove related documents from other collections.

I remove an object from a collection using the ```.remove``` method on the client. The client is permitted to do so using allow/deny.

The client fires the ```beforeRemove``` event but the server does not. Is this a bug? What is a good way to go about this?

**Comment by jagi** [comment]
You have to know that in Astronomy 1.0 when you call `save()` or `remove()` on the client it's not being executed on the server. To do so you have to execute it in the Meteor method.

```js
// client & server
Meteor.methods({
  'remove': function(doc) {
    doc.remove();
  }
});

// client
Meteor.call('remove', Docs.findOne());
```

However, in Astronomy 2.0 it's much easier you can just call `doc.remove()` and it will be executed in both client and server.

**Comment by talha-asad** [comment]
I was of the understanding that this is something Meteor did internally. I understand now, thanks.

On a side note, i noticed the Events page doesn't mention that the document being removed is accessible as ```this``` inside the event function. I think this should be mentioned on the docs.

**Comment by jagi** [comment]
Yes right, sorry for that. Could you help me with that and update [this document](https://github.com/jagi/meteor-astronomy-docs/blob/master/docs/events.md) providing proper info? I will merge it and publish. In Astronomy 2.0 it will change a little bit, you will access document in the following way:

```js
events: {
  beforeRemove: function(e) {
    e.target;
    e.currentTarget;
  }
}
```

Which is more like the standard way in JS
