### ISSUE TITLE
Can get parent attribute on validator

### ISSUE THREAD

**Issue by ArthurGerbelot** [jagi/meteor-astronomy#259]
Hi,

I try to create a Astro validator object for Meteor.users collection but I have a problem.
A good part of validation rules are based on very important field (user.level) 

```
let validPhoneNumber = Validators.if({
  condition: function () {
    return this.level === 1;
  },
  true: Validators.or([
    uniquePhoneNumber,
    Validators.empty()
  ]),
  false: Validators.and([
    Validators.required(),
    uniquePhoneNumber
  ])
})

Users = Astro.Class({
  name: 'Users',
  collection: Meteor.users,
  fields: {
    level: {
      type: 'number',
      default: 1,
      validator: [
        Validators.gte(1),
        Validators.lte(3)
      ]
    },
   /*...*/
    'profile.cellPhone': {
      type: 'string',
      validator: validPhoneNumber
    },
  }
});
```

But the `cellPhone` field is on a `profile` object. And on the condition function `this` is a reference to `user.profile` instead of `user`..
So I can't get access to user level on validation..

**Comment by jagi** [comment]
Hmmm in deed it's a problem to get the parent document. Right now I can't think of the way of accessing it. I will definitely have to allow this in Astronomy 2.0. I have to figure something out. I will be working on validation in Astronomy 2.0 this week, so I will investigate this problem.

**Comment by ArthurGerbelot** [comment]
Thank you for taking account to my issue. It's maybe simple to start with a new optional attribute like `validation_scope` where I can choose one. Ex:

```
'profile.cellPhone': {
  type: 'string',
  validator: validPhoneNumber ,
  validator_scope: this,
},
```

**Comment by jagi** [comment]
It's not so easy. As you define validators on the level of class, then you can't easily access parent context. The `profile.cellPhone` syntax is not allowed, but maybe I will have to support that. After I implement the base validation rules I will think about accessing parent context.

**Comment by stoked74** [comment]
+1 on this. I'm currently passing properties from the parent to the child when the class is created to work around this exact issue. This issue comes up a lot for me.

**Comment by lukejagodzinski** [comment]
This problem was related with Astronomy 1.0 and I'm not creating any new features for this version
