### ISSUE TITLE
.isModified() throwing cryptic error (weirdly, sometimes)

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#262]
Don't want to throw you off focus, but on calling ```.isModified()``` is returning this. It is working at a few places, but i don't understand why its not working here. I'll continue to debug but i just wanted to ask if this is a known bug in Astronomy 1.0?

```js
TypeError: Object [object Object] has no method '_getModifiers'
I20160112-19:29:23.199(5)?     at packages/jagi_astronomy/lib/modules/fields/modifiers.js:345:1
I20160112-19:29:23.199(5)?     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
I20160112-19:29:23.199(5)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160112-19:29:23.200(5)?     at packages/jagi_astronomy/lib/modules/fields/modifiers.js:343:1
I20160112-19:29:23.200(5)?     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
I20160112-19:29:23.200(5)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160112-19:29:23.200(5)?     at Class.proto._getModifiers (packages/jagi_astronomy/lib/modules/fields/modifiers.js:307:1)
I20160112-19:29:23.200(5)?     at Class.proto.isModified (packages/jagi_astronomy/lib/modules/fields/modified.js:45:1)
```

I will try and get you a reproducible version as i continue to debug this.

**Comment by jagi** [comment]
Yes, please create a reproduction. Then I will be able to tell more.

**Comment by talha-asad** [comment]
Okay i think it was my fault. I have an array in my collection. I was directly pushing to it, like ```Campaign.line_items.push``` instead of ```Campaign.push('line_items', ...)```. But the error is thrown on ```.isModified()``` not at pushing.

**Comment by jagi** [comment]
You know having to use Astronomy `set`, `push` etc. methods is pain in the ass and that's why in Astronomy 2.0 you don't have to. You can modify your documents freely and Astronomy will know what changes you've made.

If it goes about your problem. I don't know why exactly it was throwing an error but let's just forget it as you solved it. As 2.0 will be released there will be much less problems with it.

**Comment by talha-asad** [comment]
I agree. :+1:
