### ISSUE TITLE
Suggestion: use LoDash instead of Underscore for performance improvement

### ISSUE THREAD

**Issue by JonathanHindi** [jagi/meteor-astronomy#265]
I found that astronomy relies heavily on underscore, however underscore is not performant as LoDash is. 

There are some breaking changing in LoDash however it will provide astronomy with a big performance gain and since you are in the process of launching version 2 of astronomy #236, I think it could be something you consider as well. 

Meteor Discussion: meteor/meteor#1009 
LoDash Migration Guide: https://github.com/lodash/lodash/wiki/Migrating

**Comment by jagi** [comment]
I wish I could use lodash. I wanted to make that switch in 1.0 but Meteor is using underscore and loading two similar libraries would increase application size. I've been waiting for integration of both libs. But after lodash 4.0 release I see that they are still two separate projects even if they collaborate now. I would like Meteor to switch to lodash, then I would switch too.

**Comment by JonathanHindi** [comment]
@jagi I agree however, i think that MDG is also considering that if they migrated to LoDash (won't happen anytime soon) a lot of community packages will need to be updated as well, I simply believe that package maintainers should start this process as even the underscore version we have in meteor is obsolete.

IMO, The performance gain from LoDash 4.x release is much valuable than the extra KBs loaded on the client, correct me if I'm wrong.

**Comment by jagi** [comment]
Hmm maybe I should give it a chance. However, I don't know if I should use the newest 4.0 version or 3.0. The problem with 4.0 is that it does not support IE < 9 as long as you don't use polyfills. I don't know if ES6 polyfills that comes with the `ecmascript` package provide that support.

**Comment by MeKarina** [comment]
i'm using lodash...
https://github.com/stevezhu/meteor-lodash 
and not having a problem so far....

meteor using obsolete underscore... related issue:
https://github.com/meteor/meteor/issues/1009

better give it a chance @jagi ...

**Comment by jagi** [comment]
@MeKarina @JonathanHindi yes I will give it a chance, just don't know if I should use 3.0 or 4.0 version.

**Comment by DirlanS** [comment]
that's great and thank Youu.. @jagi 

for me,, this would be too much to satisfy all users especially user who uses older browser... testing debugging finding culprit tweaking OMG...!!! would be better to educate users to upgrade their browser,, this benefit to both parties (developer and users)... beside that,, IE users declining every month www.w3schools.com/browsers/browsers_stats.asp,,, and i love moving forward...

but i leave it to you.. i believe your consideration better than mine... =))

**Comment by MeKarina** [comment]
ehhh,,, so every comment sent to email... apologize for disturbing,,, previous comment was from me.... i taught my friend how to use github and accidentally use that example account to comment...

**Comment by jagi** [comment]
I've replaced underscore with lodash 3.x and had several problems related with how `_.each` method works in lodash but I've managed to fix it. I will probably release RC.1 version today so you will be able to test it out. For now I'm closing this issue.
