### ISSUE TITLE
How to get class by index?

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#267]
Where normally I would use Collect.forEach(//fn), I have an asynchronous loop, so I need to be able to get a class item by index. For example:
````javascript
var posts = Posts.find({});
var i = 0;
(function asyncLoop(
   //do something with post[i] here
   if(i < posts.count()){
      asyncLoop();
   }else{
      console.log('finished!');
   }
})();
````
Right now, the best way I know to do this is by doing Posts.find().fetch(), then using Posts.findOne(posts[i]._id) to get the correct class, is there a better way?

**Comment by jagi** [comment]
I don't think it's something related with Astronomy. I don't understand what exactly do you want to achieve, but from what I see you probably need the `skip` option in the mongo query.

```js
Posts.findOne({}, {skip: index});
```

**Comment by JulianKingman** [comment]
Ah, that's what I'm looking for, thanks!

**Comment by jagi** [comment]
No problem :)
