### ISSUE TITLE
How to put astronomy object into server method?

### ISSUE THREAD

**Issue by Tbutnyakov** [jagi/meteor-astronomy#270]
Hey!
When I tried to insert validation logic from astronomy-validators package, I found a strange error.
Look at this sample: 

**In client:**

```
 var post = new Post();
            post.set({
                title: event.target.add_post_title.value,
                content: event.target.add_post_content.value,
                video: videoId.get()
            });
            
 Meteor.call("add_post", post, function (err, post) {
                if (err) {
                    post.catchValidationException(err);
                }

                console.log(post);
            });
```

**In server method:**
```

Meteor.methods({
    'add_post': function (post) {
        if (post.validate()) {
            post.save();
            return post;
        } else {
              post.throwValidationException();
        }
       
    }
});
```

In this case i will take this error from Meteor: 

> Received error from server:  Parse error

It is look like meteor can't parse Astronomy object...
How can i put it into meteor methods?

**Comment by jagi** [comment]
Please create reproduction repository which I can clone and run. I don't have time to create one by myself.

**Comment by Tbutnyakov** [comment]
Hey, Jagi!
Already done: https://github.com/Tbutnyakov/forjagi
Ty for help!

**Comment by jagi** [comment]
The problem is with the `Meteor.userId()` default value. This method can't be called during EJSON-ification so you should put it in the try-catch block for now. Here is an issue: https://github.com/meteor/meteor/issues/5356

It's a bug/issue in EJSON. In Astronomy 2.0 it won't be sending document over wire. It will send pure data instead, so the problem will not occur.

**Comment by Tbutnyakov** [comment]
Wow...this is a very...interesting:)
Ok, TY for fast answer and awesome package. 
So, when you will publish astronomy 2.0? 
I would like to talk about it in a series of broadcasts on my youtube channel.

**Comment by jagi** [comment]
Until the end of the Q1 it should be ready. I don't want to hurry, especially when I've heard about so many changes that are going to happen in future Meteor versions.
That would be great. I wanted to create video tutorials about Astronomy when it's ready. But I would be glad if you could promote it in the form of videos on your YT channel :)

**Comment by Tbutnyakov** [comment]
Sounds great!
But i will make screencasts for russian auditory only, because I have very poor english
Good luck.
