### ISSUE TITLE
Question: Type check in Meteor methods

### ISSUE THREAD

**Issue by minfawang** [jagi/meteor-astronomy#273]
I feel this topic might be discussed somewhere earlier, but I couldn't find anything, and hence create a new thread.

For almost all the Astronomy examples that I see, this is how a method is defined:
~~~javascript
Meteor.methods({
  '/post/save': function (post) {
    if (post.validate()) {
      post.save();
    }
    post.throwValidationException();
  }
});
~~~

I wonder if it's possible to check the argument `post` is a valid `Post` instance, because I don't want the client to pass in an instance of another kind of Astronomy Class and get saved. I realize doing `post.constructor === Post` will return true with correct argument , but I suspect adding this check is still insufficient, or is it? 

Thanks!!

**Comment by jagi** [comment]
You can always do
```js
if (post instanceof Post)
```

It will change a little bit in Astronomy 2.0 because you won't have to define such methods by yourself.

As I'm thinking about it I'm considering possible security issues of not checking document type passed to the method.

**Comment by minfawang** [comment]
Oh I thought I used to try `post instanceof Post` and not got expected result. I must be wrong. 

Glad you are doing that modification on 2.0. I remember you said in 2.0 `save()` will be implemented as a meteor method and validation will always be called automatically. That's handy.

Anyway I'm closing this issue. Thanks for the response!

**Comment by jagi** [comment]
It should work without the problem.

Yes exactly.

No problem :)
