### ISSUE TITLE
Worth checking out: Neurosync has relations, bindings for other libraries

### ISSUE THREAD

**Issue by thinkpadder1** [jagi/meteor-astronomy#277]
[https://github.com/ClickerMonkey/neurosync](neurosync)

From the repo:

> Neurosync is a javascript ORM that is offline & real-time capable.
> 
> ORM you say? Neurosync doesn't do anything crazy directly with a database - the database to Neurosync is a facade typically backed by a REST API. It's an ORM in the sense that it handles creating, updating, and deleting relational data to any degree you wish.

**Comment by jagi** [comment]
I've recently follow what's going on with the Reactive GraphQL and I think it will change a lot if it goes about model layer. From what I understand in neurosync you're responsible for storing a document in a database by calling it directly or by using some REST api. I think the same scenario will be true about GraphQL. In GraphQL you can't modify documents freely. You have to create mutation for each possible change or set of changes. So, it's not so easy like in MiniMongo or just Mongo that you can do whatever change. Of course you could create mutation that update entire document and related documents in one query and only pass to this query data that has changed, which may be a good solution. However, it's to early to do any assumption without playing with actual API.

What I want to say is that in Astronomy I want to make things as easy as possible. And the approach that neurosync is using is not easy one. I want user not to think about the database at all if not needed. Take document, modify it and save it. And Astronomy 2.0 will have built in relations which will make things even easier.

But thanks for suggestion. I will come back to this problem when having to deal with GraphQL.

**Comment by tjscooper** [comment]
Thanks Jagi,

We're all eagerly awaiting your relations solution :)

I would even suggest it could take priority over auto-increment on your issue list, unless that is by design.

Keep up the great work!
Tim

**Comment by jagi** [comment]
Yes it's definitely before autoincrement feature

**Comment by Andrew1431** [comment]
When will astronomy support atomic transactions? heheheheh

:smiley: :+1:

**Comment by jagi** [comment]
@Andrew1431 hmm it was on the original list of features to implement but haven't time do it. However it's quite important feature as MongoDB does not support it out of the box. But from what I remember they are planning to introduce transactions into MongoDB, or they already do. However, problem is not so simple to solve. Even if MongoDB will support transactions, MiniMongo won't so I will still have to use one of the known workarounds for that. However, there is a chance that it should be much easier with GraphQL, where you can use any database on the server and on the client you just do simulation. But until MDG release Meteor with official support I can't tell more about the future of transactions in Astronomy. I definitely plan to support it.

**Comment by Andrew1431** [comment]
Hah, wow I mostly wrote that as a joke because of how awesome your package
is but that's sweet. Hopefully we can see that some day

**Comment by jagi** [comment]
hehe :)
