### ISSUE TITLE
Relations with manuel:viewmodel

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#278]
I am not sure if this is a problem with Viewmodel or Astronomy, but I made a repo for debugging:

https://github.com/arggh/mvissue

1. I publish a composite, which includes the Budget-object, it's childrens (budget groups) and budget groups' childrens, called the expenses.
2. I subscribe for the composite publication on the main template, from where I pass the data to other templates.

Everything works If I pass the context along like this:

    {{#each group in groups}}
        {{>budget_group group=group}}
    {{/each}}

and then, in **Budget Group Viewmodel:**

    Template.budget_group.viewmodel({
        expenses() {
            return this.group().expenses();
        }
    }

and in **Budget Group template:**

    {{#each group.expenses}}
     ....
    {{/each}}

However, if I try to pass the context like this:

    {{#each groups}}
        {{>budget_group}}
    {{/each}}

and change the **Budget Group Template** like this:

    {{#each expenses}}
    ...
    {{/each}}

it still works and renders the expense-child objects like it's supposed to. However,

if I try to access  in **Budget Group Viewmodel**

    Template.budget_group.viewmodel({
        someRandomFunction() {
            console.log(this.expenses());
        }
    });

it all goes haywire with this sort of error message:

> Exception from Tracker afterFlush function: debug.js:41 TypeError: Class.getRelation is not a function at ViewModel.prototypeMethods.getRelated (http://localhost:3000/packages/jagi_astronomy-relations.js?31f87e1c7380aa4c61a6a9d20d6738ecdfe31b8f:46:24) at ViewModel.methods.(anonymous function) [as expenses] (http://localhost:3000/packages/jagi_astronomy-relations.js?31f87e1c7380aa4c61a6a9d20d6738ecdfe31b8f:149:23) at ViewModel.Template.budget_group.viewmodel.allPaid (http://localhost:3000/client/budget_calculator/budget_group.js?16ae5fa99e0e3b5d65d548576309a68260e7b94f:11:25) at getValue (http://localhost:3000/packages/manuel_viewmodel.js?4fa94bc281850c2cbc1a78f4271fe4288c705243:665:37) at Object.getVmValue (http://localhost:3000/packages/manuel_viewmodel.js?4fa94bc281850c2cbc1a78f4271fe4288c705243:685:14) at http://localhost:3000/packages/manuel_viewmodel.js?4fa94bc281850c2cbc1a78f4271fe4288c705243:1348:20 at fun (http://localhost:3000/packages/manuel_viewmodel.js?4fa94bc281850c2cbc1a78f4271fe4288c705243:411:18) at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1872:20 at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3671:12) at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1870:29 debug.js:41 Exception from Tracker afterFlush function:

**Comment by jagi** [comment]
Example application is too complex to investigate it. I would take me to much time to understand everything. Description of the problem is also not detailed enough. Please, try preparing as minimal reproduction as possible.

**Comment by arggh** [comment]
Hi Jagi, 

sorry about the complexity, I had to keep some inheritance structure to show the problem. But I think it's more about Viewmodel than Astronomy, since the creator of Viewmodel already seems to have cracked the problem:

> Here's what's happening. The expenses method added by Astronomy expects its context to be an Astronomy object. It uses "this" expecting it to be an Astronomy object. When you let budget_group inherit from the Astronomy object, it just copies the expenses function. When you run "this.expenses()" the expenses method executes with the view model as context, not the Astronomy object, and thus it breaks. I have to think about this one because I'm not sure I want to use the inherited object as context for the inherited functions (from that object). Say that three times fast... I'll think about it in the next few days.

**Comment by jagi** [comment]
@arggh oh ok that's good that he found the problem. So I can't probably help with that one as Astronomy method needs `this` context to be an Astronomy document.

**Comment by arggh** [comment]
Here's his input on the issue from viewmodelboard.meteor.com, since I have a feeling quite a few newcomers to combination of Astronomy+Viewmolde might fall for this:

> Okay, after a lot of thought, I'm going to leave things as they are. The problem here is that you're mixing your model (capital M in MVC) with the view model (the code that drives the V in MVC). The way I see it your model should have absolutely no notion of the view. The view on the other hand can use your models, but they're two separate entities.
> 
> Why do I mention all that yada, yada? Take a look at the following model:
> 
> ```
> {
>   firstName: 'Alan',
>   lastName: 'Brito'
> }
> ```
> 
> Now let's say you're using a package like Astronomy which extends your models, and you add the function:
> 
> ```
> fullName() {
>   return this.firstName + ' ' + this.lastName;
> }
> ```
> 
> Out the bat, if a view model inherits from that object, it will not work as expected. That's because this in fullName represents the view model, not the object itself. So this.firstName returns a function, not the value of firstName.
> 
> The solution we were toying with was to set the context of functions to be the inherited objects and not the view model. At first glance this seems to be a viable solution because fullName would return Alan Brito. So far so good, until you change firstName in the view model to something like Bran. You then have a problem because fullName keeps returning Alan Brito, not Bran Brito. If you update the model you then lose reactivity. (can't win for loser huh?)
> 
> The problem is that you end up with two sources of truth. The model and the view model. The solution is to do what you've done on the route that works. Keep your models and their extended functions separate from the view model and its properties.
> 
> So, in our example, if you use fullName on the view then create a mixin for the person object with a function that returns the full name. It's pretty much the equivalent of extending the person model, but you're doing it for the view instead. If you're going to use a model and its extended properties then treat it as an immutable object. Pass the object as a part of a property, not the context itself. This is what you do in:
> 
> ```
>   {{#each groups}}
>     {{>budget_group2 group=this}}
>   {{/each}}
> ```
> Here you're not letting a group (a model with extended methods) be the context of budget_group2, instead it's a property of the context.

**Comment by jagi** [comment]
Oh that explains everything, thanks.
