### ISSUE TITLE
CRUD many-to-many relatioships between 3 interconnected collections

### ISSUE THREAD

**Issue by lobosan** [jagi/meteor-astronomy#280]
Hi @jagi, I've been reading about Astronomy, it's documentation and the examples but I'm still not sure if I can use your package for the following scenario.

I have 3 collections: Markets, Producers and Organizations
- Markets might have many Producers and vice versa
- Producers might have many Organizations and vice versa 
- Organizations might have many Markets and vice versa

My question is, how should I design the schemas in order to perform reads, inserts, updates and deletes, while everything stays in sync and integrity is ensured?

Thanks in advance for any help

**Comment by jagi** [comment]
It's not a problem of the tool you are using but database schema. There are several ways of solving this problem. You should read these: http://seanhess.github.io/2012/02/01/mongodb_relational.html#many-to-many-relationships
You can just store ids of documents in an array. And if you need many-to-many relation you should do it in both collections.

Right now in 1.x, we have experimental relations module that does not support that type of relation, however you can easily design such schema without that module. However, in Astronomy 2.x relations will be built in feature, with the support for many-to-many relations.

**Comment by jagi** [comment]
I'm closing this as not related with Astronomy and more with design. In 2.0 there will be support for relations. So you have to wait for that.
