### ISSUE TITLE
How to get this running with angular?

### ISSUE THREAD

**Issue by phortx** [jagi/meteor-astronomy#281]
**Model:**
```javascript
Entry = Astro.Class({
    name: 'Entry',
    collection: new Mongo.Collection('entries'),

    fields: {
        createdAt: 'date'
    }
});
```

**Angular Controller:**
```javascript
$scope.entries = Entry.find();
```

**View:**
```jade
 ul
    li(ng-repeat="entry in entries")
      | {{entry._id}}
```

But that produces complete senseless outputs (about 15 `<li>`s with no content). Angular seems to expect an array here and if I set `entries` to an array it acutally works like a charm.

What's the correct way to get this simple example running?

**Comment by jagi** [comment]
```js
$scope.entries = Entry.find().fetch();
```

**Comment by phortx** [comment]
Wow pretty simple solution despite I didn't find that advice anywhere else. Tried it, worked, this one is happy.

Thank you very much! :)

**Comment by jagi** [comment]
No problem :). It's not related with Astronomy but it's very common problem not only when working with Angular. The `find` method returns cursor which is not interateable by Angular because it requires just simple array.
