### ISSUE TITLE
Astronomy v2-rc Users collection migration

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#282]
I would like some help in converting users meteor class example to v2-rc compatible.

http://astronomy.jagi.io/examples

Somehow i keep getting errors, maybe i am doing something wrong. Can someone share a basic version i can work up from?

**Comment by jagi** [comment]
I haven't tested it yet but depending on the level of detail you want to provide you can do it in two ways.
**DETAILED:**
```js
UserProfile = Astro.Class.create({
  name: 'UserProfile',
  fields: {
    nickname: String
    /* Any other fields you want to be published to the client */
  }
});

UserEmail = Astro.Class.create({
	name: 'UserEmail',
	fields: {
		address: String,
		verified: Boolean
	}
});

User = Astro.Class.create({
  name: 'User',
  collection: Meteor.users,
  fields: {
    createdAt: Date,
    emails: [UserEmail],
    profile: UserProfile
  }
});

if (Meteor.isServer) {
  User.extend({
    fields: {
      services: Object
    }
  });
}
```
**SIMPLE:**
```js
User = Astro.Class.create({
  name: 'User',
  collection: Meteor.users,
  fields: {
    createdAt: Date,
    emails: [Object],
    profile: Object
  }
});

if (Meteor.isServer) {
  User.extend({
    fields: {
      services: Object
    }
  });
}
```

**Comment by talha-asad** [comment]
Thanks alot @jagi 
I'll give this a try and let you know how it goes.

I used to use ```Accounts.OnCreate``` hook to create an astro user and then return the raw version of it, so the users stored have the defaults i had in my astro class. Do i still need to do that with v2?

**Comment by talha-asad** [comment]
Your example works well, thanks alot. I recall that you said that Meteor.users will automatically start using Astronomy User Class from v2, is this still correct?

**Comment by jagi** [comment]
It's not so simple to do that automatically so you still need the `Accounts.OnCreate` hook for that. It's bad practise to mess with Meteor internals, so I'm leaving it to the user. You know the `Accounts` package has its own validation, it won't allow you to insert incorrect user. However, if you need extra validation layer then using the hook is a good option.

**Comment by talha-asad** [comment]
Okay thanks. I think that approach is good. Just wanted to make sure.
