### ISSUE TITLE
Don't change definitions

### ISSUE THREAD

**Issue by krizka** [jagi/meteor-astronomy#283]
Say, I have a field definition, like
`MeteorID = { type: String, validators: [{ type: 'regexp', param: /\w{17}/ }] }`
and then
```
Foo = Astro.Class.create({ 
  name: 'foo',
  fields: {
    foo: MeteorID,
    foo1: MeteorID
  }
});
```
The second field will be without validation. Because:
meteor-astronomy/lib/modules/validators/hooks/parse_definition.js:19 replaces original definition.
Maybe we have to clone the definition?

**Comment by jagi** [comment]
It may not be a good idea to clone original definition as it's very expensive operation. You would need copy of the all values also nested, so the best choice would be using `EJSON.clone` which I don't want to overuse. The best solution in your case would be:
```js
MeteorID = function() {
  return { type: String, validators: [{ type: 'regexp', param: /\w{17}/ }] };
};
Foo = Astro.Class.create({ 
  name: 'foo',
  fields: {
    foo: MeteorID(),
    foo1: MeteorID()
  }
});
```

**Comment by krizka** [comment]
Yeah, I thought about the solution you suggest. But It lead to hidden bugs, if will not be fixed. Anyway, it will be cloned once while initialisation, and it's not so costly for a tiny structure of 4 fields or less. Redux and Meteor doing it a lot.

**Comment by jagi** [comment]
Meteor is not using it in many places, mostly in DDP and MiniMongo packages. It's just to make sure that original data won't be modified and they are working with very simple structures. I'm not saying that I won't change how it works but I have to make conscious decision after making performance tests. It probably worth considering as it would only be cloned on page initialisation.

**Comment by krizka** [comment]
Sure I meant DDP. As it is the layer, heavily working with data.
Having chance, thank you for the Astronomy) It's great. And mostly I appreciate its cleanness and extendability.

**Comment by jagi** [comment]
With 3 simple classes it adds around 6-7 extra ms to initialisation which is not bad result. So I will release it with the next RC version, to get feedback from the community.

The solution is not using `EJSON.clone` and instead lodash `_.cloneDeepWith` where I'm cloning entire class definition and its every extension. It's deep cloning but sometime, some non simple javascript object may be cloned by reference. Let's take for example Mongo.Collection, its reference gets copied which of course is ok. But in some strange situations module/behavior developer will still be responsible for cloning non plain objects if need but I don't think it will be common situation.

**Comment by jagi** [comment]
I'm closing this issue for now. This feature will be available in the next RC version.
