### ISSUE TITLE
v2-rc automatic cast to number

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#286]
Given the following Astronomy Class:

```js
GeoJSONPoint = Astro.Class.create({
  name: 'GeoJSONPoint',
  fields: {
    type: {type: String, default: 'Point'},
    coordinates: {
      type: [Number], // [Longitude(x), Latitude(y)]
      default() { return [0.0, 0.0]; }
    }
  }
});
```

If I try inserting a number in string format for the coordinates field, astronomy throws. Shouldn't it just try to cast the string to number and only throw if it's a `NaN`?

**Comment by jagi** [comment]
There was already a topic about type casting and we came to conclusion that casting values is not a job for the model layer, it's a job for controller. Astronomy 2.0 does not have support for casting values. Casting is a big problem as developer may expect different outcome depending on the situation.

**Comment by talha-asad** [comment]
That seems a reasonable way to go about it. However i am confused, i was using upsert previously for this and it was casting strings into numbers. I am using new and than a save now.

**Comment by talha-asad** [comment]
@jagi Can this be achieved using a behaviour that runs before the internal validation runs? I think such a behaviour would also allow people to easily transition from 1.2 to 2.0.

**Comment by jagi** [comment]
Yes it can be a behavior or what would be even better a module. Hmm it may be good idea to create such module. I'm planning to release forms package with the support for casting. But Astronomy is the priority now. However, it shouldn't be hard to create a module you're talking about. I will add it to my TODO list.

**Comment by talha-asad** [comment]
Thanks jagi.
