### ISSUE TITLE
Astronomy v2 Class Inheritance

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#288]
Hi jagi,

I know you are very busy rolling out new features for v2. I just had this idea stuck in my head and wanted your opinion on this. In our case we have a Astro Class which we want to have a structure and fields if one of the fields has a particular value, and have another structure if that field has a different value.

I think this is not a very far fetched use case and is something that is very usable in mongodb in general. Do you think Astronomy should have something that supports this or do you think this is a task best dealt by a third party module?

In mongoose this is dealt with discriminators, and mongoose keeps an internal field which is `__t` i think. Would like to hear your thoughts on this.

A basic example would be like if you want to store all sorts of animals in one collection called `Animal`. And you could have some specific fields for each animal depending on the type of animal.

**Comment by jagi** [comment]
Hi,

If classes does not differ a lot I would suggest using inheritance. Create some base class that would have the same fields and two inherited classes that have extra fields that differ. When using inheritance you have to use the `typeField` property to define a "discriminator" field. Moreover, you can use the `resolveValue` field property to calculate field's value depending on the other field value.

I know that maybe it's not the best solution but for know the only available.

**Comment by talha-asad** [comment]
Seems like a good suggestion can you give like a minimal example, perhaps you could later show it as an example in the documentation as well. I think inheritance will work well enough for the use case and it is good enough.

**Comment by jagi** [comment]
http://astronomy.jagi.io/inheritance - however I've got information that it's broken in v2, so you can try it out and let me know.

**Comment by talha-asad** [comment]
The site seems to be down :(
I'll keep trying and let you know how it goes.

**Comment by talha-asad** [comment]
I am creating a base test case with the following:

```js
Animals = new Mongo.Collection('animals');

Animal = Astro.Class.create({
  name: 'Animal',
  collection: Animals,
  typeField: 'type',
  fields: {
    _id: {type: String, index: 1},
    name: {type: String}
  }
});

Dog = Animal.inherit({
  name: 'Dog',
  fields: {
    color: {type: String},
    breed: {type: String}
  }
});

Cat = Animal.inherit({
  name: 'Dog',
  fields: {
    owner: {type: String}
  }
});
```

Right now it's throwing this errror:

ReferenceError: typeField is not defined
W20160224-15:25:05.018(5)? (STDERR)     at lib/modules/storage/hooks/apply_definition.js:30:11
W20160224-15:25:05.018(5)? (STDERR)     at Module.Astro.Module.modules.storage.onApplyDefinition (lib/modules/storage/hooks/apply_definition.js:105:5)
W20160224-15:25:05.019(5)? (STDERR)     at lib/core/class/class.js:130:11
W20160224-15:25:05.019(5)? (STDERR)     at /Users/talhaasad/.meteor/packages/stevezhu_lodash/.3.10.1.xt9k8p++os+web.browser+web.cordova/npm/node_modules/lodash/index.js:3073:15
W20160224-15:25:05.019(5)? (STDERR)     at baseForOwn (/Users/talhaasad/.meteor/packages/stevezhu_lodash/.3.10.1.xt9k8p++os+web.browser+web.cordova/npm/node_modules/lodash/index.js:2046:14)
W20160224-15:25:05.019(5)? (STDERR)     at /Users/talhaasad/.meteor/packages/stevezhu_lodash/.3.10.1.xt9k8p++os+web.browser+web.cordova/npm/node_modules/lodash/index.js:3043:18
W20160224-15:25:05.019(5)? (STDERR)     at Function.<anonymous> (/Users/talhaasad/.meteor/packages/stevezhu_lodash/.3.10.1.xt9k8p++os+web.browser+web.cordova/npm/node_modules/lodash/index.js:3346:13)
W20160224-15:25:05.019(5)? (STDERR)     at Function.extend (lib/core/class/class.js:126:5)
W20160224-15:25:05.019(5)? (STDERR)     at Function.create (lib/core/class/class.js:95:9)
W20160224-15:25:05.020(5)? (STDERR)     at collections/animals.js:3:22
```

**Comment by jagi** [comment]
Ok I will check it out later today. It's probably some bug. Are you using Meteor 1.3 beta or 1.2?

**Comment by talha-asad** [comment]
I am on Meteor 1.2

**Comment by jagi** [comment]
I'm asking because new RC versions will probably be released for Meteor 1.3 only as I moved to ES2015 modules but they appeared to be not compatible with Meteor 1.2. Or maybe I will be able to figure out something to build modules into one file that could be included in Meteor 1.2

**Comment by talha-asad** [comment]
Hmm that will be a blocker, I'll see if i can upgrade the project to Meteor 1.3beta as well, however I think it will be easier said than done as they still have a lot of issues that need fixing too.

**Comment by jagi** [comment]
Yes I know it's a problem. I will have to figure something out to support Meteor 1.2. I moved to ES modules too early. It makes developing much easier and code base much cleaner so I don't want to move back. However, I will probably have to get astronomy package file that is getting built during meteor build and include it in a package for backward compatibility. I don't know if it's gonna work, so I have to test it.

**Comment by talha-asad** [comment]
It's understandable nobody likes to use old stuff ;)
I am sure you'll figure it out. A lot of module owners will have a similar concern too. Lets hope its an elegant solution :+1:

**Comment by jagi** [comment]
I've fixed a problem with the `typeField` property but still can't publish it as I'm waiting for information from MDG how to support Meteor 1.2 in packages made for Meteor 1.3 and using ES modules.

**Comment by jagi** [comment]
I'm closing this issue for now. This will be available in the next RC version.

**Comment by leosa83** [comment]
Hey @jagi 

Thanks for an awesome package :)

I just wanted to notify that this issue still exists for RC.7. I believe your latest comment was made for RC.6

Thanks

**Comment by jagi** [comment]
I will check it out before releasin rc8

**Comment by jagi** [comment]
It's working, check this out https://github.com/jagi/meteor-astronomy/issues/328
