### ISSUE TITLE
Strange Issue v2 and v1.2

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#289]
The below query seems to work fine when performed on `Meteor.collection` and fails when performed on `Astro Class`. This bug seems to be cross versions.

```js
User.update({_id: this.userId, 'someObject.id': 'xyz'}, {$set: {'someObject.$.default': true}});
```

Here `someObject` is an array of objects.

The error I get is this:
```bash
I20160224-19:46:09.648(5)? Exception while invoking method 'updateUserSettings' MinimongoError: The positional operator did not find the match needed from the query
I20160224-19:46:09.648(5)?     at MinimongoError (packages/minimongo/minimongo.js:44:1)
I20160224-19:46:09.648(5)?     at findModTarget (packages/minimongo/modify.js:129:1)
I20160224-19:46:09.648(5)?     at packages/minimongo/modify.js:66:1
I20160224-19:46:09.649(5)?     at Function.​_.each._​.forEach (packages/underscore/underscore.js:113:1)
I20160224-19:46:09.649(5)?     at packages/minimongo/modify.js:47:1
I20160224-19:46:09.649(5)?     at Function.​_.each._​.forEach (packages/underscore/underscore.js:113:1)
I20160224-19:46:09.650(5)?     at Function.LocalCollection._modify (packages/minimongo/modify.js:40:1)
I20160224-19:46:09.650(5)?     at Object.Astro.utils.storage.applyModifier (lib/modules/storage/utils/apply_modifier.js:6:18)
I20160224-19:46:09.650(5)?     at lib/modules/storage/utils/class_update.js:31:23
I20160224-19:46:09.650(5)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
I20160224-19:46:09.651(5)?     at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
I20160224-19:46:09.651(5)?     at Object.Astro.utils.storage.classUpdate (lib/modules/storage/utils/class_update.js:29:7)
I20160224-19:46:09.651(5)?     at Function.methods.update (lib/modules/storage/class_static_methods/update.js:58:37)
I20160224-19:46:09.652(5)?     at [object Object].Meteor.methods.updateUserSettings (server/methods/common_methods.js:154:10)
```

```server/methods/common_methods.js:154``` is the line of this query. I have no idea why its mentioning `Minimongo` as this is a server only method and this query is running on the server-side.

**Comment by jagi** [comment]
Right it's a bug. The positional operator requires selector that matches operator. And even when you pass correct selector I'm not using it to modify document's fields. I have to figure out some workaround for that. For now I would recommend using the collection level update method.

**Comment by jagi** [comment]
Ok I've fixed it. However, I still need to make next RC version compatible with Meteor 1.2.

It was throwing an error in the Minimongo package even when it was used on the server because I'm using some Minimongo methods to mimic how MongoDB works. MDG did a great job on creating client side Mongo version, so I didn't want to rewrite everything and I'm just using what they've done. I've just missed this one function responsible for the projection operator.

**Comment by jagi** [comment]
I'm closing this issue for now. This will be available in the next RC version.

**Comment by talha-asad** [comment]
Thanks jagi.
