### ISSUE TITLE
Astronomy v2 Questions

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#290]
If I setup behaviours on Classes that are used inside another Class, do they trigger when the parent Class is changed? Do they trigger only when the elements of that subclass are changed? Let's take timestamp behavior for example.

If i use `Class.update` and update a bunch of properties, will this trigger behaviors?

I am going to write some test cases for these and let you know how this goes, but would like to know how these are planned at the moment so I can structure my project accordingly. Some insight about these questions will be very helpful.

**Comment by jagi** [comment]
Everything depends on an events being used. The storage events like `beforeSave`, `beforeUpdate`, `beforeRemove` are propagated down to all nested classes. So if you have the `User` class that has the `address` field being an instance of the `Address` class, then the `beforeUpdate` event will be propagated also to the address field and all the `Address.beforeUpdate` events will be triggered on an address field. And the `timestamp` behavior is using `beforeInsert` and `beforeUpdate` events to set `createdAt` and `updatedAt` fields. So if you attach behavior to the `Address` class it will be run on a user save.

**Comment by talha-asad** [comment]
Okay that seems perfect.
