### ISSUE TITLE
V 2.0 Bugs: Unneeded validation & Date validation Issue

### ISSUE THREAD

**Issue by zleman1593** [jagi/meteor-astronomy#291]
**I am using 2.0.0-rc.6 (cloned from V2 repo)**

I have come across two unexpected situations from the below code, resulting in the following error:

```
[ { type: 'date',
I20160225-18:54:17.651(-8)?        name: 'dateShared',
I20160225-18:54:17.651(-8)?        value: '2016-02-25T19:23:40.970Z',
I20160225-18:54:17.651(-8)?        param: undefined,
I20160225-18:54:17.651(-8)?        error: '"dateShared" has to be a date',
I20160225-18:54:17.651(-8)?        pattern: 'dateShared' } ],
I20160225-18:54:17.651(-8)?   message: '"dateShared" has to be a date [validation-error]',
I20160225-18:54:17.651(-8)?   errorType: 'Meteor.Error' }
``` 
**First**, I am manually updating documents in the "Shares" collection because I don't think save() has the ability to update the same field in multiple documents with one mongo query. If any validation is happening, I would expect the 'used' field to be checked to make sure it is being set to a boolean. I would not expect other fields to be checked because nothing else is being changed and there are  no fields to check besides what is provided in the explicit query. So it seems strange that the error is in regards to another field not include din the query.

**Second** Regardless of what is being validated above, some object from the shares array (see third code block) is being validated due to the query and the 'dateShared' field is not being recognized as a date. The objects returned from Share.find were previously validated and added to the collection so it seems strange that that unchanged field is triggering an error. The value stored in this field in mongo looks like '2016-02-25T19:23:40.970Z', a string, which apparently doesn't pass the lodash, _.isDate().

```

 const Share = Astro.Class.create({
  name: 'Share',
  collection: Shares,
  fields: {
    userId: {
      type: String,
    },
    contentId: {
      type: String,
    },
     dateShared: {
      type: Date,
    },
    groupId: {
      type: String,
      optional: true
    },
    toUserId: {
      type: String,
    },
     used: {
      type: Boolean,
    },
  }
});
```

```
 getShares() {
    const shares = Share.find({
      toUserId: this.userId,
      used: false
    }, {
      transform: null
    }).fetch();

    Share.update({
      _id: {
        $in: _.map(shares, '_id')
      }
    }, {
      $set: {
        used: true
      }
    });
    return shares;
  };
```

**Comment by jagi** [comment]
If it's throwing a validation error so the field had to be changed. And that's probably because of saving the date as string not date object. You can update multiple objects and have validation. Try `Share.update()` method.

**Comment by zleman1593** [comment]
@jagi Ok. How do I prevent the date from saving as a string and instead save as a date object?  I am currently doing the below, which I thought should save a date object in the DB.
```
const share = new Share();
//set other fields
share.dateShared =  new Date();
 share.save();
```
 In regards to the first issue, what object is being validated leading to the error? In the update method I just specify some documents based on id's and one field to be set in each, so there is no date field to even be validated.

**Comment by jagi** [comment]
Are you sure that you're schema is:
```js
Share = Astro.Class.create({
  name: 'Share',
  collection: Shares,
  fields: {
    dateShared: {
      type: Date
    }
  }
});
```
and that after running this code:
```js
const share = new Share();
share.dateShared = new Date();
share.save();
```
you end up saving string instead of date? Check that using `meteor mongo`. You other code is probably messing with the `dateShare` field and is modifying it by accident. If it's still not saved properly, then create reproduction repository showing that problem.
