### ISSUE TITLE
Question: Collection Helpers

### ISSUE THREAD

**Issue by KyleKing** [jagi/meteor-astronomy#292]
Hi! I just transitioned to Astronomy and it is really awesome! Thank you for building and supporting it

I am having some trouble figuring out the transform function to replace dburles:collection-helpers. I want to be able to create a virtual field with a pretty timestamp (i.e. 'Sun, 28 Feb 2016 01:16:34' instead of 1456622194). Currently, I create the field based on the user's locale with collection-helpers, but I don't know how to do that with Astronomy?

For example:
```coffee
BikeData.helpers
  Timestamp: ->
    DateFormats =
      shortest: 'hh:mm:ss a'
      short: 'hh:mm:ss a M-D-YY'
      long: 'dddd DD.MM.YYYY hh:mm:ss a'
    # UI.registerHelper 'formatDate', (@Positions[0].Timestamp, format) ->
    if moment
      format = 'shortest'
      # can use other formats like 'lll' too
      format = DateFormats[format] or format
      moment(@Positions[0].Timestamp).format format
    else
      @Positions[0].Timestamp
```

I saw the docs and looked around through issues and other guides, but couldn't find any good  examples to get started with

**Comment by jagi** [comment]
But what's the problem?

**Comment by KyleKing** [comment]
No problem, I just have a question about documentation and how to use the transform functions

**Comment by KyleKing** [comment]
Actually figured it all out, I was just overthinking it

**Comment by jagi** [comment]
Ok good :)
