### ISSUE TITLE
Publications with restricted fields

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#293]
Hello.

I'm wondering if I got this right:

Let's say I have a schema with Astronomy for a 'Document' that has lots of things specified, dates, titles whatever, and I also use Astronomy's validation on these fields. All documents have all the required fields in the database and therefore are valid.

I want to to publish a part of these document's properties:

```
Meteor.publish('documents', function() {
    return Documents.find({}, {
        fields:
               {
                    title: 1
               }
    });
}

```

now, on the client, I wish to change the title of a document I have in my subscription:

```
if (Meteor.isClient) {
    const doc = Documents.findOne();
    doc.set({
         title: 'new title'
     });
    Documents.methods.update.call({ doc: doc});
}
```

and in the Meteor method, I just check if doc.validate() succeeds and try to save it. However, I will get error about missing fields, that are defined in the Astronomy schema.

I would like to hear, that it's possible to only validate & update the part that is present in the object and published by the server. Is it possible? Sorry if this is a stupid question, I tried looking at the documentation, examples and github issues but couldn't find an answer.

**Comment by jagi** [comment]
You can do that. Check the last paragraph here: http://astronomy.jagi.io/saving

**Comment by arggh** [comment]
I swear I spent an hour searching the docs for this and missed it. I have to get my eyes checked. Thank you for super fast reply, awesome project. I hope you get v2.0 going soon :+1:

**Comment by jagi** [comment]
No problem. Thanks!
