### ISSUE TITLE
Unable to set value of nested field with default value (if Timestamp behavior is used)

### ISSUE THREAD

**Issue by willrbc** [jagi/meteor-astronomy#294]
I'm having a strange issue when a field in a nested class has a default value.

In my reproduction repo you can see it working.  The issue is happens when you try to set the value of the field to it's default value. So if default is 1, then you can successfully set the value to any other number, but when you set it back to 1 again, the modifier is lost somewhere. I have looked at the DDP logs and it never reaches the database. I've traced it all through the Astronomy library of code and I can't quite pinpoint where it loses the modifier. It's fine if you remove the timestamp behavior, although I imagine that if you have any other 'beforeUpdate' events making changes, it might have a similar issue.

**Comment by jagi** [comment]
I don't have time to investigate your code in details but this feature works. There is something else that is causing something like resaving a document with default value. In the first run document correctly detects changes but later (probably some reactivity) is overriding it.

**Comment by willrbc** [comment]
Okay I appreciate you are very busy with 2.0 launch.  I will keep trying to find the cause, it appears to be happen somewhere around the updatedAt field being triggered.

**Comment by willrbc** [comment]
Found the culprit!!!!

I did some further digging and noticed that anything calling the `getModified()` was the problem.

I believe it's the `_clearUnnecessaryModifiers` function as the cause.

It finds the originalDoc from the database and then compares it field by field with the _modifiers and removes any no longer necessary.  If the field is a nested class object or array it calls itself with each nested class. When it looks for an `_id` or `Collection`, naturally it can't find one so it uses a freshly initialised document as comparison.  This is why it clears the _modifiers when a default value is set.  If default is 1 and you are trying to set that field to 1 then it thinks the modifier is unnecessary and clears it. It doesn't know what the value in the database looks like so it shouldn't have the authority to clear these modifiers.

I hope this makes sense,  I would suggest that it is unnecessary to run the function on nested fields with no _id as all modifiers will be necessary.  What do you think?


````javascript
proto._clearUnnecessaryModifiers = function() {
  old = old || false;
  var doc = this;
  var Class = doc.constructor;

  if (doc._id && Class.getCollection()) {
    var originalDoc = Class.findOne(doc._id);
  } else {
    var originalDoc = new Class();
  }

  var modified = {};

  var fields = Class.getFields();
  _.each(fields, function(field, fieldName) {
    if (field.transient) {
      return;
    }
    if (
      field instanceof Astro.fields.object &&
      field.class &&
      doc[fieldName] instanceof Astro.BaseClass
    ) {
      // Get a nested document.
      var nestedDoc = doc[fieldName];
      // Clear modifiers.
      nestedDoc._clearUnnecessaryModifiers();
    } else if (field instanceof Astro.fields.array && field.class) {
      // Get nested documents.
      var nestedDocs = doc[fieldName];
      _.each(nestedDocs, function(nestedDoc, nestedDocIndex) {
        // Clear modifiers.
        nestedDoc._clearUnnecessaryModifiers();
      });
    } else {
      if (EJSON.equals(originalDoc[fieldName], doc[fieldName])) {
        _.each(modifiersList, function(modifierName) {
          if (
            doc._modifiers[modifierName] &&
            _.has(doc._modifiers[modifierName], fieldName)
          ) {
            delete doc._modifiers[modifierName][fieldName];
            if (_.size(doc._modifiers[modifierName]) === 0) {
              delete doc._modifiers[modifierName];
            }
          }
        });
      }
    }
  });

  return modified;
};
````

**Comment by jagi** [comment]
I will take a look at it in the free time

**Comment by willrbc** [comment]
I've modified it myself to see if this could work as a fix.  Basically I pass a copy of the originalDoc's nested class field into the function so that it compares to that instead of compare to a blank new Class() document.
