### ISSUE TITLE
Documentation Site Down

### ISSUE THREAD

**Issue by maxmatthews** [jagi/meteor-astronomy#295]
Documentation appears to be down. @jagi have you released a new version that possibly had a glitch in it, or is Meteor hosting just down?
~Max

**Comment by maxmatthews** [comment]
Because Jagi is awesome, you can just clone/download this repo and run the meteor project to access the doc's locally: https://github.com/jagi/meteor-astronomy-docs until the site is back online

**Comment by jagi** [comment]
@maxmatthews I haven't been doing anything to the documentation. It's the problem with free Meteor hosting which is not perfect. I'm gonna move entire documentation for 1.x and 2.0 to the different website. I haven't chosen what service I will use but maybe readme.io. I have to test a few different solutions.

And yes, you can use docs repo in cases where the docs website is down. Moving to another service will make it more reliable.

**Comment by maxmatthews** [comment]
Awesome. I was happy when I found the github repo as a good offline backup. Thanks again for all the awesome work you do. Really excited about 2.0!

**Comment by jagi** [comment]
:)
