### ISSUE TITLE
Docs site is down :(

### ISSUE THREAD

**Issue by dgroch** [jagi/meteor-astronomy#296]
![image](https://cloud.githubusercontent.com/assets/2666385/13473597/1c52e73c-e10e-11e5-8564-19ec83702558.png)

**Comment by dnish** [comment]
Seems to be a problem on all free deployments, http://viewmodel.meteor.com is also down. Think we have to wait until we have access to all docs again :D

**Comment by jagi** [comment]
Yes it's some problem with Meteor server. For now I propose going here https://github.com/jagi/meteor-astronomy-docs/tree/master/docs and read docs directly from the .md files. On Astronomy 2.0 release I'm planning to move documentation to another service.

**Comment by ClarenceL** [comment]
What luck, I just discovered this and it's down!

**Comment by ClarenceL** [comment]
Oh wait, thanks for that link, I just cloned that doc app and ran it locally.

**Comment by jagi** [comment]
Temporarily documentation for v1 is located under this address: http://jagi.github.io/meteor-astronomy/v1 - it's not "recovered" entirely yet. Probably, it will be available tomorrow.
