### ISSUE TITLE
ReactiveMap for each transformed document

### ISSUE THREAD

**Issue by krizka** [jagi/meteor-astronomy#297]
Do we really need to create new ReactiveMap for _errors property for each Transformed document? Even if it is not verified or have any errors yet. For server too.

**Comment by jagi** [comment]
It's removed in Astronomy 2.0 it will be a choice of user to add additional module for that.

**Comment by krizka** [comment]
Is it means, that this field will still appear for every object if I will add astronomy-validators package?

**Comment by jagi** [comment]
The validators package won't work with Astronomy 2.0. It will be build in module into Astronomy 2.0 but without the `_error` object per document. However there will be a package called `jagi:astronomy-errors` that will allow storing reactive errors in a document.

**Comment by krizka** [comment]
Yes, I totally understand what are you talking about. The one thing to be sure: will it be optional and omitted (even if we add `jagi:astronomy-errors` package) until any errors check will be done? (sorry, its a bit hard to be clear in english for me)

**Comment by jagi** [comment]
Oh ok, so you mean that you would want to not have the `_erros` reactive map for each document even when you add `jagi:astronomy-errors` pacakge? And only to have such reactive map if there are actual errors?

I can understand that you wouldn't want to have a document polluted with extra private properties. And I can think about moving the `_errors` object out of the document.

**Comment by krizka** [comment]
Will be great! Thanks!

**Comment by jagi** [comment]
Ok so I will store it outside of the document. In deed it may be a better idea.
