### ISSUE TITLE
What is the right way to apply transformations to Meteor.user() ?

### ISSUE THREAD

**Issue by krizka** [jagi/meteor-astronomy#298]

**Comment by jagi** [comment]
What Astronomy version?

**Comment by krizka** [comment]
v2

**Comment by jagi** [comment]
Hmm unfortunately Meteor does not have an easy way of attaching transform function to already created collections. If it goes about Meteor.users you can do something like this:
```js
var transform = Astro.Module.modules.storage.utils.transformToClass('User');
Meteor.users.find(selector, { transform: transform });
```
Which is not perfect and I will probably introduce some easy way of doing it. You can also do it permanently for all Meteor.users and Meteor.user():
```js
var transform = Astro.Module.modules.storage.utils.transformToClass('User');
Meteor.users._transform = Package.minimongo.LocalCollection.wrapTransform(transform);
```
But why at all use the transform function on Meteor.users and Meteor.user. You can use the Astronomy User class that you've created.
```js
User.find();
// is the same like (but with transformation)
Meteor.users.find();
```
and for single user
```js
var user = User.findOne(Meteor.userId());
```

**Comment by krizka** [comment]
@jagi thanks for the detailed answer.
The question was related to fact that now Im refactoring from using SimpleSchema and collection-helpers to Astronomy. And searched the easy way to not touch Meteor.user() and Meteor.users.find at all.
I tried this before asking:
```
var transform = Astro.Module.modules.storage.utils.transformToClass('User');
Meteor.users._transform = Package.minimongo.LocalCollection.wrapTransform(transform);
```
but it is introduces problems with fast-render. Which is strange too and looked as a bug in fast-render itself. As I think, it have to be working the same as regular subscribe, which is not applying transform (What do you think, @arunoda ?).

Ok. then I'll refactor all to use User class directly if needed.

**Comment by minfawang** [comment]
@krizka Are you getting some similar error like [this one](https://github.com/kadirahq/fast-render/issues/102#issuecomment-189048765)? I found that when I do server side transformation on Meteor.users collection this error will throw. And the error is gone when I comment out that part.

**Comment by krizka** [comment]
@minfawang Yeah, exactly

**Comment by jagi** [comment]
Most packages assume that documents coming from `Meteor.users` or `Meteor.user` are plain JSON objects and when you used Astronomy 1.x it might introduce some errors because of such assumption. So that's why in Astronomy 2.0 by default I'm not transforming documents coming from collections. Instead you should use `Class.find` to get transformed documents.

**Comment by krizka** [comment]
It's great decision to not transform collection objects by default! Fully agree with that.
Think it may be closed for now. Please add some notice of this to the docs in the future.

**Comment by jagi** [comment]
Yes definitely I will add information about that. You know in 1.x I thought that it will not cause any problems but after many issues about incompatibility with some packages I've realised that it's better to leave collections as they are :). Ok so closing it for now
