### ISSUE TITLE
Working with $exists

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#299]
Hey,
I'm running into some trouble with Astronomys way to handle optional fields. Astronomy generates a null value, if an optional field isn't set. The problem here is that it collides with my database logic. So for example I'm searching for all unanswered questions:

    Meteor.publishComposite("unanswered", function() {
    return {
        find: function() {
            return Questions.find({answered:{$exists:false}},{limit:1});
        }
    }
    });

Good, this one publishes 1 unasked question. Now I'm trying to catch it on the client side:

      if(this.subReady()){
           return Questions.find({answered: {"$exists": false}});
       }

This one returns nothing, because "answered" has the value null. So I have to do the following:

      if(this.subReady()){
           return Questions.find({answered: null});
       }

To maintain the same logic, I've tried to change my publication to this one:

    Meteor.publishComposite("unanswered", function() {
    return {
        find: function() {
            return Questions.find({answered:false},{limit:1,transform:null});
        }
    }
    });

But this returns nothing, I think here we use the plain Mongo object?

Is there any option to force Astronomy not to add the optional property when it isn't available? It feels a little bit uncomfortable to remember that answered isn't a real database value while we've to remember that {answered:false} on publish methods will not work.

**Comment by jagi** [comment]
I know about that problem and it's already fixed in 2.0 but not published yet. I'm not gonna change how it works in 1.0. But release of a new version is close, so I would encourage you to wait a little bit.
