### ISSUE TITLE
Behaviors appear to not be working at all for me :/

### ISSUE THREAD

**Issue by willrbc** [jagi/meteor-astronomy#30]
I am quite new to meteor and I am playing with setting up models for a new project and I'm using the timestamp as well as some customer behaviours. At the moment  I'm specifically using behaviours to add groups of fields to models that will be re-used in a few different models,  for example address fields.

````javascript
Astro.createBehavior({
    name: 'addresses',
    events: {
        addbehavior: function(behaviorData) {
            var Class = this;

            // Add fields to the Class.
            Class.addFields({
                'addresses': {
                    type: 'array',
                    default: []
                },
                'addresses.$': {
                    type: 'object',
                    default: {}
                },
                'addresses.$.name': 'string',
                'addresses.$.street': 'string',
                'addresses.$.town': 'string',
                'addresses.$.postcode': 'string',
                'addresses.$.country': 'string',
                'addresses.$.isDefault': 'boolean',
                'addresses.$.isBilling': 'boolean',
                'addresses.$.isShipping': 'boolean'
            });
        },
        initclass: function(schemaDefinition) {},
        initinstance: function(attrs) {}
    }
});
````

I have a customer class which implements the addresses and timestamp behaviours.

````javascript
Customers = new Mongo.Collection('Customers');

Customer = Astro.Class({
    name: 'Customer',
    collection: Customers,
    transform: true,
    fields: {
        company: {
            type: 'string'
        }
    },
    behaviours: ['addresses', 'timestamp'],
    relations: {
        Quotes: {
            type: 'many',
            class: 'Quote',
            local: '_id',
            foreign: 'customerId'
        },
        Contacts: {
            type: 'many',
            class: 'Contact',
            local: '_id',
            foreign: 'customerId'
        }
    }
})
````

I am simply adding a quick customer on the server side at startup.

````javascript
Meteor.startup(function() {
    Customers.remove({});
    cust = new Customer();
    cust.company = "Acme Cafe Ltd";
    cust.set('addresses.0', {
        name: "Cafe",
        street: "The Esplanade"
    });
    cust.save();
});
````

However the document thats created in Mongo has no createdAt or address fields,  I do have the additional modules installed in the packages file.

What am I doing wrong?  I don't see any errors and the 'just' object validates.

Many thanks for a great package,  I hope I can get this working well.

**Comment by jagi** [comment]
You have a typo :). Instead
`behaviours: ['addresses', 'timestamp']`
you should write:
`behaviors: ['addresses', 'timestamp']`
The problem is a letter **u** :)

I've noticed that many people are using British English form **behaviours** instead American English **behaviors**. I'm thinking about allowing both forms, or just printing some warning in the console.

**Comment by willrbc** [comment]
I did notice that discrepancy everywhere accept where it counts. Thank you! :)

**Comment by jagi** [comment]
No problem :)
