### ISSUE TITLE
v2.0 allow/deny rules are not being followed

### ISSUE THREAD

**Issue by marbemac** [jagi/meteor-astronomy#300]
I am able to save on the client, even though no allow/deny rules are defined. According to the meteor docs, at least one allow rule must return for the given collection true in order for a client-side database mutation to work. 

http://docs.meteor.com/#/full/allow

Basically, the default is to not allow client-side mutations, unless the user has specifically allowed it.

This is respected in astronomy 1.

**Comment by jagi** [comment]
In Astronomy 2.0 allow/deny rules are not taken into account at all. `Class.insert` and `Collection.insert` are not the same. Only API is the same. They work by using validation rules. Even MDG does not recommend using allow/deny rules.

**Comment by talha-asad** [comment]
Jagi, can you explain this a bit, i know it might be time consuming but i think this can later be added to the documentation.

**Comment by jagi** [comment]
There's no need for allow/deny rules at all. In all Meteor versions you can perform security check in the meteor method. As Astronomy 2.0 is using meteor methods internally so you can put all security checks in the beforeSave/beforeUpdate/beforeRemove events, the same way as you would do it in allow/deny rules. If you want to use Meteor methods directly then you can just put your code in such method and perform additional checks.

**Comment by jagi** [comment]
```js
// PURE METEOR.
Collection.allow({
  insert(userId, doc) {
  },
  update(userId, doc, fieldNames, modifier) {
  },
  remove(userId, doc) {
  }
});

// ASTRONOMY 2.0.
beforeInsert(/* userId, doc */) {
  let userId = Meteor.userId();
  let doc = this;
}

beforeUpdate(/* userId, doc, fieldNames, modifier */) {
  let userId = Meteor.userId();
  let doc = this;
  let fieldNames = this.getModified(); // It also includes modified nested fields.
  let getModifier = this.getModifier(); // NOT YET WORKING BUT WILL.
}

beforeRemove(/* userId, doc */) {
  let userId = Meteor.userId();
  let doc = this;
}
```

**Comment by talha-asad** [comment]
Thanks jagi.

**Comment by jagi** [comment]
And one more thing. If you want to do something like not allowing any operation from the client you can use the `trusted` event's property.

```js
beforeSave(e) {
  if (!e.trusted) {
    throw new Meteor.Error('not-allowed', 'Not allowed from the client!');
  }
}
```

**Comment by marbemac** [comment]
Thanks for the explanation - imho this should be put in bold text at the top of the migration guide, or somewhere visible. While a small change, it leads to a potentially large security hole for people who already use Meteor methods and rely on allow/deny to prevent astronomy client side saves.

We are already using Meteor methods for everything. So is the recommended approach to add that if (!e.trusted) logic to each model's beforeSave, or will there be a different way in the future? Thanks!

**Comment by jagi** [comment]
Yes there will definitely be a big security section describing everything in details. Yes I know it can lead to potential security holes. Even today I've experienced a new problem with Astronomy and Meteor that may cause security holes if a developer has not enough knowledge what's going on in the Astronomy and Meteor. So I will describe everything in details.

Yes I think you should add the `!e.trusted` to all methods. It won't change. The question is, are your methods defined only on the server or also on the client?

**Comment by CoveTechnologyAus** [comment]
@jagi I am looking at the securing of updating records and was wondering about these lines in your example above
```
if (userId === 'notAllowedUserId') {
        throw new Meteor.Error('not-allowed', 'Some error message');
      }
```

If I wanted to lock down editing user profiles to say, an admin user. how do i do something like the following from inside my Astronomy User class.

```
beforeUpdate(e) {
      let theUser = User.findOne(Meteor.userId());
      let usergroup = theUser.group;

      if (usergroup != 'administrators') {
        throw new Meteor.Error('not-allowed', 'you are not an admin!');
      }
      ...
    },
```

I hope that makes sense...

**Comment by CoveTechnologyAus** [comment]
Ahh, figured it out, I didn't fully realize you can just make standard Meteor calls from within Astronomy events. Not sure if this is the best way (open to suggestions) but this seemed to have worked.

```
 beforeUpdate(e) {
     let isUserAdmin = false;
      Meteor.call('isAdmin',Meteor.userId(),(err,isAdmin) => {
            if (err) {
              console.log(err);
            }

            isUserAdmin = isAdmin
          });
          ....
```

**Comment by jagi** [comment]
@CoveTechnologyAus The first approach is correct, the second one is wrong. You shouldn't be doing asynchronous calls inside events. Event will finish execution before method returns.

**Comment by JasonWeise** [comment]
@jagi thanks for the feedback, I had tried to work with the first approach but I cannot seem to get access to the User class from within the User class to get the isAdmin field of the current user. (That sounds really confusing when I read it back).

so for example neither of these work from within the User class to get access to fields of the currently logged in user.
``` 
beforeUpdate(e) {
    var currentUser =  User.findOne(Meteor.userId())
    if(currentUser.isAdmin){....}
    ...
 ```
or
``` 
beforeUpdate(e) {
   var currentUser = this.findOne(Meteor.userId()) 
   if(currentUser.isAdmin){....}
   ...
```

I really think I am missing something here.

**Comment by jagi** [comment]
In events the `this` context is attached to the original function context. You shouldn't use it if you haven't bound it by purpose. You have to debug your code:
1. Check if `Meteor.userId()` is not empty
2. Check what value is in `currentUser`
3. Check what value is in `currentUser.isAdmin`
Just use `console.log` and you will know where is a problem

**Comment by JasonWeise** [comment]
@yagi .. thanks so much for your time to respond, sometimes you just need a push in the right direction.
I have it working now, I was really just overthinking it, I sincerely appreciate your help.

**Comment by jagi** [comment]
No problem :)

**Comment by marbemac** [comment]
@jagi Would you consider a pull request for a "protected" field option? ie:

```
membershipPlan: {
    type: Plan,
    protected: !Meteor.isServer,
    default: function() {
        return {};
    }
}
```

Similar to immutable, but can never be written (even for new models on create). So basically, the user cannot overwrite the default value on initial creation (which they can with immutable).

**Comment by jagi** [comment]
@marbemac yes I can consider introducing such field property :). But I would just like to know a use case that would require this.

**Comment by marbemac** [comment]
Right now we have to explicitly protect certain fields from the user, by overwriting them with their defaults (or other values) in the beforeInsert event. Think fields like "owner", "credit_card", "plan", "project", "logs", "version", etc. We can use immutable to protect fields like this, but it only works after the field has been set once (so for updates). For inserts, unless we overwrite again with our own values in beforeInsert, the user can set them to whatever they want.

**Comment by jagi** [comment]
Yes you're right, we should have such feature. Right now we need to duplicate our code or just not use default values and override any value in the `beforeInsert` event with the values that we want to set. I'm just thinking about the best solution to this problem.

I don't know if the `protected` keyword is the best to describe this feature but maybe there is no other word that would fit better. It's definitely correct word from the business/logic point of view. It protects a field from being anything else than X.

When you think about it in technical term, it's rather more like `forcing default value` on insert. However, default values also work on update. So if we unset some field and later try to save a doc again it will store default value again. Anything that would be named as `forcing default value` would also have to work on update. I don't know if that fits in this case.

Anyway you would still have to use it in conjunction with the `immutable` property (in your case) if you don't want that field to be changed. However, what should happen if the `immutable` property is not set?

Here are my propositions:
1.
```js
creditCardNumber: {
  type: Number,
  default: function() { /* ... */ },
  immutable: true,
  forceDefault: true
}
```
2.
```js
creditCardNumber: {
  type: Number,
  immutable: true,
  forceValue: function() { /* ... */ }
}
```
3.
```js
creditCardNumber: {
  type: Number,
  immutable: true,
  set: function(val) { /* You can do here something with a value before setting */ }
}
```
What do you think? Or maybe `protected`? :P

**Comment by marbemac** [comment]
Yup! We're basically forcing the default on insert. For that purpose, I think option 1 is the best, but as you say it's a bit misleading in that we don't force default always.

Now that I think about it, perhaps the most flexible option would be a property that only allows the field to be changed/set when "trusted" is true. For this, "protected" might be a good property name after all :). That way, the property could still be updated from trusted sever code, and by astronomy itself (for the setting of the default value). It would accomplish the same as below, but explicitly, without the user having to figure out how to combine the various properties in the right way to secure their fields.

```js
creditCardNumber: {
  type: Number,
  default: function() { /* ... */ },
  immutable: !Meteor.isServer,
  forceDefaultOnInsert: true
}
```

In general, Astronomy 2 is great, but I am noticing that it will be MUCH easier for people to have security issues, so addressing it head on with explicit properties like "trusted" (which you already have) and "protected" would really help. 

Protected might also make sense at the root level of a model, so that people can easily secure their models and handle security some other way if they want. This also applies to models like "PaymentPlan" that should never be inserted/updated by the user. Of course, you could put the logic below in your before save, but again, addressing security explicitly seems like a good idea to me.

```js
beforeSave(e) {
    if (!e.trusted) {
        throw new Meteor.Error('not-allowed');
    }
}
```

**Comment by jagi** [comment]
I like the idea of the `protected` property as the property that can only be changed when it's trusted, method called from the server. That way it would not set any value when on the client (any value from the client would just be ignored) and value would be set on the server. I think that should fit your needs

**Comment by marbemac** [comment]
Yup, that would be perfect.

**Comment by jagi** [comment]
Ok, good. I will add this feature in 2 weeks. As I said I won't be available now. Adding this to the tasks list.

**Comment by krizka** [comment]
Hello, @jagi, @marbemac! Im agree with Marc and strongly recommend  you to make security follow the opt-out model, the same as Meteor do with allow/deny. And only allow data change if user allowed it explicitly. Any other models(like checking if it allowed in beforeSave, and allow if beforeSave not present) will lead to huge security problems for people not digging deeply into the topic. Like me, before I read this thread. I didn't realize, that I can change and insert data through Astronomy objects. Though Im not a novice in data security.

**Comment by marbemac** [comment]
Yeah.. I'm afraid that even with the best documentation in the world, the "allow" by default is going to lead to many insecure apps.

**Comment by jagi** [comment]
Ok I will rethink security model when I'm back from vacations

**Comment by marbemac** [comment]
Sounds good - enjoy your vacation!

**Comment by jagi** [comment]
Thanks :-)

**Comment by lukejagodzinski** [comment]
Closing this issue because I'm preparing to release 2.0
