### ISSUE TITLE
Browser refresh throws DPP Error - Astronomy is not defined

### ISSUE THREAD

**Issue by CoveTechnologyAus** [jagi/meteor-astronomy#302]
I have found a really strange issue whereby if I reload a page (with the browser's reload button) or HMR reloads a page the following error is thrown in the browser console and no further data is available. 
I am using the most recent Astronomy 2.0 build as a local package with Meteor 1.3-beta12, could this be causing an issue whereby DDP is initializing before Astronomy is ready?

```
Exception while parsing DDP Error: Custom EJSON type Astronomy is not defined
    at Object.builtinConverters.fromJSONValue (http://localhost:3000/packages/ejson.js?hash=17e8fd94f8ed7ed07b88c94baa4d5fc8b80a8946:205:15)
    at fromJSONValueHelper (http://localhost:3000/packages/ejson.js?hash=17e8fd94f8ed7ed07b88c94baa4d5fc8b80a8946:334:28)
    at http://localhost:3000/packages/ejson.js?hash=17e8fd94f8ed7ed07b88c94baa4d5fc8b80a8946:307:21
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:157:22)
    at Object.EJSON._adjustTypesFromJSONValue (http://localhost:3000/packages/ejson.js?hash=17e8fd94f8ed7ed07b88c94baa4d5fc8b80a8946:305:5)
    at http://localhost:3000/packages/ddp-common.js?hash=5feeb4319649347951960f7aa7630ef2c77e22b4:212:26
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:149:11)
    at Object.DDPCommon.parseDDP (http://localhost:3000/packages/ddp-common.js?hash=5feeb4319649347951960f7aa7630ef2c77e22b4:210:5)
    at onMessage (http://localhost:3000/packages/ddp-client.js?hash=67ef784978f8a931afd6cded99a0f59b8f72a9e4:3321:27)
```

**Comment by CoveTechnologyAus** [comment]
As an update, I have discovered that this only occurs in Meteor develop mode and when I run ```meteor --production``` the error doesn't occur and everything is sweet.

I am using Meteor 1.3-beta12 with MantraJS and Webpack (with HMR).. I have a feeling the error I originally posted about has more to do with my develop environment than Astronomy itself.

@jagi  Any thoughts or should I just close this one?

**Comment by jagi** [comment]
It's strange because the stack trace is showing only meteor files and no custom project files. Which seems to be like a problem with HMR or just webpack. I've never experience this problem but it would be nice to know what is causing it so I could write about it in the documentation.

**Comment by ArthurGerbelot** [comment]
Humm... I got the same error, and i found my problem.
On the Database I saved Astronomy object like :

```
"emails" : [
                {
                        "EJSON$type" : "Astronomy",
                        "EJSON$value" : {
                                "EJSONclass" : "Emails",
                                "EJSONisNew" : true,
                                "EJSONoriginal" : "{\"address\":\"arthyficiel@gmail.com\",\"verified\":false}",
                                "EJSONmodifiers" : "{}",
                                "EJSONvalues" : "{\"address\":\"arthyficiel@gmail.com\",\"verified\":false}",
                                "EJSONerrors" : {

                                }
                        }
                }
```

Instead of 

```
        "emails" : [
                {
                        "address" : "arthyficiel@gmail.com",
                        "verified" : false
                },
```

Now it's work fine

**Comment by lukejagodzinski** [comment]
@ArthurGerbelot You've probably missed type definition when saving in the first place.

**Comment by arggh** [comment]
_For anyone who stumbles here like I did after encountering this error:_

I was returning an Astronomy document from a Meteor-method, but the client was not aware of Astronomy at all (intentionally).
