### ISSUE TITLE
1.2.10 transient fields in nested classes are being saved in the db

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#303]
Any transient field which is present in the main schema does not get saved, as expected. But the transient fields that I have in nested classes does get ported to the db. Please fix this in 2.0.

**Comment by jagi** [comment]
It already is working properly in 2.0. Astronomy 1.x in some parts was to complex and it was hard to keep track of all the features. And in 2.0 the code base is much cleaner and simpler. There should be less bugs. I will probably don't fix it in 1.2+, at least for now until I'm finished working with 2.0

**Comment by s7dhansh** [comment]
Awesome! I am eagerly waiting for 2.0 final release.

**Comment by Andrew1431** [comment]
We all are.
