### ISSUE TITLE
2way binding and Astronomy

### ISSUE THREAD

**Issue by jmwierzbicki** [jagi/meteor-astronomy#307]
Is it possible to set data into Astro model like in how popular ORM does? For example, in angular input field is bound to model.field, so each change acts like model.field = 'change' - however Your package does not take standard property, and use plain setters - i find it strange, as every MVC framework i used before had such behavior.
for now, before save i must iterate every property and call set() manually.

**Comment by jagi** [comment]
Using the `set()` method will not be obligatory in Astronomy 2.0 which will be released soon. So I would recommend switching to it as soon as it's available. So you will be able to set field's values directly.

If it goes about 2-way data binding, I'm not planning to introduce such feature as it's tightly coupled with a view layer and Astronomy is intended to work with many view layers. In the future I'm planning support for React and GraphQL. So it will be even less coupled with Meteor. However in when using Astronomy 2.0 it should be fairly simple to create a module for 2-way data binding.
