### ISSUE TITLE
Project Fields

### ISSUE THREAD

**Issue by andfs** [jagi/meteor-astronomy#309]
How can we project fields in query with astronomy? Fetch only desired fields?

https://docs.mongodb.org/manual/tutorial/project-fields-from-query-results/

**Comment by jagi** [comment]
You can limit fields the same way. However missing fields will be replaced with default values but it's not a problem as you are not going to use them.

**Comment by andfs** [comment]
I did it in a different way.
I was using a field in an autocomplete. So it was impossible to do direct
