### ISSUE TITLE
Questions about Astronomy 2.0

### ISSUE THREAD

**Issue by Billybobbonnet** [jagi/meteor-astronomy#310]
Hello,

First post here, so first, Congratulations to Jagi and all the contributors for the work on this great package. 

I would like to integrate Astronomy 2.0 in my app and I have several questions. I would have asked them on SO usually, but since it is exclusively about Astronomy, I thought it might help others to put these here.

Also, please tell me if you want me to split this into different issues.
___
As I understood things, with e.g. a `User` Astro class on top of `Meteor.users` collection (or any other collection for that matter), when modifying a document, `User.save()` will:

- Check the new user document against the Astro schema on client Side
- Call a server method to request the document modification
- The server method will run another check against the schema
- if successful, the document is updated/created/etc.

___
Now if I extend the `User` Astro class in a file located in my server folder, the above process will be the same except for the fields tested on client (only the non-extended subset would be checked on client). Right?

___

If I attach methods to my Astro class, such as `User.isAdmin()`, how would it work:
- I must put them in the `both `or `client `folder to use them on client side or are they somehow available to client if they are defined in the server folder? 
- If not, as I see things, either I put them in both folder and expose them to client but they are executed in both server and client so it still should be safe, either I create them on server separately from the Astro class and call them like usual methods, but I won't benefit from latency compensation.
- For the same method, can I create one version on server and another on client, the client version of my Astro method being just a stub?

___

I looked at the meteor-astronomy-relations package and as far as I can tell their is no server side code with publication related stuff. I assume then that relations will allow to get related items that are already published and available, right? It does not create an additional publication or `Cursor.observe()` or any other resource consuming server task?

___

Concerning the new syntax:
```
// v2
fields: {
  firstName: String
}
```
Does that mean that `String` is a reserved object name and I can declare string arrays fields like this: `[String]`?

___

Why is there no _id type (by choice?)? So the easiest way to check _ids is to declare the field string type and add an _id regex validator to it?

___

If you came that far, thank you for reading me :smile:

**Comment by jagi** [comment]
1. Yes it will behave that way (Astronomy 2.0)
2. Yes you can extend class only on the server and it will behave as you described (Astronomy 2.0)
3. You have to remember that Astronomy methods are not the same as Meteor methods. When you create Astronomy method it won't create Meteor method that can be run in both environments. So if you call Astronomy method on the client it won't be called on the sever. You have to create Meteor method that will do that.
4. Relations module does not deal with publications
5. `String` is just the JavaScript `String` constructor. It doesn't do anything magical here.
6. Do not understand question about ids

**Comment by Billybobbonnet** [comment]
@jagi thank you very much for your answers.

Concerning the last question, I agree it could be confusing. Let me give you more details:

The mongo _id field generated by Meteor is a string. However, a dedicated validator would be nice (besides checking it is a string). I used a simple function in my previous project when I wanted to achieve that:

``` javascript
this.checkId = function(id){
	return Match.test(id, String)&&/[a-zA-Z0-9]{17,17}/.test(id);
}
```
Basically, I was asking why you did not implement a built-in validator in Astronomy since you did it for e.g. emails.

**Comment by tylershuster** [comment]
My Validator.mongoID( 'CollectionName' ) code looks like this:

```
Astro.createValidator({
  name: 'mongoID',
  validate: function( fieldValue, fieldName, collectionName ) {
    return (typeof eval(collectionName).findOne({_id: fieldValue}) == 'object');
  },
  events: {
    validationError: function(e) {
      e.setMessage(
        e.data.fieldValue + " does not exist in the " + e.data.collectionName + " collection."
      );
    }
  }
});
```

**Comment by jagi** [comment]
Do you need this somewhere or it's just curiosity? MongoDB will validate it so there is no point of validating it in Astronomy.

**Comment by tylershuster** [comment]
My reason for creating the function was that I wanted to make sure I was storing the ID of a document that actually exists, ex:

```
Volunteer = User.inherit({
  name: 'Volunteer',
  fields: {
    areasOfExpertise: {
      type: 'array',
      nested: {
        name: 'Industry Sector',
        type: 'string',
        validator: Validators.mongoID( 'IndustrySectors' )
      }
    }
  }
});

```

**Comment by Billybobbonnet** [comment]
we drifted a little from the original point (I assumed I had to check ids & that mongo didn't) but that could be a feature to check that an id matches an actual document. 

Side note: it seems that whatever the collection is, [_ids are unique](http://stackoverflow.com/questions/34179908/in-meteor-mongo-collections-is-the-id-field-unique-in-its-collection-or-in-the).

**Comment by jagi** [comment]
> My reason for creating the function was that I wanted to make sure I was storing the ID of a document that actually exists

Still don't understand the reason behind it. What do you mean by saying "make sure I was storing the ID of a document that actually exists"?

**Comment by tylershuster** [comment]
Let’s say I have a “Volunteer” who is associated with multiple “Industry Sectors.” Both volunteers have their own collections. I want Volunteer.industrySectors to return an array of Industry Sector IDs, and furthermore I want to make sure that those IDs refer to real documents, and not just that they are strings.

**Comment by jagi** [comment]
Oh ok now I understand. So it's not possible in MongoDB to be "sure". You just have to save IDs as strings and that's all. There's nothing more you can do. And you don't have to validate it as long as data does not come from the user and is autogenerated by the script.

**Comment by Billybobbonnet** [comment]
@tylershuster, my 2 cents: you can see your system as a closed loop: 
When you insert an ID, you know it matches a document since this is where you got it. After that, you hook on the related document collection requests and you make sure that every time someone remove one of the Volunteer documents, all its ID occurrences are updated (i.e. removed from array) in the other(s) collection(s). Same system can be applied to all the situations where you could "corrupt" an ID record by removing its matching document.

I will close the issue since every question is answered, (ty @jagi ! )
