### ISSUE TITLE
2.0.0-rc.7 fieldDefinition is not defined

### ISSUE THREAD

**Issue by Zaiban** [jagi/meteor-astronomy#314]
Hello! Trying to convert my project from 1.2.10 to 2.0.0, and getting the following error:
`W20160328-03:18:25.113(3)? (STDERR)           
W20160328-03:18:25.114(3)? (STDERR) /home/esa/.meteor/packages/meteor-tool/.1.2.6-rc.13.7j9v5k++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160328-03:18:25.114(3)? (STDERR) 						throw(ex);
W20160328-03:18:25.115(3)? (STDERR) 						      ^
W20160328-03:18:25.252(3)? (STDERR) ReferenceError: fieldDefinition is not defined
W20160328-03:18:25.252(3)? (STDERR)     at checkTypeExistence (packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:15:18)
W20160328-03:18:25.252(3)? (STDERR)     at packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:48:7
W20160328-03:18:25.252(3)? (STDERR)     at /home/esa/.meteor/packages/stevezhu_lodash/.4.6.1.1hrw1j0++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4143:15
W20160328-03:18:25.252(3)? (STDERR)     at baseForOwn (/home/esa/.meteor/packages/stevezhu_lodash/.4.6.1.1hrw1j0++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:2669:24)
W20160328-03:18:25.252(3)? (STDERR)     at /home/esa/.meteor/packages/stevezhu_lodash/.4.6.1.1hrw1j0++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4112:18
W20160328-03:18:25.253(3)? (STDERR)     at Function.forEach (/home/esa/.meteor/packages/stevezhu_lodash/.4.6.1.1hrw1j0++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:7828:11)
W20160328-03:18:25.254(3)? (STDERR)     at Module.onApplyDefinition (packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:23:5)
W20160328-03:18:25.254(3)? (STDERR)     at packages/jagi:astronomy/lib/core/class.js:174:11
W20160328-03:18:25.254(3)? (STDERR)     at packages/jagi:astronomy/lib/core/module.js:95:4
W20160328-03:18:25.254(3)? (STDERR)     at arrayEach (/home/esa/.meteor/packages/stevezhu_lodash/.4.6.1.1hrw1j0++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:483:11)
`

I have only 1 very simple Astro class at the moment:

`export const Equipment = Astro.Class.create({
  name: 'Equipment',
  collection: Equipments,
  fields: {
    name: String,
    isFree: Boolean
  }
});`

The syntax should be correct? Or am I missing something here.

Thanks in advance!

**Comment by jorgeer** [comment]
Had the same problem, and it is a bug, "fieldDefinition" is not defined.
However, it is just a minor one, the bug occurs in an error call, because one of your fields are not of a valid type.
I still had some type: "boolean" definitions laying around. Are you sure that's the only astro class you have?

**Comment by Zaiban** [comment]
Yeah you were right, there was some dead code and after removing it all works great!

Now that Meteor 1.3 has been officially released I'm expecting Astro 2.0 have release soon too. Things are looking very good.

**Comment by jagi** [comment]
Hey. Yes I will release it as soon as possible. I have to make some tweaks and documentation.

I'm closing this issue for now.
