### ISSUE TITLE
Question: Is there a way to retrieve the children of a parent class?

### ISSUE THREAD

**Issue by tylershuster** [jagi/meteor-astronomy#318]
Self-explanatory. I know how to retrieve a parent, but not the other way.

**Comment by jagi** [comment]
Hi, it's not possible directly. It's rather not common in inheritance model to get children. You would have to loop through all the classes and find children of a given one. I would strongly discourage doing that. There is probably better way of achieving what you want.

**Comment by tylershuster** [comment]
Yeah, just thought I'd ask. Thanks!
