### ISSUE TITLE
Implicit Setter/Getter not possible?

### ISSUE THREAD

**Issue by dcworldwide** [jagi/meteor-astronomy#32]
Just learned about your package. I'll be tracking it to see how it evolves :)

First impression was that the setter/getter syntax is verbose. From docs

```
Setters and getters

Each class has the setter (set) and getter (get) functions. Let's take an example.

Post = Astro.Class({
  name: 'Post',
  collection: Posts,
  fields: ['title', 'commentsCount']
});

var post = new Post();
post.set('title', 'Title'); // Call field setter.
alert(post.get('title')); // Call field getter.
But you can also set values directly but assigned values won't be converted to the proper type of the fields.

post.title = 'New title';
post.title = 123; // Value won't be converted to the string.
alert(post.title);
You should always set values coming from the forms using the set function.
```

Can we not consolidate the approach somehow? object.property = x is much more terse.

**Comment by jagi** [comment]
In fact there were mutators before. So calling doc.property = x; was causing the setter to be called. However in discussion under the ReactiveMap repo someone from Meteor team noted that they try to support as many browsers as possible. And setters/getters (mutators) don't work in old IE browsers. I thought about creating two packages. One for people wanting support old browsers and one for new browsers. But I will see of it's gonna work that way.

**Comment by jbbr** [comment]
I also prefer the old behavior - using implicit setters/getters although this means no IE8 support.

**Comment by jagi** [comment]
Ok so I will create special package for people that don't want to support IE8 and below.

**Comment by jagi** [comment]
I the next version (0.11.0) I've fixed it by introducing configuration. You will be able to set:

```js
Astro.config.supportLegacyBrowsers = false;
```

I will publish the 0.11.0 version this evening.

**Comment by jbbr** [comment]
Thanks! I really like this solution. I think maintaining two packages would require more effort and would cause confusion.

**Comment by jagi** [comment]
Ok, version 0.11.0 published. Let me know if everything works as expected.

**Comment by dcworldwide** [comment]
Nice fix. Config with optimistic defaults for the win :)
