### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mp27** [jagi/meteor-astronomy#320]
Any way to get the documentation ? since the site is down ...?

**Comment by NaderIkladious** [comment]
https://github.com/jagi/meteor-astronomy-docs

here is the documentation repo.

it's a meteor app as well, so you can run it locally, or you can just search for what you want in the `docs/*.md` files

**Comment by jagi** [comment]
I'm looking for some free alternatives but I will probably end up paying for some server or by just putting documentation on GitHub pages.

**Comment by mp27** [comment]
thanks
