### ISSUE TITLE
User save fails due to duplicate ID

### ISSUE THREAD

**Issue by tylershuster** [jagi/meteor-astronomy#321]
When I call anything equivalent to `Meteor.user().save()`, including things like `Meteor.users.findOne({_id: Meteor.userId()}).save()`, I get a message saying "Error while simulating the effect of invoking '/users/insert'" and "insert failed: Access denied. No allow validators set on restricted collection for method 'insert'."

I've done nothing particularly out of the ordinary except apply a model to Meteor.users() collection.

**Comment by jagi** [comment]
Add `Meteor.users.allow` rules to the collection

**Comment by tylershuster** [comment]
Oops, forgot to mention the important part as per the title. It fails due to a duplicate _id. (Tried adding allow rules, tried adding the insecure package back).

**Comment by tylershuster** [comment]
I tried the same method in another project with Astronomy, and realized that the Meteor.users collection in the problematic project is `_restricted: true`. Do you know why that flag would become set?

**Comment by jagi** [comment]
`_restricted` is used in the `insecure` package https://github.com/meteor/meteor/blob/15cdbca24888bfdff3ad43c1891a1719c09b3dc5/packages/allow-deny/allow-deny.js#L78

**Comment by tylershuster** [comment]
I had removed that, so when I reinitialized the project it was fine. You're the bomb.
