### ISSUE TITLE
Documentation is down.

### ISSUE THREAD

**Issue by davidystephenson** [jagi/meteor-astronomy#322]
[http://astronomy.jagi.io](url) is crashing.

**Comment by minfawang** [comment]
See #320.

This is because of a decision from MDG to turn down the free hosting service.

**Comment by talha-asad** [comment]
Yup, seems we'll need to find a new host

**Comment by jagi** [comment]
I will probably switch to github documentation. All other options I've found does not fit my needs.

**Comment by ffxsam** [comment]
Desperately need this. Is there some other location we can maybe access the raw documentation? (in its MD or HTML format?)

**Comment by jagi** [comment]
I will be working on documentation for 2.0 and will also bring back docs for 1.2. You can access raw documentation here: https://github.com/jagi/meteor-astronomy-docs/tree/master/docs

**Comment by ffxsam** [comment]
I didn't even realize 2.0 was out!

**Comment by jagi** [comment]
It's not yet published but it will be soon. I've finished working on main features.

**Comment by cvsakpal** [comment]
Where would I find documentation of using astronomy for User Profile?

**Comment by jagi** [comment]
https://github.com/jagi/meteor-astronomy-docs/blob/master/docs/example.md

**Comment by cvsakpal** [comment]
Cool thanks!

**Comment by jagi** [comment]
Temporarily documentation for v1 is located under this address: http://jagi.github.io/meteor-astronomy/v1 - it's not "recovered" entirely yet. Probably, it will be available tomorrow.
