### ISSUE TITLE
model.validate() doesn't validate when offline. Expected behaviour?

### ISSUE THREAD

**Issue by Andrew1431** [jagi/meteor-astronomy#323]
Hey there, I've been scrounging your source code, and have had no luck in finding out why my callback won't get called when the server is offline. I'm getting a little adventurous with what I'm trying here. Trying to get a fully offline app going with Ground DB and astro as my model layer. So far everything is working, except when I'm offline my callback isn't run. I wasn't aware that your validation is being done server side.

```js
  saveClicked() {
    let { shift } = this.state;

    var result = shift.validate(err => {
      if (err) {
      } else {
        let _id = Shifts.insert(shift.raw());
        FlowRouter.go('/');
      }
    });
```

Where shift is

```js
Shift = Astro.Class.create({
  name: 'Shifts',
  fields: {
    title: {
      type: String
    },
    location: {
      type: String,
      optional: true
    },
```

Is this expected behaviour?

**Comment by Andrew1431** [comment]
![image](https://cloud.githubusercontent.com/assets/9736372/14198035/c7c21af6-f7a3-11e5-83ef-56bfe06eb4ce.png)

Strange order there...

**Comment by jagi** [comment]
I've tested it and it's working even when being offline. You are probably doing something wrong. If sever is not available it will still validate on the client and throw some errors or execute callback function if provided.

**Comment by Andrew1431** [comment]
Should have mentioned I'm on rc.7 maybe things have changed a bit. I'll look in to it more, but I don't see any issue with it :P Thanks for the response.

**Comment by jagi** [comment]
I'm talking about rc.7. It works that way. It wasn't doing server validation in the same time in 1.2

**Comment by Andrew1431** [comment]
Wow damn you're right, just tested in console and it was working. Strange behaviour then but definitely induced by me somehow...

![image](https://cloud.githubusercontent.com/assets/9736372/14213716/7b897774-f807-11e5-9ff1-3366f7fc0c09.png)

**Comment by jagi** [comment]
In deed :). So closing it for now
