### ISSUE TITLE
We have methods for each document, what about methods for the entire collection?

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#324]
Kind of like static functions for a Class. This is a suggestion. Would like to hear thoughts on this.

This is currently achievable by binding more functions to your Astro Class, however an official support for such a feature would be much better. @jagi  what are your thoughts on this?

**Comment by jagi** [comment]
You can always add method to the class or collection statically and I don't think that there is any reason to make it a feature in Astronomy as it's plain simple.
```
SomeCollection.method = () => {};
SomeClass.method = () => {};
```

**Comment by talha-asad** [comment]
I was of the impression that they might not work when accessing a Class this way: `Astro.Class.classes.someClass` but it turns out it works that way as well.

I am going to close this as it makes no sense. Thanks for your input.
