### ISSUE TITLE
Automatic Casting v2

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#326]
@jagi 

I think we need to have a way to enable basic automatic casting as we had in v1. I know the argument here is that Astro is just an ODM and automatically casting leads to unknowable results and causes confusion but alot of times it's a real pain in the ass to write 50+ lines casting strings etc to their proper types. In alot of cases you can't have them come in the proper object notation.

What are your thoughts on this, If this is done separately what should it be? Should it be a module. This might be trivial but without having access to the old documentation I am not sure.

If you can give me a few pointers, i would be interested in writing this, maybe i could just port the old code from v1 to create a opt-in sort of module.

Let me know your thoughts.

**Comment by jagi** [comment]
It will be definitely a separate module not something that is a part of the core. It should be fairly simple to implement. Just need to get a field definition `Class.getField()` and check its type. It could be solved in form of a new document method like:
```js
doc.fromForm(dataFromForm);
```
or something similar

**Comment by marbemac** [comment]
+1 to this, especially painful for anybody migrating from v1 - lots of hidden little issues.

Possibly related, is astronomy v2 supposed to instantiate nested classes on .set?

For example, say we have an "Endpoint" class, which has property that is an array of "Response" classes. Is the following supposed to instantiate the new endpoint class, and also instantiate response classes inside of it?

```js
var endpoint = new Endpoint();
endpoint.set(endpointProps); // endpointProps has the plan responses array of objects inside of it

// are endpoint.responses[0..n] each instantiated to their Response astronomy class?
```

**Comment by jagi** [comment]
Yes I know that it may be a problem. I will prepare simple module for that before release.

**Comment by marbemac** [comment]
For which, the automatic casting of values, or the instantiation of child classes? For the second (automatic instantiation of child classes), I think that should probably be default behavior no?

**Comment by jagi** [comment]
For both. I don't know if it should be a default behavior. Because it will be inconsistent. I want direct assignment and `set` method to have the same behavior.

**Comment by marbemac** [comment]
Hmm, yeah I can see the merit in keeping those to assignments equivalent.

However, compared to v1, it's really a pain to have to make sure we build up entire objects everywhere we use them, so that nested defaults etc are set correctly. Curious to hear what others think?

**Comment by marbemac** [comment]
Another possible solution, to keep assignment and set the same, is that the constructor could take care of instantiating nested classes, when passed an initial object.

```js
new Post({...rawPostObject}) // when passed into the constructor, nested classes are taken care of, etc
```

**Comment by jagi** [comment]
Hmmm maybe I could make an exception only for nested documents, when used with `set` and in construction phase. Ok, I will do that this way.

**Comment by lukejagodzinski** [comment]
Casting for set method implemented. Preparing to release 2.0. Closing this issue.
