### ISSUE TITLE
Astronomy v2 Optional and Null Values

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#327]
Currently If you initialize a class with some parameters set as `null` they are setup as is, I think this behaviour should be changed and if the field is marked as optional, the particular key should be dropped altogether from the Astro Object. In case that field is not marked as optional but has a default value, it should be set to that.

I think this makes sense, what are your thoughts on this? Does this behaviour contradict with something else?

**Comment by jagi** [comment]
Yes in deed it should work that way. I think there is some bug. I will fix it in rc8

**Comment by jagi** [comment]
I've fixed it and it will be published with rc8. Closing it for now.
