### ISSUE TITLE
v2 - Type of inherit class not working?

### ISSUE THREAD

**Issue by peXed** [jagi/meteor-astronomy#328]
Hello!

I try to move to Astronomy v2 and now running into an issue with a inherit class, used as a field of another class.

@jagi is this not supported anymore?
If I change the class to a normal class (Astro.Class.create), it works, but if I use Parentclass.inherit, the class won't work and would create a throwParseError (but the function checkTypeExistence is not working at the moment, so I get a ReferenceError).

**Comment by jagi** [comment]
I will check it. I've already received information that it may not work.

**Comment by jagi** [comment]
It's working:
```js
const User = Astro.Class.create({
  name: 'User',
  collection: Users,
  typeField: '_type',
  fields: {
    firstName: {
      type: String
    },
    lastName: {
      type: String
    }
  }
});

const Admin = User.inherit({
  name: 'Admin',
  fields: {
    /* Extra fields */
  }
});
```

**Comment by peXed** [comment]
Thanks @jagi for the fast test, but I was not clear enough, I guess.

The inherit class is working perfectly. The problem is, if another class uses the inherit class as a Fieldtype.

Like so:

`const User = Astro.Class.create({
  name: 'User',
  collection: Users,
  typeField: '_type',
  fields: {
    firstName: {
      type: String
    },
    lastName: {
      type: String
    }
  }
});

const Admin = User.inherit({
  name: 'Admin',
  fields: {
    /* Extra fields */
  }
});

const Group = Astro.Class.create({
  name: 'Group',
  Collection: Groups,
  fields: {
    name: {
      type: String
      },
      admins: {
        type: [Admin]
      },
      users: {
        type: [User]
      }
  }
});`

Without the admins field, the Group would work. But with the admins, you will get the error.

I can upload a quick repository, if you like, but if you add the Group Class to your test, you will see the error.

**Comment by jagi** [comment]
Oh I see, I will check it out.

**Comment by jagi** [comment]
Wait a moment. You can't do like that. It's not possible to nest/embed storable class. User/Admin class in this case can be only store in the Users collection. So you can't nest it and that's why it's throwing an error. Maybe I will print some more user friendly error to inform developers.

**Comment by peXed** [comment]
You are totally right, sorry. The example was wrong.

But if you remove the collection from Users, it will still give you the error, that the type is wrong (or without the small typo fix in the apply_difinition.js at the moment, the "ReferenceError: fieldDefinition is not definied at CheckTypeExistence).

So the code should be:

```
const User = Astro.Class.create({
  name: 'User',
  typeField: '_type',
  fields: {
    firstName: {
      type: String
    },
    lastName: {
      type: String
    }
  }
});

const Admin = User.inherit({
  name: 'Admin',
  fields: {
    /* Extra fields */
  }
});

const Group = Astro.Class.create({
  name: 'Group',
  Collection: Groups,
  fields: {
    name: {
      type: String
      },
      admins: {
        type: [Admin]
      },
      users: {
        type: [User]
      }
  }
});
```

**Comment by jagi** [comment]
Ok it's a little bit different situation. I will check it out.

**Comment by jagi** [comment]
In deed there was an error. I've fixed it and I will publish it probably today in rc8. Thanks!

**Comment by peXed** [comment]
You are a star @jagi !
Thank you very much!
