### ISSUE TITLE
Astronomy and Formsy

### ISSUE THREAD

**Issue by PolGuixe** [jagi/meteor-astronomy#329]
Is there a way to have something similar to [Autoform](https://github.com/aldeed/meteor-autoform), with Astronomy for React? 

@ochicf and myself are planning on building something to make the form generation easier for those using React and Meteor. We are planning on doing some sort of integration between Astronomy and Formsy. Any recommendation?

**Comment by jagi** [comment]
For now there is no tool  for Astronomy that would much Autoform. However, if you want to use forms (no autogeneration) I recommend [useful:forms](https://github.com/usefulio/forms). It would be great to have such tool but I will probably have no time to create one. So, if you want to make one, feel free and I can help in some aspects. What I think would be best is not focusing on one UI framework like React, and make it more generic. I mean, user just define what control/widget to render for each field. And user is responsible for providing template for such field.
