### ISSUE TITLE
Is there a way to "clean" Astronomy objects?

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#330]
When I fetch objects from the database, there's a lot of extra Astro fields attached to them besides just my own data fields. Does Astronomy have a way to clean these? The extra fields are causing problems with Redux.

**Comment by ffxsam** [comment]
The best solution I've found is to do this:

```javascript
const o = someAstroObject._original; // o = plain JSON object, no Astro properties
```

**Comment by jagi** [comment]
You can do `doc.raw()` to get clean object.

**Comment by ffxsam** [comment]
Awesome tip!! Thank you.
