### ISSUE TITLE
typeField causing error in 2.0 (Parent collection not returning results)

### ISSUE THREAD

**Issue by tylershuster** [jagi/meteor-astronomy#331]
I have a class `User` created with `Astro.Class.create.` When I run `User.find().fetch()` it returns an empty array. When I run `User.getCollection().find().fetch()` it returns the users.

Now I've extended the `User` class into two roles, and thus set the `typeField` property. When I comment this out, `User.find().fetch()` returns correctly. Has typeField behavior changed in 2.0?

**Comment by jagi** [comment]
If you have two classes `User` and `Admin` and `Admin` inherits from `User` then `Admin.find()` and `User.find()` will have different results. `Admin.find()` will only return admins and `User.find()` will only return documents that were created using the `User` constructor. So, yes behavior has changed in 2.0 and it was requested by developers.

**Comment by tylershuster** [comment]
Thanks for the answer. That's easy enough to account for.
