### ISSUE TITLE
Creating composite indexes

### ISSUE THREAD

**Issue by jazzdragon** [jagi/meteor-astronomy#335]
Hi,
I'm trying to create some composite indexes like so:
```javascript
Post = Astronomy.class({
  name: 'Post',
  fields: {
    author: 'string',
    createdAt: 'date'
  },
  indexes: {
    postIndex: {
      author: 1,
      createdAt: 1
    }
  }
})
```

This creates two separate indexes, instead of a composite index.

**Comment by jagi** [comment]
Documentation is the best source of information ;) https://github.com/jagi/meteor-astronomy-docs/blob/master/docs/indexes.md

**Comment by jazzdragon** [comment]
I guess I missed that fields key.
Another issue though: it seems like indexes like that are not being inherited. Is that by design?

**Comment by jagi** [comment]
It should be but it might be some bug if it doesn't
