### ISSUE TITLE
Softremove problems

### ISSUE THREAD

**Issue by mp27** [jagi/meteor-astronomy#337]
Short story: i used soft remove for lets say subjects , and now i want the admin user to have something like a trash where he can permanently delete or restore that doc.
But... since Class.findOne returns only doc. that are removed: false, and using to get all the documents, Collection.findOne , it gets the right doc but i can't use the astro methods, like set, maybe get etc..
I think maybe i've done something wrong or missed things in documentation , anyway i solved the problem by using plain mongo db query to set the removed field.
I wonder if there is any other solution ?

**Comment by jagi** [comment]
No in v1 there is no other way to do that. However, in v2 it was solved.

**Comment by mp27** [comment]
Thank you, looking forward to use astronomy v2
