### ISSUE TITLE
Auto-running validation only in untrusted environment

### ISSUE THREAD

**Issue by marbemac** [jagi/meteor-astronomy#339]
Astronomy 1 did not auto-run validation on every save. I understand why this is necessary, now that users can save directly from the console/client. However, perhaps it makes sense to only force validation in !trusted environments? This would make migrating from v1 easier, and for our purposes we don't want to run validation when saving from all of our server methods / code. 

At the very least, an option to skip validation when saving in a trusted environment, ie model.save({validate: false}) or something, would be welcome. We would add that to every save in all of our server methods, which is kind of cumbersome, but better than the current situation.

**Comment by jagi** [comment]
I could introduce such possibility on the server but that could cause model being not valid which is obviously not good.

**Comment by marbemac** [comment]
Hey @jagi what was the decision on this one? We would really love to see this, at least as an option. It's made the migration from v1 more difficult, and is still causing issues for us.

**Comment by lukejagodzinski** [comment]
Why would you like to skip validation on the server? How is it possible that it's making problems?

**Comment by lukejagodzinski** [comment]
If you give me good reason then I implement it. It shouldn't be a problem but I just want to implement features that are really needed.

**Comment by marbemac** [comment]
After thinking about this more it's not a huge deal, we'll move a bunch of this validation logic into a different system, that saves warnings on the models. We'll strictly use astronomy validation for deal-breaking issues like enforcing maxLength, required/optional, etc.

**Comment by lukejagodzinski** [comment]
Ok good to hear
