### ISSUE TITLE
Meteor.users() Collection Service.facebook null,

### ISSUE THREAD

**Issue by aligos** [jagi/meteor-astronomy#342]
export const UserServices = Astro.Class({
  name: 'UserServices',
  fields: {
    /\* Any fields you want to be published to the client */
    'password': {
      type: 'object',
      nested: 'Password',
      default: function() {
        return {};
      }
    },
    'facebook': {
      type: 'object',
      nested: 'Facebook',
      default: function() {
        return {};
      }
    }

**Comment by lukejagodzinski** [comment]
You don't have to provide UserServices class, you can set type of services object to `object` and it will be much more flexible.

**Comment by aligos** [comment]
But when i try to get data, `Meteor.user().services.facebook.name` data result null

**Comment by lukejagodzinski** [comment]
It's probably not Astronomy fault. If it's on the client and you're not publishing it then it can be empty

**Comment by aligos** [comment]
Yes, I'm not publish services from users collection. Thanks for your reply
