### ISSUE TITLE
v2 - Getting UserID in Behavior?

### ISSUE THREAD

**Issue by peXed** [jagi/meteor-astronomy#345]
Hello!

I'm currently trying to create a behavior in Astronomy v2. It should simply add the userID to the document (createdBy and updatedBy).

My problem is now, how can I get the userID in a behavior? I always get an error if I use Meteor.userId(), which is clear, because the events are getting called on the server as well.

Is there any way to access the userId in the events?

**Comment by lukejagodzinski** [comment]
What error do you get?

**Comment by peXed** [comment]
Hello!

I had the Meteor.userID() in a helper function. Now, I used the Meteor.user() or Meteor.userId() function directly in the behavior and it works! :+1: 

Does this code not get called on the server as well (in Astronomy v2)? The Meteor.userId() shouldn't work on the server or does it?

**Comment by lukejagodzinski** [comment]
When you call `doc.save()` it will call events in both environments client and server.

**Comment by peXed** [comment]
So it should cause an error, shouldn't it? Because Meteor.userId() is not working on the server or is it in 1.3?

**Comment by lukejagodzinski** [comment]
`Meteor.userId()` is working in any environment but publish function. You can check it in the docs. It shouldn't throw error.

**Comment by peXed** [comment]
Ok. Cool! Thanks for the support and information! :)
