### ISSUE TITLE
.save() on specific fields...

### ISSUE THREAD

**Issue by Andrew1431** [jagi/meteor-astronomy#346]
Hey Jagi, I recall there originally being a way to save specific fields.

`model.save(['firstName', 'lastName'], callback)`

But it appears this no longer works, as its trying to call the array as a function (I'm guessing the callback).

Is there a way to do this now properly on v2?

**Comment by lukejagodzinski** [comment]
Hey, no, there is no way of doing that. You have to save such fields directly without using Astronomy.

However, I may consider introducing such feature but only in the update operation. So even if there is a modified `email` field and you call `user.save({ fields: ['firstName', 'lastName'] })` it will only update first name and last name. However, it would not allow inserting only two from all the fields. Would you be happy with such feature?

**Comment by Andrew1431** [comment]
This would be beautiful! And perhaps in the beforeSave event have some kind of identifier stating what fields have been selected and a way to tell if none have been (aka preventDefault when the client tries to save() without specific fields...)

**Comment by lukejagodzinski** [comment]
Yes list of selected fields can be passed to the event object in the `beforeSave` event.

**Comment by lukejagodzinski** [comment]
Ok I've implemented this feature but I'm not passing fields list to the `beforeSave` event because it's pointless. Your use case is not something that can't be done the other way.
