### ISSUE TITLE
v2 - Error on update, if a default value gets retrieved from the database (but not on insert!)

### ISSUE THREAD

**Issue by peXed** [jagi/meteor-astronomy#348]
Hello!

I run into another strange issue.

In my model, I have a field with a default value, which gets its value from the database (via a function).

It looks like:

```
let Item = Class.create({
  name: 'Item',
  collection: Collections.Items,
  fields: {
    title: {
      type: String,
      default: function() {
        return Settings.get('itemDefaultTitle');
      }
    }
  }
});
```

It works perfectly. The value gets displayed in the UI when I create a new item and saved to the database.
But, if I update the given item, I get an infinity loop, starting with a ServerError 500.

In the console, I get:
`Exception while invoking method '/Astronomy/update' Error: Can't call yield in a noYieldsAllowed block!`

What is causing the issue? Why does the default values getting called on update?
Why is it working perfectly on insert, but not on update?
Did I do something wrong or do we have a bug here?

Cheers,
Dom

**Comment by lukejagodzinski** [comment]
Without reproduction it's hard to tell

**Comment by peXed** [comment]
Yes, it is hard to describe. I took your Astronomy v2 test and modified it to reproduce the error.
This is not the way, how I do it in my App (for example, I use React).

You can find the repo here: https://github.com/peXed/astronomy-test

Simply add a new user (this works). Then edit the user and you will get the error-loop.

**Comment by lukejagodzinski** [comment]
To be honest I have no idea why it's not working. I'm gonna have to ask in the Meteor GitHub repository.

**Comment by peXed** [comment]
Thanks for your help @jagi 

It is indeed a really strange issue and the callstack you get is not really helpful.

**Comment by lukejagodzinski** [comment]
@peXed I've asked on Meteor GitHub. I just want to know what these errors mean. In deed stack trace is not helpful in this situation. I've tried to prepare reproduction that would be very similar to what happens in Astronomy but without effect. We will see what MDG will say about that

**Comment by lukejagodzinski** [comment]
I still haven't managed to resolve this issue, so I will release 2.0 with this bug. However I'm gonna fix it in 2.0.1. I've said that I will release 2.0 before the end of this month and I will do so, later tonight :)

**Comment by peXed** [comment]
Any news on this bug? Can I help you somehow, to resolve it?

**Comment by lukejagodzinski** [comment]
@peXed I think that I've resolved a problem however I don't know if it's gonna work in all cases so I would like you to test my fix. Please clone the `v2` branch of Astronomy GitHub repository to your local `packages` directory and try running your code.

**Comment by peXed** [comment]
Hello! Your fix works like a charm!

Thank you very much.
