### ISSUE TITLE
[v2] ENUM Enhancement

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#350]
I know you're busy releasing v2, so let's get this added after you release v2.

The problem with ENUM's right now is that, there is no way to go back from the underlying value to the ENUM key. We are using hacky ways to do this right now (looping through keys of Enum and checking equality). Maybe you have this implemented but due to lack of documentation I cannot be sure.

I think this should be part of the ENUM type, something like `EnumType.getENUM(val)`. Let me know your thoughts.

**Comment by lukejagodzinski** [comment]
When I was implementing ENUMs I was thinking about such feature but I've decided that it's not necessary. In most cases ENUMs are just for easier (more human) notation. You just write `Status.OPENED` instead `2` or something like that. In most cases you don't need key `OPENED`. Could you give me some example where it's necessary?

**Comment by talha-asad** [comment]
There are 2 cases where this comes in really handy.

Case 1 is where you have a ENUM type defined with alot of keys and whenever you make a retrieval from the DB, you have to make a comparison with each one to know which one it is. It ends up either being a really long else if or a switch block.

Case 2 is where you have another object that uses the same keys to specify some data. In that case you have to first loop to get the Keys from Enum.

Currently we are using a handy function for this sort of thing:

``` js
function getEnumKey(enumObj, val) {
  for (var i = 0, keys = Object.keys(enumObj), keysLength = keys.length; i < keysLength; i++) {
    if (enumObj.hasOwnProperty(keys[i]) && enumObj[keys[i]] === val)
      return keys[i];
  };
}
```

**Comment by talha-asad** [comment]
I think a few handy utilities in the ENUM type will be helpful in different cases. Like `getIdentifiers()` and `getIdentifier(val)` will go a long way. Let me know your thoughts on this.

**Comment by lukejagodzinski** [comment]
Ok I will introduce such function to ENUM

**Comment by lukejagodzinski** [comment]
I'm implementing it right now, but there is one more question about ENUMs and possible values. Right now ENUMs in Astronomy can have any value not only numbers which actually is not perfect, because it breaks base principle, values are enumerated. However, in most languages it's possible to assign the non successive numbers for each identifier. So I think about changing how syntax will look like.

``` js
const Status = Enum.create({
  name: 'Status',
  identifiers: ['OPENED', 'CLOSED', 'DONE', 'CANCELED']
});
```

so assigned values for each identifier will be:
- OPENED = 0
- CLOSED = 1
- DONE = 2
- CANCELED = 3
  And if you want to provide non successive values then

``` js
const Status = Enum.create({
  name: 'Status',
  identifiers: {
    OPENED: 1,
    CLOSED: 2,
    DONE: 4,
    CANCELED: 8
  ]
});
```

What do you think?

**Comment by talha-asad** [comment]
That works, but I don't understand why would you want to hard bound them to integers. I think having any possible value for them is great. Do you wish to switch to numbers only so you can make use of Array functions?

**Comment by lukejagodzinski** [comment]
Yes I'm thinking about limit it only to numbers which is how ENUMs work in every language https://en.wikipedia.org/wiki/Enumerated_type so I thing it's good to keep up with the standard

**Comment by talha-asad** [comment]
That works for me, however just wanted to clarify it is not required that ENUM keys equal to an integer, it's just that most languages implement them that way. The wiki page also states it as "often" not as a requirement.

**Comment by lukejagodzinski** [comment]
I've made some fixes and allowed any values however numbers are default. I will describe more in a documentation.

**Comment by talha-asad** [comment]
I know you got this part done and it's working great for me, except a few edge cases which when I researched online, people have been able to solve by use of ES6 symbols. I would like you to have a look at [es6-enum](https://www.npmjs.com/package/es6-enum) and [enumify](https://www.npmjs.com/package/enumify)

Perhaps you can use them internally in astro. The edge case I have currently is if I have 2 separate Enum Objects with the same final value, they will match each other even though the parent Enum is different altogether. This doesn't happen when Enums are implemented using Symbols as they have this intrinsic property to never overlap with another symbol.

Let me know your thoughts, we can perhaps get this in v2.1

**Comment by lukejagodzinski** [comment]
Nice idea, I will probably add that feature in v2.1

**Comment by lukejagodzinski** [comment]
I've started working on this feature and I have one problem with it. Using Symbols as values maybe is a fancy trick but it may cause also some problems. There may be situations where somebody wants to compare enum value to another raw value like `post.status === 4` not just `post.status === Status.OPENED`. In such situations it would not work. There is also a problem with storing ENUM values  in a database, which looks like this

``` js
{
  "_k": "Symbol(Symbol.iterator)_6.13r9nd1y6xswcdi"
}
```

So I will have to prepare some converter on document save that will store it in more human readable way.

**Comment by talha-asad** [comment]
Storage is definitely going to require a bit of work. I'll do a bit of research on Symbols, i don't have experience using them either :)

I don't see a reason why someone would want to compare an ENUM with it's base value. It's goes against using ENUM in the first place.

**Comment by chathuraa** [comment]
Hi @jagi ,

How should i go about retrieving the value of the ENUM?

Thanks,

**Comment by lukejagodzinski** [comment]
@chathuraa If you want to get value of the ENUM you just use this enum and identifier `YourEnum.IDENTIFIER` if you want to get identifier using value then `YourEnum.getIdentifier(enumValue)`. Or you're talking about something else?

@talha-asad yes it will require a bit of work :)

**Comment by chathuraa** [comment]
Hi @jagi,

Apologies for not explaining it properly.

I was wondering given the Identifier how to get the underlying value.  ie. `MyEnum.getValue(enumIdentifier)`.

Thanks,

**Comment by lukejagodzinski** [comment]
Like that :)

``` js
MyEnum[enumIdentifier];
```

**Comment by chathuraa** [comment]
oh... feel dumb now. Thanks :)

**Comment by lukejagodzinski** [comment]
@chathuraa no problem :) Don't feel bad, sometimes the easiest answers seems to be hard :)
