### ISSUE TITLE
Sites are down

### ISSUE THREAD

**Issue by sgelbart** [jagi/meteor-astronomy#352]
Not sure if this is the right place for it but I wanted to checkout the demos/docs and your site are down:
http://astronomy.jagi.io/ and http://astronomy.meteor.com/

**Comment by lukejagodzinski** [comment]
It's because of termination of the free Meteor hosting by MDG. You have to clone demo repository to test it out and documentation is currently available under http://jagi.github.io/meteor-astronomy/v1
