### ISSUE TITLE
Validatoin not restricting to fields provided...

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#353]
I am validating some form fields, therefore, this is client-side validation:

```
var at = new AuditTemplateModel();
        at.status = [{
            id: 1,
            name: 'In Progress'
        }];
        at.title = this.title.value;
        at.desc = this.desc.value;
        at.instructions = this.instructions.value;
        at.category = [{
            id: this.category.value,
            name: this.category.text
        }];
        if( !at.validate(["status","title","desc","instructions","category"]) ){
            console.log("Form invalid!");
        }
```

I am getting the following error in my browser console:

`Error: "ref" is required [validation-error]`

Even though "ref" is a field within my model, I am not asking for it to be validated so the validation should pass.

**Comment by Ben305** [comment]
You should call 

```
at.validate({fields: ["status","title","desc","instructions","category"]}, function(error) {
    if (error) {
        console.log("Form invalid!");    
    }
});
```

**Comment by joetidee** [comment]
Documentation needs updating to reflect this pattern.

**Comment by joetidee** [comment]
ok, so I changed the validation to the above suggested pattern, and it validated even though the `title` was an empty form field. My model definition is simply stating that the `title` is `type: String`, so I would have assumed that it was required AND also has to not be empty in order to be valid. Is this correct, or do I have to specify something else in the model to invalidate the title if it is empty?

**Comment by lukejagodzinski** [comment]
Please always write about which version are you talking. Documentation for 2.0 is not ready yet. Some parts of it are still from the 1.0 version. So I'm updating it page by page and adding new pages specifically for 2.0.

If it goes about behavior of validators. If you specify some field it's required by default, so it can't be null or undefined. But empty string `""` will pass as its string. You have to specify for example minimal length of the field or add `notEmpty` validator.

**Comment by joetidee** [comment]
I have been using 2.0.0-rc8. I tried the notEmtpy validator in this way but the form was still passing the test even with a blank field:

```
...
title: {
            type: String,
            notEmpty: true
        }
...
```

**Comment by lukejagodzinski** [comment]
@joetidee where did you find such syntax for defining validators in 2.0?
You should do:

``` js
title: {
  type: String,
  validators: [{
    type: 'notEmpty'
  }]
}
```
