### ISSUE TITLE
v2 - 'Updating from the client is not allowed' Error in rc.9

### ISSUE THREAD

**Issue by peXed** [jagi/meteor-astronomy#359]
Hello!

I ran into a small issue again. After updating to rc.9 I can't save any of my docs.

I always get a 403 or "Updating from the client is not allowed". I used the security package from ongoworks before and it worked great, but something in rc.9 seems to be breaking the internal verification.

To test all possiblities I uninstalled ongoworks:security and added the insecure package to my meteor app. But the error still appears.

Do I do something wrong? Did I forget something?

Thank you very much in advance!

**Comment by lukejagodzinski** [comment]
Sorry I didn't mention about this when publishing. Just for now add the `secured: false` to your class schema. http://jagi.github.io/meteor-astronomy/v2#secured-property It will be false by default so you can later remove it if you want.

**Comment by peXed** [comment]
Ah! Awesome. Thanks for the fast reply!

So if I use secured: false, the ongoworks:security will still work, because Astronomy is calling the normal collection functions later on, right?

**Comment by lukejagodzinski** [comment]
I don't know what the `ongoworks:security` package is and what it does but it should work the old way when you set `secured` to `false`. I'm making last fixes and maybe I will release 2.0 tomorrow. We will see.

**Comment by peXed** [comment]
Thank you @jagi! Awesome work :).

The `ongoworks:security` is a simple package to secure database operations. As far as I know, it implements just `allow` and `deny` rules.
But I like your approach in the new documentation. I may drop the package and put all the validation inside the models.

Cheers,
Dom

**Comment by s7dhansh** [comment]
@jagi have you by any chance made this secured property true by default in the latest code? I had to set it to false to make things work..

**Comment by s7dhansh** [comment]
https://github.com/jagi/meteor-astronomy/pull/385 fixes it. Please review.
