### ISSUE TITLE
Changing schema to include a default array causes it to get casted to an object in database

### ISSUE THREAD

**Issue by laucheukhim** [jagi/meteor-astronomy#363]
If I have existing data and change the schema later on to add a property that is an array, upon saving, the array will get casted to an object in the database. This happens on Astronomy v2.

Let's say I have the following schema for phones.

``` javascript
const Phone = Astro.Class.create({
    name: 'Phone',
    collection: new Mongo.Collection('phones'),
    fields: {
        name: String
    }
});
```

And I have inserted the following data to the database.

``` javascript
let phone = new Phone();
phone.name = 'iPhone';
phone.save();
```

Later on, I change the schema to include information about color options, which is an array, and set the default to an empty array.

``` javascript
Phone.extend({
    fields: {
        colors: {
            type: [String],
            default() {
                return [];
            }
        }
    }
});
```

Then I fetch an existing record from the database and update it.

``` javascript
let phone = Phone.findOne({ name: 'iPhone' });
phone.colors = ['Silver', 'Space Gray', 'Gold', 'Rose Gold'];
phone.save();
```

The array will be casted to an object in the database, and remain as an object when fetched.

``` json
{
    "_id": "Q4GAXo5iYkcsAEhpn",
    "name": "iPhone",
    "colors": {
        "0": "Silver",
        "1": "Space Gray",
        "2": "Gold",
        "3": "Rose Gold"
    }
}
```

Specifically, the `modifier` in [`lib/modules/storage/utils/get_modifier.js`](https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/storage/utils/get_modifier.js) generates the following for the query:

``` javascript
{
    $set: {
        'colors.0': 'Silver',
        'colors.1': 'Space Gray',
        'colors.2': 'Gold',
        'colors.3': 'Rose Gold'
    }
}
```

This creates an object in MongoDB for an existing record if the field does not already exists.

Creating a new array field on an existing schema only works if I am inserting entirely new records to the database, if such field already exists as an array in the database, or if I do not set a default value. To workaround this issue, I have to resort to not setting a default value, and patch it every time I use this object (or do it in the `afterInit` event).

``` javascript
Phone.extend({
    fields: {
        colors: {
            type: [String]
        }
    }
});
```

``` javascript
let phone = Phone.findOne({ name: 'iPhone' });
if (!Array.isArray(phone.colors)) {
    phone.colors = [];
}
phone.colors.push('Classified');
phone.save();
```

This makes it clumsy to change the schema as simply setting a default value for the object does not work.

**Comment by lukejagodzinski** [comment]
@laucheukhim thanks for noticing it. I've fixed it. It will be available with 2.0 release.
