### ISSUE TITLE
[v2] Index support for nested Astro class

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#365]
Consider the following:

``` js
Child = Astro.Class.Create({
  name: 'Child',
  fields: {
    name: {type: String}
  }
});

Parent = Astro.Class.Create({
  name: 'Parent',
  collection: new Meteor.Collection('parents'),
  child: {type: Child, default() { return new Child(); }}
});
```

How can one setup an index on Child's `name` field, provided it has no collection attached to it.

**Comment by talha-asad** [comment]
Do you think it would be possible to have astro work it out, if it's done this way:

``` js
Child = Astro.Class.Create({
  name: 'Child',
  fields: {
    name: {type: String, index: 1}
  }
});

Parent = Astro.Class.Create({
  name: 'Parent',
  collection: new Meteor.Collection('parents'),
  child: {type: Child, default() { return new Child(); }}
});
```

Right now it throws an error, because an index is being set on an Astro Class that doesn't have a collection field specified, however I think this warning should be removed and it should automatically setup an index in the parent class that uses that class, which has a collection defined. Let me know your thoughts.

**Comment by lukejagodzinski** [comment]
I haven't been trying it but this should work:

``` js
import { Class } from 'meteor/jagi:astronomy';

const User = Class.create({
  name: 'User',
  /* ... */
  fields: {
    address: Address
  },
  indexes: {
    cityName: { // Index name.
      fields: { // List of fields.
        'address.city': 1
      }
    }
  }
});
```

Indexes in nested classes is not so easy problem to solve. Index is something related with Collection, so storing index information in a nested class that does not have any associated collection seems to be wrong. However, parent class could look for nested classes and compose indexes. So in my example it could look for indexes in the `Address` class and it would found index on the `city` field, so it would compose index for the field `address.city`. Seems to work fine. But what about array of nested classes? Should it create index for each index? `addresses.0.city`, `addresses.1.city`, `addresses.2.city` etc.? Or should it create index for `addresses.city`? I don't know if it's even possible. I would have to check it out.

**Comment by lukejagodzinski** [comment]
OK yes it's possible https://docs.mongodb.org/manual/core/index-multikey/#index-arrays-with-embedded-documents however I have to rethink it carefully.

**Comment by talha-asad** [comment]
I think Astro should be able to work out indexes from nested Classes.

**Comment by talha-asad** [comment]
I would like to help implement working out indexes from child or used classes.
Please point me in the right direction.

**Comment by lukejagodzinski** [comment]
Hmmm one way of implementing it would be scanning Class schema for nested fields where a field is of Astro Class type. Then we should create indexes with appropriate names in the parent class. In theory it's not hard to implement. Are you familiar with the modules structure in Astronomy 2.0?

**Comment by talha-asad** [comment]
I have glanced at it a few times, but I think I can get familiar with it when i'll start writing code, hopefully this weekend. :)

Thanks

**Comment by lukejagodzinski** [comment]
Ok, if you have any questions just ask here. I will try to help. Thanks for contribution!

**Comment by talha-asad** [comment]
I added a [pendingIndexes](https://github.com/talha-asad/meteor-astronomy/commit/5e7521eb772ed609fede2dc403d0c421cd6f97d4) hash to index module, thinking it can be used by the Class schema where a field is of Astra Class Type. 

I glanced at the fields module and I think it's the one I need to add code to, however can't seem to understand the right place for it, some direction here maybe.

**Comment by lukejagodzinski** [comment]
What is the pending index? The correct place to add any index functionality is the `indexes` module. You actually don't have to add any new fields/properties. It can be done in the apply definition hook. You just have to scan nested classes add collect all the nested indexes. Later you have to build indexes names and just add them to the collection.

**Comment by talha-asad** [comment]
@jagi You're right we don't need pending index, we can directly add it, but i don't know if there are easier ways to do what i am doing, not very familiar with the utilities or ways you use to determine things. Can you give the below code a go and see if this is good enough?

This is the apply definition hook file for indexes module.

``` js
import _ from 'lodash';
import throwParseError from '../../core/utils/throw_parse_error.js';

function onApplyDefinition(Class, parsedDefinition, className) {
    if (parsedDefinition.indexes !== undefined) {
        let Collection = Class.getCollection();

        if (!Meteor.isServer || (Collection && !Collection._connection)) {
            return;
        }

        let schema = Class.schema;

        // Add indexes to the collection
        _.each(parsedDefinition.indexes, function(index, indexName) {
            schema.indexes[indexName] = index;
            Collection._ensureIndex(index.fields, index.options);
        });

        // Add indexes to the collection from nested classes
        let classFields = Class.getFields();
        _.each(classFields, (field) => {
            if (Class.classes[field.type.name] && field.type.class === Class.classes[field.type.name]) {
                let nestedIndexes = Class.classes[field.type.name].getIndexes();
                _.each(nestedIndexes, (index, indexName) => {
                    schema.indexes[field.type.name + '_' + indexName] = index;
                    Collection._ensureIndex(index.fields, index.options);
                });
            }
        });
    }
};

export default onApplyDefinition;
```

**Comment by lukejagodzinski** [comment]
Ok you've started it correctly but there are some helper function that will make your life easier and code much more cleaner. Take a look at two methods:
- `Class.getObjectFields()`
- `Class.getListFields()`

The first one will return list of fields that have types being Astronomy classes (`type: CustomClass`)
The second one will return list of fields that have types being arrays of Astronomy classes (`type: [CustomClass]` but also `type: [String]`) I think I can improve this helper to take argument `class: true` so it will only return fields like `[CustomClass]`.

And later you can do what you did with creating nested names for indexes.

**Comment by talha-asad** [comment]
Thanks, I saw those helper functions but wasn't sure what they did. Do you think `schema.indexes[field.type.name + '_' + indexName] = index` is the right approach?

I'll try and add the argument to that helper as well.

**Comment by lukejagodzinski** [comment]
It should rather be `field.name + '_' + indexName`. I would also use `.` notation for consistency. As I think about it, they may also be a problem when extending a class definition with extra fields that may be of Astro class type. In such case it would not initialise indexes from nested classes... I have to think about a way of doing so.

**Comment by talha-asad** [comment]
Makes sense. I'll update you soon. Thanks.

**Comment by talha-asad** [comment]
[commit](https://github.com/talha-asad/meteor-astronomy/commit/26fcd7932684ca763f0ecfd1c5bbccd34324d57e)

Please review and let's think of a solution for:

> As I think about it, they may also be a problem when extending a class definition with extra fields that may be of Astro class type. In such case it would not initialise indexes from nested classes... I have to think about a way of doing so.

What will happen given our current situation, will those Astro Class field types not get indexed, isn't this limited to how we are scanning for fields? or is this related to the timing of module hooks?

**Comment by lukejagodzinski** [comment]
It looks quite good but there are some things that need fixing like collecting indexes from nested nested fields and nested nested nested fields etc. :). I'm actually working on it.

As I'm investigating it, I'm considering storing indexes in array instead of object. Right now we have to replace not only fields, name option but also object keys which is redundant.

**Comment by lukejagodzinski** [comment]
Ok nested indexes implemented. Sorry for not merging your commit but I had to rewrite a lot of things however I've used some parts of your code. And as I started doing it I've decided to finish it. Thanks a lot for your help!

Support for nested indexes in on GitHub so you can clone current version. I had one feature to implement before release. However the one I'm working on is causing me some problems. Closing for now. Let me know if it works.

**Comment by lukejagodzinski** [comment]
Oh could you create PR with Readme changes?

**Comment by talha-asad** [comment]
Sure, no problem and thanks. Just wanted to help :)

**Comment by talha-asad** [comment]
Getting this error from the latest clone:

``` bash
W20160721-14:59:52.354(5)? (STDERR) TypeError: Cannot read property 'indexes' of undefined
W20160721-14:59:52.354(5)? (STDERR)     at packages/jagi:astronomy/lib/modules/indexes/hooks/apply_definition.js:42:19
```

**Comment by talha-asad** [comment]
You skipped bringing in the changes for `Class.getListFields()`

That is whats causing the error.

**Comment by lukejagodzinski** [comment]
Oh right I forgot about that. Fixed. Check it out now.

**Comment by talha-asad** [comment]
[get_list_fields.js](https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/fields/class_static_methods/get_list_fields.js) still seems the same, forgot to push?

**Comment by lukejagodzinski** [comment]
Oh sorry it rejected push and I didn't notice that. Right now it should be available. Thanks!
