### ISSUE TITLE
[v2] Class Inheritance

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#368]
Consider the following:

``` js
Animals = new Mongo.Collection('animals');

Animal = Astro.Class.create({
  name: 'Animal',
  collection: Animals,
  typeField: 'type',
  fields: {
    _id: {type: String, index: 1},
    name: {type: String},
    options: {type: Object, default() { return {}; }}
  },
  methods: {
    speak() { return 'Animal does not know how to speak'; }
  }
});

Dog = Animal.inherit({
  name: 'Dog',
  fields: {
    color: {type: String},
    breed: {type: String}
  },
  methods: {
    speak() { return 'Woof'; }
  }
});

Cat = Animal.inherit({
  name: 'Cat',
  fields: {
    owner: {type: String}
  },
  methods: {
    speak() { return 'Meow'; }
  }
});
```

If a `Cat` and a `Dog` are inserted, doing a `Animal.find({}).fetch()` should return them both, however currently this not the case, is this by design or a bug?

**Comment by tjscooper** [comment]
When you're inheriting a model, I was not under the impression that you would also inherit a collection... Especially since you're extending the base class with new fields. I think you're going to have to specify a collection or you're stuck with a plain old object in memory.

**Comment by tjscooper** [comment]
If you add a collection, say 'cats', you'll see it hydrated with the base class fields within your cats collection as well as your new cat fields.

**Comment by talha-asad** [comment]
The advantage of mongodb being schema less is that you get to store many different sort of objects with varying schemas in one collection. This feature is available in all popular ORMs like mongoose. Everything works nicely besides the one issue I pointed.

**Comment by lukejagodzinski** [comment]
Hmmm it may be a good idea for improvement. I would have to treat it in a little bit different way than regular fetch. I will check what I can do about it.

**Comment by talha-asad** [comment]
Perhaps we could have an option to cast it in relevant subtype aswell. Can you tell me where this happens in code, hopefully i can submit a PR for this.

**Comment by lukejagodzinski** [comment]
That what I was thinking about so `Animal.find().fetch()` would return something like `[Dog, Dog, Cat, Cat]` not `[Animal, Animal, Animal, Animal]` which would make little sense

**Comment by Ben305** [comment]
@jagi It would be also pretty nice if one could overwrite the collection for a child class (and omit the type field in this case). We have several business cases where child objects should be stored in own collections, at the moment this is only possible with workarounds.

**Comment by katrotz** [comment]
@jagi Actually getting `[Cat, Cat, Dog, Dog]` makes perfect sense as long as these behave like animals inheriting its methods and properties, IMHO

**Comment by lukejagodzinski** [comment]
@katrotz yes they will inherit all methods and fields from the `Animal` class.

**Comment by lukejagodzinski** [comment]
Ok I've implemented it and I've added some extra possibilities:
- `Animal.find({}, {children: false}).fetch();` - will return only instances of the `Animal` class
- `Animal.find({}, {children: true}).fetch();` - will return instances of classes `Animal`, `Cat` and `Dog`

**Comment by lukejagodzinski** [comment]
This feature will appear in 2.1

**Comment by talha-asad** [comment]
Is there a way to manually download this change, I notice there is no 2.1 branch

**Comment by lukejagodzinski** [comment]
It's on v2 branch. You can just clone it

**Comment by fumbleforce** [comment]
Fantastic! I've been running into scenarios when this is extremely useful. When having a "Task" collection with different types of tasks, like "ShoppingTask" and "MaintainanceTask", it is really sweet to just query the Task collection for all the tasks in a combined Task list. When finding a task by ID afterwards, you can then also just query the Task collection instead of all the inherited models.

**Comment by jcheroske** [comment]
Possibly related issue/question: Can nested classes also make use of inheritance? Can I do this:

```
Person = Class.create({
   pets: [Animals]
});
```

And will the `pets` array contain the correct subclasses?

**Comment by lukejagodzinski** [comment]
@jcheroske no it won't work as inheritance only works for classes with assigned collection.

**Comment by jcheroske** [comment]
Then my next question is, why is that the case? Isn't just having a type
field enough to do the polymorphism?

**Comment by lukejagodzinski** [comment]
@jcheroske The type field is a requirement to have the polymorphism however I also need to know the inheritance tree. If you want you can implement your own inheritance/polymorphism.

**Comment by jcheroske** [comment]
I think it would be an awesome feature to be able to have polymorphic nested classes with just the `typeField` property specified on the parent class, and the parent class specified as the nested class.
