### ISSUE TITLE
[v2] file level import not read in events

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#369]
Let's say I add create a file: 

```
import {User} from "path";

const Profile = Class.create({
...
events: {
 afterInit() {
  User.findOne(...)    /// gives error, findOne of undefined. 
 }
}
})

```

Using a `const { User } = require(..)` in afterInit function, also gives the same error?

What am I doing wrong? Or is this a bug?

**Comment by lukejagodzinski** [comment]
Are you exporting the `User` class properly in the `path.js` file?

**Comment by s7dhansh** [comment]
Yes `export {User}`

It is working properly else where.

**Comment by s7dhansh** [comment]
It seems to be some other issue. I will investigate fully and report.

**Comment by lukejagodzinski** [comment]
Ok

**Comment by s7dhansh** [comment]
Do you use afterInit or other events at any place where imports may not be available?

The problem is weird and I am not able to reproduce it properly. There are a few classes (and only few classes) which are deemed to be undefined if I put them directly in the afterInit function. If I simply wrap them inside a function and call the latter in afterInit, things work properly. It may not necessarily be an Astronomy issue as such, and may be related to some import problem. If I am unable to figure out something this week, will close it.

In case someone faces such an issue, just try to wrap the usage of the class inside a function.

**Comment by lukejagodzinski** [comment]
Could you give an example of such a function wrapping?

Sorry for responding so late but I'm on my business trip and I'm not working a lot on Astronomy.

**Comment by s7dhansh** [comment]
Sorry, I too have paused the v2 migration. That issue with nested objects is a major one. Once that is fixed, I will resume the migration and will be able to give you code samples for this problem too.
