### ISSUE TITLE
Why is insecure the default in 2.0?

### ISSUE THREAD

**Issue by ndarilek** [jagi/meteor-astronomy#370]
Not sure if it was this way in V1 and I didn't notice because I'm not in production yet, but it's kind of mind-blowing that I have to opt _in_ to security. The only argument I can come up with for this is that Meteor apps start out with autopublish/insecure, but everyone developing to the point where they're pulling in Astronomy has likely removed those anyway. If they want autopublish/insecure, then why not let the insecure opt-in be keeping those packages, rather than opting out by removing them _and_ making sure every single model class they add includes `secure: true`? That's not even a global opt-in, it's an opt-in on every single model, and if I don't catch that changing in code review then I've opened a security hole.

Somewhat disappointed that insecure is the default, and worried about what other changes I've missed. It wasn't mentioned in the upgrade notes either, so either this has been true all this time or you've just opened a potential security hole in everyone who upgrade's apps when they think that reading the upgrade section is all that is needed.

Thanks for all your work on this project. It definitely makes working with Meteor models so much easier. But I'm very disappointed in this default choice, and in my need to perpetually opt into security.

**Comment by lukejagodzinski** [comment]
I understand your worries. Right now it would be hard to change this behavior because it's compatibility breaking. Of course I could introduce global setting for that but that isn't perfect solution either. To be honest I've just chosen classes to be insecure by default because it's what I use the most. In fact every developer should put a lot of attention into security. If you have a good idea how to solve this problem in the next version and make it non compatibility breaking, then I'm open for discussion.

**Comment by marbemac** [comment]
I agree with this, and brought it up several times over the past 5 months. @jagi, I would suggest shouting this in bold at the top of the release notes / migration guide, and at the top of the documentation. IMHO, this is one of the most significant changes from v1, and it's not even mentioned in the migration guide, which is kind of odd...

**Comment by lukejagodzinski** [comment]
I'm considering breaking backward compatibility in 2.1 and change it to be secured by default. Maybe people will not complain about that :)

**Comment by lukejagodzinski** [comment]
Ok I've change classes to be secured by default. It will be compatibility breaking change in 2.1. I hope people will not be pissed of.

**Comment by ffxsam** [comment]
@jagi You might consider updating the documentation.

> Every Astronomy class is not “secured” by default and any operation from the client is allowed.

**Comment by lukejagodzinski** [comment]
@ffxsam I will update with 2.1 publication
