### ISSUE TITLE
TypeError: ["User" class]["fields" property]["emails" field] Type does not exist

### ISSUE THREAD

**Issue by ickyrr** [jagi/meteor-astronomy#371]
Hi, i'm trying to create a fresh meteor 1.3 app and trying to create it with astronomy, a great package BTW. 

I would like to integrate it to Meteor.users but I could not get it to work. I could not find good examples on the web based on my needs.

Here's my `models/users.js`:

```
import { Class } from 'meteor/jagi:astronomy';

User = Astro.Class.create({
  name: 'User',
  collection: Meteor.users,
  fields: {
    username: String,
    emails: Array,
    roles: Array,
    firstname: String,
    lastname: String
  }
});

if(Meteor.isServer){
  User.extend({
    fields: {
      services: Object
    }
  });
}

```

It gives me an error:
`Uncaught TypeError: ["User" class]["fields" property]["emails" field] Type does not exist`

And also, do you have any complete examples for doing this on Meteor.users?

Thanks in advance..

**Comment by lukejagodzinski** [comment]
There is not `Array` type. Use `[Object]` instead.

**Comment by ickyrr** [comment]
I see, thanks @jagi!
