### ISSUE TITLE
getting astronomy magic in lists

### ISSUE THREAD

**Issue by JanMP** [jagi/meteor-astronomy#372]
I have been using manuel:viewmodel for a while now and I am just trying out astronomy for the very first time.

I was wondering about the inconsistencies between the .findOne() and .find() methods.
findOne returns an astronomy object with all it's goodness, but find just returns the old unmagical Mongo cursor? So I came up with this:

``` coffee-script
# this is coffee-script
Items = new Mongo.Collection "charts"
Item = Class.create
  name : "Item"
  collection : Items
  fields :
    symbol : String
    name : String

Template.list.viewmodel
  items : ->
    Item.find().fetch().map (e) -> item : Item.findOne(_id : e._id)
```

The last line fetches the cursor and returns an array with the astronomy objects. Now I can do something like this and get working without any additional viewmodel code:

``` Jade
// this is Jade
template(name="list")
  .ui.container.segment
    .ui.divided.list
      each items
        +listItem

template(name="listItem")
  .item
    .right.floated.content
      i.delete.icon($b="click:item.remove")
    .content
      .header #{item.symbol}
      .description #{item.name}
```

 It works pretty well, but I was wondering if there was a better way to do it.

 It would seem to make a lot of sense if Item.find() would just do something like that out of the box instead of returning the same result as Items.find().

**Comment by lukejagodzinski** [comment]
Please do not use CoffeeScript and Jade in examples. I don't use them and it's hard to figure out what's going there. Why do you need to put each `item` under `item` property?

To understand why the `find()` method returns cursor instead pure data you have to read more about reactivity and how Blaze uses it to limit amount or renders. Thanks to that it's much faster.

**Comment by JanMP** [comment]
Yeah, my solution looked amazingly good at first sight, after a bit more dabbling with it I came across some of the problems you mentioned. Working on a different solution...

**Comment by JanMP** [comment]
the astronomy.find() puts loads of functions into the data context. Like:

copy: function(save)
dispatchEvent: function(event)
get: function()
getModified: function()
getModifiedValues: function()
getModifier: function()
isModified: function(pattern)
raw: function()
reload: function()
remove: function()
save: function()
set: function()
 _allSubsReadyDep: Dependency, …}
toJSONValue: function(args)
typeName: function()
validate: function()
validateAll: function()

Are they meant to be useful in any way? I know they are not working, because I tried them out quite a lot this afternoon, when I was trying to find out, why my own remove method did not work. That's because your .find() was polluting the viewmodel namespace and I did not get those errors from my own method (wich is working fine) but from yours.

**Comment by lukejagodzinski** [comment]
If you're not using these methods that mean that you probably don't need Astronomy because they are essential to what Astronomy does. Have you read documentation? http://jagi.github.io/meteor-astronomy/v2

**Comment by JanMP** [comment]
Yes. I have read it. And I am not using them because I can't get them to work, like they should. I wouldn't spend a whole day, trying to figure it out, If I didn't want to get all those methods to work properly.

And I found the problem. Its actually ViewModel, that's causing all this mess. ViewModel takes templateInstance.data and chops it into little pieces. So you can't just do something like templateInstance.data.save() anymore (well, actually you could, ViewModel keeps the original templateInstance in this.templateInstance, but that's rather inconvenient and you still have the broken methods all over ViewModel's namespace)

Btw. your docs explain how to call methods when you use user = User.findOne() but I didn't find a description on how to call them on templateInstance.data when you render a list with {{#each users}}

You might want to add that.

**Comment by lukejagodzinski** [comment]
I was getting many questions from users using Astronomy with ViewModel and all of them managed to use it properly. So, you are probably doing something wrong. I've never used ViewModel so I can't help with that until you show me some code that's causing a problem.

I don't see a point of describing "how to call methods" in templates? What do you exactly mean by that?

**Comment by JanMP** [comment]
I will ask ViewModel people then. You can't really help me with that. I came up with a workaround, by using regular Collection.find() to render the list and then use AstronomyClass.findOne() from inside the list-item ViewModel to get a data object with working methods attached to it. It's working.
