### ISSUE TITLE
[v2] Array fields can't be set to blank array, with validation

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#374]
eg.
               email: {
            type: [String],
            validators: [{
                type: "email",
            }],
            default() { return []; }
        },

When blank array, it gives validation errors for emails. Is that supposed to be a feature?

**Comment by lukejagodzinski** [comment]
You have to know that validation if performed on the entire field so `["example@mail.com"]` is definitely not an email address it's an array of email addresses. Read about the `every` validator http://jagi.github.io/meteor-astronomy/v2#validators-list

**Comment by s7dhansh** [comment]
Yes, my bad.
Thank you for pointing out.
