### ISSUE TITLE
[v2] MinimongoError: cannot use the part '...' to traverse undefined/null

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#375]
In nested classes,

eg.

```
Cancellation = Class.create({
 name: ...
 fields: {
   flag: Boolean,
   reason: String
 }
})

Order = Class.create({
 ...
 cancellation: {
  type: Cancellation,
  optional: true
 }
})
used in say Order Class for collection orders.
```

Now, in the database, if order.cancellation is null or undefined - I get this error

```
MinimongoError: cannot use the part '...' to traverse null < or undefined if the data is undefined >
```

I believe it is related to https://github.com/aldeed/meteor-autoform/issues/142 and https://jira.mongodb.org/browse/SERVER-5143. So, it is a MongoDB error.

So, I am left with only one solution for now, set a default "{}" for cancellation class, in which case Astronomy creates the complete object in the first go itself.
1. Minor Con: Increase in db size.
2. Major Con: All fields must have a default value or must be marked as optional. Otherwise, the validation will fail and the object will fail to save.

Is there a way to solve this, either in Astronomy, or in my own code?

**Comment by lukejagodzinski** [comment]
You gave to little details. How are you using it? Marking the `order.cancellation` field as optional should allow filling it with null or undefined value. If it's doesn't then it's not Astronomy fault.

**Comment by s7dhansh** [comment]
Update the initial comment with more details.
I have already marked `order.cancellation` as optional. I am also not saying that it is Astronomy's fault. I have already linked the MongoDB error (https://jira.mongodb.org/browse/SERVER-5143).

I am asking if there is any other hack which Astronomy or I can use - to fix the mongo issue linked above.

**Comment by s7dhansh** [comment]
If still things are unclear, you may specify the doubts, or else I will try and create a reprod sometime soon.

**Comment by s7dhansh** [comment]
@jagi https://github.com/s7dhansh/astronomy-problem

I have neglected the issues with MongoDB for now. There is also a problem with Astronomy though which I have highlighted in the repo. Kindly run it and see the error in JS console. 

The problem is with nested Date fields. If the field is not set earlier (in the db), and then through Astronomy we try to set a nested class (with a date field), it errs:
[validation-error] <nested>.<date> must be Date.

**Comment by lukejagodzinski** [comment]
Ok the other problem you had was already fixed and this one is somehow related with `Autoform` rather than `Astronomy`. I think there is no possible situation when setting nested fields would cause a problem. Because I'm doing exactly what Aldeed wrote about this problem. I'm comparing previous and current value and try to create modifier that will be properly executed. I can do it efficiently because of how Astronomy is structured. It allows me to easily compare current and previous version of a document and set nested documents without executing forbidden dot notation.

**Comment by s7dhansh** [comment]
@jagi I am not using Autoform. I am using my own custome forms package, but it is just a frontend layer and has nothing to do with astronomy.

If you have figured out the problem and there is no solution, well nothing can be done about it then :).

Though I would like to  suggest a solution. I have no idea how many people are using Astronomy for collections which already have non-Astronomy data (documents stored without Astronomy.save()), hence deciding the priority for this is entirely upto you. [As mentioned before, I have only come across this issue for older non-astronomy data.]
1. check a field for being a nested class, and null at the same time.
2. if true, then set this field as an object/array (depending on its type) - without validation check on the sub-fields of the nested class.
3. proceed with normal astronomy save - which will set the fields as per the data.

It involves one extra save (step 2), but will do the trick.

If you decide to not implement it, I will change my backend data to have dummy objects/arrays instead of nulls, because storage is much lesser an issue than not being able to use Astronomy v2 :).

**Comment by lukejagodzinski** [comment]
I still don't understand your problem. It's has nothing to do with Astronomy.
