### ISSUE TITLE
[v2] New Behavior

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#377]
@jagi 
I have created a new behavior based on your timestamp: https://github.com/settlin/meteor-astronomy-meta-behavior. It is more like a v2 of timestamp, but I created a new repo instead of a PR because of the unsuitability of the repo name.

If you agree, I would like to transfer the ownership to you and you can publish it on atmosphere.

**Comment by lukejagodzinski** [comment]
No it's ok that you're the owner this repository. You can publish it under your name and if you want you can just add be as contributor. I will create new sections in Astronomy readme: community packages where I will list all packages worth using and also the Made with Astronomy section where I will show what apps where made using it.

**Comment by s7dhansh** [comment]
@jagi added you as admin.
https://atmospherejs.com/settlin/astronomy-meta-behavior
