### ISSUE TITLE
[v2] Softremove error

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#378]
If I use

```
var user = Users.findOne();
user.softRemove();
```

as per the documentation, I get: user.softRemove is not a function

If I use `User.findOne`, I get: wrapCallback is not a function.

Is this a bug?

**Comment by lukejagodzinski** [comment]
You can't use the `softRemove` method with document coming from collection `Collection.findOne()`. You always need astronomy document so you get it using `Class.findOne()` and in your situation `User.findOne()`. However if it's throwing that error it may mean that I forgot to import this method, so I will have to make a fix. However I can't check it now as I'm traveling. I will take a look at it later.

**Comment by s7dhansh** [comment]
Please update the documentation then. It says to use it on the db document itself.

**Comment by lukejagodzinski** [comment]
Oh right there is an error in a documentation, thanks!

**Comment by lukejagodzinski** [comment]
Ok, I've checked and it's working as expected when used with `Class.findOne()`. There is no error related to the `wrapCallback` method. Are you using the 2.0.1 version?

**Comment by s7dhansh** [comment]
No yesterday I was on 2.0. I updated today but haven't tested. I will test on 2.0.1 and revert.

**Comment by s7dhansh** [comment]
@jagi I am still getting the same error. Any ideas?
![shot](https://cloud.githubusercontent.com/assets/706996/15298325/62f6d7a0-1bbc-11e6-9321-03f6b56e033c.png)

Reproduction: https://github.com/s7dhansh/astronomy-problem - branch "softremove"
Click on the button and see JS console.

I am using 2.0.1 - both astronomy and softremove. (I have also tried latest github v2).

**Comment by lukejagodzinski** [comment]
Oh sorry I was talking about the `softremove` repo that is on GitHub but not yet published to the atmosphere. I will publish it now.
