### ISSUE TITLE
[v2] Class inheritence and different collections

### ISSUE THREAD

**Issue by Ben305** [jagi/meteor-astronomy#379]
From #368: It would be also pretty nice if one could overwrite the collection for a child class (and omit the type field in this case). We have several business cases where child objects should be stored in its own collections, at the moment this is only possible with workarounds.

**Comment by lukejagodzinski** [comment]
@Ben305 yep good idea. I will implement that however I don't know how soon. But it's definitely worth spending time on.

**Comment by lukejagodzinski** [comment]
Feature implemented and will appear in 2.1.0. However I have a question about omitting typeField in child class. Would you like to have typeField in the parent class and inherit this class in the child but without typeField?

**Comment by Ben305** [comment]
Cool, thanks. For different collections, I would like to omit the type field.

**Comment by lukejagodzinski** [comment]
By saying "omit" you mean that there should be not typeField or it should just inherited?

**Comment by Ben305** [comment]
There should be no type field. It is not needed since different collections are used.

**Comment by lukejagodzinski** [comment]
So isn't just enough to omit type field in both classes? Just don't use the `fieldType` property in classes definitions.

**Comment by Ben305** [comment]
If it is possible to have different collection for a child class without needing specifying type fields in parent and child classes, this is perfect :-)

**Comment by lukejagodzinski** [comment]
Ok so it works that way :)
