### ISSUE TITLE
Ability to mass-set attributes before .save() (update, not new object)

### ISSUE THREAD

**Issue by jsilverMDX** [jagi/meteor-astronomy#38]
Vanilla meteor allows you to pass a hash to an .update() call using $set. This feature is missing from Astronomy. (or is it?) It's definitely missing from the docs.  Is there a way to do this in Astronomoy, similar to mass-setting the parameters in a new Object(hash) call? Thanks!

eg.
```javascript
var obj = {"name": "blah", "title": "name"}
// ast is an astronomy object
ast.update(obj)
ast.save()
```

**Comment by jsilverMDX** [comment]
Note: I solved it with code like

```javascript
        $.each(Session.keys, function(key, val){
          show[key] = Session.get(key);
        })
```

But I still think it's a good idea for a feature.

**Comment by jagi** [comment]
I don't know if I understand you correctly but you would solve your problem by just using the `set` function.

```js
ast.set({
  name: 'blah',
  title: 'name'
});
ast.save();
```

The `set` function can set not only one attribute but multiple attributes at once.

Does it solve your problem?

**Comment by jsilverMDX** [comment]
@jagi yes that is exactly what I was looking for. Don't know how I missed it. This will clarify my code. Thanks for this and a great library! :+1:

**Comment by jagi** [comment]
Glad that I could help. Enjoy :)
