### ISSUE TITLE
Objects with modified date fields are not saved in the database

### ISSUE THREAD

**Issue by laucheukhim** [jagi/meteor-astronomy#380]
If you update an object by modifying its date field only, it will not be saved to the database.

Let's say I have the following schema and an existing object of that class.

``` javascript
const Phone = Astro.Class.create({
    name: 'Phone',
    collection: new Mongo.Collection('phones'),
    fields: {
        name: String,
        releaseDate: Date
    }
});

let phone = new Phone();
phone.name = 'iPhone';
phone.releaseDate = new Date(2007, 5, 29);
phone.save();
```

If I update this object to change its date field, it will not be saved to the database.

``` javascript
let phone = Phone.findOne({ name: 'iPhone' });
phone.releaseDate = new Date(2016, 2, 31);
phone.save();
```

In MongoDB the object still has the old date.

``` javascript
{ 
    "_id" : "G5zHXbL77qf4cH8Wn",
    "name" : "iPhone",
    "releaseDate" : ISODate("2007-06-29T00:00:00.000+0000")
}
```

However, if I update other fields as well as the date field, all fields will be saved properly.

``` javascript
let phone = Phone.findOne({ name: 'iPhone' });
phone.name = 'iPhone SE';
phone.releaseDate = new Date(2016, 2, 31);
phone.save();
```

``` javascript
{ 
    "_id" : "G5zHXbL77qf4cH8Wn",
    "name" : "iPhone SE",
    "releaseDate" : ISODate("2016-03-31T00:00:00.000+0000")
}
```

**Comment by lukejagodzinski** [comment]
Yes in deed there is some problem. It's actually not detecting that document is modified but it knows what changes were made. So it's like some little bug that I'm going to fix today.

**Comment by lukejagodzinski** [comment]
I've fixed it and I will publish it in the next bug fix version. I will do it in the next week.

**Comment by Ben305** [comment]
Is the fix available on GitHub? I'm running into the same problem.

**Comment by lukejagodzinski** [comment]
@Ben305 yes fix is available in the latest version available on GitHub in the `v2` branch

**Comment by laucheukhim** [comment]
@jagi Do you have a timeline for the next release? We have been waiting for this bug fix for quite a while.

**Comment by Ben305** [comment]
Just use the current HEAD as local package.

**Comment by lukejagodzinski** [comment]
Sorry I have a lot of work lately and I don't have a lot of free time. I'm trying to do my best to release it as soon as possible. As @Ben305 said, try using Astronomy locally. Just clone it to you project's `packages` directory.
