### ISSUE TITLE
validation for mdg:validated-method

### ISSUE THREAD

**Issue by JanMP** [jagi/meteor-astronomy#381]
Is there a way to use astronomy for simple validation of arguments in mdg:validated-method?

**Comment by jhuenges** [comment]
I was wondering the same. For now, I am using the `method` object that comes with the class. However, I am not sure if that is best practice...

**Comment by lukejagodzinski** [comment]
What rules do you exactly want to check? If they are simple rules then why not just use the `match` package? If they are more complex rules then you may use Astronomy for that but I don't think it's a good choice. I would rather use to check Astronomy for document's validity and integrity not just for method's arguments. However, I will probably allow something like easy arguments checking in Astronomy. It would look like following

``` js
User = Class.create({
  name: 'User',
  /* ... */
});

Meteor.methods({
  methodName(data) {
    User.validate(data);
  }
});
```

But right now it's not planned for 2.1. So if there is a big demand for such a feature then I will consider implementing it.

**Comment by JanMP** [comment]
I was going for the recommended mdg:validated-methods
AFAIK `match` doesn't do, because it doesn't throw the proper errors. According to the Meteor Guide Astronomy throws the proper errors.

**Comment by lukejagodzinski** [comment]
Yes Astronomy throw proper errors that can be handled in Autoforms from what I know. We used `mdg:validation-error` in Astronomy and SimpleSchema (I don't know if it's already using it) to consolidate our efforts in making it easier to switch between packages and to be able use autoform with both Astronomy and SimpleSchema. I don't know if it's going to work right now or with future versions of autoform.

**Comment by jcheroske** [comment]
Just an FYI: SimpleSchema has a `validator()` method:

"Call `mySimpleSchema.validator()` to get a function that calls `mySimpleSchema.validate` for whatever object is passed to it. This means you can do validate: `mySimpleSchema.validator()` in the mdg:method (now called `mdg:validated-methods`) package. If you set the clean option to true, then the object will be cleaned before it is validated. If you want to change any of the default cleaning options, you can pass in those, too."

I think, since Astronomy is already using `mdg:validation-error`, adding a similar method to Astronomy would be fairly trivial and would then give developers a choice of schema packages when using `mdg:validated-methods`.

**Comment by lukejagodzinski** [comment]
Yes I'm opened to discussion about new features. I will probably add a new module that will handle populating object with data coming from forms which includes cleaning data. And if it goes about validating any object, I'm also going to introduce a new method on the level of the class and you will use it in the following way.

``` js
const MyClass = Class.create({
  name: 'MyClass',
  /* ... */
});

MyClass.validate({
  somePlainObjectProp: 'somePlainObjectValue'
});
```

**Comment by jcheroske** [comment]
Fantastic!

**Comment by tzapu** [comment]
i would be very interested in something like this as well, validate an object based on an astronomy schema.
it would come in very handy for validating users with Accounts.validateNewUser so you can reuse the astronomy schema.
this is of course unless i m missing something very obvious and you can use Account.createUser with astronomy already.

Cheers

**Comment by lukejagodzinski** [comment]
Implemented and it will be published with the next minor release. For now it can be cloned from GH to the local packages directory. Closing it for now.
