### ISSUE TITLE
[v2] Arrays in nested objects replaces with objects on save

### ISSUE THREAD

**Issue by krizka** [jagi/meteor-astronomy#383]
I have Object and Nested, something like
pseudocode:

```
Nested: {
  array: [String]
}

Object: {
  nested: Nested
}
```

After

```
object.nested = { array: [] }
object.save()
```

`object.nested.array` contains `{}`. After digging down and debug I found `omitUndefined` function where _.isObject thinks array is object too. Please fix it.

```
    if (_.isObject(value)) {
      result[key] = omitUndefined(value);
    }
    else if (!_.isUndefined(value)) {
      result[key] = value;
    }
```

**Comment by lukejagodzinski** [comment]
I've already fixed it but it's not published yet. I will probably publish
it next week.

**Comment by lukejagodzinski** [comment]
I'm closing it right now as it was fixed. I will publish a new version soon.
