### ISSUE TITLE
[v2] fieldPattern.indexOf is not a function on validate.

### ISSUE THREAD

**Issue by zachariahtimothy** [jagi/meteor-astronomy#384]
During model validation, I am receiving the error "is_nested_field_name.js:2 Uncaught TypeError: fieldPattern.indexOf is not a function".
I placed a debug point and found it fails when there are non-strings in the model. For instance, this fails when it checks a Number type in my model. 

```
function isNestedFieldName(fieldPattern) {
  return fieldPattern.indexOf('.') !== -1; // FAILS when non-string value
};
```

Calling code looks like so:

```
const newBoat = new Boat(boatData);
const isValid = newBoat.validate({});
```

**Comment by lukejagodzinski** [comment]
First of all the `validate` method does not return anything. However tell
me what's inside `boatData` and how your model looks like.

**Comment by zachariahtimothy** [comment]
Yeah I was not sure validate() returned anything, I was just debugging.
Model is as follows:

import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';
import { Class } from 'meteor/jagi:astronomy';
import { LengthUnit } from './enums';
import Amenity from './amenity';

const Boats = new Mongo.Collection('boats');

const BoatSpec = Class.create({
name: 'BoatSpec',
fields: {
length: {
type: Number
},
lengthUnit: {
type: LengthUnit,
optional: true,
default() {
return LengthUnit.FEET;
}
},
draft: {
type: Number,
optional: true
}
}
});

const Model = Class.create({
name: 'Boat',
collection: Boats,
fields: {
name: {
type: String,
unique: true,
validators: [ {
type: 'minLength',
param: 2
} ]
},
description: {
type: String,
validators: [ {
type: 'minLength',
param: 25
} ]
},
specs: {
type: BoatSpec,
default() {
return {};
}
},
amenities: {
type: [ Amenity ],
optional: true
},
userId: {
type: String,
immutable: true,
default() {
return Meteor.call('currentUserId');
}
}
},

behaviors: {
slug: {
fieldName: 'name',
slugFieldName: 'slug',
canUpdate: true,
unique: true,
separator: '-'
},
timestamp: {
hasCreatedField: true,
createdFieldName: 'createdAt',
hasUpdatedField: true,
updatedFieldName: 'updatedAt'
}
}
});

Meteor.methods({
currentUserId() {
return Meteor.userId() || 'SYSTEM';
}
});

export default Model;

---

Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis https://twitter.com/#!/@zachariahCurtis

**Comment by zachariahtimothy** [comment]
With a little more debugging I found it does not like the BoatSpec model. I
suspected the Enum was the problem but even with that commented out it does
not work. If I comment out BoatSpec completely it works. I tried importing
the BoatSpec model individually and just validating that as a separate
model but that does not work either. I will keep digging but it seems to be
related to the Number type.

---

Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis https://twitter.com/#!/@zachariahCurtis

**Comment by lukejagodzinski** [comment]
There are a lot of things happening in your code. You have custom type what can also be a problem. You have to create reproduction repository. Without that it's hard to tell what may be a cause of your problem.

**Comment by lukejagodzinski** [comment]
Oh maybe try changing a name of the `length` field. It may be a problem with that I thought that I've already fixed.

**Comment by lukejagodzinski** [comment]
Ok I think that I've found a problem. It's a problem with the `length` property. I've already fixed this problem in previous versions but the bug was introduced one more time because of another bug in lodash. So I have to change a method that I'm using to perform some internal operations.

**Comment by lukejagodzinski** [comment]
Bug fixed and it's on GitHub. I will publish it the next week.

**Comment by zachariahtimothy** [comment]
Thank you, I will try it out shortly.

---

Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis https://twitter.com/#!/@zachariahCurtis
