### ISSUE TITLE
Double number in astronomy ?

### ISSUE THREAD

**Issue by sieutruc** [jagi/meteor-astronomy#386]
Hello,
in simple schema, i can defined a field of type "number" with "decimal": true , it means a non-integer.

How can i achieve the same thing with astronomy ?

**Comment by lukejagodzinski** [comment]
You just use the `Number` type as it's still double no matter if you put there integer or float. It's how JavaScript and MongoDB works. In SS you have this option because of validation. I will probably introduce `integer` and `float` validators in the next version.

**Comment by sieutruc** [comment]
Iam appreciated your answer :)

If it is possible, can you show me how to test mongo.objectid ? i see the doc mentions about mongo.ObjectId, but when i use this type, i get an error even the variable gets its value from user.id ...

**Comment by lukejagodzinski** [comment]
@sieutruc just show some example code then I may help you. Without that it's hard to tell what's going on. Are you importing `Mongo.ObjectId` from the Mongo package in the class definition?

**Comment by sieutruc** [comment]
I define my collection like below

const Test = Class.create({
    name: "Test",
    collection: Likes,
    fields: {
        userId: {
            type: Mongo.ObjectID, // has to be checked for objectid
            optional: false
        },
        testId: {
            type: Mongo.ObjectID,
            optional: false
        }
    },
    indexes: {
        userTestIndex: {
            fields: { // List of fields.
                userId: 1,
                testId: 1
            },
            options: {
                unique: true
            }
        }
    }
});

I assigned the user.id to the field userId of Test collection : 

"userId": user._id,

and here what i got :
Error: "userId" has to be a Mongo.ObjectID [validation-error]

Do you know how i can test mongo.objectId like "regEx:SimpleSchema.RegEx.Id" in simpleschema ?

**Comment by lukejagodzinski** [comment]
Are you using Mongo.ObjectID in collection definition? By default collections are using string IDs. So if you didn't change that, then just use the `String` type instead of the `Mongo.ObjectID`.

**Comment by sieutruc** [comment]
Yes, i did. i saw in the documentation 

"There are several predefined types. You can choose from: ....
Mongo.ObjectId ?"

Do you know how to test if the field is a mongodb object id ? or will i create a validator by myself ?

**Comment by lukejagodzinski** [comment]
Oh I forgot to describe it in the documentation. There is the `mongoObjectID` validator https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/validators/validators/type/mongo_object_id.js

If you set field's type to `Mongo.ObjectID` then this validator will be applied automatically to the field. However, you can also access this validator directly if you want:

``` js
import { Validators } from 'meteor/jagi:astronomy';

Validators.mongoObjectID();
```

Your problem seems to be related with how `Meteor.users` collection stores user objects. It probably uses strings for IDs instead of `Mongo.ObjectID`. I don't have time to check it out how to change that. But I think it's possible but you have to look for the solution. To make sure that right now it's not using `Mongo.ObjectID` do `console.log(Meteor.userId())`

**Comment by lukejagodzinski** [comment]
I think that here is an answer to your problem http://stackoverflow.com/questions/24964005/using-mongo-objectid-type-for-meteor-user-ids

**Comment by purplecones** [comment]
@jagi I still get this error:

```
I20160601-15:57:21.239(-4)? 0.02
W20160601-15:57:21.301(-4)? (STDERR)
W20160601-15:57:21.302(-4)? (STDERR) /Users/xxx/.meteor/packages/meteor-tool/.1.3.2_4.yt9u9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160601-15:57:21.302(-4)? (STDERR)                            throw(ex);
W20160601-15:57:21.302(-4)? (STDERR)                                  ^
W20160601-15:57:21.544(-4)? (STDERR) Error: "current_return" has to be a number [validation-error]
W20160601-15:57:21.544(-4)? (STDERR)     at new _class (packages/mdg:validation-error/validation-error.js:14:12)
W20160601-15:57:21.544(-4)? (STDERR)     at throwError (packages/jagi:astronomy/lib/modules/validators/validator.js:63:15)
W20160601-15:57:21.544(-4)? (STDERR)     at Validator.validate (packages/jagi:astronomy/lib/modules/validators/validator.js:89:9)
W20160601-15:57:21.544(-4)? (STDERR)     at Object._validators2.default.(anonymous function) [as number] (packages/jagi:astronomy/lib/modules/validators/validator.js:101:17)
W20160601-15:57:21.545(-4)? (STDERR)     at Type.validate (packages/jagi:astronomy/lib/modules/fields/types/number.js:8:16)
W20160601-15:57:21.545(-4)? (STDERR)     at ScalarField.validate (packages/jagi:astronomy/lib/modules/fields/scalar_field.js:18:24)
W20160601-15:57:21.545(-4)? (STDERR)     at packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:109:13
W20160601-15:57:21.545(-4)? (STDERR)     at catchValidationError (packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:38:7)
W20160601-15:57:21.546(-4)? (STDERR)     at packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:67:28
W20160601-15:57:21.546(-4)? (STDERR)     at arrayEach (/Users/xxx/.meteor/packages/jagi_astronomy/.2.0.1.ecfp2t++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:498:11)

```

when trying to insert a decimal even though I declared

```
...
current_return: {
 type: Number
},
...
```

The value that is being inserted is `0.02`

I am using the following version:

```
jagi:astronomy@2.0.1
jagi:astronomy-timestamp-behavior@2.0.0
```

**Comment by lukejagodzinski** [comment]
So what's wrong with the number `0.02` being inserted? If you put `0.02` in the `current_return` field, then it will be exactly what's gonna be inserted. What's your expected outcome?

**Comment by purplecones** [comment]
@jagi I want the value `0.02` to be inserted but it is not allowing me to and throws the error above. I am generating dummy data at first launch. When the document gets inserted with `0.02` value for `current_return` it throws the error. However, if I insert the value `5` for example, it does not throw error.

**Comment by lukejagodzinski** [comment]
Are you sure that it's a number and not string? If value comes from the form it may be a string. In such situation you may need to use `parseFloat(value)` before setting the `current_return` field's value

**Comment by purplecones** [comment]
right on @jagi, faker was returning a string: https://github.com/practicalmeteor/meteor-faker/blob/meteor/lib/finance.js#L51

**Comment by lukejagodzinski** [comment]
Ok good
