### ISSUE TITLE
Can't save nested array of classes

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#387]
I have the following schemas:

```
const Participant = Class.create({
  name: 'Participant',
  secured: false,

  fields: {
    lastViewed: {
      type: Date,
      default: new Date(),
    },
    userId: String,
  },
});

export const Conversation = Class.create({
  name: 'Conversation',
  collection: Conversations,
  behaviors: ['timestamp'],
  secured: false,

  fields: {
    startedBy: {
      type: String,
      immutable: true,
    },
    participants: {
      type: [Participant],
      default() {
        return [new Participant({ userId: Meteor.userId() })]
      },
    },
  },

  methods: {
    // ...
    markAllAsRead() {
      const index = this.participants
        .findIndex(p => p.userId === Meteor.userId());

      this.participants[index].lastViewed = new Date();
      console.log(this.participants);
    },
  },
});
```

After calling `c.markAllAsRead()` and `c.save()`, the data is not saved in the database. I've tried everything I can think of.

**Comment by lukejagodzinski** [comment]
This sample code is not enough to tell what can be wrong. You have to prepare reproduction repository. The problem is probably not in Astronomy.

**Comment by ffxsam** [comment]
Does this code look correct, then? Is there a better way to set an Astro class within an array?

I'll get to building a reproduction repo in a couple days.

**Comment by lukejagodzinski** [comment]
Code seems to be correct but it depends on the context of it's invocation, so reproduction is necessary here to tell more. You may probably find an error when making reproduction. However, if there is an error in Astronomy then I will fix it as soon as possible.

**Comment by jagi** [comment]
I'm closing it for now, and waiting for the reproduction. Then I will reopen it.

**Comment by ffxsam** [comment]
@jagi Here you go: https://github.com/ffxsam/astro-v2-nested

Totally reproducible. In the console, you can see the updated dates on participants, but `c.save()` returns a 0.

Steps to reproduce: (in browser console):
1. `Accounts.createUser({email: 'test@test.net', password: 'test'})`
2. `c = new Models.Conversation()`
3. `c.save()`
4. Wait a couple minutes
5. `c.markAllAsRead(); c.save()`

The participant `lastViewed` field is not updated in the database, though you can see it was updated in the class.

**Comment by lukejagodzinski** [comment]
Hmmm I think that I might solve your problem with the last fix which is on GitHub in the `v2` branch. Please, try cloning Astronomy repository into your project's `packages` directory. I think it should work. Let me know.

**Comment by lukejagodzinski** [comment]
I've tested your code with that fix and it worked for me.

**Comment by ffxsam** [comment]
Awesome! I'll check this out in just a bit here, and let you know.

**Comment by ffxsam** [comment]
Works great!! 👍

**Comment by lukejagodzinski** [comment]
Ok great! I will publish a new version this week. So stay tuned. Closing this issue for now

**Comment by ffxsam** [comment]
Did this ever get published?

**Comment by lukejagodzinski** [comment]
Sorry, not yet. I had some work to do, and haven't time to publish it. But I will certainly publish it in the following week.

**Comment by ffxsam** [comment]
No prob at all! I'll keep an eye out on Atmosphere for it. Thanks! 👍
