### ISSUE TITLE
[v2] Class Inheritance Limitation

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#388]
Consider the Following:

Animal, Cat and Dog are all Astro classes. Cat and Dog inherit from the Animal class. We have 2 animals, 2 cats and 1 dog. If the server publishes `Animal.find({}, {children: true})` the client side is able to receive the 2 cats and 1 dog accessible through Cat and Dog Astro classes, however the 2 animals are never published and/or are not accessible through the Animal Astro class.

I would expect this to work regardless of `children: true` or `children: false`. This seems like a bug, could be a feature if something like `abstract: true` is introduced in the Animal class.

Let me know your thoughts @jagi

**Comment by lukejagodzinski** [comment]
It actually works as you described. You probably have a bug in your code.

**Comment by talha-asad** [comment]
I forgot to use `{children: true}` on the client side, my bad. Perhaps this could be added to the documentation as a note.
