### ISSUE TITLE
Pub/Sub with Astronomy

### ISSUE THREAD

**Issue by PolGuixe** [jagi/meteor-astronomy#389]
I guess that Astronomy is agnostic of the Pub/Sub system i.e. if we create a doc in the client, and save it with doc.save(), then to access the saved data, we need to subscribe to a publication that permits access to the information we just saved. 

Is that correct?

**Comment by PolGuixe** [comment]
This happens specially with data injected by behaviours such as the timeStamp.

**Comment by PolGuixe** [comment]
@jagi how do you handle pub/sub with astronomy? Can you perform de publications using the Astro Class or you have to use the collection?

**Comment by lukejagodzinski** [comment]
@PolGuixe Astronomy does not change anything about publication. You can use either `Class.find()` and `Collection.find()`. Both return Mongo cursor. There is nothing special about the `timestamp` behavior that you should take into account when working with pub/sub. The only difference is the `softremove` behavior when you should use `Class.find()` to only publish non-softremoved documents.
