### ISSUE TITLE
Question: Possible to save a reference (or class type) in a model?

### ISSUE THREAD

**Issue by peXed** [jagi/meteor-astronomy#390]
Hello!

I'm trying to build a log behavior. The behavior should simply log which user changed (inserted, deleted, updated) a model with the behavior attached to it.

Here is my model for the tracked actions (the log).

``` js
TrackedActionClass = Astro.Class.create({
  name: 'TrackedAction',
  collection: Collections.TrackedActions,
  secured: false,
  fields: {
    type: {
      type: String
    },
    changes: {
      type: Object,
      optional: true
    },
    date: {
      type: Date
    },
    docID: {
      type: Mongo.ObjectID
    },
    userID: {
      type: Mongo.ObjectID
    },
    originClass: {
      type: Object
    },
    userName: {
      type: String
    }
  },
  behaviors: ['ownedCollection']
});
```

It is working like a charm, but I also want to save a reference to the class to retrieve the changed document later on (because I will use the behavior on many different models).

Is there any good and easy solution for this?

**Comment by lukejagodzinski** [comment]
I'm not sure that you mean by "reference to the class" but I guess that you want to get the class/constructor of a document instance and store it somehow in a database. If it's what you want to do, then I have a solution for that. You can get the class name and store it as a string, and later you can just get a class/constructor using this class name.

``` js
var trackedAction = new TrackedActionClass();
var className = trackedAction.constructor.getName();
```

And later the way of getting class/constructor using class name

``` js
import { Class } from 'meteor/jagi:astronomy';
var AstroClass = Class.get(className);
var doc = new AstroClass();
```

Is this what you want to do?

**Comment by peXed** [comment]
That was exactly what I wanted to do. Thank you very much.
