### ISSUE TITLE
defaulting _isNew to false if passed in object already has _id

### ISSUE THREAD

**Issue by marbemac** [jagi/meteor-astronomy#391]
Have been coming across this in our work. If the model passed into the astro class constructer already has an _id property set, would it make sense to default _isNew to false?

```
// model is a plain object representing the existing environment
const env = new Environment(model);

// avoids having/needing to know to do this:
env._isNew = false;
```

**Comment by lukejagodzinski** [comment]
No, it can set the `_isNew` property to false because you may want to insert a new document with a given ID and Astronomy uses the `_isNew` property to decide if it should insert or update a document.

**Comment by talha-asad** [comment]
I would advice for it to be the opposite of how it is right now. If the constructor is passed with an _id it should assume it as an edit and if the user wanted to create a new document, he should explicitly set _isNew to true.

Edits are much more frequent than people trying to insert new document with manual _ids.

**Comment by lukejagodzinski** [comment]
I don't agree that edits are more often, it depends on the use case. However, I can change it right now even if I want to. It would be compatibility breaking change. And to be honest I don't see it right now as a bad design.

**Comment by talha-asad** [comment]
It's not bad design, it just that it's very uncommon/unheard of people using their own _id in mongoDB in general.

**Comment by lukejagodzinski** [comment]
We are using it a lot in our applications :) and it's not my idea to do so. I don't know if it's something correct to do in MongoDB but I don't think it should cause any problems. Anyway, setting the `_isNew` flag is quite trivial things so as I said I'm not gonna change it now because it would be compatibility breaking change.

**Comment by marbemac** [comment]
Understood - it's not worth the breaking change I guess. In one of the situations, you will have to set _isNew (either to true or false), so I guess it's a choice about which is more common:
1. Using a pre-existing (fetched from the DB, whatever), plain object, and using that object to create an astronomy object (passing it into the constructor).
2. Creating a new plain object outside of astronomy, and assigning an _id outside of astronomy, and then using that object to create a new astronomy object.

I totally don't have the data to back this up, but I would imagine case #1 is more common.

Anyways, we can set _isNew to false - just figured I'd open a quick discussion.

**Comment by marbemac** [comment]
Whoops, this is basically what @talha-asad said - I didn't see his comment above.
