### ISSUE TITLE
How to get back Mongo error code from Astronomy?

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#392]
I am using v1.2.10. I want to get back any error code that is theown by Mongo when a write operation is made. Can this be done in Astronomy?

As a comparison. below is an example of how this would be done if inserting directly to Mongo:

```
var results = MyColl.insert(doc);
if (results.hasWriteError()) {
    if (results.writeError.code == 11000 /* dup key */) {
        ...
    }
}
```

**Comment by lukejagodzinski** [comment]
When you're invoking some code on the server dealing with MongoDB, then any error will be thrown. If you use Meteor methods then you can handle it in the callback function.

``` js
// server
Meteor.methods({
  doSomething() {
    var post = new Post();
    post.save();
  }
});
```

``` js
// client
Meteor.call('doSomething', function(err) {
  err.error;
  // Do something with an error
});
```

**Comment by joetidee** [comment]
Just a quick check on my server syntax/logic.... is it necessary to have a function like this to return the error?

```
// server
Meteor.methods({
  doSomething() {
    var post = new Post();
    post.save(function (err, res) {
                if (err) {
                    return err;
                }
            });
  }
});
```

**Comment by lukejagodzinski** [comment]
You don't have to provide callback function in such situation. If you don't provide callback, then it will throw error and it will be sent back to the client. Callback functions are only for asynchronous calls on the client. On the server you can always call it synchronously.
