### ISSUE TITLE
Question: Can you call the validate() syncronously?

### ISSUE THREAD

**Issue by mbabauer** [jagi/meteor-astronomy#393]
I am trying to use the `validate()` on my object from a React Bootstrap `FormControl`'s `validationState`.  I need to be able to return a String of either "success" of "error".  Is there a way to call the validation such that it doesn't require a callback so that I can test it synchronously?  Or, maybe there is a better pattern for this?

**Comment by lukejagodzinski** [comment]
The `validate` method will throw `ValidationError` if there is no callback function. However, it will only work for client validation. If you want to get error from the server, then there is no other way than calling it asynchronously with the callback function.

**Comment by mbabauer** [comment]
Thanks!  That was the trick!
