### ISSUE TITLE
optional: true with Validators

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#396]
Currently, if I have optional and validators both fields set, it ignores the optional setting and tries to validate the given field. Can we have a setting where optional is given a higher priority during validation, i.e. not validate the field if it is null?

Also, I think optional is not honored properly in the nested classes. If the main field is optional, but a nested field is not, it still gives errors during validation.

**Comment by jagi** [comment]
From what I remember I've implemented it in the way where optional works
only with `undefined` values. But I have to check it out.

**Comment by lukejagodzinski** [comment]
From what I remember I've implemented it in the way where optional works
only with `undefined` values. But I have to check it out.

**Comment by lukejagodzinski** [comment]
I've checked it and it works properly for both `null` and `undefined` values. So, the problem may be on your side. Show your code.
