### ISSUE TITLE
v2: Values lost when doing: findOne() => set() => save()

### ISSUE THREAD

**Issue by ayalpani** [jagi/meteor-astronomy#397]
Hi Łukasz,

I started to migrate to v2 today. Here is something that seems to work different or is broken?

I use `findOne` to query an item from my items collection, with a restricted list of fields like so:

```
const itemToRestore = AstroItem.findOne(item._id, { fields: { _id: 1,  done: 1 } })
```

Then, I `set` a single field and `save`:

```
itemToRestore.set('foo', 'bar')
itemToRestore.save()
```

All the other fields on the document that weren't listed in the field selector for `findOne` are now reset to the default values I specified in the `Class.create` definition.

Why is it so? I would have expected only the "foo" field to have changed, nothing more
Thanks

**Comment by lukejagodzinski** [comment]
It's not so easy as it seems to be. When you limit a list of fields in a query then it will be undefined and Astronomy will try to use default values. In v2.1 on which I'm currently working there is a way of not filling these fields with defaults.

``` js
AstroItem.findOne(selector, {
  fields: { _id: 1, done: 1 },
  defaults: false
});
```

And it could work the way you want. If you want to try it out, you can clone the newest version from GitHub to your `packages` project's directory.

**Comment by ayalpani** [comment]
Dear Łukasz, thanks! I will wait until 2.1 is released. For now, I'll just not restrict by fields selector.

**Comment by ayalpani** [comment]
Or, wait: did you mean v2.0.1 or v2.1?

**Comment by lukejagodzinski** [comment]
I mean 2.1.0 which will be release soon.
