### ISSUE TITLE
Date Does not Save

### ISSUE THREAD

**Issue by tylershuster** [jagi/meteor-astronomy#398]
I have a document with field of type `Date`. When I try to save a Date object to it, it throws a validation error. If I change the field type to `Object` it stores a blank Object, and not a Date. I can provide more samples if you'd like but it's a pretty standard arrangement. I'm running 2.0.1 and even used the latest code from this repo in my packages folder.

**Comment by lukejagodzinski** [comment]
It's rather not possible that it does not work because I'm using date types on daily basis. Show your code.

**Comment by tylershuster** [comment]
A more simple use case fixes it. The case where it's not working I've circumvented by removing the document and re-saving. I don't think it's a significant issue.
