### ISSUE TITLE
TypeError when reusing same Class

### ISSUE THREAD

**Issue by frco9** [jagi/meteor-astronomy#399]
Hello, 

I get a `TypeError: ["Foo" class]["fields" property]["offers" field] Type does not exist` if I define a `offers` attribute with type `Offer` and that inside the `Offer` class I have an attribute which type is `Foo`.

To be more explicit, I've reproduced my issue here : 
https://github.com/frco9/astroBug

I think there's some kind of circular dependency causing it.

Thanks !

**Comment by lukejagodzinski** [comment]
Yes it's the problem with circular dependencies. However it's quite strange structure you've designed. I know that it's only a reproduction but by using such schemas you would have never ending nesting. Foo has Offer and Offer has Foo. You probably have to redesign your schemas.

**Comment by frco9** [comment]
Well the idea was to get some kind of Has-many Belongs-To relation. 
In the `Foo` class I would have had a `offer_ids` array, and a `offers` attribute that would have resolved offers using `offer_ids` in order to get its "children". And I would have used the same idea in the `Offer` class to get its "parent".

Have you some ideas on a better way to achieve that ?

**Comment by lukejagodzinski** [comment]
You can't just use class type for such relation. If you want to store ids of the counter part in both classes you just have to store array of ids.

``` js
const Foo = Class.create({
  fields: {
    barsIds: {
      type: [String]
    }
  }
});

const Bar = Class.create({
  fields: {
    foosIds: {
      type: [String]
    }
  }
});
```

That could be one of the solutions if I understood you correctly.

**Comment by frco9** [comment]
Hum, ok I think I'll use Class method, for now, to get its parent based on the `barId` saved. 
Thanks
