### ISSUE TITLE
Form data

### ISSUE THREAD

**Issue by VladShcherbin** [jagi/meteor-astronomy#4]
When working with forms, we definitely want to set the label, placeholder, the input type, if it is a textarea, number of rows, min and max, etc to use then in template helpers.

Now, we can't define this on scheme level. Besides, if we use validators, we also define some of this info there: maxLen, minLen for example. The type definition is duplicated in **fields** and **simpleValidators** (string for example).

We need to think about a good api for that functionality.

@jagi , any thoughts on how this can be implemented? Where do you suggest to do that?

**Comment by jagi** [comment]
Model, Validators and Forms are two different things. Right now there is no module for creating forms from model definition, however I have it in plans.

Duplication of type definition is required. Type definition in `fields` is for type casting. In fact you could avoid adding validator `isString` (or similar) at all.

If it goes about forms module it needs longer discussion. I've used forms libraries before and non of them was good enough to fit all my needs. I ended creating forms by hand. As many developers as many use cases and we should think about all of them. I will open discussion about forms when all major features will be ready.

**Comment by VladShcherbin** [comment]
@jagi sure, I also think this are two different things, though we have to think how to make things work in that direction. Hope, you can finish all major astronomy features so that we can discuss, how to make forms work.

I need isString, isNumber because I want the error if you input the word instead of number for example. So, I guess the duplication can not be avoided.
