### ISSUE TITLE
Cannot use Meteor.userId() as default value for field

### ISSUE THREAD

**Issue by matikucharski** [jagi/meteor-astronomy#40]
Hi.
First of all thank you very much for your excellent package.

I'm having an issue when trying to attach currently logged in userId as a default value for field in Astro.Class.

When I have 
```
Message = Astro.Class({
    name: 'Messages',
    collection: Messages,
    fields: {
        'senderId': { type: 'string', default: Meteor.userId() },
```

I got an error: `Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.`

But with `'senderId': { type: 'string', default: this.userId },` this keyword is AstroClass and its userId is null.

**Comment by jagi** [comment]
Hi,
A default value is static value, so you can not use a reactive variable here. Instead you should fill this field before saving document.

```js
var m = new Message();
m.set('senderId', Meteor.userId());
```

I will be creating behavior that does it automatically, however right now you have to do it manually.

Regards

**Comment by matikucharski** [comment]
Thanks for your reply! 
It is how I'm doing it right now:) It would be great to have this behavior made automatically.

**Comment by jagi** [comment]
No problem :). I will be updating readme with list of behaviors. I have long list of features to implement so it can take time :). Stay tuned.
