### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by satyavh** [jagi/meteor-astronomy#401]
```
Posts = new Mongo.Collection('posts')

Post = Astro.Class
  name: 'Post'
  collection: Posts
```

gives me this error

```
W20160526-14:34:44.791(2)? (STDERR) TypeError: Cannot call a class as a function
W20160526-14:34:44.792(2)? (STDERR)     at BabelRuntime.classCallCheck (packages/babel-runtime/babel-runtime.js:25:1)
W20160526-14:34:44.792(2)? (STDERR)     at Object.Class (packages/jagi:astronomy/lib/core/class.js:36:24)
```

**Comment by satyavh** [comment]
Perhaps because I'm using Coffeescript... but `Class` is kind of reserved in javascript

**Comment by lukejagodzinski** [comment]
`Class.create` instead `Astro.Class`

``` js
import { Class } from 'meteor/jagi:astronomy';
import { Mongo } from 'meteor/mongo';

const Posts = new Mongo.Collection('posts');

const Post = Class.create({
  name: 'Post',
  collection: Posts
});

export default Post;
```

**Comment by lukejagodzinski** [comment]
As I said `Class.create` instead `Class`. The `Class` keyword is not reserved, the `class` keyword is.

**Comment by satyavh** [comment]
I got this working as `Astro.Class.create` - works. However, I do notice that Astro class is not attached in this scenario:

```
post = new Post

post.set
   content: content

id = post.save()
post = Posts.findOne _id: id

console.log post
```

when I log this out (on server), it's not an Astro class attached, just the data. 
And as a result, the `afterFind` event is not being triggered.

Could this be caused by using `Astro.Class.create` ?

**Comment by satyavh** [comment]
Strangely, the `beforeSave` event does trigger

**Comment by satyavh** [comment]
Nevermind, I figured it out. 
Still need to get used to V2, I was on <v2 for a long time and the changes are very subtle!
