### ISSUE TITLE
Discussion on security

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#403]
I'm curious about something: if we properly publish limited content to a certain client, and don't secure any of the Astro classes, is there any harm in this?
1. Since Meteor 1.3 and using imports, things are no longer global, so people can't use the browser console to hack things.
2. Even if someone could access the Astronomy classes somehow, and none are secured, all they could do is ruin their own content (since I'm not publishing other people's stuff to them).

In what kinds of scenarios would it be problematic to set `secured: false` on all my Astronomy classes?

**Comment by lukejagodzinski** [comment]
In Astronomy 2.1 I will introduce compatibility breaking change that will secure all classes by default.
1. It's still possible to access Astronomy classes using `Astro.Class.get('className')` so you can perform some dangerous operations.
2. In theory yes, but if they know ID of some document that does not belongs to them they can modify such data. Moreover even changing their own data (they are subscribed to) may cause security issues. They can change ownership of some documents, they can change their own privileges etc. So, you should always think about security.

I will make Astronomy 2.1 more secure by default, but it still does not guarantee anything. With or without Astronomy you should always think about security.

**Comment by ffxsam** [comment]
Ahh right, since Astronomy is a Meteor package, its namespace is still global. I didn't think of that. Ok, all makes sense. Thanks for clarifying!
