### ISSUE TITLE
Regarding Documentation.

### ISSUE THREAD

**Issue by smooJitter** [jagi/meteor-astronomy#405]
Is it possible to provide examples of working with sub documents. The Astronomy Documentation does a good job highlighting features but I'd like to see examples of how apply the features. Specifically, 
1. What is the best way to  work with sub-documents i.e., adding, updating, and removing objects from array fields.
2. What's the recommended way of working with sub-document Classes that are not bound to a collection.  In other words, suppose I'd like to create a class (e.g., Profile) that I can reuse across several collections ( e.g., user, activity, item). 
3. What's ideal approach to working with resulting object instances. Again, consider a Class with no attached collection (e.g., Profile).  I would like set and manipulate the attributes of the Profile instance and then push the results to a nested field of another class.

**Comment by lukejagodzinski** [comment]
Here is an example app https://github.com/jagi/meteor-astronomy-examples/tree/v2

**Comment by smooJitter** [comment]
Thanks for everything!

**Comment by lukejagodzinski** [comment]
No problem :)
