### ISSUE TITLE
[timestamp] Bug: createdAt not set for collectionless models

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#406]
Minimal repro here: https://github.com/ffxsam/astro-v2-timestamp-bug

`createdAt` field in a new comment is left as null, whereas `updatedAt` is set to the current date (when saved in an entry). To reproduce:
1. `npm i && meteor && meteor shell`
2. `e = new Models.Entry({ name: 'Test Entry' })`
3. `e.save()`
4. `c = new Models.Comment({ content: 'Hello', author: 'Me' })`
5. `e.comments.push(c)`
6. `e.save()`

Actual output of `e`:

```
{ _id: 'GcYcGRcxTSYcwwMcD',
  name: 'Test Entry',
  comments:
   [ { createdAt: undefined,
       updatedAt: Tue May 31 2016 13:43:34 GMT-0700 (PDT),
       content: 'Hello',
       author: 'Me' } ] }
```

Collections are in `/imports/collections`.

**Comment by lukejagodzinski** [comment]
It's not a bug, it's how the timestamp behavior works. It's not intended to work with collectionless classes. If you want such behavior, you have to implement it by yourself. To understand why it's not working with collectionless classes you have to understand when creation date is set. It's set in the `beforeInsert` event which is only triggered on creation of a new `Models.Entry` instance. It's not triggered when you push nested instances of classes. It would be very hard to implement to cover all the use cases.

**Comment by ffxsam** [comment]
But `createdAt` is always undefined.. at no point during the steps above is it ever populated. Once I save the entry, though, `updatedAt` is populated with a date. Why can't `createdAt` be populated with a date as well?

**Comment by lukejagodzinski** [comment]
Because `beforeInsert` event was already triggered. In this situation it will be populated and only in this situation.

``` js
const e = new Models.Entry({ name: 'Test Entry' });
const c = new Models.Comment({ content: 'Hello', author: 'Me' });
e.comments.push(c);
e.save();
```
