### ISSUE TITLE
Handling relationship and error

### ISSUE THREAD

**Issue by jhuenges** [jagi/meteor-astronomy#408]
Lets assume I have these classes

``` js
export default Class.create({
  name: 'Person',
  collection: Persons,
  fields: {
    ...
    children: {
      type: [Child],
      optional: true
    },
    parents: {
     type: [String],
      optional: true,
      validators: [{
        type: 'every',
        param: [{
          type: 'regexp',
          param: /^[23456789ABCDEFGHJKLMNPQRSTWXYZabcdefghijkmnopqrstuvwxyz]{17}$/
        }]
      }]
  },
...
});
```

``` js
export default Class.create({
  name: 'Child',
  fields: {
    _id: {
      type: String,
      validators: [{
        type: 'regexp',
        param: /^[23456789ABCDEFGHJKLMNPQRSTWXYZabcdefghijkmnopqrstuvwxyz]{17}$/
      }]
    },
    type: {
      type: String,
      validators: [{
         type: 'choice',
         param: ["biological", "adopted", "noinformation"]
      }]
    },
    with: {
      type: String,
      validators: [{
        type: 'regexp',
        param: /^[23456789ABCDEFGHJKLMNPQRSTWXYZabcdefghijkmnopqrstuvwxyz]{17}$/
      }]
    }
  }
});
```

And now I want to save a Person as Child of two other Persons. 
1. Create Child and save it
2. Add Child to both Parents (Persons)

If something happens in the second step (the `parent1.save()` - call throws an error) I would have to revert the changes done to the child (i.e. its creation). So i would call `child.remove()`. But what if something happens here? How can I avoid this situation?
The problem gets even more complicated if the saving of `parent1` is successfull, but during `parent2.save()` an error occurs. Then I would have to revert not only the changes done to the `child` but also the changes on `parent1`

Does anyone have a solution for this type of problem?

**Comment by lukejagodzinski** [comment]
The thing you're talking about is not especially related with Astronomy but rather with MongoDB. The same situation could happen if there is some MongoError (like unique index error) on the second insert. Then you would have to revert also the first insert. There is lack of transactions in MongoDB. There are some ways of overcoming this but they are kinda ugly IMHO. I think I've read somewhere that there will be support for transactions in future MongoDB releases but I'm not 100% sure. Lack of transactions in MongoDB is why it's a very bad choice for banking applications. Maybe in some future release I will support transactions or create some "polyfill" for this using current solutions, but can'r promise anything at this stage.

**Comment by jhuenges** [comment]
Thank you :) So at the moment I either have to hope everything works or I have to write a lot of nested code...

**Comment by lukejagodzinski** [comment]
What do you mean by writing "a lot of nested code"? MongoDB has "transaction" like behavior on the document level. So it locks a document when you're changing it, so you can nested some data inside it. It's not perfect to have big documents that has a lot of nesting but it's just one way of solving this problem. And the second thing is just responding to the error in the callback function (so it's probably why you mentioned nesting) and removing documents if entire "transaction" didn't succeeded.

**Comment by jhuenges** [comment]
Yeah, I meant nested callback code. So if on save fails, I have to undo the changes etc.

**Comment by lukejagodzinski** [comment]
Yes for now I think it's the best solution. You should always put such code in a Meteor method.

**Comment by jhuenges** [comment]
Does is make sense to write a function for the rollback? Then it would be possible to re-run this function until the rollback was successfull

**Comment by lukejagodzinski** [comment]
You know, in most cases I don't care about that. It's very unlikely to happen. It's good to check validity of all documents that you're going to save before actually saving them. You can use `doc.validate()` to make sure that both documents being saved are valid and after that just perform save operation on both documents.

I don't want to implement any transactions feature for now in Astronomy as I will probably switch to GraphQL and things can look quite differently there. We will see what MDG team will figure out in Apollo.
