### ISSUE TITLE
Meteor.loginWithPassword fails when using "supportLegacyBrowsers" option

### ISSUE THREAD

**Issue by jbbr** [jagi/meteor-astronomy#41]
With the new "supportLegacyBrowsers" config (see #32) the "_values" object have been reintroduced. This causes some trouble with "Meteor.loginWithPassword".

It fails with "User has no password set" as it does not find a password in key "services" of user object - because its hidden inside the "_values" object

**Comment by jbbr** [comment]
I tried to find out some more about this issue and it seems as if there is no implicit getter anymore.

Example:

```js
var post = new Post({name: 'New Post'})

post.name
-> undefined

post._values.name
-> 'New Post'

post.name = 'Other Title'
post.name
-> 'Other Title'
```

**Comment by jagi** [comment]
I will check it out

**Comment by jagi** [comment]
Hmm it's strange because it works for me. Are you sure that you are doing everything correctly? Could you post an example code that does not work for you?

**Comment by jbbr** [comment]
Sorry for not trying that before: I've created a new, clean meteor project and everything works as expected. I'm still unsure why this doesn't work in my project as it looks for me as if I'm doing exactly the same there.

Anyway, Thanks for checking this out!
I'll close this issue for know - and debug my project.

**Comment by jagi** [comment]
Ok good to hear

**Comment by jbbr** [comment]
I was able to get it working in my project. The problem was caused by some kind of load order issue...

But the behavior was a bit strange: Setting "supportLegacyBrowsers" to false made a difference - so load order seemed correct. transformed objects had the "_values" property added etc.
Only the getters and setters where missing.

Moving the supportLegacyBrowsers settings into a deeper hierarchy or to a package helped.

Maybe this helps others which might experience the same problem. It's a bit strange that having the setting at the wrong place changes *some* things but not all or nothing. If you think thats a bug I can try to make a clean example reproducing this behavior.

**Comment by jagi** [comment]
Oh I see. The configuration should be called at the beginning, before all the other code starts running. You should put configuration in root or `lib` directory. Thanks to that you will make sure that it's called first. If you have some custom packages then they are loaded first so you should also add configuration in these packages.

But you are sure, I should mention it in the documentation.

**Comment by jbbr** [comment]
I was aware, that I'd have to put the configuration at the beginning. As I had all models in one folder (lib/models) I've placed configuration in lib/models/config/astroConfig.js.
Unfortunately it didn't work (The configuration made a difference - but getters/setters where still missing).
It was confusing for me as for my understanding deeper nested files are executed before less deep nested files.

But currently I'm unable to reproduce this easily as I restructured my code a lot.
I'm using es6 modules now with universe:modules package - load order is not an issue since :)

**Comment by jagi** [comment]
It's the other way. The deeper nested files are loaded after. From documentation:

1. HTML template files are always loaded before everything else
2. Files beginning with main. are loaded last
3. Files inside any lib/ directory are loaded next
4. Files with deeper paths are loaded next
5. Files are then loaded in alphabetical order of the entire path

So it's:

lib/models/*.js
lib/models/config/astroConfig.js

**Comment by jbbr** [comment]
Sorry but I'm confident that in this case astroConfig.js is loaded first.
lib directories are first loaded but inside lib directories usual load order happens (deep first)
I've even tried it by putting some console logs inside.

But sure this is not the right place to discuss this.

Nevertheless it might be a good idea to give some hint in the documentation where to put the config.

**Comment by jagi** [comment]
Ok I will make more tests regarding files load order. But in the fact files load order is pain in the ass :)
