### ISSUE TITLE
Latency Compensation

### ISSUE THREAD

**Issue by PolGuixe** [jagi/meteor-astronomy#410]
How does latency compensation works with Astronomy? 

When I do `doc.save()`. Is the `insert / update` method also executed in the client? So miniMongo gets updated.

If I want the miniMongo to be updated I normally have to define a method stub like in [here](https://github.com/mantrajs/mantra-sample-blog-app/blob/master/client/modules/core/configs/method_stubs/posts.js).

Also I am wondering if there is a way to test the latency effect like in [here](https://github.com/mantrajs/mantra-sample-blog-app/blob/master/server/methods/posts.js#L29).

**Comment by lukejagodzinski** [comment]
It works the same way as in MiniMongo, so it will perform simulation in the client first but also execute code in the server.

**Comment by PolGuixe** [comment]
@jagi, is there a way to add a certain delay in the server or a way to simulate the latency?

**Comment by lukejagodzinski** [comment]
You may try the same trick as in this test https://github.com/mantrajs/mantra-sample-blog-app/blob/master/server/methods/posts.js#L29 you've posted

**Comment by PolGuixe** [comment]
I don't have a method defined in server as I only perform the `doc.save()` in the client. Should I add the delay in a before save event?
But in that case, will the delay also happen in the client?

**Comment by lukejagodzinski** [comment]
If you add delay in the `beforeSave` event then it should work but you have to check it out. You can do something like:

``` js
beforeSave() {
  if (Meteor.isServer) {
    Meteor._sleepForMs(500);
  }
}
```

**Comment by tmpg** [comment]
I have a question about this also. I have a bunch of server methods, do I need to use a client method_stub as shown in:
[https://github.com/mantrajs/mantra-sample-blog-app/blob/master/client/modules/core/configs/method_stubs/posts.js](url)
To get latency compensation with Astronomy? 
What are best practices to achieve latency compensation? Are there examples?

**Comment by PolGuixe** [comment]
@tmpg yes, you have to define a method stub or a define the methods in `/both` or `/lib` folder

**Comment by tmpg** [comment]
If I define the methods in the /lib folder is there anything specific I need to do like add context (on client) or will it detect it?

@PolGuixe I appreciate the help, are there any examples of this?

**Comment by PolGuixe** [comment]
@tmpg your methods should be agnostic from the client context I would say. As if they where only in the server. If you really need to use the client context it should be passed as a variable. 

If your client methods is really different from your server method, then the best thing would be to define them separately.

(sorry I've written really quick from my phone, let me know if it's not clear)

**Comment by tmpg** [comment]
I think I understand. Let me just reiterate:

If I want latency compensation I must define the methods in /lib but to the client, it will seem as if it was only on the server.

Sounds correct?

**Comment by PolGuixe** [comment]
@tmpg I don't understand your approach 😅 . I'll put an example:

This method: 
```js
// in lib/methods/posts.js
  Meteor.methods({
    'posts.create'(_id, title, content) {
      check(_id, String);
      check(title, String);
      check(content, String);

      // Do some user authorization
      const createdAt = new Date();
      const post = {_id, title, content, createdAt};
      Posts.insert(post);
    }
  });
```
Will be executed in the server and in the client, i.e. it will work as an optimistic UI, as it will also be executed on the client.

In you separate them as in the case above:
```js
// in server/methods/posts.js
  Meteor.methods({
    'posts.create'(_id, title, content) {
      check(_id, String);
      check(title, String);
      check(content, String);

      // Demo the latency compensations (Delete this in production)
      Meteor._sleepForMs(500);

      // XXX: Do some user authorization
      const createdAt = new Date();
      const post = {_id, title, content, createdAt};
      Posts.insert(post);
    }
  });

// in client/.../methodstubs/posts.js
  Meteor.methods({
    'posts.create'(_id, title, content) {
      check(_id, String);
      check(title, String);
      check(content, String);

      const createdAt = new Date();
      const post = {
        _id, title, content, createdAt,
        saving: true
      };
      // Do other stuff in the client....

      Collections.Posts.insert(post);
    }
  });
```
You obtain the "same" result as if they are declared in `lib`. But these way give you the flexibility to have different methods in the client and in the server.

**Comment by tmpg** [comment]
@PolGuixe,
My primary question is will this work with astronomy. You did not use astronomy here. Here is an example method of mine:

```
import Post from '../../lib/posts';
import {Meteor} from 'meteor/meteor';
import {check} from 'meteor/check';

import AppConfig from '../../lib/configs/app';

export default function () {
  Meteor.methods({
    'posts.new'(_id) {
      if (!Roles.userIsInRole(Meteor.userId(), AppConfig.roles.contributorPlus)) {
        let message = "You are not authorised";
        throw new Meteor.Error("Not Permitted", message);
      }
      check(_id, String);

      let post = new Post();
      post.userSlug = Meteor.user().profile.userSlug;
      post._id = _id;
      post.save();
    },
  });

}
```

Which is found in the `/server` directory and in `/lib` I defined an astronomy class Post.

With this kind of setup, what will I have to do to allow for latency compensation?
Move the methods out of `/server` into` /lib` or define astronomy classes in `client/.../methodstub`?
Or something totally different?

Thanks.

**Comment by PolGuixe** [comment]
@tmpg you can just put this method in `/lib` or define the method stubs in `/client`, without declaring new astronomy classes. If you declared your classes in `/lib` they are already in client.

**Comment by tmpg** [comment]
@PolGuixe thank you very much for explaining.

**Comment by tmpg** [comment]
@PolGuixe,
I still declare my methods in `server/main.js`. Is this correct?

```
import publications from './publications';
import methods from '../lib/methods';
import router from './configs/router';

publications();
methods();
router();
```

**Comment by PolGuixe** [comment]
@tmpg yes. 

I do it this way. I split some methods between `/lib` and `/server` and I declare all of them in `/server`.

**Comment by tmpg** [comment]
@PolGuixe 

Why do you split them between `/lib` and `/server`? What are the disadvantages of keeping them all in `/lib`?

I assume it would be a security risk as it is seen by the client?

**Comment by PolGuixe** [comment]
More than disadvantages, are the advantages. A bit of optimisation and security. 

Separating them I can control what methods stubs are in the client, because I don’t what all the methods in the client. e.g. I have a method to generate dummy data for testing and I am not interested in having this method in the client. 

On Thu, 12 Jan 2017 at 14:51 tmpg

<
mailto:tmpg <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/PolGuixe

Why do you split them between

/lib

and

/server

? What are the disadvantages of keeping them all in

/lib

?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/jagi/meteor-astronomy/issues/410#issuecomment-272167704
, or
