### ISSUE TITLE
Question: Securing application using methods

### ISSUE THREAD

**Issue by PolGuixe** [jagi/meteor-astronomy#412]
I have few questions about securing applications using methods as it is described in the [documentation](http://jagi.github.io/meteor-astronomy/#secured-property). 
Somehow this means just performing the `doc.save()` in the server. Hence, I have the following questions: 
1. Will the simulation (latency compensation) happen in the client? 
2. Is it possible to send an `_id` generated in the client, and use it in the `doc.save()` in the server when the doc is inserted?

**Comment by lukejagodzinski** [comment]
1. Yes it will
2. Yes it's possible
