### ISSUE TITLE
[v2] Astronomy Document Reactivity (Client-Side)

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#414]
I followed a bit on one of your previous discussions, however I don't know how it stands as of today and there is no mention about this in the documentation either. What's the best way to go about client side reactivity for an Astro document object? Do we have to use ReactiveMap or something of that sort?

**Comment by lukejagodzinski** [comment]
If you want document level reactivity you can just store it in the `ReactiveVar` it's what is done in an example app and it works well. It's able to detect new elements in array so it's updates form accordingly.

**Comment by talha-asad** [comment]
Thanks!
