### ISSUE TITLE
[v2] {children: true} for updates doesn't work

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#416]
`{children: true}` works well for retrieval, but it doesn't work for updates, my guess is it probably doesn't work for deletes either. It works if you use native base meteor collection because it doesn't understand inheritance anyway.

**Comment by lukejagodzinski** [comment]
Oh yes it's definitely not working. I forgot to take that use case into account. I will prepare a fix.

**Comment by talha-asad** [comment]
Two more considerations:

`SomeAstroClass.find({}, {fields: {}, {children: true})` will this work?, since we aren't selecting the type field. I am going to test this out but my suggestion is this should automatically add the type field to the fields object.

`SomeAstroClass.find({})` should return all types by default and cast them to the base "SomeAstroClass", this isn't the case right now, which seems right because we have "children: true" instead maybe we need "cast: true", and "children: true" should be default?

Let me know your thoughts.

**Comment by jhuenges** [comment]
Nothing on the bug, but what does `{children: true}` do? I couldn't find it in the docs

**Comment by talha-asad** [comment]
@jhuenges It's an undocumented and unreleased feature at the moment, read up on #368

**Comment by lukejagodzinski** [comment]
I've fixed it and it will be published in 2.1

**Comment by talha-asad** [comment]
@jagi can you let me know your thoughts on the 2 other considerations I posted.

**Comment by lukejagodzinski** [comment]
Can you tell me exactly which one?

**Comment by talha-asad** [comment]
Two more considerations:

SomeAstroClass.find({}, {fields: {}, {children: true}) will this work?, since we aren't selecting the type field. I am going to test this out but my suggestion is this should automatically add the type field to the fields object.

SomeAstroClass.find({}) should return all types by default and cast them to the base "SomeAstroClass", this isn't the case right now, which seems right because we have "children: true" instead maybe we need "cast: true", and "children: true" should be default?

Let me know your thoughts.

**Comment by lukejagodzinski** [comment]
1. Oh yes good idea to add the type field automatically. I will add that feature.
2. I'm not quite sure about that one. I can agree that it might return all children automatically, so default would be `children: true`. However, I would still cast all children to their appropriate classes. I don't want to cast it to parent class.

**Comment by laurentpayot** [comment]
+1 for `children: true` by default, and another +1 to keep children their appropriate classes intead of their parent class.

**Comment by talha-asad** [comment]
The problem I face is that if you need count of all inherited objects you have to fetch and count on individual Astro Classes, which can get tedious, Maybe if a workaround for this is added.

**Comment by lukejagodzinski** [comment]
``` js
Animal = Class.create({ /* ... */ });
Dog = Animal.inherit({ /* ... */ });
Cat = Animal.inherit({ /* ... */ });
Animal.find().count(); // Count all
Dog.find().count(); // Count only dogs
Cat.find().count(); // Count only cats
```

and of course the `children` flag will be set to `true` by default

**Comment by talha-asad** [comment]
If that works, we are all set. I think the decision to make `children` flag true by default is a good one. Should I submit another issue to keep track on these changes or should we just do it here?

**Comment by lukejagodzinski** [comment]
The only one thing to implement is default value of the `children` option. Everything else is already on the `v2` branch. So I don't think that there is a need for creating another thread for that.

**Comment by talha-asad** [comment]
Awesome ;)

**Comment by talha-asad** [comment]
@jagi can you please get this on v2 branch so i can clone it for local usage

**Comment by lukejagodzinski** [comment]
@talha-asad it is on the `v2` branch

**Comment by talha-asad** [comment]
I meant the other part of having it default to `children: true`. I am using the latest clone and it doesn't have it.

**Comment by lukejagodzinski** [comment]
Oh maybe I forgot to push it

**Comment by lukejagodzinski** [comment]
Ok pushed
