### ISSUE TITLE
If validation not working in v1.2.10

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#417]
I have this validator in my model:

```
question_type: [
    Validators.if({
                condition: function(fieldValue, fieldName) {
                    var val = parseFloat(fieldValue[0].id);
                    if(val > 1) {
                        return true;
                    }
                    else{
                        console.log("Here");
                        return false;
                    }
                },
                true: Validators.and([
                    Validators.required(),
                    Validators.array(),
                    Validators.minLength(1)
                ])
            })
]
```

The console log is printing out "Here", so I know that `false` is being returned from the condition. However, the overall document is being validated as `true`. Why is this?

**Comment by peterchoo** [comment]
You are returning false from your condition function.  This is telling the Validator to run the `false` validators, which you have not specified.

In pseudo code, you have `If the float representation of the id of the first element of the array is greater than one, validate the field value is there, it's an array and it has at least 1 element`.

You need to provide some `false` validators.

**Comment by joetidee** [comment]
If I wanted to in-validate the question_type if the condition returns false, how would I do this?

**Comment by lukejagodzinski** [comment]
You have to create reproduction repository.

**Comment by joetidee** [comment]
ok, solved it just but putting false: `Validators.equal('somerandomtext')` under the true block.
