### ISSUE TITLE
Cannot set object to null in v1

### ISSUE THREAD

**Issue by peterchoo** [jagi/meteor-astronomy#418]
In my model, I have a nested object, which is optional.  This nested object can be added or removed from the model at any time.  I have tried to do `model.set('obj', null)` - but this gives no change in the object before or after saving.

I've made a demo repo here: https://github.com/peterchoo/astronomy-v1-set-object-null

Is there a way of removing a nested object?  Thanks!

**Comment by lukejagodzinski** [comment]
Bug fixed in 1.2.11, however I would strongly recommend switching to version 2.0

**Comment by peterchoo** [comment]
Thank you, I'll upgrade to 1.2.11 now.  We are intending to upgrade to 2.0 ASAP, we just have some blocks right now, it will be upgraded within a few weeks.

**Comment by lukejagodzinski** [comment]
Ok good
