### ISSUE TITLE
Generate _id locally

### ISSUE THREAD

**Issue by Mokto** [jagi/meteor-astronomy#419]
Hi,

Thank you for your package. I just switched with SimpleSchema and it feels nice ;)

Is _id only generated when saving a data on the server ?
In SimpleSchema we could do things like :

`const id = Users.insert({...});`

the _id was generated locally (it feels like it is the good way of doing this). Now I have to wait for a callback...

Thanks !

**Comment by lukejagodzinski** [comment]
Hi, Astronomy returns ID:

``` js
var user = new User();
var id = user.save();
```

However, as I remember there is a bug that it does not return ID on the server and that bug was already fixed in 2.1 which wasn't published yet. But you can clone `v2` branch to your local packages directory.

**Comment by Mokto** [comment]
Thanks !!

Great job again.
