### ISSUE TITLE
Nested field with Astro.Class value type

### ISSUE THREAD

**Issue by AbdelBa** [jagi/meteor-astronomy#42]
I tried to do that

```js
Address = Astro.Class({
  name: 'Address',
  collection: Addresses,
  fields: {
    // ...
  }
});

Person = Astro.Class({
  name: 'Person',
  collection: Persons,
  fields: {
    // ...
    address: new Address() // here
  }
});
```
But it doesn't work, how do I achieve this ?

**Comment by jagi** [comment]
If you want to store a plain object in the address field you should use the `object` type instead.

```js
Person = Astro.Class({
  name: 'Person',
  collection: Persons,
  fields: {
    address: 'object'
  }
});
```

and now you can store simple objects:

```js
var p = new Person();
p.set('address', {
  city: 'San Francisco',
  state: 'CA'
});
```

However if you want to store other astronomy object (maybe store it's not the correct word in this context) you should use relations package https://atmospherejs.com/jagi/astronomy-relations https://github.com/jagi/meteor-astronomy/wiki/Relations

It's in early stage. However you can store single values right now. It just stores references to objects saved in another collection. Everything depends on the case you have (how big `Address` class is etc.).

**Comment by dcworldwide** [comment]
I have the same issue. In SimpleSchema we are able to define sub-documents using a SimpleSchema. The advantage of this approach, as opposed to your suggestion, is that it is typed - allowing us to apply validation to sub-document structures. 

I also really don't like the set(string) syntax. It is verbose and may not work well with IDE refactor tooling.

**Comment by jagi** [comment]
You can still apply validation and types to subdocuments. Take a look at this documentation https://github.com/jagi/meteor-astronomy#nested-fields. However I see that in deed, in some situation it would be nice to have possibility to include schema in the schema that would be saved in the same collection. I will add this feature after implementing indexes.

**Comment by dcworldwide** [comment]
Sounds great.

Thanks for the code sample.

**Comment by jagi** [comment]
I'm thinking about that and I don't know what approach I should choose. You told that in SimpleSchema you can defined field type to be an another schema. In Astronomy you can do as follows:

```js
User = Astro.class({
  name: 'User',
  collection: Users,
  fields: {
    'firstName': {
      type: 'string',
      validators: Validators.string()
    },
    'lastName': {
      type: 'string',
      validators: Validators.string()
    },
    'address': {
      type: 'object',
      validators: Validators.string()
    },
    'address.city': {
      type: 'string',
      validators: Validators.string()
    },
    'address.state': {
      type: 'string',
      validators: Validators.string()
    },
  }
});

var user = new User();
user.address = {
  city: 'San Francisco',
  state: 'CA'
};

if (user.validate()) {
  user.save();
}
```

You can still have nested object and nested validation. Maybe separating Address object would be better approach but it creates some difficulties which I can manage. It could look like follows:

```js
Address = Astro.class({
  name: 'Address',
  fields: {
    'city': {
      type: 'String',
      validators: Validators.string()
    },
    'state': {
      type: 'String',
      validators: Validators.string()
    }
  }
});

User = Astro.class({
  name: 'User',
  collection: Users,
  fields: {
    'firstName': {
      type: 'String',
      validators: Validators.string()
    },
    'lastName': {
      type: 'String',
      validators: Validators.string()
    },
    'address': {
      type: 'Address'
    }
  }
});

var user = new User();
user.address = new Address({
  city: 'San Francisco',
  state: 'CA'
});

if (user.validate()) {
  user.save();
}
```

Notice that in this example I've made all the types uppercase like the type constructor. Maybe it was bad idea to make it lowercase in the first place.

Other difficulties are:
- Every Astro class/model/schema has the `_id` field which should be present here. I should probably only add the `_id` field to classes that are related with some collection.
- I would have to transform nested fields to objects of given class when fetching from the collection. It causes problem with transforming nested fields. I would be able to transform only first level fields (like the address field in the example). If I would like to transform nested fields to some class's instance I would have to rewrite a lot of code.

What do you think about it?

**Comment by dcworldwide** [comment]
Nice stuff @jagi 

*Structure & Id FIelds*
'''
Every Astro class/model/schema has the _id field which should be present here. I should probably only add the _id field to classes that are related with some collection.
'''

What if we seperate the schema concept from the class concept. A class could then map to a collection and be composed of 1.* schemas? This would allow us to re-use schema's across classes. Some example use case would be auditing fields (createdBy etc) and voting fields (upVotes, upVoteUsers etc). 

With this case, a class would expect an _id field to always exist, but a schema wouldn't. 

*Field Class Transformation*

'''I would have to transform nested fields to objects of given class when fetching from the collection. It causes problem with transforming nested fields. I would be able to transform only first level fields (like the address field in the example). If I would like to transform nested fields to some class's instance I would have to rewrite a lot of code.'''

Perhaps the suggestion above would help resolve this problem?

**Validator Chaining & Schema Tree**

The suggested change would also make it easier to define a complex tree of schemas, that in turn would make complex validation function chaining easy. I.e. calling user.validate() would first call user.address.validate() which may call user.address.postcode.validate()

Just a few thoughts :)

**Comment by dcworldwide** [comment]
Also, i'm wondering if we should avoid using strings as types and instead force users to use constants.

```
Address = Astro.class({
  name: 'Address',
  fields: {
    'city': {
      type: Astro.String,
      validators: Validators.string()
    },
    'state': {
      type: Astro.String,
      validators: Validators.string()
    }
  }
});
```

Benefits:

- IDE Autocomplete makes it easy for DEVs to understand available types
- If the constant values are ints and not strings, memory footprint reduced.
- Potential IDE refactoring benefits

**Comment by jagi** [comment]
About your second post. I have to use string format for types, but thanks for suggestion. From the beginning I wanted to use string and there is a reason for doing so. I future versions of Astronomy, (probably in 2.0) the basic class will be pre built without runtime interpretation of the schema. I was playing with it already https://github.com/jagi/meteor-astronomy/tree/build/lib/build and postponed it for future version because it's a huge feature. It requires the types to be strings, in fact it requires from all the schema values to me JSON-able (plain types: string, number, boolean, object). After building, it will produce one file with the `BaseClass` class. You will be able to add validators, methods etc to it. The "first run" will be much faster. But that's in the future.

If it goes about nested schemas. I'm not going to call it schema. I will use schema/class/model names interchangeably. I don't want to introduce new term because users will be confused. I want to make it simple. It's just a class instance that holds another class instance. Because it's possible in MongoDB, however it's not possible in relational databases. In the future I want Astronomy to work with many databases, so when implementing any feature I always think about the future development.

I already have implemented mechanism for nested schemas and it works quite well. Now I have to take care of validation. You are right that in many cases, nested schemas will make validation tree easier to define. Maybe it's not the very often use case. I think that most developers take out nested schemas and put into separate collection.

And going back to your idea about making Classes to be composed of many Schemas and implementing in that way createdAt fields etc. You probably read about [behaviors](https://github.com/jagi/meteor-astronomy/wiki/Behaviors). You idea is similar to what behaviors do but in a little bit different way. In fact, your idea make me think if I could implement it more like nested schemas. I will rethink it :).

**Comment by dcworldwide** [comment]
Hi @jagi 

```
If it goes about nested schemas. I'm not going to call it schema. I will use schema/class/model names interchangeably. I don't want to introduce new term because users will be confused. I want to make it simple. It's just a class instance that holds another class instance. Because it's possible in MongoDB, however it's not possible in relational databases. In the future I want Astronomy to work with many databases, so when implementing any feature I always think about the future development.
```


```
I already have implemented mechanism for nested schemas and it works quite well. Now I have to take care of validation. You are right that in many cases, nested schemas will make validation tree easier to define. Maybe it's not the very often use case. I think that most developers take out nested schemas and put into separate collection.
```
I think tree data structures would be a fairly common thing in collections. I apply a behaviour like patterns to my collections (i.e auditing, location (gps, address)) and typically have collections that are 3 levels deep, sometimes more. 

```
And going back to your idea about making Classes to be composed of many Schemas and implementing in that way createdAt fields etc. You probably read about behaviors. You idea is similar to what behaviors do but in a little bit different way. In fact, your idea make me think if I could implement it more like nested schemas. I will rethink it :).
```
Yep, I have. Behaviours really simplify my codebase, they have been invaluable as complexity has grown. If Astro behaviours own their own schema and can inject it to inject it to an arbitrary collection then i think Behaviours become much more elegant in design.

cheers

**Comment by jagi** [comment]
3 levels deep? Could you post here some example class that you are using with 3 levels deep?

I will be working on improvements and sharing my thoughts.

**Comment by dcworldwide** [comment]
Sure, sounds good.

Some examples of how i've been composing SimpleSchema's for my collections.

- POI schema
 - Location schema
  - Address schema
  - GPS Coordinate schema
 - Auditing Schema (createdBy, createdAt, updatedBy, updatedAt)

**Comment by jagi** [comment]
For now I'm closing this issue because the feature has been implemented and will appear in the next Astronomy release.
