### ISSUE TITLE
Strange situation with "this" context on the client

### ISSUE THREAD

**Issue by Tbutnyakov** [jagi/meteor-astronomy#420]
Hey, Jagi!

I found a very strange behaviour of the Astronomy class on the client. 

I have "User" class, and it have method "getAvatar". 
i have "Post" class,and it have relaion with user called "author". 
So, on the client,  in template helpers i call: 

`avatar:function(){
           return this.author().getAvatar();
}` 

In chrome everything works fine, but in yandex browser (sometimes), or IE (always) i took:

> cannot read property getAvatar of undefined 

In console:
in Chrome i have author object in '_references' of 'this' context, 
in Yandex i have author object, but its fields is undefined (but sometimes it have, and all work fine!). 

Can you explain me what im doing wrong?:)
Or...it s not my fault?

P.S. Thank you for a realy good package!

**Comment by lukejagodzinski** [comment]
If it works in Chrome and not in Yandex then it means that it's a problem with Yandex browser. I haven't been testing it in that browser. There is probably lack of some feature in JS but I can't tell what as I'm not supporting this browser.

**Comment by Tbutnyakov** [comment]
Hello! I tried to check out a few more times , got the details.
When I load the page in chrome for the first time , I get the same problem as in Yandex . In any browser . I tried and Vivaldi . Same. Now it seems to me that the problem is not in the browser . I use the first version of Astronomy

**Comment by lukejagodzinski** [comment]
Are you sure that `this.author()` is a function and it returns object? Have you published authors?

**Comment by Tbutnyakov** [comment]
Yes, it is declared in relations block of Post class like in example of documentation
http://jagi.github.io/meteor-astronomy/v1#relations 

relations:{
        author: {
            type: 'one',
            class: 'User',
            local: 'userId',
            foreign: '_id'
        }
    }

For now i still not delete autopublish package.  Cause it still under dev. 
So, this is a not a reason, i suppose. 
The interesting thing of this problem - all will work fine if i will load page in a second time.

**Comment by lukejagodzinski** [comment]
So the problem is probably publication. Remove the `autopublish` package and create publication that returns all necessary data.

**Comment by Tbutnyakov** [comment]
Ohh...ok:) 
Very strange. 
I think, i need migrate to Astronomy 2.  Jagi, are you planing to create a relation-package for Astronomy 2, or i can create relations-logic for my own?:)

Thank you so much!

**Comment by lukejagodzinski** [comment]
It's better to create relations logic by yourself. I had the `relations` package for v2 in plans but I don't know how it will go as things change very fast in JS world and with GraphQL things will change too. So probably there gonna be some changes in the future in how Astronomy works. We will see, time will show.

**Comment by Tbutnyakov** [comment]
Ok. 
Thank you and good luck!)
