### ISSUE TITLE
Parent.update doesn't update children when typeField is in use

### ISSUE THREAD

**Issue by mikecentiq** [jagi/meteor-astronomy#424]
There is an issue when calling "update" on parent classes, when a child class was used to create a document and typeField is in use:

``` js
rawCollection = new Mongo.Collection('whatever');

Parent = Astro.Class.create({
  name: 'Parent',
  typeField: '_type',
  collection: rawCollection,
  fields: {...},
});

Child = Parent.inherit({
  name: 'Child',
  fields: {...},
});

Parent.update({ ... }, { $set: {...} }, { multi: true });
```

When performing that update, `_type: 'Parent'` is added to the search parameters, which means anything with a `_type` of "Child" is excluded.

I think that when `Parent.inherit` is called, it should track children (recursively) such that when it comes time to call `Parent.update` it can still add `_type` to the selector, but instead of saying: `_type: 'Parent'` it could say: `_type: { $in: ['Parent', 'Child'] }`

P.S I am working from the current latest commit on the master branch.
P.P.S This code worked in Astronomy v1, so it was caused by a change from v1 to v2.

**Comment by lukejagodzinski** [comment]
Oh right my bad. I forgot to include all child classes. I will fix it.

**Comment by lukejagodzinski** [comment]
I forgot to push default `children: true`. It should work now.
