### ISSUE TITLE
[v2] Not permitted

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#426]
Provided that my Class is not secured and i have implemented logic for checking in events like `beforeRemove`, i can't remove dependant documents in other collections because i am not using an ID selector and the remove was triggered from client. Why does this limitation exist?

Shouldn't be the programmer be responsible for security?

**Comment by lukejagodzinski** [comment]
It's how it works in Meteor and I've just duplicated this behavior. They probably had good reason to do so. I've tried to think of the situation when it can be not save to allow deletions with non id selectors and I don't think it's so big deal. However, they decided to do this and I don't want to mess with this philosophy to not introduce any confusion for developers.

**Comment by aaroniscode** [comment]
I've got a similar issue, I think.

My Class "Watchlist" is secured and I've removed the meteor package insecure.

I'm using Meteors ValidatedMethod to create a method to remove an item. The code in my Meteor Method is:

```
if (! this.userId) {
  throw new Meteor.Error('watchlists.remove.notLoggedIn');
}

const result = Watchlist.remove({
  _id: watchlistId,
  userId: this.userId,
});

if (! result) {
  throw new Meteor.Error('watchlists.remove.notFound');
}

return result;
```

I'm not using just the ID because I'm confirming the user owns the Watchlist he/she is trying to remove

I'd like to simulate the result on the client, but I'm getting a Not Permitted error. Am I doing it wrong?

**Comment by talha-asad** [comment]
Consider the following:
A user owns a campaign and each campaign has a lot of line items and the user triggers a remove for the campaign from the client side. We can't remove all the line items using the campaign id selector. I think this is a reasonable use case.

@gitamiller case also seems reasonable.

My suggestion would be to not limit, in this way as long as the class is not secured, because then it should be as it is designed "programmer responsible for security". No point in not permitting certain selectors.

**Comment by lukejagodzinski** [comment]
I'm not going to change it. It's how it's implemented in Meteor so I will stick to it, to make it concise. So far users are creating big applications using Meteor and that wasn't a big deal. I know it may be a constraint but it's not a problem without a workaround. If MDG will change it in the future I will change it too.

**Comment by lukejagodzinski** [comment]
I would be glad if you could look for some MDG response to this problem. Why they implemented it that way.

**Comment by lukejagodzinski** [comment]
I'm working on one bug in Astronomy and I've noticed that in some cases it's possible in Meteor to remove or update documents by ID. The requirement is calling `doc.remove()` from within a meteor method call. There is a check in Meteor if we're already in simulation. If so, then we don't check id restrictions. I will update my code to reflect that after I'm done solving the current one problem.

**Comment by aaroniscode** [comment]
Great!  That addresses exactly my issue. I'll be able to remove in simulation without the "id" restriction. Looking forward to the fix.

Thanks for reopening.

**Comment by lukejagodzinski** [comment]
Ok I've fixed it. If you want to use it right away you can clone current version from GitHub. Otherwise it will be available with the next bug fix version. I only have to fix one more bug and I will be releasing. Closing for now.
