### ISSUE TITLE
Union type

### ISSUE THREAD

**Issue by peterchoo** [jagi/meteor-astronomy#427]
Hi @jagi,

In updating from v1 to v2, I have found that I now have to specify a type for a field, where as before I did not.

I have a schema for a constraint, which in v1 looks like this:

``` javasript
Stanza = Astro.Class({
  name: 'Stanza',
  fields: {
    field: 'string',
    operator: 'string',
    value: {
      // type is NOT defined to allow string or number types
      optional: true,
    },
    column: {
      type: 'string',
      optional: true,
    },
  },
});
```

As the comment suggests, type can be either a String or a Number, however in v2 I have converted the class to this:

``` javascript
Stanza = Astro.Class.create({
  name: 'Stanza',
  fields: {
    field: {type: String},
    operator: {type: String},
    value: {
      // type is NOT defined to allow string or number types
      optional: true,
    },
    column: {
      type: {type: String},
      optional: true,
    },
  },
});
```

It is now giving me the following error:

`TypeError: ["Stanza" class]["fields" property]["value" field] Type does not exist`

Is it possible to have a field with multiple types?

If not, I can work around it by having two optional fields and some logic to use `stringValue` or `numberValue`.

**Comment by lukejagodzinski** [comment]
Right now it's not possible to provide two or more types for a field. You may try using `Object` type which should store numbers as the `Number` instance and strings as the `String` instance. I haven't tested it but in theory it should work. In Astronomy 2.2 I will try to introduce type similar to [GraphQL union](http://graphql.org/docs/api-reference-type-system/#graphqluniontype), where you can create the Union type which can take 1+ types

**Comment by peterchoo** [comment]
Thank you for the suggestion, but unfortunately it does not:

``` javascript
import { Meteor } from 'meteor/meteor';
import { Class } from 'meteor/jagi:astronomy';

const Model = Class.create({
  name: 'Model',
  fields: {
    type: {type: Object}
  }
});


Meteor.startup(() => {
  let models = [
    new Model({type: Number(123)}),
    new Model({type: String('abc')}),
    new Model({type: 123}),
    new Model({type: 'abc'}),
  ];

  models.forEach((m) => {
    try {
      m.validate();
    } catch(e) {
      console.log(e);
    }
  });
});
```

This throws an error for every model with the message `"type" has to be an object [validation-error]`.  I'm looking forward to being able to use multiple types for a field.

**Comment by lukejagodzinski** [comment]
Ok so I have to implement unions to allow that

**Comment by talha-asad** [comment]
It would be awesome to have this feature sometime soon, the workaround for this is really ugly. Do you have a proposed way of declaring unions?

**Comment by lukejagodzinski** [comment]
Hey, I will work on that as the next feature. I will probably find some time next week. API will probably be sth like this:

```js
import { Union } from 'meteor/jagi:astronomy';

var StringOrNumber = Union.create({
  name: 'StringOrNumber',
  types: [String, Number]
});
```

Btw. I've abandoned the idea of integrating Astronomy with GraphQL. I've been testing this and didn't find any proper solution. So Astronomy will be in its current shape for a while.

**Comment by talha-asad** [comment]
Will this also support something like this:

```js
import { Union } from 'meteor/jagi:astronomy';

var StringOrNumber = Union.create({
  name: 'StringOrNumber',
  types: [[String], [Number]]
});
```

So an array of Strings or Numbers.

**Comment by lukejagodzinski** [comment]
It will work but not the way you wrote:

```js
const Item = Class.create({
  name: 'Item',
  fields: {
    strOrNumList: [StringOrNumber]
  }
});
```

**Comment by lukejagodzinski** [comment]
Feature implemented in v2.4.0

**Comment by talha-asad** [comment]
Sorry I didn't see it was not a class. Yup that works well.

How well does this work with auto casting?

**Comment by lukejagodzinski** [comment]
It's described in docs. It can't be done automatically. You have to provide your own casting function.

**Comment by s7dhansh** [comment]
How can I use `Union` for a string-or-array-of-strings field?

**Comment by lukejagodzinski** [comment]
@s7dhansh such a possibility would violate what union type is. It shouldn't allow storing strings and array of strings in the same field. Your schema design is probably wrong.
