### ISSUE TITLE
React Native: Client can insert invalid fields

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#428]
Hi,
I'm having some trouble with Astronomy and React Native. In a RN app, I can execute the following code:

```
Meteor.collection("messages").insert({chatId:this.props.doc._id,text:this.state.inputText, userId:Meteor.userId(), someFieldIDontWant:'1234'});
```

This is my schema:

```
Message = Class.create({
    name: 'Message',
    collection: Messages,
    fields: {
        text: {
            type: String
        },
        userId: String,
        createdAt: {
            type: Date,
            default: function() {
                return new Date();
            }
        },
        chatId: String
});
```

Why can the client add the field <code>someFieldIDontWant</code> to the doc? It isn't defined within the schema, but I can add it?

**Comment by dnish** [comment]
I don't know if this is the best solution, but my current fix would be a allow method on the server side, denying direct access and instead creating an Astronomy object:

```
Messages.allow({
    insert(userId, doc) {
         /** some other validation logic **/
        var message = new Message(doc);
        message.save();
        return false;
    }
});
```

Is this the recommended way when we try to access our Meteor backend over RN?

**Comment by lukejagodzinski** [comment]
You didn't read documentation carefully. You are inserting from the level of Collection not Class:

``` js
Messages.insert(); // Collection
// is not the same as
Message.insert(); // Class
```

The second one will not allow you inserting extra fields.

**Comment by dnish** [comment]
@jagi Yeah, I've just read it in the section "Differences between v1 and v2". I'm just wondering why you chose this approach? It's against MDG's way for opening Meteor. Astronomy isn't available as NPM package and it depends fully on the Meteor structure. So if we connect our none Meteor apps to a Meteor backend, we have to work with the collections over DDP and not with the Astronomy models - because they aren't available on a none Meteor app. 

Normally, we would use own methods to handle all of this, but in case of a chat application, we need an optimistic UI and so we have to use the collection way (because method simulation is also not available on a RN app).

**Comment by lukejagodzinski** [comment]
Astronomy was never designed to work with React Native. My approach is not against MDG's way. Only recently they stated that they will move all packages to NPM. Probably Astronomy 3.0 will work with GraphQL and will be published as NPM package. But it's too early to tell how future of Meteor will look like.
