### ISSUE TITLE
Field not updating

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#432]
Hey,
maybe it's too late, but I can't find the reason why my field "updatedAt" isn't updated. This is my schema:

```
Chats = new Meteor.Collection("chats");

Chat = Class.create({
    name: 'Chat',
    collection: Chats,
    fields: {
        user1: String,
        user2: String,
        user1Title:String,
        user2Title:String,
        createdAt: {
            type: Date,
            default: function() {
                return new Date();
            }
        },
        updatedAt: {
            type: Date,
            optional:true
        },

    }
});
```

On the server, I'm doing something like this:

```
var chat = Chat.findOne(doc.chatId);
chat.updatedAt = new Date();
chat.save();

 console.log(chat);
```

The console output is showing me the correct id with the correct updatedAt value:

```
{ _id: 'kYNhnY3jHSgnvpvta',
user1: 'QrZKTkzGyhYyGFXd9',
user2: '47bG9Tb9PXvXAXGnK',
user1Title: 'Hase',
user2Title: 'Dennis',
createdAt: Tue Jun 28 2016 15:55:01 GMT+0200 (CEST),
updatedAt: Thu Jun 30 2016 22:56:18 GMT+0200 (CEST) }
```

The problem: The value isn't saved on the database server. It is still showing the first date that was saved within updatedAt. The validation error object is undefined, so I guess this isn't a validation issue.

//Edit:

It works if I define another different value, f.e. user2Title:

```
chat.updatedAt = new Date();
chat.user2Title = "DennisX";
chat.save();
```

But this only works once. To make it work again, I need to set another user2Title again (and so on...).

**Comment by lukejagodzinski** [comment]
You're probably doing something wrong. I've tested it and it works. You have to make sure that `chat` object you are working with is in the most recent state, however it depends on the use case.

**Comment by dnish** [comment]
We changing the value in <code>server/security.js</code>:

```
Messages.allow({
    insert(userId, doc) {

        var chat = Chat.findOne(doc.chatId);


        if(chat.user1 != userId && chat.user2 != userId) {
            return false;
        }

        if(doc.userId != userId) return false;



        chat.updatedAt = new Date();
        chat.save();


        var message = new Message(doc);
        message.save();


        return false;
    }
});
```

The message is inserted from a React Native client. Inserting of the message works fine, updating the chat object not. We don't change it anywhere on the inserting process, so it should be the recent object.

Doing a direct update without Astronomy is also working fine:

```
Chats.update({_id:chat._id},{$set:{updatedAt:new Date()}});
```

// Edit:

It seems only to happen on Date fields (updating createdAt is also not working). If I only set user2Title to a random value, the change is saved on every update. 

```
chat.user2Title = randomString();
chat.save();
```

**Comment by dnish** [comment]
Works fine after upgrading from 2.0.1 to 2.1.0

**Comment by lukejagodzinski** [comment]
There were some changes in 2.1 that was related with detecting modifications, so maybe that's why it didn't work for you. It's always good to upgrade. Remember to read release note: https://github.com/jagi/meteor-astronomy/releases/tag/2.1.0
