### ISSUE TITLE
Weird behaviour using .getModified()

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#433]
I'm delaying my transition to Astronomy 2.x and still trying to use the 1.x branch.

I tried this pattern, where:
1. on the client I have an incomplete document, since I have only published and subscribed to some fields.
2. I update **one** field using `document.set`  and call `Document.methods.update.call({doc: document});`
3. On the server, I have the method defined like this:

```
Document.methods.update = new ValidatedMethod({
  name: 'Document.methods.update',
  validate: null,
  run({doc}) {
    console.log(`Updating guest ${JSON.stringify(doc, null, 4)}`);
    let modifiedFields = _.keys(doc.getModified());
    console.log(`Trying to validate fields that were marked as modified: ${modifiedFields.toString()}`);
    if (doc.validate(modifiedFields)) {
        ...
```

Now, if I check for `document.getModified()` on the client, I get only the modified field, as expected. However, on the server, I get _"Trying to validate fields that were marked as modified: [createdAt, updatedAt, bunch of other fields, the actual field modified]"_. Then my validation fails, because the document does not have the values of `updatedAt`, `createdAt`, `bunchOfOTherValues` etc... which were actually not intended to be updated by the method.

I have a hunch this is due to some behaviours making changes, like `Timestamp`. Is there something really wrong with this pattern, and if not, what's the correct way of fixing this?

**Comment by arggh** [comment]
Oh, forgot to add:

If I subscribe to all these missing values that are marked as modified by Astronomy, then suddenly the only field marked as modified is **the one I actually modified**.

**Comment by lukejagodzinski** [comment]
I totally don't understand your problem. Your description is very chaotic. However, what I can say is that you should always be subscribed to all fields in a model or at least get a document on the server and update it with values that were modified. However, I don't understand your code and your problem so it's just a guess

**Comment by arggh** [comment]
Sorry for the bad description, I'll try and explain it with code samples:

**client/client.js** _(update a field in document, call an update method in server)_

```
updateDocumentName() {
   let document = this.document();
   document.set({
      name: 'new name'
   });
   console.log(_.keys(document.getModified())); // prints ['name']
   Documents.methods.update.call({ doc: document });
}
```

**server/methods.js** _(check what fields are modified and save only those)_

```
Documents.methods.update = new ValidatedMethod({
  name: 'Documents.methods.update',
  validate: null,
  run({doc}) {
    let modifiedFields = _.keys(doc.getModified());
    console.log(modifiedFields);
    // ?!? prints ['createdAt', 'updatedAt', 'name', 'userId', 'someOtherFieldThatWasNotTouched', 'randomField']

    if (doc.validate(modifiedFields)) {
        doc.save(modifiedFields);
    } else {
        // We will end up here, since our doc doesn't have values in fields returned by getModified
        doc.throwValidationException();
    }
  }
});
```

So, what I'm trying to achieve is:
1. Client updates a field on a document that doesn't have all the values
2. Client calls a method on the server with the updated document
3. Method on server checks what fields have been changed by using `.getModified`
4. Method on server validates and updates only those fields, therefore not needing the entire document

It fails in point 3, where the `doc.getModified()` return a whole bunch of fields that were not actually modified.

The interesting part is, that if I have those values present on the client (and they are still not touched), the  `doc.getModified()` only returns the field that was actually updated on the client. 

I hope I came across better this time.

**Comment by lukejagodzinski** [comment]
I think better way of doing it would be sending document id and modified fields only instead of entire document. Fetching document with the given ID on the server and setting all modified values in a document one more time.

**Comment by arggh** [comment]
That's how I used to do it, but then I ended up writing lots of methods on the server side:

```
Document.methods.updateName,
Document.methods.updateCount,
Document.methods.updateSomething
...
```

I was trying this new approach to have just one method, that would know which fields have been updated   and act accordingly. Maybe something like you have in v2.0.
