### ISSUE TITLE
Sort-behaviour coming to Astronomy v2.x?

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#434]
I noticed Sort is still missing on the docs of v2.x. Is Sort-behavior coming to v2.x any time?

**Comment by lukejagodzinski** [comment]
Maybe, I don't know. Updating a package should be fairly easy however, it may not work properly in big applications as there is no transactions in MongoDB, so using such databases with sort behavior may not make any sense.

**Comment by arggh** [comment]
Any updates on this one? I was looking on implementing it myself, but the documentation on writing behaviors with Astronomy V2.x are missing.

Looking at the sources of old sort-behavior and the new slug- and timestamp-behaviors, it wasn't immediately obvious where I should start the update process..

**Comment by arggh** [comment]
I think there is still a use case for this, for example, when it's guaranteed that only one or few people will be re-arranging a set of documents.

Also, would be cool to implement some kind of auto-correcting version, which fixes the ordering should it get mixed up.

**Comment by lukejagodzinski** [comment]
For now I'm not planning updating this plugin. I have a lot of work with other stuff.

**Comment by arggh** [comment]
What about the documentation on writing Behaviors or some guidance on what exactly should be changed to make the old sort-behavior work with V2?

**Comment by lukejagodzinski** [comment]
As I said I have a lot of work to do and don't have time to provide neither sort behavior or documentation for behaviors. It's not hard to do when you just examine how other behaviors for v2 are written. Most of code you already have in v1 behavior. You just need to setup it correctly.

**Comment by arggh** [comment]
Got it working, thanks.
