### ISSUE TITLE
Comply with the SemVer conventions

### ISSUE THREAD

**Issue by jsamr** [jagi/meteor-astronomy#435]
First of all, thanks a lot for this awesome package!

But I saw some breaking changes in version **2.1.0**, which does not comply with the _SemVer_ conventions.

Quoting [from the official Meteor guide](https://guide.meteor.com/writing-atmosphere-packages.html#version-constraints) : 

> Meteor’s package system **relies heavily on Semantic Versioning, or SemVer**. When one package declares a dependency on another, it always comes with a version constraint. These version constraints are then solved by Meteor’s industrial-grade Version Solver to arrive at a set of package versions that meet all of the requirements, or display a helpful error if there is no solution.

The [_SemVer_ specs](http://semver.org/) states that : 

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1. MAJOR version when you make incompatible API changes,
> 2. **MINOR** version when you add functionality **in a backwards-compatible manner**, and
> 3. PATCH version when you make backwards-compatible bug fixes.

So any breaking changes must be postponed to a MAJOR release.

**Comment by lukejagodzinski** [comment]
I know SemVer convention. I had to make compatibility breaking change because of bad assumptions in 2.0. It was first and the last compatibility breaking change.

**Comment by jsamr** [comment]
Ok, thanks for the clarification!
