### ISSUE TITLE
Consistent ID generation with Astronomy

### ISSUE THREAD

**Issue by moberegger** [jagi/meteor-astronomy#436]
I was trying to implement the validated-method pattern of consistent id generation as described [here](https://atmospherejs.com/mdg/validated-method#id-generation-and-returnstubvalue), but ran into some problems.

Basically, what this pattern tries to accomplish:
- Run the method on both the client (ie. simulation) and server
- Have the same ID generated on both the client and server
- The generated ID is available immediately on the client

When using the Astronomy API, this doesn't work; different IDs are generated on either client and server. When switching to the standard Collection.insert API, it works; the same ID is generated on both client and server.

Some sample code below.

I have a Meteor collection and Astronomy class defined like:

```
export const Images = new Mongo.Collection('images');

export const Image = Class.create({
  name: 'Image',
  collection: Images,
  secured: true,
  fields: {
    url: String,
    ownerId: String,
  }
});
```

If I have a method defined on both client and server like...

```
export const insert = new ValidatedMethod({
  name: 'image.insert',
  validate: null,
  run({ url }) {
    const image = new Image({
      url: url,
      ownerId: this.userId,
    });
    return image.save();
  },
});
```

that is called on the client like...
`const imageId = insert.call({ url: url });`

One ID will be generated when the method runs in simulation mode on the client, and a completely different one will be generated when the method is run on the server.

This also happens if I use Astronomy's insert API, like so:

```
export const insert = new ValidatedMethod({
  name: 'image.insert',
  validate: null,
  run({ url }) {
   return Image.insert({
      url: url,
      ownerId: this.userId,
    });
  },
});
```

But, if I use the Meteor's native Collection.insert API like...

```
export const insert = new ValidatedMethod({
  name: 'image.insert',
  validate: null,
  run({ url }) {
   return Images.insert({
      url: url,
      ownerId: this.userId,
    });
  },
});
```

The same ID is generated on both client and server, as expected. Note that in the first scenario, I am using Astronomy's Image.insert (via the Asto class), and in the second scenario, I am using the Mongo Collection's Images.insert.

I am not sure what could be causing this... if Astronomy is using the Mongo.Collection.insert to insert new records when calling .save(), the consistent ID generation should work as expected. 

My workaround for this right now is to create my Astro object to perform validation, and then insert the raw fields directly into the collection. This is unfortunate because I have to work outside of Astronomy's nice API, but it's the only way I have been able to get this to work. 

Would it be possible to have Astronomy support this feature through the Asto save() method?

**Comment by moberegger** [comment]
Ok, so I did a bit of digging around in the source code and I think I have an idea what is causing this.

In modules/storage/utils/document_insert.js, on line 68 (sorry... I have no idea how to link to source code in github...) you have the following:

```
// There is a difference in what the insert method returns depending on the
// environment. On the client it returns an inserted document id, on the
// server it returns array of inserted documents. So we always return the
// generated id. We can't send an entire document because it could be a
// security issue if we are not subscribed to all fields of a document.
const result = Collection._collection.insert(values);
```

I got here by following the logic through the save() function to where an insert is done. So, what I suspect the root cause is that the consistent ID generation is done _only_ when using the Collection.insert API, and does not happen when doing an insert directly to the raw Mongo collection (like the code above).

Is there a specific reason why the insert is being done this way instead of through the API that Meteor gives you? I noticed the same thing is done for update() and remove() as well.

**Comment by lukejagodzinski** [comment]
If I would call `Collection.insert` on the client it would perform the insert operation also on the server and I don't want it. I want to control the process on the server, because I have to perform validation. I can't just assume that client validation is safe. It's strange that it produces different ID on the client and server as I'm using the same mechanism as MDG. However I will take a look at it, maybe I'm missing something.

**Comment by lukejagodzinski** [comment]
Can you create minimal reproduction repository?

**Comment by moberegger** [comment]
Yup, no problem. I will do it tonight. Sorry about that.

I started making one last night and just got too tired to finish. Was hoping I could get away without doing it! :)

**Comment by moberegger** [comment]
I put up a reproduction here: [https://github.com/MichaelOber/astro-consistent-id-repo](https://github.com/MichaelOber/astro-consistent-id-repo)

Let me know if there are any issues running it. I hacked it up pretty quickly.

**Comment by lukejagodzinski** [comment]
Ok I know what is the problem. I'm generating ID in wrong place. It's easy fix. I will inform about update.

**Comment by lukejagodzinski** [comment]
Ok I've fixed it. If you want to use it right away you can clone current version from GitHub. Otherwise it will be available with the next bug fix version. I only have to fix one more bug and I will be releasing. Closing for now.

**Comment by moberegger** [comment]
Amazing! Thank you so much!
