### ISSUE TITLE
Class security using events 

### ISSUE THREAD

**Issue by Deadly0** [jagi/meteor-astronomy#438]
I'm try to check permissions inside events as described in docs:

```
events:
    beforeUpdate: () ->
        if !Roles.userIsInRole Meteor.user(), ['admin']
            throw new Meteor.Error 403, 'You are not authorized'
```

But when i call `myModel.save()` on server side (where it's no need to check permissions) it raises an error:

```
Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
```

How to check permissions in this case?

**Comment by lukejagodzinski** [comment]
Don't use coffee script for sample codes and there is to little context that you're providing. How/where do you call it on the server? What is `Roles.userIsInRole`?

**Comment by Deadly0** [comment]
```
events: {
    beforeUpdate: function() {
        if (!Roles.userIsInRole(Meteor.user(), ['admin'])) {
            throw new Meteor.Error(403, 'You are not authorized');
        }
    }
}
```

`Roles.userIsInRole` from the popular Meteor package https://atmospherejs.com/alanning/roles , but it doesn't matter. I call `model.save()` from server background task, where Meteor.user() not available.

**Comment by lukejagodzinski** [comment]
So it's not a thing related with Astronomy. Your are just calling function which is not available. If it's a background task that it's called on schedule then you certainly can't access user id as there is no user.

**Comment by Mokto** [comment]
I have the same issue here.

Is beforeUpdate server side not knowing Meteor.user() ?

**Comment by Mokto** [comment]
Can I know Meteor.user() in any method ?

**Comment by lukejagodzinski** [comment]
Astronomy does not change anything about `Meteor.user()`

**Comment by Mokto** [comment]
@jagi I know but the issue here is that we want to be able to access Meteor.user() in beforeUpdate, afterUpdate events server side. It seems to be impossible because when we do that, it throws 

`Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.`

**Comment by lukejagodzinski** [comment]
Such error does not mean that it's a bug in Astronomy. Probably you're just calling it in not Meteor method context. Show the code so I will be able to tell more.

**Comment by Mokto** [comment]
Thanks @jagi. I didn't manage to reproduce this bug. Sorry for the trouble and thanks for your help !

**Comment by lukejagodzinski** [comment]
Ok no problem
