### ISSUE TITLE
How to specify that a field is indexed in MongoDB?

### ISSUE THREAD

**Issue by dpdonohue** [jagi/meteor-astronomy#44]
Apologies if I missed this somewhere.  Thanks for an awesome product!

**Comment by jagi** [comment]
This feature is already available but not published yet. I will publish it on Monday :)

You will define it in the schema definition:

```js
Post = Astro.class({
  collection: Posts,
  fields: {
    name: 'string'
  },
  indexes: {
    indexName: {
      fields: {
        name: 1
      },
      options: {}
    }
  }
});
```

Where the value in the field is an index order. In fact it just passes an index definition to standard `ensureIndex` function of the MongoDB collection.

**Comment by dpdonohue** [comment]
Cool!  Ask and ye shall receive.  Do you support shorter hand notation perchance like
```
fields: {
    name: {
        type: 'string',
        index: 1
    }
}
```

or like this
```
fields: {
    name: 'string',
    email: 'string'
  },
indexes: ['name', 'email']
```

**Comment by jagi** [comment]
Yes of course I can do that. I did it for validators where you can define them just with the field definition. The same can be handy for the one field indexes. However the are situation where you have to have an index defined for more than one field.

So I will add this feature on Monday. Stay tuned

**Comment by laurentpayot** [comment]
Great package indeed, I'm evaluating it to eventually replace aldeed's packages in a project (can't wait for the forms).
Could you give an example of how to set the options so that in your example the <code>name</code> field is a <b>unique</b> index?

**Comment by Taik** [comment]
Hi @jagi thanks for adding this. Are there plans for supporting compound indices? (multi-key index)

**Comment by jagi** [comment]
@Taik yes this feature is already implemented. It will be published today and documented.

**Comment by jagi** [comment]
Indexes added in the version 0.12.0. Now I will update documentation. I'm closing this issue for now.
