### ISSUE TITLE
History.md for v2

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#441]
I notice this package is improving in long strides and the feature enhancements have been wonderful, however it's difficult to keep track of them for people who aren't very active on Github, and I would suggest we start keeping a good versioned history for v2, currently History.md has details for v1.

**Comment by talha-asad** [comment]
On second note, I just realized you have notes under each release. Should i create a pull request with them nicely sorted in History.md?

**Comment by lukejagodzinski** [comment]
Yes I've moved to descriptions in releases but in deed it would be good to have them also in history.md so if you want to help with that just create PR :)

**Comment by talha-asad** [comment]
I've already got this part done, will be submitting a PR for that along with the other contributions. You can have a look [here](https://github.com/talha-asad/meteor-astronomy/blob/v2/HISTORY.md)

**Comment by lukejagodzinski** [comment]
Ok cool, waiting for PR!

**Comment by talha-asad** [comment]
#452 submitted.
