### ISSUE TITLE
Using push on array fields changes default value

### ISSUE THREAD

**Issue by ghost** [jagi/meteor-astronomy#442]
I observe the following behavior:

Class definition:

```
const Entity = Class.create({
    collection: Entities,
    fields: {
        myArray: {
            type: [String],
            default: []
        }
    }
);
```

When I'm using the `Array.push` method on `myArray`, the default value gets changed. When the server gets restarted the default is set back to `[]`.
So when I use the following "insert" method the first time, the `myArray` value of the new entity is set to `[42]`, the second time the method is called it is set to `[42, 42]`, the third time to `[42, 42, 42]`, and so on:

```
Meteor.methods({
   "insert"() {
        const entity = new Entity();            
        if (case === STAY_PERSISTENT) {
            entity.myArray.push(42);   // Changes default to `default.push(42)`
        }
        else {
             entity.myArray = entity.myArray.concat(42);   // Leaves default unchanged
        }
        entity.save();
    }
})
```

By the way, thank you for your wonderful work! :)

**Comment by lukejagodzinski** [comment]
And what's wrong with that? You create new instance of the `Entity` on each method call and you just push the number `42` to the array. The `if` statement does matter as you are creating a new instance on each method call.

**Comment by ghost** [comment]
Okay thanks for the answer, I just would have expected a hard copy for basic types ;)
