### ISSUE TITLE
Any plans to migrate to npm? 

### ISSUE THREAD

**Issue by PolGuixe** [jagi/meteor-astronomy#443]
I know a lot of meteor packages are planning to migrate to npm. 

Any idea if Astronomy has any plans on doing so...?

**Comment by lukejagodzinski** [comment]
Probably not until version 3.0. I'm waiting until Meteor switch all packages to npm that Astronomy is using. Before that it's not possible for Astronomy to switch.

**Comment by JulianKingman** [comment]
I'm curious, what are the Meteor dependencies? I might be able to help with migrating, I would find this useful in my react-native projects, for which I currently have to use simple schema.

**Comment by lukejagodzinski** [comment]
Astronomy is heavily dependent on meteor collections and any save/remove operation goes through the meteor method. I was thinking about creating separate package that can be used in any JS project, which would be stripped of the storage functionality. It would allow defining schemas, validation, values casting etc. But I have several projects going on and I lack of the time to develop it :)
