### ISSUE TITLE
Behavior default options are shared between classes

### ISSUE THREAD

**Issue by ochicf** [jagi/meteor-astronomy#444]
When creating a custom behavior that has an option with a default value of a non primitive type (such as an array or object), that value is shared across all classes that implement that behavior and that do not provide a custom value. I don't know if this is the intended behavior, but it seems wrong to me.

I've made this simple example just to replicate the error. I know that in this specific case the validators array could (and propably should) NOT be an option, but it is just a demo.

``` js
import { Mongo } from 'meteor/mongo';
import { Class, Behavior } from 'meteor/jagi:astronomy';

Behavior.create({
  name: 'range',
  options: {
    fieldName: null,  // field to apply the behavior
    min: null,        // range lower limit
    max: null,        // range upper limit
    validators: [],   // validators that will be added to the field
  },
  createClassDefinition() {
    const { fieldName, validators, min, max } = this.options;
    if (_.isNumber(min)) {
      validators.push({
        type: 'gte',
        param: min,
      });
    }
    if (_.isNumber(max)) {
      validators.push({
        type: 'lte',
        param: max,
      });
    }
    return {
      validators: {
        [fieldName]: validators,
      },
    };
  },
  apply(Class) {
    Class.extend(this.createClassDefinition(), [
      'validators',
    ]);
  },
});

const Product = Class.create({
  name: 'Product',
  collection: new Mongo.Collection(null),
  fields: {
    price: {
      type: Number,
      optional: true,
    },
  },
  behaviors: {
    range: {
      fieldName: 'price',
      min: 0,
    },
  },
});

const Client = Class.create({
  name: 'Client',
  collection: new Mongo.Collection(null),
  fields: {
    age: {
      type: Number,
      optional: true,
    },
  },
  behaviors: {
    range: {
      fieldName: 'age',
      min: 0,
      max: 100,
    },
  },
});
```

Note that Product.price should only have the lower limit validator and that Client.age should have both limits. But when comparing the behaviours in the console:

![screen shot 2016-07-15 at 17 23 31](https://cloud.githubusercontent.com/assets/16188653/16879457/ea645bae-4ab0-11e6-9e38-9c1b21d5161a.png)

All 3 validators have been added to both array. And indeed, they are the same array:

![screen shot 2016-07-15 at 17 24 49](https://cloud.githubusercontent.com/assets/16188653/16879487/0e9dd68a-4ab1-11e6-9be9-ebd8cb7ebe3e.png)

The immediate solution would be to set a null default in order to check in `createClassDefinition` if the user has specified that parameter and initialise it with the default value if not. But that's basically what I think that the default options should be doing.

**Comment by lukejagodzinski** [comment]
Hmmm I've probably never thought about behavior options to be objects so that's why I'm not cloning them. However I can clone options in the next bug fix release. However, it may be applied only to plain JS objects.

**Comment by lukejagodzinski** [comment]
At first I though it's a bug but it's not. You actually shouldn't provide the `validators` option as it's not intended to be set by developer. `options` are only to be set in a class definition. So you should create "private" `validators` property on the fly in the `createClassDefinition` method.

**Comment by JulianKingman** [comment]
I think my situation is similar: I'm creating a `relationship` behavior, initialized like so:
````javascript
relations: [
      {
        keyStore: 'Leagues', // Where foreign _id's are stored
        foreignKeyStore: 'Users', // Where local _id's are stored in foreign doc
        foreignClass: 'League', // Class to relate to
      },
      {
        keyStore: 'Teams',
        foreignKeyStore: 'Users',
        foreignClass: 'Team',
      },
    ],
````
What's happening is the same keyStore value is being used for both behavior instances. I'm not quite sure how the lines are getting crossed, but I'm ending up with the `_id` of both `Leagues` and `Teams` only in the `Teams` field.

**Comment by lukejagodzinski** [comment]
Relations is rather to be module not behavior. It can be created as a behavior but it's less flexible then. I can understand that not making copy of options may be a problem and I will probably fix that but creating a copy of all options in all possible scenarios for behaviors may be very performance intensive operation and may not be the best solution.

**Comment by JulianKingman** [comment]
The problem I'm running into is actually because I have a helper which calls a method, but it doesn't know which instance of the behavior to use.The helper needs to know based on the parameter (in this case `className === behavior.options.foreignClass`), so I'll just use Class.getBehavior and filter for the correct one in the method.

**Comment by JulianKingman** [comment]
Is there an easier way to get a behavior by it's option value?

**Comment by lukejagodzinski** [comment]
You know I would have to check it out because to be honest I don't remember :). But I would encourage you to create a module for that because behaviors are limited. How to create module? Everything in Astronomy is a module. Storing documents is a module, fields is a module, events is a module. Here is a code for `storage` module https://github.com/jagi/meteor-astronomy/tree/v2/lib/modules/storage which will be most similar to relations module because both are storing some documents. There is a main `module.js` file where module initialization takes place. But when you're creating external module package you would `import {Module} from 'meteor/jagi:astronomy' instead of `import Module from '../../core/module.js';` which is internal Astronomy import. Everything else is similar. You can learn how to create your own module by investigating code. It's quite simple actually. I will probably create video tutorial very soon about how to create your own module. Here are tutorials I've made so far https://goo.gl/9gnrav

**Comment by JulianKingman** [comment]
Thanks, I'll look into that. In either case, in behaviors there should be a way to get the correct instance of the behavior. I'm not sure what's the right way to do that, the more I think about it the tricker it is. Maybe something like this?
````javascript
createClassDefinition() {
  // get array of behaviors?
  const behaviors = this;
  helpers: {
    example(param) {
      // get instance of behavior where the option is equal to the param?
      const behavior = behaviors.getByOption({option: param});
    }
  }
}
````

**Comment by lukejagodzinski** [comment]
I've checked and the `this.options` property in each behavior has different values so you're probably doing something wrong.

**Comment by JulianKingman** [comment]
True, but that doesn't always work. For example my `relateTo` helper takes a parameter that determines which options should be used, so there's no way to tell which options it should use until it runs. 
It's not so hard to get the options from `Class.getBehavior`, but it would be nice to be able to easily get all behavior options from `this`.

**Comment by lukejagodzinski** [comment]
You know the `relateTo` helper can operate with all relation behaviors attached to the given class, so you have to find your own mechanism of checking which option to use. There is no other way of doing it automatically.
