### ISSUE TITLE
Uncaught exception error in IE11

### ISSUE THREAD

**Issue by Zaiban** [jagi/meteor-astronomy#445]
Hello. I'm having trouble getting my app work on IE11. I've narrowed the problem down to Astronomy having uncaught exceptions. When IE11 detects uncaught exception, it seems to stop executing rest of the code and app fails.

When I put all Class.create -statements inside try-catch blocks, the app loads. But its still not working, as the imported astronomy variables show up as undefined.

The app runs normally on all other major browsers, including Edge. I myself don't care about IE11, but my client says IE11 is required. Does anyone have any clues how to solve the problem?

**Comment by jsamr** [comment]
What are those uncaught exceptions?

**Comment by Zaiban** [comment]
`"[\"ReservationChangePair\" class][\"fields\" property][\"amount\" field] Type does not exist"`

So it seems to be a type error referring to "amount" field, which is a Number. Hmm.. I'll do a little more research on this.

**Comment by jsamr** [comment]
ok, can I see the `ReservationChangePair` class declaration ?

**Comment by Zaiban** [comment]
Don't have an NDA on this so I guess its fine, here's the whole file.

```
import { Mongo } from 'meteor/mongo';
import { Class } from 'meteor/jagi:astronomy';

export const Equipments = new Mongo.Collection('equipments');

export const ReservationChangePair = Class.create({
  name: 'ReservationChangePair',
  fields: {
    date: Date,
    amount: Number,
  },
});
export const Equipment = Class.create({
  name: 'Equipment',
  collection: Equipments,
  secured: true,
  fields: {
    name: {
      type: String,
      index: 1,
    },
    amount: {
      type: Number,
      validators: [{
        type: 'gte',
        param: 0,
      }],
    },
    reservationChangePairs: {
      type: [ReservationChangePair],
      default: [],
    },
    attributes: {
      type: [String],
      default: [],
      optional: true,
    },
    category: {
      type: String,
      optional: true,
    },
    description: {
      type: String,
      optional: true,
    },
    notes: {
      type: String,
      optional: true,
    },
  },
  behaviors: {
    timestamp: {
      hasCreatedField: true,
      createdFieldName: 'createdAt',
    },
  },
});
```

**Comment by jsamr** [comment]
Strange (I'm not a maintainer).
The [Number type definition is here](https://github.com/jagi/meteor-astronomy/blob/1823acb76800919699c9afe92743819e86e1cf80/lib/modules/fields/types/number.js). Can you check in IE11 if `Number` is exposed to the global namespace?

**Comment by Zaiban** [comment]
Yep creating Number from the IE console works as is expected. Hate these browser specific bugs :|

Edit: and of course I'm using Number elsewhere in my code too. But only the Astronomy class introduces this problem.

**Comment by jsamr** [comment]
yeah.... :disappointed: Try the following in the browser console : 

``` javascript
var Type = require('meteor/jagi:astronomy/lib/modules/fields/type').default
Type.find(Number) // <= should output the Number type definition
```

**Comment by Zaiban** [comment]
Outputs `undefined` for Number. Tested with String and Date also and they are working.

**Comment by jsamr** [comment]
Ok, we've pin the bug. What about `Type.types.Number` ?

**Comment by jsamr** [comment]
I suggest we continue [on gitter](https://gitter.im/jagi/meteor-astronomy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

**Comment by lukejagodzinski** [comment]
Have you manage to find a bug? I've seen that problem may be in the lodash, right?

**Comment by jsamr** [comment]
I'm not yet sure it comes from lodash after all. But it's definitely in the `Type.find` method ; I don't have any Windows set up around, so I couldn't investigate further ; waiting for @Zaiban to do some tests

**Comment by lukejagodzinski** [comment]
Yep me either. I don't want to setup VM just to test this bug. So I will wait for @Zaiban too

**Comment by Zaiban** [comment]
Here are some tests results
Number with lodash@4: https://gist.github.com/Zaiban/9751730dba4d4cedb0a8a479a8024179
Number with lodash@3: https://gist.github.com/Zaiban/9b4d3bd58b9fcf9e8e29d3e3f85cb83f

Everything else than Number work with both lodash 3 and 4.

**Comment by Zaiban** [comment]
Test results: https://gist.github.com/Zaiban/9751730dba4d4cedb0a8a479a8024179

Only number is broken, I tried giving any other type to findtype() and it returns the correct Type.types object.

Also tried downgrading to lodash 3 but that did not fix the issue.

**Comment by Zaiban** [comment]
In short, with IE11:

```
var Type = require('meteor/jagi:astronomy/lib/modules/fields/type').default
Type.types.String.class === String
true
Type.types.Date.class === Date
true
Type.types.Number.class === Number
false
```

With Edge (or any other browser I guess..):

```
var Type = require('meteor/jagi:astronomy/lib/modules/fields/type').default
Type.types.String.class === String
true
Type.types.Date.class === Date
true
Type.types.Number.class === Number
true
```

**Comment by lukejagodzinski** [comment]
It's strange as `Type.types.Number.class` and `Number` are actually the same references to number constructor. Can you check this one?

``` js
Type.types.Number.class.prototype === Number.prototype
```

**Comment by jsamr** [comment]
I noticed in [the official Microsoft doc](https://msdn.microsoft.com/en-us/library/jj159602%28v=vs.94%29.aspx), they use `==` equality, see snippet beneath : 

``` javascript
var num = new Number();

if (num.constructor == Number)
    document.write("Object is a Number.");
else
    document.write("Object is not a Number.");

// Output:
// Object is a Number.
```

**Comment by lukejagodzinski** [comment]
It's definitely bug in IE11 because strict equality operator (`===`) works properly with other types like `String` or `Boolean` and it's also working properly in all major browsers. And in fact the `constructor` property should be the same across all instances of a given class. I could use loose equality operator (`==`) but I don't know if it's correct in this place. In theory after reading documentation it should work as we are comparing two `Function` objects so no conversion will take place here. Can you check what is the result of the following `Object.is(Number, Number)` in IE11?

**Comment by Zaiban** [comment]
Here are some cases:

```
var Type = require('meteor/jagi:astronomy/lib/modules/fields/type').default
undefined
Type.types.Number.class === Number
false
Type.types.Number.class == Number
false
Object.is(Number, Number)
true
Object.is(Number, Type.types.Number.class)
false
Type.types.Number.class.prototype === Number.prototype
true
```

When I inspect the Number class in IE11, there are 2 fields that catch my attention:

```
arguments<Funktion arguments-ominaisuuden käyttö ei ole sallittua strict-tilassa>
caller<Funktion tai argumenttiobjektin caller-ominaisuuden käyttöä ei sallita strict-tilassa>
```

(the messages are in Finnish, they basically say that you cant use this property when in strict mode)

In other classes in IE11, and with the Number class in other browsers than IE11, those 2 fields show up as "null". Only in IE11 and with Number, they instead show that message. So probably that causes the comparisons to turn up as false.

**Comment by lukejagodzinski** [comment]
Yes probably you're right. I'm still amazed how is it possible that IE developers do so bad work. It's always like all browsers work properly and only IE isn't :).

Ok so if prototypes comparison works properly then I can change it because in other browsers it also works with prototypes.

**Comment by jthomaschewski** [comment]
I got the same problem now - Have you found any workaround/hotfix?

**Comment by lukejagodzinski** [comment]
I will probably do check using prototypes but don't know if it's correct in all cases.

**Comment by lukejagodzinski** [comment]
I've fixed it just by checking prototypes. I hope it will work. I will release it with the next minor Astronomy version. If you want to use it for now just clone GH repo to your local packages directory.
