### ISSUE TITLE
What is the result of throwing an exception inside an event listener ?

### ISSUE THREAD

**Issue by jsamr** [jagi/meteor-astronomy#446]
Let's say I'd like to prevent the save operation under certain circumstances by throwing a custom exception that I could catch and handle properly to display a contextual message to the user. 

So I would write something like : 

``` javascript
beforeSave (e) {
  e.preventDefault()
  throw new Meteor.Error('some.specific.failure')
}
```

My questions are following (for _beforeSave_, _beforeUpdate_ and _beforeRemove_) : 
- Is the `preventDefault` useless here? 
- Will the event still propagate to nested classes? 

I would guess that `preventDefault` doesn't change anything, but I might be wrong.

Would be nice to have some documentation about errors in events, 

Cheers

**Comment by lukejagodzinski** [comment]
Yes it will immediately stop code execution and even will be just thrown and can be caught in the callback function of the `save` method. However, the `preventDefault` method is just more general way of doing the same thing. Of course, when you throw custom error, you can provide message, so in some cases it may be a better way.
