### ISSUE TITLE
cannot find module 'meteor/jagi:astronomy'.

### ISSUE THREAD

**Issue by emilianosantucci** [jagi/meteor-astronomy#447]
Hi @jagi,
I'm starting new project and I want use your great ODM with Angular2 and Meteor, writing in TypeScript.
Anyway I'm not found library compatibility with TS, it's right?

I'm trying to add module but I receive message error `cannot find module 'meteor/jagi:astronomy'` when use `Class` object.

Can you help me?

**Comment by lukejagodzinski** [comment]
I haven't been working with TS and Angular2. I don't think it's a question you should ask here. It's rather related with Meteor and support for TS and modules loading. You probably can use the old way

``` js
const Class = require('meteor/jagi:astronomy').Astro.Class;
```

but it's far from perfect

**Comment by emilianosantucci** [comment]
Thank you.

I've create a TypeScript definition file (it's only a snippet) for your project, like this:

``` typescript
declare namespace Astronomy {
    module Class {
        function toJSONValue(...any): string;
        function getName(): string;
        function getParent(): string;
        function getChildren(): string;
        function create(any): this;
        function inherit(any): this;
        function extend(any): void;
        function get(className: string): this;
        function has(className: string): this;
        function includes(className: string): this;
        function isParentOf(clazz: this): boolean;
        function isChildOf(clazz: this): boolean;
    }
}

declare module 'meteor/jagi:astronomy' {
    export = Astronomy;
}

declare var Astro = Astronomy; 
```

Since I've decide to use your library anyway, I'll work to complete that and share with community on [https://github.com/DefinitelyTyped/DefinitelyTyped](url) after your revision.
This can help Astronomy to share it potentiality with TypeScript community.

It sound be good for you?

**Comment by lukejagodzinski** [comment]
I'm not quite sure what's your goal here. As I said I haven't been working with TS.

**Comment by emilianosantucci** [comment]
Basically, the definition _wrap_ class e function call for usage on TypeScript without errors during development and compilation, no more else.
When Meteor compile, match module name with your library, et-voila, Astronomy is usable for any developer that decide to use TS :).

Deep inside, for complete compatibility, _all class and methods_ usable by Astronomy API need to be wrapped.

I think that is a great opportunity for usage Astronomy as ODM for Angular2-Meteor's community that grow day by day.

**Comment by lukejagodzinski** [comment]
Are you using google translate or sth similar to translate to English? I'm saying this because grammar is not correct and it's hard to read and understand :)

I understand that TS requires providing return types for each method. But still don't understand what is your goal here. Do you want me to support TS? Or would you like to create package that would allow using Astronomy with TS?

**Comment by emilianosantucci** [comment]
Nothing translator, sorry is my bad english :D. 
Anyway, my first goal is use Astronomy. Said that, I can't because it isn't available in TS. So I've decide to implement it.
I think that the best approach to reach this goal is to collaborate with you, because owner of the project and you know API without reverse engineering the source code as I need to do :).

To clarify the goal, **I don't want re-implement** Astronomy on TS but create a definition file to allow its usage on TS projects, like below:
1.  Install Astronomy package with Atmosphere **(already available)**
2.  Install Astronomy TS definition file with Typings **(to do)**

I hope now its all clear although my english :D.

**Comment by lukejagodzinski** [comment]
Ok don't worry I understand most of what you said.
I didn't plan to support TS because I'm for open standards. JS is evolving rapidly and is good enough for most cases. So I don't want to waste my time on doing another package/extension that would allow use of TS. However I can answer your question if you have any.

**Comment by emilianosantucci** [comment]
Ok, thank you anyway for your time.

**Comment by emilianosantucci** [comment]
Hi @jagi,
here is a first stable release for TS definitions (w/ sample project): https://github.com/emilianosantucci/meteor-astronomy-ts

Any suggestion is welcome ;)

**Comment by james1293** [comment]
@emilianosantucci , thanks for creating this! And of course thanks to @jagi for creating astronomy!!
