### ISSUE TITLE
MomentJS on event hook

### ISSUE THREAD

**Issue by andrerfneves** [jagi/meteor-astronomy#45]
I'm trying to use MomentJS to format the date for the createdAt and updatedAt timestamps. I tried using an aftersave and a beforesave event like this

```javascript
    events: {
        aftersave: function() {
            var date = moment();
            date = moment(date, 'MM-DD-YYYY');
            post.set('postedAt', date );
        }
    }
```
Neither of them seem to create a postedAt field on the db when I add another post. Am I approaching this the correct way?

**Comment by webyak** [comment]
Did you give `date = new Date(moment(date, 'MM-DD-YYYY'));` a try?

**Comment by jagi** [comment]
If you set field's type to `date` the only correct format is `Date` object, so you shouldn't use momentJs for that. If you want to format date in the template you should create your own helper for that (on the level of template).

```js
{
  fields: {
    postedAt: 'date'
  }
}

/* ... */

post.set('postedAt', new Date());

/* ... */

Template.Post.helpers({
  postedAtFormatted: function() {
    return moment(this.postedAt, 'MM-DD-YYYY');
  }
});
```

or something like this depending on how it structured.

**Comment by andrerfneves** [comment]
Yup! I assumed that would work as well @yagi.

@webyak, I tried that, but I actually had to format it as ``` moment.().format('MM-DD-YYYY'); ```
Maybe there's two syntax?

Thanks guys!
