### ISSUE TITLE
"TypeError: Cannot read property 'create' of undefined" - After update from meteor 1.3 to 1.4-rc.0

### ISSUE THREAD

**Issue by GamesZentral** [jagi/meteor-astronomy#450]
Hi! I have a code:

``` javascript
import Astro from 'meteor/jagi:astronomy';
export const CodeList = Astro.Class.create(...);
...
```

And after meteor update to 1.4-rc.0, I get an error:

```
TypeError: Cannot read property 'create' of undefined
```

Can you tell if error is somehow related to your package or is it caused by new meteor release?

**Comment by lukejagodzinski** [comment]
I don't know if it's a bug in Meteor if it worked in 1.3 or they just fixed it in 1.4-rc.0 but your import statement is definitely wrong. There is no default export in `jagi:astronomy` package. So you can't write `import Astro from 'meteor/jagi:astronomy';`. Instead you should do `import { Class } from 'meteor/jagi:astronomy';` and later `export const CodeList = Class.create(...);`

**Comment by GamesZentral** [comment]
I noticed, that I was using somehow old version of Astronomy, I upgraded it, and now it all seems to work :D Thank you for your answer. And sorry for bothering you.

**Comment by lukejagodzinski** [comment]
Ok no problem :)
