### ISSUE TITLE
Automatically restrict fields during publishing

### ISSUE THREAD

**Issue by Faberle** [jagi/meteor-astronomy#453]
I would love to be able to write something like this: 

``` javascript

  const UserProfiles = new Mongo.Collection('userProfiles');

  const UserProfile = Class.create({
    name: 'UserProfile',
    collection: UserProfiles,
    fields: {
        name: {
            type: String
        },
    }
});

if(Meteor.isServer){
    UserProfile.extend({
        fields: {
            server: {
                type: String,
                private: true
            }
        }
    })
}


Meteor.publish("UserProfiles", () => {
    return UserProfiles.find({}, {
        fields: UserProfile.publicFields
    });
});
```

That way I only have the set of fields in one place instead of having to define them again in the publication.

Do you think that would be helpful? If so I would try to implement it

Cheers

**Comment by lukejagodzinski** [comment]
And how would you tell which fields are public?

**Comment by Faberle** [comment]
Non-Publich fields set private: true

``` javascript
fields: {
            server: {
                type: String,
                private: true
            }
        }
```

**Comment by lukejagodzinski** [comment]
On the server you have no way of telling what fields were added only on the client so such approach would not work in all cases.

**Comment by Faberle** [comment]
That why we have to add the private tag manually for all fields only available on the server. We have to modell that anyway, right?

Or what are the best practices for publishing using astronomy?

**Comment by Faberle** [comment]
One really big advantage would be that we can use Classes to secure the information, that is being send to the Client. Not only server/client wise, but also inheritance wise. So if I would publish a UserProfile of another user I would send less fields than if I publish MyUserProfile (Another Class that inherits from UserProfile).

``` javascript
const UserProfiles = new Mongo.Collection('userProfiles');

const UserProfile = Class.create({
    name: 'UserProfile',
    collection: UserProfiles,
    fields: {
        name: {
            type: String
        },
    }
});


const MyUserProfile = UserProfile.inherit({
        fields: {
            secret: {
                type: String
            }
        }
    })



Meteor.publish("UserProfiles", () => {
    return UserProfiles.find({}, {
        fields: UserProfile.publicFields
    });
});

Meteor.publish("MyUserProfile", () => {
    return UserProfiles.find({userId: Meteor.userId}, {
        fields: MyUserProfile.publicFields
    });
});
```

**Comment by lukejagodzinski** [comment]
I don't like idea of adding extra properties to fields definition just to allow easier publishing. You will actually write more code to achieve the same thing. Moreover you don't want to publish always the same set of fields. In one publishing function you may want to publish less fields the in the other. And using your approach you couldn't do so.

**Comment by Faberle** [comment]
I think in most cases you want to publish all the fields needed for a certain Class to function properly. If you want to publish less fields, you should have probably created a super Class containing only those fields. Also how would I be writing more code?
At the moment I have to be careful that I always publish all fields needed for a certain class. With the addition the published fields change as I change them in my Class. 

Also what is bad about adding extra properties?

I forked it now and am currently implementing a backend. In a week I can probably tell you if it was a wise choice or not xD

**Comment by lukejagodzinski** [comment]
I'm closing it for now. Let me know if you found your solution useful.
