### ISSUE TITLE
How to restrict the fields that can be updated by the client?

### ISSUE THREAD

**Issue by Faberle** [jagi/meteor-astronomy#455]
How can I prevent the client from updating credits? While still being able to update the name.
(Without using an Event to check for every field if its ok to update that specific one)

``` javascript
const UserProfiles = new Mongo.Collection('userProfiles');

 const UserProfile = Class.create({
    name: 'UserProfile',
    collection: UserProfiles,
    secured: {
        insert: true,
        update: true
    },
    fields: {
        name: {
            type: String
        },
       credits: {
            type: Number
        },
    }
});
```

**Comment by lukejagodzinski** [comment]
To secure update you can only use events or meteor methods. There is no other way of doing it.

**Comment by Faberle** [comment]
I hope I'm not annoying, but what about adding a field property to show that this field can only be changed by the server, a method or an event. 

So if we hit save, we simply check if a "secured" field has been modified.
Since the changes made by a method or an event happen on the server.

``` javascript
const UserProfiles = new Mongo.Collection('userProfiles');

 const UserProfile = Class.create({
    name: 'UserProfile',
    collection: UserProfiles,
    secured: {
        insert: true,
        update: true
    },
    fields: {
        name: {
            type: String
        },
       credits: {
            type: Number,
            secured: true
        },
    }
});
```

**Comment by lukejagodzinski** [comment]
I like this idea. I may introduce such feature in near future.

**Comment by jhuenges** [comment]
@jagi what does near future mean? :D

**Comment by Genroa** [comment]
I like this idea!

**Comment by lukejagodzinski** [comment]
@jhuenges probably 1-2 months :) depends on how much work I'm gonna have

**Comment by Faberle** [comment]
I looked at it, wanting to implement it myself but I'm unsure where. In the document_validate would be the appropriate place, however I'm able to pass trusted into it but I'm lacking the information on whether the field was modified or not yet. I'll take another look at it this weekend though.

**Comment by lukejagodzinski** [comment]
The best place to do it is in the `documentUpdate` utility function https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/storage/utils/document_update.js#L46.
1. Get all fields that have security rules.
2. Get all modified fields.
3. Check if there is any intersection between these fields.
In theory seems to be easy to do but there are subtle things to do here which may cause many problems. I mean nested fields. We should perform such operation for each nested field, so we need some method that gets modified fields as argument and traverse class fields and check if they intersect.

**Comment by lukejagodzinski** [comment]
It was long time from when we talked about this feature and I'm sorry to tell that I will probably not implement this feature as it would be hard to do and have little benefit for community. As there is now meteor methods feature it's much simpler to prepare methods that will update only chosen fields.
