### ISSUE TITLE
Is it possible to use Astronomy with mdg:validated-method ?

### ISSUE THREAD

**Issue by dgroch** [jagi/meteor-astronomy#458]

**Comment by lukejagodzinski** [comment]
Yes it is possible, however there was a bug in generating IDs which is fixed but not yet published. However, you can use the most recent version from GitHub

**Comment by dgroch** [comment]
thanks @jagi

**Comment by dgroch** [comment]
Can you direct me to a code sample?

Get Outlook for iOS

On Tue, Jul 26, 2016 at 4:46 PM +1000, "jagi" notifications@github.com wrote:

Yes it is possible, however there was a bug in generating IDs which is fixed but not yet published. However, you can use the most recent version from GitHub

**Comment by lukejagodzinski** [comment]
Here is the issue https://github.com/jagi/meteor-astronomy/issues/436 where I was fixing the bug with IDs generation. You can find there a reproduction repository with some code samples.

**Comment by dgroch** [comment]
Thanks!!

Get Outlook for iOS

On Tue, Jul 26, 2016 at 10:03 PM +1000, "jagi" notifications@github.com wrote:

Here is the issue #436 where I was fixing the bug with IDs generation. You can find there a reproduction repository with some code samples.
