### ISSUE TITLE
Setting _id on new document

### ISSUE THREAD

**Issue by dapearce** [jagi/meteor-astronomy#46]
Hi, great package and thanks for all the time put in!

Is it possible to set the `_id` when inserting new documents? I'm storing data from a 3rd party API which already includes a unique ID. I need to query based on this 3rd party ID, and since `_id` is indexed automatically I'd prefer to just use the 3rd party ID, rather than having to create another index.

**Comment by jagi** [comment]
Hi, thanks.

Hmm I've denied setting the `_id` field but I can change that behavior.
I will make this change with today's update.

**Comment by jagi** [comment]
Now you can set a document's id on creation in the version 0.12.0 of Astronomy. Enjoy :)

**Comment by dapearce** [comment]
Great, thanks!
