### ISSUE TITLE
Is it possible to check the whole document like we do in simple schema?

### ISSUE THREAD

**Issue by THPubs** [jagi/meteor-astronomy#462]
Hi, In simple schema, we can check the whole document by matching the schema like this : `check(document, BookSchema);`. Can we do it in Astronomy?

**Comment by lukejagodzinski** [comment]
You can check that way only if the `document` is instance of the `BookSchema` class in Astronomy. I didn't know that it's possible at all in SS. I will read more about it and if it's actually possible I will probably implement such feature

**Comment by lukejagodzinski** [comment]
Yes in deed it's working that way and it would be possible to add such functionality to Astronomy however I don't want to do it the way it's done in SimpleSchema. `const MyCustomClass = Class.create()` creates a class and some developers already use it in the `check` package `check(doc, MyCustomClass)` to check if a document is an instance of the `MyCustomClass`. So what I would do to support validation in check would be something like `check(doc, MyCustomClass.getPattern())` or other similar method name (maybe `getCheckPattern()`).

**Comment by THPubs** [comment]
@jagi Perfect thanks! :-)

**Comment by lukejagodzinski** [comment]
Implemented and can be downloaded by cloning the most recent version from GitHub. It will be published with the next minor release. Closing it for now.

**Comment by THPubs** [comment]
@jagi Perfect thanks :-)
