### ISSUE TITLE
Subclass attributes undefined when queried by their parent class

### ISSUE THREAD

**Issue by ghost** [jagi/meteor-astronomy#464]
Hi!

Only since my last update attributes of instances of subclasses are set to `undefined` when they were queried by their parent class. For example like `let child = Parent.findOne({_id: childId})`leads to `child.childAttribute === undefined`, when `childAttribute` is set and defined in the fields of the `Child = Parent.inherit(…` class. Is this intended?

Many thanks, great Work!

**Comment by lukejagodzinski** [comment]
First of all please put a little time to use some formatting when you post some issue. It makes reading code sample much easier. And getting back to your question, you gave so little details that it's impossible to answer your question. Just post class definitions for classes you're talking about and the code that fails. And the best thing would be just creating reproduction repository.

**Comment by ghost** [comment]
Class Defintion:

```
const Parents = new Mongo.Collection("parents");

const Parent = Class.create({
    name: "Parent",
    collection: Parents,
    typeField: 'type',
    fields: {
        name: String
    }
});

const Child = Parent.inherit({
    name: "Child",
    fields: {
        toy: String
    }
});

export default {
    Parent, Child
}
```

Meteor test method:

```
Meteor.methods({
    "test"() {
        const child = new test.Child({name: "Bobby", toy: "Stick"});
        const childId = child.save();
        console.log("Parent query: ", test.Parent.findOne({_id: childId}));
        console.log("Child query: ", test.Child.findOne({_id: childId}));
    },
});
```

Meteor method call in React component:

```
<button onClick={() => Meteor.call("test")}>Test</button>
```

Server-side output:

```
Parent query:  Class {
   _id: 'hmWAe86HkNFGGfKTs',
   type: 'Child',
   name: 'Bobby',
   toy: undefined }
Child query:  Class {
   _id: 'hmWAe86HkNFGGfKTs',
   type: 'Child',
   name: 'Bobby',
   toy: 'Stick' }
```

So it seems that the query defines the format of the object in the new version?
To hold up the object-orientation-analogy I would have expected the "object" to be unmodified by the query.

**Comment by lukejagodzinski** [comment]
Is the document returned by parent query instance of the Child class or Parent?

**Comment by ghost** [comment]
I updated the code in the comment above, since I forgot the type discriminator `typeField: 'type',` in the `Parent` defintion. Now the outputs displays the types. Here the returned ducuments are instances of the `Child` class in both cases.
This is the result of a direct query in the `meteor mongo` cli: 

```
meteor:PRIMARY> db.parents.find({_id: "hmWAe86HkNFGGfKTs"})
{ "_id" : "hmWAe86HkNFGGfKTs", "type" : "Child", "name" : "Bobby", "toy" : "Stick" }
```

**Comment by lukejagodzinski** [comment]
So right now it behave correctly. It always return instances of proper class.

**Comment by ghost** [comment]
Why do you consider this a correct behavior? 
The `type` attributes are returned correctly, but the`toy` attribute of the document returned by the query `test.Parent.findOne({_id: childId})` is set to `toy: undefined` though having the class `type: 'Child'`.

**Comment by joefru** [comment]
I'm experiencing the same behavior as @burggraben 

For inheritance to be useful, this needs to be resolved.

**Comment by lukejagodzinski** [comment]
Please create reproduction repository so it will be easier for me to check this

**Comment by ghost** [comment]
Hi! Repo reproducing the issue:
https://github.com/burggraben/reproduction-repo-jagi-meteor-astronomy-issue-464
Also thanks @joefru for the proposed commits - great!

**Comment by lukejagodzinski** [comment]
Ok fixed with the PR by @joefru. Thanks! I will publish it with the next bugfix version
