### ISSUE TITLE
Broken changelog link in documentation

### ISSUE THREAD

**Issue by louis-cl** [jagi/meteor-astronomy#467]
In the doc http://jagi.github.io/meteor-astronomy/#changelog; the "here" link gives an 404 error.

Going to https://github.com/jagi/meteor-astronomy/blob/master/HISTORY.md but branch master doesn't exist anymore.

It's not difficult to find the history but it would be nice if the link worked.

**Comment by lukejagodzinski** [comment]
Ok I will fix that

**Comment by lukejagodzinski** [comment]
Fixed
