### ISSUE TITLE
Better error message on validation - display class name where the error occured

### ISSUE THREAD

**Issue by rnarayan** [jagi/meteor-astronomy#469]
I am working on a large project that has quite a number of collections. We use the wonderful package astronomy for schema definition. It's an awesome package and thank you for creating it.

Could you put the class name in the error messages when validation fails. For example, here is the error message that I received today  - "url is required" and I had to go through all the schema definitions and several of them use "url" field. It was difficult to find out which exact schema was giving the error.

Error: "url" is required [validation-error]

W20160804-20:42:06.255(-5)? (STDERR)     at new _class (packages/mdg:validation-error/validation-error.js:14:12)

W20160804-20:42:06.255(-5)? (STDERR)     at throwError (packages/jagi:astronomy/lib/modules/validators/validator.js:63:15)

W20160804-20:42:06.255(-5)? (STDERR)     at Validator.validate (packages/jagi:astronomy/lib/modules/validators/validator.js:89:9)

W20160804-20:42:06.256(-5)? (STDERR)     at Object.Validators.(anonymous function) [as required](packages/jagi:astronomy/lib/modules/validators/validator.js:101:17)

W20160804-20:42:06.256(-5)? (STDERR)     at ScalarField.validate (packages/jagi:astronomy/lib/modules/fields/field.js:38:18)

W20160804-20:42:06.257(-5)? (STDERR)     at ScalarField.validate (packages/jagi:astronomy/lib/modules/fields/scalar_field.js:12:5)

W20160804-20:42:06.257(-5)? (STDERR)     at packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:111:13

W20160804-20:42:06.257(-5)? (STDERR)     at catchValidationError (packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:40:7)

W20160804-20:42:06.258(-5)? (STDERR)     at packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:109:5

W20160804-20:42:06.258(-5)? (STDERR)     at arrayEach (/xxx/.meteor/packages/jagi_astronomy/.2.1.1.1ckm8t2++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:484:11)

**Comment by lukejagodzinski** [comment]
Yes I know about this problem. I've experienced similar problem :). And yes I will definitely add class name to the validation error.

**Comment by lukejagodzinski** [comment]
Ok fixed. I will release it in a moment
