### ISSUE TITLE
Doc is not well organized IMO

### ISSUE THREAD

**Issue by steph643** [jagi/meteor-astronomy#47]
A ToC is supposed to describe what's in the document below. Here there are 2 issues:
- There are 2 ToCs! One at the beginning, and one in the "Features" chapter.
- The second ToC points to following chapters ***and*** to external documents.

As a result, I have just spent 15 minutes starring at the doc to find the concept of "validator" (although I used other keywords such as "validate" and "check"). I found nothing and went though the source code, wondering "how is it possible there is nothing to validate a value?!". Then I finally found that there is an external package for this (a package whose name isn't even mentioned in the doc).

I suggest the following:
 1. Merge chapter "Features" with the ToC.
 2. Create a chapter called "External features", containing a list of all external modules, with package name, description and github link.
 3. Remove the wiki pages and turn them into standard package doc.

**Comment by jagi** [comment]
Yes indeed there is a little mess right now. I moved some parts of the documentation to the wiki to avoid to big readme file however it caused some inconsistency. I'm planning to create separate website with info about Astronomy and well organised documentation, something like Meteor doc (in terms of organisation).
