### ISSUE TITLE
Throw error on immutable set/save?

### ISSUE THREAD

**Issue by peterchoo** [jagi/meteor-astronomy#472]
Hi,

I'm looking at using immutable fields in my modelling now, and I was expecting the `save` function to thrown an error when an immutable field has been changed, but Astronomy seems to just ignore setting immutable fields.

Is throwing an error something you would consider implementing, either through an option in the `save`/`validate` methods, as a global setting, or as a default?

Thanks

**Comment by lukejagodzinski** [comment]
It just does not allow changing immutable fields without throwing error. There is no point of having such error being thrown by default. Why do you need it?

**Comment by peterchoo** [comment]
It's behaviour I'm expecting as the user is trying to change a field they shouldn't be changing.  Similarly, I expect an error when a user tries to set a field which doesn't exist, however I only see a warning in the console and no error is thrown.

**Comment by lukejagodzinski** [comment]
If you want such feature you can just detect field being modified in a meteor method and throw error by yourself.

**Comment by peterchoo** [comment]
Alright, thanks, I'll look at it that way.
