### ISSUE TITLE
Use Class Methods inside publications

### ISSUE THREAD

**Issue by axelvaindal** [jagi/meteor-astronomy#473]
Hi,

It seems I have an issue with using Astronomy Class Methods inside publications.
Considering this code, I got the following problem:

```
import { User } from './Users.js';

Meteor.publish('userData', function()
{
    let user = User.find({_id: this.userId}).fetch();

    console.log(user);
    console.log(user.isActive());

    // Actual return of data here, not important for the example
}
```

 Exception from sub userData id 4bo69wdFwpeGTeZM8 TypeError: user.isActive is not a function
I20160810-11:53:34.690(2)?     at Subscription._handler (imports/api/users/publish.js:19:19)
I20160810-11:53:34.691(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160810-11:53:34.691(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160810-11:53:34.692(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160810-11:53:34.692(2)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160810-11:53:34.692(2)?     at packages/ddp-server/livedata_server.js:551:43

Fun facts is that when my use similar code in my hook for user collection (onLogin hooks), methods work fine.

Is there a known bug with using Class Methods inside publications or do I need to do something special to make it work inside publications ?
I haven't found anything inside the docs about this, so I considered it should work either way.

EDIT: It seems displaying the user class inside the publish function also display the methods, so I tend to think something is wrong with my way of doing things, but can't understand what considering the same code is working everywhere else.

Output from `console.log(User)`:

 methods:
I20160810-14:13:22.010(2)?       { softRemove: [Function: softRemove],
I20160810-14:13:22.010(2)?         softRestore: [Function: softRestore],
I20160810-14:13:22.010(2)?         getStatusName: [Function: getStatusName],
I20160810-14:13:22.010(2)?         isOffline: [Function: isOffline],
I20160810-14:13:22.010(2)?         isOnline: [Function: isOnline],
I20160810-14:13:22.011(2)?         isWorking: [Function: isWorking],
I20160810-14:13:22.011(2)?         isBusy: [Function: isBusy],
I20160810-14:13:22.011(2)?         isAway: [Function: isAway],
I20160810-14:13:22.011(2)?         isMale: [Function: isMale],
I20160810-14:13:22.011(2)?         isFemale: [Function: isFemale],
I20160810-14:13:22.011(2)?         isActive: [Function: isActive],
I20160810-14:13:22.011(2)?         isInactive: [Function: isInactive],
I20160810-14:13:22.012(2)?         isAsleep: [Function: isAsleep],
I20160810-14:13:22.012(2)?         isDeactivated: [Function: isDeactivated],
I20160810-14:13:22.012(2)?         isDeleted: [Function: isDeleted],
I20160810-14:13:22.012(2)?         isBanned: [Function: isBanned],
I20160810-14:13:22.012(2)?         getPublishedFields: [Function: getPublishedFields],
I20160810-14:13:22.012(2)?         getFields: [Function: getFields] },

Edit: This was my mistake doing User.find() instead of User.findOne();
I assumed considering there is only one document matching options the User was retrevied directly and not a Collection of User.

I'm closing this as soon as I get a feedback. But maybe it should be considered to get only a single instance when only one result is fetch while using Class.find() ?

**Comment by lukejagodzinski** [comment]
It's correct behavior. It's how Meteor works so it's done the same way in Astronomy.
