### ISSUE TITLE
[v2] .save() function is not working

### ISSUE THREAD

**Issue by aufahr** [jagi/meteor-astronomy#479]
Sorry, i'm quite new with meteor and all.. have tried asking in chat & stackoverflow with no solution. For some reason, i get a "post.save is not a function" on using the .save() function on astronomy v2. i tried to call the .save() on inserting a new doc in the db using a meteor methods call from the client side.

Here's some code : 

```
import { Class } from 'meteor/jagi:astronomy';
import { Mongo } from 'meteor/mongo';

const Posts = new Mongo.Collection("Posts");

const Post = Class.create({
    name: 'Post',
    Collection : 'Posts',
    secured: true,
    fields: {
        title: String,
        published: Boolean,
        /* ... */
    },
    methods: {
        rename(title) {
            // Check if a given user can rename this post.
            if (this.ownerId !== Meteor.userId()) {
                throw new Meteor.Error(403, 'You are not an owner');
            }
            this.title = this;
            this.save();
        },
        publish() {
            // Check if a given user can publish this post.
            if (this.ownerId !== Meteor.userId()) {
                throw new Meteor.Error(403, 'You are not an owner');
            }
            if (this.published) {
                throw new Meteor.Error(403, 'Post is already published');
            }
            this.published = true;
            this.save();
        }
    }
});

Meteor.methods({
    "newPost"(){
        const post = new Post();
        post.title = "test";
        post.save();
    },
    "renamePost"(postId, title) {
        const post = Post.findOne(postId);
        post.rename(title);
    },
    "publishPost"(postId) {
        const post = Post.findOne(postId);
        post.publish();
    }
});`
```

As you can see im using the samples on the astronomy documentation with an additional methods called newPost.

calling on those functions all resulted in an Exception 

> TypeError: post.save is not a function

Have tried the following tries on resolving the error with no success 
- Removing and re adding astronomy
- Rebuild meteor project
- Updating to latest 2.1.2 version
- create method overlay on Post model that called this.save() instead of directly calling .save()

**Comment by jhuenges** [comment]
I am not 100% sure, but could you check this line

```
Collection : 'Posts',
```

? 

I think it should be

```
collection : Posts,
```

**Comment by aufahr** [comment]
oh, i see.. im really sorry for that mistakes.., have changed it to the correct one now.. the problem still happens though.. it keeps having a  TypeError: post.save is not a function exception.

**Comment by aufahr** [comment]
any ideas @jagi ?

**Comment by lukejagodzinski** [comment]
Collection name should be lower case and you should pass collection object not string. If you don't do that the `save` method won't be added to the class. So that's why it was not working.

If it's still not working then I need more details. You have to create reproduction repository where you provide minimal amount of code that is not working. You will probably find error when creating such reproduction.

**Comment by aufahr** [comment]
Hi,  i've noticed my mistakes on passing string in the collection fields...  And have corrected them as of what @jhuenges pointed out..  Afterwards i tried to start out with a clean code repo  and also have changed the name of my mongo collection to lowercase as what you've said..  And it works as it supposed to be now..   Thx againn..  Sorry for bothering you..

**Comment by lukejagodzinski** [comment]
Ok no problem
