### ISSUE TITLE
How to create index for "createdAt" in timestamp behavior

### ISSUE THREAD

**Issue by rnarayan** [jagi/meteor-astronomy#480]
I am sorry if I missed the documentation on it, I couldn't find one. I would like to create an index on "createdAt" field in collections so that I can sort search results based on create time. I am using the timestamp behavior. How do I do that? Thanks in advance for answering.

**Comment by lukejagodzinski** [comment]
http://jagi.github.io/meteor-astronomy/v2#indexes
