### ISSUE TITLE
[Question] Can i use User object replace for Accounts.users ?

### ISSUE THREAD

**Issue by lyquocnam** [jagi/meteor-astronomy#481]
I use many fields with user. so how to combine or replace Accounts.createUser() with User class created by astronomy ?
Meteor standard have Meteor.loginWithPassword, Meteor.loginWithFacebook .... so can i handle this with User class ?

**Comment by lukejagodzinski** [comment]
The `accounts` package operates on plain JS objects so if you want to use Astronomy with it you have to give it back plain object using the `raw` method.

``` js
// Create Astronomy document using raw object.
const user = new User(rawUserObject);
// Get back raw object from Astronomy document.
user.raw();
```

**Comment by lyquocnam** [comment]
yep, so how to validate user when i use `Accounts.createUser` by using User class ?
currently, i validate by hand:

```
if (!user.username)
...
if (user.point === 0)
...
```

and `validate` function in User class is client side right ?
Have any way i use it in server ?

**Comment by lukejagodzinski** [comment]
You don't perform validation in the `Accounts.createUser` method. Instead you should use the `Accounts.onCreateUser` hook.

``` js
Accounts.onCreateUser(function(options, rawUser) {
  const user = new User(rawUser);
  user.validate();
  return user.raw();
});
```

It will be even easier with the new version that is comming

``` js
Accounts.onCreateUser(function(options, user) {
  User.validate(user);
  return user;
});
```

And no, the `validate` function is not only client side. It works in both client and server.

**Comment by lyquocnam** [comment]
thanks @jagi  so much, i think this must be in Document Page :+1:
