### ISSUE TITLE
[Question] How to nest User object like a tree ?

### ISSUE THREAD

**Issue by lyquocnam** [jagi/meteor-astronomy#483]
dear author,  i have user Class:

```
const User = Class.create({
 fields: {
      parent: {
        type: User,
        optional: true,
      },

      children: {
        type: [User],
        optional: true,
      },
    }
}) ;
```

this throw error.
so i try :

```
if (Meteor.isServer) {

  User.extend({
    fields: {
      parent: {
        type: User,
        optional: true,
      },

      children: {
        type: [User],
        optional: true,
      },
    }
  });

}
```

error:
`Exited from signal: SIGSEGV`

**Comment by lukejagodzinski** [comment]
It's rather not possible to nest user objects in Meteor in its Meteor.users collection. More over if these users get stored in the collection then it's not correct MongoDB pattern. Take a look here https://docs.mongodb.com/manual/tutorial/model-tree-structures-with-child-references/ you have to store ids of children. However it's one of possible implementations. There are other possibilities. Which one you choose depends on your needs.

**Comment by lyquocnam** [comment]
thanks @jagi i got it

**Comment by lyquocnam** [comment]
@jagi  i have Class like this:

```
User
{
        .........
        parentId: String,
        children: [String] // [userId1, userId2, userId3, ........]
       ...........
}
```

how can i find user Hierarchy in model function like this:

```
user = .......... // { username: a }
user.findChildrenTree();
```

result:

```
A {username: a, .... }
--B { username: b, age: 22,...}
----C {username: b}
```

and tree 2 (include parent}:
`user.findParentMeChildrenTree();`
result:

```
Parent { username: z }
--A {username: a, ...., current: true }
----B { username: b, age: 22,...}
------C {username: b}
```

it so hard for me, please help.

**Comment by jhuenges** [comment]
What is the purpose of a children tree? The way it looks right now is that you store not only the direct children, but also the grand-children and grand-grand-children etc. From my point of view that doesnt make any sense. It would be more useful if you only store the direct children and than iterate over the children to get the grand-children and so on. Then you could do something like

``` js
// Pseudo-not-complete-code (writing from mobile)
getChildren function() {
   // maybe store the children in an array and push the new ones to it
  _.each(this.children, (child) {
    var user = Users.findOne(child);
    user.getChildren();
   // and a return somewhere
  });
}
```

**Comment by lukejagodzinski** [comment]
@lyquocnam I don't understand your problem because you didn't describe it in enough details. However, I can't help everyone with their problems if it's not related with Astronomy. Sorry but I have a lot of work to do. Maybe someone else will help you.

**Comment by lyquocnam** [comment]
thanks @jhuenges it work !
