### ISSUE TITLE
[Question][v2] How to ignore validate from object ?

### ISSUE THREAD

**Issue by lyquocnam** [jagi/meteor-astronomy#484]
Dear @jagi , i has Class have some validation defined, but sometime i want disable on save like this: 

```
User.save({
  validation: false // i want ignore validate in this time.
});
```

this can be ? have any ideas for this ?

**Comment by lukejagodzinski** [comment]
You can do so but I would not recommend it

``` js
import { ValidationError } from 'meteor/jagi:astronomy';

try {
  user.save();
} catch(err) {
  // You can also check here if it was validation error and ignore it.
  if (!ValidationError.is(err)) {
    throw err;
  }
}
```

**Comment by lukejagodzinski** [comment]
Sorry my bad it will catch validation error but still prevent saving. There is no way of performing save without validation using Astronomy. It's by purpose. You can only disable client validation:

``` js
user.save({
  simulation: false
});
```

If you want to save some data without validation, you have to use pure Meteor for that:

``` js
const modifier = user.getModifier();
Users.update(user._id, modifier);
```

However I would not recommend doing it if you're not 100% sure about security.

**Comment by lyquocnam** [comment]
thanks @jagi so much, i got it !
