### ISSUE TITLE
Private Methods

### ISSUE THREAD

**Issue by axelvaindal** [jagi/meteor-astronomy#485]
Hi,

Is it possible to declare "private" methods with Astronomy ?
Private method should only be called from other Astronomy methods.

I would like to do so in order to separate some internal logic which should not be used outside of the class.

If there is not, is it possible considering adding it ?

I suppose the method should be undefined if called outside of another method, ie not be available like this:

```
var obj = new Class();

class.method(); // Not working (undefined or do nothing)
class.method2(); // This call class.method() internally and is working perfectly
```

I suppose a way of achieving so would be to add some keyword for declaring public or private method, ie:

```
export const MyClass = Class.create(
{
    name: "MyClass",
    collection: MyCollection,
    /* Skipping fields declaration which is irrelevant for now */
    publicMethods:
    {
        // Public methods goes here
    },
    privateMethods:
    {
        // Private methods goes here
    },
    /* Skipping events / behaviors which are irrelevant for now */
}
```

I also thought about nesting the function inside an object in order to set is privacy, name or whatever but I suppose this would be a break-compatibility change and is not my intent.

Please, let me know if there is any workaround about this :).

**Comment by lukejagodzinski** [comment]
There is no such thing like private class method in JavaScript so it's not possible to implement it in Astronomy. There are only some workarounds which make function private in a scope of the file in which given function will be used. But there is not way of doing it in a way how it's done let's say in C++.
