### ISSUE TITLE
Using nested fields with self reference

### ISSUE THREAD

**Issue by saulide** [jagi/meteor-astronomy#486]
What is the best way to use a nested field, that references to same class , e.g.

``` javascript
const Element = Class.create(
    { name : "Element",
        fields: {
            name: String,
            inputs: {
                type: [Element]
            }
        }
    }
)
```

My current approach is

``` javascript
const Element = Class.create(
    { name : "Element",
        fields: {
            name: String,
        }
    }
);
Element.extend({
    inputs: {
        type: [Element]
    }});
export default Element;
```

**Comment by lukejagodzinski** [comment]
First of all use correct code styling because right now it's hard to read.

If it goes about your question. It's not correct way of storing nested documents. If `Element`s are stored in collection then you would store ids of nested documents which does not make sense. If the `Element` class is not intended to be stored directly then it's still not good design pattern even if MongoDB allows that. However it depends on use case. Sometimes it's just unavoidable.

**Comment by saulide** [comment]
Thanks jagi for the quick reply.

Now I understood what's meant with the nested fields. I was unaware of the whole ORM mapping features, and I thought that a feature like Reference Field in different ORM frameworks was implemented by astronomy. So knowing the current state of astronomy, how should I define such field? As a `[String]`?

**Comment by lyquocnam** [comment]
i think this could help @saulide  https://docs.mongodb.com/manual/applications/data-models-tree-structures/

**Comment by lukejagodzinski** [comment]
@saulide yes take a look at the link that @lyquocnam posted

**Comment by saulide** [comment]
Thanks for the comments!

I wonder if a feature using reference fields (similar to http://docs.mongoengine.org/guide/defining-documents.html#one-to-many-with-listfields) is planned in next iteration of astronomy? As I see, currently I need to check manually own defined rules in case e.g. deletion and do appropriate action ( cascade, null data, etc.)

**Comment by lukejagodzinski** [comment]
Right now I'm not going to introduce such a feature because Astronomy will probably change a lot in the future. I'm rather more focuses on small improvements and bug fixes right now.

**Comment by lyquocnam** [comment]
@saulide @jagi that is nice feature. i think so too :dancers:

**Comment by lukejagodzinski** [comment]
Yes but it's also not so easy to implement. So probably it will not appear in Astronomy any time soon. Astronomy will also probably evolve from ORM to GraphQL+Relay wrapper.

**Comment by laurentpayot** [comment]
@jagi OMG does "GraphQL+Relay wrapper" means use of Apollo or are you working on something else ?

**Comment by lukejagodzinski** [comment]
@laurentpayot rather not Apollo as it uses Redux but we will see. Right now I'm learning Relay which is quite complex to learn and use. And I'm thinking about simplifying this process. The naming convention is also weird. From experience I know that every tool can be done simpler and API can be much easier to learn and use. But at the current stage it's hard to tell if there is a point of creating such a wrapper. Definitely I would also like to use such a tool with Meteor. We will see.
