### ISSUE TITLE
Documentation on Security [2.1.2]

### ISSUE THREAD

**Issue by Andrew1431** [jagi/meteor-astronomy#487]
Your documentation on security states that `secured: false` is enabled by default. This is not true, and also enabling secured: false on your models does not remove the security.

I had to enter

``` javascript
secured: {
  insert: false,
  update: false,
  remove: false
},
```

Just an FYI and perhaps a fix to the documentation. This is version 2.1.2.

**Comment by lukejagodzinski** [comment]
Classes are secured by default so `secured: true`. I have to fix docs. Using phrase `enabling secured: false` is not correct. You should say `Setting secured option to false` or `Disabling secured option`. So it's easier what you mean. And it works, so you're probably doing something wrong.

**Comment by Andrew1431** [comment]
``` javascript
secured: {
  insert: false,
  update: false,
  remove: false
}
```

on version 2.1.2 got rid of the `Can not insert from the client` error, whereas

``` javascript
secured: false
```

did not get rid of the error. I don't think I was doing anything wrong, but the 3 property secured false works, so thats what i've done in the app :P

**Comment by lukejagodzinski** [comment]
I will take a look at it in free time

**Comment by thomas-p-wilson** [comment]
Noticed the same as @Andrew1431

**Comment by daande** [comment]
@Andrew1431 if that is the case create a PR with an updated https://github.com/jagi/meteor-astronomy/blob/v2/README.md file.

**Comment by lukejagodzinski** [comment]
@daande I've already updated docs
