### ISSUE TITLE
this.userId is undefined in events

### ISSUE THREAD

**Issue by phortx** [jagi/meteor-astronomy#488]
Is there a way to get the `userId` within an astronomy event? Neither `Meteor.userId()` nor `this.userId` works.

I'm thankful for any hint :)

**Comment by laurentpayot** [comment]
`Meteor.userId()` is working fine for me in the `beforeInsert` event. Did you install the `accounts-base` package ?

**Comment by phortx** [comment]
Thanks for your reply!

Yes I'm sure. In a publication or on the client it works like a charm.

However within the event handler `Meteor.userId()` throws `Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.`. And `this.userId` is `undefined`.

Actually I have a behavior wich registers a `beforeFind` event.

**Comment by lukejagodzinski** [comment]
You could probably use `bindEnvironment` method for that:

``` js
events: {
  beforeFind: Meteor.bindEnvironment(function() {
    return Meteor.userId();
  })
}
```

If the `Meteor.userId()` method will work depends on in what context you're using it

**Comment by phortx** [comment]
Doesn't work neither :(

The stack trace is basically: `subscription -> publication -> model method -> find -> beforeFind`

The model method is actually not a method from the astronomy `methods` hash rather then a plain old public instance method on the model class.

**Comment by lukejagodzinski** [comment]
You have to show code

**Comment by phortx** [comment]
I've tried to reduce the code to everything necessary:

https://gist.github.com/phortx/907500fb1b516ee9c5ffde820437c930

**Comment by lukejagodzinski** [comment]
First of all you can'y use `this.userId` in the beforeFind event because the `this` context is not meteor method or publish function.
The second thing is that you're doing a lot of custom stuff and moreover you're using TS which I don't like to read.
The best way of finding a problem would be creating reproduction repository where you have a class with the `beforeFind` event and you get user id using `Meteor.userId()`. It will definitely work. And later you can build all the stuff you have in your current code base. At some point you will notice error.

The same issue already happened to many developers and it was always bug in a code. You make search for closed issues about userId.

**Comment by phortx** [comment]
I don't want to start a discussion about code quality, typescript or meteor here.

However I'll do further research like you suggested. Thank you for your advice.

**Comment by phortx** [comment]
Seems like this is not a astronomy issue at all.

I've created a plain new meteor app, added the `accounts-password` package and wrote this code:

``` javascript
Meteor.methods({
    'testMethod': function() {
        console.log('test2:', this.userId); // => null
        console.log('test3:', Meteor.userId()); // => null
    }
});

if (Meteor.isServer) {
    Meteor.publish('testPublication', function() {
        console.log('test1:', this.userId); // => the userid
        Meteor.call('testMethod');
    });
}

if (Meteor.isClient) {
    Meteor.loginWithPassword('test', 'test', function() {
        Meteor.subscribe('testPublication');
    });
}
```

The outputs are annotated in the comments. Seems like this is a meteor issue. I've created a stackoverflow question for that: http://stackoverflow.com/questions/39200445/meteor-this-userid-and-meteor-userid-both-are-null-within-a-meteor-method

Also if I add `astronomy`, a model and a `beforeFind` event, I can reproduce the original issue:

``` javascript
import { Class } from 'meteor/jagi:astronomy';

const Appointments = new Mongo.Collection('appointments');
const Appointment = Class.create({
    name: 'Appointment',
    collection: Appointments,
    fields: {
        companyId: String
    },
    events: {
        beforeFind: function(e) {
            console.log('test2:', this.userId); // => undefined
            console.log('test3:', Meteor.userId()); // => Error: Use this.userId instead 
        }
    }
});

if (Meteor.isServer) {
    Meteor.publish('testPublication', function() {
        console.log('test1:', this.userId); // => the userid
        return Appointment.find({}, {limit: 10});
    });
}

if (Meteor.isClient) {
    Meteor.loginWithPassword('test', 'test', function() {
        Meteor.subscribe('testPublication');
    });
}
```

**Comment by phortx** [comment]
I reopen this due the fact that even without typescript, any custom stuff etc. It's easy to reproduce the error.

**Comment by lukejagodzinski** [comment]
But it's not related with Astronomy

**Comment by phortx** [comment]
Isn't it? In the documentation you have a code sample which says, the user id is available in events, but it actually isn't available. So it's a bug or the documentation is wrong. Isn't it?

(http://jagi.github.io/meteor-astronomy/v2#secured-property see INSERT example)

**Comment by lukejagodzinski** [comment]
It's working. You can check it by your self https://github.com/jagi/userid-example. Just create an account and add new post using the `Add post` button
So it's a bug in your code

**Comment by phortx** [comment]
You're right, your example is working like a charm, even if I change the event type to `beforeFind`.

However the code differs from my example due the fact that it's not called from a publication.

If I remove the `autopublish` package and add a publication and subscription like above, the userId is null again.

See my fork: https://github.com/phortx/userid-example

**Comment by lukejagodzinski** [comment]
You can't use `Meteor.userId()` in publish function so if you do `Class.find()` in the publish function it will throw error. It's also not possible to use `this.userId` as the `beforeFind` event context is not publication function. You can't also invoke meteor methods inside publish functions that call `Meteor.userId()`

**Comment by lukejagodzinski** [comment]
In fact it's strange that you want to access `userId` in the `beforeFind` event. In a minute I will post example of how to do some operations using `userId` but without the `beforeFind` event.

**Comment by phortx** [comment]
Yeah well thats a design flaw of Meteor in my opinion :)

Thank you very much for your help!

**Comment by phortx** [comment]
> In fact it's strange that you want to access userId in the beforeFind event.

Let me explain this. We have a system with lots of entities. All these entities are related to a company. Also the user belongs to a company. The user obviously should have access only to the data of its company. Therefore all publications have to be filtered by companyId (which comes from the user).

To redude that to a single point of failure, I want to implement a beforeFilter with a single implementation. This filter adds the companyId to the selector, so the developer can't forget the companyId in the publication and produce a data leak.

**Comment by lukejagodzinski** [comment]
Then what you described it's not possible to do in Astronomy. You can access `this.userId` only in publication. You would have to have a way of passing `this.userId` to the `beforeFind` event but anyway you would have to do it manually. I'm not detecting invocation context in the events.

``` js
Meteor.publish('companies', function() {
  // If you want to limit results to some userId
  const userId = this.userId;
  return Company.find({
    userId: userId
  });
});
```

**Comment by phortx** [comment]
Too bad :(

However maybe you can add this to your feature requests list or something.

Thank you for your time and your help!

**Comment by lukejagodzinski** [comment]
Theoretically it would be possible but it would be ugly API which I don't want to produce. From what I know it's not possible to detect publish function invocation context. You can only detect if you're in a method call.

``` js
Meteor.publish('publicationName', function() {
  (function() {})(
    // There is no way of detecting if I'm in a publish function here
  );
});
```

The only way of doing this would be (as I said) passing userId somehow:

``` js
Meteor.publish('publicationName', function() {
  Post.find(selector, {userId: this.userId});
});
```

So it's not perfect as you still have to remember to pass `userId`.

**Comment by phortx** [comment]
Yes, you're right. I'm trying to find another solution, maybe I'll try to overload `find()` or write some kind of PublicationManager which does the work for me, or or or ... :)

**Comment by lukejagodzinski** [comment]
It's a very common patter to write publication manager but you would still have to pass userId to such manager.

**Comment by phortx** [comment]
That's ok, I think ... some kind of:

``` javascript
class PublicationManager {
    publish(name, model, callback) {
        Meteor.publish(name, () => {
            let publishData = callback();
            publishData.selector['companyId'] = Meteor.user().profile.companyId;
            return model.find(publishData.selector, publishData.options);
        });
    }
}


let publicationManager = new PublicationManager()
publicationManager.publish('posts', Post, () => {
    return {
        selector: {},
        options: { limit: 10 }
    }
});
```

**Comment by fabiodr** [comment]
With this package [meteor-user-extra](https://github.com/peerlibrary/meteor-user-extra), you can use Meteor.userId() the same way, in client and server, anywhere. It's code is simple and i've been using it for months with no problem. Hope it helps.

**Comment by phortx** [comment]
@fabiodr this is simply awesome! You sir, just saved my day :)

**Comment by lukejagodzinski** [comment]
Hmm interesting solution however I'm curious if it will work in all scenarios. This comment https://github.com/meteor/meteor/blob/d7c509b5fb8d6987f084bf6df96b9886d68f2393/packages/accounts-base/accounts_server.js#L71 in meteor code says that there are some limitations if it goes about reactivity.

**Comment by fabiodr** [comment]
Interesting, i haven't tested this case, but publications aren't reactive anyway. Maybe a solution for ensure a publication that uses Meteor.userId() in server reacts to a login, logout and user change is, from client, wrap subscriptions including a call to Meteor.userId() (that is reactive in client) in Tracker.autorun. This way, when the user changes, the old subscription stops and a new with the right user is subscribed.

**Comment by lukejagodzinski** [comment]
@fabiodr yes that's probably a solution. Anyway it's a nice package that solves the problem that was asked many time. I think I will info about it to the docs
