### ISSUE TITLE
reload() method causes recognition as "new" in astronomy 0.12.0

### ISSUE THREAD

**Issue by jbbr** [jagi/meteor-astronomy#49]
In my code I use the "reload" prototype method in some cases.

In Version 0.11.0 I was able to save a already persisted document after a reload. In 0.12.0 its recognized as new after reloading and saving it causes a duplicate key exception.

```js
var post = Posts.findOne();
post.save(); // No error here
post.reload();
post.save(); // Exception while invoking method 'Post.save'
             // MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index
```

After reload new property ".isNew" becomes true

**Comment by jagi** [comment]
Oh sorry I don't have tests for the `reload` function yet and I didn't notice that latest fix can cause this problem. I make quick fix.

**Comment by jbbr** [comment]
No problem. Thanks for this great package. 
I really like your clean code with tests for most cases.

**Comment by jagi** [comment]
I've published the fix. Now it should work.
