### ISSUE TITLE
Different behaviour with Astronomy's findOne-functions

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#491]
I noticed different behaviour when using Astronomy's own findOne-function compared to the Mongo Collection's findOne.

If the function argument is null, Meteor's version does not return anything. Astronomy just finds one document and returns that.

```
Documents = new Mongo.Collection('documents');
Document = Class.create({ .....

// insert some documents to collection...

// Let's see what we can find with findOne(null)
Documents.findOne(null); // Nothing
Document.findOne(null); // Found a document
```

Reproduction here: https://github.com/arggh/astronomy-find-issue

**Comment by lukejagodzinski** [comment]
It's known behavior and I would rather say that it's bug on Meteor's side. I don't know why they decided to treat `null` value that way. When you execute Mongo `findOne` method directly with the `null` value it will return the first document.

```
db.users.findOne(null); // document
db.users.findOne(); // document
```

Meteor treats `null` differently which in some cases may be understandable when you think about security but developer should be responsible for security.

**Comment by lukejagodzinski** [comment]
Ok I've made it consistent with what Meteor does. However I still don't like it but I agree that it should be consistent. But MDG wasn't consistent with MongoDB at first place. You can clone most recent version from the GitHub repository.
