### ISSUE TITLE
Custom setter/getter for field value

### ISSUE THREAD

**Issue by Deadly0** [jagi/meteor-astronomy#492]
It's will be nice if astronomy had possobility to set custom setter/getter for fields.

**Example:**

```
const Product = Class.create({
  name: 'Product ',
  collection: Products,
  fields: {
    title: {
      type: String
    },
    price: {
      type: Number,
      setter: function(val) {
         return Math.round(parseFloat(val)*1000);
      },
      getter: function(val) {
         return (val/1000).toFixed(2);
      },
    }
  }
});
```

**Usecase:**
MongoDB does not support Decimal data type now. To store price in mongoDB it's recommended to convert it to integer. https://docs.mongodb.com/manual/tutorial/model-monetary-data/#exact-precision

P.S. any workaround will be very helpful.

**Comment by axelvaindal** [comment]
Hello @Deadly0,

Why don't you define methods inside your class to achieve this behavior ?

If you want specific save behavior, you can use the beforeSave event in order to modify your variable before it's inserted inside MongoDB.

**Comment by samicemalone** [comment]
I'm currently trying to implement this. I'm storing a currency code and the scaled up number:

``` js
export const Money = Class.create({
  name: 'Money',
  fields: {
    value: {type: Number},
    code: {type: String, default: 'GBP'}
  },
  methods: {
    toString: function () {
      return (this.value / 1000).toFixed(2);
    }
  }
});
```

You could then use this as the type for multiple fields

**Comment by lukejagodzinski** [comment]
I won't implement setters as its functionality is very limited in JS. You can't create setter for a field with the same name, so I would have to go back to how it worked in v1.0 where I was storing values in the private `_values` object which didn't play nicely with Meteor. You have to use methods for what you want to achieve.

**Comment by Deadly0** [comment]
@axelvaindal, thank you, i use the same approach already

@samicemalone thank you, it's a good idea to create custom type.

@jagi, ok, if it's hard to implement i will close the issue, thx.
