### ISSUE TITLE
Server side beforeInsert generated fields, not available in model.save() callback

### ISSUE THREAD

**Issue by smysnk** [jagi/meteor-astronomy#493]
Universal:

```
const Users = new Mongo.Collection('users');
User = Astro.Class.create({
  name: 'User',
  collection: Users,
  fields: {
    generated: String
  },
  events: {
    beforeInsert(e) {
      e.currentTarget.set('generated', '123');
    }
  }
});
```

Client side:

```
    var user = new User();
    user.save(() => {
      console.log(user);
    });
```

Output:
<img width="481" alt="screen shot 2016-08-31 at 3 14 58 pm" src="https://cloud.githubusercontent.com/assets/1548173/18146581/c246cc40-6f8d-11e6-9133-d3f93e7732c1.png">

Expected generated field to be available on the client side in the .save(()=> {}) callback.

**Comment by lukejagodzinski** [comment]
It's not updating the original user object as all operations are invoked on an document copy in meteor method. For what you want to do there is the `reload()` method.

``` js
var user = new User();
user.save(() => {
  user.reload();
  console.log(user);
});
```

**Comment by daande** [comment]
@jagi is it possible to update Astronomy to auto-reload the object on the client side as your answer above just seems like a workaround; not a solution. Also, the documentation surrounding this is unclear as per the docs:

> The save() method takes a callback function as the last argument. The callback function will be called when document storage is finished or on when any error occurred on the client or server. The first argument of the callback function is error object and the second one is response from the server. On insert the response is ID of the inserted document, and on update it’s number of modified documents.
> `
> var user = new User();
> user.save(function(err, id) {
> });
> `

**Comment by smysnk** [comment]
No @daande, someone needs to write special framework on top of astronomy to auto-reload objects on the client side.  Having boiler plate code just to get what was persisted to the database in the save() callback is totally reasonable.

**Comment by lukejagodzinski** [comment]
@daande I'm not gonna change this behavior as in most cases you don't need to do anything with data that you saved. It's unnecessary operation that would be called on every save. When you would be updating tens of thousands of documents it would call reload each time and slow down application. If you want to do something in a callback function then you can just `reload()`. Depending on the case you may also subscribe to changes to that object.
