### ISSUE TITLE
Default values and optional flag

### ISSUE THREAD

**Issue by jhuenges** [jagi/meteor-astronomy#494]
I have two classes

``` js
export default Class.create({
  name: 'Person',
  collection: Persons,
  secured: false,
  fields: {
    ...
   deathdate: {
      type: CustomDate,
      optional: true,
      default() {
        return new CustomDate();
      }
    },
    ...
  }
```

and 

``` js
export default Class.create({
  name: 'CustomDate',
  fields: {
    year: {
      type: Number,
      optional: false,
      validators: [{
        type: 'and',
        param: [{
          type: 'gt',
          param: 1000
        }, {
          type: 'lt',
          param: 9999
        }]
      }]
    },
    month: {
      type: Number,
      optional: true,
      validators: [{
        type: 'and',
        param: [{
          type: 'gt',
          param: 0
        }, {
          type: 'lt',
          param: 13
        }]
      }]
    },
    day: {
      type: Number,
      optional: true,
      validators: [{
        type: 'and',
        param: [{
          type: 'gt',
          param: 0
        }, {
          type: 'lt',
          param: 32
        }]
      }]
    }
  }
});
```

When I create a new person, the person is not necessarily dead (who could have guessed that! :D). Thats why `deathdate` is an optional field. But when I try to validate the object, it throws an error because in `CustomDate` the `year` is not optional. Shouldnt the field `deathdate` be optional and therefore not throw the error if it is not used?

**Comment by lukejagodzinski** [comment]
It's correct behavior. Field is considered to be optional if it's `null` or `undefined`. And in your case it's set to an instance of the `CustomDate`. It's strange that you use some custom class to store date. I think better choice is `Date` type. You probably try to over-engineer your app :). Most things can be made using simple patterns.

**Comment by jhuenges** [comment]
I have to do something like this because I dont store actual dates. In some cases I only want to store a year, sometimes month + year and in rare cases the full date.

**Comment by lukejagodzinski** [comment]
So just don't provide default value for the `deathdate` field, it's not necessary. Or if you need to have year because it's required then you should provide year for every `CustomDate` document. It's just design problem, not framework problem.
