### ISSUE TITLE
Add options to Event

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#499]
Currently if you do a `Class.remove({_id: 'asdasd'}, {awesome: true})` You can't access the options in the second parameter in any of the Events, like `afterRemove` or `BeforeRemove`. I have a couple of use cases which can use options from the remove call, but right now there is no way to access them, can we perhaps introduce a `e.currentTarget.options` or something similar for this?

Thoughts, @jagi ?

**Comment by lukejagodzinski** [comment]
It would be hard to implement considering how events are triggered right now. And you're only talking about `Class.remove()` situation if that would have to work it should also be possible in `doc.remove()` which also triggers the `beforeRemove` event.

Give me good use case where it can't be done easily with other solution, then I can consider introducing such a feature.

**Comment by talha-asad** [comment]
`Class.remove` and `doc.remove`, should work the same way for events. My use case is deletion of remote objects at a third party service. We already clean up stuff in afterRemove, and wanted to clean up on the third party service as well, however wanted to control this through an option.

Our current approach is to call a method which triggers remove and then performs cleanup on the third party service, earlier we could call `.remove` from the client directly and it worked.

**Comment by lukejagodzinski** [comment]
Provide some example code.

**Comment by talha-asad** [comment]
I cannot provide code, as my contract negates that. However i will try to explain the problem.

We allow people to create campaigns in our system, which is then mirrored onto different ad networks, A user can delete a campaign on our system and choose to keep the other one.
From a UX perspective, when a user deletes a Campaign in our system, we give him the option to choose to delete the campaign on Facebook as well. The way it is setup currently is that we simply call `doc.remove()` after the user confirms the deletion, however if he chooses to delete the campaign on Facebook as well, then we have no way to pass this bit to the Astro event(afterRemove) which is responsible for cleaning up the campaign on Facebook.

I was thinking if the Event class had a `.options` or something of that sort, we could easily do a `doc.remove(null, {remoteDelete: true})` and have a condition in the event to act accordingly.

Looking at the code, I think, event dispatching and the Event class will need a bit of modification. What do you think? A valid use case or an edge case?

**Comment by lukejagodzinski** [comment]
For that purpose you should use Meteor methods. In the next release I will introduce meteor methods wrapper for Astronomy, so it will be easier to create meteor method right in a class definition. Events are not supposed to serve as place for application logic. It's just an event that should do some stuff with a document. Do not confuse events with hooks.
