### ISSUE TITLE
Update an object without fetching it first?

### ISSUE THREAD

**Issue by steph643** [jagi/meteor-astronomy#50]
Consider the following code:

```javascript
Meteor.methods({
  setPostTitle: function(postId, title) {
    Posts.update(postId, { title: title });
  }
});
```

It this the Astronomy equivalent?:

```javascript
Meteor.methods({
  setPostTitle: function(postId, title) {
    var post = Posts.findOne(postId);
    post.set('title', title);
    post.save();
  }
});
```

Any way to avoid the extra database read? (findOne)

**Comment by jagi** [comment]
In this [example](https://github.com/jagi/meteor-astronomy-examples/blob/master/methods.js) I'm passing entire document from the client to the server over DDP so there is no need to fetch an object on the server. In most cases when you work with some document on the client, you already had to fetch it on the server and publish to the client. So, on the client you have this document. Now you can just send it back to the server.

However, maybe it's a good reason to introduce the collection level validation.

You could also do it the another way.

```js
Meteor.methods({
  setPostTitle: function(postId, title) {
    var post = new Post({
      _id: postId,
      title: title
    });
    if (post.validate('title')) {
      post.save();
    } else {
      post.throwValidationException();
    }
  }
});
```

**Comment by steph643** [comment]
This makes perfect sense, thanks a lot.
