### ISSUE TITLE
App 10113 stderr: Trying to set a value of the field that does not exist in the class

### ISSUE THREAD

**Issue by ayalpani** [jagi/meteor-astronomy#501]
Hi,

after changing some field names in the code (no changes to the mongo were made), I am seeing these kinds of errors:

`App 10113 stderr: ["AstroItem" class]["integrationType" field] Trying to set a value of the field that does not exist in the class
`

There is no mention of "integrationType" in the code at all, anymore. I have unset all the fields that are not referenced in code, with mongodb $unset. Still, these messages are pouring in. 

How can I solve this? Thanks!

**Comment by lukejagodzinski** [comment]
In your database this field probably still exist. Go to the `meteor mongo` and make sure that all occurrences of this field are unset.

**Comment by ayalpani** [comment]
You are right. My unset statement was incomplete before, I forgot to use "multi" option like so:

`> db.items.update({},{$unset:{integrationType:""},},{multi:true})`

**Comment by lukejagodzinski** [comment]
Yep, that's common mistake :). Closing this issue.
