### ISSUE TITLE
Question: How to save a nested document?

### ISSUE THREAD

**Issue by Faberle** [jagi/meteor-astronomy#503]
``` javascript

const collection= new Mongo.Collection('collection');

const SubClass = Class.create({
    name: 'SubClass',
    fields: {
        text: String  
    },
})

const SuperClass = Class.create({
    name: 'SuperClass',
    collection: collection,
    fields: {
        subClass: {
            type: [SubClass ]
        },      
    },
})

```

Let's say in Meteor I have a Template that has SubClass as a data context. Now I change the text of the SubClass in the Template and I want to save that change. 

Is there another way except to give the template a reference to the SuperClass in order to save the changes made to the SubClass to the database? ala: SubClass.save()

_I hope this is understandable_

**Comment by lukejagodzinski** [comment]
No there is not way of saving a change from the child. You need access to parent.
