### ISSUE TITLE
Question: Why is propagates false for AfterInit Events?

### ISSUE THREAD

**Issue by Faberle** [jagi/meteor-astronomy#504]
I'm currently trying to add transient references to the root document of a subdocument and I fail because the afterInit event is fired on every nested document with  e.target being the nested document instead of the root document.

**Comment by lukejagodzinski** [comment]
Without code I can't tell anything

**Comment by Faberle** [comment]
https://github.com/jagi/meteor-astronomy/blob/v2/lib/core/class.js#L96 here the event is created and dispatched.
It is then not propagated due to the default value of propagates (https://github.com/jagi/meteor-astronomy/blob/1823acb76800919699c9afe92743819e86e1cf80/lib/modules/events/class_prototype_methods/dispatch_event.js#L49) 

Definition Event: https://github.com/jagi/meteor-astronomy/blob/1823acb76800919699c9afe92743819e86e1cf80/lib/modules/events/event.js)

**Comment by lukejagodzinski** [comment]
Init events are not propagated by purpose. I don't remember why I did it but it was necessary to make everything work. So closing it now as I'm not gonna change this behavior because it would break apps using Astronomy.
