### ISSUE TITLE
BeforeSave/BeforeUpdate not working on nested Classes

### ISSUE THREAD

**Issue by Faberle** [jagi/meteor-astronomy#505]
I ran into the issue of events not firing in nested classes. At the time when the before events are called the nested classes aren't casted yet and therefore are not executed. 

Due to this line: https://github.com/jagi/meteor-astronomy/blob/1823acb76800919699c9afe92743819e86e1cf80/lib/modules/events/class_prototype_methods/dispatch_event.js#L56

Here we call the events:
https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/storage/utils/document_update.js#L50

Before the casting of nested classes happens right after: https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/storage/utils/document_update.js#L54

The same is true for insert as well

**Comment by lukejagodzinski** [comment]
Hmm yes in some cases it may be a problem. It should call `castNested` before and after triggering events. I will make a fix.

**Comment by Faberle** [comment]
Please add the fix for insert too (https://github.com/jagi/meteor-astronomy/blob/1823acb76800919699c9afe92743819e86e1cf80/lib/modules/storage/utils/document_insert.js#L43)

Thank you!

**Comment by lukejagodzinski** [comment]
Ok updated. I will release bug fix version.
