### ISSUE TITLE
Temporary object isn't destroyed?

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#506]
Hey,
I'm creating a temporary Astronomy object in one of my Meteor methods (Playlist is the Astronomy class). 

```
'myMethod':function() {


var playlist = new Playlist();
    titles.forEach((doc) => {
        playlist.videos.push(PlaylistHelper.format(doc));
    });

    return playlist;

}
```

Now everytime I call <code>myMethod</code> I see all pushed video objects of the previous method calls, but the object isn't saved in the database (because I didn't call .save()). The expected behavior would be a new and empty object. What's going on here? Seems like Astronomy is saving the object globally and reusing it on every call.

**Comment by dnish** [comment]
Okay, now I'm confused. If I set a name, the property isn't saved on each call:

```
var playlist = new Playlist();
 console.log(playlist);
  playlist.name = "Hello";
   titles.forEach((doc) => {
       playlist.videos.push(PlaylistHelper.format(doc));
   });


return playlist;
```

...but the videos of the other calls are still there

**Comment by lukejagodzinski** [comment]
You've probably defined a default value of the `titles` field in the following way:

``` js
fields: {
  titles: {
    type: [String],
    default: []
  }
}
```

Which is wrong. It should be:

``` js
fields: {
  titles: {
    type: [String],
    default() {
      return [];
    }
  }
}
```

**Comment by dnish** [comment]
Found the problem, I didn't use a function for my default value:

    videos: {
            type: Object,
            default: []
        },

**Comment by dnish** [comment]
Yep, just found it a minute ago 😁, that was the problem.
