### ISSUE TITLE
Class.findOne in React:  Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by Tbutnyakov** [jagi/meteor-astronomy#507]
Hello, Jagi! 
How are you?)

I got a strange error with Class.findOne in React.Component. Its looks like my class dont know nothing about findOne method, or work incorrect. Meanwhile find-method work good. 
Take a look at the example. This is part of code in Container, but in Component section it will not working too.

```
export default createContainer(()=>{
  var userId = Meteor.userId();
  if(userId){
      var userWithFind = User.find({_id:userId}).fetch();
      console.log(userWithFind);
      var userWithFindOne = User.findOne(userId).fetch(); //This string will resolve a error. 
      console.log(userWithFindOne);
  }
  return {
    user:userWithFind
  }
}, Header)
```

And i got:

> Header.jsx:59 Uncaught TypeError: Cannot read property 'fetch' of undefined

What can it be? 
Thank you for brilliant package!

**Comment by lukejagodzinski** [comment]
When you call `findOne()` you don't have to call `fetch()`. The `findOne()` method returns single document and the `find()` method returns cursor on which you have to call `fetch()` to retrieve actual records.

**Comment by Tbutnyakov** [comment]
XD
My bad)
Sorry)

**Comment by lukejagodzinski** [comment]
No problem :)
