### ISSUE TITLE
validate is not a function

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#511]
I have a document initiated as follows:

```
var doc = new SomeModel();
doc = someData[0]; // Populates with array object
```

But when running the validate function:

```
if (doc.validate({ fields: ["blocks"] })) {         
    ...
}
```

I'm getting this in the browser console:

```
Error: doc.validate is not a function
TypeError: doc.validate is not a function
```

I am upgrading from version 1 to 2.1.4, so just wondering if I am missing something obvious (?)

**Comment by lukejagodzinski** [comment]
The problem is this line:

``` js
doc = someData[0]; // Populates with array object
```

You're overriding document, so it's not Astronomy doc anymore.

**Comment by joetidee** [comment]
This used to work in v 1 of Astronomy - has this significantly changed somewhat? How, in v2 am I suppoed to populate a document - I can't use the find() / fetch() methods as the contents of the document are poassed down from a higher level React component ?

**Comment by lukejagodzinski** [comment]
If it's in the way it is in the example then it's not possible that it worked. You populate document using the `doc.set(data)` method.
