### ISSUE TITLE
Weird Validation error

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#515]
So I have a document Class `Unit`, with field `review` of type `UnitReview` (a class defined in the "unit" definition file, and not exported). The following code fails on the client but works on the server,

```
let u = Unit.findOne();
u.validate();
```

The client give the error as "review has to be UnitReview". At this moment, `u.review.validate()` passes. `u.save()` also works. So basically, if I ignore this error, the entire actual code works properly :/.

@jagi  Do you have any idea why such a thing may happen? Are there any special check being done in client astronomy code? How can I debug this further?

If you need more code, do tell. I will create a repo with that same document structure and similar values.

**Comment by lukejagodzinski** [comment]
Is it the validation error or some other error? More code would help.

**Comment by s7dhansh** [comment]
Validation error. Ok, will try to prep a repo, but it may take some time.

**Comment by lukejagodzinski** [comment]
Oh I just noticed that you wrote: 'definition file, and not exported'. I think it's a reason for having this error. Astronomy can't create instance of the `UnitReview` class. You have to export and import all classes that are used, even if they are used internally. I don't know if I can solve it in Astronomy or it's how importing works in Meteor. Try it and let me know.

**Comment by s7dhansh** [comment]
It was a bug in my code. There was UnitReview declaration in 2 different files, and one of the methods file was importing both those files. It caused some definition conflict.

**Comment by s7dhansh** [comment]
And, by the way, we do not need to export the internal nested Classes, unless we need them explicitly. I use lots of such sub-classes in the definition files, and use normal objects while assigning (thanks to v2 :)). During validation, it works perfectly.
