### ISSUE TITLE
Question: How to use Astronomy for migrations and seeding?

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#517]
I am using Astronomy v2 and it's working nicely. Is there a way that you know of to utlize the schema definitions when generating migrations or seeding the database?

**Comment by lukejagodzinski** [comment]
There is no built in migration feature into Astronomy. Ask about specific case then I will be able to help. Your question is too generic.

**Comment by joetidee** [comment]
Just saying that Meteor does not have any native model support and you solved that by creating Astronomy. But what would be really useful is to re-purpose the schema when creating migrations and seeding the database. Might be a natural extension to Astronomy's core functionality.

**Comment by lukejagodzinski** [comment]
There was an idea to add migration feature to Astronomy but it's not must have. There are many packages for migration in Meteor and you can probably use Meteor with them.
