### ISSUE TITLE
Getting return value back to Meteor method to return...

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#520]
I have the following Metero method which runs the validate and save functions from Astronomy:

```
Meteor.methods({

    'do_something': function(id) {

        at.validate(function(err) {
            if (err && err.error === 'validation-error') {
                return err;
            }
            else {
                at.save({fields: fields}, function (err, id) {
                    if (err) {
                        return err;
                    }
                    else {
                        return true;
                    }
                });
            }
        });
    }
});
```

How do I get the return results from the `validate` and `save` functions back out to the parent Meteor method, to then return that value back to the client?

**Comment by lukejagodzinski** [comment]
Please read documentation before asking. You don't have to call the `validate` method if you're already calling the `save` method.

``` js
Meteor.methods({
  do_something(id) {
    return at.save({
      fields: fields
    });
  }
});
```

**Comment by joetidee** [comment]
Just to confirm then, how do I get the `return err;` or `return true;` values back from the `save()` function, is it simply to place `return` in front of the `at.save()` function?

**Comment by lukejagodzinski** [comment]
`doc.save()` throw validation error if any, otherwise it returns number of records that were modified or inserted document id.
You can also do.

``` js
Meteor.methods({
  do_something(id) {
    at.save({
      fields: fields
    });
    return true; // Returns only if there were no validation errors.
  }
});
```

**Comment by joetidee** [comment]
The problem is that i would like to chain some events together, based on whether the `save` function failed or not. For example:

```
Meteor.methods({
  do_something(id) {
    return at.save({
      fields: fields
    },function(err, id){
        if( err ){
             // Generate a custom error message, or trigger some other function that sends data back to the client.
        }
        else{
            // Do some other stuff and ultimately return the results of this back to the client.
        }
    });
    return true; // Returns only if there were no validation errors.
  }
});
```

If the `save` function doesn't allow subsequent event results to bubble up and be returned by the Meteor method back to the client, then it doesn't give you much control over the return value of the Meteor method.

**Comment by lukejagodzinski** [comment]
It's not Astronomy problem but Meteor/JS problem. First you should learn more about synchronous/asynchronous calls. `doc.save()` is called synchronously if not callback is provided and asynchronously if callback was passed as the last argument - the same as in `Collection.insert/update`. So your code can look like in the example below.

``` js
import User from '/imports/classes/user.js';

Meteor.methods({
  test() {
    const user = User.findOne();
    user.firstName = String(Math.random() * 10000000000000000);
    let result;
    try {
      result = user.save();
      if (result === 1) {
        return `Result is ${result}`;
      }
    }
    catch(err) {
      if (err) {
        throw new Meteor.Error('Throw different error');
      }
    }
  }
});
```

**Comment by joetidee** [comment]
Much appreciated.

**Comment by joetidee** [comment]
If save is run synchronously, is there a need to wrap it in the try/catch block? I take it the save method returns the _id if a new record, the num records affected if an existing document and and error if something failed?

**Comment by lukejagodzinski** [comment]
Please read documentation and don't create so many threads with basic questions. Moreover I recommend reading some advanced JS course.

As I said, `doc.save()` throw exception if validation fails. If there is an error thrown then it mean no return value. If there is no validation error thrown, then `doc.save()` will return some value: number of affected documents on update and inserted doc id on insert.

You don't need to wrap `doc.save()` in try/catch as long as you don't want to do something with the error. If you just want to throw error to the client than do not use try/catch.

**Comment by joetidee** [comment]
I couldn't find anything in the Storing Documents section which identifies what is returned form the save() function.
