### ISSUE TITLE
Can fields be excluded from being validated/saved?

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#521]
As opposed to the section 'Updating only selected fields', is there away to exclude fields from validation/saving, for example:

`doc.save({exclude: ['some_field']});`

This would be useful if say you have a model with say 50 fields and you just want to exclude one field when saving. Otherwise the only way to do this is to list 49 fields in `fields` parameter of the `save` function.

**Comment by lukejagodzinski** [comment]
Right now there is no option of excluding some fields. However you can do it without listing all the fields:

``` js
import { pull } from 'lodash';

const Class = doc.constructor;
doc.save({
  fields: pull(Class.getFieldsNames(), 'some_field')
});
```
