### ISSUE TITLE
How to use the save() method in progam flow ...

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#522]
I am wondering how to use the `save` method, where subsequent code relies on the outcome of the `save` method (this is server-side by the way). I.e. is it async or sync? Do I:

1) Place code, that relies on the return value of the `save` method, inside the callback function?

```
var user = new User();
user.save(function(err, id) {
    if( err ){
        throw new Meteor.Error("something here");
    }
    else{
        // Continue with code execution that relies on the id or num records affected being returned.
    }
});
```

or 2) Place the code after the save method ?

```
var user = new User();
user.save();
// Continue with code execution that relies on the id or  num records affected being returned.
```

**Comment by jhuenges** [comment]
If I am not mistaken it doesnt matter. At least on the server. However, using callbacks makes the code less readable. On the client you do have to use callbacks to use the result of the `.save` call.

**Comment by lukejagodzinski** [comment]
@jhuenges is right. If it's on the server then just don't use callback and code will be synchronous.

**Comment by joetidee** [comment]
The difference being that the function call in 1) is async and in 2) is sync, right ?

**Comment by lukejagodzinski** [comment]
@joetidee yes
