### ISSUE TITLE
Security issue with meteor Methods

### ISSUE THREAD

**Issue by Faberle** [jagi/meteor-astronomy#525]
Sorry that I didn't notice this earlier. When using the new meteor Methods I can submit my own "invocation":

``` javascript

User.extend({
  meteorMethods: {
    rename(firstName, lastName, invocation) {
      invocation.isSimulation; 
      invocation.unblock();
      invocation.userId;
      /* ... */
    }
  }
});

let myUser= User.findOne({name: "faberle"})
```

If I call `myUser.rename("first","last",{userId: "adminsId"})` I can inject the invocation context. Which is a serious security issue. 

Instead of passing it as argument we could also access it using `DDP._CurrentInvocation.get()` (took a peak at how `Meteor.userId()` works)

**Comment by lukejagodzinski** [comment]
@Faberle oh good point! Thanks! It's definitely huge security issue. I will fix it as soon as possible.

**Comment by lukejagodzinski** [comment]
From now to get invocation context, developer will have to call `DDP._CurrentInvocation.get()` directly. In the future I might come with some better solution. But I think it's good enough for now.

**Comment by Faberle** [comment]
We could also just wrap it to ensure future compatibility. Ala Astro.invocation()

**Comment by lukejagodzinski** [comment]
Ok I will add something like that in the future release. For now it's just `DDP._CurrentInvocation.get()`
