### ISSUE TITLE
Removing field "user_id" when saving instance of Class via meteorMethods

### ISSUE THREAD

**Issue by furagi** [jagi/meteor-astronomy#528]
Here's my application: https://github.com/furagi/poller
In the [Topics](https://github.com/furagi/poller/blob/develop/imports/api/topics/collection.js) I defined meteorMethod "answer". In this method I creating instance of Comment, like 
```
if(!Meteor.isServer) {
        userId = Meteor.userId();
}
let comment = new Comment({
        text,
        topic_id: this._id,
        user_id: userId
      });
```
When I call Topic::answer from the server, everything is fine.
But when I call the Topic::answer from [client-side](https://github.com/furagi/poller/tree/develop/imports/ui/components/comments/commentAdd/commentAdd.js) , I get validation error. It says, that user_id is undefined. I checked in debugger, and comment.user_id is defined when I call comment.save().
I also checked in debugger, at [Comment's](https://github.com/furagi/poller/blob/develop/imports/api/comments/collection.js) event beforeInsert(e) , e.currentTarget.user_id is still defined.
I found temporary solution: for some reasons, when I set user_id in Comment's beforeInsert event, it's works.
Here is my Comment's beforeInsert code:
```
beforeInsert: function(e) {
      const comment = e.currentTarget;
      let slug = comment._id;
      let fullSlug = `${formatDate(comment.created_at)}:${slug}`;
      if(typeof comment.parent_id == "string") {
        const parent = Comment.findOne(comment.parent_id);
        fullSlug = `${parent.full_slug}/${fullSlug}`;
        slug = `${parent.slug}/${slug}`;
      }
      e.currentTarget.user_id = Meteor.userId();
      e.currentTarget.slug = slug;
      e.currentTarget.full_slug = fullSlug;
    }
```

**Comment by lukejagodzinski** [comment]
You're not providing `user_id` on `topic.answer` and your `beforeInsert` event is only setting the `user_id` field on the client. Validation is performed on both client and server, so you should also fill this field on the server. Validation error is not coming from the client but probably from the server.
