### ISSUE TITLE
Transforming documents into astronomy object

### ISSUE THREAD

**Issue by matteodem** [jagi/meteor-astronomy#531]
Is there anyway to transform a mongodb document into an astronomy object? The original question is asked here https://github.com/matteodem/meteor-easy-search/issues/428. 

```js 
const Posts = new Mongo.Collection('posts');
const Post = Class.create({
  name: 'Post',
  collection: Posts,
  fields: {
    title: {
      type: String,
      validators: [{
        type: 'minLength',
        param: 3
      }]
    },
    userId: String,
    publishedAt: Date
  },
  behaviors: {
    timestamp: {}
  }
})

Post.transform(Posts.findOne(/* ... */)) // is this possible?
```

Thanks for this awesome package! ⭐️

**Comment by lukejagodzinski** [comment]
Hey, yes there are several options of doing what you want. The easiest one is:

``` js
Posts.findOne(selector, {
  transform(doc) {
    return new Post(doc, {
      clone: false
    });
  }
});
```

It's also important to note here, that for performance reason, you should pass the `clone: false` option to the constructor. You could also assign the transform function to the class permanently but it may not work with all third party packages. But if you want I'm giving a sample code.

``` js
const Posts = new Mongo.Collection('posts', {
  transform(doc) {
    return new Post(doc, {
      clone: false
    });
  }
});
```

**Comment by matteodem** [comment]
perfect, thank you!
