### ISSUE TITLE
helpers or methods.

### ISSUE THREAD

**Issue by mikecentiq** [jagi/meteor-astronomy#532]
I upgraded to 2.3.1 earlier, and I noticed that you'd renamed helpers back to methods. So I updated my code again to go back to methods. Yet I'm still getting the deprecation warnings saying that I'm supposed to be using helpers. So which is it?

On a wider note, don't these sorts of backwards incompatible changes usually warrant a major version change? It would also be helpful to know why you felt the need to change the API in this way, but I can't find anything relevant in the commit logs. Is it going to change back again?

**Comment by lukejagodzinski** [comment]
Where did you see info that I've change helpers back to methods? It didn't happen. And you should still use helpers. However both are working and it's not breaking semver compatibility. It's just deprecation warning, so it will change permanently in 3.0.
