### ISSUE TITLE
indexes not being created

### ISSUE THREAD

**Issue by fugufish** [jagi/meteor-astronomy#533]
```
fields: {
        name: {
            type: String,
            validators: [{
                type: 'minLength',
                param: 3
            }],
            index: 'text'
        }
```

```meteor:PRIMARY> db.meteor.getIndexes()
[ ]
```

**Comment by fugufish** [comment]
`Exception while polling query {"collectionName":"things","selector":{"$text":{"$search":""}},"options":{"defaults":true,"children":true,"clone":false}}: text index required for $text query`

**Comment by fugufish** [comment]
seems to be limited to only text indexes. I have a 2dsphere index on the same collection and it was created.

**Comment by lukejagodzinski** [comment]
Hmm strange. I've tested and it works on my machine. Maybe it's a problem related with MongoDB version. What version do you have?

**Comment by lukejagodzinski** [comment]
Can you confirm that this bug is present?

**Comment by fugufish** [comment]
sorry for the delayed response, busy week. I can confirm that $text indexes are not being created unless I use the ensure index method. other indexes are being created. this is development so it is using meteor's mongo instance.

if I create the index using ensure index it shows up.

**Comment by lukejagodzinski** [comment]
Once you wrote that using `ensureIndex` indexes are not created and the other time that using `ensureIndex` creates indexes. So which one is true? You have to test several ways of creating indexes.

In Meteor shell or in the server Meteor code:
```js
YourCollectionName._ensureIndex(/* ... */);
```

In MongoDB console:
```js
db.your_collection_name.createIndex(/* ... */);
// or
db.your_collection_name.ensureIndex(/* ... */);
```
Depending on which version of MongoDB you have.
