### ISSUE TITLE
Class inheritance bug if extend is called after inherit?

### ISSUE THREAD

**Issue by Faberle** [jagi/meteor-astronomy#536]
I create a Class A, then let B inherit from A. 
Afterwards I `extend `A by adding a field foo.
Then `A.foo` exists but `B.foo` doesn't.

My proposal: 
We update all already created children of A after `extend` is called.

**Comment by lukejagodzinski** [comment]
Yes I know about this issue. During development of version 2.0 there was no easy way of implementing it but just with a lot new features it should be quite easy to implement now. I will add this to the features list to implement.

**Comment by lukejagodzinski** [comment]
I've implemented this feature and it will appear in the next release. I don't know if it's gonna be minor or bugfix release. I will decide this week :)
