### ISSUE TITLE
softremove-behavior-error

### ISSUE THREAD

**Issue by CyberCactus** [jagi/meteor-astronomy#539]
After latest package updates, Astronomy "methods" were changed with "helpers".
I have this version installed in Meteor: jagi:astronomy@2.2.4
I have behavior package installed: jagi:astronomy-softremove-behavior@2.0.4

**BUG**
If I open the "behavior.js" file, I can see that "softRemove" method is defined under object name "methods", which is why probably I get this error: "softRemove" is not defined.

**Comment by lukejagodzinski** [comment]
There was a bug introduced with the `meteorMethods` feature. You have to use `jagi:astronomy-softremove-behavior@2.0.4` or update Astronomy to the newest version.
