### ISSUE TITLE
Default values on nested inherited fields

### ISSUE THREAD

**Issue by atcwells** [jagi/meteor-astronomy#54]
It doesn't appear that these work.. I realise it's an edge case!

Code something like this:

Parent = Astro.Class({
  name: 'Parent',
  fields: {
    'system': {
      type: 'object',
      default: {}
    },
    'system.field2': {
      type: 'string',
      default: 'field2test'
    },
});

Child = Base.extend({
  name: 'Child',
  collection: Childs,
  fields: {
    "field1": {
      type: 'string',
      default: 'field1test'
    }
});

new Child().save();

The record created will have the values {} for system, and field1test for 'field1', but not the nested field. Moving the nested field up to the top level causes this default to be inserted properly.

Will see if I can dig in the code and suggest a fix.

**Comment by jagi** [comment]
Hi, thanks for letting know. I'm right now a little bit busy with private stuff and will have time to test it out after the weekend, so I would be glad if you could suggest a fix. However I will get back to it on Monday.

**Comment by jagi** [comment]
This bug was fixed, probably by accident :D in the next release. I won't publish it right now because it's bigger release. So, please wait for it. For now I'm closing this issue.
