### ISSUE TITLE
Split form submission

### ISSUE THREAD

**Issue by bryantbiggs** [jagi/meteor-astronomy#540]
I have a parent class ("Projects") and three child classes ("Shoe", "Pant", "Shirt") that inherit from it. The information in the parent class is on a single form and I can submit that into the collection without issue. Once I submit the first form, I update my route id with the newly created document id and I want to use that in the second form as an update. So the first form is general "Project" information and then in the second form, using that id and based on a radio selection, the document will be updated to either a "Shoe", "Pant" or "Shirt" item. Is there a way of doing this in Astronomy? I want to avoid things like reactiveVar because once the user submits the first form and it is valid, I don't want them to have to come back to it - if I just hold the first form ("Projects") information and then validate it when the second form is submitted (all information required for each child class will now be present) the user would have to be possibly directed to two locations to correct their entries

**Comment by bryantbiggs** [comment]
for now I am saving using the "Projects" parent class, then re-assign those values to the child class during the second form submission and then delete the initial "Projects" document now that all the information is rolled into one document of a child class. I just didn't know if there was a better method to performing this style operation - initially I thought I could use "Extend" to incrementally build the document but I was unable to do so

**Comment by lukejagodzinski** [comment]
It a little vague for me. Let me ask a question so maybe it will be more clear what you want to do. So you have form data and you want to save it as the `Project` document and later change type to one of the `Shoe`, `Pant`, `Shirt`? Is that all you want to do? Probably there would be better solution for that but I don't know how actually your forms and code is structured and without code samples it's hard to tell.

However, currently there is no way of directly changing type of a document, but it's possible. In the parent class you had to provide `typeField` which tells Astronomy which fields describes type of a document. So when that field is `type`, then it will store in that field the `"Project"` string. So to change type of a document you would have to change that field to for example `"Shoe"`. So you would have to do:

``` js
const project = Project.findOne(projectId);
project.type = 'Shoe';
project.save();
```

That way, whenever you fetch the same document again it will be instance of the `Shoe` class.

``` js
const project = Project.findOne(projectId);
project.type; // "Shoe"
project instanceof Shoe; // true
```

Is that what you want?

**Comment by bryantbiggs** [comment]
That was initially what I thought I could do but I was unable to get it to work properly.

So if I have my parent class "Projects":

``` js
export const Projects = Class.create({
    name: 'Projects',
    collection: ProjectsCol,
    typeField: 'type',
    fields: {
        shape: { type: String },
        color: { type: String },
        size: { type: String }
    },
    indexes: {},
    behaviors: {
        timestamp: {}
    },
    helpers: {}
});
```

And then one of the child classes such as "Pant":

``` js
export const Pant = Projects.inherit({
    name: 'Pant',
    fields: {
        waist: { type: Number },
        inseam: { type: Number }
    },
    indexes: {},
    behaviors: {},
    helpers: {}
});
```

From the first form submission I am just collecting general information that will be validated/saved against the "Projects" class" and with the callback I pass the document id into my route for use in the next form:

``` js
projectDoc.validate(function(err, id) {
    if (err) {
        if (ValidationError.is(err)) {
            //...
        }
    } else {
        Meteor.call('insertProject', doc, function(error, result){
          var id = result;
          FlowRouter.go('/'+shape+'/'+id);
        });
    }
});
```

Then on the 2nd form, I tried a similar approach to what you suggested:

``` js
var project_id = FlowRouter.getParam("projectId");
var shape = FlowRouter.getParam("shape");
var projectDoc = Projects.findOne(project_id);

if (shape === 'pant') {
    projectDoc.type = 'pant';
    projectDoc.waist = template.find('[name=waist]').value;
    projectDoc.inseam = template.find('[name=inseam]').value;
} else if (shape === 'shirt') {
    projectDoc.type = 'shirt';
    //...
} else if (shape === 'shoe') {
    projectDoc.type = 'shoe';
    //..
}

projectDoc.validate(function(err, id) {
    if (err) {
        if (ValidationError.is(err)) {
            //...
        }
    } else {
        Meteor.call('insertProject', doc, function(error, result){
            //...
        });
    }
});
```

And my meteor method is:

``` js
Meteor.methods({
    'insertProject' (projectDoc) {
        // Make sure the user is logged in before inserting a project
        if (!this.userId) {
            throw new Meteor.Error('not-authorized');
        }
        return projectDoc.save();
    },
});
```

However, when I do this I can change the class type from "Project" to "Pant" but I am not updating the document with "waist" and "inseam" (they don't show up in the document record at all).

**Comment by lukejagodzinski** [comment]
That's because they don't update automatically. Meteor's reactivity system will detect changes to the document field and push it to the client, but document will still be instance of the old class. You have to refetch document. Reloading document won't change here anything, it has to be a new fetch.

I see that the `shape` field dictates to what class given document will be casted, so you may consider making the `shape` field the `typeField` option's value. However, remember that the best practice is to make class names capitalized. Whatever you decide to do with the `typeField` option, there is a way of making class transformation on the server. It could look in the following way:

``` js
Meteor.methods({
    'insertProject' (projectDoc) {
        // Make sure the user is logged in before inserting a project
        if (!this.userId) {
            throw new Meteor.Error('not-authorized');
        }
        if (shape === 'pant') {
            projectDoc.type = 'Pant';
        }
        return projectDoc.save();
    },
});
```

Notice that in `projectDoc.type = 'Pant';` it's capitalized `"Pant"` the same as class name. So in your code is a bug.

**Comment by bryantbiggs** [comment]
Ah perfect, that works inside the method call. Thank you very much for the clarification.

Note - I made up the classes in order to better demonstrate the concept so the typos were in haste; thanks though!

**Comment by lukejagodzinski** [comment]
@bryantbiggs ok glad that I could help :)
