### ISSUE TITLE
Error: object [""] is not a valid ObjectId

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#542]
Hey,
in one of our cronjobs I'm getting the following error message if I try to save an Astronomy object:

     Error: object [""] is not a valid ObjectId

We're creating an Astronomy object on the begin of the Cronjob, f.e.:

     var playlist = new Playlist({
            name: "Top 100",
            details: {country: country._id, type: 'top100'},
            userId: 'system'
        });

Then we add some objects to an array (takes about 5-6 seconds) and finally try to save it:

     playlist.validate((err) => {

            if(err) {
                console.log(err);
            } else {

                playlist.save();
            }

        });

In my case, <code>_id</code> seems to be <code>null</code>.

**Comment by lukejagodzinski** [comment]
It's hard to tell. You need to create reproduction repository.

**Comment by dnish** [comment]
Mh interesting, we've added objects to our songs array - and each song had an <code>_id</code> field. 


     var playlist = new Playlist({
        name: "Top 100",
        details: {country: country._id, type: 'top100'},
        userId: 'system'
    });

    foundSongs.forEach((doc) => {
      playlist.songs.push(doc);
    });

After removing the _id field of each song, it started working again. We've defined the songs field like this in our Astronomy class:

     songs: {
            type: Object,
            default: function() { return []; }
        },

**Comment by lukejagodzinski** [comment]
You shouldn't store objects with `_id`s as a nested field. If you have the `_id` field in a document it means that it should be stored in a separate collection. I assume that you're doing so, but you're also trying to store it in the `songs` property which is not correct. If you want to store relations, then you should only store id of a related document in a field like `songId` which is string.

**Comment by dnish** [comment]
Yeah I know, the songs aren't received from a Mongo collection. In my case I've added the <code>_id</code> field to the filter, but it was always null because songs don't have an <code>_id</code>. So I guess this caused the issue. But good to know that foreign <code>_id</code> fields could cause such an error.
