### ISSUE TITLE
{merge: true} fails on date type

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#546]
```
post.set({readOn: new Date()}, {merge: true});
```

fails to update `readOn` if it already exists. This probably happens because `Date` is of type "object".

**Comment by lukejagodzinski** [comment]
I think I've made `_.isPlainObject` check instead of `_.isObject` just because of such a case but I will check it.

**Comment by lukejagodzinski** [comment]
Yes I've used `_.isObject` my bad. I will fix it later today.

**Comment by lukejagodzinski** [comment]
I've fixed it and will release a bug fix version today.
