### ISSUE TITLE
[Q] doc.validate() validates each field or only the modified ones?

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#547]

**Comment by lukejagodzinski** [comment]
It validates all the fields

**Comment by s7dhansh** [comment]
Shouldn't it validate only the modified fields? It will make it a lot faster.
I have a collection with quite a complex + big document schema and it takes a lot of time to save it.

**Comment by lukejagodzinski** [comment]
I can think about such solution. It shouldn't be hard to do and in deed it will speed up validation a little bit. However I'm just concerned about data being modified in a database without using Astronomy. Let's say somebody changed first name of a user:

```js
// NOTE: Collection update
Users.update(userId, {$set: {firstName: 123}});
```

Now when I fetch this document and try to validate it, it will not throw any errors.

```js
// NOTE. Class fetch
const user = User.findOne(userId);
user.validate();
```

Maybe I could add some option to the validate method that would force validation of all fields

**Comment by s7dhansh** [comment]
True, in that case we can have a flag `{all: true}` as an argument to `validate`. Or the opposite for backwards compatibility, `{modified: true}`.

**Comment by lukejagodzinski** [comment]
Feature implemented and will appear in the next release
