### ISSUE TITLE
not returning astronomy class

### ISSUE THREAD

**Issue by frankapimenta** [jagi/meteor-astronomy#548]
V2.3.4

Retrieving the document from the collection (on server side only) is not returning an astronomy class object but a js object.

Is there something in this version that is different from V1?

**Comment by lukejagodzinski** [comment]
You are switching from `v1` to `v2.3.4`? If so, then there are a lot of differences. You no longer retrieve Astronomy document using collections. You use classes.

```js
const Posts = new Mongo.Collection('posts');
const Post = Class.create({
  name: 'Post',
  collection: Posts,
  /* ... */
});
// v1
Collection.findOne();
// v2
Class.findOne();
```

**Comment by frankapimenta** [comment]
Yap. Sorry for this question. Thank you for your great support!
