### ISSUE TITLE
Error: "fullName" is required [validation-error]

### ISSUE THREAD

**Issue by aabanaag** [jagi/meteor-astronomy#550]
Tried using Mapping in my class. I wanted to perform the classing retrieval of fullName from firstName and lastName field.

**class:**
```
fullName: {
      type: String,
      resolve: function(doc) {
        return doc.firstName + ' ' + doc.lastName;
      }
    }
```

**implementation**
```
let playerData = new Player(data);
playerData.set(data);
```

**ERROR**

`Exception in callback of async function: Error: "fullName" is required [validation-error]`

**Comment by lukejagodzinski** [comment]
And what values does the `data` variable have? Mapping is only used for values coming from collections. So if you're trying to pass `firstName` and `lastName` in `data` and expecting it to be resolved to `fullName` then you're doing it wrong. As I said it's only for collection data.

**Comment by aabanaag** [comment]
okay. I'm doing it wrong. I'm closing this one. Thanks for the response.
