### ISSUE TITLE
Helpers not being added in behaviors

### ISSUE THREAD

**Issue by ochicf** [jagi/meteor-astronomy#551]
Hi! I've been changing all my definitions `methods` to `helpers`, and I've found that the `helpers` defined by a behavior are not added to the definition and hence cannot be used from documents.

I think the problem is in the `Class.extend` static method: when looping through the Modules in order to apply them the module 'helpers' seems to be missing. I don't know if this [commit](https://github.com/jagi/meteor-astronomy/commit/1e655226094583e04b6636d1df5ec759c5c80be3#diff-0d8c7c17ec9c9a1124ea9167c921afad) has something to do with it?

Here's a piece of code so you can test it:

```js
import { Class, Behavior } from 'meteor/jagi:astronomy';

Behavior.create({
  name: 'methodsBehaviorTest',
  createClassDefinition() {
    return {
      methods: {
        methodTest() {
          console.log('method correctly added');
        },
      },
    };
  },
  apply(Class) {
    Class.extend(this.createClassDefinition(), ['methods']);
  },
});

Behavior.create({
  name: 'helpersBehaviorTest',
  createClassDefinition() {
    return {
      helpers: {
        helperTest() {
          console.log('helper correctly added');
        },
      },
    };
  },
  apply(Class) {
    Class.extend(this.createClassDefinition(), ['helpers']);
  },
});

const MethodsVsHelpersTest = Class.create({
  name: 'MethodsVsHelpers',
  behaviors: {
    methodsBehaviorTest: {},
    helpersBehaviorTest: {},
  }
});

const test = new MethodsVsHelpersTest();
test.methodTest(); // method correctly added
test.helperTest(); // Uncaught TypeError: test.helperTest is not a function
```

I'm using `astronomy@2.3.7`.

Thanks!

**Comment by lukejagodzinski** [comment]
It's because module name is still `methods` for backward compatibility. The only change is in class definition. So you should write:

```js
Class.extend(this.createClassDefinition(), ['methods']);
```

instead

```js
Class.extend(this.createClassDefinition(), ['helpers']);
```

**Comment by ochicf** [comment]
Thanks for the response.

The thing is that If I exend the class with `methods` (as it was before I tried to change it) I'm getting the deprecation warning `Deprecation warning: Methods have been renamed to helpers. Please use the "helpers" section in the "MethodsVsHelpers" class definition.`

Wouldn't be easier to have both `methods` and `helpers` modules (being the same module but with different names) so they both work and remove `methods` when changing to Astronomy 3?

**Comment by lukejagodzinski** [comment]
In theory I could allow a module to have some aliases, so the `methods` module could have the `helpers` alias. But I don't know if it's a good idea, because such things causes even more confusion as developers may not know which name to use.

**Comment by ochicf** [comment]
I think it would be clearer with the alias because when using the `methods` module in a behavior the deprecation warning is shown, so the developer can choose between ignoring it or changing it to `helpers`, the new and future proof way of doing it. But right now if the developer chooses to apply what the deprecation warning says the behavior's helpers will not work anymore. In my opinion this is far more confusing (and frustating) than having the alias.

**Comment by lukejagodzinski** [comment]
I've added aliases in 2.3.10
