### ISSUE TITLE
arrays

### ISSUE THREAD

**Issue by frankapimenta** [jagi/meteor-astronomy#552]
V2

I have a class with an array field which stores (pushes) objects of type some Class.

Imagine Post saves comments in an array and each comment is a class Comment (without collection) with an _id (generated with Random.id()).

How can I delete a specific comment from the comments array?
How can I replace a specific comment from the comments array?

(could not find anything regarding this in the docs - besides the push example)

**Comment by lukejagodzinski** [comment]
You can use whatever method you want to achieve that. There are many tools that allow such things. I prefer `lodash` but you could also use pure JS. It could look like this:

```js
// pure JS
// Delete comment which author is Jagi
const post = Post.findOne();
const index = post.comments.findIndex((comment) => comment.author === 'Jagi');
post.comments.splice(index, 1);
post.save();
```

```js
// using lodash
const post = Post.findOne();
post.comments = _.remove(post.comments, (comment) => comment.author === 'Jagi');
post.save();
```

**Comment by frankapimenta** [comment]
I used _.reject ...but if the framework api would provide it I would prefered to use the api.
But good like this.
Maybe it would not be a bad idea to mention this (and this example) in the docs for V2 because in V1 it existed the pull method.
Thank you :)

**Comment by lukejagodzinski** [comment]
I've mentioned in docs that developer is free to use any method to modify data, so there are no restrictions. But I will add the "pull" operation example.

**Comment by frankapimenta** [comment]
You are right. I would suggest thought, those info (some color background divs) for special notes. Like in the rails guides.
One could make it one color for deprecated, another for solution example, another for special attention to something...
