### ISSUE TITLE
Invalid or missing Date validation message

### ISSUE THREAD

**Issue by stoked74** [jagi/meteor-astronomy#553]
I have a date property in an Astronomy class that I want to override the default error message during validation but when I add the date type validator to the validators array with the message property or the resolveError function the default message is still returned in the errors array. The message that gets returned is: "jobStartDate" has to be a date

```javascript
jobStartDate: {
  type: Date,
  validators: [{
     type: 'date',
      resolveError () {
        return 'Please provide a valid date'
      }
    }]
}
```

**Comment by lukejagodzinski** [comment]
I forgot to describe it in docs, so I have add this. There was already the thread about this. Read this https://github.com/jagi/meteor-astronomy/issues/518

**Comment by stoked74** [comment]
Thanks for the update Jagi.
