### ISSUE TITLE
Referencing _collection instead of using Collection?

### ISSUE THREAD

**Issue by Andrew1431** [jagi/meteor-astronomy#555]
https://github.com/jagi/meteor-astronomy/blob/76251adaf7cf6410bfe642c5c14ccdeb229ed51e/lib/modules/storage/utils/document_update.js#L78

Hey, I'm just curious why on this line you use Collection._collection instead of calling Collection.update? Is there any difference between the two?

**Comment by lukejagodzinski** [comment]
It's a huge difference. Calling `Collection._collection.insert` will call only local version of the method, however `Collection.insert` would call meteor method that would executed method in both client and server.
