### ISSUE TITLE
Nested fields in options.fields are ignored

### ISSUE THREAD

**Issue by jthomaschewski** [jagi/meteor-astronomy#557]
Astronomy 2.3.7

**Code** (based on test in `test/modules/storage/document_update.js`)

```js
const storage = Storage.findOne(id);

storage.number = 1234;
storage.one.string = 'something';

storage.save({fields: ['one.string']});
```

**Expected result:**
Successful save of only `one.string` of storage instance

**Actual result:**
field `one.string` remains untouched.
```
- fail — assert_equal - message The document has not been updated properly - expected {"one":{"string":"something"} .... } - actual {"one":{"string":"cba"}....} - not
```
This is reproducable by cloning latest `v2` and adding this to `test/modules/storage/document_update.js`
Test will fail with the above error.

EDIT: 
I previously added a stacktrace for an exception which was caused by me (wrong field provided).
So I roughly edited my previous report as the base issue still remains (nested field updates do not work with options.fields)

**Comment by jthomaschewski** [comment]
I compared the behavior with previous commits and could track it down to this commit: https://github.com/jagi/meteor-astronomy/commit/147429df7bb5f8b589c82af28a0e72830e4906a7
Any later commits have this issue.

For completeness the lines I added to the `document_update.js` test:
```js
 /** .... rest unchanged ... **/

  // only save specified fields
  storage.number = 123;
  storage.boolean = true;
  storage.one.string = 'abc';

  expected.one.string = 'abc';
  expected.number = 123;

  storage.save({fields: ['number', 'one.string']});

  test.equal(Storage.findOne(id, {
    transform: null,
  }), expected,
    'The document has not been updated properly'
  );
});
```

**Comment by lukejagodzinski** [comment]
So, you're saying that it used to work and now is broken? In which version it used to work?

**Comment by lukejagodzinski** [comment]
Hmm yes in deed in might break things... I will try to solve this problem later today. Thanks for noticing it. I have to create more tests to avoid such problems in the future.

**Comment by lukejagodzinski** [comment]
Fixed! Today I will release another bugfix version

**Comment by jthomaschewski** [comment]
Thanks! I can confirm that it's working now
