### ISSUE TITLE
Exception while parsing DPP TypeError:  Class is not  a constructor

### ISSUE THREAD

**Issue by aabanaag** [jagi/meteor-astronomy#558]
I got this error.

```
let model = SettingsModel.findOne();
return model;
```

when I traced it it goes to this line.

```
EJSON.addType('Astronomy', function(json) {
  let Class = AstroClass.get(json.class);
  let doc = new Class();
```
but Class is undefined.

![image](https://cloud.githubusercontent.com/assets/2245822/20828892/a0de02ec-b8b4-11e6-87a1-28d0b90892d9.png)

Weird is the error is gone when I added .raw()

but when I used this

```
const md = SettingsModel.find({ userId: id }).fetch()[0];
console.log(md);
return md;
```

**Comment by lukejagodzinski** [comment]
Class definition has to be available on both client and server. So if you're not doing so, then it may not see the class in some of environments.
