### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by iamdanthedev** [jagi/meteor-astronomy#561]
Hello. I've started putting my application on Astronomy rails, but encountered the following problem:

Have this error appearing here:

```
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/babel-runtime/helpers/inherits.js                                                                      //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
.....

  if (typeof superClass !== "function" && superClass !== null) {                                                       // 24
    throw new TypeError("Super expression must either be null or a function, not " + (typeof superClass === "undefined" ? "undefined" : (0, _typeof3.default)(superClass)));
  }    

```

console.log(superClass):

```
Class() {                                                                                                   // 55
    var rawDoc = arguments.length > 0 && arguments[0] !== undefined ? argumen…
modules.js?hash=09e6f88…:244

**create {}**
```

That is for some reason babel treats create as a class or smth.. Need to say that I couldn't update Astronomy to v2 by regular means (meteor update --packagename), it stayed version 1.12.something... Specified version manually: (from packages.json)

jagi:astronomy@2.3.9
jagi:astronomy-timestamp-behavior@2.0.0
ecmascript@0.6.1

**Comment by lukejagodzinski** [comment]
It's rather your project, not Astronomy specific. Have you tried updating Astronomy using?

```sh
meteor add jagi:astronomy@2.3.9
```

If you updated it manually, then you might break some constraints. First, you have to make sure that you're not using some other package that might require Astronomy 1.x

**Comment by iamdanthedev** [comment]
Hi Jagi, thank you for quick reply

I think I didn't explain what I had done clearly enough:
1) firstly meteor didn't want to update astronomy to v2, saying that "the latest version is installed satisfying dependencies"
2) I did  meteor remove jagi: astronomy and than, as you suggested,  meteor add  jagi:astronomy@2.3.9, it was installed correctly
3) from .meteor folder I manually deleted v1 of astronomy
4) I checked all deoendencies versions according to you git example project (npm and meteor dependencies file) - everything looks ok
5) :( 

Any ideas?

Thanks !

**Comment by iamdanthedev** [comment]
I've tried cloning the example project, it works perfectly
Now investigating into babel-runtime version and reintalling

**Comment by iamdanthedev** [comment]
After a few hours experimenting with packages I suddenly realised that I had a "new" operator before Class.create..... 
......

Thank you for the great library !

**Comment by lukejagodzinski** [comment]
Such bugs happen :)
