### ISSUE TITLE
meteorMethods callbacks not called, if Meteor.Error thrown

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#564]
I'm not sure if I misunderstood the docs or what, but..

it seems if I throw an error, or if any of the event hooks throws an error, the `meteorMethod`'s callback doesn't get called.

Repro:
https://github.com/arggh/astronomy-method-issue

**Comment by arggh** [comment]
From the docs:

```
const User = Class.create({
  name: 'User',
  /* ... */
  fields: {
    firstName: String,
    lastName: String
  },
  meteorMethods: {
    rename(firstName, lastName) {
      this.firstName = firstName;
      this.lastName = lastName;
      return this.save();
    }
  }
});
```

then:

```
const user = User.findOne();
user.rename('John', 'Smith', (err, result) => {
});
```

Now, if there is also this (doesn't have to be extend, can be in the actual Class declaration):

```
User.extend({
   events: {
    beforeUpdate: (e) {
       const user = e.currentTarget;
       if (user.isModified('firstName')) {
           throw new Meteor.Error('not-allowed');
       }
    }
  }
});
```

Then our callback doesn't get called, when calling `user.rename`.

**Comment by lukejagodzinski** [comment]
Yes in deed, it seems to be a bug but it only happens when error is throw on the client, when it's throw on the server, callback gets called. It should be easy fix.

**Comment by lukejagodzinski** [comment]
Fixed. Today I will release a new version

**Comment by arggh** [comment]
Great, thanks!
