### ISSUE TITLE
merge: true and optional fields

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#565]
Let's say a a field is defined as:
```
Category = Class.create({
	...
        fields: {
		type: {
			type: String,
			optional: true
		},
       }
});

category: {
  type: Category,
  optional: true
}
```

When `category` is `null` or `undefined`, doc.set({category: {type: ""}}, {merge: true, cast: true}) fails to update `category.type`. It succeeds only if `category` is an `Object`.

EDIT: Actually it happens in case of a double nested scenario: eg. `page.category.type`

**Comment by lukejagodzinski** [comment]
It's expected behavior as astronomy doesn't know how to merge undefined value. Yoo can only merge objects.

**Comment by s7dhansh** [comment]
But then we lose the advantage of `merge`. If we have to remember the field types and set them as objects, it again becomes an extra task.
Can't Astronomy have an extra check in case of merge and automate it?

**Comment by lukejagodzinski** [comment]
You can use default value for that field and it will merge with it. I can't merge with undefined values. Because it can be any value. What if someone set field's type to `String` and want to merge some value with it? I can't merge anything with string. Merging only applies to objects, so there should be an object already in a field. And as I said you can use default values for that.

**Comment by s7dhansh** [comment]
I generally avoid `default` as it causes problem in updating docs where I have not fetched all fields. It sets field which is not fetched to its default value, overwriting its original value.
Is there a way to use `default` safely?

**Comment by lukejagodzinski** [comment]
Yes there is a way of using `default` safely. Assuming that in the `User` class there is the `address` field whose default values is `{}`, then you can fetch it in the following way:

```js
User.findOne({}, {fields: {address: 0}, defaults: false});
```

**Comment by s7dhansh** [comment]
thanks!
