### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#566]
There is no mention in the docs about rate limiting. Has this been taken into consideration in Astronomy in any way, or is there a recommended way of settings it up with Astronomy?

**Comment by lukejagodzinski** [comment]
What do you mean by "rate limiting"?

**Comment by arggh** [comment]
https://guide.meteor.com/security.html#rate-limiting

So in essence, I can open up my console in Chrome and do this:

```
var jamServer = function() { while (true) { var d = new Doc({title: 'hax0r'}); d.save(); } };
jamServer();
```

There's no mention in Astronomy documentation on how to use rate limiting with Astronomy, so I thought I'd ask, if you have any thoughts.

**Comment by lukejagodzinski** [comment]
Astronomy registers several methods to allow certain operations:

- `/Astronomy/execute`
- `/Astronomy/insert`
- `/Astronomy/remove`
- `/Astronomy/update`
- `/Astronomy/upsert`
- `/Astronomy/validate`

and:

- `/Astronomy/softRemove`
- `/Astronomy/softRestore`

for the `softremove` behavior. They're global methods for all classes. So if you want to limit rate of method calls you should use them. If you would like to add info to documentation, it would be appreciated. I think it would best fit into security section.

**Comment by arggh** [comment]
Here you go: https://github.com/jagi/meteor-astronomy/pull/572

**Comment by lukejagodzinski** [comment]
Thanks! :)
