### ISSUE TITLE
Old values in afterUpdate -hook

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#569]
Say I have a Class `group`, which can be referenced from Class `person` to indicate that the person is part of that group.

When I move persons from one group to another, I would like to check if the previous group has any persons left, and if it doesn't, remove that group.

How is this achieved with Astronomy events? Basically I would need to know the old group in the `afterUpdate` event hook and also that the referenced group has changed.

Any ideas, besides refactoring into methods?

**Comment by lukejagodzinski** [comment]
You don't have access to the old value of a field in the `afterUpdate` event. You have to use `meteorMethods` instead.

**Comment by arggh** [comment]
Understood :)
