### ISSUE TITLE
Question about events

### ISSUE THREAD

**Issue by serkandurusoy** [jagi/meteor-astronomy#57]
I have three questions about events.

1) What is the order of execution for the events: `beforesave`, `beforeinsert`, `beforeupdate`, `beforeremove`, `aftersave`, `afterinsert`, `afterupdate`, `afterremove`? Is this correct: `beforesave` => `aftersave` => `beforeinsert/update` => `afterinsert/update` and independently `beforeremove` => `afterremove` 

2) Is the `afterinsert` hook from `matb33:collection-hooks` the same thing compared to the `afterinsert` event from `astronomy`?

3) Is `getModified()` available to the events so that I can check what actually has been modified within the `before/afterupdate` hook and act accordingly? I'm referring to the `this.previous` from https://github.com/matb33/meteor-collection-hooks#afterupdateuserid-doc-fieldnames-modifier-options

**Comment by jagi** [comment]
1) Insert operation: beforeSave, beforeInsert, afterInsert, afterSave
Update operation: beforeSave, beforeUpdate, afterUpdate, afterSave
Remove operation: beforeRemove, afterRemove
I forgot to mention it in the doc. I will add it.

2) It's not exactly the same thing but please precise the question.

3) Yes you can use `getModified()` in the event, however it will only work in the `before` events.
Also have to mention it in the doc.

**Comment by serkandurusoy** [comment]
1) Thanks for 1&2 although I would naturally assume beforesave,aftersave,beforeinsert,afterinsert but now I understand that a save *wraps* the insert. So I guess updating the docs would be great help in understanding that. So then, what's the difference between afterinsert and aftersave? What happens in between? Why would I need those two different events?

2) I was thinking about the insert operation having finished so that we have a reference to the newly created document's id and use it to trigger other database operations. Could you provide an example?

3) Great!. Thanks.

and bonus 4) Are you planning a beforeFind / beforeFindOne so that we can manipulate the query selector and options (not talking about a transform, I'm referring to changing he actual query selector)

**Comment by jagi** [comment]
1) The reason for having two different events is that there are operations that you would like to execute no matter if you are inserting or updating document. Let's say we have `timestamp` behavior. In this situation you would like to update different fields in `beforeInsert` and beforeUpdate` events. However in the `slug` behavior you would like to update the `slug` field no matter if you are updating or inserting, so the obvious solution would be using `beforeSave` event.

2) In the `beforeInsert` event you have access to the document before inserting, and in the `afterInsert` event the document already has the `_id` field filled.

4) Yes, I already had request about that feature. And implementing before and after `transform` events will be quite easy.

**Comment by serkandurusoy** [comment]
Thanks!

**Comment by minfawang** [comment]
I was looking for the order of execution of events created from behaviors, and found this thread. Looks like that part was not documented (if I didn't miss one or two pages).

I was afraid of creating multiple behaviors using the same event name overwriting other ones, so I did a manual experiments:
~~~javascript
Astro.Class({
  ...
  events: {
    afterSet(e) { /* myAfterSet */ }
  },
  behaviors: [ 'afterSet1', 'afterSet2' ]
})
~~~

And found out the order is: `afterSet1`, `afterSet2`, and `myAfterSet`, which is great! :+1: 
I guess it kinda matches people's expectation, but maybe that's something worth documenting :)
BTW, awesome work!

**Comment by jagi** [comment]
@minfawang yes it may be good to add this information to the documentation. That's exactly how it works. The user events are added at the end.

Thanks :)
