### ISSUE TITLE
Accidental removal of document's data

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#571]
Astronomy either has a defect in implementation or a big missing gap in the documentation regarding saving documents when subscribed to only a subset of the fields. There is a high chance of losing data.

Repro: https://github.com/arggh/astronomy-removal-issue

It's a best practice recommended by MDG and Meteor Guide to publish/subscribe only to the fields you need and keep most of them "secret", if they are not needed.

Right now, the following scenario can happen to anybody and I can assure that it's quite easy to not notice what's happening, before it's too late.

You have a Class `Document`

```
Document = Class.create({
  name: 'Document',
  collection: Documents,
  secured: false,
  fields: {
    name: {
      type: String,
      optional: true
    },
    address: {
      type: Object,
      default: function() {
        return {};
      }
    }
  }
});
```

1. One part of the app allows `Document`'s to be saved with two fields, `name` and `address`.
2. Another part of the app manages the same documents, but only needs the name field. Therefore the publication this time limits the published documents' fields to only `name`.
3. When only subscribed to partial fields, if making an update to the `name` field, the `address` gets overwritten by (the default) empty object, even though it hasn't been changed.
4. Voilá, your user's data is gone forever-ever.

This only (by preliminary tests) happens, if there is a default value specified for the field.

To remedy this, I would either:

**A)** Only update the fields that have been actually changed (not counting changed by Astronomy by filling in default values)
**B)** Have a Gigantic warning sign about this issue and dedicate a section in the documentation about how to use Publish&Subscribe with Astronomy (eg. always publish everything, which is probably not possible for most use cases)

**Comment by arggh** [comment]
Also, I realize there is the option to declare which fields to update when calling `save`, but I still consider current behavior quite dangerous?

**Comment by arggh** [comment]
Also, seems like setting the particular field as `optional` might prevent the overwrite.

**Comment by arggh** [comment]
It doesn't matter if the field is set as `optional` or not, it gets overwritten by a default value.

**Comment by lukejagodzinski** [comment]
Hmmm yes in deed it's a big problem. The way how I'v implemented default values was wrong. Default values should only be used on insert not on update. However, changing that right now would break compatibility. I'm aware of this problem, it was discussed many times already. That's why I've introduced `defaults` option to the `find()` method. You could solve this problem in your code by changing this code:

```js
Template.partialDocs.helpers({
  documents() {
    return Document.find({}, {defaults: false});
  }
});
```

In fact the `defaults` option should be set to `false` by default but to not break compatibility I've just introduced this option. There is also the same option in the class constructor.

```js
var doc = new Document({}, {defaults: false});
```

This time it's also `true` by default and it's the only place where it should be `true`. Maybe some section in documentation would help a little bit but most people don't even read documentation :). However, I will describe it.

**Comment by lukejagodzinski** [comment]
http://jagi.github.io/meteor-astronomy/v2#setting-and-getting-values
http://jagi.github.io/meteor-astronomy/v2#fetching-documents

**Comment by arggh** [comment]
How about including this as a global setting for Astronomy, instead of passing it around as a parameter to method calls?

Then it would not break backwards compatibility, but would allow the "correct behavior" to be set as the default.

I'm also having a hard time understanding why anybody would want it the other way round, but it's late and that's just me.

**Comment by lukejagodzinski** [comment]
Yes I may include it as a global setting.

As I said it's a bad design from the early versions of Astronomy and I couldn't just change it because I realized that it's a bad behavior. I've already made one compatibility breaking change and I said it's the last one but then it was more serious issue.

**Comment by arggh** [comment]
I still don't understand how it's a breaking change, if calling `save` on a document would update only the fields that have been changed?

I mean, this is literally the first thing one sees when opening Astronomy docs:

```
...
// Check if all fields are valid and update document
// with only the fields that have changed.
post.save();
```

when it in fact does something like overwrites document's fields that haven't changed (as far as I'm being asked, since I didn't change them between `find` and `save`), I'd personally consider it a bug.

It's too late in the night for me to reason about, how somebody could have programmed their app on this expectation (against the docs) and how their app might break, should Astronomy _not_ overwrite unchanged properties. I'll try to think about it in the morning :)

Thanks for explaining the issue and why it still exists.

**Comment by lukejagodzinski** [comment]
Because it's not only about the `save()` method. You don't have a whole picture of problems that may occur. Original reasoning was that when you migrate data and introduce a new field with a default value then all old documents will have this field filled with a default value on `find()`. That way calling `doc.save()` later would update old document to new state. It's similar to GraphQL's resolve method. Right now I know that this reasoning was wrong but you can't be sure if somebody is not using this in that way.

Trust me, people are using Astronomy in many strange ways, you would even never think off. I've experienced it many times. Some change that might be trivial will be a big problem for others. You have always think twice before making any change.

Of course, I could introduce this change and maybe no one would noticed, but who knows.

**Comment by arggh** [comment]
I trust your experience on the plethora of ways people use Astronomy, no doubt about that :)

My reasoning was more in line of these two thought chains:

1. Current implementation acts differently from what's said in the docs, so it's a bug that should be fixed

or..

2. Why couldn't a Document just keep track of the fields that changed after initialization. Then it wouldn't matter that the default values were "forced", they would not be touched in DB.

Also, I very much think the opt-in for the "correct" behavior should (or at least could?) be global and the recommended practice to avoid accidents.

But like you said, I'm probably missing 96% of the big picture with my reasoning. I just find this problem interesting, plus now that I refactored a rather larger part of my app to use `secured: false` and calling `save` from client, I actually have to run around my code base and define the fields I want to change on every call to `save`, so that I don't accidentally overwrite other fields in the process. Or use the `defaults`-option in `find`, which I'm not comfortable with - I would be afraid to call `save` on a document without tracing it's steps all the way to where `find`was called - again another opportunity for a small mishap and big problems.

Or maybe I just revert back to methods, as painful as it sounds now that I'm almost finished with the refactoring 👎

Offtopic feedback about the conversion away from methods:
- It's really quite magical to use Astronomy that way, you can easily skip a couple of boilerplate layers in your app and remove hundreds of lines of code
- It's really easy to break existing functionalities if you also manage the same documents from server side code without the client involved, so carefully considering authentication rules using `e.trusted` is vital, as well as thinking thoroughly how the documents are initialized in the `beforeInsert`-hook. Those two caused most of the problems in the process. I ended up using a lot of "if trusted and specific fields set, skip initialization" -checks.
- I was negatively surprised by this issue, that almost caused me a catastrophe. Luckily we caught it in testing before deploying.

**Comment by lukejagodzinski** [comment]
1. I will just add a disclaimer in docs
2. It was working that way in v1 and it caused even more problems. Documents should be as dumb as it's possible. All the magic should only happen when you perform operation like save or validation.

Yes I will introduce global setting.

I encourage you to use `meteorMethods` feature in Astronomy, if you haven't used it  before. It's like Meteor methods but from the level of Astronomy. You can provide security in more granular way (per method). And using methods is just recommended by MDG way of performing operations.

**Comment by arggh** [comment]
`I encourage you to use meteorMethods feature in Astronomy, if you haven't used it before.`

I didn't quite grasp what are the main benefits over using normal Meteor methods, except that you can call `doc.methodName(params)` instead of `method.call(params)` ?

**Comment by lukejagodzinski** [comment]
Benefit is just cleaner code and that you keep your methods next to the model. I don't actually understand why you don't like regular Meteor methods and you've switched to using Astronomy events. Astronomy events are great for small apps or models where you only update entire documents. It's similar to allow/deny in Meteor. However for bigger apps and more complicated models it's more reliable to use meteor methods. MDG recommend it and I recommend it in Astronomy docs.

**Comment by arggh** [comment]
I had a few reasons, but I might still have to eat it up and change direction. 

Reasoning: 

My Classes are very similar in certain ways, so that I can very easily authenticate and authorize operations with events.

```
secured: false,
events: {
   beforeInsert: [authenticate, setOwner],
   beforeUpdate: [authorize],
   beforeRemove: [authorize]
}
```

I also have lots of different places where updates occur, sometimes on all fields, sometimes on just one field, sometimes two fields. And there can be over 15 fields per Class.

So instead of writing lots of similar methods for updating different fields, I could just make the update from client like so

```
// save a particular field
doc.save({ fields: [ 'name' ] }, displayError);
```

or 

```
// save all fields
doc.save(displayError);
```

I thought setting up Astronomy's event system and enabling "client side"-updates would save me heaps of time and boilerplate code. **And it did**, except for these few issues I've ran into.

If you have any suggestions how I could prevent writing so much boilerplate and repetitive code with Meteor methods or Astronomy's meteorMethods, I'm all ears. It's becoming quite complex to evaluate the benefits of different approaches, not to mention mixing them up!

**Comment by arggh** [comment]
If you have any suggestions how I could prevent writing so much boilerplate and repetitive code with Meteor methods or Astronomy's meteorMethods, I'm all ears. It's becoming quite complex to evaluate the benefits of different approaches, not to mention mixing them up!

**Comment by lukejagodzinski** [comment]
Ok in your situation in deed it's very handy to use events, so I would stick to it. So I will just introduce global setting for `defaults` and you're good to go.

**Comment by arggh** [comment]
I can see that using Astronomy's `meteorMethods`, I can indeed skip some hoops compared to regular methods or validated methods:

```
// Client:
Meteor.call('updateTitle', {docId: id, title: newTitle}, handleResponse);

// Methods
Meteor.methods({
  updateTitle({docId, title}) {
    check(docId);
    check(newTitle);
    const doc = Document.findOne(docId);
    if (!doc.editableBy(this.userId) throw new Meteor.Error('unauthorized');
    doc.title = title;
    return doc.save();
  }
```

Versus:

```
// Client:
doc.changeTitle(newTitle, handleResponse);

// Class def:
...
meteorMethods: {
   changeTitle(title) {
     if (!this.editableBy(Meteor.userId()) throw new Meteor.Error('unauthorized');
     this.title = title;
     return this.save();
   }
}
```

I haven't yet figured out how to implement authentication/authorization when using `meteorMethod`s as easily as with events. When mixing in the need to do updates from server code (for example, creating documents for a new user, triggered by account creation), it gets tricky.

I would love to figure out:

- Clean and well organized code with meteorMethods (I did bump into few problems when refactoring certain logic into events, since the old values are not availble in `after*`-hooks)
- Easily repeatable, reusable way of declaring authentication and authorization rules (such as event hooks are for me now)
- Possibility to distinguish trusted server side actions from client-originating calls, so that I can make changes to documents from server side code without authentication errors.

Currently with this events system, for example when I send a welcome message to my users, I can just create the message on the server automatically, pre-populate the sender information that would normally be populated in the `beforeInsert`, and then in the hook I check `if (e.trusted && message.hasValidSenderData()) return;` and it just works, the rest of the process is handled by other hooks, such as updating conversation's metadata (excerpt, last message date etc.).

I'm really trying to make most out of Astronomy, since otherwise I have a lot of code to write!

**Comment by lukejagodzinski** [comment]
You know both events and methods have its pros and cons. I will be preparing video tutorials soon and I hope to provide as much information about Astronomy as possible. I will try to explain all the use cases.

For now, it's just developer's responsibility to find his/her own way of doing it the best way. Everyone has different style of programming and Astronomy does not force developer to use my way of authenticating requests.

If it goes about authentication, I'm lately working with Serverless and AWS lambda functions, where I can attach authorizer method to each "method". I'm thinking about similar feature in Astronomy where I would have one entry point for authorizing meteor methods.

**Comment by arggh** [comment]
I think for now I'll settle in a hybrid solution, keeping the more complicated operations in methods and use Astronomy's events and client-side-save's for most of the bulk stuff.

I'd be interested to hear those ideas on method authorization when your thoughts progress and contribute if I can.

My initial thought was to include a similar flow to `meteorMethods` as what can be found in `validated-method`, where the method has a `validate` and `run` parts and extendability via mixins, so you can have "ensureLoggedInMixin" etc.

So, in Astronomy, it could be like:

```
...
meteorMethods: {
   rename: {
     authorize: [isOwner, hasVerifiedEmail],
     run(name) {
        this.name = name;
        this.save();
     }
  }
}
```

or

```
meteorMethods: {
   changeEmail: {
     mixin: [authenticate, showSuccessNotificationOnComplete, myCustomErrorLogger],
     run(email) {
        this.primaryEmail = email
        this.save();
     }
  }
}
```

Anyway, Merry Christmas and thanks for an awesome package 👍

**Comment by lukejagodzinski** [comment]
I like this idea, I will probably implement something like that. I will get back to it after Christmas :)

Thanks and best Christmas wishes for you too :)

**Comment by davidsavoie1** [comment]
Hey @jagi and @arggh thanks for this really interesting conversation! I really liked to get both your viewpoints on how to handle document updates via events vs meteorMethods. Very insightful! Any development in this matter, anyway?

**Comment by lukejagodzinski** [comment]
You should use Meteor method whenever it's possible. The documentation describes that using events is like using allow/deny rules in pure Meteor. So if you have any doubts, then just use meteor Methods.
