### ISSUE TITLE
Need to disable errors when I prevent remove or save operations in Astronomy

### ISSUE THREAD

**Issue by luzlab** [jagi/meteor-astronomy#573]
Hi,

I'm writing a behavior that commits all `save` and `remove` operations to a broker (kafka in our case). When those methods are called, the behavior does a Meteor.call to generate the appropriate message. A separate consumer process listens for those messages and modifies Mongo appropriately.

When I `preventDefault` in beforeSave or beforeRemove, Astronomy throws an error. There's 'cancelable' property (set to true) on these events, but the error is thrown regardless. I would think if an event can be cancelled - no error should be thrown if it's cancelled...

In the short term, Is there a way to catch that error from my behavior? If not, what's the best way to make this error configurable? I don't mind putting together a PR if you'd like.

**Comment by lukejagodzinski** [comment]
Hi,

`preventDefault` just throws an error that an event was prevented. You can just catch this error.

```js
try {
  doc.save();
}
catch(e) {}
```

Or if you're using callback function:

```js
doc.save((err, result) => {});
```

**Comment by luzlab** [comment]
Thanks for the quick response!

So I've used both of these methods during development, but they require the app developer to change the way they use Astronomy. We have some code already written on top of Astronomy, and none of it has either try/catch blocks wrapping saves and removes or passes in an empty callback.

What I'm asking for is a way to write my behavior in a way that's backwards compatible with our existing code. I could do it by forking Astronomy (yuck) and just changing a couple of lines of code, but my preference is to write a behavior that I can publish on Atmosphere and share with the rest of the community as well (and I'm pretty sure most folks don't use try/catch blocks or pass in callbacks...).

Thanks

**Comment by lukejagodzinski** [comment]
In fact actually most developers use try/catch block or callbacks as it's the only way how you can use Astronomy. It's well documented. You can probably try/catch in behavior and expose some API that will just return appropriate value. Everything depends on how behavior works. And you're description without code doesn't tell me much.
