### ISSUE TITLE
Working with nested documents

### ISSUE THREAD

**Issue by manuelro** [jagi/meteor-astronomy#574]
I have been using Astronomy for Meteor and I'm loving it so far. But I'm also having some issues while working with nested documents. Consider the code below: 

**The Model**
```javascript
Model = Basic.inherit({
  name: 'Model',
  collection: Models,
  fields: {
    slides: {
      type: [Slide],
      default: function() {
        return [];
      }
    }
  }
});
```

**The Meteor Method**
```javascript
'models.addSlide'(modelId, slide){
    let model = Model.findOne({ _id: modelId });

    protector.call(this, { userId: model.userId }); // Ignore this
    
    model.slides.push(slide);
    model.save();
  },
```

If I treat the nested array as a plain-old JS array everything works just fine, but I was wondering if there is an API to treat it as a MongoDB documents collection (with filtering, etc.), or if I'll have to implement the filters by myself.

I haven't seen anything like this in the Astronomy documentation. Any help would be greatly appreciated.

**Comment by lukejagodzinski** [comment]
In Astronomy there is no API/feature that would allow treating nested documents as documents stored in external collection. Maybe in the future there will be a module for relations. For now if you want to have such a relation and filtering you have to implement it by yourself or externalise slides to separate collection and store only slides ids in the `Model`.

**Comment by manuelro** [comment]
Yes. I noticed that already. The native array API (or custom filters) is the way to go. Thank you for replying.
