### ISSUE TITLE
Cannot recognize Floating point as Number

### ISSUE THREAD

**Issue by skynightz93** [jagi/meteor-astronomy#575]
Hi, i dont know if it is related to MongoDB or your package, but as far as i know, your package cannot recognize float number as Number type although actually in javascript, float is recognize as Number. Right now, my float number such as sell price, currency are being saved as String because everytime i want to do price.save() (or this.save() in meteorMethods), it will give error price.sellPrice are required. Thanks.

**Comment by lukejagodzinski** [comment]
Post the code but you're probably not casting values coming from the form.

```js
price.set('sellPrice', formField.value, {cast: true});
price.save();
```

**Comment by skynightz93** [comment]
i use cast in Class create as your example 

```
fields: {
    price: {
      type: Number,
      cast(value) {
        return value;
      }
    }
  }
```

I already delete the code but basically this is what im doing. And then, when im still cannot cast the value, i did like your recommendation, but still the value cannot being save. i will try to post my code after office. Thanks.

**Comment by lukejagodzinski** [comment]
You're cast code doesn't do anything, it just passes value instead casting it. Nowhere in docs I gave such an example.  Cast function for a field is a way of manually cast values. In your situation you don't need custom casting function so yours field's definition should be:

```js
fields: {
  price: {
    type: Number
  }
}
```

and when setting fields value you should:

```js
doc.set('price', formField.value, {cast: true});
doc.save();
```

**Comment by skynightz93** [comment]
Hi i try to done it again and it is working.

**Comment by a4xrbj1** [comment]
We have the same problem, both within our code:

`return Gedmatches.insert({ kit1, kit2, totalCm, created, notSharing: true });`

and when using MongoDb insert directly:

`db.gedmatches.insert({ kit1: 'SyVRzmvn4f', kit2: 'Syfq7mD3Nz', created: new Date(), updatedAt: new Date(), totalCm: 7.32, HIR: 1 })`

In both cases it changes the field value to `7` in the doc instead of 7.32

There must be an easier way to allow floating point numbers!
