### ISSUE TITLE
Publish with composite - Weird behavior

### ISSUE THREAD

**Issue by RemyLespagnol** [jagi/meteor-astronomy#576]
Hi @jagi,

I found a strange bug with the publish-composite package.
https://github.com/englue/meteor-publish-composite/issues/94

I find a solution, if I use the default collection : 
`const _artworks = new Mongo.Collection('artworks');`
`_artworkFavorites = new Mongo.Collection('artwork_favorites');`

So the code is : 

```
Meteor.publishComposite('artwork_favorites.ofUser', function (userId, limit) {
        let favs = null;
        return {
            find: function () {
                const selector = {
                    user: userId
                };
                const options = {
                    limit: limit || 10,
                    fields: {
                        artwork: 1
                    }
                }
                favs = _artworkFavorites.find(selector, options);
                return favs;
            },
            children: [
                {
                    find: function (fav) {
                        const options = {
                            limit: limit || 10,
                            fields: {
                                image: 1,
                                title: 1,
                                year: 1,
                                slug: 1,
                                createdAt: 1,
                                owner : 1
                            },
                            sort: {
                                createdAt: -1
                            }
                        }
                        return _artworks.find({
                            _id: fav.artwork
                        }, options)
                    }
                }
            ]
        }
    });

```

The bug disappear.

Why ? Have you got some idea ?

Thanks :+1:

**Comment by lukejagodzinski** [comment]
How does it relate to Astronomy?

**Comment by RemyLespagnol** [comment]
Hi @jagi,

Because when I use my variables I have : 

```
export const _artworks = new Mongo.Collection('artworks');

export const Artworks = Class.create({
    name: 'Artworks',
    collection: _artworks,
    fields: {
    .....
}

```

With Astronomy, we need to use the Collection Artworks and not _artworks in our publication, don't we ?

But when I use "your collection" in my publish-composite, it doesn't work well.
Use the "meteor/mongo collection" works well.

So I suppose it's related to your package. The workaround is to use the meteor collection in the publish with composition. But it is the good way ?

Thanks your reply :+1:

**Comment by lukejagodzinski** [comment]
Ok, so you can use pure Mongo collections for that purpose. I would rather say that it's a bug in publish with composite because itsit's probably doesn't take transformation function into account. If you're not using behaviors like soft delete that are modifying query then you're good to go with pure Mongo collections.

**Comment by RemyLespagnol** [comment]
OK thanks for your help @jagi.
The repo of publish-composite sleep during many month, so I thought it was a good idea to open an issue here.

And thanks for Astronomy !

**Comment by lukejagodzinski** [comment]
No problem :-)
