### ISSUE TITLE
Error when using Meteor.userId() in 'fields.[someField].default'

### ISSUE THREAD

**Issue by skynightz93** [jagi/meteor-astronomy#577]
Hi, Actually i follow this example to do something like this one. 

```
/**
     * Users who are interested in this conversation.
     **/
    participants: {
      type: [Participant],
      default () {
        if (Meteor.userId()) {
          return [
            new Participant({
              userId: Meteor.userId()
            })
          ];
        }
        else {
          return [];
        }
      }
    }
  },
```

This is my code that run on server:

```
ProductType.extend({
    fields: {
        totalTransaction: {
            type: Number,
            default: function() {
                if(Meteor.userId()) {
                     let id = Meteor.userId(); 
                     let user = User.findOne(id)
                     return Transaction.find({productTypeId: this._id, branchId: user.branchId}).count();

                } 
                return 0;
            },
        }
    }
});
```

The reason i do like this on server but not in client because i am not going to load all of transactions to the client because it will take time just to load for displaying the total of transaction. Actually i can get the dummy data means that it will not give any problem to use architecture like this (Actually i am quite suprise that i can get the data like this). However, the problem here is it cannot get 
Meteor.userId() and here is the error in console.

```
I20170101-12:31:40.180(8)? Exception in queued task: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20170101-12:31:40.181(8)?     at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
I20170101-12:31:40.181(8)?     at Object.Meteor.userId (packages/accounts-base/accounts_common.js:252:19)
I20170101-12:31:40.182(8)?     at ScalarField._default [as default] (server/model/Product.js:83:28)
I20170101-12:31:40.182(8)?     at ScalarField.getDefault (packages/jagi:astronomy/lib/modules/fields/Field.js:22:9)
I20170101-12:31:40.182(8)?     at packages/jagi:astronomy/lib/modules/fields/utils/set_one.js:47:28
I20170101-12:31:40.183(8)?     at traverse (packages/jagi:astronomy/lib/modules/fields/utils/traverse.js:24:12)
I20170101-12:31:40.183(8)?     at setOne (packages/jagi:astronomy/lib/modules/fields/utils/set_one.js:21:10)
I20170101-12:31:40.183(8)?     at Class.set (packages/jagi:astronomy/lib/modules/fields/class_prototype_methods/set.js:56:7)
I20170101-12:31:40.184(8)?     at packages/jagi:astronomy/lib/core/class.js:89:11
I20170101-12:31:40.184(8)?     at arrayEach (/home/nizul/.meteor/packages/jagi_astronomy/.2.3.11.1p5jbt0++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:537:11)
I20170101-12:31:40.190(8)? Exception in queued task: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20170101-12:31:40.190(8)?     at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
I20170101-12:31:40.191(8)?     at Object.Meteor.userId (packages/accounts-base/accounts_common.js:252:19)
I20170101-12:31:40.191(8)?     at ScalarField._default [as default] (server/model/Product.js:83:28)
I20170101-12:31:40.191(8)?     at ScalarField.getDefault (packages/jagi:astronomy/lib/modules/fields/Field.js:22:9)
I20170101-12:31:40.192(8)?     at packages/jagi:astronomy/lib/modules/fields/utils/set_one.js:47:28
I20170101-12:31:40.192(8)?     at traverse (packages/jagi:astronomy/lib/modules/fields/utils/traverse.js:24:12)
I20170101-12:31:40.193(8)?     at setOne (packages/jagi:astronomy/lib/modules/fields/utils/set_one.js:21:10)
I20170101-12:31:40.193(8)?     at Class.set (packages/jagi:astronomy/lib/modules/fields/class_prototype_methods/set.js:56:7)
I20170101-12:31:40.194(8)?     at packages/jagi:astronomy/lib/core/class.js:89:11
I20170101-12:31:40.194(8)?     at arrayEach (/home/nizul/.meteor/packages/jagi_astronomy/.2.3.11.1p5jbt0++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:537:11)
```

**Comment by skynightz93** [comment]
Nevermind, i found the right solution for this one. Just invoke extend code in publish function so that i can use `this.userId` although this solution is a little bit hacky

**Comment by lukejagodzinski** [comment]
There was an issue on GH in this repository about Meteor.userId and possible solutions. Just search for it

**Comment by andrewlorenz** [comment]
there is a problem with the documentation, which shows the use of Meteor.userId() in this very way.  As it doesn't work, the documentation should be fixed!  Its August 2018 and the documentation still shows the same code as above that fails

**Comment by lukejagodzinski** [comment]
It works properly. You're probably doing something wrong or using some older Meteor version. If you're invoking it on the server then it's normal thing. Meteor doesn't know what user ID you're referring to. You can't just use Meteor.userId wherever you want. On the client it will work as it can identify user. On the server the only way to identify user is to run code in the method or publication.

**Comment by andrewlorenz** [comment]
hi Luke, In your documentation, you show in 2 places the use of Meteor.userId() in defaults for an Astronomy class, here is one such example:
```
const Conversation = Class.create({
  name: 'Conversation',
  collection: new Mongo.Collection('conversations'),
  behaviors: ['timestamp'],
  fields: {
    /**
     * The userId of the user who created the conversation, or 'SYSTEM'
     * if created by the app.
     **/
    ownerId: {
      type: String,
      default () {
        return Meteor.userId() || 'SYSTEM';
      },
```
I personally can't get this sort of default assignment to work, because it fails server-side with "Error: Meteor.userId can only be invoked in method calls or publications." .  However, by trial and error (using suggestions from you and others in various GH issues), I have got this pattern working:
```
const StandardStatus = Class.create({
  name: 'StandardStatus',
  fields: {
    userId: {
      type: String,
      optional: true,
    },
  },
  events: {
    beforeSave(e) {
      const doc = e.currentTarget;
      doc.userId = Meteor.userId();
    },
  },
});
```
In the event handlers, the Meteor context appears valid and .userId() is correct on the server
ps I am using the latest version of Meteor (1.7.0.4 to be precise)

**Comment by lukejagodzinski** [comment]
@andrewlorenz events are always run in the Meteor methods created by Astronomy. There are four Meteor methods created by Astronomy:
`/Astronomy/insert`
`/Astronomy/update`
`/Astronomy/upsert`
`/Astronomy/remove`
When you call `doc.save()` or `doc.remove()` the appropriate Meteor method will be called. So if you have any events like `beforeSave`, `beforeUpdate` etc. then all these event will be run in the method context so, the `Meteor.userId()` call will work.

However, if you're trying to use the `Meteor.userId()` line as the default you're responsible for making sure that this function is available. When it won't work? For example if you're trying to create a new document in the startup method:
```js
Meteor.startup(function() {
  var doc = new Doc(); // Where userId's default is Meteor.userId()
});
```
In such case, Meteor doesn't know what to return from the `Meteor.userId()` call. It's impossible as it can't correlate it with any user. It's just server = no user. Call was initiated by server and not client side user. So in this case you should avoid using `Meteor.userId()` in defaults or just put it in the try catch block, so it will not complain but it will also not set any value:
```js
userId: {
  default() {
    try {
      return Meteor.userId();
    } catch(error) {}
  }
}
```
