### ISSUE TITLE
Need to have custom label for error rendering

### ISSUE THREAD

**Issue by skynightz93** [jagi/meteor-astronomy#578]
Hi, I try to look for custom label function for error reason will look human read text. For now, when i do not input required input, the error receive will look like this 

`"firstname" is required`

It is pretty cool if we can print like this:

`First name is required`

Or do you have any recommendation? Maybe, what I actually mean is we can create Class like this

```
Class.create({
    fields: {
        firstname: {
             type: String,
             label: "First name",
        }
    }
});
```

**Comment by jhuenges** [comment]
Have you tried this: http://jagi.github.io/meteor-astronomy/#generating-errors

Follow-up question for @jagi 
Do validators like `required` also allow a `resolveError`-function?

**Comment by lukejagodzinski** [comment]
@nizulzaim @jhuenges in both cases you have to use class level `resolveError` function, which I forgot to describe in docs. Here is an example how to use it:

```js
const messages = {
  'user.firstName.required': `Don't forget about your name!`,
  'user.firstName.minLength': `Doesn't your name too short?`
};

const User = Class.create({
  name: 'User',
  /* ... */
  fields: {
    firstName: {
      type: String
      validators: [{
        type: 'minLength',
        param: 3
      }]
    }
  },
  resolveError({ nestedName, validator }) {
    return messages[`user.${nestedName}.${validator}`];
  }
});
```

I will add proper section to the documentation. However, this problem was already discussed on this GH page, so always remember to check out closed issues :)

**Comment by skynightz93** [comment]
There are a lot of close issue (500++) to look and not all of title will be the same as what is in my mind. Yeah. This is actually i wanted where we can get the custom label. However, it is not become more easy if we can set label for each field that we create so that we can just print out like i said before? Also can you link to me where is the closed issue so that i can read your discussion? 

My recommendation here are based on SimpleSchema format. And that's why i ask you here. Because for my understanding, it is possible to print like this without creating additional code and just add "label":

```
Title is required
Author is required
Brief summary is required
```

```
// Define the schema
BookSchema = new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  author: {
    type: String,
    label: "Author"
  },
  copies: {
    type: Number,
    label: "Number of copies",
    min: 0
  },
  lastCheckedOut: {
    type: Date,
    label: "Last date this book was checked out",
    optional: true
  },
  summary: {
    type: String,
    label: "Brief summary",
    optional: true,
    max: 1000
  }
});
```

It is recommendation not a question at all. And sorry if you think my issue is annoyed you because i just hope I can help you from my point of view. Sorry again.

**Comment by lukejagodzinski** [comment]
I'm currently not able to check closed issues, you have to do it by yourself. The reason why I didn't introduce labels is that labels are not part of schema, it's more part of the forms library. And we have to distinguish that. Maybe if someone would create forms package for astronomy then it would use labels. However, I'm not going to introduce labels.

No problem, suggestions are always welcome.
