### ISSUE TITLE
Deprecation warning breaks meteor app in IE11 and Edge

### ISSUE THREAD

**Issue by smooth-operator** [jagi/meteor-astronomy#579]
Hello,
After updating astronomy i got a deprecation warning that methods have been renamed to helpers. I ignored it for a while, but i found out that the the meteor app won't load in IE11 and Edge with the following error: SCRIPT65535: Invalid calling object, jagi_astronomy.js (1099,3) which is this call warn('Deprecation warning: ' + message); If i have the dev tools open, everything works ok, so i guess it has something to do with how and when IE creates the console object. After renaming methods to helpers the warning disappeared and everything went back to normal. I saw that there is a check if console.warn exists but this seems to fail on ie, i'll see if i can find out why and come up with a pull request.

P.S. Thanks for a great package!

**Comment by lukejagodzinski** [comment]
Thanks for informing about that. I will have to introduce the console variable check.

**Comment by lukejagodzinski** [comment]
Fixed! Fix will appear in the next bug fix version, later today.
