### ISSUE TITLE
Question about bulk updates

### ISSUE THREAD

**Issue by serkandurusoy** [jagi/meteor-astronomy#58]
Let's say I want to increment vote count on all documents on a Posts collection.

How do I do that?

a) Iterate over the cursor 

    Posts.find().forEach(function(Post) {
      // Post is an Astro.Class, right?
      Post.voteUp();
      Post.save();
    })

b) Directly update the Posts collection

    Posts.update({}, {$inc: {voteCount: 1}}, {multi: true});

c) Some other way?

**Comment by jagi** [comment]
Yes you would need to iterate over the cursor and save each individual post. It's not super efficient.
So, it's why I want to execute events and all model logic also on the level of the collection when you are using plain collection methods like `Posts.update({}, {$inc: {voteCount: 1}}, {multi: true});` It will be possible in the next Astronomy release.

**Comment by serkandurusoy** [comment]
Hmm, when are you planning this release for?

**Comment by jagi** [comment]
Probably it will appear with the next release

**Comment by serkandurusoy** [comment]
Well, that's what I meant, the (targeted) time of your next release :)

**Comment by bhishp** [comment]
Hi. I'm wondering about the same but for multi-inserts?

With Mongo we can do like `collection.insert(arrayOfDocuments)`

In astronomy I would like to do the same (bulk insert seems like it would be more efficient than iterating over a large array and creating several atro docs).

I have something like:

```
  const objectsToInsert = [{
    prl_lng_id: '123',
    prl_prc_id: '321',
  }, {
    prl_lng_id: 'abc',
    prl_prc_id: 'cba',
  }, {
    prl_lng_id: '789',
    prl_prc_id: '987',
  }];
ThisAstronomyModel.insert(langMapObjs);
```

The above doesn't work (it thinks I am trying to insert a single document and see an array - so the Model validation complains)

I have even tried with `ThisAstronomyModel.insert(langMapObjs, { multi: true });` but I get an exception: `Exception while invoking method '/Astronomy/execute' TypeError: callback is not a function`.

**Comment by lukejagodzinski** [comment]
Actually, you can't either do it with pure Meteor's MongoDB collections. When you do `Collection.insert(arrayOfDocs)` it will convert the array to object, so you're gonna end up with an object having keys being indexes of the array. I don't know why they made it that way but it was probably some trade-off between simplicity and overcomplication of their code base which would be later hard to maintain. As I'm focusing more on GraphQL and Apollo right now, I will probably prepare Astronomy version for Apollo. However, I'm still looking for the best way of integrating it. I wouldn't want to tie it to GraphQL to much. I did it previously with too much integration with Meteor and that's causes some problems. So right now I'm thinking about making it more just like regular model layer for any database with some drivers for each of the most popular once. And creating some additional package for Apollo that would integrate with both server and client.
