### ISSUE TITLE
Question: how to access parent in nested class helper

### ISSUE THREAD

**Issue by Lukasvo** [jagi/meteor-astronomy#583]
Can I access the parent doc from a helper of a nested class?

Example
```
const Reservation = Class.create(
	{
		name: 'Reservation',
		collection: new Mongo.Collection('reservations'),
		fields: {
			reservationTypeId: {
				type: String
			},
			invoices: {
				type: [Invoice] 
			}
		},
	});
```
```
const Invoice = Class.create(
	{
		name: 'Invoice',
		fields: {
			code: {
				type: String
			},
		},
		helpers: {
			price() {
				// How to access parent attribute for db query?
				return Price.find({ code: code, reservationTypeId: ... });
			}
		}
	});
```

I need to perform a database query, but only in some children classes, so adding price as a transient field is not really an option for performance reasons. I could add the reservationTypeId to the Invoice class as a transient field, but is there also a better way?

Thank you!

**Comment by lukejagodzinski** [comment]
No you can't access parent class from children. You have to implement it yourself in a way that fits your needs best.

**Comment by Lukasvo** [comment]
Ok, I'll add a transient field to the child classes with events then, since accessing the parent object is possible there. Other suggestions are welcome. Thanks!
