### ISSUE TITLE
No reactivity if I call .set()?

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#584]
Hey,
I'm just wondering if this is a missing feature since we moved over to React and using createContainer of Meteor.

I have the following component:

```
class ProjectsEdit extends ProjectsAdd {

    constructor(props) {
        super(props);

    }


    setValue(e) {
        e.preventDefault();
        this.props.project.set(e.target.id, e.target.value);

    };



    render() {

        return <div>
            {this.renderForm()}
        </div>

    }
}



let container = createContainer((props) => {


    const project = Project.findOne({_id:props.params.id}) || new Project();

    return {
        project
    };
},ProjectsEdit);
```

In this case I set all changes to the Astronomy object, hoping that it will reflect those changes (reactivity). But there is no rerender, so I guess calling ".set()" isn't reactive within Tracker?

**Comment by lukejagodzinski** [comment]
No astronomy objects are not reactive. You have to store astronomy object inside `ReactiveVar` and any changes to it will be reflected in React.
