### ISSUE TITLE
map without losing class props/methods?

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#585]
When mapping in this manner:

```js
const items = Item.find().fetch().map(item => ({
  ...item,
  extra: 123,
}));
```

The helpers of `Item` are lost. Is there a way to preserve them somehow?

**Comment by ffxsam** [comment]
The only workaround I've found is to explicitly re-create the methods:

```js
      return {
        ...record,
        getAudits: record.getAudits,
        getCoverImageUrl: record.getCoverImageUrl,
        lastAuditDate: audit.createdAt,
      }
```

**Comment by lukejagodzinski** [comment]
You're destructuring astronomy object and constructing plain JS object so that's normal behavior. You can't do that if you want to preserve astronomy functionality. However if you really want to do that and construct JS object with all Item's methods, you can also do something like this:

```js
const items = Item.find().fetch().forEach((item) => {
  _.extend(item, {
    extra: 123
  });
});
```

or

```js
const items = Item.find().fetch().map(item => ({
  ...item,
  ...Item.getHelpers(),
  extra: 123
}));
```

**Comment by ffxsam** [comment]
Ahh, perfect! That's even better than my messy solution, thanks! 👍
