### ISSUE TITLE
The "type" keyword shouldn't be reserved

### ISSUE THREAD

**Issue by manuelro** [jagi/meteor-astronomy#589]
The server is returning an error while using ENUMS. When I try to access `MyEnum.FOO` it just throws an `undefined` error. I `console.log` the class and it was printed out, the importing is also fine.

**The ENUM**
```
import { Enum } from 'meteor/jagi:astronomy';

const PlaceholderTypes = Enum.create({
  name: 'PlaceholderTypes',
  identifiers: { NORMAL: 1, SYNC: 2 }
});

module.exports = {
  PlaceholderTypes
}
```

**The implementation** (with the imported class)
```
Placeholder = Class.create({
  name: 'Placeholder',
  fields: {
    // ... 
    type: {
      type: PlaceholderTypes,
      default () {
        return PlaceholderTypes.SYNC
      }
    }
  },
});
```

**The error**
```
TypeError: ["Placeholder" class]["fields" property]["type" field] Type does not exist
```

Any help would be much appreciated.

**Comment by lukejagodzinski** [comment]
Maybe it's has something to do with the field name which is `type`. I don't think that I reserved this keyword but it might be a bug. Please check out if changing field's name helped. If not please create simple reproduction with what you've posted here and I will take a look at it.

**Comment by manuelro** [comment]
Hey, Jagi. You were right. The `type: {...}` keyword was reserved (or at least not processed nicely). This would be a nice-to-have feature if we can use type as a field name in future releases. Thank you for taking the time to look into it.

**Comment by lukejagodzinski** [comment]
Ok, so I will probably have to fix it because it shouldn't be reserved. In fact the `type` field used for inheritance is only a default value and any field can be used for inheritance. So there is no need for making it reserved. So I will fix it in the next bugfix version.

**Comment by lukejagodzinski** [comment]
I've been trying to solve the problem and I've noticed that the `type` keyword is not reserved. Actually you have a bug in your code in type exports. It should be:

```js
import { Enum } from 'meteor/jagi:astronomy';

const PlaceholderTypes = Enum.create({
  name: 'PlaceholderTypes',
  identifiers: { NORMAL: 1, SYNC: 2 }
});

export default PlaceholderTypes;
```

and later in the class definition:

```js
import PlaceholderTypes from './path/to/type/file/PlaceholderTypes';

// Class definition goes here...
```
