### ISSUE TITLE
mongoimport of .json file with arrays -- _id issues

### ISSUE THREAD

**Issue by waxhell** [jagi/meteor-astronomy#59]
The following code works fine:
```
TestCollections = new Mongo.Collection('testcollection');
TestCollection = Astro.Class({
    name: 'TestCollection',
    collection: TestCollections,
    fields: {
      name: 'string',
      testarray: 'array',
      'testarray.$': 'number',
    }
})

var testitem = new TestCollection({
  name: 'testincode',
  testarray: [1,2,3,4]
});
testitem.save()
```
TestCollection contains the new item (with name 'testincode'). However, if I import in a json using the following mongoimport command:
```
mongoimport -h localhost:3001 --db meteor --collection testcollection --type json --jsonArray --file test.json
```
where test.json contains:
```
[{"testarray":[12,35,82,12],"name":"test3"}]
```
I get the following error in my meteor log:
I20150803-17:04:57.170(-7)? Exception in queued task: Error: transformed document can't have different _id
I20150803-17:04:57.171(-7)?     at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
I20150803-17:04:57.171(-7)?     at wrapped (packages/minimongo/wrap_transform.js:37:1)
I20150803-17:04:57.171(-7)?     at self.applyChange.added (packages/minimongo/observe.js:53:1)
I20150803-17:04:57.171(-7)?     at packages/mongo/observe_multiplex.js:183:1I20150803-17:04:57.171(-7)?     at Array.forEach (native)
I20150803-17:04:57.172(-7)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150803-17:04:57.172(-7)?     at packages/meteor/fiber_helpers.js:125:1I20150803-17:04:57.172(-7)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20150803-17:04:57.172(-7)?     at Object.task (packages/mongo/observe_multiplex.js:177:1)

However, looking at the mongo db, the import was successful. Each successive restart of meteor, I get the following error:
I20150803-17:09:56.031(-7)? Failed while syncing collections for reason: Error:transformed document can't have different _id

The mongo db contains the following:
```
/* 0 */
{
  "_id" : "JAeedqrohksZ96L53",
  "name" : "testincode",
  "testarray" : [1, 2, 3, 4]
}

/* 1 */
{
  "_id" : ObjectId("55c001a9c6660b9667b5d3c6"),
  "testarray" : [12, 35, 82, 12],
  "name" : "test3"
}
```
This issue does not seem to exist if no arrays are in the json file json import using mongoimport.

**Comment by jagi** [comment]
Hmm I don't see that there is any error coming from astronomy. Are you sure that it isn't caused by something else? If yes, could you provide reproduction repository so I will be able to treat it out.

**Comment by waxhell** [comment]
I built a test project from scratch and I realized it's the combination of astronomy, mongoimport, and houston:admin. It actually occurs with any import, not just the arrays -- likely due to the way that mongoimport populates the _id field with an ObjectId object rather than a string.

```
/* 0 */
{
  "_id" : "Qc54Eao7T59qrXxdx",
  "name" : "test3",
  "testarray" : [12, 13, 14, 15]
}

/* 1 */
{
  "_id" : ObjectId("55c0f2b206ef2cef26ff692c"),
  "name" : "test4"
}
```

This might be more of a houston:admin issue than an astronomy issue, however if I remove the astronomy template, this issue goes away.

I'm filing a bug report with houston:admin as well.

**Comment by jagi** [comment]
You should be able to import documents from other databases by passing JSON to the class constructor.

```js
var doc = new Doc(json);
doc.save();
```

It's a feature implemented in the 1.0.0 RC version https://github.com/jagi/meteor-astronomy/issues/97

**Comment by martunta** [comment]
this also means that new documents in collection can not be created in Meteor Mongo console - they fail to be picked up by Meteor, due to failure in transform with error message mentioned above.

Why did you choose to override default Mongo ObjectId() with own version?

**Comment by jagi** [comment]
I didn't. It's what Meteor is doing. It's using string instead ObjectId.

**Comment by michaelsframe** [comment]
Check out this related issue: https://github.com/strongloop/loopback/issues/274
