### ISSUE TITLE
Meteor method callback not called if Astronomy class is returned

### ISSUE THREAD

**Issue by DavidSichau** [jagi/meteor-astronomy#590]
I have the following method, which works fine if I directly use the Collection.

```
'resumePosition.getLastPostition'(etId) {
            return ResumePosition.getCollection().findOne({
                userId: Meteor.userId(),
                etId,
            });
        },
```
If I change the method like that:
```
'resumePosition.getLastPostition'(etId) {
            return ResumePosition.findOne({
                userId: Meteor.userId(),
                etId,
            });
        },
```
The callback on the client is never called.

Is something missing in my code or what does causes this problem?

Here my Schema
```
import { Mongo } from 'meteor/mongo';
import { Meteor } from 'meteor/meteor';
import { Class } from 'meteor/jagi:astronomy';

const ResumePositionMongo = new Mongo.Collection('resume_position');

const ResumePosition = Class.create({
    name: 'ResumePosition',
    collection: ResumePositionMongo,
    fields: {
        userId: {
            type: String,
            default: () => (Meteor.userId()),
        },
        mdId: {
            type: String,
        },
        etId: {
            type: String,
        },
    },
    indexes: {
        userIdMdId: { // Index name.
            fields: { // List of fields.
                userId: 1,
                etId: 1,
            },
        },
    },
});

export default ResumePosition;
```

**Comment by lukejagodzinski** [comment]
What callback? I don't see any callback in your examples

**Comment by DavidSichau** [comment]
@jagi Sorry the callback on the client call method:

```
Meteor.call('resumePosition.getLastPostition', etId, (error, lastPosition) => {
        console.log(lastPosition);
        console.log(error);
        if (error) {
            onData();
        } else {
            onData(null, { lastPosition });
        }
    });
```
Here the callback is only called if I use findOne on the Collection but not if I call findOne direct on the Astronomy class.

**Comment by lukejagodzinski** [comment]
Ok, so please create reproduction repository co I can clone it and test. It's rather problem with your code because this feature worked. However let's just create reproduction and I will check it out.

**Comment by DavidSichau** [comment]
Here is the repo:

https://github.com/DavidSichau/AstronomyProblem

The problem is in the file https://github.com/DavidSichau/AstronomyProblem/blob/master/server/methods/resume_pos.js
If one there inserts the comment one gets undefined in the callback in the file
https://github.com/DavidSichau/AstronomyProblem/blob/master/client/modules/core/containers/resume_pos.js

Hope this helps.

**Comment by lukejagodzinski** [comment]
It does not look like proper reproduction. Reproduction should be minimal. And there is a lot of unnecessary complexity. However, I've managed to find what's wrong with your code. Please, check your code several times before posting issue here on GH. In the server console there is an error, so your code can't work. You're importing `import {ResumePos} from '/lib/collections';` and later using `ResumePosition.findOne()`. So how do you expect it to work? Replacing it with `ResumePos.findOne()` makes code work.

**Comment by DavidSichau** [comment]
@jagi Sorry for the bad reproduction and sorry for your trouble.

**Comment by lukejagodzinski** [comment]
That's ok :) I get a lot of issues like that because most people don't check their code carefully enough but I can understand that :) If something does not work, the first thing that comes to your mind is that's a problem with a tool I'm using :). I've made this mistake several times :). So don't worry :)
