### ISSUE TITLE
Email Address Validation (Apostrophes)

### ISSUE THREAD

**Issue by samicemalone** [jagi/meteor-astronomy#591]
Hi,

It looks like the email address regex being used for validation, doesn't accept an apostrophe which is a valid character.

Thanks,

Sam

**Comment by lukejagodzinski** [comment]
Hmm you're right. I've checked and many other characters are valid in email address. Do you have any good regular expression that would validate email address correctly?

**Comment by lukejagodzinski** [comment]
Ok I think that this one will solve most of the problems `/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/` I will make a fix.

**Comment by lukejagodzinski** [comment]
Fix will appear in the next bug fix release
