### ISSUE TITLE
Unique validator in v2

### ISSUE THREAD

**Issue by DarthRumata** [jagi/meteor-astronomy#593]
Hello. Is it possible to create something like Validators.unique in API v1?
Now I can't call findOne for current class

```
Validator.create({
  name: 'unique',
  isValid({doc, value, name}) {
    const isExisted = doc.findOne({name: value});
    return !isExisted;
  },
  resolveError({name}) {
    return `Cannot save doc with already existed "${name}"`;
  }
});
```

**Comment by lukejagodzinski** [comment]
Document (`doc`) does not have `findOne` method. Try this:

```js
Validator.create({
  name: 'unique',
  isValid({Class, value, name}) {
    return Class.find({name: value}).count() === 0;
  },
  resolveError({name}) {
    return `Cannot save doc with already existed "${name}"`;
  }
});
```

and if it does not work then this:

```js
Validator.create({
  name: 'unique',
  isValid({doc, value, name}) {
    const Class = doc.constructor;
    return Class.find({name: value}).count() === 0;
  },
  resolveError({name}) {
    return `Cannot save doc with already existed "${name}"`;
  }
});
```

**Comment by DarthRumata** [comment]
Thanks! 
The second approach works fine)

**Comment by davidsavoie1** [comment]
@lukejagodzinski I tried the solution explained here to create a `unique` validator I could use on specific fields. Here's the code:
```js
Validator.create({
  name: 'unique',
  isValid({ doc, value, name }) {
    const selector = objOf(name, value);
    return doc.constructor.find(selector).count() === 0;
  },
  resolveError({ name }) { return `${name} must be unique.`; },
});
```
However, when I execute code on the client which would create a duplicate, no error is thrown. I only receive a console message `Error invoking Method '/Astronomy/execute': code must be unique. [validation-error]` a little later, but no real error I could handle somehow.

So of course, it seems to signify that I don't have sufficient data on the client to validate properly. And indeed, if I add `autopublish` package, I get the expected validation error. However, I can't always subscribe to the entire collection just to do validation on one document! **What would be the best way to handle such a situation?**

Also, where would be the **right place to define such validators?** In a file imported on startup by both client and server?

**Comment by lukejagodzinski** [comment]
@davidsavoie1 hmmm it might be hard to implement such a validator as they work synchronously and in that situation, you would have to call some server method to check uniqueness of the document being inserted. In your situation, the only way of doing it is just validating only on the server.

**Comment by davidsavoie1** [comment]
@lukejagodzinski Yeah, I thought about that yesterday and that's what I'll probably have to do: restrict methods that deal with the must-be-unique prop to server side only with `invocation.isSimulation` or something like that. Thanks anyway!

**Comment by lukejagodzinski** [comment]
You can add server only validators by extending schema on the server:

```js
// server.js
MyClass.extend({
  validators: [
    uniqueFieldName: [{ type: 'unique' }]
  ]
});
```
