### ISSUE TITLE
Encryption of certain fields

### ISSUE THREAD

**Issue by PolGuixe** [jagi/meteor-astronomy#594]
Is it possible to encrypt certain fields with Astronomy? Is there any behaviour available?

**Comment by lukejagodzinski** [comment]
Provide an example of what you want to achieve

**Comment by PolGuixe** [comment]
Something like this:

```js
const Company = Class.create({
  name: 'Company',
  collection: new Mongo.Collection('companies'),
  secured: true,
  fields: {
    name: {
      type: String,
    },
    sensitiveField: { //Field to encrypt in server - On client, it should be decrypted for the ones who have access to it
      type: String, 
    },
  }
})
```

**Comment by lukejagodzinski** [comment]
If you don't want some fields to be visible on the client than just don't publish them, that's it. If you want to achieve something else than describe your problem in more details.

**Comment by PolGuixe** [comment]
Imagine it is a bank account number:
- I want to encrypt it in the DB.
- I want the user -which holds the right permissions- to view it. 
 
This is what I am trying to achieve. It is more clear now? 😉

**Comment by lukejagodzinski** [comment]
This example does not make sense. You still don't want to publish account number without logging in by the user that has permissions to view this account number. So subs/pubs schema works here. I don't see any need to publish encrypted data to the client. Moreover encrypting account number is pointless.

Imagine accounts system in Meteor. Passwords are encrypted and not published to the client. That's all you need.

**Comment by PolGuixe** [comment]
If someone has access to the DB they can read the sensitive fields if they are not encrypted.
The idea is not to hide it against other users -here pub/sub will work-. The goal is to protect the stored data in the DB, without having to encrypt the whole DB.

**Comment by lukejagodzinski** [comment]
So do it the way Meteor accounts system does it. There is no universal way of doing it.

**Comment by martineboh** [comment]
Thanks @jagi for the wonderful astronomy! Here's my question: Can werl define fields with a TTL? I am creating an app and I want some fields to auto delete after sometime from mongo automatically.

**Comment by manuelro** [comment]
@jagi, there can be other scenarios as well. For instance, while storing the api secret of any image hosting provider, we may not want to store it as is, imagine if someone gets a hold of the DB, that person could potentially use the stored information to upload images on behalf of the user with the chance of generating a lot of traffic and money in usage fees for that person.

@PolGuixe, I think this has more to do with an encryption library (I can suggest you [CryptoJS](https://www.npmjs.com/package/crypto-js)), then you will have to encrypt the information right before saving and decrypt it on the server in case you need to use it - just be careful to save the decryption key in the safe environment too, and perhaps having a backup somewhere else, if not, your information will be lost forever.

**Comment by lukejagodzinski** [comment]
@manuelro still this example does not imply any feature that should be added to Astronomy. Everything can be done using existing features. But when somebody has access to you DB, then you're screwed anyway :). So it's more about securing your server and code, so that it's not vulnerable to any attack.
