### ISSUE TITLE
Propagate Meteor method down the inheritance tree even when no collection provided

### ISSUE THREAD

**Issue by manuelro** [jagi/meteor-astronomy#596]
I'm using `astronomy@2.3.12` and tried to use the `meteorMethods` property. Everything works well on the client-side if I use the `[entity].callMethod` but when I try to access the method directly on server-side tests the method is `undefined`.

This happens only if I have class `B` inheriting from class `A` (the class that has the `meteorMethods` attached to it), which I think the child class should also inherit the parent's `meteorMethods` and apply them in a polymorphic way. Is this the case? Is this intended to be some sort of polymorphism applied to JS prototypical inheritance? 

If I declare the `meteorMethods` property directly on the child class, the method is recognized on the server side (without calling `callMethod`). Which means that the parent class `meteorMethods` property is not being propagated down the tree of classes that inherit from a parent. 

# The code

## The parent class
```
Basic = Class.create({
  name: 'Basic',
  fields: {
    userId: String,
    name: { type: String, optional: true },
    description: { type: String, optional: true },
    uuid: { type: String, immutable: true, optional: true },
  },
  behaviors: {
    timestamp: {}
  },
  events: {
    beforeInsert (e){
      let target = e.target;
      target.uuid = uuid.new();
    }
  }
});

if(Meteor.isServer){
  Basic.extend({
    meteorMethods: {
      setName (name) {
        this.name = name;
        return this.save();
      }
    }
  });
}
```

## The child class
```
const Grids = new Mongo.Collection('grids');
Grid = Basic.inherit({
  name: 'Grid',
  collection: Grids,
  fields: {
    cells: { type: [ Cell ], default: () => [] }
  }
});
```

## The test (just to see if the method is being recognized)
```
it('foobar', () => {
    let grid = new Grid({ userId: 'myuserid' });
    grid.save();

    let newGrid = Grid.findOne();
    console.log(newGrid.setName); // This method might have been inherited fom Basic class
})
```

**Comment by manuelro** [comment]
By the way, how would you test that a certain record belongs to a certain user using `userId`? I mean, passing the context to check whether `this.userId` is equal to Meteor's current `userId`.

**Comment by lukejagodzinski** [comment]
Meteor methods are only applied to classes that have assigned collection, so that's why it does not work. It's a limitation that can't be solved in any way. As you may know meteor methods are assigned to connection object. Even when you use `Meteor.methods()` it still assigns methods to the `Meteor.connection` object which is global connection object. But I can't make assumption that this connection object is used with any collection. Because you can provide custom connection object in Collection constructor `new Mongo.Collection('name', {connection})`.

If it goes about the second question I don't know if I understand your problem but you're probably looking for Invocation object about which you can read in documentation: http://jagi.github.io/meteor-astronomy/v2#meteor-methods--220

**Comment by manuelro** [comment]
Makes sense from the current state of Astronomy. However, I'll take a look into the source code for the entity invocation (for creation, reading and destruction). I'm thinking that it may be possible to propagate the parent's `meteorMethods` to the child, at execution time. If I come up with something I'll make a PR for consideration. Thank you for taking the time to answer this, as usual.

**Comment by lukejagodzinski** [comment]
Yes I probably should propagate `meteorMethods` even if there is no collection defined. If you want to handle that I can give you some tips on where to look for it.

**Comment by manuelro** [comment]
Sure, I'm working on a side project right now but I'll be taking a look into this again during next week. Any advice will be welcome.

**Comment by lukejagodzinski** [comment]
Ok I've fixed it. It wasn't so easy as I thought, so it would be hard for you to make that fix. That's why I did it by my self. This fix will appear in the next bug fix version of Astronomy

**Comment by manuelro** [comment]
Awesome! Thanks!

**Comment by lukejagodzinski** [comment]
Feature released with a new version
