### ISSUE TITLE
beforeRemove / afterRemove event and softremove behavior

### ISSUE THREAD

**Issue by Zyets** [jagi/meteor-astronomy#600]
Those events are never triggered while softremove behavior is on.
Is it a bug or am i doing something wrong?

**Comment by lukejagodzinski** [comment]
It's because soft removed documents are not being removed but "soft removed", so `beforeSoftRemove` and `afterSoftRemove` events are triggered. Moreover `before(after)Save` and `before(after)Update` events are triggered where you can also detect if the `removed` field is set or not.

**Comment by Zyets** [comment]
Oh, thanks for such a quick reply))
But that didn't helped me..
Neither beforeSoftRemove nor before Save are not triggered when I do softRemove()

**Comment by lukejagodzinski** [comment]
Show code of your class. Maybe you're doing something wrong

**Comment by Zyets** [comment]
ok, i get it! It works only on server-side...
is there any way to get it work on client?

**Comment by lukejagodzinski** [comment]
It should work on the client too, so as I said you're probably doing something wrong.

**Comment by Zyets** [comment]
omg... i DID something wrong..
i call softRemove through Meteor.methods....
i didnt work on that project for a few weeks, so i simply forgot that moment... sorry for taking your time.

**Comment by lukejagodzinski** [comment]
Ok no problem, good that you found it
