### ISSUE TITLE
Uncaught TypeError: Class is not a constructor

### ISSUE THREAD

**Issue by RWizard** [jagi/meteor-astronomy#604]
Would you like help me with the problem?
In old project, no problem, but in new project, the line on Client with error:
  var doc = new Class(); // Trigger the "fromJSONValue" event handlers.                                                

![2017-04-15 19 39 08](https://cloud.githubusercontent.com/assets/190453/25065188/88b3203a-2213-11e7-88dc-f3dc11b37e5d.JPG)

In new project I can`t install pkg as classic: meteor add ...
I copy astronomy code line from file ./meteor/packages to new project and run app. In server not problem, collections created, insert, update and etc.. In Client - problem.

**Comment by lukejagodzinski** [comment]
Show your code. Without it it's hard to tell

**Comment by eviatarkhen** [comment]
How did you resolved the issue?
Here is the code

`const Organizations = new Mongo.Collection('organizations');
const Organization = Class.create({
  name: 'Organization',
  collection: Organizations,
  fields: {
    name: {
      type: String,
    },
    users: {
      type: [Mongo.ObjectID],
    },
  },
});`
`const add = new ValidatedMethod({
  name: 'admin.organizations.add',
  validate(options) {
    check(options, {
      name: String,
    });
  },
  run({ name }) {
    try {
      const org = new Organization({ name });
      org.save();
      Logger.info(`Organization ${name} added`);
    } catch (exception) {
      Logger.error(`Adding organization failed ${exception}`);
      throw new Meteor.Error(
        'admin.organizations.addOrganization',
        'Adding Organization Failed',
      );
    }
  },
});`

The error is: TypeError: Organization is not a constructor
