### ISSUE TITLE
Index inheritance should not work if the field is a transient field

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#605]
Currently Astronomy will ensureIndex on a field if it uses a type of another Class and is marked as transient, this shouldn't be the case as the field is transient. I remember when we implemented this feature, we missed this edge-case.

cc @jagi

**Comment by lukejagodzinski** [comment]
> Currently Astronomy will ensureIndex on a field if it uses a type of another Class and is marked as transient

Could you give some example? Because from this description I can say for sure that Astronomy by itself does not add indexes to transient fields and classes that are not stored in collections. So you probably used class as a nested field which is not intended to be used in that way.

**Comment by talha-asad** [comment]
If that's the case then we don't need this. I was recalling this from memory, closing.
