### ISSUE TITLE
Inheritance bug

### ISSUE THREAD

**Issue by fahadAziz44** [jagi/meteor-astronomy#606]
Say we have 2 classes: `Animals` and another class `Cats` extending it. We have 2 objects, one of type `Animal` and the other of type `Cat`.

If we fetch objects through Animal Class, with `{children: true}`, which is the default anyway. It returns objects of both classes, which is as expected. However the `type` field is incorrectly set for the `Cat` Object. It is set exactly like the `Animal` object. Isn't this wrong behavior? If not, What is a good programmatic way to dynamically cast it to it's proper Class?

**Comment by bryantbiggs** [comment]
I had a similar question but I was using inheritance instead of extension. However, you can see the outcome here [#540](https://github.com/jagi/meteor-astronomy/issues/540)

Basically start with your base class and then later on down the line you can update the type field to be the child class type: `Animals ==> Cat`

**Comment by fahadAziz44** [comment]
Thanks @bryantbiggs

**Comment by lukejagodzinski** [comment]
In deed it should populate the type property with proper value. I thought that I've fixed it. Are you using the newest version? I will check if this bug still appears, and if it do then I'll fix it.

**Comment by lukejagodzinski** [comment]
@fahadAziz44 it's working properly, what Astronomy version are you using? Please create reproduction repository if you still have this problem.

**Comment by fahadAziz44** [comment]
@jagi I am working on v2.4.3. Actually it was a mistake by my side, I was setting the same `name` field for both Classes.

**Comment by lukejagodzinski** [comment]
@fahadAziz44 ok good to hear that you solved that
