### ISSUE TITLE
Class Inheritence Import/Export

### ISSUE THREAD

**Issue by bryantbiggs** [jagi/meteor-astronomy#608]
Hello Jagi - many thanks for the great library!

I am trying to break up my classes into individual modules but running into some issues. If I place all of my classes that inherit from their parent class(es) in one file, there are no issues. However, if I take my parent and child classes and move them to their own individual files then I am getting an error stating ```TypeError: [childClass].inherit is not a function```

I have made a repro here https://github.com/bryantbiggs/inherit, am I missing something in order to split up classes and import them?

**Comment by skynightz93** [comment]
see my pull request

**Comment by bryantbiggs** [comment]
Thank you @nizulzaim  for catching that! I discovered I had to import the classes on the server as well to make it finally work.
