### ISSUE TITLE
Class method 'validate' doesn't return callback if no errors in model

### ISSUE THREAD

**Issue by DarthRumata** [jagi/meteor-astronomy#609]
```js
this.user.validate({
  stopOnFirstError: false
}, (err) => {
  // some code here
  callback(results, isValid);
});

// user model
const User = Class.create({
  name: 'User',
  fields: {
    fullname: {
      type: String,
      default: '',
      validators: [{
        type: 'minLength',
        param: 3,
        message: 'minLengthError'
      }]
    },
    email: {
      type: String,
      default: '',
      validators: [{
        type: 'email',
        message: 'invalidEmailError'
      }]
    },
    password: {
      type: String,
      default: '',
      validators: [{
        type: 'minLength',
        param: 3,
        message: 'minLengthError'
      }]
    },
    repassword: {
      type: String,
      default: '',
      validators: [{
        type: 'equalToField',
        param: 'password'
      }]
    }
  }
});
```

Meteor throwing error to browser console: "Received error from server:  Parse error".

**Comment by lukejagodzinski** [comment]
I've tested it and it's working properly. You're probably doing something wrong. I see that you're using some `callback` function which is not provided here, so it's hard to tell where a bug is.
When you do something like this it should work:

```js
this.user.validate({
  stopOnFirstError: false
}, (err) => {
  if (err) {
    console.log('There is an error');
  } else {
    console.log('No error');
  }
});
```

If you still having this problem, please create reproduction repository. It always helps find a bug.

**Comment by qbonnard** [comment]
Sorry for unearthing long closed issues, but in case someone ends up here with a mysterious Parse error which ruins everything, the solution is actually : [Class definition has to be available on both client and server. So if you're not doing so, then it may not see the class in some of environments.](https://github.com/jagi/meteor-astronomy/issues/558#issuecomment-264433128)

I was trying to do client-side only validation, so I hadn't imported the Class definition anywhere on the server. I'm brand new to Astronomy, so I hadn't even realised that validate was actually a method method.

Hope that helps someone ;)
