### ISSUE TITLE
Setting Meteor.users schema & methods

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#61]
Are there any special instructions for setting up Meteor.users schema? Does the default schema have to be copied in for it to work normally (meaning with user accounts, etc...)?

Thanks!

**Comment by jagi** [comment]
There is the wiki [page](https://github.com/jagi/meteor-astronomy/wiki/Examples#users-collection) showing example of using Astronomy with `Meteor.users` collection. There will be a little change with nested schemas in the coming release, so examples on that page will get more detailed.

**Comment by JulianKingman** [comment]
Perfect, thanks! I don't know why I didn't find that page.

**Comment by JulianKingman** [comment]
Can you put that snippet in your new shiny documentation?

**Comment by jagi** [comment]
Yes right I will it

**Comment by jagi** [comment]
I will put it here also. There are many possible ways of defining schema for the user however here is a minimal schema. It could be simplified with a lack of UserProfile nested schema but some people may want to be sure about default values in the profile.

```js
UserProfile = Astro.Class({
  name: 'UserProfile',
  fields: {
    /* Any fields you want to be published to the client */
  }
});

User = Astro.Class({
  name: 'User',
  collection: Meteor.users,
  fields: {
    createdAt: 'date',
    emails: {
      type: 'array',
      default: function() {
        return [];
      }
    },
    profile: {
      type: 'object',
      nested: 'UserProfile',
      default: function() {
        return {};
      }
    }
  }
});

if (Meteor.isServer) {
  User.extend({
    fields: {
      services: 'object'
    }
  });
}
```

Of course it could also get a lot more complicated. It could define nested class for email, nested class for all services however as long as Meteor cares about validity of this data as there is no need for checking it again by a developer. I will add it to the docs in a minute.

**Comment by JulianKingman** [comment]
Thanks! It's a snippet that I use often, and the new documentation is a little confusing because it uses a collection called 'users', but would give validation errors with a normal user collection, because of the missing default fields. 
-- 
julian.kingman@gmail.com
Sent with Airmail for iPhone

**Comment by jagi** [comment]
Yes, I agree that it may be confusing. I've just chosen the `User` class because I could show all the features/properties using only one model. Maybe I will add information that it's not for use with the `Meteor.users` collection.
