### ISSUE TITLE
React-Native-Meteor doesn't work with user object

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#612]
Hey @jagi ,
we're using Astronomy within our new Meteor project, which also requires a React Native application. Here we have a problem with the structure of our user object. The problem is, that we don't receive the user object when we publish by the Astronomy class:

    const User = Class.create({
    name: 'User',
    collection: Meteor.users,
    fields: {
        username: {
            type: String
        },
        details: {
            type: UserDetails
        },

        emails: {
            type: [Object],
            default: function () {
                return [];
            }
        },
    }});

Publish:

    return User.find({_id: this.userId}, {fields: {'details': 1}});

The problem is based on the following property:

        details: {
            type: UserDetails
        },

Astronomy transmits it as "Class" to the React Native application, which isn't able to handle (and merge) it. If we change the structure to:

        details: {
            type: Object
        },

everything is working fine. But in this case we would loose the validation structure we have on the server side. Any idea how we could benefit from both? We need the Astronomy object also to fire an event after initialization, so we are not able to publish only by Meteor.users.

**Comment by dnish** [comment]
Currently I found this workaround, I'm just wondering if there is a better alternative?

    events: {
        afterInit(e) {
            const doc = e.target;
            const packageDoc = Packages.findOne({_id:doc.details.packageDetails.packageId});

            if(packageDoc) {
                doc.details.packageDetails.packageDoc = packageDoc;
            }

            doc.details = doc.details.raw(); 


        }
    }

**Comment by lukejagodzinski** [comment]
Yes there is a better way of doing it. You can pass `transform: null` option to the `find` method and it will not transform document into astronomy class instances.

```js
return User.find({_id: this.userId}, {fields: {'details': 1}, transform: null});
```
