### ISSUE TITLE
Fields validation override

### ISSUE THREAD

**Issue by redbaron76** [jagi/meteor-astronomy#616]
Is it possible to override validation on certain fields?
Let's say I have a `firstName` field with `validators: [{ type: 'minLength', param: 2 }]`, is it possible to update it as an empty string without applying validation rules? It seems not atm from the documentation. (but it could be very useful sometimes).

At the moment the only way I found is to `$set` values directly using `getCollection()`.

An idea would be:
```js
const user = User.findOne(Meteor.userId());
user.firstName = '';
user.lastName = 'Smith',
user.save({
    fields: ['firstName', 'lastName'],
    excludeValidation: ['firstName']
});
```

Thanks

**Comment by lukejagodzinski** [comment]
If I would allow doing so from the client then it would be security hole as anyone on the client could just turn off validation. Validators are supposed to make sure that your data is valid. If you want per operation validation, then you would probably have to create meteor method for that where you just check additional rules.

Let's consider the following scenario. You have the `firstName` field which has only the `string` validator (the default one for the string fields). You don't add the `minLength` validator for the field. Now, you have some operation that also requires checking if the `firstName` field is at least 2 characters long. Then you create a method for this operation.

```js
meteorMethods: {
  someOperation() {
    if (this.firstName.length < 2) {
      throw new Meteor.Error(/* ... */);
    }
    this.save();
  }
}
```

And you invoke it on a doc:

```js
user.someOperation();
```
