### ISSUE TITLE
Loading related documents using ObjectId as reference 

### ISSUE THREAD

**Issue by manuelro** [jagi/meteor-astronomy#618]
I was wondering is Astronomy supports loading documents that are referenced by ID in other documents. I did not see anything like that in the documentation...

**Comment by lukejagodzinski** [comment]
You have to fetch documents by yourself. It used to be such a module for Astronomy v1 but it wasn't perfect and considering a number of different relations and structures I've decided to let the developer decide how to fetch related documents.

**Comment by manuelro** [comment]
Got it. Thanks for the advice.
