### ISSUE TITLE
Using empty array as type

### ISSUE THREAD

**Issue by manuelro** [jagi/meteor-astronomy#619]
Astronomy does not seem to support an empty array ([]) as a type, nor a array of arrays ([Array]). Is there any way to achieve this?

**Comment by manuelro** [comment]
SOLUTION: An array is also an object. The following code will do the trick:

``` javascript
fields: {
  myField: { type: Object, default: () => [] },
}
```

**Comment by Genroa** [comment]
There is a way : custom types. You can easily define Array as a custom type. :)
