### ISSUE TITLE
"Relation" module, how to?

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#62]
I'm having trouble implementing the relation package (https://github.com/jagi/meteor-astronomy/wiki/Relations). 

Data normalization:
Let's say I have a user and a post, and I want the user related to the post. Do I add relations to both classes? Just to the 'parent'? What are the acceptable 'local' and 'foreign' values? I ask this because I'm having trouble understanding how this can work with data normalization.
In the example of user/post, there may be millions of posts, but a user may only have thousands, so it would be more efficient to store the _id of the post in a user's relatedPosts field (thus searching thousands of lines) than storing the users _id in each of their posts (thus searching through millions of posts for the user _id). Can I do that? In the example you put in the wiki, the local and foreign values would pretty much be inverted.

Relating them:
Next, how do I actually relate them, do I do that by setting the respective ID's as normal? Is there a 'relation' function? 

Relation vs. Method
Finally, what's the difference between doing that and just adding a method that finds the related class object? For example this method:
```posts: function(){
      return Posts.find({author: _id});
    }```
The above doesn't seem to work consistently, however...
```console.log(user.posts.title) //outputs 'undefined'```
I realize that example is a little strange because it involves more than one post, but in my real example it's only one, so perhaps a better example is 'post.author.username'
However, when I put it in a template, it does work:
```{{#with user}}{{posts.title}}{{/with}}``` <- correctly shows title

**Comment by JulianKingman** [comment]
Also, do I need to set up relations on both sides to get the related object? (post.author and author.posts)

**Comment by jagi** [comment]
If `User` to `Post` is `1 to 1` relation then you have to do something like this:

```js
User = Astro.Class({
  name: 'User',
  relations: {
    post: {
      type: 'one',
      class: 'Post',
      local: '_id',
      foreign: 'userId'
    }
  }
});

Post = Astro.Class({
  name: 'Post',
  relations: {
    user: {
      type: 'one',
      class: 'User',
      local: '_id',
      foreign: 'postId'
    }
  }
});
```

You have to directly set both relations, in both classes.

When we talk about the `1 to many` relation, the way you store related id depends on the use case. Of course you can store ids of all related post in the user document in the array.

```js
user.postsIds = [1, 2, 3, 4, 5];
```

However when deleting any post you would have to remember to remove the id of that post from any user that may have reference to it. So everything depends on your use case.

Of course you could create method that does it in the same way. However I'm planning to add some extra functionality to this module like for example automatic removal of related documents.

**Comment by JulianKingman** [comment]
So does this work?

```javascript
User = Astro.Class({
  name: 'User',
  relations: {
    posts: {
      type: 'one',
      class: 'Post',
      local: 'postIds',
      foreign: '_id'
    }
  }
});

Post = Astro.Class({
  name: 'Post',
  relations: {
    user: {
      type: 'one',
      class: 'User',
      local: '_id',
      foreign: 'postId'
    }
  }
});
```

**Comment by jagi** [comment]
It should be something like this:

```js
User = Astro.Class({
  name: 'User',
  fields: {
  },
  relations: {
    posts: {
      type: 'many',
      class: 'Post',
      local: '_id',
      foreign: 'userId'
    }
  }
});

Post = Astro.Class({
  name: 'Post',
  fields: {
    userId: 'string'
  },
  relations: {
    user: {
      type: 'one',
      class: 'User',
      local: 'userId',
      foreign: '_id'
    }
  }
});

var u = new User();
u.save();

var p = new Post();
p.userId = u._id;
p.save();

u.posts(); // Gets all related posts
p.user(); // Gets user related with given post
```

I know it maybe counter intuitive to set all the local and foreign keys but I was inspired by Doctrine library from PHP language and it's how they did it. It probably could be done better. Relations module is in its early stage. What I would suggest for now is not using it. You can just write your own mechanisms using methods. It's even shorter to write and more clear what it does:

```js
User = Astro.Class({
  name: 'User',
  fields: {
  },
  methods: {
    posts: function() {
      return Posts.find({
        userId: this._id;
      });
    }
  }
});

Post = Astro.Class({
  name: 'Post',
  fields: {
    userId: 'string'
  },
  methods: {
    user: function() {
      return Users.findOne({
        _id: this.userId
      });
    }
  }
});

var u = new User();
u.save();

var p = new Post();
p.userId = u._id;
p.save();

u.posts(); // Gets all related posts
p.user(); // Gets user related with given post
```

**Comment by JulianKingman** [comment]
OK, I can stick to methods for now.

Look at how I wrote my relation definition, though, as there are reasons to write it that way. Assuming two databases, user and post, depending on what sort of structure you have, any of the following are valid ways to set up a relationship (according to MongoDB):

1. Store user._id in post.userId (one-to-one, simplest. Technically also one-to-many as many posts can store the same userId)
2. Store user._id in post.userId array (many-to-one, what you've written above. Many to one means more than one user could have the same related post doc. Example: a post with multiple collaborators)
3. Store post._id in user.postId (backwards one-to-one, less expensive if there are many more post docs than user docs as the search is over a smaller collection. This is true one-to-one, as you can't have multiple posts with the same _id. Example: many posts can be claimed by users, and once assigned the post belongs only to that user.)
4. Store post._id in user.postId array (one-to-many, what I wrote above. This works well where user will have relatively few related post docs, and where there may be many post docs, it has the same advantage as number 3. Example: medium.com, where many users post many articles. Searching all articles is expensive, easier to find the post's _id in the user.postId array).
5. Any combination of the above
6. Self-relation using any combination of the above

**Comment by JulianKingman** [comment]
Should this work? It's coming back undefined

```javascript
  Users.find({}).forEach(function(link){
    var posts = link.posts;
    return posts.title;
  });
```
(Note: If the example seems silly, it's going to be used to add data to an object that will be exported as CSV)

**Comment by JulianKingman** [comment]
I see what I did wrong, it should have been:
```javascript
var posts = user.posts();
```

**Comment by jagi** [comment]
Storing multiple post ids in the postsIds array is not implemented yet in relations module. Of course it's one of the proposed solutions in MongoDB and will probably be implemented in this package.

**Comment by jagi** [comment]
Closing this issue as it's related to the `relations` package on which I will be working soon.
