### ISSUE TITLE
Map custom type problem

### ISSUE THREAD

**Issue by Genroa** [jagi/meteor-astronomy#621]
Hi again!

I tried to implement a new Type in Astronomy, for JS Maps:

```js
Type.create({
	name: 'Map',
	class: Map,
	validate(args) {
		return true;
	}
});
```

If I use the cast function to display the field value in my document, it display "Map {}". No problem here. But when on clientside I call findOne on a document, and then display the type of the field, it displays "Object{}". That's a real problem, because of that, I can't iterate correctly on it, nor call get, set, delete.

I can't seem to find what's going on, or what I missed. Any idea or valid custom type implementation for Maps?

**Comment by lukejagodzinski** [comment]
If you take a look at this line: https://github.com/jagi/meteor-astronomy/blob/v2/lib/core/class.js#L157 you will see what's happening when we create a new class.

```js
Type.create({
  name: className,
  class: Class,
  validate(args) {
    // Add current class as a param of validator.
    args.param = Class;
    Validators.class(args);
  }
});
```

We register a new type an provide as the `class` property the `Class` constructor. And what is `Class`? `Class` is an Astronomy class that is EJSONable. And `Map` is not EJSON able. You have to create wrapper around Map that would have the same methods as `Map`. Let's call it `MeteorMap`. Here is my example from docs how to define custom type in EJSON https://docs.meteor.com/api/ejson.html#EJSON-addType

```js
class Distance {
  constructor(value, unit) {
    this.value = value;
    this.unit = unit;
  }
  // Convert our type to JSON.
  toJSONValue() {
    return {
      value: this.value,
      unit: this.unit
    };
  }
  // Unique type name.
  typeName() {
    return 'Distance';
  }
}
EJSON.addType('Distance', function fromJSONValue(json) {
  return new Distance(json.value, json.unit);
});
EJSON.stringify(new Distance(10, 'm'));
// Returns '{"$type":"Distance","$value":{"value":10,"unit":"m"}}'
```

**Comment by Genroa** [comment]
Thanks for the quick reply. Maybe Astronomy could provide wrappers or custom types for the now standard Javascript types like Map, Set, ... ? I could try to do a PR if you want. :) or maybe it has been designed this way?

**Comment by lukejagodzinski** [comment]
Hmm maybe I could implement it. I don't know if there is a high demand for
that. Maybe there is a way you could implement solution to your problem in
a different way? Could you tell me more about your use case?

**Comment by Genroa** [comment]
I'm currently a miniature's wargame army list builder, and obviouly, the Army object representing an army list contains Units. Theses units can't be in an Array field like [Unit], because if you are browsing to a url of this kind /edit/[unit_position] and the array changes (positions are changed or you add/remove a Unit from it), the whole interface would refresh. But unless you delete the unit, it shouldn't matter.

But because Unit is a nested field, it has no unique _id to get it. So, I tried to change the [Unit] field and use a Map, mapping a UUID to a unit when you add it. This way, even if the units pool changes, if the unit is still in the Map, everything's fine.

Maps have really clean and smooth to use methods, like get, set, delete. They are powerful, you don't need to hack it using an Object and its properties. My work is mainly software programing, so, you know, if something can be more appropriate for what I want to do, even if I could do it in a messy way, I wanted to try.

Sets and Maps could easily be parsed and be added to the custom types known by Astronomy, I think. Like any other type defined with the Type API. 😄

**Comment by lukejagodzinski** [comment]
Provide some example, I don't understand description of your problem.

**Comment by Genroa** [comment]
Example:

```javascript
Army = Class.create({
	name: 'Army',
	collection: new Mongo.Collection('army'),
	fields: {
		...,
		units: {
			type: Map,
			default: function(){return new Map();}
		}
	},
	helpers: {
		...,
		getUnits() {
			return this.units.values();
		},

		getUnitsUIDs() {
			return this.units.keys();
		},

		getUnit(uid) {
			return this.units.get(uid);
		},

		addUnit(unit) {
			let uid = uuidv4();
			unit._uid = uid;
			this.units.set(uid, unit);
		},

		removeUnit(uid) {
			this.units.delete(uid);
		}
	}
});
```

And looping over key/values is easy, and you can loop over pairs easily, in a clean way. Right now, I have to do this:

```javascript
Army = Class.create({
	name: 'Army',
	collection: new Mongo.Collection('army'),
	fields: {
		...,
		units: {
			type: Object,
			default: function(){return {};}
		}
	},
	helpers: {
		...,
		
		getUnits() {
			return Object.values(this.units);
		},
		
		getUnitsUIDs() {
			return Object.keys(this.units);
		},
		
		getUnit(uid) {
			return this.units[uid];
		},
		
		addUnit(unit) {
			let uid = uuidv4();
			
			unit._uid = uid;
			this.units[uid] = unit;
		},
		
		removeUnit(uid) {
			delete this.units[uid];
		}
	}
});
```

Not the cleanest nor fastest way to do it. And for Sets, I have to hack it even more

**Comment by lukejagodzinski** [comment]
It would have to serialize and deserialize data on saves and reads which is not the best idea. MongoDB is supposed to store plain data not serialized Maps. EJSON which could serialize (stringify) Maps if properly extended is not intended to be used to store data in MongoDB. Astronomy could have a feature for converting maps to plain objects and later back to Maps but it would have to be one more step which would make code really slow. Your solution is quite good.

Taking all pros and cons, sorry but I'm not gonna implement this feature.
