### ISSUE TITLE
[Feature Request] Relations?

### ISSUE THREAD

**Issue by iMagdy** [jagi/meteor-astronomy#624]
Is there any plans to support relations?

Example:
```javascript
// product order doc
{
  _id: '.....',
  user_id: USER_ID
}

// user doc
{
  _id: '.....',
  username: 'Łukasz Jagodziński'
}
```

Then from orders Model, maybe reach the user info by doing:

```javascript
Order.user.username // Łukasz Jagodziński
```

`Order.user` is based on `user_id` .. `Order.{{identifier}}` without `_id`

I know this can be done by using Helpers:

```javascript
const Order = Class.create({
  name: 'Order',
  fields: {
    user_id: String
  },
  helpers: {
    user: () => Meteor.users.findOne(this.user_id)
  }
});
```

Then (function vs prop):

```javascript
Order.user().username // Łukasz Jagodziński
```

However, you'll repeat this every time you there's a relation, thoughts?

**Comment by lukejagodzinski** [comment]
There used to be relations feature in v1 but I've removed that because it was causing a lot of problems. It's quite easy to implement some helper functions that can do the job, so it's a developer's job to implement that.
