### ISSUE TITLE
Optional number didn't check gt validation

### ISSUE THREAD

**Issue by ArthurGerbelot** [jagi/meteor-astronomy#639]
Hi,

This is a field validation for a Number: 
```
    width: {
      type: Number,
      validator: [
        {type: 'gt', param: 0}
      ],
      optional: true
    },
```

But if I put width to `-2`, no error are fired.

**Comment by lukejagodzinski** [comment]
@ArthurGerbelot can you create reproduction repository? After I've checked source code I think it's very unlikely to happen but would like to confirm it by checking reproduction repository.

**Comment by ArthurGerbelot** [comment]
@jagi this is a reproduction repository: https://github.com/ArthurGerbelot/astronomyvalidator

I made some example:

Validation on required String work fine
![1](https://user-images.githubusercontent.com/8027826/29660616-c2ea2b94-888f-11e7-8dd3-fa502957a1d2.png)
![2](https://user-images.githubusercontent.com/8027826/29659074-0ef1b066-888b-11e7-9741-43dc4ae6149d.png)

When I put a negative number, `gt` validation didn't work :/
![3](https://user-images.githubusercontent.com/8027826/29659072-0ee1127e-888b-11e7-9d8d-9ca8e4a1a5a9.png)


And The last: It's working and insert with `width: -4`
![4](https://user-images.githubusercontent.com/8027826/29660771-1af899ec-8890-11e7-8523-85348daf338b.png)

**Comment by lukejagodzinski** [comment]
The field definition should be:
```js
width: {
  type: Number,
  validators: [
    {type: 'gt', param: 0}
  ],
  optional: true
}
```

not

```js
width: {
  type: Number,
  validator: [
    {type: 'gt', param: 0}
  ],
  optional: true
}
```

`validators` instead of `validator`. In the future, please read documentation carefully
