### ISSUE TITLE
Defer Astronomy loading

### ISSUE THREAD

**Issue by antoninadert** [jagi/meteor-astronomy#642]
Hello there, 

I tried to add Astronomy in my project, I then used the bundle-visualizer and to my surprise Astronomy weights 173kB (that's a lot) in my project. 

The thing is that I didn't even import it anywhere, it is just automatically included in the build.

Is there any way for me to control the load of Astronomy (using dynamic imports for example) ?

I hope you have a solution for that. 

Regards

**Comment by lukejagodzinski** [comment]
Hi, for backward compatibility it's using automatic import feature from earlier Meteor's versions. So even though it's working with imports it's still using old import feature which makes it load on Meteor start up. I might deprecate older Meteor versions in the newest Astronomy version.

**Comment by lukejagodzinski** [comment]
It should be fixed in Astronomy 2.5.0. Let me know if it still loads entire Astronomy package even without a single import statement.

**Comment by antoninadert** [comment]
Sure ! By the way any resource on how to use the best of astronomy and grapher to make something really fancy ? 
Maybe there are overlaps between the two that are not necessary

**Comment by lukejagodzinski** [comment]
Never used grapher so I don't know.

**Comment by davidsavoie1** [comment]
@antoninadert I'm curious, have you tried integrating Astronomy with Grapher yet?

**Comment by antoninadert** [comment]
@davidsavoie1 no, I am currently contemplating different options but I don't think I'll use astronomy in the end. 
I'll probably use GraphQl or something with Grapher
