### ISSUE TITLE
Strange behavior when saving arrays with undefined values

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#644]
If I try to save my Astronomy document with an array like this `var a = [undefined, undefined, 'foobar', undefined]`, only the two last entries will be saved, resulting in `['foobar', undefined]`.

Reproduction:

https://github.com/arggh/astronomy-array-issue

### How it works:

1. Run `meteor`
2. Observe the type of array we are about to save (displayed on page for convenience)
3. Click the Save -button
4. Observe what actually got saved in the database (displayed on page for convenience)

**Comment by lukejagodzinski** [comment]
@arggh Yep, indeed there is a bug. Thanks for noticing it. I've already fixed it and I will release a new version that fixes that.

**Comment by lukejagodzinski** [comment]
Fixed in Astronomy 2.5.0

**Comment by arggh** [comment]
I confirm the issue is now fixed, thanks! 👍 

Btw, is this the "correct" way to define a field, which holds an Array of mixed nulls/undefineds  and Strings? (with no validation yet for actually having only nulls/undefineds or Strings obviously)
 
```
fields: {
    values: {
      type: Object,
      default: function() {
        return [];
      },
      validators: [
        { type: 'array' }
      ]
    }
  }
```

**Comment by lukejagodzinski** [comment]
Actually, there is no official way of doing it but if it works in your example then it's ok. In fact, an array is just an object so it should work properly.

**Comment by arggh** [comment]
It works, it just looks a bit _hacky_ so I was wondering if I had missed something in the docs.

Maybe it could be a good idea to consider one or many of these solutions:

- Possible to define multiple types for an Array eg. `type: [String, null, Boolean]`
- Possible to define the specified type as _optional_, meaning, it can also be `null` or `undefined`
- Possible to define Array containing _anything_: `type: []`

**Comment by lukejagodzinski** [comment]
> Possible to define multiple types for an Array eg. type: [String, null, Boolean]

It is actually possible using [unions](http://jagi.github.io/meteor-astronomy/v2#union-type)

> Possible to define the specified type as optional, meaning, it can also be null or undefined

That would be the best solution. It would be similar to what we have in GraphQL. However, it would require entire redesign of the types system in Astronomy.

> Possible to define Array containing anything: type: []

That actually might be the easiest one to do. Will think about implementing it.

**Comment by jdalrymple** [comment]
> > Possible to define multiple types for an Array eg. type: [String, null, Boolean]
> 
> It is actually possible using [unions](http://jagi.github.io/meteor-astronomy/v2#union-type)
> 
> > Possible to define the specified type as optional, meaning, it can also be null or undefined
> 
> That would be the best solution. It would be similar to what we have in GraphQL. However, it would require entire redesign of the types system in Astronomy.
> 
> > Possible to define Array containing anything: type: []
> 
> That actually might be the easiest one to do. Will think about implementing it.

Unions dont support null types or optional keys afaik
