### ISSUE TITLE
Astronomy throws exception when upsert is used with Meteor 1.5.2 (LocalCollection._removeDollarOperators is not a function)

### ISSUE THREAD

**Issue by derwok** [jagi/meteor-astronomy#645]
It seems astronomy is not compatible with current Meteor 1.5.2

After we upgraded our project (https://www.4minitz.com) from Meteor 1.5.1 to 1.5.2 we suddenly get crashes when using upsert like so:

```
        TopicSchema.upsert(
            { parentId: this.meetingSeriesId, _id: topicId },
            topicDoc
        );
``` 

Here comes exception text (caused by astronomy)
```
meteor: I20170915-07:42:48.688(2)? Exception while invoking method 'workflow.finalizeMinute' TypeError: LocalCollection._removeDollarOperators is not a function
meteor: I20170915-07:42:48.689(2)?     at classUpsert (packages/jagi:astronomy/lib/modules/storage/utils/class_upsert.js:83:43)
meteor: I20170915-07:42:48.690(2)?     at Function.upsert (packages/jagi:astronomy/lib/modules/storage/class_static_methods/upsert.js:50:18)
meteor: I20170915-07:42:48.690(2)?     at MeetingSeriesTopicsUpdater.upsertTopic (imports/services/finalize-minutes/meetingSeriesTopicsUpdater.js:28:21)
meteor: I20170915-07:42:48.691(2)?     at TopicsFinalizer._mergeOrInsertTopic (imports/services/finalize-minutes/topicsFinalizer.js:53:28)
meteor: I20170915-07:42:48.692(2)?     at TopicsFinalizer.mergeTopics (imports/services/finalize-minutes/topicsFinalizer.js:43:18)
meteor: I20170915-07:42:48.692(2)?     at Function.mergeTopicsForFinalize (imports/services/finalize-minutes/topicsFinalizer.js:14:25)
meteor: I20170915-07:42:48.693(2)?     at [object Object].Meteor.methods.workflow.finalizeMinute (imports/services/finalize-minutes/finalizer.js:75:25)
meteor: I20170915-07:42:48.694(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
meteor: I20170915-07:42:48.694(2)?     at packages/ddp-server/livedata_server.js:719:19
meteor: I20170915-07:42:48.695(2)?     at [object Object].EVp.withValue (packages/meteor.js:1135:15)
```

With Meteor 1.5.2 we saw this exception on astronomy current version 2.5.0 and even on the older 2.4.8. We used astronomy 2.4.8 together with Meteor 1.5.1 without any problems. So this is not a new astronomy issue - We looked at changes on Meteor's side that may have caused this issue even with the former working astronomy version 2.4.8. 

Surprise: we found this Meteor commit that removed the private _removeDollarOperators for Meteor 1.5.2-beta1:
https://github.com/meteor/meteor/commit/dda994c26247f5b8eeb7fc789735f05e94d82b0e#diff-92272525414f7df6943cac34ebea2a2fL1267

Is there a way to work around the absence of this removed private meteor function?

**Comment by lukejagodzinski** [comment]
It's not Astronomy bug, it's Meteor bug. I'm not using the `_removeDollarOperators` method so probably it was removed and is still used somewhere in Meteor in LocalCollection. I'm only using the `LocalCollection._modify` function which is probably using somewhere `_removeDollarOperators` https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/storage/utils/apply_modifier.js#L18.

Maybe right now there is the other way of applying a modifier. I would have to investigate this problem.

**Comment by derwok** [comment]
I checked the callstack above once more.
This seems the problematic line in astronomy:
https://github.com/jagi/meteor-astronomy/blob/04e8e24153b36243731265a77ced51aa86ce3ffd/lib/modules/storage/utils/class_upsert.js#L83

**Comment by lukejagodzinski** [comment]
Let's keep it open as I will investigate it anyway. In theory, I shouldn't use private methods in Astronomy but I had to. Maybe there is the other way of doing it right now, so it would be good to use it. However, I'm a little bit worried about backward compatibility.

**Comment by martinhbramwell** [comment]
I just now attempted upgrading to ```METEOR@1.6-beta.27```  

      TypeError: LocalCollection._removeDollarOperators is not a function
      at classUpsert (packages/jagi:astronomy/lib/modules/storage/utils/class_upsert.js:83:43)
      at Function.upsert (packages/jagi:astronomy/lib/modules/storage/class_static_methods/upsert.js:50:18)
      at Function._AccessControl.upsertRecord (lib/access_control.js:83:17)
      at server/configs/initial_adds.js:25:19
      at Array.forEach (<anonymous>)
      at Function._.each._.forEach (packages/underscore.js:139:11)
      at _initPosts (server/configs/initial_adds.js:24:5)
      at main.js (server/main.js:86:1)
            : 
            : 

Is there some sort of workaround?

**Comment by lukejagodzinski** [comment]
I will test Astronomy with Meteor 1.6 this week and let you know if I have
some solution for that

**Comment by martinhbramwell** [comment]
I'd be very grateful.  My 1.6 upgrade attempt is on hold because of it.  I'd rather not have to switch to ```simple-schema```  :-(.

**Comment by lukejagodzinski** [comment]
Ok, I see that you're talking about two different versions. I've tested Astronomy with Meteor 1.6-beta.30 and it works properly. So for all of you who are trying Astronomy with Meteor 1.6 beta please update your project to beta.30. If it goes about Meteor 1.5.2 it looks like it's a bug in Meteor so I don't recommend this version but I will investigate it further.

**Comment by lukejagodzinski** [comment]
@derwok I've tested Astronomy also with Meteor 1.5.2 and it works properly. Are you sure that you're not using some other package that could mess with Meteor internals? The commit you've been talking about is for Meteor 1.6

**Comment by martinhbramwell** [comment]
Hi @jagi 
So I tried with beta.30 and still have the same error. :-(

**Comment by lukejagodzinski** [comment]
Sorry, my bad. Indeed, I'm using this function and it's not working in both 1.5.2 and 1.6. I will prepare a fix. Let you know when it's ready.

**Comment by lukejagodzinski** [comment]
Ok, should be fixed in 2.5.1. Please check and let me know if it works.

**Comment by derwok** [comment]
Thx! I'll give it a try as soon as possible. Will report here!

**Comment by derwok** [comment]
You're DA MAN! All our Meteor 1.5.2 Tests are green for the first time.
Yieeha!

![grafik](https://user-images.githubusercontent.com/4393698/30719004-3223b950-9f22-11e7-9122-ecfcd42d3204.png)

https://travis-ci.org/4minitz/4minitz/builds/278350531

Thanks a lot, jagi!

**Comment by lukejagodzinski** [comment]
No problem :)

**Comment by martinhbramwell** [comment]
I confirm that I am back happy; running Meteor 1.6-beta and Node 8.5. Yoo Hoo!

Thanks for the super fast response.

**Comment by lukejagodzinski** [comment]
@martinhbramwell good to hear. No problem :)
