### ISSUE TITLE
Default value of field with type Object is referenced instead of copied

### ISSUE THREAD

**Issue by pepijnverburg** [jagi/meteor-astronomy#647]
Hi there,

This took some time to figure out, but apparently when a schema is created the 'default' value of a field with type 'Object' is passed by reference to each of the documents fetched where this field was not set. 

For example the following definition:
```
name: 'Car',
collection: CarCollection,
fields: {
  wheels: {
    type: Object,
    default: {}
  },
},
```

All documents when fetching the cars with all 'wheels' undefined will have the same object set by reference. I think the default value should be (deep)copied. Or is there a reason not to?

Now this happens:
```
var cars = Car.find({}).fetch() // gives three cars
cars = cars.map((car, index) => {
  car.wheels.amount = index
})
cars.map((car) => {
  console.log('amount: '+ car.wheels.amount)
})

```
Output:
```
amount: 3
amount: 3
amount: 3
```

Thanks for the awesome library btw. Works great!

**Comment by lukejagodzinski** [comment]
Hi,

From documentation:

>We can’t use JavaScript objects for default values directly. If we want to do so, then we have to use function and return such an object.

```js
name: 'Car',
collection: CarCollection,
fields: {
  wheels: {
    type: Object,
    default: () => {}
  },
},
```

**Comment by pepijnverburg** [comment]
Hi there,

Thanks for the reply! Totally missed that in the documentation. Thanks & closed :)
