### ISSUE TITLE
Calling meteorMethod fails if document doesn't contain all fields

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#649]
I noticed a strange issue after updating to newest Astronomy.

One part of my app that I haven't touched in ages wasn't working anymore.

It's a simple scenario, where I fetch my data with only some of the fields included.

```js
// used in the template
docs() { 
   return Doc.find({}, {
     fields: {
        title: 1,
        color: 1,
        order: 1,
        removed: 1
     }
   });
}
```

Then at some point I would then call a `meteorMethod` on one of these documents, provided via Astronomy behavior (one I forked from your sorting-behavior).

It used to work with `v2.3.x`, but after updating to all I get is 

```
`Exception while simulating the effect of invoking '/Astronomy/execute' TypeError: Cannot read property 'order' of undefined
    at Class.methods.moveTo
```

I pin-pointed the bug to have appeared in `v2.4.7`. The same issue is also present on the newest release.

**If I remove the `fields` - attribute** from the method that gets my documents, it works with `v2.4.7` and above.

**Comment by arggh** [comment]
I have a strong hunch It's lurking somewhere here: https://github.com/jagi/meteor-astronomy/commit/f056af9fa12763b55b1765a3df105d70668e958a

**Comment by arggh** [comment]
Ok, I figured out the cause in this case:

I had declared my "sort" -behavior like so:

```js
behaviors: {
    sort: {
      orderFieldName: 'order',
      hasRootField: true,
      rootFieldName: 'userId', // <--- culprit
    }
  }
```

If I add `userId` to the `fields` attribute when fetching documents, it works again.

This changed in `v2.4.7`, since before that it used to work without specifying the `userId` (aka. rootFieldName), as long as it was actually present on the client, or so it seems.

Here is the forked version of sort-behavior I'm using: https://github.com/arggh/meteor-astronomy-sort-behavior/tree/v2

Should I close this issue or should it be given some thought?

**Comment by lukejagodzinski** [comment]
You could actually extend definition by adding the `beforeFind` event and extend the `fields` option so that both the `orderFieldName` and `rootFieldName` are always included.

```js
if (this.options.hasRootField) {
  definition.fields[this.options.rootFieldName] = {
    type: String,
    optional: true,
    default: null
  };

  definition.events.beforeFind = (e) => {
    const doc = e.currentTarget;
    const options = e.options;
    if (options.fields) {
      options.fields[this.options.rootFieldName] = 1;
    }
  };
}
```

So I'm closing this issue as it's not related with some bug in Astronomy.
