### ISSUE TITLE
Apply Astronomy schema to multiple collections ?

### ISSUE THREAD

**Issue by axelvaindal** [jagi/meteor-astronomy#651]
Hi,

I look for a particular functionality in the documentation and couldn't find anything.
Is there any way to apply Astronomy schema to multiple collections ?

My use case is the following : 

I have a `users` collections (the Meteor embedded one in fact), with a `User` astronomy class with some helpers and behaviors.
Building the administration panel, I have to display a list of user (in the form of a table), so I publish the users in a dedicated client side collection (which is not the users collection).
I would like to apply my Astronomy schema for the users to this client-side only collection AND to the actual `users` collection.

The reason I'm doing this is because I have another publication, which publish the data of the current logged in user for another component available on this page as well, and couldn't separate this user from the others in the table if I were getting them from the users collections only.

**Comment by lukejagodzinski** [comment]
If you have class defined like this:

```js
const UserBase = Class.create({
  name: "UserBase",
  // No collection definition here
  fields: {},
  helpers: {}
});
```

Then you can define two classes by extending it.

```js
const User = UserBase.extend({
  name: "User",
  collection: Meteor.users
});

const OtherUser = UserBase.extend({
  name: "OtherUser",
  collection: OtherCollectionWithUsers
});
```

I don't know if it solves your problem but let me know

**Comment by axelvaindal** [comment]
Hum, don't know if I made it wrong, but got some issue with your code.

I did this : 

```js

// Trimmed this class to simplify displaying
const UserBase = Class.create(
{
	name: "UserBase",
	fields: {},
	helpers: {},
        behaviors: 
       {
  		timestamp:
  		{
  		},
  		softremove:
  		{
  		}
	}
});

export const User = UserBase.extend(
{
	name: "User",
	collection: Meteor.users,
});
```

And got this error : 

```
W20180122-23:02:06.438(1)? (STDERR) /home/avaindal/.meteor/packages/meteor-tool/.1.6.0_1.7s0lvf.tm1qa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180122-23:02:06.440(1)? (STDERR)                                             throw(ex);
W20180122-23:02:06.441(1)? (STDERR)                                             ^
W20180122-23:02:06.441(1)? (STDERR)
W20180122-23:02:06.442(1)? (STDERR) TypeError: Cannot read property '_connection' of undefined
W20180122-23:02:06.442(1)? (STDERR)     at Behavior.apply (packages/jagi:astronomy-softremove-behavior/lib/behavior/behavior.js:65:33)
W20180122-23:02:06.443(1)? (STDERR)     at behaviorOptions (packages/jagi:astronomy/lib/modules/behaviors/hooks/apply_definition.js:18:16)
W20180122-23:02:06.444(1)? (STDERR)     at arrayEach (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_arrayEach.js:15:9)
W20180122-23:02:06.444(1)? (STDERR)     at forEach (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/forEach.js:38:10)
W20180122-23:02:06.445(1)? (STDERR)     at _each (packages/jagi:astronomy/lib/modules/behaviors/hooks/apply_definition.js:11:5)
W20180122-23:02:06.445(1)? (STDERR)     at /home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_createBaseFor.js:17:11
W20180122-23:02:06.446(1)? (STDERR)     at baseForOwn (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_baseForOwn.js:13:20)
W20180122-23:02:06.446(1)? (STDERR)     at /home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_createBaseEach.js:17:14
W20180122-23:02:06.447(1)? (STDERR)     at forEach (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/forEach.js:38:10)
W20180122-23:02:06.448(1)? (STDERR)     at Module.onApplyDefinition (packages/jagi:astronomy/lib/modules/behaviors/hooks/apply_definition.js:8:3)
```

**Comment by axelvaindal** [comment]
I managed to resolve the issue mentioned in my previous comment, but this still doesn't work.

It seems the extended class is undefined because the extend does not return the extended Astro class (at least in my code).
I tried to do this and it displays `undefined`: 

```
console.log(UserBase.extend(
{
	name: "User",
	collection: Meteor.users,
	behaviors:
    {
  		timestamp:
  		{
    		hasCreatedField: true,
    		createdFieldName: "createdAt",
    		hasUpdatedField: true,
    		updatedFieldName: "updatedAt"
  		},
  		softremove:
  		{
    		removedFieldName: "deleted",
    		hasRemovedAtField: true,
    		removedAtFieldName: "deletedAt"
  		}
	}
}));
```

Basically in your documentation, you do not get back the result of the extend considering you're extending for environment purpose, so you don't need to hold the result in another variable. I assume this is normal behavior ?

Perhaps it should be made available as the return of the function ?
But if it is only to apply the schema to client-side only collection, I would rather prefer being able to pass an array of Mongo.Collection directly in the first class to avoid duplicating data.
This should just apply the schema for each specified collection in the array (which should be sanitized of anything not being a Mongo.Collection).

So, on second thought, I think this would make a great improvement to have the two things implemented in your package, if it's not available yet. (Return a copy of the extended class and make array of collections available in the Class design).

**Comment by lukejagodzinski** [comment]
Sorry, I meant `inherit` not `extend` :) my bad

```js
import { Class } from "meteor/jagi:astronomy";
import { Mongo } from "meteor/mongo";

Users = new Mongo.Collection("users");
ClientUsers = new Mongo.Collection(null);

BaseUser = Class.create({
  name: "BaseUser",
  fields: {
    name: String
  },
  helpers: {}
});

User = BaseUser.inherit({
  name: "User",
  collection: Users
});

ClientUser = BaseUser.inherit({
  name: "ClientUser",
  collection: ClientUsers
});
```

**Comment by axelvaindal** [comment]
Looks like this is actually working with the following code: 

```javascript
export const User = UserBase.inherit(
{
	name: "User",
	collection: Meteor.users,
	behaviors:
	{
		timestamp:
		{
			hasCreatedField: true,
			createdFieldName: "createdAt",
			hasUpdatedField: true,
			updatedFieldName: "updatedAt"
		},
		softremove:
		{
			removedFieldName: "deleted",
			hasRemovedAtField: true,
			removedAtFieldName: "deletedAt"
		}
	}
});

if (Meteor.isClient)
{
	export const UserAdminList = UserBase.inherit(
	{
		name: "UserAdminList",
		collection: new Mongo.Collection("users-admin-list")
	});
}
```
Although this is working, there is much downside doing it this way : 

- I need 3 classes with exactly the same behavior to achieve this instead of one
- The code is pretty messed up, with client and server side specific export and more.
- As before, the behaviors must be duplicated in both inherited classes as I cannot put them in the parent class without breaking the application with the error I mentioned in my previous comment.

I'm pretty sure the use of an array in the collection field of the Astro class would be a better way of achieving such a thing. Is there any downside of this method ? 🙂

**Comment by lukejagodzinski** [comment]
Currently it's not possible to add one class to multiple collections as there is a possibility to fetch documents from the collection by class name:
```js
ClassName.find();
```
Which collection should it fetch documents from? It would require additional parameters or make find in both collections. That's not a good idea.

**Comment by axelvaindal** [comment]
I understand.
Is it possible to look deeper in the behavior issue so I don't have to copy/paste behaviors in all my inherited classes ? 
Because when I put the behaviors in the parent class, the inherit fails and I have this error in my server console : 

```
TypeError: Cannot read property '_connection' of undefined
W20180123-21:23:35.827(1)? (STDERR)     at Behavior.apply (packages/jagi:astronomy-softremove-behavior/lib/behavior/behavior.js:65:33)
W20180123-21:23:35.827(1)? (STDERR)     at behaviorOptions (packages/jagi:astronomy/lib/modules/behaviors/hooks/apply_definition.js:18:16)
W20180123-21:23:35.828(1)? (STDERR)     at arrayEach (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_arrayEach.js:15:9)
W20180123-21:23:35.828(1)? (STDERR)     at forEach (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/forEach.js:38:10)
W20180123-21:23:35.828(1)? (STDERR)     at _each (packages/jagi:astronomy/lib/modules/behaviors/hooks/apply_definition.js:11:5)
W20180123-21:23:35.829(1)? (STDERR)     at /home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_createBaseFor.js:17:11
W20180123-21:23:35.829(1)? (STDERR)     at baseForOwn (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_baseForOwn.js:13:20)
W20180123-21:23:35.829(1)? (STDERR)     at /home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/_createBaseEach.js:17:14
W20180123-21:23:35.830(1)? (STDERR)     at forEach (/home/avaindal/.meteor/packages/jagi_astronomy/.2.5.2.vsvntv++os+web.browser+web.cordova/npm/node_modules/lodash/forEach.js:38:10)
W20180123-21:23:35.831(1)? (STDERR)     at Module.onApplyDefinition (packages/jagi:astronomy/lib/modules/behaviors/hooks/apply_definition.js:8:3)
```

**Comment by lukejagodzinski** [comment]
Ok, behavior probably requires collection property to be set. In such a situation there is another way, maybe even more elegant.

```js
import { Class } from "meteor/jagi:astronomy";
import { Mongo } from "meteor/mongo";

const CommonSchema = {
  fields: {
    name: String
  },
  helpers: {},
  behaviors: {}
};

Users = new Mongo.Collection("users");
ClientUsers = new Mongo.Collection(null);

User = Class.create(Object.assign({
  name: "User",
  collection: Users
}, CommonSchema));

ClientUser = Class.create(Object.assign({
  name: "ClientUser",
  collection: ClientUsers
}, CommonSchema));
```

**Comment by axelvaindal** [comment]
Yes, this is it 🙂.
This way is working fine, although I feel unfamiliar with using `Object.assign`.
Is there any downside of this way of doing things (in terms of performance or usage) ?

If not, I will try to refactor my code to take this design into account and build collections handler and publication manager around this.

**Comment by lukejagodzinski** [comment]
`Object.assign` is actually almost the same as `_.extend` from lodash or underscore. Of course you can use `_.extend` instead. There won't be any problem with performance when using it. So, feel free to refactor your code.
