### ISSUE TITLE
update collection, $unset is not working

### ISSUE THREAD

**Issue by PedroACF** [jagi/meteor-astronomy#655]
Hi, i wanted to delete a field with the '$unset' option on the server side, but my code isn't working:
`meteorMethods(){
 unsetField(){
    MyCollection.update(this._id, {$unset: {fieldToDelete:''}})
}
}`
did i something wrong?

**Comment by a4xrbj1** [comment]
Agree with @PedroACF , same here this isn't working anymore:

`Groups.update({ _id: 'Q9DLXgQKJQdFZQq6k' }, {
        $unset: {
            temp: '',
        },
    });`

**Comment by lukejagodzinski** [comment]
Did you update Astronomy version recently? Or tell me what version you are
using.

**Comment by lukejagodzinski** [comment]
I did a test and you have to update Astronomy version. In the newest one, everything is working properly.

**Comment by a4xrbj1** [comment]
2.5.2

This error want detected as only today I added a safeguard around it to
identify if a doc was updated or not.

That's how I identified it doesn't update at all.

Andreas

**Comment by a4xrbj1** [comment]
Confirmed, updating to 2.5.3 solved the issue. You can close the issue and many thanks for the prompt answer @lukejagodzinski

**Comment by PedroACF** [comment]
MyCollection.update (...) works correctly (v2.5.3), but the "save()" method does not work correctly with the $unset operator.

When I want to see the modifier with `getModifier()`, the result on the client-side is
`{$set: {"field1": "new value"}, {$unset: {"field2": ""}}}`
but on the server-side $unset disappears.

Is there any reason for this behavior?

**Comment by lukejagodzinski** [comment]
@PedroACF I've tested it and it works so you're probably doing something wrong. Please, create reproduction repository so I'll be able to help you.
