### ISSUE TITLE
Single field validation as boolean

### ISSUE THREAD

**Issue by davidsavoie1** [jagi/meteor-astronomy#657]
Hi! I'm looking at ways to validate form inputs without having to rewrite all validation logic in the view itself (such as using [ViewModel validation](https://viewmodel.org/react#AdvancedValidation)).

[The `validate` method](http://jagi.github.io/meteor-astronomy/#validation) can be used on a single field with `class.validate('fieldName')`, but it doesn't return a simple `true`/`false` value that I can use to either display or hide validation error message. It instead throws a validation error that I need to catch in a callback, which doesn't seem to work well with reactive message display.

Is there a way that I'm not aware of to validate some fields and getting a simple boolean back, without error handling? Thanks in advance!

**Comment by lukejagodzinski** [comment]
@davidsavoie1 validation in Astronomy works the same way as Meteor methods so that when you do not pass callback function it will perform client simulation and return immediately without waiting for the server response. So what you can do is:

```js
var u = new User({ firstName: 234 });
try {
  u.validate("firstName");
} catch(err) {
  // Do something with the validation error.
}
```

So it's quite easy to write helper function:

```js
import { ValidationError } from 'meteor/jagi:astronomy';

const isValid = (doc, fieldName) {
  try {
    doc.validate(fieldName);
    return true;
  } catch(err) {
    if (ValidationError.is(err)) {
      return false;
    }
    // If an error thrown from validation is not instance of ValidationError then we throw this error again.
    throw err;
  }
}
```

**USAGE**

```js
var u = new User({ firstName: 234 });
if (!isValid(u, "firstName")) {
  // Do something with the validation error.
}
```

Actually, it would be probably a good idea to have such a helper built in, so if you would like to contribute it would be great :)

It could be something like:

```js
var u = new User({ firstName: 234 });
if (!u.isValid("firstName")) {
  // Do something with the validation error.
}
// Or for entire document.
if (!u.isValid()) {
  // Do something with the validation error.
}
```

**Comment by davidsavoie1** [comment]
Aaaah! Makes sense! OK, great, I'll try that out!
Thanks a lot for your time and effort, I really appreciate that!

**Comment by davidsavoie1** [comment]
This kind of helper seems to work, but for the record, an actual helper function would be more like so:
```javascript
const isValid = (doc, fields) => {
  try {
    doc.validate({ fields });
    return true;
  } catch (err) {
    if (ValidationError.is(err)) {
      return false;
    }
    // If an error thrown from validation is not instance of ValidationError then we throw this error again.
    throw err;
  }
};
```
where `fields` is an array of fields. The simpler syntax `doc.validate(fieldName)` seems to validate other fields too!

Getting the actual error messages could be nice too, though... Here's an attempt:
```javascript
const invalidMessages = (doc, fields) => {
  try {
    doc.validate({ fields, stopOnFirstError: false });
    return null;
  } catch (err) {
    if (ValidationError.is(err)) {
      return err.details.map(e => e.message);
    }
    // If an error thrown from validation is not instance of ValidationError then we throw this error again.
    throw err;
  }
};
```

However, although this function will return an error message for each invalid field, it won't show _all_ messages of a single field. As an example, if a field `myField` is required and has a `minLength` of 3, the function `invalidMessages(myDoc, ['myField'])` will return only `"myField" is required` at first, then only `Length of "myField" has to be at least 3` when a first character is typed in. That's true even with `stopOnFirstError: false`.

Well, there's progress! Thanks again!

**Comment by lukejagodzinski** [comment]
Yep, sorry it should be `validate({fields})`.
If it goes about validation error messages, take a look at how I've implemented it in this example repository https://github.com/jagi/meteor-astronomy-examples/blob/v2/client/templates.js#L101
Actually, I only care about the first error message and most users too. If you fix this problem, the next time validation happens it will throw another error and so on, until you fix all validation errors. Flooding user with error messages is not a good idea from the UX perspective.
