### ISSUE TITLE
Forcing Meteor.users to use Astronomy

### ISSUE THREAD

**Issue by lightpriest** [jagi/meteor-astronomy#659]
I guess this is more of a general Meteor question, but is there a recommended way to force Meteor to use an Astronomy class for `Meteor.users`? I am switching from SimpleSchema to Astronomy, and what I'm missing right now is the ability to globally force field-level behavior on the collection.

For example, in SimpleSchema I made `profile.name` a required field and this worked regardless of where the user updated their name from. i.e. even if I add a community package, the system agrees on `Meteor.users` as the user collection (validations, `onCreateUser`, etc.)

**Comment by lukejagodzinski** [comment]
It's not recommended to alter how users are fetched from the `Meteor.users` collection because it can interfere with other packages using this approach. So that's why we have hooks that we can attach to. However, if you really want to achieve that you can do following:

```js
import { LocalCollection } from "meteor/minimongo";

// "User" is the Astronomy class.
Meteor.users._transform = LocalCollection.wrapTransform(doc => new User(doc));
```

**Comment by lightpriest** [comment]
I understand. I also don't like this approach (one of the reasons I'm switching away from SimpleSchema and collection helpers). This will also force me to configure the fields definitions for other packages as well.

Well, considering the only real reason is to keep `profile` in check (other fields are read-only, server-updated anyway), I guess it'll be simpler to use `User` class when I need to update it and make it client side read-only as well.
