### ISSUE TITLE
Query Builder docs are missing

### ISSUE THREAD

**Issue by andykingking** [jagi/meteor-astronomy#66]
There are a fair number of methods in the query builder repo, but unfortunately no documentation on how to use it in this wiki.

Can anyone provide any insight or examples?

**Comment by jagi** [comment]
Hi, QueryBuilder is an experimental module for Astronomy that was proposed by me to deal with querying data that depends on some behaviors. Right now it's only used in the SoftRemove behavior. The API can change a lot in future releases, so if you don't have to, then don't use it now extensively. I will provide documentation after 1.0 release.

**Comment by an0nym0use** [comment]
Noted, thanks.
