### ISSUE TITLE
beforeRemove: How handle it with async functions?

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#663]
Hey,
I'm just wondering how I can handle the beforeRemove event with async functions. I want to remove a storage object when I delete a doc from the database. Currently, my implementation looks like this:

```
    events: {
        beforeRemove(e) {

            const doc = e.currentTarget;
            const client = cloudHelper.getClient(); // PKG cloud client



            client.removeFile(doc.fileObject.containerId, doc.fileObject.fileName,() => null);
            client.removeFile(doc.previewObject.containerId, doc.previewObject.fileName,() => null);
            client.removeFile(doc.posterObject.containerId, doc.posterObject.fileName,() => null);

        }
    }
```

In my case I want to "fire" the final remove after all callbacks from the clients were fired. If I check the docs, there could be an function which should stop the remove proccess -> <code>      e.preventDefault();</code> - but is there also a function like <code>e.next()</code> that I could call after all callbacks were resolved?

**Comment by lukejagodzinski** [comment]
Are you talking about client or server? If it's on the server then you should wrap all your async functions with [Meteor.wrapAsync](https://docs.meteor.com/api/core.html#Meteor-wrapAsync). If it's on the client then it's probably not possible in the `beforeRemove` event as it does not support promises so you can't use async/await. You would have to move your logic into some helper and execute the `remove` method only after all callbacks returned.

**Comment by dnish** [comment]
Ahh right, just forgot the whole wrapAsync thing. Yeah, it's server-only. Thanks :)
