### ISSUE TITLE
Documentation for writing behaviours and modules

### ISSUE THREAD

**Issue by iainhallam** [jagi/meteor-astronomy#665]
At the moment the Astronomy documentation at https://jagi.github.io/meteor-astronomy/#writing-behaviors says "IN PROGRESS", as does the writing-modules section. I've wondered about writing my own behaviours, but haven't had a chance to delve in to find out how. Filling in these sections would probably help enormously.

**Comment by lukejagodzinski** [comment]
Hi, for now, the only way to learn about writing behaviors is looking at the code of the other already implemented behaviors (the same with modules). I will probably not write documentation for it as there is little demand for that and it would take a lot of time which I don't have. Currently, I'm only adding some minor features and bugfixes so support for Astronomy will be continued but only for things that are crucial, sorry.
