### ISSUE TITLE
Versioning astronomy collections

### ISSUE THREAD

**Issue by luzlab** [jagi/meteor-astronomy#666]
Are there any turnkey solutions for versioning a records in an Astronomy collection? We're going to need to track versions of documents for compliance reasons and I'm doing research on possible approaches.

Thank you in advance for your advice and suggestions!

**Comment by lukejagodzinski** [comment]
Hi, you would probably have to write your own module/behavior for that. It won't be easy as it's not only about adding some extra field with the version number but also entire logic for retrieving records with the newest version or any version. There is no plug & play solution for that.
