### ISSUE TITLE
Retrieve Enum list of values

### ISSUE THREAD

**Issue by axelvaindal** [jagi/meteor-astronomy#668]
Hi,

I have a use case in my code where I need to loop through Enum values in order to generate a flag with binary operator. I would like to be able to call my function with every Enum values as an array.
I didn't find anything in the docs about that, is it something possible right now ?

Here is the related function : 

```js
// Security checks are omitted for better clarity
static flagEncode(booleans, binaryValues)
{
    let flag = 0;

    for (let i = 0; i < booleans.length; i++)
        flag |= booleans[i] ? binaryValues[i] : 0;

    return flag;
}
```
And here is what I'm trying to achieve: 
```js
let booleans = [0,0,1,0,1];

let flag = flagEncode(booleans, [1, 2, 4, 8, 16]); // gives 20
let flag = flagEncode(booleans, MyEnum.getValues()); // gives 20 as well

// MyEnum.getValues should be retrieving the same array as the first call => [1, 2, 4, 8, 16]
// The corresponding enum would be the following
const MyEnum = Enum.create(
{
    name: "MyEnum",
    identifiers:
    {
	IDENTIFIER_A:	  1,
	IDENTIFIER_B: 	  2,
	IDENTIFIER_C:    4,
	IDENTIFIER_D:    8,
        IDENTIFIER_E:    16
    }
});
```

Edit:
-----

Seems like you're already getting the values on this file, but just not using them for this purpose.
As they are already there, I don't think that would hurt to add a `Enum.getValues()` function to this file in order to be able to get the whole values as an array.
https://github.com/jagi/meteor-astronomy/blob/eb3cf960fe8f330b19fcc62b15a92f551ed63783/lib/modules/fields/Enum.js#L43

I will propose a PR in order to add the function to the package so we can get the values from the enumeration, if that's okay for you.

**Comment by lukejagodzinski** [comment]
Good idea. Merged PR
