### ISSUE TITLE
Updating foreign keys using set

### ISSUE THREAD

**Issue by chroz** [jagi/meteor-astronomy#67]
Hi again!

My relation is working fine, and I'm able to retrieve the related object successfully.
However, if i try to update the foreign key on my object using set() - 
retrieving the related object does not seem to work, I still get the original one. 

Any clue?
This is all client-side code, before trying to save the object.

**Comment by jagi** [comment]
Hi, post here you schema and the code that is not working properly.

**Comment by chroz** [comment]
Thanks - 

Sorry, i should also have made it clear that it was a one-to-one relation: 

@Models.ClientSession = Astro.Class(
  name: 'ClientSession'
  collection: ClientSessions
  fields: 
    name: 'string'
    duration: 'number'
    date: 'date'
    time: 'string'
    clientService_id: 'string'
  relations:
    clientService: 
      type: 'one'
      class: 'ClientService'
      local: 'clientService_id'
      foreign: '_id'


*** using: 

      sess = new Models.ClientSession()
      sess.set 'clientService_id', '5nQzBuamK83tjQryY' 
      console.log sess.clientService._id #5nQzBuamK83tjQryY <- id is retrieved properly
      sess.set 'clientService_id', '8QtgKwBBRKcFwjKtr' # <- trying to overwrite
      console.log sess.clientService._id #5nQzBuamK83tjQryY <- still the original document

Both documents exist, reversing the order produces a similar result.

**Comment by jagi** [comment]
Oh yes, there is an error in the code. I'm caching references and after changing id I'm not checking if it had changed. I will fix it in the next release. For, now I would recommend implementing relations by hand, what I've demonstrated [here](https://github.com/jagi/meteor-astronomy/issues/62#issuecomment-129974825)

**Comment by chroz** [comment]
Ok great, thanks!

I suppose the docs should also be updated with the importance of using set () for this to work, i suppose just setting the var directly will be difficult to detect.

**Comment by jagi** [comment]
I'm closing it here as it's related to the `relations` module. After creating the `forms` package I will focus on the `relations` module.
