### ISSUE TITLE
Functions inside objects trigger lots of warnings on schema validation

### ISSUE THREAD

**Issue by derwok** [jagi/meteor-astronomy#671]
First of all - thank you for providing this great package! We use it for Schema validation in our open source meeting minutes WebApp https://www.4minitz.com

We migrated from the aledeed:simple-schema to Astronomy.

When saving objects via Astronony we get this kind (client side) warning "all over the place":

```
["MeetingSeriesSchema" class]["findLabelByName" field] Trying to set a value of the field that does not exist in the class
["MeetingSeriesSchema" class]["upsertLabel" field] Trying to set a value of the field that does not exist in the class
["MeetingSeriesSchema" class]["getAvailableLabels" field] Trying to set a value of the field that does not exist in the class
```

`findLabelByName`, `upsertLabel` and `getAvailableLabels` are functions attached to the object to be stored. The reason for the warnings seem to be all thes "intelligent" functions. We enriched the "dumb" database objects by the functions defined in a separate class by tranforming them:

```
let MeetingSeriesCollection = new Mongo.Collection('meetingSeries', {
    transform: function (doc) {
        return new MeetingSeries(doc);
    }
});
```
The Schema is attached like so:
```
export const MeetingSeriesSchema = SchemaClass.create({
    name: 'MeetingSeriesSchema',
    collection: MeetingSeriesCollection,
    fields: {
        project: {type: String},
        name: {type: String},
        createdAt: {type: Date},
```

So, while we understand that Astronomy provides a way to add functions to objects inside the schema, this would be a rather huge refactoring for us. To "whitelist" our functions somehow inside the schema would lead to error prone house keeping.

But, as far as we know, functions can not be stored to MongoDB anyhow. So it seems save that they are stripped in insert/update operations or during validation. Or that they are simply not considered in validations. 

Our question now is: 
* Can we configure schema validation to ignore or silently clean functions attached to objects on insert/update? {Preferred}
* Or can we swallow the warnings that currently pollute the client log? {Preferred we could only do this for functions - other warnings are still of interrest!}
* Is there a pre-validation hook where we could somehow inject our removing of functions {Helpful. But not really preferred... as it modifies the object that might be used after insers/update. This might lead to some surprises of the caller}

**Comment by lukejagodzinski** [comment]
Hi, as you correctly noticed, the reason for getting these warnings is that you're using transform function and adding them to the dumb/raw/pure objects. And yes, you can't store functions in MongoDB.

However, warnings are not related to saving documents by Astronomy. When you save a document it gets a list of fields in the schema and tries to save only them.

For now, you can turn off warnings. It's described in docs, however I will paste it here:

```js
import { Astro } from 'meteor/jagi:astronomy';

// Do not log deprection warnings.
Astro.config.verbose = false;
```

Indeed, I could just strip objects out of functions when saving but that would be an extra step that would influence performance and I want to minimize the amount of work during all the operations.

**Comment by derwok** [comment]
Thanks for your comment.
I understand we can turn off logging completely.
But we still find it useful in many other cases.
And I understand that you are careful about perfomance issues (Cleaning up function fields would take time...).

But would it be possible to just skip logging warnings for function fields not part of the schema?
As functions are never stored in Mongo, this warning is confusing?

**Comment by lukejagodzinski** [comment]
@derwok right now I'm just checking if a field being set is defined in the schema, so it's very fast. If I'm gonna check every single field's type then it will be super slow. So I'm not gonna check that. The only thing I could do is introduce another config option to turn off all the warnings for the extra fields.

However, I'm not using warnings in many places. Beside deprecation warnings, the extra field warnings are the only one. So if you find logging useful in other places, then I wonder in what places?

**Comment by derwok** [comment]
@lukejagodzinski Yes, maybe we simply switch off all messages. If you think this makes sense.

My point was, that enriching "stupid" database objects with some methods/functions is quite a common pattern to my knowledge... so we thought, maybe it would be a good idea to handle this scenario not with a warning. Additionally of course we are interested in all other "real" warnings - whatever they are (you mentioned deprecated warnings! => Yes good example! We would love to see them, but the ones we discussed above just clutter our users console...).

Nevertheless: If you feel this "filtering" might have too big perfomance influence, then feel free to close this issue. We will go for your `Astro.config.verbose = false;`proposal in that case. Thanks for pointing out!
If you keep this issue open we will interpret this as "maybe some clever filter mechanism will happen one day", so we'll wait for that.

Thanks for all your great work and happy & successful 2019!

**Comment by lukejagodzinski** [comment]
@derwok ok I've introduced several flags for turning off warnings in Astronomy 2.7.1:

```js
import { config } from "meteor/jagi:astronomy";

config.logs.deprecation = false; // Turn off deprecation warnings.
config.logs.nonExistingField = false; // Turn off warnings about non existing fields.
config.logs.classDuplicate = false; // Turn off class duplication warnings.
config.logs.typeDuplicate = false; // Turn off type duplication warnings.
```

You can turn off all of them just by setting `config.verbose = false` too.

**Comment by derwok** [comment]
Hey @lukejagodzinski,
it took me a few month to find time to make use of your new config API in our project.
So now I found out: the syntax is a little bit different than you stated above.
We had to to it like this (Otherwise we got `unresoveld symbold config`):

```
import { Astro } from 'meteor/jagi:astronomy';
Astro.config.logs.nonExistingField = false; // Turn off warnings about non existing fields.
```

Maybe you want to update your docs somehow?
Nevertheless - its working like a charm on our side!
Thanks again for your great package and the new config possibility. Our client side log is much cleaner now!

**Comment by lukejagodzinski** [comment]
@derwok it's already described here: http://jagi.github.io/meteor-astronomy/#global-configuration

**Comment by derwok** [comment]
Hi @lukejagodzinski,
yes - and as I said, it does not work as described.
This sentence of docs:
`You can also import config object directly import { config } from 'meteor/jagi:astronomy'.`
seems not true. We got "Unresoved symbol" errors at runtime and inside the WebStorm IDE with this.

So, also the example in the docs did not work for us:
```
Example:
import { config } from 'meteor/jagi:astronomy';
// Do not log warnings.
config.verbose = false;
```

I think root cause is here:
https://github.com/jagi/meteor-astronomy/blob/1dc8d1c7ab6fd2f278f98113ffae016bde202869/lib/main.js#L49
no 'config' but only Astro is exported.

**Comment by lukejagodzinski** [comment]
@derwok probably I forgot to export it. For now you can just `Astro.config` instead
