### ISSUE TITLE
Class name conflict

### ISSUE THREAD

**Issue by davidsavoie1** [jagi/meteor-astronomy#675]
Hi!

I've just spent -- too much -- time trying to find a bug in my Astronomy code that I've finally found. There was a name conflict between two classes, one being a main class linked to a collection, the other an internal class used as nested validation for another main class. The thing is that when I was invoking any Meteor method on an instance of the main class, nothing would happen. However, I could see the method in its prototype, helpers were working and meteorMethods were fine on other classes.

Would there be a way to at least warn us when we're using an already existing class name? This kind of bug is my fault of course, but was VERY hard to find since things were working only partly and I could see no error whatsoever...

Regards!

**Comment by lukejagodzinski** [comment]
Hey, yes it was requested feature by some people already. I will add warning or just throw an error if somebody tries to reuse class name. However, I'm not so sure about throwing error as there might be people already using it incorrectly and their apps would break after updating. So for now warning might be a better solution.

**Comment by davidsavoie1** [comment]
Warning would be fine, since it's always something we try out in development anyway. Thanks for the support!

**Comment by lukejagodzinski** [comment]
Fixed in version 2.5.8
