### ISSUE TITLE
How to handle different Astronmy classes on server/client?

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#677]
Hey,
I'm having a question about handling different definitions on server and client. For example, I'm using a "global" definition of my Astronomy object and importing it on client and server, f.e.:

/imports/collections/videos.js

```
const videoObj = {
     name: 'Video',
    collection: Videos,
    fields {....}
}
```

Then I'm importing this object into client and server and add some values to it (f.e. on the server side some beforeRemove events and also some stuff that shouldn't be sent to the user).

/imports/server/collections/videos.js

```
import {videoObj} from '/imports/collections/videos';

const video = ...extending videoObj...;
const Video = Class.create(video);
``` 

 Now I'm having a little issue with one of my helpers which is defined "globally" (in /imports/collections/videos.js):

```
helpers: {
   canRelease() {
        const countTitles = Video.find({title: titleRegEx, status: this.status}).count();
   }
}
```

Problem is, that Video isn't defined yet (it's the Astronomy object). It will be defined on client and server. How can I handle this issue? I've tried to use <code>this.find()</code> instead, but find isn't available in the context. I'v also tried to define the Astronomy class "globally" and importing it seperately on client and server - but the problem is, that I'm not able to add any new events to it, f.e. <code>beforeRemove</code>.

**Comment by lukejagodzinski** [comment]
It's probably a problem related with the import order. It's hard to tell what the problem is without reproduction repository.

**Comment by dnish** [comment]
Hey @lukejagodzinski,
just created a repo for you: https://github.com/dnish/meteor-astronomy-code-share

You'll get a <code>ReferenceError: Video is not defined</code> which happens because <code>Video</code> isn't defined in the imported definition. I create each Astronomy object separately on client and server, because we need to add some special methods on the server side. So I'm just wondering what's the right way to solve this issue.

**Comment by lukejagodzinski** [comment]
https://github.com/lukejagodzinski/meteor-astronomy-code-share however it's described in docs how to extend classes in one env

**Comment by dnish** [comment]
Argh, sorry, you right.
