### ISSUE TITLE
Run behaviors without saving to database.

### ISSUE THREAD

**Issue by MichaelOber** [jagi/meteor-astronomy#68]
Would it be possible to add a feature when you can run certain behaviors on an Astro object without it being saved to the database? Right now, I think they are only run when using .save();

A good use case for this would be when creating a user. Right now, in Meteor, you are locked into using Accounts.createUser and Accounts.onCreateUser. When meteor creates the user, none of the behaviors are run since .save() isn't used. 

In this situation, it would be useful to create a User instance inside the onCreateUser hook, and do something like `user.runBehaviors()` to have timestamps, slugs, etc. generated, and then grab those fields to send back with the onCreateUser response.

**Comment by jagi** [comment]
Oh good point. However implementing it could be tricky. The reason for that is that a behavior can not only hook into the process of saving of a document but it can also hook into almost any process happening in Astronomy.

Let's take the `timestamp` behavior. It uses the `beforeInsert` and the `beforeUpdate` events to set the `createdAt` and the `updatedAt` fields. So for this one we would need two methods:

```js
user.runBehaviorMethod('timestamp', 'createDate');
user.runBehaviorMethod('timestamp', 'updateDate');
```

or something like that.
For the `slug` behavior, we would need one method:

```js
user.runBehaviorMethod('slug', 'generateSlug');
```

However, I can't force any behavior creator to follow this principle. Of course, I can provide API that can be used but won't be obligatory.

Thanks for pointing this out. I will work on this issue.

**Comment by jagi** [comment]
I've already added methods for the `slug` behavior that can be invoked by developer at any time. I will add similar method for the `timestamp` behavior in the next week.
