### ISSUE TITLE
Move meteor-independent parts to NPM

### ISSUE THREAD

**Issue by krizka** [jagi/meteor-astronomy#681]
Astronomy itself is a great package for defining schemas and validation, also it could be other modules to couple it with many systems. Here is request and proposition of collaboration on moving meteor-independent parts of astronomy to NPM.

**Comment by lukejagodzinski** [comment]
@krizka recently I was advised to take a look at this package https://www.npmjs.com/package/typeorm that has almost everything that I ever wanted to do in npm version of Astronomy. So probably there no more need to create one :)

**Comment by RobertLowe** [comment]
I scanned through the code, and I could only see about 5 imports that we're meteor dependant, it shouldn't be too difficult to fallback/proxy through mongoose or something else. 

The benefit of writing it Meteor first is the client+server advantage, the benefit of falling back is portability (npm modules)

**Comment by lukejagodzinski** [comment]
Moving it to NPM would mean rewriting everything. It's not only about imports, it's mostly about code that is using these imports. I think everything is moving towards GraphQL and package like Astronomy which are heavily dependent on MongoDB will not be necessary in the future. Meteor will become build tool only. I hope it's the future that we'll see :P
