### ISSUE TITLE
Astronomy not working with webpack

### ISSUE THREAD

**Issue by Deadly0** [jagi/meteor-astronomy#688]
[ardatan:webpack](https://github.com/ardatan/meteor-webpack) provides a way to use Webpack with meteor. But for some reasons Astronomy can't be imported in project by webpack. I have reported this bug to @ardatan but he said it's not meteor-webpack bug https://github.com/ardatan/meteor-webpack/issues/40

It's important to me to migrate to Webpack, but i can't do it becouse of this bug with Astronomy :(

Thank you!

**Comment by lukejagodzinski** [comment]
It's definitely not something related with Astronomy. I would rather say that's it's a bug in webpack package. Astronomy is working normally when you just use Meteor alone. In the last version of Astronomy I've introduced lazy loading, so maybe this webpack plugin does not work well with this kind of scenarios. Try using it with different Astronomy versions and see if it's producing the same error. And if it's not gonna help then create a reproduction repository so I will be able to check it

**Comment by Deadly0** [comment]
@lukejagodzinski you are right, old versions works fine. In which version lazy loading was introduced?

**Comment by lukejagodzinski** [comment]
@Deadly0 it was the last one version 2.6.0. In the version 2.5.8 there was no lazy loading.
So as I said it's maybe not bug but a lack of feature in the webpack package. It's not so uncommon to have Meteor packages with the lazy loading feature, so I think that the webpack package should take that into account.

**Comment by Deadly0** [comment]
@lukejagodzinski thank you!

**Comment by alexpricedev** [comment]
Yeah I'm having the same issue. @Deadly0 did you resolve it?

**Comment by Deadly0** [comment]
@Deadly0 no, but workaround is to use v2.5.8 of astronomy.

**Comment by alexpricedev** [comment]
Yeah thats that I've done! Let me know if you look into it again
