### ISSUE TITLE
Is this prod ready?

### ISSUE THREAD

**Issue by AdamBrodzinski** [jagi/meteor-astronomy#69]
This looks really great! Is this production ready even though it's not fully complete yet? Does it have high test coverage? (I see there are some tests).

At the least I wanted to try it out on my [Reactive Meteor](https://github.com/adambrodzinski/react-ive-meteor) example repo.

Cheers :beers:

**Comment by jagi** [comment]
Hi, thanks :)

I've heard that some people used it in production and they were happy with it. But I always warn that before 1.0 release anyone use it on his/her own risk :). The 1.0 version is not so far from now, so you can just wait for it :).

If it goes about tests, I'm working on it right now. The `nested` branch is the one on which I'm working currently and as you can see [here](https://github.com/jagi/meteor-astronomy/tree/nested/test), there are a lot more tests. I've already covered with tests like 70% of the package.

I would be happy if you use it. It definitely would be a good source of feedback.

One more thing to mention here is that in the next version there will be a little change in definition of nested fields, so people using it, will have to update their schemas.

**Comment by AdamBrodzinski** [comment]
Very cool! I'll try it out on the Reactive meteor demo first and then I have a greenfield app to build in another month or two so it should be ready by then. I'm sooo tired of writing my own anemic model facades :laughing: 

Feel free to close this (not sure if it's helpful for others)
