### ISSUE TITLE
Changelog is behind by two years

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#692]
I'd like to point out that having an up to date changelog would be a good thing.

Currently `HISTORY.md` is at `2.1.0` and releases are going somewhere around `2.5.8`.

Just thought I'd mention this in case it's unintentional.

**Comment by lukejagodzinski** [comment]
@arggh yep I haven't been updating `HISTORY.md` file as I was mostly focusing on describing changes in the release notes. I should probably remove `HISTORY.md` file all together or just redirect people reading it to the release notes. What do you think?

**Comment by arggh** [comment]
Personally, I'd just copy over the release notes to `HISTORY.md` and keep it up-to-date. But If it's no longer maintained, I'd probably remove it as it leads to confusion. Even if removed, it can still be found in version control if necessary.

**Comment by lukejagodzinski** [comment]
I will probably copy notes to HISTORY.md and keep it up to date from now

**Comment by lukejagodzinski** [comment]
Ok HISTORY.md updated
