### ISSUE TITLE
ObjectID vs String

### ISSUE THREAD

**Issue by RemyLespagnol** [jagi/meteor-astronomy#693]
Hello @lukejagodzinski,

I have a weird behavior and I don't know if it's an error from my code or a missunderstanding of the package.

I have this collection:
```
import {Mongo} from 'meteor/mongo';
import {Class, Enum} from 'meteor/jagi:astronomy';
import {Clients} from './client';

const State = Enum.create({
    name: 'State',
    identifiers: ['CREATED', 'ASSIGNED', 'REVIEWED']
  });

export const _warnings = new Mongo.Collection('warnings');

export const Warnings = Class.create({
    name: 'Warnings',
    collection: _warnings,
    fields: {
      state: {
        type: State,
        default: 'REVIEWED'
      },
      client: {
        type: Mongo.ObjectID,
        optional: true
      },
      group: [Mongo.ObjectID],
      news: [Mongo.ObjectID],
      history: [Mongo.ObjectID]
    }
});
```

On the client I send to a `Meteor.call` the `_id` from the warning object that I have fetch from a publication.

On the server, I receive the ObjectID.
With a `findOne(_id)`, it's working, I can have my object from the DB.
But after a `.save()`, on the client I receive `_id has to be a string [validation-error] `.

OK weird... So I send the `_id._str` value to the server.
But the `findOne(_id)` doesn't find something...

I don't understand this problem and why I cannot use the `String` type to fetch the object.

And I don't understand why when I send the ObjectID I cannot save my object... (I just change the state value of this object).

Do you have an idea ? :/

EDIT:
My DB comes from another application where it uses mongoose as a data acess layer. Mongoose generate ObjectID. And Astronomy generate String.
So I put `{_id: Mongo.ObjectID}` in the Class. But now, I cannot create a new Object with `new Warning(...).save()` => `_id" has to be a Mongo.ObjectID`

```
 new Warnings({
        state:state,
        group: [],
        news: [],
        history:[],
        client: null
      }).save();
```

Thx

**Comment by lukejagodzinski** [comment]
@Themandunord you description is a little bit vague :P but I think that it comes down to ObjectID vs String. If you have ObjectIDs in the Mongo database then you have to use MongoIDs everywhere. You can't later fetch anything using String. It's nothing related with Astronomy but with MongoDB/Meteor overall.

From what I remember, you can just use Mongo.ObjectID in Astronomy just by doing this:

```js
const Warning = Class.create({
  name: 'Warning',
  /* ... */
  fields: {
    _id: {
      type: Mongo.ObjectID
    }
  }
});
```

**Comment by RemyLespagnol** [comment]
@lukejagodzinski Clearly :D Sorry for that.

So yes, when I defined the fields `_id` in the Class, it is working.

Now when I want to create a new object, just do : 
```
 new Warnings({
        state:state,
        group: [],
        news: [],
        history:[],
        client: null
      }).save();
```

It doesn't work because `_id" has to be a Mongo.ObjectID`.

I do `_id: new Mongo.ObjectID()` and it's working. It is the good way for you?

**Comment by lukejagodzinski** [comment]
@Themandunord it's correct but you can also generate IDs automatically just by defining collection in the following way:

```js
const Warnings = new Mongo.Collection("warning", { idGeneration: "MONGO" });
```

**Comment by RemyLespagnol** [comment]
Love you ❤️ 

Thanks !
