### ISSUE TITLE
Is there any beforeValidation event?

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#696]
Hey,
I'm trying to clean an object from empty fields before doing the final validation. I know that there is a beforeSave method, but If I got it right, this one is fired after the validation (when I call the .save() method of the object).

For example, I'm doing something like this:

```
   beforeSave(e) {

          e.target.updatedAt = new Date();
          e.target.resources = e.target.resources.filter(r => r.value !== ''); // Filter all empty values


        }
```

My current approach is to manipulate the value property within my own validator, but I don't like this approach because the validator shouldn't mutate the data. Any idea how I can filter my data before doing the validation?

**Comment by lukejagodzinski** [comment]
You can create [helper method](http://jagi.github.io/meteor-astronomy/v2#helpers) in which you will clean data and later invoke the `save()` method
