### ISSUE TITLE
Can I get the previous doc data in the Update event? 

### ISSUE THREAD

**Issue by mingz-unity** [jagi/meteor-astronomy#697]
Hi coming from collection-hook and wonder if the same feature is available here: 

When I am in one of those collection update events, can I have access to the previous value so I can do some change handling? I inspected the runtime class of "e" and it only contains the changed value not the original. 

Is there anywhere I can get that? 
Thanks

**Comment by lukejagodzinski** [comment]
@mingz-unity in the newest Astronomy version you can access the old document in the `beforeUpdate` event in the following way:

```js
beforeUpdate(e) {
  e.oldDoc; // Do something with the previous document state
}
```

**Comment by mingz-unity** [comment]
Cool cool that's great. Yes I dig into the source code and found out. That's great thanks Luke.

**Comment by s7dhansh** [comment]
`oldDoc` is not available on the server? Is it by design? @lukejagodzinski

**Comment by lukejagodzinski** [comment]
@s7dhansh thanks for letting me know that it doesn't work on the server. I've fixed it in `jagi:astronomy@2.7.3`

**Comment by s7dhansh** [comment]
@lukejagodzinski the new version has made the updates take a lot of time. Can you kindly check that? Can we have some way to make it faster when we have `disabledEvents` for an update?

**Comment by lukejagodzinski** [comment]
Ok, I will check that this week and try to improve performance

**Comment by s7dhansh** [comment]
@lukejagodzinski sorry you can ignore that last comment. It was caused by something else locally.
