### ISSUE TITLE
Can schema handle properties like 'members.$.userId'?

### ISSUE THREAD

**Issue by banglashi** [jagi/meteor-astronomy#7]
Would this be feasible? Like in simple-schema?

**Comment by jagi** [comment]
I don't quite understand what is the function of `"members.$.userId": {type: 'string'}`. Does it define the type of the nested field? `members` array where any object in the array can have `userId` field of `string` type? Am I correct?

**Comment by banglashi** [comment]
yes, that's the idea, like in simple-schema -> https://github.com/aldeed/meteor-simple-schema#schema-keys

**Comment by jagi** [comment]
I think that it will work in different way in Meteor Astronomy. Of course it should be possible to define types of fields for nested objects and also be able to validate such objects.

I think it will be done automatically. I'm planning to introduce relations feature. It would look something like...

```js
Chat.schema.addRelation('members', {
  type: 'many',
  collection: Member,
  local: '_id',
  foreign: 'chatId'
});
```

... or in the definition...

```js
Chat = Astro.Class({
  /* ... */
  fields: {
    /* ... */
  },
  relations: {
    'members': {
      type: 'many',
      collection: Member,
      local: '_id',
      foreign: 'chatId'
    }
  }
});
```

or something like this. Thanks to that `members` field would be added automatically with the correct type. Validation would work out of the box etc. It will be big feature so it will take some time to implement but as always stay tuned :)

**Comment by banglashi** [comment]
sounds great and a better way to solve it. Will stay tuned ;)

**Comment by jagi** [comment]
@banglashi ok I've made it work. Now you can validate nested fields. You can read more here https://github.com/jagi/meteor-astronomy/wiki/Validators or here https://github.com/jagi/meteor-astronomy/wiki/Simple-Validators.
