### ISSUE TITLE
Any thoughts on JSON Schema?

### ISSUE THREAD

**Issue by jakobrosenberg** [jagi/meteor-astronomy#70]
Have you considered implementing the JSON Schema specification?

**Comment by jagi** [comment]
What do you mean by saying "JSON Schema specification"?

**Comment by jakobrosenberg** [comment]
http://json-schema.org/

Structuring JSON objects according to json-schema.org could help with 3rd party compatibility. Form generators, validators, etc.

**Comment by jagi** [comment]
It doesn't seem to be used by many developers. Right now I don't see any benefit of implementing it. Maybe someday in the future someone will implement module for Astronomy that allows export to these kids of schemas.

However, even though 1.0 version of Astronomy isn't ready yet, I'm thinking about 2.0 version which will be based on JSON schema specification (however not compatible with the one you mentioned). All the schemas will also be prebuild during Meteor startup. Thanks to that it will be much faster to run Meteor application using Astronomy. It will also use ES2015 classes. It's only a plan, we will see what the future will bring.

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.

**Comment by james1293** [comment]
Did this ever come to fruition?

I'm considering writing a (basic) Astronomy schema to JSON schema converter because there's a [Typescript tool](https://www.npmjs.com/package/json-schema-to-typescript) that I'd like to use which expects the JSON Schema style.

**Comment by lukejagodzinski** [comment]
Currently I have no plans to implement this feature, but if you want to try, then such a contribution is more than welcome :)
