### ISSUE TITLE
More useful method names

### ISSUE THREAD

**Issue by yorrd** [jagi/meteor-astronomy#703]
Right now, it seems like you're hiding all method calls on astronomy objects behind the /Astronomy/execute "endpoint". This leads to Kadira not giving me very useful information about its statistics. 

![image](https://user-images.githubusercontent.com/1191486/56274951-10b98a00-6100-11e9-8d0c-85320a9394ca.png)

What about opening an endpoint for each method so that the statistics are meaningful again?

**Comment by lukejagodzinski** [comment]
You're not force to use Astronomy methods. You can define them just in regular way and name theme whatever you want:

```js
Meteor.methods({
  whateverNameIWant() {}
});
```

Ability to Meteor methods from the schema definition is just a "syntactic" sugar (if I can call it that way).

Changing how it works right now, could be possibly a breaking change.
