### ISSUE TITLE
[Feature Request] doc.save() return a promise

### ISSUE THREAD

**Issue by lucaciraolo** [jagi/meteor-astronomy#709]
It would be very useful to have doc.save() return a promise instead of using a callback so that we can use es6 async/await syntax!

**Comment by lukejagodzinski** [comment]
Astronomy was created when using async/await was not so common in Meteor, especially in Meteor methods. Such change would be a breaking one, so no plans to introduce it for now

**Comment by lucaciraolo** [comment]
What about adding a savePromise() method? I feel like it is an importand feature if you want people to keep using this as async/await becomes more and more prevalent.

**Comment by lukejagodzinski** [comment]
I can investigate that option but don't have time for that now. Astronomy is currently my side project
