### ISSUE TITLE
Updating Meteor.users Collection

### ISSUE THREAD

**Issue by andrerfneves** [jagi/meteor-astronomy#71]
Jagi, 

Been having some trouble with applying the Astronomy View Layer to the Meteor.users collection. What I'm trying to achieve is a simple Edit Profile page, where logged in users can change things like First Name, Last Name, Age, Email and so forth. My idea is to have a form with inputs that display this data. Screenshot below. 
<img width="749" alt="screen shot 2015-08-18 at 3 28 45 pm" src="https://cloud.githubusercontent.com/assets/2574011/9340487/fbc48124-45bd-11e5-951f-86c9ddcbc469.png">

I want users to be able to edit those fields (if they want to modify the content) and then once they press SAVE I want to validate all the fields and then call the Meteor Method to update the user's user object. 

Below is all the code for the page:

```javascript
Template.editProfile.events({
    'change input': function(e, tmpl) {
        var user = Meteor.users.findOne();
        console.log(user);
        var field = e.currentTarget;
        console.log(field.value);

        user.set(field.id, field.value);
        user.validate(field.id);
    },
    'click #save-profile': function(e, tmpl) {
        var user = Meteor.users.findOne();
        console.log(user);

        if (user.validate()) {
            Meteor.call('/user/save', user, function(err) {
                if (!err) {
                    sweetAlert("Edit Successful", "Your profile has been updated successfully.", "success");
                } else {
                    user.catchValidationException(err);
                    console.log(err);
                }
            });
        }

    },
}):
```
console.logs are just so I can make sure the data from the 'change input' event is called/correct. When I press SAVE, it seems that the RPC Method is called and has no error, as the alert pop up shows up confirming success. That being said, the user object does not receive the new/modified data. Below is my method call:

```javascript
Meteor.methods({
    '/user/save': function(user) {
        if (user.validate()) {
            user.save();
            return user;
        }

        user.throwValidationException();
    }
}):
```

I figured this could have to do with Allow and Deny rules so I added this as well:

```javascript
Meteor.users.allow({
    'update': function(userId, doc, fields, modifier) {
        return userId === doc.userId;
    }
});
```
What am I doing wrong? Why won't the updated user object's records appear in the database? Is there another way that you see might be better in order to handle this 'Edit Profile' page?

Thanks in advance my man!

**Comment by ribbedcrown** [comment]
Hi, @andrerfneves!
You have different model instances for `change input` and `click #save-profile` events. While "change" instance is filled with new data, the "save" instance handles only actual db data. 

As solution: 
``` javascript
Template.editProfile.onCreated(function() {
    this.data.user = Meteor.users.findOne();
});

Template.editProfile.events({
    'change input': function(e, tmpl) {
        var field = e.currentTarget;

        this.user.set(field.id, field.value);
        this.user.validate(field.id);
    },
    'click #save-profile': function(e, tmpl) {
        var self = this;

        if (this.user.validate()) {
            Meteor.call('/user/save', this.user, function(err) {
                if (!err) {
                    sweetAlert("Edit Successful", "Your profile has been updated successfully.", "success");
                } else {
                    self.user.catchValidationException(err);
                    console.log(err);
                }
            });
        }

    },
}):
```

**Comment by andrerfneves** [comment]
@ribbedcrown thanks for the quick response. I just tried you code and though it makes sense what you said about two model instances of the User object, I now receive a TypeError

```javascript
TypeError: this.user is undefined
```
It seems that this is getting called here (line 10):
```javascript
this.user.set(field.id, field.value);
```

Any idea why that might be?

**Comment by ribbedcrown** [comment]
@andrerfneves maybe subscription trouble. Meteor.users.findOne() returns undefined? Similar solution works for me fine

**Comment by andrerfneves** [comment]
Meteor.users.findOne() returns the current user object as expected. 

<img width="589" alt="screen shot 2015-08-18 at 4 51 10 pm" src="https://cloud.githubusercontent.com/assets/2574011/9342384/5ab60224-45c9-11e5-9644-a973309fa685.png">

Do I need to have some sort of subscription on the router/template? I know I don't need to subscribe to the user object but maybe I need to have some Astronomy-specific calls that I'm missing?

**Comment by andrerfneves** [comment]
@ribbedcrown Are you using Iron Router or Flow Router? Do you have any calls on the ```subscription``` or ```waitOn``` fields for the route?

**Comment by banglashi** [comment]
@andrerfneves can u post the html part?

If you setup this.data.user at onCreated you should use tmpl.data.user to get that value unless you have a user as a data context on the editProfile template
```
'change input': function(e, tmpl) {
        var field = e.currentTarget;
        user = tmpl.data.user;
        user.set(field.id, field.value);
        user.validate(field.id);
    },
```

**Comment by ribbedcrown** [comment]
@andrerfneves Yeah my bad! Wrong context at event handler. 

@banglashi Thank you)

**Comment by andrerfneves** [comment]
@banglashi, here's my .html for editProfile. Ignore the extra helpers like isThirdPartyLogin and isDisabled. Those are helpers that check whether the user is signed on with FB/Google (and then disable the field to change names/email...) or straight up accounts-password.

```html
<template name="editProfile">
    {{#with currentUser}}
    <div class="ui form">
        <div class="two fields">
            <div class="{{isThirdPartyLogin currentUser._id}} field">
                <label>Nome</label>
                <input name="firstName" id="firstName" disabled="{{isDisabled currentUser._id}}" value="{{profile.firstName}}" type="text">
            </div>
            <div class="{{isThirdPartyLogin currentUser._id}} field">
                <label>Sobrenome</label>
                <input name="lastName" id="lastName" disabled="{{isDisabled currentUser._id}}" value="{{profile.lastName}}" type="text">
            </div>
        </div>
        <div class="{{isThirdPartyLogin currentUser._id}} field">
            <label>Email</label>
            <input name="Email" disabled="{{isDisabled currentUser._id}}" value="{{userEmail currentUser._id}}" type="email" id="email">
        </div>
        <div class="{{isThirdPartyLogin currentUser._id}} field">
            <label>Imagem de Perfíl</label>
            {{> upload_semanticUI}}
        </div>
        <div class="field">
            <label>Organização</label>
            <input name="Email" id="organization" value="{{profile.profPicture}}">
        </div>
        <div class="field floated right">
            <div class="ui green button" id="save-profile">Salvar</div>
            <div class="ui button">Reset</div>
        </div>
    </div>
    {{/with}}
</template>
```
And here's the modified JS. 

```javascript
Template.editProfile.onCreated(function() {
    this.data.user = Meteor.users.findOne();
});

Template.editProfile.events({
    'change input': function(e, tmpl) {
        var field = e.currentTarget;
        user = tmpl.data.user;

        user.set(field.id, field.value);
        user.validate(field.id);
    },
    'click #save-profile': function(e, tmpl) {
        var self = this;

        if (this.user.validate()) {
            Meteor.call('/user/save', this.user, function(err) {
                if (!err) {
                    sweetAlert("Edit Successful", "Your profile has been updated successfully.", "success");
                } else {
                    self.user.catchValidationException(err);
                    console.log(err);
                }
            });
        }
    }
});
```
With the exact code above, I'm still getting the following errors:
<img width="590" alt="screen shot 2015-08-18 at 5 31 11 pm" src="https://cloud.githubusercontent.com/assets/2574011/9343289/09d56fba-45cf-11e5-81f8-d3bc3f6e3e65.png">
The first is for the 'change input' event and the other is for the 'save' event.

Thanks in advance for all the help @banglashi and @ribbedcrown!

**Comment by ribbedcrown** [comment]
@andrerfneves, without data context headache:
``` javascript

var user;

Template.editProfile.onCreated(function() {
    user = Meteor.users.findOne();
});

Template.editProfile.events({
    'change input': function(e, tmpl) {
        var field = e.currentTarget;

        user.set(field.id, field.value);
        user.validate(field.id);
    },
    'click #save-profile': function(e, tmpl) {
        if (user.validate()) {
            Meteor.call('/user/save', user, function(err) {
                if (!err) {
                    sweetAlert("Edit Successful", "Your profile has been updated successfully.", "success");
                } else {
                    user.catchValidationException(err);
                    console.log(err);
                }
            });
        }

    },
}):
```

**Comment by andrerfneves** [comment]
@ribbedcrown I completely understand the problems I had on my code, and I get the data context headache situation. That being said, both your code and @banglashi's modification seem to do what I want (in theory), but I continue to get the same errors. One for when I make changes to the input at line 11:9 (user is undefined) and another when I click the save button at line 15:1 (user is undefined).

That being said, ``` user = Meteor.users.findOne();``` does not return undefined, it actually returns my user object as it should.

I'm also assuming my HTML does not have any errors?

Reading the code, this seems simple and straightforward, yet I'm not quite sure what is happening.

Thanks again!

**Comment by ribbedcrown** [comment]
@andrerfneves no, no troubles with html. Spending some time I found that `this.user is undefined` error from my first "solution" disappears when velocity is turned off with VELOCITY=0.
I have no idea yet why this happens, but it's not Astronomy issue. We need to dig into the source code, maybe we are doing it wrong.

**Comment by banglashi** [comment]
@andrerfneves try this:

```handlebars
<template name="editProfile">
    {{#with user}}
    <div class="ui form">
        <div class="two fields">
            <div class="{{isThirdPartyLogin currentUser._id}} field">
                <label>Nome</label>
                <input name="firstName" id="firstName" disabled="{{isDisabled currentUser._id}}" value="{{profile.firstName}}" type="text">
            </div>
            <div class="{{isThirdPartyLogin currentUser._id}} field">
                <label>Sobrenome</label>
                <input name="lastName" id="lastName" disabled="{{isDisabled currentUser._id}}" value="{{profile.lastName}}" type="text">
            </div>
        </div>
        <div class="{{isThirdPartyLogin currentUser._id}} field">
            <label>Email</label>
            <input name="Email" disabled="{{isDisabled currentUser._id}}" value="{{userEmail currentUser._id}}" type="email" id="email">
        </div>
        <div class="{{isThirdPartyLogin currentUser._id}} field">
            <label>Imagem de Perfíl</label>
            {{> upload_semanticUI}}
        </div>
        <div class="field">
            <label>Organização</label>
            <input name="Email" id="organization" value="{{profile.profPicture}}">
        </div>
        <div class="field floated right">
            <div class="ui green button" id="save-profile">Salvar</div>
            <div class="ui button">Reset</div>
        </div>
    </div>
    {{/with}}
</template>
```

and for the js

```javascript
Template.editProfile.onCreated(function() {
    this.user = Meteor.users.findOne();
});

Template.editProfile.helpers({
    user: function(){
        return Template.instance().user;
    }
});
Template.editProfile.events({
    'change input': function(e, tmpl) {
        var field = e.currentTarget;
        user = this;

        user.set(field.id, field.value);
        user.validate(field.id);
    },
    'click #save-profile': function(e, tmpl) {
        user = this;
        if (user.validate()) {
            Meteor.call('/user/save', user, function(err) {
                if (!err) {
                    sweetAlert("Edit Successful", "Your profile has been updated successfully.", "success");
                } else {
                    user.catchValidationException(err);
                    console.log(err);
                }
            });
        }
    }
});
```

**Comment by andrerfneves** [comment]
@banglashi So your code didn't work, but I changed one little thing and it finally worked! 

I moved the call for the user object to the helper and removed the oncreated call for the object instance, like this:

```javascript

Template.editProfile.helpers({
    user: function() {
        return Meteor.users.findOne();
    }
});

Template.editProfile.events({
    'change input': function(e, tmpl) {
        var field = e.currentTarget;
        user = this;

        user.set(field.id, field.value);
        user.validate(field.id);
    },
    'click #save-profile': function(e, tmpl) {
        user = this;
        if (user.validate()) {
            Meteor.call('/user/save', user, function(err) {
                if (!err) {
                    sweetAlert("Edit Successful", "Your profile has been updated successfully.", "success");
                } else {
                    user.catchValidationException(err);
                    console.log(err);
                }
            });
        }
    }
});
```
Just glad it works now. Not quite sure why the other code wasn't working but this one works perfectly. Also, remember to have your input's id match your user's db schema, otherwise the field will never 'set' in the view layer in the first place.

Cheers for all the help @ribbedcrown and @banglashi

**Comment by jagi** [comment]
Thanks guys for helping solving this issue :-). Thanks to your help I can focus more on improving astronomy :-)
