### ISSUE TITLE
Getting field definition

### ISSUE THREAD

**Issue by meecect** [jagi/meteor-astronomy#717]
I see I can get: 

```
MyClassName.definition.fields.myFieldName
```

Is that the recommended way to do it?  Is there a way to do it from the class instance?   In general, is it possible to get the Class object from the instance?

Basically, I would like to do something like:

```
thing = new Thing({some data});

thing.getDefinition().fields['somefield'];

```

**Comment by lukejagodzinski** [comment]
You can do:

```js
const thing = new Thing({/* data */});
thing.constructor.getFields();
thing.constructor.getField("somefield");
```

**Comment by meecect** [comment]
perfect, thanks.
