### ISSUE TITLE
How to mock meteor method call when declaring method in class?

### ISSUE THREAD

**Issue by JoaoCardoso193** [jagi/meteor-astronomy#725]
I'm trying to test an app I'm building using Astronomy. In some of my tests, I need to mock method calls to methods I defined in a class (using `meteorHelpers` in my class definition). The package I'm using to mock meteor calls is quave:testing (https://atmospherejs.com/quave/testing) and the syntax to make a mock method call as if from a user is:

```
 mockMethodCall('methodName', args, { context: { userId } });
```

The `context` object is important as these are authorization tests, that should return an authorization error if there is no current user logged on.

How can I mock calls to the methods I defined in my Astronomy classes? If not with quave:testing, is there another way or another package I can use to make mock calls to these methods in my tests?

**Comment by lukejagodzinski** [comment]
Astronomy registers the `/Astronomy/execute` method in `Meteor.methods` https://github.com/jagi/meteor-astronomy/blob/b238fbce73da94bba2fee75a8f55547c5b13a401/lib/modules/methods/hooks/onFinalizeClass.js#L19-L21. This Meteor method takes the `methodName` as one of the arguments https://github.com/jagi/meteor-astronomy/blob/b238fbce73da94bba2fee75a8f55547c5b13a401/lib/modules/methods/meteor_methods/astronomyExecute.js#L6-L11. So you can easily determine which one is being called and with what arguments (`methodArgs`).

**Comment by JoaoCardoso193** [comment]
Great, thank you for the quick and clear explanation!
