### ISSUE TITLE
Index creation issue.

### ISSUE THREAD

**Issue by ansarizafar** [jagi/meteor-astronomy#73]
I am trying to create index on a field in my schema
```
BizTypes = new Mongo.Collection('biztypes');

BizType = Astro.Class({
    name: 'BizType',
    collection: BizTypes,
    fields: {
        typeName: {
            type: 'string',
            index: 1,
            validators: [
                Validators.required(),
                Validators.string(),
                Validators.maxLength(40)
            ]
        }
    }
});
```
When a save new document by using BizType.save()  no index is created on typeName field in MongoDb collection. Please help me resole this issue.

**Comment by jagi** [comment]
Hmm strange, I've created Meteor project and pasted your code. Index was created. How are you checking for an index existence?

```sh
meteor mongo
db.biztypes.getIndexes()
```

Like that?

**Comment by ansarizafar** [comment]
Yes I have checked using mongo shell and MongoChef. there is no index on typeName field. I am also experiencing same issue with other collections.

**Comment by jagi** [comment]
Have you tried with different, clean Meteor project?

**Comment by jagi** [comment]
Hi, did you solve your problem? I'm making tests for Index modules and I've experienced similar situation. Index was not created. The problem was with trying to create index for the field that already had index. Let's say that, we've defined index for the `firstName` field. Now when trying to define index for two fields the `firstName` and the `lastName` it will fail without any error. Maybe it's why you are experiencing this problem?

**Comment by ansarizafar** [comment]
No, the problem is still there. I don't already have index on the same field. I only have auto generated index on _id field in the same collection. I used Meteor reset and run the app several times but experiencing same problem.

**Comment by jagi** [comment]
Have you tried using the `Collection._ensureIndex` directly? Does it create index?

If yes could you create reproduction repository, so I would be able to work on the same code as you.

**Comment by jagi** [comment]
Please test out 1.0.0 RC version of astronomy https://github.com/jagi/meteor-astronomy/issues/97 to check out if it works for you
