### ISSUE TITLE
Allow non-schema fields in a document

### ISSUE THREAD

**Issue by cwohlman** [jagi/meteor-astronomy#74]
Oftentimes when I'm prototyping, or writing code that doesn't interact with users I want to add fields which don't really need to be a part of the schema - but right now those fields will simply be erased on save, I think it would be a good idea to optionally allow a 'non-strict' mode where fields which aren't part of the schema are saved as-is.

So this would work: 
```javascript
Post = Astro.Class({
  name: 'Post'
  , collection: Posts
  , fields: ['title']
});
var post = new Post({
  title: 'x'
  , name: 'y'
});
post.save() // currently drops name property
```

**Comment by jagi** [comment]
It's quite hard to implement, because Astronomy document contains not only fields and their values but also some private data like validation errors. Because of that it would try to save all properties that are stored in an object. Of course there are ways to avoid it but I think that if someone chooses to use schemas, then he/she is aware of what restrictions it introduces.

For, now I don't see good use case for implementing it. But I'm open for discussion :)

**Comment by cwohlman** [comment]
Honestly the only use case is fast-prototyping, in the long run (e.g. production) everyone should only use fields that are on the schema (if they're going to have a schema), but in the short run, the ability to use fields which are not on the schema would save the developer a lot of time if they're experimenting/prototyping because they might be changing the implied schema a lot. This was actually one of the things which bugged me about SimpleSchema was that I was always forgetting to add fields to the schema.

After looking at the code I did notice that it would take some non-trivial refactoring to implement, so I'll close this issue for now. If I find I'm still interested in the feature after using this package for a while I'll open a PR for discussion.

**Comment by jagi** [comment]
Ok great. I will add this feature to my list for future consideration.

**Comment by ianserlin** [comment]
+1 for this actually.

Being unable to use the `methods`, etc. features without pre-specifying the fields on a particular collection means that I either need to use a static utility function, or attach the transformation some other way (e.g. using meteor's collection `transform` directly or `dburles:collection-helpers`, etc.).

It is a valid use-case to be developing using many of the astronomy paradigms (even way before astronomy existed) and also have flexible schemas, which is one of the advantages of Mongo.

It would be preferable to _not_ tie every feature that astronomy implements to each other as hard dependencies... you've already got the whole astronomy module system going for that reason.

**Comment by jagi** [comment]
I would like to see some example use case. Not just any example but example from real life application. I can add this feature after 1.0 release if I see the need for this.
