### ISSUE TITLE
add isModified() method

### ISSUE THREAD

**Issue by banglashi** [jagi/meteor-astronomy#75]
Hi @jagi, hope you are well.
Would it make sense to have a isModified() method, that would return true as soon as it gets the first modified value? In my case I would use it to save a roundtrip to the server when the model has not been modified by the user but he chooses to save anyway. Let me know

**Comment by jagi** [comment]
Hi, thanks I'm well :). I'm working hard on new release and I'm very happy with what I've achieved as far :).

Getting to your question. Definitely it would make sense to add such method. I just would like to know more about your use case. Do you want this method to be reactive?

```js
// The "post" doc used in the template.
// Any modification of the field value in the template sets proper field in the "post".
var post = Posts.findOne();

Template.Post.events({
  'input change': function() {
    /* ... */
    post.set(fieldName, fieldValue);
  }
});

Meteor.autorun(function() {
  if (post.isModified()) {
    post.save(); // Reactive save
  }
});
```

Is it your use case, or you want it to do something different?

**Comment by banglashi** [comment]
yeah, keep up the good work. Really happy on how it's evolving. Regarding the question: actually in my use case I don't need it to be reactive, since the check will be done on a submit button. I just wanna save a server call if nothing changed. But I have to say I can see the use case for it being reactive too, so it's up to you on what makes more sense. There could be just a parameter isModified which is non-reactive and a method isModified() which is reactive. What do you think?

**Comment by jagi** [comment]
If you want to detect if there are any modification you can just use `getModified()` function. It's actually detecting all the changes to the document and returning them. You would only have to do it the following way:

```js
if (_.size(post.getModified())) {
  // Do something...
}
```

The `getModified()` method returns object with modified fields and their values. However, if there were n modifications, it returns empty object, so it's why you have to check it's size. I can implement it that way for now.

However reactive `isModified()` function would be also great. I've recently experienced situation where not having it makes it hard to implement certain feature. I will definitely add this in short future.

**Comment by jagi** [comment]
Feature implemented and will appear in 1.0 :). For now it's not reactive. Maybe in the future :)

**Comment by elidoran** [comment]
+1 for making it reactive. Would be nicer to only enable the submit button when isModified() returns true instead of allowing the button press and then rejecting because isModified() returns false.

Too new to using Astronomy to make a PR for you, but, I'll keep it in mind as I look around. :)

**Comment by jagi** [comment]
I'm going to introduce better `isModified` method in Astronomy 2.0 however it's still won't be reactive. As MDG is planning deeper integration with React there will be no reason to have reactivity (Tracker package anymore - if I understand their plans correctly :P). I don't know exactly how is it going to look like in future versions of Meteor so can't give you more details.

However, if it goes about the better `isModified` method I'm going to allow such syntax: `doc.isModified('firstName')` which will tell you if the `firstName` was modified. Of course you can check if there are any modifications by just calling `doc.isModified()`.
