### ISSUE TITLE
Will this work with SQL support in Meteor?

### ISSUE THREAD

**Issue by bensmeets** [jagi/meteor-astronomy#77]
Hi, how is this package going to work (if at all) with the most likely upcoming SQL support in Meteor? https://forums.meteor.com/t/an-early-look-at-sql-in-meteor/8736 

Will it bite each other or complement each other?

Cheers.

**Comment by jagi** [comment]
Hi, as long as SQL support is experimental it's not going to support it. However, when designing Astronomy I was planning to support other databases in the future so it's ready to deal with it. It won't need complete redesign to support SQL. It will be more like adding some features. As I know there are still many problems if it goes about SQL support. For instance the Accounts module is still based on the MongoDB, so you can't make a complete transition to SQL.

I'm also planning to give developers ability to use two database drivers in one application. But as I said earlier, we have to wait.

**Comment by andrerfneves** [comment]
Love the long term plans @jagi. Keep up the good work!

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.
