### ISSUE TITLE
Second event propagation example doesn't extend Child from Parent

### ISSUE THREAD

**Issue by dandv** [jagi/meteor-astronomy#79]
At /README.md#events-propagation

**Comment by jagi** [comment]
Thanks for noticing it. I'm working on website based documentation, more like docs.meteor.com and I will make fix there. This documentation on github will be shrinked to the basic description and for more there will be link to the full documentation. Repository for documentation will also be available on GitHub so anyone will be able to make PR's.

**Comment by dandv** [comment]
:+1:
