### ISSUE TITLE
Is it possible to apply Astronomy.Class to the Meteor.users collection?

### ISSUE THREAD

**Issue by banglashi** [jagi/meteor-astronomy#8]

**Comment by jagi** [comment]
Yes it is possible, but for now only on the client. You have to write.

```js
if (Meteor.isClient) {
  User = Astro.Class({
    name: 'User',
    collection: Meteor.users,
    fields: {
      emails: 'array'
    }
  });
}
```

and add to fields list any field that you have published. Right now it's not possible to do it on the server because Astronomy objects can be EJSONified but it's on my TODO list. So soon :)

**Comment by jagi** [comment]
Thanks to last update it's possible now to apply Astronomy.Class to Meteor users collection in both environments client and server. The minimal schema looks like this:

```js
User = Astro.Class({
  name: 'User',
  collection: Meteor.users,
  fields: {
    emails: 'array',
    services: 'object',
    createdAt: 'date'
  }
});
```

I will also add example to the documentation. Thanks for collaboration! :)
