### ISSUE TITLE
Simple-schema autovalue equivalent

### ISSUE THREAD

**Issue by dandv** [jagi/meteor-astronomy#80]
What is the best equivalent for [autovalues from Simple Schema](https://github.com/aldeed/meteor-simple-schema#autovalue)?

**Comment by jagi** [comment]
I'm not familiar with all Simple Schema features. Is it mostly for auto incrementing values?

**Comment by dandv** [comment]
[autovalue](https://github.com/aldeed/meteor-simple-schema#autovalue) is a field definition property that allows computing the value of the field based on other field values (e.g. something like `this.fullName = this.first + ' ' + this.last`) and of course, external data. One very common use case is adding a createdAt field in Collection2 - see https://github.com/aldeed/meteor-collection2/#autovalue

**Comment by shadowRR** [comment]
You can add autovalue with the 'behaviors' module. The 'timestamp' behaviors already permits you to add createdAt and updatedAt fields. So you should be able to do pretty much anything you want with those...
