### ISSUE TITLE
Having .getModified() on the afterupdate event

### ISSUE THREAD

**Issue by shadowRR** [jagi/meteor-astronomy#82]
Was wondering if it would be feasible to still have the original fields data in the afterupdate events ? This way, we could still call the getModified() to know if a wanted value has been changed and act accordingly.
Ex: If i need to update some fields in a different document (denormalized data), depending on if a particular field has been updated but i want to make sure that the update has been done without errors which then require the use of the afterupdate event...

**Comment by jagi** [comment]
Hmm yes it seems to be a good idea. It probably could break somebody's code when implemented. However, right now it limits a developer. I will change this in the next release.

**Comment by shadowRR** [comment]
I'm not sure i see where it could break somebody's code ? Since getModified() is always empty in an 'afterupdate' event, i don't see why anybody would use it... Or would he changed the way this function behave everywhere ?
Anyway, great to here it will be in the next release ;)

**Comment by jagi** [comment]
Oh yes, sorry it won't break anything :). I was just coming back from work when replying and it was just my quick thought that it will break something, but indeed it won't :).

**Comment by jagi** [comment]
Feature implemented and will appear in the next version. For now I'm closing this issue.

**Comment by shadowRR** [comment]
Ok. Can't wait :D

**Comment by shadowRR** [comment]
Hey @jagi,

It looks like the `getModified()` is available on the `afterUpdate()` and `afterInsert()` events, but not the `afterSave()` ?

**Comment by shadowRR** [comment]
Actually, scratch that. It's not available on `afterUpdate` either.

**Comment by jagi** [comment]
Ok good :)
