### ISSUE TITLE
Support for setting nested fields in instance constructor

### ISSUE THREAD

**Issue by ianserlin** [jagi/meteor-astronomy#83]
This example is supported:

```
var item = new Item();
item.set('object.property', 123);
item.get('object.property'); // -> returns 123
```

And so it would be excellent if the following was also supported (perhaps with the limitation that the field `object` would have to be specified with a default value of `{}`):

```
var item = new Item({'object.property': 123});
item.get('object.property');
// -> currently returns null (and perhaps should return undefined instead)
// -> would be awesome if it returned 123 as it can make handling input from complex forms easier
```

**Comment by jagi** [comment]
Right now, you have to specify entire chain of nested fields to achieve that.

```js
new Item({
  object: {
    property: 123
  }
});
```
However, it shouldn't be so hard to implement it. I would like to better know your usecase. Why you are trying to do that. Can't you do it the way I wrote?

**Comment by jagi** [comment]
Hehe, I was shocked to notice that it actually works in the newest version :). So as you said, as far as you set a default value of nested property to `{}` then it will work :).

Closing for now as it will appear in the next release.

**Comment by ianserlin** [comment]
Awesome, thank you!

For posterity, the use case is that because of the flexibility of mongo modifier syntax, you can easily support saving nested objects from forms by giving the input a name that matches the path into the object whose value you want to set.

e.g.

```
<input name="path.to.nested.property">
```

because

```
Collection.update(_id, { $set: { 'path.to.nested.property': "works as expected" } })
```

**Comment by jagi** [comment]
Oh ok, right
