### ISSUE TITLE
Astro validation on classic insert method

### ISSUE THREAD

**Issue by ezpub** [jagi/meteor-astronomy#84]
I have this scenario where I want to limit the number of documents a user can create. so I added the following code to Astro class. It works fine. BUT...

My questions is 
1. is it possible to return an error message instead of stop the execution of the event.
2. when you add validations to an Astro class, the validation only works if you save data through Astro like post.save(), it would NOT valid if I do Posts.insert({...}), so I can just open the console, and use the classic insert method to add invalid data to my database, how to solve this? In SimpleSchema, if I add validations, it validates against Posts.insert({...})

```javascript
    beforesave: function (e) {
            if(Collection.find().count() > 5){
                e.stopPropagation();
            }
        }
```

**Comment by jagi** [comment]
Limiting amount of documents that you can insert into collection is rather not the use case for validators. Validators validates document, its fields but are not tracking amount of documents in the collection. You should rather do something like this:

```js
Meteor.methods({
  '/item/insert': function(doc) {
    if (Collection.find().count() > 5) {
      throw new Meteor.Error('Can not insert more than 5 documents');
    }
  }
});
```

The first problem with implementing it as validator would be decision about the field given validator should be assigned to. Which one? It's more like "document validator" not "field validator". I'm not planning to introduce "document validators". At least right now.

If it goes about direct collection access and validation. I'm working right now on it. It looks like follows:

```js
Item.insert(); // Direct access with type casting and all benefits of Astronomy

Item.validateAndInsert(); // Validate document and insert if validation passes.
```

The same will be true if it goes about other methods: `update`, `upsert`, `remove`. I don't know yet how validation errors will be retrieved.

**Comment by ezpub** [comment]
Yes, the validation is on a document level, so you mean `beforesave` is meant for any actions I want to do to a field before saving, it's not meant to add document level validation?

and for the direct collection access, I'm more concerned about this, it's good to know you are working on it, when do you think you will finish? I'm assuming (I hope not) I'll need to create meteor methods like your example for all my defined Astro classes/Collections in order to have Astro benefits?

**Comment by jagi** [comment]
Of course you can use events for whatever purpose you have however it's not a good programming practice, IMHO. I was always doing it the way I've presented it.

It if goes about Meteor methods, I think that it's much better to implement as many things as possible as Meteor methods. It separates logic into atomic operations, thanks to that you can avoid many errors. It's really hard to keep track of all operations in allow/deny rules if you would ever want to use them.

About direct collection access, I think it will take me couple weeks to implement. I've decided that after that one and few minor features I will move Astronomy into pre 1.0 release phase. It's time to finish this project and move on with extra features and modules.

**Comment by ezpub** [comment]
Okay, thanks for your good work. I really like the way how Astronomy works. It's awesome!  :-)

**Comment by jagi** [comment]
No problem :-). Thanks :-)
