### ISSUE TITLE
Filtering in Astronomy

### ISSUE THREAD

**Issue by andrerfneves** [jagi/meteor-astronomy#86]
@jagi, this isn't an issue per se, so feel free to close the issue and disregard. But I was wondering if you could go over a little issue I'm having. I need to create some sort of filtering/sorting functionality upon documents (sorting by specific fields from the documents). Would my best bet be working with a query helper that uses a Session variable that changes reactively, or is there a better way to get around this with some Astronomy underlining?

Thanks in advance

**Comment by jagi** [comment]
Yes it's definitely not something related with astronomy :). I would definitely do it using the Session variable. Template helpers are reactive, so changing the session variable will update template.

```js
Template.Posts.helpers({
  posts: function() {
    var options = {sort: {}};
    options.sort[Session.get('sortBy')] = Session.get('sortOrder');
    return Posts.find({}, options);
  }
});
```

**Comment by andrerfneves** [comment]
Perfect. Thanks @jagi. Just wanted to make sure I was coding in a manner that is ok with the Astronomy layer. Cheers!
