### ISSUE TITLE
beforeremove/afterremove: 'this' only has _id

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#87]
I'm performing some functions using the beforeremove (I was actually using afterremove, but beforeremove is easier to debug). If I have the following:
````javascript
beforeremove: function(){
    console.log(this);
}
````
I get a mostly empty document with only the _id. Is this how it is supposed to work? I assume I should be able to get the rest of the object? It clearly has more fields with data, they show as null.

**Comment by jagi** [comment]
Yes it has. However you have to know that when using the console.log(object) you're using a reference to the object. Because of that when you investigate the object in the console it doesn't have a state from the moment you printed it to the console. Instead, it has a star from the moment you're investigating it, so the object does not exist. You have to do something like this:

```js
console.log(EJSON.stringify(this.get()));
```

Or any other technic that would convert a reference to the string. If you don't want to do that, it's better to use chrome debugger and set breakpoints.

**Comment by JulianKingman** [comment]
Using the chrome inspector it allows me to read the whole object. Here's are results from using 'this' in beforeremove vs find from the inspector:

console.log(this):
![this](https://cloud.githubusercontent.com/assets/1566400/9632723/e88e174c-5156-11e5-95ed-da77504eb847.png)

console.log(Links.findOne({_id: id})) from chrome console:
![chromeconsole](https://cloud.githubusercontent.com/assets/1566400/9632741/017bdadc-5157-11e5-98ea-eae2fccd724e.png)

As you can see, the _id is returned in both cases, however in the first all fields are null except the _id. So for instance if I try to use this.url it returns undefined, where in other event scripts that sort of use works just fine.

**Comment by jagi** [comment]
It's strange. I've made a test. My class:

```js
Posts = new Mongo.Collection('posts');
Post = Astro.Class({
  name: 'Post',
  collection: Posts,
  fields: {
    a: 'string',
    b: 'string'
  },
  events: {
    beforeremove: function() {
      console.log(this);
    }
  }
});
```

And the console output

![beforeremove](https://cloud.githubusercontent.com/assets/1051229/9634044/1f988f5e-5190-11e5-8be0-41cefcee74b2.png)

Could you create a reproduction repository?

**Comment by JulianKingman** [comment]
OK, I figured it out. In my file I was using this snipped:
````javascript
(new Link({_id:this._id})).remove()
````
I got the idea from here: https://github.com/jagi/meteor-astronomy/issues/25
I'm still not sure why 'this' doesn't return the entire object in this case, but I changed it to the normal remove syntax and it's working now, so problem solved :)

**Comment by jagi** [comment]
It's because, the `new Link({_id: this._id});` does not fetch a document from the database. You have to do `Links.findOne(this._id).remove();`
