### ISSUE TITLE
Meteor.users access permissions

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#88]
It seems that the Meteor.users collection has special permissions that can only (as far as I can tell) be performed through a server method. For instance the following would give an 'access denied' message:

````javascript
var user = Meteor.users.findOne({_id: someid});
user.set('profile.fullname', 'Bruce Wayne');
user.save()
````

**Comment by jagi** [comment]
Hmm it may be possible, I haven't been testing it. But saving a document using `user.save()` function on the client would send it to the server and go through allow/deny rules. So maybe there is some kind of allow/deny rule that prevents it.

However, it's a good idea for security reason to send an astronomy document to the server using Meteor methods.

```js
var user = Meteor.users.findOne({_id: 'someid'});
user.set('profile.fullname', 'Bruce Wayne');

Meteor.call('/user/updateProfile', user);

Meteor.methods({
  '/user/updateProfile': function(user) {
    if (user.validate()) {
      user.save();
      return user;
    }

    user.throwValidationException();
  }
});
```

**Comment by JulianKingman** [comment]
I think there are built-in allow/deny rules for user accounts. It would be nice if it could work as normal, or if it was mentioned in the documentation since it seems to be put in place for security. Thanks for your suggestion.

**Comment by jagi** [comment]
It's strange. I've made a test. My class:

```js
Posts = new Mongo.Collection('posts');
Post = Astro.Class({
  name: 'Post',
  collection: Posts,
  fields: {
    a: 'string',
    b: 'string'
  },
  events: {
    beforeremove: function() {
      console.log(this);
    }
  }
});
```

And the console output

![beforeremove](https://cloud.githubusercontent.com/assets/1051229/9634044/1f988f5e-5190-11e5-8be0-41cefcee74b2.png)

Could you create a reproduction repository?

**Comment by jagi** [comment]
Yes, maybe they should provide such information in the documentation. But, even though they have a lot of work to do. They can't do everything :). Maybe you should ask on Meteor's github repository? Or on Meteor's forum.

**Comment by andrerfneves** [comment]
I have a Meteor.Method that gets called from the client with a Meteor.call and it affects changes onto the user document successfully. Remember to make the Users Collection an Astro collection as well.

Like so:
```javascript
User = Astro.Class({
    name: 'User',
    collection: Meteor.users,
    fields: {
        emails: 'array',
        profile: 'object',
        roles: 'array',
        services: 'object',
        preferences: 'object',
    }
});
```

**Comment by jagi** [comment]
So, maybe you have some error in your code. It would be nice if you could create reproduction repository, so we would be able to test it out and help you.

**Comment by JulianKingman** [comment]
Huh, and you can update all of those fields, even the ones not in ‘profile’?


On September 3, 2015 at 2:28:53 PM, jagi (notifications@github.com) wrote:

So, maybe you have some error in your code. It would be nice if you could create reproduction repository, so we would be able to test it out and help you.

**Comment by jagi** [comment]
@andrerfneves I don't have time to make test right now so could you confirm that you can edit the `profile` from the client, without having the `insecure` package?

**Comment by andrerfneves** [comment]
@jagi @JulianKingman Sorry for the delay. But yes I can edit the profile from the client without having the insecure package. I definitely can make changes to the 'profile' in the user. I'm about to write our User Settings page, and that'll deal with the 'preferences' field in the User object. I believe it'll work out just fine.

**Comment by jagi** [comment]
@andrerfneves thanks! Ok so @JulianKingman you are probably doing something wrong. Check it out again. Maybe you missed something.
