### ISSUE TITLE
Question: How to set conditions for saving a document?

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#89]
I'm discovering the joys of the astronomy events, and there are some functions that I want to take place for a collection before inserting it and after removing it, involving automatically linking and unlinking it to documents in other collections. What I'm running into, though, is that with the beforeinsert function, I want to prevent the insertion of the document in certain scenarios and take another action instead (basically, I want documents to be unique based on a certain field, and if it isn't unique, to add a related document ID to the unique document's foreign key array). I've got everything working, except the prevention of creating a new document. My assumption was that ````return false;```` would stop the document from being created, but it didn't work like that, so I'm wondering if I'm doing it wrong.

**Comment by JulianKingman** [comment]
In reviewing the validation wiki, it looks like it may be a job for validators. I know the validationerror event is probably meant for logging messages, but does it work just as any other function, like could I put the function to update the unique document into the event function?

**Comment by shadowRR** [comment]
I'm not sure this is what you want (maybe you could post some code example ?). But from what i gathered in the code, there's a property in the event that can provide you with what you need:
```
// If user prevented default operation, then we have to stop here.
    if (event.defaultPrevented) {
      return;
    }
```

So, test something like this:

```
events: {
        beforeinsert: function(e) {
            // do here what you already do
           // and if false, return this
           e.defaultPrevented = true
           return;
        }
}
```
It should work.

**Comment by jagi** [comment]
@shadowRR you are right but I shouldn't directly access the `defaultPrevented` property. There is the `e.preventDefault()` function that does the job. There is entire section about events propagation: https://github.com/jagi/meteor-astronomy#events-propagation

@JulianKingman so it's the method that you're probably looking for.

**Comment by JulianKingman** [comment]
@jagi and @shadowRR OK, I've got it working, thanks for your help. For future reference, do you think it would be more logical to use validators, or is this the best approach? 

Here's my code, if anyone else should be interested in doing the same. Links and fragments are related, one fragment can have many links, and if duplicate links are added it should update the existing link, not create a new one, as well as update the fragment so references are stored in both documents.

````javascript
    beforeinsert: function(e){
      //a potentially new fragment to relate to it
      var fragments = Fragments.find({_id: {$in: this.fragmentId}});
      var status = this.status;
      var notes = this.notes;
      //find the link based on URL
      var foundLink = Links.findOne({url: this.url});
      //if the URL already exists, then...
      if(typeof foundLink !== 'undefined'){
        //for each related fragment
        fragments.forEach(function(fragment, i){
          //make sure the existing link has all the fragment _ids, and set some fields
          foundLink.set({
            fragmentId: _.union(foundLink.fragmentId, fragment._id),
            status: _.union(foundLink.status, status),
            notes: notes + foundLink.notes
          });
          foundLink.save();
          //make sure all the fragments are related to the link
          fragment.set({links: _.union(fragment.links, foundLink._id)});
          fragment.save();
          //don't insert the link
          e.preventDefault();
        });
      }
    },
````

**Comment by shadowRR** [comment]
@jagi I thougth the `e.preventDefault()` was only there to prevent triggering an other events of the same type, and not to stop everything else from happening (which doesn't makes much sense now that i'm saying it out loud).

@JulianKingman I would do it the same way has you did. For me, changing data doesn't have it's place in a validator. It's only to check the data is valid or the action is correct. Now every case has a different approach, and i'd follow yours on this.

**Comment by jagi** [comment]
@shadowRR events in Astronomy works the same way how they works in HTML5. There are two methods:
- `e.preventDefault()` - prevent operation from taking place
- `e.stopPropagation()` - stops any following events of the same type but does not prevent operation

@JulianKingman I think using events for this purpose is correct. Sorry, but I don't have enough time to get familiar with details of your code but it seems to be something that should be implemented in the `relations` package. After Astronomy hit 1.0, I will work on side packages like `forms` and `relations`. Maybe it will make your and other developers lives easier :).

For now I'm closing this issue
