### ISSUE TITLE
Take a look at Orion 

### ISSUE THREAD

**Issue by timfam** [jagi/meteor-astronomy#9]
@jagi 
We can team together instead of re-inventing the wheel. Great work though!
https://github.com/orionjs
http://orionjs.org/

**Comment by jagi** [comment]
I'm opened to any suggestions. On what level would you like to cooperate?

**Comment by timfam** [comment]
We want Meteor to have  a rock solid enterprise grade backend blah blah :) we know for this to happen means code + documentation + tutorials + support this requires a team. So I suggest we bring you in as part of the core-team of Orion we extend it to meet your goals. win-win for everyone including the community

**Comment by jagi** [comment]
I don't know if I would have time to work on another project. I work on Meteor Astronomy after my daily job and it's consuming almost all my free time, so you have to understand. I see that you have right now support of simple-schema package and that Orion is modular. Would you like me to integrate Meteor Astronomy with Orion or what?

**Comment by timfam** [comment]
I want us to all work less. Only way to do that is as a team. Astronomy has many good parts Orion can use and it can be gradually integrated. Orion had to be rewritten from grounds up a few weeks ago to make it modular and extendable. Meteor Kitchen/ famous-views and as many others as I can get to come around are all moving to make Orion their default backend. We have the same goal. Lets make something great!

**Comment by dandv** [comment]
Hey Tim,

I would help establish leadership and credibility if you had a real(-looking) name and avatar here on GitHub.

Good luck with the effort!

**Comment by dandv** [comment]
Same for @jagi aka Łukasz Jagodziński.

**Comment by timfam** [comment]
@dandv I hear you :)

**Comment by dandv** [comment]
@timfam: Much better... hopefully in the near future ;-P

**Comment by timfam** [comment]
@dandv I digress but that is from atlas shrugged you know what it means ;) . @jagi  keep up the good work

**Comment by dandv** [comment]
@timfam: I've [read the book](http://www.librarything.com/catalog/dandv&deepsearch=atlas), [know the philosophy](http://wiki.dandascalescu.com/essays/the-case-against-the-unregulated-free-market), and also one of its major failings: understanding that humans are Predictably Irrational.

In this particular case, have a look at [Microsoft's and CMU's research on avatar credibility](http://research.microsoft.com/pubs/155374/tweet_credibility_cscw2012.pdf):

> Features associated with low credibility perceptions were the use of non-standard grammar and
punctuation, not replacing the default account image, or using a cartoon or avatar as an account image

Anyway, who am I to tell you what avatar to use? I'm just saying that there are consequences you may or may not be aware of.

**Comment by timfam** [comment]
@dandv  there are no contradictions maybe I don't have anything to gain from avatar or have gained more from the one I used. Trust me I have been on this planet long enough to see things for what they are. Btw  the book is about what ought to be and why logic must prevail. To be human is to aspire, thrive and achieve, not to be miserable and irrational. The lower state is for animals, humanity is something we all must attain and work hard to maintain. It is an achievement of the rational mind not a gift of nature. You and I  must have a private chat someday :). @jagi  thanks for bearing with us.

**Comment by jagi** [comment]
Hehe :) disussion is thriving :P.
I can say that version 1.0.0 of Astronomy is almost there. And that will be the time to start integration with Orion CMS and create Forms package. However we can start working on the integration right now.

**Comment by timfam** [comment]
This is awesome news! However I think we should wait for v1 to be out and I can have the team take a look together and see how integration will work

**Comment by jagi** [comment]
Ok sounds reasonable:-)

**Comment by jagi** [comment]
Hmm I'm so busy developing Astronomy that I won't have time to work on Orion integration. However, I would be glad if someone could work on it instead of me. As Astronomy is now in 1.0 version, maybe it's good time to investigate it, if there is a demand for such integration.
