### ISSUE TITLE
So sorry I don't know this... :)

### ISSUE THREAD

**Issue by bensmeets** [jagi/meteor-astronomy#93]
But am curious about trying out the current "dev" or "nested" version, but have no idea how to do that in my current project. Is there a way to point my "packages" to the dev and use that instead of the latest released version?

Cheers

**Comment by shadowRR** [comment]
I don't think you can do this from atmosphere packages... But it should be possible to do it manually by cloning the `nested` branches of the repo, and loading the files into you're project. Now, @jagi said the new version should be out in beta in the next two weeks so...

**Comment by jagi** [comment]
Yes it's possible.

- Create packages directory:
```sh
cd workspace
mkdir packages
```
- Clone Astronomy repository:
```sh
cd packages
git clone https://github.com/jagi/meteor-astronomy.git
```
- Swich to `nested` branch as @shadowRR said
```sh
cd meteor-astronomy
git checkout nested
```
- Add `PACKAGE_DIRS` environment variable (of course replace `jagi` with your user name).
```sh
PACKAGE_DIRS="/home/jagi/workspace/packages"
```

The last one you should add to the `.bashrc` file to run it at the system start.
```sh
export PACKAGE_DIRS="/home/jagi/workspace/packages"
```

**Comment by bensmeets** [comment]
Thanks, that got me up and running. Curious to find out more about Astronomy, thanks for all the effort!
