### ISSUE TITLE
Auto increment field

### ISSUE THREAD

**Issue by jagi** [jagi/meteor-astronomy#94]
Hi all, Yesterday I received question about auto increment field and how to implement it using Astronomy. There is a page on MongoDB website where we can find the instruction on how to do it http://docs.mongodb.org/master/tutorial/create-an-auto-incrementing-field/

As you can see it's not so trivial like in SQL databases. I will think about incorporating it into Astronomy as a built in core feature. However for every one who would like to use a workaround, here is a gist https://gist.github.com/jagi/32d834053620f0b71397 showing how to do it right now.

**Comment by frabrunelle** [comment]
Thank you, that's really useful!

I need this in my app for saving customer numbers and order numbers.

Right now my code looks like:

```javascript
Meteor.methods({
  'saveCustomer': function (customer) {
    return manageSequenceFieldOnSave(customer, 'customerNumber');
  },
  'saveOrder': function (order) {
    return manageSequenceFieldOnSave(order, 'orderNumber');
  }
});
```

```javascript
manageSequenceFieldOnSave = function(doc, fieldName) {
  if (doc.validate()) {
    if (doc._isNew) {
      return autoIncrementOnInsert(doc, fieldName);
    } else {
      doc.save();
      return doc;
    }
  }

  doc.throwValidationException();
};
```

```javascript
autoIncrementOnInsert = function(doc, fieldName) {
  while (true) {
    var Class = doc.constructor;
    var Collection = Class.getCollection();

    var sort = {};
    var fields = {};
    sort[fieldName] = -1;
    fields[fieldName] = 1;

    var max = Collection.findOne({}, {
      sort: sort,
      fields: fields,
      transform: null
    })[fieldName];

    var next = max + 1;

    try {

      doc.set(fieldName, next);
      doc.save();
      break;

    } catch (e) {
      console.log(e)
      if (e.name === 'MongoError' && e.code === 11000) {
        continue;
      }

    }
  }
  return doc;
};
```

It works, but I wish it was built-in or at least easy to add via a package.

I'm thinking that it should be implemented as a behavior. It makes me think of the timestamp behavior. For timestamp, we set the value of `createdAt` and `updatedAt` fields, in this case we set the value of a field that autoincrements.

It could be called `meteor-astronomy-autoincrement-behavior` maybe.

```javascript
behaviors: {
  autoincrement: {
    // The field name that should be increment.
    incrementFieldName: 'orderNumber',
    // The value at which the counter will start incrementing
    initalValue: 1000
  }
}
```

Anyways, this is not urgent at all and could be done once there are more people who want this feature.

Thank you :smile:

**Comment by jagi** [comment]
Yes, probably it could be done as a behavior however there is a problem because we need to catch Mongo exception on a document save. It could be done using several solutions but all of them are not good :)

- New method on a document that would call save method
```js
doc.incSave = function() {
  try {
    this.save();
  } catch(e) { /* ... */ }
}
```
- Catching error inside the `save` method by Astronomy
```js
doc.save = function() {
  try {
    Collection.insert(/* ... */);
  } catch(e) {
    Class.emitEvent('saveError', e);
  }
}
```
In this case the behavior creator would be responsible for handling the `saveError` event in which he/she should call the save method again until the auto increment field was filled properly. If there is no `saveEvent` handler then the exception object would be thrown again.

The second approach seeps to be more complex but also more flexible. It's definitely something that will be added after 1.0.0 and should be implemented as a behavior.

**Comment by frabrunelle** [comment]
Very nice! :+1: for the second approach :smile: 

> It's definitely something that will be added after 1.0.0 and should be implemented as a behavior.

Excellent!

**Comment by SenerDemiral** [comment]
AutoIncrementing should be on Server side.
In dedicated mongo collection on server only (GENID)
Put one record for each sequence, _id: sequenceName
Increment this record and use.

```
GenId = function () {
  var rawCollection = GENID.rawCollection();
  var rawFaM = Async.runSync(function(done) {
    rawCollection.findAndModify(
      {_id: "1"},
      {},
      {'$inc': {seq: 1}},
      {new: true, upsert: true},
      function(err, data) {
        done(err, data);
    });
  });

  // Use one of them
  return rawFaM.result.seq.toString();		// Return 10base string
  return rawFaM.result.seq.toString(36);	// Return 36base string
}
```
Usage
```
  xxx._id = GenId();
```

**Comment by jagi** [comment]
It's not required to use a separate Mongo collection. If it goes about server only generation - yes it's required but can also be simulated on the client in a stub. Thanks to Meteor, a client simulation will be replaced with the proper value from the server, when the response come back.

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.

**Comment by willrbc** [comment]
Hi Jagi,

I know this is closed but I wanted to ask a question about the suggested implementation and the mongo exception.

I'm not sure I understand why there is potentially an exception error?  I'm using auto increment for 'job number' but this field in not going to be used as a unique ID field or index.  In fact there may be different versions of the 'JOB' with the same number but different 'version' numbers. (Also as my system is multi-tenant, there will be other 'jobs' belong to different tenants with the same number)

I've written a behavior that does a simple lookup to find the top 'jobNumber' and increment it by one before saving the document by using the 'beforeInsert' event handler.

However, I still need to ensure jobs saved simultaneously don't have the same job number in that one tenant. I imagine it is possible for there to be duplicates in this scenario, although potentially unlikely?

Do you have any thoughts on this?  And Merry Christmas :)

**Comment by jagi** [comment]
I think using mongo exception for auto incrementing was not good idea. In Astronomy 2.0 I'm going to use [`usefulio:atomic-counter`](https://atmospherejs.com/usefulio/atomic-counter) package or maybe I will integrate it into Astronomy somehow - we will see. It does it's job, it's easy to use and does not require any "hacky" solutions.

Marry Christmas :)

**Comment by willrbc** [comment]
Interesting,  will look into that, although I can't find the docs / readme, I'm guessing it's quite new?  I can't find it on their GitHub account either.

**Comment by jagi** [comment]
You can find docs/readme on GitHub here: https://github.com/usefulio/meteor-mongo-counter/

**Comment by danpilat** [comment]
Hi Jagi, 

I know this is closed, but was wondering if you've made any progress on adding an autoincrement behaviour to v2. I can't find much about it. If not, what would be the suggested approach - the one you posted 8 months ago - would it still be valid? 

Thanks!
Dan.

**Comment by lukejagodzinski** [comment]
@danpilat the best way of adding an autoincrement feature would be using this approach https://github.com/usefulio/meteor-mongo-counter/. You can also try incrementing value in the callback function and saving document one more time if there is an unique index on a field.

``` js
doc.save(function(err, result) {
  if (err.name === 'MongoError' && err.code === 11000) {
    doc.number++;
  }
});
```

or on the server

``` js
try {
  doc.save();
}
catch (err) {
  if (err.name === 'MongoError' && err.code === 11000) {
    doc.number++;
  }
}
```

In theory it should work but I haven't tested it. Anyway I think that the first solution is the best one.
