### ISSUE TITLE
doc.reload() should not empty an instance if the document is not found in the collection

### ISSUE THREAD

**Issue by cwohlman** [jagi/meteor-astronomy#95]
If a document is removed from the collection (either explicitly, or because a subscription was stopped), calling doc.reload() will null all of the fields in the doc (including the id field), which I don't think should be the expected behavior.

I ran into this as I was trying to implement an 'undo remove' feature, I expected to be able to call `.remove()`, and later to be able to call `.save()` to re-insert the document, however this didn't work because some intervening code had called `.reload()` which emptied the document of values.

I believe what we need is a null check before this line: https://github.com/jagi/meteor-astronomy/blob/e22b4a3d47a7464647050edbc292651d1771673c/lib/modules/fields/init_module.js#L336

I'd be happy to submit a PR if you think that this is a good idea.

**Comment by jagi** [comment]
So, it's your code that is calling the `reoad()` method under way between the `remove()` and `save()` methods? Because astronomy does not use the `reload()`method internally. I can make this check if you want. However I will do it for 1.0 version because I'm releasing alpha version tomorrow or the day after tomorrow.

**Comment by cwohlman** [comment]
Yes, it was my code that was calling `reload()`. I also had this issue when I tried to access the doc in a callback, I called `reload()` in the callback, but because the user had changed routes the doc was no longer in the client cache.

I'm not 100% sure what the expected behavior should be, but definitely silent nulling of fields was a little unexpected. I suggest we either throw an error, or do nothing if the document does not exist in the collection.

**Comment by jagi** [comment]
However, if you want to implement undo remove behavior you should rather use softremove behavior. It will not remove your document fromthe database, but rather flag it as soft removed. Later you can set the flag to false to undo remove.

**Comment by cwohlman** [comment]
That's actually what I was doing, but I only subscribe to documents which do not have the `__removed` flag, so once I softRemove the doc it no longer exists in the client cache. The work around is fairly simple, I just cache the `_id` of the doc in a variable, but it would be nice if that wasn't necessary.

**Comment by jagi** [comment]
Oh I see. You could always subscribe to all document also with the `_removed` flag set to true and on the client display only those with the `_removed` flag set to false or null.

```js
// On the client
var items = Items.find({
  removed: {
    $ne: true
  }
});
```

However, your solution with storing `_id` is also good. But still don't know why it's happening. I don't see any problem with the code. The `reload()` method should not clear any field if the document does not exist. I will make test.

**Comment by jagi** [comment]
This feature should work as expected in the 1.0.0 RC version https://github.com/jagi/meteor-astronomy/issues/97 I'm planning a release of 1.0.0 version for the next week.

**Comment by cwohlman** [comment]
Thanks!



—
