### ISSUE TITLE
_type for parent is always Child _type

### ISSUE THREAD

**Issue by matikucharski** [jagi/meteor-astronomy#96]
It looks like your `getDefaultValue` method in /lib/modules/fields/utils.js returns child _type if document itself don't have one.
In my case I have several documents in `Documents` collection some of them are Parents some of them were created as Children. But when I do `Documents.find().fetch()` all documents have `_type: 'Children'`

**Comment by matikucharski** [comment]
Now I see there is wrong transform called on Collection find. It is called as Child but this should be Parent transform function

**Comment by matikucharski** [comment]
How do you know if fetched document should be parent or child type?
I can see you have 
```
if (schemaDefinition.transform) {
      this.collection._transform = LocalCollection.wrapTransform(
        Astro.utils.class.transform(this.className)
      );
}
```
in schema.js.
But it looks like if Parent and Child shares the same collection the last one transform function is added permanently for collection that is shared by those two classes

**Comment by jagi** [comment]
Hi, are you using custom transform function?
Right now I'm working on 1.0 pre release version of Astronomy and I hope that it will be available tomorrow. A lot of things have changed, the same is true about inheritance and transform function. You probably should wait for new version. However, I would like to know what is your use case and if you are using custom transform function.

**Comment by matikucharski** [comment]
Hi, No I'm not using any custom transform functions. Good to hear about 1.0 :)

**Comment by jagi** [comment]
Hmm so it should work out of the box. Show me your code. How are you inserting instances of different classes and how are you fetching them.

**Comment by matikucharski** [comment]
Here is my code example - nothing special:
```js
CD.models.Document = Astro.Class({
    name: 'Document',
    collection: Documents,
    fields: {
        name: 'string',
        slug: 'string',
        docType: 'string',
        docNotes: 'string',
        showId: 'string',
        uploadId: 'string',
        dateCreated: 'date',
        userId: 'string'
    }
});

CD.models.DocumentBudget = CD.models.Document.extend({
    name: 'DocumentBudget',
    fields: {
        atl: 'number',
        btl: 'number',
        costs: 'number',
        totalGross: 'number'
    }
});
```

I use `new CD.models.Document()` or `new CD.models.DocumentBudget()`  and then `save()` it to create document.

But when I do `Documents.find().fetch()` I can see all fetched documents have 
`_type: 'DocumentBudget'`
no matter if they were created as `new CD.models.Document()` or `new CD.models.DocumentBudget()`

**Comment by jagi** [comment]
Please try testing RC version https://github.com/jagi/meteor-astronomy/issues/97
It would be nice if you could create a reproduction repository so I would be able to tell if an error is on the Astronomy side.

**Comment by matikucharski** [comment]
I tested it with 1.0 version and it works here:) Thanks:)

**Comment by jagi** [comment]
Good to hear :)
