### ISSUE TITLE
Testing 1.0.0-rc.6 version

### ISSUE THREAD

**Issue by jagi** [jagi/meteor-astronomy#97]
Hi everyone,
The time has come, 1.0.0 is around the corner :). I would like to invite everyone to test a new version. It introduced so many changes that your currently existing projects many not work properly. You may need to make some changes. Ok, but how to test this release?

1) At first, you have to remove all astronomy packages from your project (you have to do it because there are changes in dependencies' versions):
```sh
meteor remove jagi:astronomy
meteor remove jagi:astronomy-validators
meteor remove jagi:astronomy-simple-validators
meteor remove jagi:astronomy-timestamp-behavior
meteor remove jagi:astronomy-softremove-behavior
meteor remove jagi:astronomy-slug-behavior
```

etc.

2) Next, you have to add these packages back but now with specified versions.
```sh
# NOTICE! Take a look at different version numbers
meteor add jagi:astronomy@1.0.0-rc.6
meteor add jagi:astronomy-validators@1.0.0-rc.4
meteor add jagi:astronomy-simple-validators@1.0.0-rc.2
meteor add jagi:astronomy-timestamp-behavior@1.0.0-rc.1
meteor add jagi:astronomy-softremove-behavior@1.0.0-rc.1
meteor add jagi:astronomy-slug-behavior@1.0.0-rc.2
```

That's it. You are ready to test.

**IMPORTANT!**
There is no guide on moving to 1.0.0-rc.6 yet, but I'm working on the documentation that you can find under this address: http://astronomy.meteor.com
It's in a very early stage so forgive me its poor quality.

**NOTICE**
The `jagi:astronomy-behaviors` package will be deprecated because it was included in the core Astronomy package. So, there is no RC version of the behaviors package.

**Let's start testing :)**

**Comment by shadowRR** [comment]
Awesome @jagi . Will start testing this tomorrow ;)

**Comment by andrerfneves** [comment]
Awesome!. I won't push to my production app yet but will test this on a side project and see the difference. Thanks for the hard work @jagi!

**Comment by laurentpayot** [comment]
Amazing worg @jagi! 
I'm doing the switch. Could you update the changelog to be sure that we won't miss anything new?

**Comment by jagi** [comment]
@laurentpayot Yes, right I will update it today :)

**Comment by jagi** [comment]
I've added some change logs in the documentation for now: http://astronomy.meteor.com/#changelog
It's not very detailed but I will update it later today.

**Comment by laurentpayot** [comment]
Thanks @jagi :+1:

**Comment by laurentpayot** [comment]
Well in 1.0 there's "a new way of inheriting from a class" but this new way is not documented and I couldn't find the difference way from the commits. So for now I'm stuck because I can't create inherited classes and that's what I'm using the most. @jagi could you give us an example of this "new way of inheriting from a class"?

**Comment by laurentpayot** [comment]
Also I have a <code>tags</code> field that is an array of plain values (strings) like this:
<pre>
'tags': {
  index: true,
  type: 'array',
  nested: 'string',
  default: function() {return [];},
  validators: [V.required(), V.array(), V.maxLength(100)]
}
</pre>

But validation only checks if my tags are strings. Is there a way to check if all my tags strings are between 2 and 20 characters long without the hassle of defining a new nested class "tag" and an unnecessary complex array of these "tag" objects?

**Comment by jagi** [comment]
@laurentpayot I will update info about inheritance in a moment.

If it goes about validation of nested fields of plain type you have to use the `each` validator.

```js
'tags': {
  index: true,
  type: 'array',
  nested: 'string',
  default: function() {return [];},
  validator: V.each(
    V.and(V.required(), V.array(), V.maxLength(100))
  )
}
```

Notice also that the property name in the field's definition is `validator` not `validators` because it's validator for ONE field. However, on the level of class schema you have the `validators` property because you define validators for MANY fields.

**Comment by jagi** [comment]
I've updated the [Inheritance](http://astronomy.meteor.com/#inheritance) section. I've also published 1.0.0-rc.2 version that fixes some bugs.

**Comment by bensmeets** [comment]
Is relations a part of 1.0 as well? Or is that something seperate?

**Comment by jagi** [comment]
Relations module is still in an experimental phase and I will be working on it after release of Astronomy 1.0.0

**Comment by jagi** [comment]
I've found an error in documents EJSONification. Because of that error it is not possible to send over a DDP documents with nested fields. I will publish the 1.0.0-rc.3 version because it's a serious bug.

**Comment by jagi** [comment]
You can also checkout example app built with 1.0.0-rc.3 here https://github.com/jagi/meteor-astronomy-examples/tree/nested

**Comment by andrerfneves** [comment]
Having this issue while trying to install rc3 @jagi 

```bash
 meteor add jagi:astronomy-validators@1.0.0-rc.3

 => Errors while parsing arguments:

While adding package jagi:astronomy-validators@1.0.0-rc.3:
error: no such version jagi:astronomy-validators@1.0.0-rc.3
```

**Comment by frabrunelle** [comment]
@andrerfneves `jagi:astronomy-validators` is still at 1.0.0-rc.1. Same thing for slug and timestamp behaviors.

**Comment by andrerfneves** [comment]
@jagi you should correct this in your comment then: 

<img width="624" alt="screen shot 2015-09-20 at 2 39 22 pm" src="https://cloud.githubusercontent.com/assets/2574011/9982322/6fd8ad00-5fa5-11e5-9b66-443fcecfcd46.png">

Thanks @frabrunelle

**Comment by jagi** [comment]
Oh right :) sorry hehe I've just copied rc.3 for every package :) I will fix it

**Comment by laurentpayot** [comment]
Thanks for your reactivity @jagi.
I have created https://github.com/jagi/meteor-astronomy-validators/issues/27 about "each" array validator method.

**Comment by laurentpayot** [comment]
I have also created https://github.com/jagi/meteor-astronomy-slug-behavior/issues/3 about slugs not working anymore.

**Comment by jagi** [comment]
Ok I've answered your questions.

**Comment by jagi** [comment]
In the `Astronomy 1.0.0-rc.5` I've made it compatible with `Meteor 1.2`.

**Comment by andrerfneves** [comment]
Sweet! Thanks @jagi
